# Path router: matches (method, path) against a hand-written route
# table and resolves to (controller_class, action, path_params).
#
# In real-blog this is generated by Rails from `config/routes.rb`'s
# `resources` DSL; in spinel-blog it's a flat data structure (see
# `config/routes.rb`). The eventual transpiler reproduces this shape
# from the DSL declarations.
module Router
  module_function

  # Match a request against the route table. Returns a hash with
  # :controller, :action, :path_params on success; nil otherwise.
  def match(method, path, table)
    method_upcase = method.to_s.upcase
    table.each do |route|
      next unless route[:method] == method_upcase
      params = match_pattern(route[:pattern], path)
      next if params.nil?
      return {
        controller: route[:controller],
        action:     route[:action],
        path_params: params,
      }
    end
    nil
  end

  # Match a path against a pattern containing `:name` segments.
  # Returns a Hash[Symbol => String] of captured params, or nil if
  # the pattern doesn't match. No regex; segment-by-segment compare.
  def match_pattern(pattern, path)
    pattern_parts = pattern.split("/")
    path_parts    = path.split("/")
    return nil if pattern_parts.length != path_parts.length
    params = {}
    i = 0
    while i < pattern_parts.length
      pp = pattern_parts[i]
      ap = path_parts[i]
      if pp.start_with?(":")
        params[pp[1..].to_sym] = ap
      elsif pp != ap
        return nil
      end
      i += 1
    end
    params
  end
end
