module ActiveSupport
  def self.blank?: (untyped value) -> bool

  def self.present?: (untyped value) -> bool

  def self.presence: (untyped value) -> untyped
  def self.presence_in: (untyped value, Array[String] list) -> untyped
end
