// Generated by `cargo run --bin runtime_transpile_ts` from runtime/ruby/action_controller/base.rb.
// Do not edit by hand — edit the source `.rb` and re-run.

export class Base {
  params: Parameters;
  session: Record<string, any>;
  flash: Record<string, any>;
  request_method: string;
  request_path: string;
  status: number;
  body: string;
  location: any;

  constructor() {
    this.params = ActionController.Parameters.new({  });
    this.session = {  };
    this.flash = {  };
    this.status = 200;
    this.body = "";
    this.location = null;
  }

  process_action(_action_name: string): void {
    (() => { throw new Error("process_action must be overridden by subclass"); })();
  }

  render(html: string, status?: any): void {
    this.body = html;
    this.status = this.resolve_status(status);
    null;
  }

  redirect_to(path: string, notice?: any, alert?: any, status?: any): void {
    this.location = path;
    this.status = this.resolve_status(status);
    if (notice === null) { null; } else { this.flash["notice"] = notice; }
    if (alert === null) { null; } else { this.flash["alert"] = alert; }
    null;
  }

  head(status: any): void {
    this.status = this.resolve_status(status);
    this.body = "";
    null;
  }

  resolve_status(s: any): number {
    if (Number.isInteger(s)) return s;
    return STATUS_CODES.fetch(s, 200);
  }
}
