// Generated by `cargo run --bin runtime_transpile_ts` from runtime/ruby/action_view/route_helpers.rb.
// Do not edit by hand — edit the source `.rb` and re-run.

export class RouteHelpers {
  articles_path(): string {
    return "/articles";
  }

  article_path(id: number): string {
    return `/articles/${id}`;
  }

  new_article_path(): string {
    return "/articles/new";
  }

  edit_article_path(id: number): string {
    return `/articles/${id}/edit`;
  }

  article_comments_path(article_id: number): string {
    return `/articles/${article_id}/comments`;
  }

  article_comment_path(article_id: number, id: number): string {
    return `/articles/${article_id}/comments/${id}`;
  }

  new_article_comment_path(article_id: number): string {
    return `/articles/${article_id}/comments/new`;
  }

  edit_article_comment_path(article_id: number, id: number): string {
    return `/articles/${article_id}/comments/${id}/edit`;
  }

  root_path(): string {
    return "/";
  }
}
