// Generated by `cargo run --bin runtime_transpile_ts` from runtime/ruby/active_record/validations.rb.
// Do not edit by hand — edit the source `.rb` and re-run.

export class Validations {
  errors(): string[] {
    if (this.errors === null) this.errors = [];
    return this.errors;
  }

  validates_presence_of(attr_name: string, value: any): null {
    let blank = false;
    if (value === null) { blank = true; } else if (value instanceof String && value.empty) { blank = true; } else if (value instanceof Array && value.empty) { blank = true; }
    if (blank) this.errors.push(`${attr_name} can't be blank`);
  }

  validates_absence_of(attr_name: string, value: any): null {
    let present = false;
    if (!(value === null)) if (value instanceof String) { present = !value.empty; } else if (value instanceof Array) { present = !value.empty; } else { present = true; }
    if (present) this.errors.push(`${attr_name} must be blank`);
  }

  validates_length_of(attr_name: string, value: any, minimum: any, maximum: any, is: any): null {
    if (value === null) return;
    const len = value instanceof String || value instanceof Array ? value.length : 0;
    if (!(minimum === null) && (() => { throw new Error("roundhouse: + with incompatible operand types"); })()) this.errors.push(`${attr_name} is too short (minimum is ${minimum})`);
    if (!(maximum === null) && (() => { throw new Error("roundhouse: + with incompatible operand types"); })()) this.errors.push(`${attr_name} is too long (maximum is ${maximum})`);
    if (!(is === null) && len !== is) this.errors.push(`${attr_name} is the wrong length (should be ${is})`);
  }

  validates_numericality_of(attr_name: string, value: any, greater_than: any, less_than: any, only_integer: boolean): null {
    if (value === null || !value instanceof Numeric) this.errors.push(`${attr_name} is not a number`); (() => { return null; })();
    if (!(greater_than === null) && (() => { throw new Error("roundhouse: + with incompatible operand types"); })()) this.errors.push(`${attr_name} must be greater than ${greater_than}`);
    if (!(less_than === null) && (() => { throw new Error("roundhouse: + with incompatible operand types"); })()) this.errors.push(`${attr_name} must be less than ${less_than}`);
    if (only_integer && !value instanceof Integer) this.errors.push(`${attr_name} must be an integer`);
  }

  validates_inclusion_of(attr_name: string, value: any, within: string[]): null {
    if (within.include(value)) return;
    this.errors.push(`${attr_name} is not included in the list`);
  }

  validates_format_of(attr_name: string, value: any, with_: Regexp): null {
    const ok = value instanceof String && with.match(value);
    if (ok) { null; } else { this.errors.push(`${attr_name} is invalid`); }
  }
}
