//! Controllers — Juntos modules of exported async functions.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use super::expr::{emit_expr, emit_send_with_parens};
use crate::App;
use crate::dialect::Controller;
use crate::expr::{Expr, ExprNode, LValue, Literal};
use crate::ident::Symbol;
// Trait import for the controller walker. Used by TsEmitter's
// helper methods to call `self.render_expr(...)` (the trait
// method) from inside inherent-impl code.
use crate::lower::CtrlWalker as _;

// Controllers ----------------------------------------------------------
//
// Juntos controllers are modules of exported async functions, not
// classes. Each action becomes `export async function name(context)`
// (read actions) or `export async function name(context, params)`
// (write actions — `create` / `update`). Rails instance variables
// (`@foo = ...`) rebind to local `let`s; `params[:key]` rewrites to
// `context.params.<key>`. Matches ruby2js's
// `lib/ruby2js/filter/rails/controller.rb` shape.
//
// Phase 4c: action bodies emit through the shared SendKind classifier
// from `lower::controller`. The TS render table handles HTTP surface
// (`render`/`redirectTo`/`head`), `respondTo` block + FormatRouter,
// `params` access, model / association shapes, and the BangStrip
// variant (TS forbids `!` in idents just like Rust and Go).

// `emit_main_ts` and `emit_ts_route_helpers` lifted to dedicated
// `super::main_ts` and `super::route_helpers` modules during the
// rip-and-replace migration. `emit_ts_importmap` stays below.

/// Emit `src/importmap.ts` — the app-specific pin list ingested
/// from `config/importmap.rb` (with `pin_all_from` expanded).
///
/// Shape: `Array<{ name, path }>` — matches the framework Ruby's
/// `Importmap::PINS` (each pin is a hash with `:name` / `:path`
/// keys). The `javascript_importmap_tags` helper consumes this
/// shape directly. The previous tuple form `[string, string][]`
/// required per-helper conversion; the named-field form is
/// uniform with the source.
pub(super) fn emit_ts_importmap(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s).unwrap();
    writeln!(
        s,
        "export const PINS: ReadonlyArray<{{ name: string; path: string }}> = ["
    )
    .unwrap();
    if let Some(importmap) = &app.importmap {
        for pin in &importmap.pins {
            writeln!(
                s,
                "  {{ name: {:?}, path: {:?} }},",
                pin.name, pin.path,
            )
            .unwrap();
        }
    }
    writeln!(s, "];").unwrap();
    EmittedFile {
        path: PathBuf::from("src/importmap.ts"),
        content: s,
    }
}

/// Compose one modifier onto the running TS expression. `all` +
/// no-op modifiers (includes, preload, joins, distinct, select)
/// pass through. `order` appends a `.sort(...)` with a comparator
/// derived from the modifier's `{field: :dir}` hash. Unknown
/// modifiers drop (returning prev unchanged) so the output still
/// compiles — a compare-tool divergence will signal the gap.
///
/// Chain-walk lives in `src/lower/chain.rs`; this fn just renders
/// one already-classified layer.
fn apply_ts_chain_modifier(prev: String, m: crate::lower::ChainModifier<'_>) -> String {
    match m.method {
        "all" | "includes" | "preload" | "joins" | "distinct" | "select" => prev,
        "order" => {
            let Some(hash) = m.args.first() else { return prev };
            let ExprNode::Hash { entries, .. } = &*hash.node else { return prev };
            let Some((k, v)) = entries.first() else { return prev };
            let field = match &*k.node {
                ExprNode::Lit { value: Literal::Sym { value } } => value.as_str().to_string(),
                ExprNode::Lit { value: Literal::Str { value } } => value.clone(),
                _ => return prev,
            };
            let dir = match &*v.node {
                ExprNode::Lit { value: Literal::Sym { value } } => value.as_str().to_string(),
                ExprNode::Lit { value: Literal::Str { value } } => value.clone(),
                _ => "asc".to_string(),
            };
            let cmp = if dir == "desc" {
                format!(
                    "(a: any, b: any) => (a.{field} < b.{field} ? 1 : a.{field} > b.{field} ? -1 : 0)"
                )
            } else {
                format!(
                    "(a: any, b: any) => (a.{field} < b.{field} ? -1 : a.{field} > b.{field} ? 1 : 0)"
                )
            };
            format!("{prev}.sort({cmp})")
        }
        "limit" => {
            let Some(n) = m.args.first() else { return prev };
            if let ExprNode::Lit { value: Literal::Int { value } } = &*n.node {
                return format!("{prev}.slice(0, {value})");
            }
            prev
        }
        _ => prev,
    }
}

pub(super) fn lower_first_char(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) => c.to_ascii_lowercase().to_string() + chars.as_str(),
        None => String::new(),
    }
}


pub(super) fn emit_controllers(
    app: &App,
    adapter: &dyn crate::adapter::DatabaseAdapter,
) -> Vec<EmittedFile> {
    let known_models: Vec<Symbol> =
        app.models.iter().map(|m| m.name.0.clone()).collect();
    app.controllers
        .iter()
        .map(|c| emit_controller_file(c, &known_models, app, adapter))
        .collect()
}

fn emit_controller_file(
    c: &Controller,
    known_models: &[Symbol],
    app: &App,
    adapter: &dyn crate::adapter::DatabaseAdapter,
) -> EmittedFile {
    let name = c.name.0.as_str();
    let file_stem = crate::naming::snake_case(name);
    let resource = crate::lower::resource_from_controller_name(name);
    let model_class = crate::naming::singularize_camelize(&resource);
    let has_model = known_models.iter().any(|m| m.as_str() == model_class);
    let parent = crate::lower::find_nested_parent(app, name);
    let permitted = crate::lower::permitted_fields_for(c, &resource)
        .unwrap_or_else(|| crate::lower::default_permitted_fields(app, &model_class));

    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(
        s,
        "import type {{ ActionContext, ActionResponse }} from \"juntos\";",
    )
    .unwrap();
    if !known_models.is_empty() {
        let model_imports: Vec<String> = known_models
            .iter()
            .map(|m| {
                format!(
                    "import {{ {} }} from \"../models/{}.js\";",
                    m.as_str(),
                    crate::naming::snake_case(m.as_str()),
                )
            })
            .collect();
        for line in model_imports {
            writeln!(s, "{line}").unwrap();
        }
    }
    writeln!(s, "import * as routeHelpers from \"../../src/route_helpers.js\";").unwrap();
    writeln!(s, "import * as Views from \"../views/all.js\";").unwrap();

    let (public_actions, _private) = crate::lower::split_public_private(c);
    for action in &public_actions {
        writeln!(s).unwrap();
        let la = crate::lower::lower_action(
            action.name.as_str(),
            &resource,
            &model_class,
            has_model,
            parent.as_ref(),
            &permitted,
        );
        emit_ts_action(&mut s, &la, &action.body, known_models, c, adapter);
    }

    // Namespace object — same shape as before but only public actions.
    let action_names: Vec<String> = public_actions
        .iter()
        .map(|a| {
            let raw = a.name.as_str();
            if raw == "new" {
                "new: $new".to_string()
            } else {
                raw.to_string()
            }
        })
        .collect();
    if !action_names.is_empty() {
        writeln!(s).unwrap();
        writeln!(
            s,
            "export const {name} = {{ {} }};",
            action_names.join(", ")
        )
        .unwrap();
    }

    EmittedFile {
        path: PathBuf::from(format!("app/controllers/{file_stem}.ts")),
        content: s,
    }
}

/// Render one LoweredAction as a TS `export async function`. Mangles
/// `new` → `$new` (ruby2js convention — `new` is a JS keyword). Uses
/// the `routeHelpers.<name>Path` import for redirect Location URLs.
fn emit_ts_action(
    out: &mut String,
    la: &crate::lower::LoweredAction,
    body: &Expr,
    known_models: &[Symbol],
    controller: &Controller,
    adapter: &dyn crate::adapter::DatabaseAdapter,
) {
    let name = if la.name == "new" { "$new" } else { la.name.as_str() };
    if la.has_model {
        emit_ts_action_via_walker(out, la, body, known_models, controller, name, adapter);
    } else {
        // Actions on controllers with no associated model (e.g.
        // ApplicationController) emit a 200-empty stub; the walker
        // would try to synthesize a view-fn reference that doesn't
        // resolve.
        writeln!(
            out,
            "export async function {name}(_context: ActionContext): Promise<ActionResponse> {{",
        )
        .unwrap();
        writeln!(out, "  return {{ body: \"\" }};").unwrap();
        writeln!(out, "}}").unwrap();
    }
}

/// Run the normalization pipeline + walker for one action body,
/// then write the `export async function …` wrapper. The walker
/// dispatch lives in `src/lower/controller_walk.rs`; this function
/// builds a `TsEmitter` and hands it off.
fn emit_ts_action_via_walker(
    out: &mut String,
    la: &crate::lower::LoweredAction,
    body: &Expr,
    known_models: &[Symbol],
    controller: &Controller,
    name: &str,
    adapter: &dyn crate::adapter::DatabaseAdapter,
) {
    use crate::lower::CtrlWalker;
    let normalized =
        crate::lower::normalize_action_body(controller, la.name.as_str(), body);
    let rewritten = rewrite_for_controller(&normalized);
    let mut emitter = TsEmitter {
        ctx: crate::lower::WalkCtx {
            known_models,
            model_class: la.model_class.as_str(),
            resource: la.resource.as_str(),
            parent: la.parent.as_ref(),
            permitted: &la.permitted,
            adapter,
        },
        state: crate::lower::WalkState::new(),
    };
    let body_src = emitter.walk_action_body(&rewritten);
    // uses_context is set by SendKind arms that render `context.*`,
    // but rewrite_for_controller can also produce `context.params.k`
    // as a plain chained Send that falls through the generic path.
    // Post-scan the body to catch those.
    let uses_context = emitter.state.uses_context || body_src.contains("context.");
    let ctx_param = if uses_context { "context" } else { "_context" };
    writeln!(
        out,
        "export async function {name}({ctx_param}: ActionContext): Promise<ActionResponse> {{",
    )
    .unwrap();
    out.push_str(&body_src);
    writeln!(out, "}}").unwrap();
}

/// TS's controller-body emitter — implements the shared
/// `CtrlWalker` trait with TS-specific render methods.
struct TsEmitter<'a> {
    ctx: crate::lower::WalkCtx<'a>,
    state: crate::lower::WalkState,
}

impl<'a> crate::lower::CtrlWalker<'a> for TsEmitter<'a> {
    fn ctx(&self) -> &crate::lower::WalkCtx<'a> { &self.ctx }
    fn state_mut(&mut self) -> &mut crate::lower::WalkState { &mut self.state }
    fn indent_unit(&self) -> &'static str { "  " }

    fn suspending_prefix(&self) -> &'static str { "await " }

    fn write_assign(&mut self, name: &str, value: &Expr, indent: &str, out: &mut String) {
        // `render_expr` handles the suspending wrap internally
        // when `value` is a Send — compound-shape renders
        // (ModelFind's coalesce) place the `await` at the
        // suspending sub-expression rather than the outer
        // expression. For non-Send RHS shapes, `render_expr`
        // emits the expression as-is; suspension can only arise
        // from Sends in the current IR, so the walker doesn't
        // need to wrap here.
        let rhs = self.render_expr(value);
        writeln!(out, "{indent}const {name} = {rhs};").unwrap();
    }

    fn write_create_expansion(
        &mut self,
        var_name: &str,
        class: &str,
        indent: &str,
        out: &mut String,
    ) {
        writeln!(out, "{indent}const {var_name} = new {class}();").unwrap();
        if let Some(parent) = self.ctx.parent {
            writeln!(
                out,
                "{indent}({var_name} as any).{0}_id = Number(context.params.{0}_id);",
                parent.singular,
            )
            .unwrap();
            self.state.uses_context = true;
        }
        let permitted: Vec<String> = self.ctx.permitted.iter().cloned().collect();
        let resource = self.ctx.resource.to_string();
        for field in &permitted {
            writeln!(
                out,
                "{indent}({var_name} as any).{field} = context.params[\"{resource}[{field}]\"] ?? \"\";",
            )
            .unwrap();
            self.state.uses_context = true;
        }
    }

    fn write_if(
        &mut self,
        cond: &Expr,
        then_branch: &Expr,
        else_branch: &Expr,
        indent: &str,
        depth: usize,
        is_tail: bool,
        out: &mut String,
    ) {
        // render_expr places the suspending-wrap correctly when
        // cond is a Send; no extra wrapping needed here.
        let cond_s = self.render_expr(cond);
        writeln!(out, "{indent}if ({cond_s}) {{").unwrap();
        self.walk_stmt(then_branch, out, depth + 1, is_tail);
        if !crate::lower::is_empty_body(else_branch) {
            writeln!(out, "{indent}}} else {{").unwrap();
            self.walk_stmt(else_branch, out, depth + 1, is_tail);
        }
        writeln!(out, "{indent}}}").unwrap();
    }

    fn write_update_if(
        &mut self,
        recv: &Expr,
        then_branch: &Expr,
        else_branch: &Expr,
        indent: &str,
        depth: usize,
        is_tail: bool,
        out: &mut String,
    ) {
        let recv_s = self.render_expr(recv);
        let permitted: Vec<String> = self.ctx.permitted.iter().cloned().collect();
        let resource = self.ctx.resource.to_string();
        for field in &permitted {
            writeln!(
                out,
                "{indent}if (context.params[\"{resource}[{field}]\"] !== undefined) {{ ({recv_s} as any).{field} = context.params[\"{resource}[{field}]\"]; }}",
            )
            .unwrap();
            self.state.uses_context = true;
        }
        writeln!(out, "{indent}if ({recv_s}.save) {{").unwrap();
        self.walk_stmt(then_branch, out, depth + 1, is_tail);
        if !crate::lower::is_empty_body(else_branch) {
            writeln!(out, "{indent}}} else {{").unwrap();
            self.walk_stmt(else_branch, out, depth + 1, is_tail);
        }
        writeln!(out, "{indent}}}").unwrap();
    }

    fn write_response_stmt(&mut self, r: &str, _is_tail: bool, indent: &str, out: &mut String) {
        writeln!(out, "{indent}{r}").unwrap();
    }

    fn write_expr_stmt(&mut self, s: &str, indent: &str, out: &mut String) {
        // Note: callers of `walk_stmt` who route Send nodes
        // through `render_send_stmt` produce a rendered fragment
        // and hand it here; the suspension decision has to happen
        // at the walker's Send-dispatch site where the original
        // Expr is still available. See the walker's expression-
        // node handling in `walk_stmt`.
        writeln!(out, "{indent}{s};").unwrap();
    }

    fn render_expr(&mut self, expr: &Expr) -> String {
        if let ExprNode::Send { recv, method, args, block, .. } = &*expr.node {
            // Compute the target-specific suspending prefix from
            // this Send's effects + the adapter's suspending set.
            // Passed into `render_send_stmt` so each variant
            // places the wrapping correctly (outermost for simple
            // shapes, inside compounds for ModelFind's coalesce).
            let prefix = if self.ctx.expr_suspends(expr) {
                self.suspending_prefix()
            } else {
                ""
            };
            if let Some(stmt) = self.render_send_stmt(
                recv.as_ref(), method.as_str(), args, block.as_ref(), prefix,
            ) {
                return match stmt {
                    crate::lower::Stmt::Response(r) => r
                        .trim_start_matches("return ")
                        .trim_end_matches(';')
                        .to_string(),
                    crate::lower::Stmt::Expr(s) => s,
                };
            }
            // Generic fall-through: no SendKind matched. Simple
            // `recv.method(args)` shape; prefix externally.
            let base = emit_send_with_parens(recv.as_ref(), method.as_str(), args, false);
            return if prefix.is_empty() { base } else { format!("{prefix}{base}") };
        }
        emit_expr(expr)
    }

    fn render_send_stmt(
        &mut self,
        recv: Option<&Expr>,
        method: &str,
        args: &[Expr],
        block: Option<&Expr>,
        suspending_prefix: &str,
    ) -> Option<crate::lower::Stmt> {
        use crate::lower::{SendKind, Stmt};
        let kind = crate::lower::classify_controller_send(
            recv, method, args, block, self.ctx.known_models,
        )?;
        let p = suspending_prefix;
        Some(match kind {
            SendKind::ParamsAccess => {
                self.state.uses_context = true;
                Stmt::Expr("context.params".to_string())
            }
            SendKind::ParamsIndex { key } => {
                self.state.uses_context = true;
                let key_s = self.render_expr(key);
                Stmt::Expr(format!("context.params[{key_s}]"))
            }
            SendKind::ParamsExpect { args: pe_args } => {
                self.state.uses_context = true;
                let fragment = match pe_args.first().map(|e| &*e.node) {
                    Some(ExprNode::Lit { value: Literal::Sym { value: key } }) => {
                        format!("context.params.{}", key.as_str())
                    }
                    _ => "context.params /* TODO: params.expect hash */".to_string(),
                };
                Stmt::Expr(fragment)
            }
            SendKind::ModelNew { class } => {
                // `Model.new` is Pure in the catalog — never suspends
                // even under async adapters. Ignore prefix.
                Stmt::Expr(format!("new {}()", class.as_str()))
            }
            SendKind::ModelFind { class, id } => {
                // Compound shape: the `Post.find(id)` call is the
                // suspending piece; the `?? new Post()` fallback is
                // a TS idiom for nullable-lookup coalescing. Under
                // async adapters we need
                //   (await Post.find(id) ?? new Post())
                // which parses as
                //   ((await Post.find(id)) ?? new Post())
                // by precedence (await = 17, ?? = 3) — await binds
                // to the Promise-returning call, not the whole
                // coalesce. Wrong shape was `await (X ?? Y)`:
                // `?? Y` is falsy-coalesce on Promise (truthy), so
                // returns Promise unchanged; `await Promise` then
                // resolves, dropping Y.
                //
                // The same single-paren shape under sync stays
                // `(Post.find(id) ?? new Post())`; stripping
                // `await ` from the async form recovers it
                // exactly, preserving the byte-diff invariant.
                let id_s = self.render_expr(id);
                Stmt::Expr(format!(
                    "({p}{0}.find({id_s}) ?? new {0}())",
                    class.as_str(),
                ))
            }
            SendKind::AssocLookup { target, outer_method } => {
                let target_s = target.as_str();
                match outer_method {
                    "find" => {
                        let id_s = args.first().map(|a| self.render_expr(a))
                            .unwrap_or_else(|| "0".to_string());
                        Stmt::Expr(format!("{p}{target_s}.find({id_s})"))
                    }
                    _ => Stmt::Expr(format!(
                        "new {target_s}() /* TODO: {outer_method} */"
                    )),
                }
            }
            SendKind::QueryChain { target: Some(target), method, args, recv: chain_recv } => {
                // Walk the full chain to collect modifiers, then
                // emit `{target}.all()` + modifier calls. For the
                // scaffold, `order` is the only modifier that
                // changes observable output — the rest (includes,
                // preload, joins, distinct) are no-ops for our
                // sqlite runtime.
                let modifiers = crate::lower::collect_chain_modifiers(method, args, chain_recv);
                let mut s = format!("{}.all()", target.as_str());
                for m in modifiers {
                    s = apply_ts_chain_modifier(s, m);
                }
                Stmt::Expr(format!("{p}{s}"))
            }
            SendKind::QueryChain { target: None, .. } => {
                Stmt::Expr("[] /* TODO: unresolved query chain */".to_string())
            }
            SendKind::PathOrUrlHelper => Stmt::Expr(format!(
                "routeHelpers.{}()",
                lower_first_char(&crate::naming::camelize(method)),
            )),
            SendKind::BangStrip { recv, stripped_method, args: bs_args } => {
                let recv_s = self.render_expr(recv);
                if bs_args.is_empty() {
                    Stmt::Expr(format!("{p}{recv_s}.{stripped_method}"))
                } else {
                    let args_s: Vec<String> =
                        bs_args.iter().map(|a| self.render_expr(a)).collect();
                    Stmt::Expr(format!(
                        "{p}{recv_s}.{stripped_method}({})",
                        args_s.join(", "),
                    ))
                }
            }
            SendKind::InstanceUpdate => {
                Stmt::Expr("false /* TODO: instance update */".to_string())
            }
            SendKind::Render { args: r_args } => {
                // Render/redirect/head are Io effects, not DB —
                // under SqliteAsyncAdapter they don't suspend.
                // Responses stay plain.
                Stmt::Response(self.render_ts_render(r_args))
            }
            SendKind::RedirectTo { args: r_args } => {
                Stmt::Response(self.render_ts_redirect_to(r_args))
            }
            SendKind::Head { args: h_args } => {
                let status = h_args.first().map(|a| self.render_expr(a))
                    .unwrap_or_else(|| "200".to_string());
                Stmt::Response(format!("return {{ status: {status} }};"))
            }
            SendKind::RespondToBlock { .. }
            | SendKind::FormatHtml { .. }
            | SendKind::FormatJson => Stmt::Expr(
                "/* unreachable: respond_to not normalized */".to_string(),
            ),
        })
    }
}

impl<'a> TsEmitter<'a> {
    fn render_ts_render(&mut self, args: &[Expr]) -> String {
        if let Some(first) = args.first() {
            if let ExprNode::Lit { value: Literal::Sym { value: sym } } = &*first.node {
                let suffix = capitalize_ascii(sym.as_str());
                let view_fn = ts_view_fn(self.ctx.model_class, &suffix);
                let arg = self.state.last_local.clone()
                    .unwrap_or_else(|| "undefined as any".to_string());
                let body_part = format!("body: Views.{view_fn}({arg})");
                return match crate::lower::extract_status_from_kwargs(&args[1..]) {
                    Some(status) => format!("return {{ status: {status}, {body_part} }};"),
                    None => format!("return {{ {body_part} }};"),
                };
            }
            let body_s = self.render_expr(first);
            return format!("return {{ body: {body_s} }};");
        }
        "return { body: \"\" };".to_string()
    }

    fn render_ts_redirect_to(&mut self, args: &[Expr]) -> String {
        let Some(first) = args.first() else {
            return "return { status: 303 };".to_string();
        };
        let loc = self.render_expr(first);
        let status = crate::lower::extract_status_from_kwargs(&args[1..]).unwrap_or(303);
        if is_bare_ident(&loc) {
            let helper = lower_first_char(&crate::naming::camelize(&loc));
            let id_access = format!("({} as any).id", loc);
            return format!(
                "return {{ status: {status}, location: routeHelpers.{helper}Path({id_access}) }};",
            );
        }
        format!("return {{ status: {status}, location: {loc} }};")
    }
}

fn is_bare_ident(s: &str) -> bool {
    let bytes = s.as_bytes();
    if bytes.is_empty() {
        return false;
    }
    let first = bytes[0];
    if !(first.is_ascii_lowercase() || first == b'_') {
        return false;
    }
    bytes
        .iter()
        .all(|&b| b.is_ascii_alphanumeric() || b == b'_')
}

fn capitalize_ascii(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) => c.to_ascii_uppercase().to_string() + chars.as_str(),
        None => String::new(),
    }
}


/// Build a TS view fn name from a model class + action suffix.
/// `Article`, `Show` → `renderArticlesShow`; `Article`, `Index` →
/// `renderArticlesIndex`.
fn ts_view_fn(model_class: &str, suffix: &str) -> String {
    let plural = crate::naming::pluralize_snake(model_class);
    let plural_camel = crate::naming::camelize(&plural);
    format!("render{plural_camel}{suffix}")
}


/// IR-level rewrite pass that reshapes a controller action body to
/// Juntos conventions *before* the generic expression emitter runs:
///
/// - `@foo = x` → `foo = x`        (ivar writes become locals)
/// - `@foo`      → `foo`           (ivar reads become locals)
/// - `params[:k]` → `context.params.k` via a chained Send
///
/// Doing it at the IR level lets the existing `emit_expr` recurse
/// through nested expressions naturally — there's no need to thread
/// a "controller mode" flag through every call site.
pub(super) fn rewrite_for_controller(expr: &Expr) -> Expr {
    use crate::ident::VarId;
    // Intercept the `params[:key]` pattern as a whole node first.
    if let Some(rewritten) = try_rewrite_params_access(expr) {
        return rewritten;
    }
    let new_node: ExprNode = match &*expr.node {
        ExprNode::Ivar { name } => ExprNode::Var { id: VarId(0), name: name.clone() },
        ExprNode::Assign { target: LValue::Ivar { name }, value } => ExprNode::Assign {
            target: LValue::Var { id: VarId(0), name: name.clone() },
            value: rewrite_for_controller(value),
        },
        ExprNode::Assign { target: LValue::Var { id, name }, value } => ExprNode::Assign {
            target: LValue::Var { id: *id, name: name.clone() },
            value: rewrite_for_controller(value),
        },
        ExprNode::Assign { target: LValue::Attr { recv, name }, value } => ExprNode::Assign {
            target: LValue::Attr {
                recv: rewrite_for_controller(recv),
                name: name.clone(),
            },
            value: rewrite_for_controller(value),
        },
        ExprNode::Assign { target: LValue::Index { recv, index }, value } => ExprNode::Assign {
            target: LValue::Index {
                recv: rewrite_for_controller(recv),
                index: rewrite_for_controller(index),
            },
            value: rewrite_for_controller(value),
        },
        ExprNode::Send { recv, method, args, block, parenthesized } => ExprNode::Send {
            recv: recv.as_ref().map(rewrite_for_controller),
            method: method.clone(),
            args: args.iter().map(rewrite_for_controller).collect(),
            block: block.as_ref().map(rewrite_for_controller),
            parenthesized: *parenthesized,
        },
        ExprNode::Seq { exprs } => ExprNode::Seq {
            exprs: exprs.iter().map(rewrite_for_controller).collect(),
        },
        ExprNode::If { cond, then_branch, else_branch } => ExprNode::If {
            cond: rewrite_for_controller(cond),
            then_branch: rewrite_for_controller(then_branch),
            else_branch: rewrite_for_controller(else_branch),
        },
        ExprNode::BoolOp { op, surface, left, right } => ExprNode::BoolOp {
            op: *op,
            surface: *surface,
            left: rewrite_for_controller(left),
            right: rewrite_for_controller(right),
        },
        ExprNode::Array { elements, style } => ExprNode::Array {
            elements: elements.iter().map(rewrite_for_controller).collect(),
            style: *style,
        },
        ExprNode::Hash { entries, braced } => ExprNode::Hash {
            entries: entries
                .iter()
                .map(|(k, v)| (rewrite_for_controller(k), rewrite_for_controller(v)))
                .collect(),
            braced: *braced,
        },
        // Lambda bodies (the `do ... end` block of `respond_to` or
        // `format.html`) need the same ivar / params rewrites as the
        // surrounding action body. Preserve other Lambda fields.
        ExprNode::Lambda { params, block_param, body, block_style } => ExprNode::Lambda {
            params: params.clone(),
            block_param: block_param.clone(),
            body: rewrite_for_controller(body),
            block_style: *block_style,
        },
        // Other variants don't contain rewritable subtrees we care
        // about at controller-scope today (Literal, Const, Var,
        // Apply, Case, Yield, Raise, RescueModifier, StringInterp,
        // Let). Clone verbatim.
        other => other.clone(),
    };
    Expr {
        span: expr.span,
        node: Box::new(new_node),
        ty: expr.ty.clone(),
        effects: expr.effects.clone(),
        leading_blank_line: expr.leading_blank_line,
        diagnostic: expr.diagnostic.clone(),
    }
}

/// Match the `params[:key]` call shape and rewrite it to the Juntos
/// `context.params.<key>` three-level Send chain. Returns None if the
/// expression isn't the params-access shape — the outer rewriter
/// continues with its generic recursion.
fn try_rewrite_params_access(expr: &Expr) -> Option<Expr> {
    let ExprNode::Send { recv: Some(recv), method, args, .. } = &*expr.node else {
        return None;
    };
    if method.as_str() != "[]" {
        return None;
    }
    let ExprNode::Send {
        recv: None,
        method: recv_method,
        args: recv_args,
        ..
    } = &*recv.node
    else {
        return None;
    };
    if recv_method.as_str() != "params" || !recv_args.is_empty() {
        return None;
    }
    let idx = args.first()?;
    let ExprNode::Lit { value: Literal::Sym { value: key } } = &*idx.node else {
        return None;
    };
    // Build `context.params.<key>` as three chained Sends — emit_expr
    // renders this as `context.params.<key>` via the Ruby-reader path.
    let span = expr.span;
    let context = Expr::new(
        span,
        ExprNode::Send {
            recv: None,
            method: crate::ident::Symbol::from("context"),
            args: vec![],
            block: None,
            parenthesized: false,
        },
    );
    let params = Expr::new(
        span,
        ExprNode::Send {
            recv: Some(context),
            method: crate::ident::Symbol::from("params"),
            args: vec![],
            block: None,
            parenthesized: false,
        },
    );
    Some(Expr::new(
        span,
        ExprNode::Send {
            recv: Some(params),
            method: key.clone(),
            args: vec![],
            block: None,
            parenthesized: false,
        },
    ))
}
