//! TypeScript fixture emit — `spec/fixtures/<table>.ts` per fixture
//! set plus the `spec/fixtures.ts` lookup helper.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use crate::ty::Ty;

// Fixtures ------------------------------------------------------------

/// Emit one fixture file as `spec/fixtures/<table>.ts` — a set of
/// named exports, one per fixture record. IDs assigned in insertion
/// order (1..N), matching Rust/Crystal emit.
pub(super) fn emit_ts_fixture(lowered: &crate::lower::LoweredFixture) -> EmittedFile {
    let fixture_name = lowered.name.as_str();
    let class_name = lowered.class.0.as_str();
    let model_file = crate::naming::snake_case(class_name);

    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(
        s,
        "import {{ {class_name} }} from \"../../app/models/{model_file}.js\";"
    )
    .unwrap();
    writeln!(s, "import {{ FIXTURE_IDS, fixtureId }} from \"../fixtures.js\";").unwrap();

    // `_loadAll` — called from Fixtures.setup inside beforeEach. Each
    // record runs through the model's `save` getter (validations +
    // INSERT via the juntos runtime); the AUTOINCREMENT id lands in
    // FIXTURE_IDS so the named getters and cross-fixture FK refs can
    // find it.
    writeln!(s).unwrap();
    writeln!(s, "export function _loadAll(): void {{").unwrap();
    for record in &lowered.records {
        let label = record.label.as_str();
        writeln!(s, "  {{").unwrap();
        writeln!(s, "    const record = new {class_name}();").unwrap();
        for field in &record.fields {
            let col = field.column.as_str();
            let val = match &field.value {
                crate::lower::LoweredFixtureValue::Literal { ty, raw } => {
                    ts_literal_for(raw, ty)
                }
                crate::lower::LoweredFixtureValue::FkLookup {
                    target_fixture,
                    target_label,
                } => format!(
                    "fixtureId({:?}, {:?})",
                    target_fixture.as_str(),
                    target_label.as_str(),
                ),
            };
            writeln!(s, "    record.{col} = {val};").unwrap();
        }
        writeln!(
            s,
            "    if (!record.save) throw new Error(\"fixture {fixture_name}/{label} failed to save\");",
        )
        .unwrap();
        writeln!(
            s,
            "    FIXTURE_IDS.set(\"{fixture_name}:{label}\", record.id);",
        )
        .unwrap();
        writeln!(s, "  }}").unwrap();
    }
    writeln!(s, "}}").unwrap();

    for record in &lowered.records {
        let label = record.label.as_str();
        writeln!(s).unwrap();
        writeln!(
            s,
            "export function {label}(): {class_name} {{",
        )
        .unwrap();
        writeln!(
            s,
            "  const id = fixtureId({fixture_name:?}, {label:?});"
        )
        .unwrap();
        writeln!(
            s,
            "  const record = {class_name}.find(id);"
        )
        .unwrap();
        writeln!(
            s,
            "  if (!record) throw new Error(\"fixture {fixture_name}/{label} not loaded\");",
        )
        .unwrap();
        writeln!(s, "  return record;").unwrap();
        writeln!(s, "}}").unwrap();
    }

    EmittedFile {
        path: PathBuf::from(format!("spec/fixtures/{fixture_name}.ts")),
        content: s,
    }
}

/// `spec/fixtures.ts` — top-level fixture harness: the shared
/// FIXTURE_IDS map, the `setup()` entrypoint that every spec's
/// `beforeEach` runs, and the `fixtureId` lookup helper.
pub(super) fn emit_ts_fixtures_helper(lowered: &crate::lower::LoweredFixtureSet) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s, "import {{ setupTestDb }} from \"juntos\";").unwrap();
    writeln!(s, "import {{ CREATE_TABLES }} from \"../src/schema_sql.js\";").unwrap();
    for f in &lowered.fixtures {
        writeln!(
            s,
            "import * as {}Fixtures from \"./fixtures/{}.js\";",
            crate::naming::camelize(f.name.as_str()),
            f.name.as_str(),
        )
        .unwrap();
    }
    writeln!(s).unwrap();
    writeln!(s, "export const FIXTURE_IDS = new Map<string, number>();").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "/** Per-test entry point. Opens a fresh :memory: DB, runs schema").unwrap();
    writeln!(s, " *  DDL, and reloads every fixture in declaration order. */").unwrap();
    writeln!(s, "export function setup(): void {{").unwrap();
    writeln!(s, "  setupTestDb(CREATE_TABLES);").unwrap();
    writeln!(s, "  FIXTURE_IDS.clear();").unwrap();
    for f in &lowered.fixtures {
        writeln!(
            s,
            "  {}Fixtures._loadAll();",
            crate::naming::camelize(f.name.as_str())
        )
        .unwrap();
    }
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "export function fixtureId(fixture: string, label: string): number {{").unwrap();
    writeln!(s, "  const v = FIXTURE_IDS.get(`${{fixture}}:${{label}}`);").unwrap();
    writeln!(
        s,
        "  if (v === undefined) throw new Error(`fixture ${{fixture}}/${{label}} not loaded`);"
    )
    .unwrap();
    writeln!(s, "  return v;").unwrap();
    writeln!(s, "}}").unwrap();
    EmittedFile {
        path: PathBuf::from("spec/fixtures.ts"),
        content: s,
    }
}

/// Map a Roundhouse `Ty` to (type annotation, default expression) for
/// a TS instance field declaration. Keeping both Time and DateTime as
/// `string` matches the Rust/Crystal convention — SQLite stores ISO
/// strings; generated tests compare them as opaque values.
pub(super) fn ts_field_type_and_default(ty: &Ty) -> (String, String) {
    match ty {
        Ty::Int => ("number".into(), "0".into()),
        Ty::Float => ("number".into(), "0".into()),
        Ty::Bool => ("boolean".into(), "false".into()),
        Ty::Str | Ty::Sym => ("string".into(), "\"\"".into()),
        Ty::Class { id, .. } if id.0.as_str() == "Time" => ("string".into(), "\"\"".into()),
        _ => ("any".into(), "null".into()),
    }
}

pub(super) fn ts_literal_for(value: &str, ty: &Ty) -> String {
    match ty {
        Ty::Str | Ty::Sym => format!("{value:?}"),
        Ty::Int => {
            if value.parse::<i64>().is_ok() {
                value.to_string()
            } else {
                format!("0 /* TODO: coerce {value:?} */")
            }
        }
        Ty::Float => {
            if value.parse::<f64>().is_ok() {
                value.to_string()
            } else {
                format!("0 /* TODO: coerce {value:?} */")
            }
        }
        Ty::Bool => match value {
            "true" | "1" => "true".into(),
            "false" | "0" => "false".into(),
            _ => format!("false /* TODO: coerce {value:?} */"),
        },
        Ty::Class { id, .. } if id.0.as_str() == "Time" => format!("{value:?}"),
        _ => format!("{value:?}"),
    }
}
