//! Library-shape emission — kind-agnostic LibraryClass walker.
//!
//! After Phase B of the TS rewrite, this is the *only* code path that
//! turns an IR class into a TS file. All inputs (lowered models,
//! lowered views, lowered controllers, `app.library_classes`) reach
//! the emitter as `LibraryClass` and flow through `emit_class_file`.
//! No per-output-kind machinery: schema/routes/importmap are expected
//! to land here once their lowerers exist.
//!
//! `emit_class_file` does two things: collect imports (juntos exports
//! + sibling models / library_classes referenced in method bodies)
//! and delegate to `super::emit_library_class` for the class body.
//! That body renderer (in `typescript.rs`) handles attr_reader/writer
//! collapse, identifier sanitization, super translation, and
//! Ty-signature-driven param + return types.

use std::collections::BTreeSet;
use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use crate::App;
use crate::dialect::LibraryClass;
use crate::expr::{Expr, ExprNode, InterpPart, LValue, RescueClause};
use crate::ident::Symbol;
use crate::span::Span;

/// Build `(ClassId, ClassInfo)` pairs from a slice of LibraryClasses
/// for use as `extras` to a downstream bulk lowerer. Folds methods
/// across same-named classes (e.g., view modules from the same dir
/// share a `Views::X` ClassId) and registers under both the full
/// ClassId and a last-segment alias for the typer's Const-path
/// resolver. Used by emit() to thread a shared registry through
/// model → controller → test lowerings.
pub(super) fn extras_from_lcs(
    lcs: &[LibraryClass],
) -> Vec<(crate::ident::ClassId, crate::analyze::ClassInfo)> {
    let mut grouped: std::collections::HashMap<
        crate::ident::ClassId,
        crate::analyze::ClassInfo,
    > = std::collections::HashMap::new();
    for lc in lcs {
        let info = grouped.entry(lc.name.clone()).or_default();
        let from = crate::lower::class_info_from_library_class(lc);
        for (k, v) in from.class_methods {
            info.class_methods.insert(k, v);
        }
        for (k, v) in from.instance_methods {
            info.instance_methods.insert(k, v);
        }
        for (k, v) in from.class_method_kinds {
            info.class_method_kinds.insert(k, v);
        }
        for (k, v) in from.instance_method_kinds {
            info.instance_method_kinds.insert(k, v);
        }
    }
    let mut out: Vec<(crate::ident::ClassId, crate::analyze::ClassInfo)> = Vec::new();
    for (full_id, info) in grouped {
        let raw = full_id.0.as_str();
        let last = raw.rsplit("::").next().unwrap_or(raw).to_string();
        if last != raw {
            let mut alias = crate::analyze::ClassInfo::default();
            alias.class_methods = info.class_methods.clone();
            alias.instance_methods = info.instance_methods.clone();
            alias.class_method_kinds = info.class_method_kinds.clone();
            alias.instance_method_kinds = info.instance_method_kinds.clone();
            out.push((crate::ident::ClassId(crate::ident::Symbol::from(last)), alias));
        }
        out.push((full_id, info));
    }
    out
}

/// Emit one `LibraryClass` as a TS source file at `out_path`. The
/// universal entry point — used by `emit()` for lowered models, lowered
/// views, and `app.library_classes` alike.
pub(super) fn emit_class_file(
    lc: &LibraryClass,
    app: &App,
    out_path: PathBuf,
) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();

    let imports = render_imports(lc, app, &out_path);
    if !imports.is_empty() {
        s.push_str(&imports);
        writeln!(s).unwrap();
    }

    match super::emit_library_class(lc) {
        Ok(body) => s.push_str(&body),
        Err(e) => writeln!(s, "// EMIT ERROR: {e}").unwrap(),
    }

    EmittedFile {
        path: out_path,
        content: s,
    }
}

/// Number of `../` hops needed to escape the directory containing
/// `out_path` back to the project root. `app/models/x.ts` → 2 hops
/// up; `test/x.test.ts` → 1; root-level `x.ts` → 0.
fn dir_depth(out_path: &std::path::Path) -> usize {
    out_path.parent().map(|p| p.components().count()).unwrap_or(0)
}

fn relative_to_root(out_path: &std::path::Path, target: &str) -> String {
    let depth = dir_depth(out_path);
    if depth == 0 {
        return format!("./{target}");
    }
    let mut s = String::new();
    for _ in 0..depth {
        s.push_str("../");
    }
    s.push_str(target);
    s
}

/// Names exported from `juntos.ts` that library-class bodies may
/// reference. Anything else not found among siblings is silently
/// skipped from the import list (safer than emitting broken imports).
const JUNTOS_EXPORTS: &[&str] = &[
    "ActiveRecord",
    "ApplicationRecord",
    "CollectionProxy",
    "ErrorCollection",
    "Reference",
    "Router",
    "modelRegistry",
    "conn",
    "installDb",
    "setupTestDb",
    "InMemoryActiveRecordAdapter",
];

/// Compute the import block for a class: scan method bodies for Const
/// references, partition into juntos-provided names vs sibling models /
/// library_classes vs unknown (skipped). Also imports the parent class
/// when it's a juntos export.
fn render_imports(lc: &LibraryClass, app: &App, out_path: &std::path::Path) -> String {
    let name = lc.name.0.as_str();

    let mut refs: BTreeSet<String> = BTreeSet::new();
    for m in &lc.methods {
        collect_class_refs(&m.body, &mut refs);
    }
    if let Some(p) = &lc.parent {
        let raw = p.0.as_str();
        let import_name = match raw {
            "ActiveRecord::Base" => "ActiveRecord".to_string(),
            "StandardError" => String::new(), // TS builtin Error, no import
            // Test parents — the runtime adapter exports both the
            // `TestCase` (Rails) and `Test` (Minitest) names; emit a
            // last-segment import that resolves through the runtime
            // path special-case below.
            "ActiveSupport::TestCase" | "ActionDispatch::IntegrationTest" => "TestCase".to_string(),
            "Minitest::Test" => "Test".to_string(),
            _ => raw.rsplit("::").next().unwrap_or(raw).to_string(),
        };
        if !import_name.is_empty() {
            refs.insert(import_name);
        }
    }
    refs.remove(name);

    let mut juntos_imports: Vec<String> = Vec::new();
    let mut model_imports: Vec<(String, String)> = Vec::new();
    let mut runtime_imports: Vec<String> = Vec::new();
    let mut fixture_imports: Vec<(String, String)> = Vec::new();

    for r in refs {
        let r_str: &str = &r;
        if JUNTOS_EXPORTS.contains(&r_str) {
            juntos_imports.push(r);
        } else if r == "Test" || r == "TestCase" {
            runtime_imports.push(r);
        } else if app.models.iter().any(|m| m.name.0.as_str() == r) {
            let stem = crate::naming::snake_case(&r);
            model_imports.push((r, stem));
        } else if app.library_classes.iter().any(|other| other.name.0.as_str() == r) {
            let stem = crate::naming::snake_case(&r);
            model_imports.push((r, stem));
        } else if let Some(fixture_stem) = r.strip_suffix("Fixtures") {
            // `<Plural>Fixtures` ↔ `test/fixtures/<plural>.ts`. The
            // fixture-call rewrite produces these Const references on
            // every test body that uses `articles(:one)`-style helpers.
            let plural = crate::naming::snake_case(fixture_stem);
            if app.fixtures.iter().any(|f| f.name.as_str() == plural) {
                fixture_imports.push((r, plural));
            }
        }
    }

    let mut s = String::new();
    if !juntos_imports.is_empty() {
        writeln!(
            s,
            "import {{ {} }} from \"juntos\";",
            juntos_imports.join(", ")
        )
        .unwrap();
    }
    if !runtime_imports.is_empty() {
        // Test files live under test/; the runtime adapter is at
        // test/_runtime/minitest.ts. Compute path: relative to the
        // test file's parent dir, the runtime is `./_runtime/minitest.js`.
        // For non-test files (which shouldn't import TestCase but
        // we handle defensively), use root-relative.
        let runtime_path = if out_path.starts_with("test") {
            "./_runtime/minitest.js".to_string()
        } else {
            relative_to_root(out_path, "test/_runtime/minitest.js")
        };
        writeln!(
            s,
            "import {{ {} }} from \"{runtime_path}\";",
            runtime_imports.join(", "),
        )
        .unwrap();
    }
    for (n, stem) in &model_imports {
        // Models live at app/models/<stem>.ts. Test files at
        // test/<stem>.test.ts need `../app/models/<stem>.js`; views at
        // app/views/<dir>/<base>.ts need `../../app/models/<stem>.js`;
        // models in the same dir use `./<stem>.js`.
        let import_path = if out_path.starts_with("app/models") {
            format!("./{stem}.js")
        } else {
            relative_to_root(out_path, &format!("app/models/{stem}.js"))
        };
        writeln!(s, "import {{ {n} }} from \"{import_path}\";").unwrap();
    }
    for (n, stem) in &fixture_imports {
        // Fixtures live at test/fixtures/<stem>.ts. Test files at
        // test/<x>.test.ts use `./fixtures/<stem>.js`; nested test
        // files (test/integration/<x>.test.ts) need root-relative.
        let import_path = if out_path.starts_with("test")
            && out_path.parent().map(|p| p.to_str() == Some("test")).unwrap_or(false)
        {
            format!("./fixtures/{stem}.js")
        } else {
            relative_to_root(out_path, &format!("test/fixtures/{stem}.js"))
        };
        writeln!(s, "import {{ {n} }} from \"{import_path}\";").unwrap();
    }
    s
}

/// Walk an expression tree collecting top-level Const references —
/// the leading segment of a `path` is what gets imported (Ruby's
/// `Foo::Bar` uses `Foo` as the resolved name; we don't import inner
/// segments).
fn collect_class_refs(e: &Expr, out: &mut BTreeSet<String>) {
    use crate::expr::LValue;
    match &*e.node {
        ExprNode::Const { path } => {
            if let Some(first) = path.first() {
                out.insert(first.as_str().to_string());
            }
        }
        ExprNode::Send { recv, args, block, .. } => {
            if let Some(r) = recv {
                collect_class_refs(r, out);
            }
            for a in args {
                collect_class_refs(a, out);
            }
            if let Some(b) = block {
                collect_class_refs(b, out);
            }
        }
        ExprNode::Apply { fun, args, block } => {
            collect_class_refs(fun, out);
            for a in args {
                collect_class_refs(a, out);
            }
            if let Some(b) = block {
                collect_class_refs(b, out);
            }
        }
        ExprNode::Hash { entries, .. } => {
            for (k, v) in entries {
                collect_class_refs(k, out);
                collect_class_refs(v, out);
            }
        }
        ExprNode::Array { elements, .. } => {
            for el in elements {
                collect_class_refs(el, out);
            }
        }
        ExprNode::StringInterp { parts } => {
            for p in parts {
                if let InterpPart::Expr { expr } = p {
                    collect_class_refs(expr, out);
                }
            }
        }
        ExprNode::BoolOp { left, right, .. } => {
            collect_class_refs(left, out);
            collect_class_refs(right, out);
        }
        ExprNode::Let { value, body, .. } => {
            collect_class_refs(value, out);
            collect_class_refs(body, out);
        }
        ExprNode::Lambda { body, .. } => collect_class_refs(body, out),
        ExprNode::If { cond, then_branch, else_branch } => {
            collect_class_refs(cond, out);
            collect_class_refs(then_branch, out);
            collect_class_refs(else_branch, out);
        }
        ExprNode::Case { scrutinee, arms } => {
            collect_class_refs(scrutinee, out);
            for arm in arms {
                collect_class_refs(&arm.body, out);
            }
        }
        ExprNode::Seq { exprs } => {
            for e in exprs {
                collect_class_refs(e, out);
            }
        }
        ExprNode::Assign { target, value } => {
            if let LValue::Attr { recv, .. } | LValue::Index { recv, .. } = target {
                collect_class_refs(recv, out);
            }
            collect_class_refs(value, out);
        }
        ExprNode::Yield { args } => {
            for a in args {
                collect_class_refs(a, out);
            }
        }
        ExprNode::Raise { value } => collect_class_refs(value, out),
        ExprNode::RescueModifier { expr, fallback } => {
            collect_class_refs(expr, out);
            collect_class_refs(fallback, out);
        }
        ExprNode::Return { value } => collect_class_refs(value, out),
        ExprNode::Super { args } => {
            if let Some(args) = args {
                for a in args {
                    collect_class_refs(a, out);
                }
            }
        }
        ExprNode::BeginRescue { body, rescues, else_branch, ensure, .. } => {
            collect_class_refs(body, out);
            for r in rescues {
                collect_class_refs(&r.body, out);
            }
            if let Some(e) = else_branch {
                collect_class_refs(e, out);
            }
            if let Some(e) = ensure {
                collect_class_refs(e, out);
            }
        }
        ExprNode::Next { value } => {
            if let Some(v) = value { collect_class_refs(v, out); }
        }
        ExprNode::MultiAssign { value, .. } => collect_class_refs(value, out),
        ExprNode::While { cond, body, .. } => {
            collect_class_refs(cond, out);
            collect_class_refs(body, out);
        }
        ExprNode::Range { begin, end, .. } => {
            if let Some(b) = begin { collect_class_refs(b, out); }
            if let Some(e) = end { collect_class_refs(e, out); }
        }
        ExprNode::Lit { .. }
        | ExprNode::Var { .. }
        | ExprNode::Ivar { .. }
        | ExprNode::SelfRef => {}
    }
}

// `sanitize_identifier`, `rewrite_for_class_method`, and
// `rewrite_for_constructor` are referenced from `super::emit_class_member`
// — keep them here.

/// Ruby allows `?` and `!` suffixes on method names; TS does not.
/// Strip them for the output identifier. Juntos's runtime drops them
/// too (`Article.exists(id)` not `Article.exists?(id)`).
pub(super) fn sanitize_identifier(ruby_name: &str) -> String {
    ruby_name
        .trim_end_matches('?')
        .trim_end_matches('!')
        .to_string()
}

/// IR transformation applied to each class method body before emission.
/// Two pieces:
///  1. `Send { recv: None, ... }` (bare method call / implicit self)
///     gets `SelfRef` as an explicit receiver, so the TS output
///     becomes `this.method(...)` instead of a dangling `method(...)`.
///  2. `Super { args }` becomes a Send on a synthetic `super` receiver
///     with the enclosing method's name. TS needs
///     `super.methodName(args)`, not bare `super(...)`.
///
/// `enclosing_method` is the Ruby method name (may end in `=` for
/// setters). The `=` is dropped for the super-call target so the
/// method name is a valid TS identifier.
pub(super) fn rewrite_for_class_method(e: &Expr, enclosing_method: &str) -> Expr {
    let method_for_super = enclosing_method.trim_end_matches('=').to_string();
    rewrite(e, Some(&method_for_super))
}

/// Variant of `rewrite_for_class_method` that leaves `Super { args }`
/// nodes intact instead of rewriting them to `super.<method>(args)`.
/// Constructors use this: TS spells the parent-constructor call as
/// `super(args)`, not `super.initialize(args)`.
pub(super) fn rewrite_for_constructor(e: &Expr) -> Expr {
    rewrite(e, None)
}

fn rewrite(e: &Expr, super_method: Option<&str>) -> Expr {
    let new_node = match &*e.node {
        // `raise X, msg` is a Kernel-level call that target emitters
        // render as `throw new X(msg)`. Leaving it as Send-no-recv (no
        // SelfRef rewrite) lets the emit_send_with_parens special-case
        // for `raise` fire.
        ExprNode::Send { recv: None, method, args, block, parenthesized }
            if method.as_str() == "raise" =>
        {
            ExprNode::Send {
                recv: None,
                method: method.clone(),
                args: args.iter().map(|a| rewrite(a, super_method)).collect(),
                block: block.as_ref().map(|b| rewrite(b, super_method)),
                parenthesized: *parenthesized,
            }
        }
        ExprNode::Send { recv: None, method, args, block, parenthesized } => ExprNode::Send {
            recv: Some(Expr::new(Span::synthetic(), ExprNode::SelfRef)),
            method: method.clone(),
            args: args.iter().map(|a| rewrite(a, super_method)).collect(),
            block: block.as_ref().map(|b| rewrite(b, super_method)),
            parenthesized: *parenthesized,
        },
        ExprNode::Send { recv: Some(r), method, args, block, parenthesized } => ExprNode::Send {
            recv: Some(rewrite(r, super_method)),
            method: method.clone(),
            args: args.iter().map(|a| rewrite(a, super_method)).collect(),
            block: block.as_ref().map(|b| rewrite(b, super_method)),
            parenthesized: *parenthesized,
        },
        ExprNode::Super { args } => match super_method {
            None => {
                let rewritten_args: Option<Vec<Expr>> = args
                    .as_ref()
                    .map(|v| v.iter().map(|a| rewrite(a, None)).collect());
                ExprNode::Super { args: rewritten_args }
            }
            Some(super_method) => {
                let super_recv = Expr::new(
                    Span::synthetic(),
                    ExprNode::Const { path: vec![Symbol::from("super")] },
                );
                let args_vec: Vec<Expr> = match args {
                    Some(v) => v
                        .iter()
                        .map(|a| rewrite(a, Some(super_method)))
                        .collect(),
                    None => vec![],
                };
                let is_base_getter = matches!(
                    super_method,
                    "save" | "destroy" | "errors" | "attributes"
                );
                let parenthesized = !args_vec.is_empty() || !is_base_getter;
                ExprNode::Send {
                    recv: Some(super_recv),
                    method: Symbol::from(super_method.to_string()),
                    args: args_vec,
                    block: None,
                    parenthesized,
                }
            }
        },
        ExprNode::Seq { exprs } => ExprNode::Seq {
            exprs: exprs.iter().map(|c| rewrite(c, super_method)).collect(),
        },
        ExprNode::If { cond, then_branch, else_branch } => ExprNode::If {
            cond: rewrite(cond, super_method),
            then_branch: rewrite(then_branch, super_method),
            else_branch: rewrite(else_branch, super_method),
        },
        ExprNode::BoolOp { op, surface, left, right } => ExprNode::BoolOp {
            op: *op,
            surface: *surface,
            left: rewrite(left, super_method),
            right: rewrite(right, super_method),
        },
        ExprNode::Array { elements, style } => ExprNode::Array {
            elements: elements.iter().map(|c| rewrite(c, super_method)).collect(),
            style: *style,
        },
        ExprNode::Hash { entries, braced } => ExprNode::Hash {
            entries: entries
                .iter()
                .map(|(k, v)| (rewrite(k, super_method), rewrite(v, super_method)))
                .collect(),
            braced: *braced,
        },
        ExprNode::StringInterp { parts } => ExprNode::StringInterp {
            parts: parts
                .iter()
                .map(|p| match p {
                    InterpPart::Text { value } => InterpPart::Text { value: value.clone() },
                    InterpPart::Expr { expr } => InterpPart::Expr {
                        expr: rewrite(expr, super_method),
                    },
                })
                .collect(),
        },
        ExprNode::Lambda { params, block_param, body, block_style } => ExprNode::Lambda {
            params: params.clone(),
            block_param: block_param.clone(),
            body: rewrite(body, super_method),
            block_style: *block_style,
        },
        ExprNode::Apply { fun, args, block } => ExprNode::Apply {
            fun: rewrite(fun, super_method),
            args: args.iter().map(|a| rewrite(a, super_method)).collect(),
            block: block.as_ref().map(|b| rewrite(b, super_method)),
        },
        ExprNode::Assign { target, value } => {
            let new_target = match target {
                LValue::Var { id, name } => LValue::Var { id: *id, name: name.clone() },
                LValue::Ivar { name } => LValue::Ivar { name: name.clone() },
                LValue::Attr { recv, name } => LValue::Attr {
                    recv: rewrite(recv, super_method),
                    name: name.clone(),
                },
                LValue::Index { recv, index } => LValue::Index {
                    recv: rewrite(recv, super_method),
                    index: rewrite(index, super_method),
                },
            };
            ExprNode::Assign {
                target: new_target,
                value: rewrite(value, super_method),
            }
        }
        ExprNode::Yield { args } => ExprNode::Yield {
            args: args.iter().map(|a| rewrite(a, super_method)).collect(),
        },
        ExprNode::Raise { value } => ExprNode::Raise {
            value: rewrite(value, super_method),
        },
        ExprNode::RescueModifier { expr, fallback } => ExprNode::RescueModifier {
            expr: rewrite(expr, super_method),
            fallback: rewrite(fallback, super_method),
        },
        ExprNode::Return { value } => ExprNode::Return {
            value: rewrite(value, super_method),
        },
        ExprNode::BeginRescue { body, rescues, else_branch, ensure, implicit } => {
            ExprNode::BeginRescue {
                body: rewrite(body, super_method),
                rescues: rescues
                    .iter()
                    .map(|rc| RescueClause {
                        classes: rc.classes.iter().map(|c| rewrite(c, super_method)).collect(),
                        binding: rc.binding.clone(),
                        body: rewrite(&rc.body, super_method),
                    })
                    .collect(),
                else_branch: else_branch.as_ref().map(|b| rewrite(b, super_method)),
                ensure: ensure.as_ref().map(|b| rewrite(b, super_method)),
                implicit: *implicit,
            }
        }
        ExprNode::Case { scrutinee, arms } => ExprNode::Case {
            scrutinee: rewrite(scrutinee, super_method),
            arms: arms
                .iter()
                .map(|arm| crate::expr::Arm {
                    pattern: arm.pattern.clone(),
                    guard: arm.guard.as_ref().map(|g| rewrite(g, super_method)),
                    body: rewrite(&arm.body, super_method),
                })
                .collect(),
        },
        ExprNode::Let { id, name, value, body } => ExprNode::Let {
            id: *id,
            name: name.clone(),
            value: rewrite(value, super_method),
            body: rewrite(body, super_method),
        },
        ExprNode::Next { value } => ExprNode::Next {
            value: value.as_ref().map(|v| rewrite(v, super_method)),
        },
        ExprNode::MultiAssign { targets, value } => ExprNode::MultiAssign {
            targets: targets.clone(),
            value: rewrite(value, super_method),
        },
        ExprNode::While { cond, body, until_form } => ExprNode::While {
            cond: rewrite(cond, super_method),
            body: rewrite(body, super_method),
            until_form: *until_form,
        },
        ExprNode::Range { begin, end, exclusive } => ExprNode::Range {
            begin: begin.as_ref().map(|b| rewrite(b, super_method)),
            end: end.as_ref().map(|e| rewrite(e, super_method)),
            exclusive: *exclusive,
        },
        // Leaves pass through unchanged.
        ExprNode::Lit { .. }
        | ExprNode::Var { .. }
        | ExprNode::Ivar { .. }
        | ExprNode::Const { .. }
        | ExprNode::SelfRef => (*e.node).clone(),
    };

    Expr {
        span: e.span,
        node: Box::new(new_node),
        ty: e.ty.clone(),
        effects: e.effects.clone(),
        leading_blank_line: e.leading_blank_line,
        diagnostic: e.diagnostic.clone(),
    }
}
