//! Library-shape emission — kind-agnostic LibraryClass walker.
//!
//! After Phase B of the TS rewrite, this is the *only* code path that
//! turns an IR class into a TS file. All inputs (lowered models,
//! lowered views, lowered controllers, `app.library_classes`) reach
//! the emitter as `LibraryClass` and flow through `emit_class_file`.
//! No per-output-kind machinery: schema/routes/importmap are expected
//! to land here once their lowerers exist.

use std::collections::BTreeSet;
use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use super::expr::{emit_body, emit_expr};
use super::ty::ts_ty;
use crate::App;
use crate::dialect::{LibraryClass, MethodDef, MethodReceiver};
use crate::expr::{Expr, ExprNode, InterpPart, LValue, RescueClause};
use crate::span::Span;
use crate::ident::Symbol;
use crate::ty::Ty;

/// Emit one `LibraryClass` as a TS source file at `out_path`. The
/// universal entry point — used by `emit()` for lowered models, lowered
/// views, and `app.library_classes` alike.
pub(super) fn emit_class_file(
    lc: &LibraryClass,
    app: &App,
    out_path: PathBuf,
) -> EmittedFile {
    emit_library_class_decl(lc, app, out_path)
}

/// Names exported from `juntos.ts` that library-class bodies may
/// reference. Anything else not found among siblings is silently
/// skipped from the import list (safer than emitting broken imports).
const JUNTOS_EXPORTS: &[&str] = &[
    "ActiveRecord",
    "ApplicationRecord",
    "CollectionProxy",
    "ErrorCollection",
    "Reference",
    "Router",
    "modelRegistry",
    "conn",
    "installDb",
    "setupTestDb",
    "InMemoryActiveRecordAdapter",
];

fn emit_library_class_decl(lc: &LibraryClass, app: &App, out_path: PathBuf) -> EmittedFile {
    let name = lc.name.0.as_str();
    let mut s = String::new();

    writeln!(s, "// Generated by Roundhouse (library class).").unwrap();

    // Walk method bodies for cross-class references and partition into
    // juntos-provided names vs sibling models/library-classes vs unknown.
    let mut refs: BTreeSet<String> = BTreeSet::new();
    for m in &lc.methods {
        collect_class_refs(&m.body, &mut refs);
    }
    refs.remove(name); // self-references aren't imports

    let mut juntos_imports: Vec<String> = Vec::new();
    let mut sibling_imports: Vec<(String, String)> = Vec::new();

    for r in refs {
        let r_str: &str = &r;
        if JUNTOS_EXPORTS.contains(&r_str) {
            juntos_imports.push(r);
        } else if app.models.iter().any(|m| m.name.0.as_str() == r) {
            let stem = crate::naming::snake_case(&r);
            sibling_imports.push((r, stem));
        } else if app.library_classes.iter().any(|other| other.name.0.as_str() == r) {
            let stem = crate::naming::snake_case(&r);
            sibling_imports.push((r, stem));
        }
        // Unknown identifier — skip. Likely a global, builtin, or
        // typo. Better to emit no import than a bad one.
    }

    if !juntos_imports.is_empty() {
        writeln!(
            s,
            "import {{ {} }} from \"juntos\";",
            juntos_imports.join(", ")
        )
        .unwrap();
    }
    for (n, stem) in &sibling_imports {
        writeln!(s, "import {{ {n} }} from \"./{stem}.js\";").unwrap();
    }
    if !juntos_imports.is_empty() || !sibling_imports.is_empty() {
        writeln!(s).unwrap();
    }

    // No automatic ApplicationRecord parent — library classes only
    // extend something if the source declared a superclass. Most won't.
    let extends_clause = lc
        .parent
        .as_ref()
        .map(|p| {
            let raw = p.0.as_str();
            let last = raw.rsplit("::").next().unwrap_or(raw);
            format!(" extends {last}")
        })
        .unwrap_or_default();

    writeln!(s, "export class {name}{extends_clause} {{").unwrap();

    // Collect ivar names referenced by any method body and emit them
    // as class fields. Without these declarations, TS rejects
    // `this.owner = owner` and `this.owner.id` reads. Declared as
    // `any` for now — proper typing per ivar lands when the analyzer
    // exposes its discovered ivar types to emit.
    let mut ivar_names: BTreeSet<String> = BTreeSet::new();
    for m in &lc.methods {
        collect_ivar_names(&m.body, &mut ivar_names);
    }
    if !ivar_names.is_empty() {
        for name in &ivar_names {
            writeln!(s, "  {name}: any;").unwrap();
        }
        writeln!(s).unwrap();
    }

    let mut first = true;
    for m in &lc.methods {
        if !first {
            writeln!(s).unwrap();
        }
        first = false;
        emit_plain_method(&mut s, m);
    }

    writeln!(s, "}}").unwrap();

    EmittedFile {
        path: out_path,
        content: s,
    }
}

/// Walk an expression tree collecting top-level Const references —
/// the leading segment of a `path` is what gets imported (Ruby's
/// `Foo::Bar` uses `Foo` as the resolved name; we don't import inner
/// segments). Misses are fine: if a referenced name isn't here, the
/// import scan won't generate an import for it, but emission still
/// produces a TS reference that surfaces at tsc-check time.
pub(super) fn collect_class_refs(e: &Expr, out: &mut BTreeSet<String>) {
    use crate::expr::LValue;
    match &*e.node {
        ExprNode::Const { path } => {
            if let Some(first) = path.first() {
                out.insert(first.as_str().to_string());
            }
        }
        ExprNode::Send { recv, args, block, .. } => {
            if let Some(r) = recv {
                collect_class_refs(r, out);
            }
            for a in args {
                collect_class_refs(a, out);
            }
            if let Some(b) = block {
                collect_class_refs(b, out);
            }
        }
        ExprNode::Apply { fun, args, block } => {
            collect_class_refs(fun, out);
            for a in args {
                collect_class_refs(a, out);
            }
            if let Some(b) = block {
                collect_class_refs(b, out);
            }
        }
        ExprNode::Hash { entries, .. } => {
            for (k, v) in entries {
                collect_class_refs(k, out);
                collect_class_refs(v, out);
            }
        }
        ExprNode::Array { elements, .. } => {
            for el in elements {
                collect_class_refs(el, out);
            }
        }
        ExprNode::StringInterp { parts } => {
            for p in parts {
                if let InterpPart::Expr { expr } = p {
                    collect_class_refs(expr, out);
                }
            }
        }
        ExprNode::BoolOp { left, right, .. } => {
            collect_class_refs(left, out);
            collect_class_refs(right, out);
        }
        ExprNode::Let { value, body, .. } => {
            collect_class_refs(value, out);
            collect_class_refs(body, out);
        }
        ExprNode::Lambda { body, .. } => collect_class_refs(body, out),
        ExprNode::If { cond, then_branch, else_branch } => {
            collect_class_refs(cond, out);
            collect_class_refs(then_branch, out);
            collect_class_refs(else_branch, out);
        }
        ExprNode::Case { scrutinee, arms } => {
            collect_class_refs(scrutinee, out);
            for arm in arms {
                collect_class_refs(&arm.body, out);
            }
        }
        ExprNode::Seq { exprs } => {
            for e in exprs {
                collect_class_refs(e, out);
            }
        }
        ExprNode::Assign { target, value } => {
            if let LValue::Attr { recv, .. } | LValue::Index { recv, .. } = target {
                collect_class_refs(recv, out);
            }
            collect_class_refs(value, out);
        }
        ExprNode::Yield { args } => {
            for a in args {
                collect_class_refs(a, out);
            }
        }
        ExprNode::Raise { value } => collect_class_refs(value, out),
        ExprNode::RescueModifier { expr, fallback } => {
            collect_class_refs(expr, out);
            collect_class_refs(fallback, out);
        }
        ExprNode::Return { value } => collect_class_refs(value, out),
        ExprNode::Super { args } => {
            if let Some(args) = args {
                for a in args {
                    collect_class_refs(a, out);
                }
            }
        }
        ExprNode::BeginRescue { body, rescues, else_branch, ensure, .. } => {
            collect_class_refs(body, out);
            for r in rescues {
                collect_class_refs(&r.body, out);
            }
            if let Some(e) = else_branch {
                collect_class_refs(e, out);
            }
            if let Some(e) = ensure {
                collect_class_refs(e, out);
            }
        }
        ExprNode::Next { value } => {
            if let Some(v) = value { collect_class_refs(v, out); }
        }
        ExprNode::MultiAssign { value, .. } => collect_class_refs(value, out),
        ExprNode::While { cond, body, .. } => {
            collect_class_refs(cond, out);
            collect_class_refs(body, out);
        }
        ExprNode::Range { begin, end, .. } => {
            if let Some(b) = begin { collect_class_refs(b, out); }
            if let Some(e) = end { collect_class_refs(e, out); }
        }
        // Leaf nodes — nothing to walk.
        ExprNode::Lit { .. }
        | ExprNode::Var { .. }
        | ExprNode::Ivar { .. }
        | ExprNode::SelfRef => {}
    }
}

pub(super) fn emit_plain_method(s: &mut String, m: &MethodDef) {
    let name = sanitize_identifier(m.name.as_str());
    let ret_ty = m.body.ty.clone().unwrap_or(Ty::Nil);
    let ret_s = ts_ty(&ret_ty);
    let is_static = matches!(m.receiver, MethodReceiver::Class);
    let static_prefix = if is_static { "static " } else { "" };

    let uses_yield = body_uses_yield(&m.body);

    // Ruby's `def initialize` maps to TS's `constructor`. Constructors
    // can't have a return-type annotation (TS rejects them) and don't
    // use the `function` keyword.
    let is_constructor = !is_static && m.name.as_str() == "initialize";

    // Zero-arg, no-yield, instance methods emit as TS getters. Matches
    // the Juntos convention (and Ruby's no-paren reader idiom): callers
    // invoke `record.size` as a property access, not a function call.
    // Static methods stay as methods (Class.foo() reads naturally with
    // parens). Methods with parameters or `yield` always emit as methods
    // since getters can't take args. Constructors are also methods.
    let is_getter =
        !is_static && !is_constructor && m.params.is_empty() && !uses_yield;

    if is_constructor {
        let params: Vec<String> = m
            .params
            .iter()
            .map(|p| format!("{}: unknown", p.as_str()))
            .collect();
        writeln!(s, "  constructor({}) {{", params.join(", ")).unwrap();
    } else if is_getter {
        writeln!(s, "  get {name}(): {ret_s} {{").unwrap();
    } else {
        let mut params: Vec<String> = m
            .params
            .iter()
            .map(|p| format!("{}: unknown", p.as_str()))
            .collect();
        if uses_yield {
            params.push("__block: (...args: any[]) => any".to_string());
        }
        writeln!(
            s,
            "  {static_prefix}{name}({}): {ret_s} {{",
            params.join(", ")
        )
        .unwrap();
    }
    let method_body = rewrite_for_class_method(&m.body, m.name.as_str());
    // Constructors can't return a value — force void emission so
    // `@x = y` emits as `this.x = y;` not `return this.x = y;`.
    let emit_ty = if is_constructor { Ty::Nil } else { ret_ty.clone() };
    let body = emit_body(&method_body, &emit_ty);
    for line in body.lines() {
        writeln!(s, "    {line}").unwrap();
    }
    writeln!(s, "  }}").unwrap();
}

/// Walk an expression tree collecting ivar names (the leading `@` is
/// stripped — `@owner` becomes `owner`). Used by library-class
/// emission to produce TS field declarations so reads/writes
/// type-check.
pub(super) fn collect_ivar_names(e: &Expr, out: &mut BTreeSet<String>) {
    use crate::expr::LValue;
    match &*e.node {
        ExprNode::Ivar { name } => {
            out.insert(name.as_str().to_string());
        }
        ExprNode::Assign { target: LValue::Ivar { name }, value } => {
            out.insert(name.as_str().to_string());
            collect_ivar_names(value, out);
        }
        ExprNode::Send { recv, args, block, .. } => {
            if let Some(r) = recv {
                collect_ivar_names(r, out);
            }
            for a in args {
                collect_ivar_names(a, out);
            }
            if let Some(b) = block {
                collect_ivar_names(b, out);
            }
        }
        ExprNode::Apply { fun, args, block } => {
            collect_ivar_names(fun, out);
            for a in args {
                collect_ivar_names(a, out);
            }
            if let Some(b) = block {
                collect_ivar_names(b, out);
            }
        }
        ExprNode::Hash { entries, .. } => {
            for (k, v) in entries {
                collect_ivar_names(k, out);
                collect_ivar_names(v, out);
            }
        }
        ExprNode::Array { elements, .. } => {
            for el in elements {
                collect_ivar_names(el, out);
            }
        }
        ExprNode::StringInterp { parts } => {
            for p in parts {
                if let InterpPart::Expr { expr } = p {
                    collect_ivar_names(expr, out);
                }
            }
        }
        ExprNode::BoolOp { left, right, .. } => {
            collect_ivar_names(left, out);
            collect_ivar_names(right, out);
        }
        ExprNode::Let { value, body, .. } => {
            collect_ivar_names(value, out);
            collect_ivar_names(body, out);
        }
        ExprNode::Lambda { body, .. } => collect_ivar_names(body, out),
        ExprNode::If { cond, then_branch, else_branch } => {
            collect_ivar_names(cond, out);
            collect_ivar_names(then_branch, out);
            collect_ivar_names(else_branch, out);
        }
        ExprNode::Case { scrutinee, arms } => {
            collect_ivar_names(scrutinee, out);
            for arm in arms {
                collect_ivar_names(&arm.body, out);
            }
        }
        ExprNode::Seq { exprs } => {
            for e in exprs {
                collect_ivar_names(e, out);
            }
        }
        ExprNode::Assign { target, value } => {
            if let LValue::Attr { recv, .. } | LValue::Index { recv, .. } = target {
                collect_ivar_names(recv, out);
            }
            collect_ivar_names(value, out);
        }
        ExprNode::Yield { args } => {
            for a in args {
                collect_ivar_names(a, out);
            }
        }
        ExprNode::Raise { value } => collect_ivar_names(value, out),
        ExprNode::RescueModifier { expr, fallback } => {
            collect_ivar_names(expr, out);
            collect_ivar_names(fallback, out);
        }
        ExprNode::Return { value } => collect_ivar_names(value, out),
        ExprNode::Super { args } => {
            if let Some(args) = args {
                for a in args {
                    collect_ivar_names(a, out);
                }
            }
        }
        ExprNode::BeginRescue { body, rescues, else_branch, ensure, .. } => {
            collect_ivar_names(body, out);
            for r in rescues {
                collect_ivar_names(&r.body, out);
            }
            if let Some(e) = else_branch {
                collect_ivar_names(e, out);
            }
            if let Some(e) = ensure {
                collect_ivar_names(e, out);
            }
        }
        ExprNode::Next { value } => {
            if let Some(v) = value { collect_ivar_names(v, out); }
        }
        ExprNode::MultiAssign { targets, value } => {
            collect_ivar_names(value, out);
            for t in targets {
                if let LValue::Ivar { name } = t {
                    out.insert(name.as_str().to_string());
                }
            }
        }
        ExprNode::While { cond, body, .. } => {
            collect_ivar_names(cond, out);
            collect_ivar_names(body, out);
        }
        ExprNode::Range { begin, end, .. } => {
            if let Some(b) = begin { collect_ivar_names(b, out); }
            if let Some(e) = end { collect_ivar_names(e, out); }
        }
        ExprNode::Lit { .. }
        | ExprNode::Var { .. }
        | ExprNode::Const { .. }
        | ExprNode::SelfRef => {}
    }
}

/// True if the expression tree contains an `ExprNode::Yield` anywhere.
/// Used by `emit_plain_method` to decide whether to inject a `__block`
/// parameter. Lambdas do *not* mask yield (Ruby's yield always targets
/// the enclosing method, not the surrounding block), so naive
/// recursion is correct.
fn body_uses_yield(e: &Expr) -> bool {
    use crate::expr::LValue;
    match &*e.node {
        ExprNode::Yield { .. } => true,
        ExprNode::Send { recv, args, block, .. } => {
            recv.as_ref().is_some_and(|r| body_uses_yield(r))
                || args.iter().any(body_uses_yield)
                || block.as_ref().is_some_and(|b| body_uses_yield(b))
        }
        ExprNode::Apply { fun, args, block } => {
            body_uses_yield(fun)
                || args.iter().any(body_uses_yield)
                || block.as_ref().is_some_and(|b| body_uses_yield(b))
        }
        ExprNode::Hash { entries, .. } => {
            entries.iter().any(|(k, v)| body_uses_yield(k) || body_uses_yield(v))
        }
        ExprNode::Array { elements, .. } => elements.iter().any(body_uses_yield),
        ExprNode::StringInterp { parts } => parts.iter().any(|p| {
            matches!(p, InterpPart::Expr { expr } if body_uses_yield(expr))
        }),
        ExprNode::BoolOp { left, right, .. } => body_uses_yield(left) || body_uses_yield(right),
        ExprNode::Let { value, body, .. } => body_uses_yield(value) || body_uses_yield(body),
        ExprNode::Lambda { body, .. } => body_uses_yield(body),
        ExprNode::If { cond, then_branch, else_branch } => {
            body_uses_yield(cond) || body_uses_yield(then_branch) || body_uses_yield(else_branch)
        }
        ExprNode::Case { scrutinee, arms } => {
            body_uses_yield(scrutinee) || arms.iter().any(|a| body_uses_yield(&a.body))
        }
        ExprNode::Seq { exprs } => exprs.iter().any(body_uses_yield),
        ExprNode::Assign { target, value } => {
            let target_yields = matches!(
                target,
                LValue::Attr { recv, .. } | LValue::Index { recv, .. } if body_uses_yield(recv)
            );
            target_yields || body_uses_yield(value)
        }
        ExprNode::Raise { value } => body_uses_yield(value),
        ExprNode::RescueModifier { expr, fallback } => {
            body_uses_yield(expr) || body_uses_yield(fallback)
        }
        ExprNode::Return { value } => body_uses_yield(value),
        ExprNode::Super { args } => args.as_ref().is_some_and(|a| a.iter().any(body_uses_yield)),
        ExprNode::BeginRescue { body, rescues, else_branch, ensure, .. } => {
            body_uses_yield(body)
                || rescues.iter().any(|r| body_uses_yield(&r.body))
                || else_branch.as_ref().is_some_and(|e| body_uses_yield(e))
                || ensure.as_ref().is_some_and(|e| body_uses_yield(e))
        }
        ExprNode::Next { value } => value.as_ref().is_some_and(body_uses_yield),
        ExprNode::MultiAssign { value, .. } => body_uses_yield(value),
        ExprNode::While { cond, body, .. } => body_uses_yield(cond) || body_uses_yield(body),
        ExprNode::Range { begin, end, .. } => {
            begin.as_ref().is_some_and(body_uses_yield) || end.as_ref().is_some_and(body_uses_yield)
        }
        ExprNode::Lit { .. }
        | ExprNode::Var { .. }
        | ExprNode::Ivar { .. }
        | ExprNode::Const { .. }
        | ExprNode::SelfRef => false,
    }
}

/// Ruby allows `?` and `!` suffixes on method names; TS does not.
/// Strip them for the output identifier. Juntos's runtime drops them
/// too (`Article.exists(id)` not `Article.exists?(id)`).
pub(super) fn sanitize_identifier(ruby_name: &str) -> String {
    ruby_name
        .trim_end_matches('?')
        .trim_end_matches('!')
        .to_string()
}

/// IR transformation applied to each class method body before emission.
/// Two pieces:
///  1. `Send { recv: None, ... }` (bare method call / implicit self)
///     gets `SelfRef` as an explicit receiver, so the TS output
///     becomes `this.method(...)` instead of a dangling `method(...)`.
///  2. `Super { args }` becomes a Send on a synthetic `super` receiver
///     with the enclosing method's name. TS needs
///     `super.methodName(args)`, not bare `super(...)`.
///
/// `enclosing_method` is the Ruby method name (may end in `=` for
/// setters). The `=` is dropped for the super-call target so the
/// method name is a valid TS identifier.
pub(super) fn rewrite_for_class_method(e: &Expr, enclosing_method: &str) -> Expr {
    let method_for_super = enclosing_method.trim_end_matches('=').to_string();
    rewrite(e, Some(&method_for_super))
}

/// Variant of `rewrite_for_class_method` that leaves `Super { args }`
/// nodes intact instead of rewriting them to `super.<method>(args)`.
/// Constructors use this: TS spells the parent-constructor call as
/// `super(args)`, not `super.initialize(args)`.
pub(super) fn rewrite_for_constructor(e: &Expr) -> Expr {
    rewrite(e, None)
}

fn rewrite(e: &Expr, super_method: Option<&str>) -> Expr {
    let new_node = match &*e.node {
        // `raise X, msg` is a Kernel-level call that target emitters
        // render as `throw new X(msg)`. Leaving it as Send-no-recv (no
        // SelfRef rewrite) lets the emit_send_with_parens special-case
        // for `raise` fire. Mirrors the parse-side carve-out in
        // `runtime_src::rewrite_bare_sends_to_self`; both are needed
        // because this function is also called from the app-level
        // emit path which doesn't go through the parse-side rewrite.
        ExprNode::Send { recv: None, method, args, block, parenthesized }
            if method.as_str() == "raise" =>
        {
            ExprNode::Send {
                recv: None,
                method: method.clone(),
                args: args.iter().map(|a| rewrite(a, super_method)).collect(),
                block: block.as_ref().map(|b| rewrite(b, super_method)),
                parenthesized: *parenthesized,
            }
        }
        ExprNode::Send { recv: None, method, args, block, parenthesized } => ExprNode::Send {
            recv: Some(Expr::new(Span::synthetic(), ExprNode::SelfRef)),
            method: method.clone(),
            args: args.iter().map(|a| rewrite(a, super_method)).collect(),
            block: block.as_ref().map(|b| rewrite(b, super_method)),
            parenthesized: *parenthesized,
        },
        ExprNode::Send { recv: Some(r), method, args, block, parenthesized } => ExprNode::Send {
            recv: Some(rewrite(r, super_method)),
            method: method.clone(),
            args: args.iter().map(|a| rewrite(a, super_method)).collect(),
            block: block.as_ref().map(|b| rewrite(b, super_method)),
            parenthesized: *parenthesized,
        },
        ExprNode::Super { args } => match super_method {
            None => {
                // Constructor mode: rewrite args (so bare-Send→self
                // applies inside super-args) but keep `Super` itself
                // intact — TS spells the parent-constructor call as
                // `super(args)`, not `super.initialize(args)`.
                let rewritten_args: Option<Vec<Expr>> = args
                    .as_ref()
                    .map(|v| v.iter().map(|a| rewrite(a, None)).collect());
                ExprNode::Super { args: rewritten_args }
            }
            Some(super_method) => {
                let super_recv = Expr::new(
                    Span::synthetic(),
                    ExprNode::Const { path: vec![Symbol::from("super")] },
                );
                let args_vec: Vec<Expr> = match args {
                    Some(v) => v
                        .iter()
                        .map(|a| rewrite(a, Some(super_method)))
                        .collect(),
                    None => vec![],
                };
                // Bare `super` (no args) calling a method that's a
                // getter in the base class needs property-access form,
                // not method call. Mirrors the per-name allowlist used
                // for emit-time getter-vs-method choice. With args,
                // always method form.
                let is_base_getter = matches!(
                    super_method,
                    "save" | "destroy" | "errors" | "attributes"
                );
                let parenthesized = !args_vec.is_empty() || !is_base_getter;
                ExprNode::Send {
                    recv: Some(super_recv),
                    method: Symbol::from(super_method.to_string()),
                    args: args_vec,
                    block: None,
                    parenthesized,
                }
            }
        },
        ExprNode::Seq { exprs } => ExprNode::Seq {
            exprs: exprs.iter().map(|c| rewrite(c, super_method)).collect(),
        },
        ExprNode::If { cond, then_branch, else_branch } => ExprNode::If {
            cond: rewrite(cond, super_method),
            then_branch: rewrite(then_branch, super_method),
            else_branch: rewrite(else_branch, super_method),
        },
        ExprNode::BoolOp { op, surface, left, right } => ExprNode::BoolOp {
            op: *op,
            surface: *surface,
            left: rewrite(left, super_method),
            right: rewrite(right, super_method),
        },
        ExprNode::Array { elements, style } => ExprNode::Array {
            elements: elements.iter().map(|c| rewrite(c, super_method)).collect(),
            style: *style,
        },
        ExprNode::Hash { entries, braced } => ExprNode::Hash {
            entries: entries
                .iter()
                .map(|(k, v)| (rewrite(k, super_method), rewrite(v, super_method)))
                .collect(),
            braced: *braced,
        },
        ExprNode::StringInterp { parts } => ExprNode::StringInterp {
            parts: parts
                .iter()
                .map(|p| match p {
                    InterpPart::Text { value } => InterpPart::Text { value: value.clone() },
                    InterpPart::Expr { expr } => InterpPart::Expr {
                        expr: rewrite(expr, super_method),
                    },
                })
                .collect(),
        },
        ExprNode::Lambda { params, block_param, body, block_style } => ExprNode::Lambda {
            params: params.clone(),
            block_param: block_param.clone(),
            body: rewrite(body, super_method),
            block_style: *block_style,
        },
        ExprNode::Apply { fun, args, block } => ExprNode::Apply {
            fun: rewrite(fun, super_method),
            args: args.iter().map(|a| rewrite(a, super_method)).collect(),
            block: block.as_ref().map(|b| rewrite(b, super_method)),
        },
        ExprNode::Assign { target, value } => {
            let new_target = match target {
                LValue::Var { id, name } => LValue::Var { id: *id, name: name.clone() },
                LValue::Ivar { name } => LValue::Ivar { name: name.clone() },
                LValue::Attr { recv, name } => LValue::Attr {
                    recv: rewrite(recv, super_method),
                    name: name.clone(),
                },
                LValue::Index { recv, index } => LValue::Index {
                    recv: rewrite(recv, super_method),
                    index: rewrite(index, super_method),
                },
            };
            ExprNode::Assign {
                target: new_target,
                value: rewrite(value, super_method),
            }
        }
        ExprNode::Yield { args } => ExprNode::Yield {
            args: args.iter().map(|a| rewrite(a, super_method)).collect(),
        },
        ExprNode::Raise { value } => ExprNode::Raise {
            value: rewrite(value, super_method),
        },
        ExprNode::RescueModifier { expr, fallback } => ExprNode::RescueModifier {
            expr: rewrite(expr, super_method),
            fallback: rewrite(fallback, super_method),
        },
        ExprNode::Return { value } => ExprNode::Return {
            value: rewrite(value, super_method),
        },
        ExprNode::BeginRescue { body, rescues, else_branch, ensure, implicit } => {
            ExprNode::BeginRescue {
                body: rewrite(body, super_method),
                rescues: rescues
                    .iter()
                    .map(|rc| RescueClause {
                        classes: rc.classes.iter().map(|c| rewrite(c, super_method)).collect(),
                        binding: rc.binding.clone(),
                        body: rewrite(&rc.body, super_method),
                    })
                    .collect(),
                else_branch: else_branch.as_ref().map(|b| rewrite(b, super_method)),
                ensure: ensure.as_ref().map(|b| rewrite(b, super_method)),
                implicit: *implicit,
            }
        }
        ExprNode::Case { scrutinee, arms } => ExprNode::Case {
            scrutinee: rewrite(scrutinee, super_method),
            arms: arms
                .iter()
                .map(|arm| crate::expr::Arm {
                    pattern: arm.pattern.clone(),
                    guard: arm.guard.as_ref().map(|g| rewrite(g, super_method)),
                    body: rewrite(&arm.body, super_method),
                })
                .collect(),
        },
        ExprNode::Let { id, name, value, body } => ExprNode::Let {
            id: *id,
            name: name.clone(),
            value: rewrite(value, super_method),
            body: rewrite(body, super_method),
        },
        ExprNode::Next { value } => ExprNode::Next {
            value: value.as_ref().map(|v| rewrite(v, super_method)),
        },
        ExprNode::MultiAssign { targets, value } => ExprNode::MultiAssign {
            targets: targets.clone(),
            value: rewrite(value, super_method),
        },
        ExprNode::While { cond, body, until_form } => ExprNode::While {
            cond: rewrite(cond, super_method),
            body: rewrite(body, super_method),
            until_form: *until_form,
        },
        ExprNode::Range { begin, end, exclusive } => ExprNode::Range {
            begin: begin.as_ref().map(|b| rewrite(b, super_method)),
            end: end.as_ref().map(|e| rewrite(e, super_method)),
            exclusive: *exclusive,
        },
        // Leaves pass through unchanged.
        ExprNode::Lit { .. }
        | ExprNode::Var { .. }
        | ExprNode::Ivar { .. }
        | ExprNode::Const { .. }
        | ExprNode::SelfRef => (*e.node).clone(),
    };

    // Silence unused-fn warning on the old passthrough helper.
    let _ = emit_expr as fn(_) -> _;

    Expr {
        span: e.span,
        node: Box::new(new_node),
        ty: e.ty.clone(),
        effects: e.effects.clone(),
        leading_blank_line: e.leading_blank_line,
        diagnostic: e.diagnostic.clone(),
    }
}
