//! Library-shape emission — kind-agnostic LibraryClass walker.
//!
//! After Phase B of the TS rewrite, this is the *only* code path that
//! turns an IR class into a TS file. All inputs (lowered models,
//! lowered views, lowered controllers, `app.library_classes`) reach
//! the emitter as `LibraryClass` and flow through `emit_class_file`.
//! No per-output-kind machinery: schema/routes/importmap are expected
//! to land here once their lowerers exist.
//!
//! `emit_class_file` does two things: collect imports (juntos exports
//! + sibling models / library_classes referenced in method bodies)
//! and delegate to `super::emit_library_class` for the class body.
//! That body renderer (in `typescript.rs`) handles attr_reader/writer
//! collapse, identifier sanitization, super translation, and
//! Ty-signature-driven param + return types.

use std::collections::BTreeSet;
use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use crate::App;
use crate::dialect::LibraryClass;
use crate::expr::{Expr, ExprNode, InterpPart, LValue, RescueClause};
use crate::ident::Symbol;
use crate::span::Span;

/// Build `(ClassId, ClassInfo)` pairs from a slice of
/// LibraryFunctions. Groups functions by module_path so all
/// `RouteHelpers.*` (or `Schema.*`, etc.) functions register under
/// one ClassId, mirroring `extras_from_lcs`. Each function becomes
/// a class-method entry whose Ty is the function's signature.
pub(super) fn extras_from_funcs(
    funcs: &[crate::dialect::LibraryFunction],
) -> Vec<(crate::ident::ClassId, crate::analyze::ClassInfo)> {
    use crate::ident::{ClassId, Symbol};
    let mut grouped: std::collections::HashMap<ClassId, crate::analyze::ClassInfo> =
        std::collections::HashMap::new();
    for func in funcs {
        let raw = func
            .module_path
            .iter()
            .map(|s| s.as_str())
            .collect::<Vec<_>>()
            .join("::");
        let id = ClassId(Symbol::from(raw));
        let info = grouped.entry(id).or_default();
        if let Some(sig) = &func.signature {
            info.class_methods.insert(func.name.clone(), sig.clone());
            info.class_method_kinds.insert(
                func.name.clone(),
                crate::dialect::AccessorKind::Method,
            );
        }
    }
    let mut out: Vec<(ClassId, crate::analyze::ClassInfo)> = Vec::new();
    for (full_id, info) in grouped {
        let raw = full_id.0.as_str();
        let last = raw.rsplit("::").next().unwrap_or(raw).to_string();
        if last != raw {
            let mut alias = crate::analyze::ClassInfo::default();
            alias.class_methods = info.class_methods.clone();
            alias.class_method_kinds = info.class_method_kinds.clone();
            out.push((ClassId(Symbol::from(last)), alias));
        }
        out.push((full_id, info));
    }
    out
}

/// Emit a group of LibraryFunctions sharing the same module_path as
/// a single TS file. Each function becomes a top-level
/// `export function` AND a namespace-const member, so both
/// `RouteHelpers.foo()` (member access via the const) and
/// `import { foo }` (direct function import) work.
pub(super) fn emit_module_file(
    funcs: &[crate::dialect::LibraryFunction],
    app: &App,
    out_path: PathBuf,
) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();

    // Collect imports across every function's body. The synthesized
    // wrapper class stays in scope only long enough for render_imports
    // to walk the bodies — it's never written to the output.
    let synthetic_lc = synthesize_module_lc(funcs);
    let imports = render_imports(&synthetic_lc, app, &out_path);
    if !imports.is_empty() {
        s.push_str(&imports);
        writeln!(s).unwrap();
    }

    let mut exported_names: Vec<(String, String)> = Vec::new();
    // (key_in_namespace, exported_identifier)
    for func in funcs {
        match super::emit_library_function(func) {
            Ok(body) => {
                s.push_str(&body);
                s.push('\n');
            }
            Err(e) => writeln!(s, "// EMIT ERROR: {e}").unwrap(),
        }
        let raw = func.name.as_str();
        let key = raw.to_string();
        let escaped = super::escape_for_function_name(raw);
        exported_names.push((key, escaped));
    }

    // Namespace const so existing `RouteHelpers.foo()` call sites
    // resolve via member access. Last segment of the module path is
    // the const name (`Views::Articles` → `Articles` would conflict
    // here; module artifacts always have a single-segment path).
    if let Some(module_name) = funcs
        .first()
        .and_then(|f| f.module_path.last())
        .map(|s| s.as_str().to_string())
    {
        s.push_str(&format!("export const {module_name} = {{\n"));
        for (i, (key, exported)) in exported_names.iter().enumerate() {
            let comma = if i + 1 < exported_names.len() { "," } else { "" };
            if key == exported {
                s.push_str(&format!("  {key}{comma}\n"));
            } else {
                s.push_str(&format!("  {key}: {exported}{comma}\n"));
            }
        }
        s.push_str("};\n");
    }

    EmittedFile {
        path: out_path,
        content: s,
    }
}

/// Wrap a function group as a synthetic LibraryClass whose methods
/// are the functions, used solely so `render_imports` can walk the
/// bodies the same way it does for class-shaped artifacts.
fn synthesize_module_lc(
    funcs: &[crate::dialect::LibraryFunction],
) -> LibraryClass {
    use crate::ident::{ClassId, Symbol};
    let module_id = funcs
        .first()
        .map(|f| {
            ClassId(Symbol::from(
                f.module_path
                    .iter()
                    .map(|s| s.as_str())
                    .collect::<Vec<_>>()
                    .join("::"),
            ))
        })
        .unwrap_or_else(|| ClassId(Symbol::from("")));
    let methods: Vec<crate::dialect::MethodDef> = funcs
        .iter()
        .map(|f| crate::dialect::MethodDef {
            name: f.name.clone(),
            receiver: crate::dialect::MethodReceiver::Class,
            params: f.params.clone(),
            body: f.body.clone(),
            signature: f.signature.clone(),
            effects: f.effects.clone(),
            enclosing_class: Some(module_id.0.clone()),
            kind: crate::dialect::AccessorKind::Method,
        })
        .collect();
    LibraryClass {
        name: module_id,
        is_module: true,
        parent: None,
        includes: Vec::new(),
        methods,
        origin: None,
    }
}

/// Build `(ClassId, ClassInfo)` pairs from a slice of LibraryClasses
/// for use as `extras` to a downstream bulk lowerer. Folds methods
/// across same-named classes (e.g., view modules from the same dir
/// share a `Views::X` ClassId) and registers under both the full
/// ClassId and a last-segment alias for the typer's Const-path
/// resolver. Used by emit() to thread a shared registry through
/// model → controller → test lowerings.
pub(super) fn extras_from_lcs(
    lcs: &[LibraryClass],
) -> Vec<(crate::ident::ClassId, crate::analyze::ClassInfo)> {
    let mut grouped: std::collections::HashMap<
        crate::ident::ClassId,
        crate::analyze::ClassInfo,
    > = std::collections::HashMap::new();
    for lc in lcs {
        let info = grouped.entry(lc.name.clone()).or_default();
        let from = crate::lower::class_info_from_library_class(lc);
        for (k, v) in from.class_methods {
            info.class_methods.insert(k, v);
        }
        for (k, v) in from.instance_methods {
            info.instance_methods.insert(k, v);
        }
        for (k, v) in from.class_method_kinds {
            info.class_method_kinds.insert(k, v);
        }
        for (k, v) in from.instance_method_kinds {
            info.instance_method_kinds.insert(k, v);
        }
    }
    let mut out: Vec<(crate::ident::ClassId, crate::analyze::ClassInfo)> = Vec::new();
    for (full_id, info) in grouped {
        let raw = full_id.0.as_str();
        let last = raw.rsplit("::").next().unwrap_or(raw).to_string();
        if last != raw {
            let mut alias = crate::analyze::ClassInfo::default();
            alias.class_methods = info.class_methods.clone();
            alias.instance_methods = info.instance_methods.clone();
            alias.class_method_kinds = info.class_method_kinds.clone();
            alias.instance_method_kinds = info.instance_method_kinds.clone();
            out.push((crate::ident::ClassId(crate::ident::Symbol::from(last)), alias));
        }
        out.push((full_id, info));
    }
    out
}

/// Emit one `LibraryFunction` as a TS source file at `out_path`.
/// Used by `emit()` for lowered views (one template = one function);
/// other module-of-functions artifacts will migrate here as their
/// lowerers move from LibraryClass-with-class-methods to
/// LibraryFunction.
///
/// Output shape:
///   `// Generated by Roundhouse.`
///   imports (resolved via `render_imports_for_function`)
///   `export function <name>(<params>): <ret> { <body> }`
///
/// Body emission reuses the class-method machinery
/// (`super::emit_function_member`) which handles param typing, body
/// typing, and the same `super`-rewrite plumbing — minus the
/// SelfRef-injection that's specific to instance methods.
pub(super) fn emit_function_file(
    func: &crate::dialect::LibraryFunction,
    app: &App,
    out_path: PathBuf,
) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();

    let imports = render_imports_for_function(func, app, &out_path);
    if !imports.is_empty() {
        s.push_str(&imports);
        writeln!(s).unwrap();
    }

    match super::emit_library_function(func) {
        Ok(body) => s.push_str(&body),
        Err(e) => writeln!(s, "// EMIT ERROR: {e}").unwrap(),
    }

    EmittedFile {
        path: out_path,
        content: s,
    }
}

/// Build the per-app `Views` aggregator at `app/views.ts`. Imports
/// every view function and assembles them into a single `Views`
/// const whose keys mirror the Ruby module path (`Views::Articles`
/// → `Views.Articles`). Consumers (controllers) reach view methods
/// through this aggregator: `Views.Articles.article(record)`.
pub(super) fn emit_views_aggregator(
    views: &[crate::dialect::View],
    funcs: &[crate::dialect::LibraryFunction],
) -> EmittedFile {
    use std::collections::BTreeMap;

    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();

    // One import line per template file — alias each function to a
    // unique local name so collisions (`articles_index` vs
    // `comments_index`) don't shadow each other.
    let mut alias_map: Vec<(String, String, String)> = Vec::new();
    // (alias, import_path, fn_name)
    let mut grouped: BTreeMap<Vec<String>, Vec<(String, String)>> = BTreeMap::new();
    // module_path_segments → Vec<(fn_name, alias)>
    for (view, func) in views.iter().zip(funcs.iter()) {
        let alias = mangle_alias(view.name.as_str(), func.name.as_str());
        let import_path = format!(
            "./{}.js",
            view_module_import_subpath(view.name.as_str())
        );
        alias_map.push((alias.clone(), import_path, func.name.as_str().to_string()));
        let segments: Vec<String> = func
            .module_path
            .iter()
            .map(|s| s.as_str().to_string())
            .collect();
        grouped
            .entry(segments)
            .or_default()
            .push((func.name.as_str().to_string(), alias));
    }

    for (alias, import_path, fn_name) in &alias_map {
        // The function was emitted under its escaped name (e.g.
        // `new` → `new_`), so the import has to match the escaped
        // form. Apply the same escape here for consistency.
        let escaped_fn = escape_for_import(fn_name);
        if &escaped_fn == alias {
            writeln!(s, "import {{ {escaped_fn} }} from \"{import_path}\";").unwrap();
        } else {
            writeln!(
                s,
                "import {{ {escaped_fn} as {alias} }} from \"{import_path}\";"
            )
            .unwrap();
        }
    }
    writeln!(s).unwrap();
    s.push_str("export const Views = ");
    write_namespace_object(&mut s, &grouped, &[], 0);
    s.push_str(";\n");

    EmittedFile {
        path: PathBuf::from("app/views.ts"),
        content: s,
    }
}

/// Recursive object literal emitter for the Views aggregator.
/// Produces `{ Articles: { article, index, ... }, Comments: {...} }`
/// — collapsing `Views::Articles` paths into nested object keys.
fn write_namespace_object(
    out: &mut String,
    grouped: &std::collections::BTreeMap<Vec<String>, Vec<(String, String)>>,
    prefix: &[String],
    depth: usize,
) {
    use std::collections::BTreeSet;
    let indent = "  ".repeat(depth);
    let inner_indent = "  ".repeat(depth + 1);

    // Direct functions at this level (module_path == prefix + [Views] basically).
    // Find groups whose path starts with prefix.
    let mut child_keys: BTreeSet<String> = BTreeSet::new();
    let mut direct: Vec<(String, String)> = Vec::new();
    for (path, fns) in grouped {
        // Skip "Views" leading segment when prefix is empty (the
        // aggregator is rooted at `Views`, so `["Views","Articles"]`
        // becomes the `Articles` key).
        let stripped: &[String] = if prefix.is_empty() {
            if path.first().map(|s| s.as_str()) == Some("Views") {
                &path[1..]
            } else {
                path
            }
        } else if path.starts_with(prefix) {
            &path[prefix.len()..]
        } else {
            continue;
        };
        if stripped.is_empty() {
            for f in fns {
                direct.push(f.clone());
            }
        } else {
            child_keys.insert(stripped[0].clone());
        }
    }

    out.push_str("{\n");
    let mut first = true;
    for (fn_name, alias) in &direct {
        if !first {
            out.push_str(",\n");
        }
        first = false;
        if fn_name == alias {
            out.push_str(&format!("{inner_indent}{fn_name}"));
        } else {
            out.push_str(&format!("{inner_indent}{fn_name}: {alias}"));
        }
    }
    for child in &child_keys {
        if !first {
            out.push_str(",\n");
        }
        first = false;
        let mut new_prefix: Vec<String> = if prefix.is_empty() {
            vec!["Views".to_string()]
        } else {
            prefix.to_vec()
        };
        new_prefix.push(child.clone());
        out.push_str(&format!("{inner_indent}{child}: "));
        write_namespace_object(out, grouped, &new_prefix, depth + 1);
    }
    out.push('\n');
    out.push_str(&format!("{indent}}}"));
}

/// Mangle a per-template alias used inside `app/views.ts` to avoid
/// import collisions (`index` from articles AND comments). Form:
/// `<dir1>_<dir2>_..._<fn>` from the view path's directories +
/// function name.
fn mangle_alias(view_name: &str, fn_name: &str) -> String {
    let mut parts: Vec<String> = view_name
        .split('/')
        .filter(|s| !s.is_empty())
        .take_while(|_| true)
        .map(|s| s.trim_start_matches('_').to_string())
        .collect();
    // Drop the last segment (the file name); replace with fn_name.
    parts.pop();
    parts.push(fn_name.to_string());
    parts.join("_")
}

/// `articles/_article` → `views/articles/_article` (path under
/// `app/`). Used by the aggregator to compute import paths.
fn view_module_import_subpath(view_name: &str) -> String {
    format!("views/{view_name}")
}

/// Mirror the per-function-name escape applied by
/// `emit_library_function` so the aggregator's import names match
/// the actual exported identifiers. Limited subset that's been
/// observed in practice (Rails action `new`); extend as needed.
fn escape_for_import(name: &str) -> String {
    if matches!(name, "new" | "default" | "delete" | "class" | "function") {
        format!("{name}_")
    } else {
        name.to_string()
    }
}

/// Compute imports for a view function file. Same logic as
/// `render_imports` but specialized to a function (no parent class,
/// no class-level fields). Walks the body collecting Const refs and
/// resolves them via the same buckets (juntos / models / fixtures /
/// route helpers / the new view aggregator).
fn render_imports_for_function(
    func: &crate::dialect::LibraryFunction,
    app: &App,
    out_path: &std::path::Path,
) -> String {
    // Synthesize a one-method LibraryClass so we can reuse render_imports
    // verbatim. The synthesized class never reaches the file output —
    // only its method body is walked for refs.
    let synthetic_lc = LibraryClass {
        name: crate::ident::ClassId(crate::ident::Symbol::from(
            func.module_path
                .iter()
                .map(|s| s.as_str())
                .collect::<Vec<_>>()
                .join("::"),
        )),
        is_module: true,
        parent: None,
        includes: Vec::new(),
        methods: vec![crate::dialect::MethodDef {
            name: func.name.clone(),
            receiver: crate::dialect::MethodReceiver::Class,
            params: func.params.clone(),
            body: func.body.clone(),
            signature: func.signature.clone(),
            effects: func.effects.clone(),
            enclosing_class: Some(crate::ident::Symbol::from(
                func.module_path
                    .iter()
                    .map(|s| s.as_str())
                    .collect::<Vec<_>>()
                    .join("::"),
            )),
            kind: crate::dialect::AccessorKind::Method,
        }],
        origin: None,
    };
    render_imports(&synthetic_lc, app, out_path)
}

/// Emit one `LibraryClass` as a TS source file at `out_path`. The
/// universal entry point — used by `emit()` for lowered models, lowered
/// views, and `app.library_classes` alike.
pub(super) fn emit_class_file(
    lc: &LibraryClass,
    app: &App,
    out_path: PathBuf,
) -> EmittedFile {
    emit_class_file_with_synthesized(lc, app, out_path, &[])
}

/// Variant that recognizes additional synthesized class names as
/// sibling model imports. Used by the lowered-model emit path so
/// references to `<Model>Row` / `<Resource>Params` (which aren't in
/// `app.library_classes`) resolve to `./<stem>.js` imports.
pub(super) fn emit_class_file_with_synthesized(
    lc: &LibraryClass,
    app: &App,
    out_path: PathBuf,
    synthesized: &[String],
) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();

    let imports = render_imports_with_synthesized(lc, app, &out_path, synthesized);
    if !imports.is_empty() {
        s.push_str(&imports);
        writeln!(s).unwrap();
    }

    match super::emit_library_class(lc) {
        Ok(body) => s.push_str(&body),
        Err(e) => writeln!(s, "// EMIT ERROR: {e}").unwrap(),
    }

    EmittedFile {
        path: out_path,
        content: s,
    }
}

/// Number of `../` hops needed to escape the directory containing
/// `out_path` back to the project root. `app/models/x.ts` → 2 hops
/// up; `test/x.test.ts` → 1; root-level `x.ts` → 0.
fn dir_depth(out_path: &std::path::Path) -> usize {
    out_path.parent().map(|p| p.components().count()).unwrap_or(0)
}

fn relative_to_root(out_path: &std::path::Path, target: &str) -> String {
    let depth = dir_depth(out_path);
    if depth == 0 {
        return format!("./{target}");
    }
    let mut s = String::new();
    for _ in 0..depth {
        s.push_str("../");
    }
    s.push_str(target);
    s
}

/// Names exported from `juntos.ts` that library-class bodies may
/// reference. Anything else not found among siblings is silently
/// skipped from the import list (safer than emitting broken imports).
///
/// `ApplicationRecord` was here historically — kept removed because
/// real-blog (and any Rails app) defines its own
/// `app/models/application_record.rb` so the local-model lookup
/// further down should resolve it. Likewise `ActiveRecord` lives in
/// the transpiled `src/active_record_base.ts` now (via the
/// `ActiveRecordBase` aliased import), not in juntos.
const JUNTOS_EXPORTS: &[&str] = &[
    "CollectionProxy",
    "ErrorCollection",
    "Reference",
    "Router",
    "modelRegistry",
    "conn",
    "installDb",
    "setupTestDb",
    "InMemoryActiveRecordAdapter",
];

/// Compute the import block for a class: scan method bodies for Const
/// references, partition into juntos-provided names vs sibling models /
/// library_classes vs unknown (skipped). Also imports the parent class
/// when it's a juntos export.
fn render_imports(lc: &LibraryClass, app: &App, out_path: &std::path::Path) -> String {
    render_imports_with_synthesized(lc, app, out_path, &[])
}

fn render_imports_with_synthesized(
    lc: &LibraryClass,
    app: &App,
    out_path: &std::path::Path,
    synthesized: &[String],
) -> String {
    let name = lc.name.0.as_str();

    let mut refs: BTreeSet<String> = BTreeSet::new();
    for m in &lc.methods {
        collect_class_refs(&m.body, &mut refs);
        // Also harvest class references from the method's signature
        // (param types + return type). View functions like
        // `function article(article: Article): string` mention
        // `Article` only as a type annotation; without this, the
        // body walker misses it and the file emits without an
        // import → TS2304 Cannot find name 'Article'.
        if let Some(sig) = &m.signature {
            collect_ty_class_refs(sig, &mut refs);
        }
        // Walk @ivar = <expr> assignments inside method bodies and
        // collect class refs from the assigned expressions' types —
        // these surface as `declare <name>: <Class>;` field
        // declarations on the class, and the type annotation needs
        // its class imported. Without this, a test class that
        // declares `declare article: Article;` from
        // `@article = ArticlesFixtures.one()` would emit without an
        // `import { Article }` line and trip TS2304.
        collect_ivar_assignment_class_refs(&m.body, &mut refs);
    }
    if let Some(p) = &lc.parent {
        let raw = p.0.as_str();
        let import_name = match raw {
            "ActiveRecord::Base" => "ActiveRecordBase".to_string(),
            "StandardError" => String::new(), // TS builtin Error, no import
            // Test parents — the runtime adapter exports both the
            // `TestCase` (Rails) and `Test` (Minitest) names; emit a
            // last-segment import that resolves through the runtime
            // path special-case below.
            "ActiveSupport::TestCase" | "ActionDispatch::IntegrationTest" => "TestCase".to_string(),
            "Minitest::Test" => "Test".to_string(),
            // Controller base — runtime exports `Base` from
            // `action_controller_base.ts`; we route through an aliased
            // name (`ActionControllerBase`) so the `extends` clause
            // reads clearly.
            "ActionController::Base" | "ActionController::API" => {
                "ActionControllerBase".to_string()
            }
            _ => raw.rsplit("::").next().unwrap_or(raw).to_string(),
        };
        if !import_name.is_empty() {
            refs.insert(import_name);
        }
    }
    refs.remove(name);

    let mut juntos_imports: Vec<String> = Vec::new();
    let mut model_imports: Vec<(String, String)> = Vec::new();
    let mut runtime_imports: Vec<String> = Vec::new();
    let mut fixture_imports: Vec<(String, String)> = Vec::new();
    let mut controller_imports: Vec<(String, String)> = Vec::new();
    let mut controller_base_import: bool = false;
    let mut active_record_base_import: bool = false;
    let mut route_helpers_import: bool = false;
    let mut views_import: bool = false;
    let mut view_helpers_import: bool = false;
    let mut inflector_import: bool = false;
    let mut broadcasts_import: bool = false;
    let mut importmap_import: bool = false;

    for r in refs {
        let r_str: &str = &r;
        if JUNTOS_EXPORTS.contains(&r_str) {
            juntos_imports.push(r);
        } else if r == "Test" || r == "TestCase" {
            runtime_imports.push(r);
        } else if r == "ActionControllerBase" {
            controller_base_import = true;
        } else if r == "ActiveRecordBase" {
            // Transpiled framework Base — `ApplicationRecord extends Base`
            // resolves through this aliased import. Same pattern as
            // ActionControllerBase: the runtime exports `Base` from
            // `src/active_record_base.ts`; the alias keeps the
            // `extends` clause readable.
            active_record_base_import = true;
        } else if r == "RouteHelpers" {
            // RouteHelpers is generated by routes_to_library and emitted
            // to app/route_helpers.ts; recognize it here so controller /
            // view bodies that call `RouteHelpers.<x>_path(...)` get the
            // import.
            route_helpers_import = true;
        } else if r == "Views" {
            // Views is the per-app aggregator emitted to app/views.ts;
            // controller bodies that call `Views.Articles.index(...)`
            // resolve through this single namespace import.
            views_import = true;
        } else if r == "ViewHelpers" {
            // Framework view helpers — class with snake-cased static
            // methods (`ViewHelpers.link_to(...)`) shipped at
            // `src/view_helpers.ts`.
            view_helpers_import = true;
        } else if r == "Inflector" {
            // Free-function module — view bodies use namespace access
            // (`Inflector.pluralize(...)`); import as `* as Inflector`
            // from `src/inflector.ts`.
            inflector_import = true;
        } else if r == "Broadcasts" {
            // Broadcasts shim — model after_create/update/destroy
            // bodies call `Broadcasts.prepend({...})` etc. The runtime
            // file at `src/broadcasts.ts` adapts to the installed
            // broadcaster.
            broadcasts_import = true;
        } else if r == "Importmap" {
            // Importmap is generated at app/importmap.ts by the
            // importmap lowerer. Layout view body uses
            // `Importmap.pins()` / `Importmap.entry()`.
            importmap_import = true;
        } else if app.models.iter().any(|m| m.name.0.as_str() == r) {
            let stem = crate::naming::snake_case(&r);
            model_imports.push((r, stem));
        } else if app.library_classes.iter().any(|other| other.name.0.as_str() == r) {
            let stem = crate::naming::snake_case(&r);
            model_imports.push((r, stem));
        } else if synthesized.iter().any(|s| s == &r) {
            // Synthesized siblings (`<Model>Row`, `<Resource>Params`)
            // aren't in app.library_classes — they're produced by the
            // lowerer alongside the source-derived classes. Recognize
            // them here so `Article.from_row(ArticleRow.from_raw(row))`
            // resolves to a sibling import in the emitted file.
            let stem = crate::naming::snake_case(&r);
            model_imports.push((r, stem));
        } else if app.controllers.iter().any(|c| c.name.0.as_str() == r) {
            let stem = crate::naming::snake_case(&r);
            controller_imports.push((r, stem));
        } else if let Some(fixture_stem) = r.strip_suffix("Fixtures") {
            // `<Plural>Fixtures` ↔ `test/fixtures/<plural>.ts`. The
            // fixture-call rewrite produces these Const references on
            // every test body that uses `articles(:one)`-style helpers.
            let plural = crate::naming::snake_case(fixture_stem);
            if app.fixtures.iter().any(|f| f.name.as_str() == plural) {
                fixture_imports.push((r, plural));
            }
        }
    }

    let mut s = String::new();
    if !juntos_imports.is_empty() {
        writeln!(
            s,
            "import {{ {} }} from \"juntos\";",
            juntos_imports.join(", ")
        )
        .unwrap();
    }
    if !runtime_imports.is_empty() {
        // Test files live under test/; the runtime adapter is at
        // test/_runtime/minitest.ts. Compute path: relative to the
        // test file's parent dir, the runtime is `./_runtime/minitest.js`.
        // For non-test files (which shouldn't import TestCase but
        // we handle defensively), use root-relative.
        let runtime_path = if out_path.starts_with("test") {
            "./_runtime/minitest.js".to_string()
        } else {
            relative_to_root(out_path, "test/_runtime/minitest.js")
        };
        writeln!(
            s,
            "import {{ {} }} from \"{runtime_path}\";",
            runtime_imports.join(", "),
        )
        .unwrap();
    }
    for (n, stem) in &model_imports {
        // Models live at app/models/<stem>.ts. Test files at
        // test/<stem>.test.ts need `../app/models/<stem>.js`; views at
        // app/views/<dir>/<base>.ts need `../../app/models/<stem>.js`;
        // models in the same dir use `./<stem>.js`.
        let import_path = if out_path.starts_with("app/models") {
            format!("./{stem}.js")
        } else {
            relative_to_root(out_path, &format!("app/models/{stem}.js"))
        };
        writeln!(s, "import {{ {n} }} from \"{import_path}\";").unwrap();
    }
    for (n, stem) in &fixture_imports {
        // Fixtures live at test/fixtures/<stem>.ts. Test files at
        // test/<x>.test.ts use `./fixtures/<stem>.js`; nested test
        // files (test/integration/<x>.test.ts) need root-relative.
        let import_path = if out_path.starts_with("test")
            && out_path.parent().map(|p| p.to_str() == Some("test")).unwrap_or(false)
        {
            format!("./fixtures/{stem}.js")
        } else {
            relative_to_root(out_path, &format!("test/fixtures/{stem}.js"))
        };
        writeln!(s, "import {{ {n} }} from \"{import_path}\";").unwrap();
    }
    for (n, stem) in &controller_imports {
        // Controllers live at app/controllers/<stem>.ts. Same-dir
        // imports (controller → controller, e.g. ApplicationController)
        // use `./<stem>.js`; otherwise root-relative.
        let import_path = if out_path.starts_with("app/controllers") {
            format!("./{stem}.js")
        } else {
            relative_to_root(out_path, &format!("app/controllers/{stem}.js"))
        };
        writeln!(s, "import {{ {n} }} from \"{import_path}\";").unwrap();
    }
    if controller_base_import {
        // ActionController::Base lives in the runtime as `Base` from
        // `src/action_controller_base.ts`; import-as-rename so the
        // emitted `extends ActionControllerBase` reads cleanly.
        let runtime_path = relative_to_root(out_path, "src/action_controller_base.js");
        writeln!(
            s,
            "import {{ Base as ActionControllerBase }} from \"{runtime_path}\";",
        )
        .unwrap();
    }
    if active_record_base_import {
        // ActiveRecord::Base lives in the runtime as `Base` from
        // `src/active_record_base.ts`; aliased so the emitted
        // `extends ActiveRecordBase` reads cleanly. Replaces the prior
        // route through juntos's hand-written `ApplicationRecord` —
        // models now inherit from the transpiled framework directly.
        let runtime_path = relative_to_root(out_path, "src/active_record_base.js");
        writeln!(
            s,
            "import {{ Base as ActiveRecordBase }} from \"{runtime_path}\";",
        )
        .unwrap();
    }
    if route_helpers_import {
        // routes_to_library emits the per-app helpers to
        // `app/route_helpers.ts`. Same-dir for files in app/, relative
        // for everything else (controllers in app/controllers, views
        // in app/views/<dir>, tests in test/).
        let import_path = if out_path.starts_with("app")
            && out_path.parent().map(|p| p.to_str() == Some("app")).unwrap_or(false)
        {
            "./route_helpers.js".to_string()
        } else {
            relative_to_root(out_path, "app/route_helpers.js")
        };
        writeln!(s, "import {{ RouteHelpers }} from \"{import_path}\";").unwrap();
    }
    if views_import {
        // The Views aggregator lives at app/views.ts; same-dir
        // resolution for files at the app/ root, relative-from-root
        // for nested files (controllers in app/controllers, etc.).
        let import_path = if out_path.starts_with("app")
            && out_path.parent().map(|p| p.to_str() == Some("app")).unwrap_or(false)
        {
            "./views.js".to_string()
        } else {
            relative_to_root(out_path, "app/views.js")
        };
        writeln!(s, "import {{ Views }} from \"{import_path}\";").unwrap();
    }
    if view_helpers_import {
        let import_path = relative_to_root(out_path, "src/view_helpers.js");
        writeln!(s, "import {{ ViewHelpers }} from \"{import_path}\";").unwrap();
    }
    if inflector_import {
        // Inflector is a module of free functions; namespace import
        // so call sites stay `Inflector.pluralize(...)` etc.
        let import_path = relative_to_root(out_path, "src/inflector.js");
        writeln!(s, "import * as Inflector from \"{import_path}\";").unwrap();
    }
    if broadcasts_import {
        let import_path = relative_to_root(out_path, "src/broadcasts.js");
        writeln!(s, "import {{ Broadcasts }} from \"{import_path}\";").unwrap();
    }
    if importmap_import {
        let import_path = relative_to_root(out_path, "app/importmap.js");
        writeln!(s, "import {{ Importmap }} from \"{import_path}\";").unwrap();
    }
    s
}

/// Walk an expression tree collecting top-level Const references —
/// the leading segment of a `path` is what gets imported (Ruby's
/// `Foo::Bar` uses `Foo` as the resolved name; we don't import inner
/// segments).
/// Walk a Ty collecting `Ty::Class { id }` first-segment names and
/// the same from any nested types. Used to surface model references
/// that appear only in method signatures (param types, return types)
/// — the body walker doesn't see these, so a view like
/// `def self.article(article)` typed as `(Article) -> String`
/// would have no Const ref to Article anywhere in the IR's body.
fn collect_ty_class_refs(ty: &crate::ty::Ty, out: &mut BTreeSet<String>) {
    use crate::ty::Ty;
    match ty {
        Ty::Class { id, args } => {
            // Take the first `::`-separated segment, matching how
            // `collect_class_refs` handles Const paths.
            let raw = id.0.as_str();
            let first = raw.split("::").next().unwrap_or(raw);
            out.insert(first.to_string());
            for a in args {
                collect_ty_class_refs(a, out);
            }
        }
        Ty::Array { elem } => collect_ty_class_refs(elem, out),
        Ty::Hash { key, value } => {
            collect_ty_class_refs(key, out);
            collect_ty_class_refs(value, out);
        }
        Ty::Union { variants } => {
            for v in variants {
                collect_ty_class_refs(v, out);
            }
        }
        Ty::Fn { params, block, ret, .. } => {
            for p in params {
                collect_ty_class_refs(&p.ty, out);
            }
            if let Some(b) = block {
                collect_ty_class_refs(b, out);
            }
            collect_ty_class_refs(ret, out);
        }
        _ => {}
    }
}

/// Walk `@ivar = <expr>` assignments and harvest class refs from
/// the assigned expressions' types. Each ivar assignment surfaces
/// in the emitted class as a `declare <name>: <Class>;` field
/// declaration; we need to import `<Class>` so the annotation
/// resolves.
fn collect_ivar_assignment_class_refs(e: &Expr, out: &mut BTreeSet<String>) {
    use crate::expr::LValue;
    match &*e.node {
        ExprNode::Assign { target: LValue::Ivar { .. }, value } => {
            if let Some(ty) = &value.ty {
                collect_ty_class_refs(ty, out);
            }
            collect_ivar_assignment_class_refs(value, out);
        }
        ExprNode::Assign { target, value } => {
            if let LValue::Attr { recv, .. } | LValue::Index { recv, .. } = target {
                collect_ivar_assignment_class_refs(recv, out);
            }
            collect_ivar_assignment_class_refs(value, out);
        }
        ExprNode::Send { recv, args, block, .. } => {
            if let Some(r) = recv {
                collect_ivar_assignment_class_refs(r, out);
            }
            for a in args {
                collect_ivar_assignment_class_refs(a, out);
            }
            if let Some(b) = block {
                collect_ivar_assignment_class_refs(b, out);
            }
        }
        ExprNode::Apply { fun, args, block } => {
            collect_ivar_assignment_class_refs(fun, out);
            for a in args {
                collect_ivar_assignment_class_refs(a, out);
            }
            if let Some(b) = block {
                collect_ivar_assignment_class_refs(b, out);
            }
        }
        ExprNode::Seq { exprs } => {
            for x in exprs {
                collect_ivar_assignment_class_refs(x, out);
            }
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            collect_ivar_assignment_class_refs(cond, out);
            collect_ivar_assignment_class_refs(then_branch, out);
            collect_ivar_assignment_class_refs(else_branch, out);
        }
        ExprNode::BeginRescue { body, rescues, else_branch, ensure, .. } => {
            collect_ivar_assignment_class_refs(body, out);
            for r in rescues {
                collect_ivar_assignment_class_refs(&r.body, out);
            }
            if let Some(b) = else_branch {
                collect_ivar_assignment_class_refs(b, out);
            }
            if let Some(b) = ensure {
                collect_ivar_assignment_class_refs(b, out);
            }
        }
        ExprNode::While { cond, body, .. } => {
            collect_ivar_assignment_class_refs(cond, out);
            collect_ivar_assignment_class_refs(body, out);
        }
        ExprNode::Case { scrutinee, arms } => {
            collect_ivar_assignment_class_refs(scrutinee, out);
            for arm in arms {
                collect_ivar_assignment_class_refs(&arm.body, out);
            }
        }
        ExprNode::Lambda { body, .. } => collect_ivar_assignment_class_refs(body, out),
        ExprNode::Let { value, body, .. } => {
            collect_ivar_assignment_class_refs(value, out);
            collect_ivar_assignment_class_refs(body, out);
        }
        _ => {}
    }
}

fn collect_class_refs(e: &Expr, out: &mut BTreeSet<String>) {
    use crate::expr::LValue;
    match &*e.node {
        ExprNode::Const { path } => {
            if let Some(first) = path.first() {
                out.insert(first.as_str().to_string());
            }
        }
        ExprNode::Send { recv, args, block, .. } => {
            if let Some(r) = recv {
                collect_class_refs(r, out);
            }
            for a in args {
                collect_class_refs(a, out);
            }
            if let Some(b) = block {
                collect_class_refs(b, out);
            }
        }
        ExprNode::Apply { fun, args, block } => {
            collect_class_refs(fun, out);
            for a in args {
                collect_class_refs(a, out);
            }
            if let Some(b) = block {
                collect_class_refs(b, out);
            }
        }
        ExprNode::Hash { entries, .. } => {
            for (k, v) in entries {
                collect_class_refs(k, out);
                collect_class_refs(v, out);
            }
        }
        ExprNode::Array { elements, .. } => {
            for el in elements {
                collect_class_refs(el, out);
            }
        }
        ExprNode::StringInterp { parts } => {
            for p in parts {
                if let InterpPart::Expr { expr } = p {
                    collect_class_refs(expr, out);
                }
            }
        }
        ExprNode::BoolOp { left, right, .. } => {
            collect_class_refs(left, out);
            collect_class_refs(right, out);
        }
        ExprNode::Let { value, body, .. } => {
            collect_class_refs(value, out);
            collect_class_refs(body, out);
        }
        ExprNode::Lambda { body, .. } => collect_class_refs(body, out),
        ExprNode::If { cond, then_branch, else_branch } => {
            collect_class_refs(cond, out);
            collect_class_refs(then_branch, out);
            collect_class_refs(else_branch, out);
        }
        ExprNode::Case { scrutinee, arms } => {
            collect_class_refs(scrutinee, out);
            for arm in arms {
                collect_class_refs(&arm.body, out);
            }
        }
        ExprNode::Seq { exprs } => {
            for e in exprs {
                collect_class_refs(e, out);
            }
        }
        ExprNode::Assign { target, value } => {
            if let LValue::Attr { recv, .. } | LValue::Index { recv, .. } = target {
                collect_class_refs(recv, out);
            }
            collect_class_refs(value, out);
        }
        ExprNode::Yield { args } => {
            for a in args {
                collect_class_refs(a, out);
            }
        }
        ExprNode::Raise { value } => collect_class_refs(value, out),
        ExprNode::RescueModifier { expr, fallback } => {
            collect_class_refs(expr, out);
            collect_class_refs(fallback, out);
        }
        ExprNode::Return { value } => collect_class_refs(value, out),
        ExprNode::Super { args } => {
            if let Some(args) = args {
                for a in args {
                    collect_class_refs(a, out);
                }
            }
        }
        ExprNode::BeginRescue { body, rescues, else_branch, ensure, .. } => {
            collect_class_refs(body, out);
            for r in rescues {
                collect_class_refs(&r.body, out);
            }
            if let Some(e) = else_branch {
                collect_class_refs(e, out);
            }
            if let Some(e) = ensure {
                collect_class_refs(e, out);
            }
        }
        ExprNode::Next { value } => {
            if let Some(v) = value { collect_class_refs(v, out); }
        }
        ExprNode::MultiAssign { value, .. } => collect_class_refs(value, out),
        ExprNode::While { cond, body, .. } => {
            collect_class_refs(cond, out);
            collect_class_refs(body, out);
        }
        ExprNode::Range { begin, end, .. } => {
            if let Some(b) = begin { collect_class_refs(b, out); }
            if let Some(e) = end { collect_class_refs(e, out); }
        }
        ExprNode::Lit { .. }
        | ExprNode::Var { .. }
        | ExprNode::Ivar { .. }
        | ExprNode::SelfRef => {}
    }
}

// `sanitize_identifier`, `rewrite_for_class_method`, and
// `rewrite_for_constructor` are referenced from `super::emit_class_member`
// — keep them here.

/// Ruby allows `?` and `!` suffixes on method names; TS does not.
/// Rename instead of silently stripping — silent strip merges
/// three namespaces (`persisted?`, `persisted!`, `persisted`) into
/// one and creates collisions with same-named fields:
///   * `?`-suffix predicate → prepend `is_` (TS-idiomatic for
///     boolean methods: `Array.isArray`, `Number.isInteger`).
///     `def persisted?` becomes `is_persisted()`; `def valid?`
///     becomes `is_valid()`. Doesn't collide with the field
///     `persisted` (from `@persisted = false` ivar).
///   * `!`-suffix bang method → suffix `_bang`. `def save!`
///     becomes `save_bang()`; doesn't collide with `def save`.
/// Both definition emit and call-site emit go through the same
/// rule so `def persisted?` and `record.persisted?` line up at
/// the call site (`record.is_persisted()`).
pub(super) fn sanitize_identifier(ruby_name: &str) -> String {
    if let Some(stem) = ruby_name.strip_suffix('?') {
        return format!("is_{stem}");
    }
    if let Some(stem) = ruby_name.strip_suffix('!') {
        return format!("{stem}_bang");
    }
    ruby_name.to_string()
}

/// IR transformation applied to each class method body before emission.
/// Two pieces:
///  1. `Send { recv: None, ... }` (bare method call / implicit self)
///     gets `SelfRef` as an explicit receiver, so the TS output
///     becomes `this.method(...)` instead of a dangling `method(...)`.
///  2. `Super { args }` becomes a Send on a synthetic `super` receiver
///     with the enclosing method's name. TS needs
///     `super.methodName(args)`, not bare `super(...)`.
///
/// `enclosing_method` is the Ruby method name (may end in `=` for
/// setters). The `=` is dropped for the super-call target so the
/// method name is a valid TS identifier.
pub(super) fn rewrite_for_class_method(e: &Expr, enclosing_method: &str) -> Expr {
    let method_for_super = enclosing_method.trim_end_matches('=').to_string();
    rewrite(e, Some(&method_for_super))
}

/// Variant of `rewrite_for_class_method` that leaves `Super { args }`
/// nodes intact instead of rewriting them to `super.<method>(args)`.
/// Constructors use this: TS spells the parent-constructor call as
/// `super(args)`, not `super.initialize(args)`.
pub(super) fn rewrite_for_constructor(e: &Expr) -> Expr {
    rewrite(e, None)
}

/// Rewrite for a free function (no `this`, no `super`, no inheritance).
/// Walks the tree to recurse on children but skips the bare-Send →
/// SelfRef injection. Bare Sends in a free-function body emit as plain
/// function calls (resolved against imports) — that matches what views
/// (and other LibraryFunction artifacts) actually mean.
pub(super) fn rewrite_for_free_function(e: &Expr) -> Expr {
    rewrite_free(e)
}

fn rewrite_free(e: &Expr) -> Expr {
    let new_node = match &*e.node {
        ExprNode::Send { recv, method, args, block, parenthesized } => ExprNode::Send {
            recv: recv.as_ref().map(rewrite_free),
            method: method.clone(),
            args: args.iter().map(rewrite_free).collect(),
            block: block.as_ref().map(rewrite_free),
            parenthesized: *parenthesized,
        },
        ExprNode::Apply { fun, args, block } => ExprNode::Apply {
            fun: rewrite_free(fun),
            args: args.iter().map(rewrite_free).collect(),
            block: block.as_ref().map(rewrite_free),
        },
        ExprNode::Seq { exprs } => ExprNode::Seq {
            exprs: exprs.iter().map(rewrite_free).collect(),
        },
        ExprNode::If { cond, then_branch, else_branch } => ExprNode::If {
            cond: rewrite_free(cond),
            then_branch: rewrite_free(then_branch),
            else_branch: rewrite_free(else_branch),
        },
        ExprNode::BoolOp { op, surface, left, right } => ExprNode::BoolOp {
            op: *op,
            surface: *surface,
            left: rewrite_free(left),
            right: rewrite_free(right),
        },
        ExprNode::Array { elements, style } => ExprNode::Array {
            elements: elements.iter().map(rewrite_free).collect(),
            style: *style,
        },
        ExprNode::Hash { entries, braced } => ExprNode::Hash {
            entries: entries.iter().map(|(k, v)| (rewrite_free(k), rewrite_free(v))).collect(),
            braced: *braced,
        },
        ExprNode::StringInterp { parts } => ExprNode::StringInterp {
            parts: parts.iter().map(|p| match p {
                InterpPart::Text { value } => InterpPart::Text { value: value.clone() },
                InterpPart::Expr { expr } => InterpPart::Expr { expr: rewrite_free(expr) },
            }).collect(),
        },
        ExprNode::Lambda { params, block_param, body, block_style } => ExprNode::Lambda {
            params: params.clone(),
            block_param: block_param.clone(),
            body: rewrite_free(body),
            block_style: *block_style,
        },
        ExprNode::Assign { target, value } => {
            let new_target = match target {
                LValue::Var { id, name } => LValue::Var { id: *id, name: name.clone() },
                LValue::Ivar { name } => LValue::Ivar { name: name.clone() },
                LValue::Attr { recv, name } => LValue::Attr {
                    recv: rewrite_free(recv),
                    name: name.clone(),
                },
                LValue::Index { recv, index } => LValue::Index {
                    recv: rewrite_free(recv),
                    index: rewrite_free(index),
                },
            };
            ExprNode::Assign { target: new_target, value: rewrite_free(value) }
        }
        ExprNode::Yield { args } => ExprNode::Yield {
            args: args.iter().map(rewrite_free).collect(),
        },
        ExprNode::Raise { value } => ExprNode::Raise { value: rewrite_free(value) },
        ExprNode::RescueModifier { expr, fallback } => ExprNode::RescueModifier {
            expr: rewrite_free(expr),
            fallback: rewrite_free(fallback),
        },
        ExprNode::Return { value } => ExprNode::Return { value: rewrite_free(value) },
        ExprNode::BeginRescue { body, rescues, else_branch, ensure, implicit } => ExprNode::BeginRescue {
            body: rewrite_free(body),
            rescues: rescues.iter().map(|rc| RescueClause {
                classes: rc.classes.iter().map(rewrite_free).collect(),
                binding: rc.binding.clone(),
                body: rewrite_free(&rc.body),
            }).collect(),
            else_branch: else_branch.as_ref().map(rewrite_free),
            ensure: ensure.as_ref().map(rewrite_free),
            implicit: *implicit,
        },
        ExprNode::Case { scrutinee, arms } => ExprNode::Case {
            scrutinee: rewrite_free(scrutinee),
            arms: arms.iter().map(|arm| crate::expr::Arm {
                pattern: arm.pattern.clone(),
                guard: arm.guard.as_ref().map(rewrite_free),
                body: rewrite_free(&arm.body),
            }).collect(),
        },
        ExprNode::Let { id, name, value, body } => ExprNode::Let {
            id: *id,
            name: name.clone(),
            value: rewrite_free(value),
            body: rewrite_free(body),
        },
        ExprNode::Next { value } => ExprNode::Next {
            value: value.as_ref().map(rewrite_free),
        },
        ExprNode::MultiAssign { targets, value } => ExprNode::MultiAssign {
            targets: targets.clone(),
            value: rewrite_free(value),
        },
        ExprNode::While { cond, body, until_form } => ExprNode::While {
            cond: rewrite_free(cond),
            body: rewrite_free(body),
            until_form: *until_form,
        },
        ExprNode::Range { begin, end, exclusive } => ExprNode::Range {
            begin: begin.as_ref().map(rewrite_free),
            end: end.as_ref().map(rewrite_free),
            exclusive: *exclusive,
        },
        ExprNode::Super { args } => ExprNode::Super {
            args: args.as_ref().map(|v| v.iter().map(rewrite_free).collect()),
        },
        ExprNode::Lit { .. }
        | ExprNode::Var { .. }
        | ExprNode::Ivar { .. }
        | ExprNode::Const { .. }
        | ExprNode::SelfRef => (*e.node).clone(),
    };
    Expr {
        span: e.span,
        node: Box::new(new_node),
        ty: e.ty.clone(),
        effects: e.effects.clone(),
        leading_blank_line: e.leading_blank_line,
        diagnostic: e.diagnostic.clone(),
    }
}

/// Bare-Send method names that the emitter handles as Kernel-level
/// (`raise` → `throw`, `puts`/`print`/`p`/`pp` → `console.log`,
/// `require`/`require_relative`/`load`/`autoload` → drop). These
/// keep `recv: None` through the rewrite so the
/// `emit_send_with_parens` special-cases fire instead of producing a
/// stray `this.method(...)`.
fn is_kernel_call(method: &str) -> bool {
    matches!(
        method,
        "raise" | "puts" | "print" | "p" | "pp"
            | "require" | "require_relative" | "load" | "autoload",
    )
}

fn rewrite(e: &Expr, super_method: Option<&str>) -> Expr {
    let new_node = match &*e.node {
        // Kernel-level calls (raise, puts, …) stay receiver-less so
        // the per-target Send rewriter can map them directly to the
        // host equivalent. Adding SelfRef here would force the typer
        // and emitter to invent a `this.puts` shim on every class.
        ExprNode::Send { recv: None, method, args, block, parenthesized }
            if is_kernel_call(method.as_str()) =>
        {
            ExprNode::Send {
                recv: None,
                method: method.clone(),
                args: args.iter().map(|a| rewrite(a, super_method)).collect(),
                block: block.as_ref().map(|b| rewrite(b, super_method)),
                parenthesized: *parenthesized,
            }
        }
        ExprNode::Send { recv: None, method, args, block, parenthesized } => ExprNode::Send {
            recv: Some(Expr::new(Span::synthetic(), ExprNode::SelfRef)),
            method: method.clone(),
            args: args.iter().map(|a| rewrite(a, super_method)).collect(),
            block: block.as_ref().map(|b| rewrite(b, super_method)),
            parenthesized: *parenthesized,
        },
        ExprNode::Send { recv: Some(r), method, args, block, parenthesized } => ExprNode::Send {
            recv: Some(rewrite(r, super_method)),
            method: method.clone(),
            args: args.iter().map(|a| rewrite(a, super_method)).collect(),
            block: block.as_ref().map(|b| rewrite(b, super_method)),
            parenthesized: *parenthesized,
        },
        ExprNode::Super { args } => match super_method {
            None => {
                let rewritten_args: Option<Vec<Expr>> = args
                    .as_ref()
                    .map(|v| v.iter().map(|a| rewrite(a, None)).collect());
                ExprNode::Super { args: rewritten_args }
            }
            Some(super_method) => {
                let super_recv = Expr::new(
                    Span::synthetic(),
                    ExprNode::Const { path: vec![Symbol::from("super")] },
                );
                let args_vec: Vec<Expr> = match args {
                    Some(v) => v
                        .iter()
                        .map(|a| rewrite(a, Some(super_method)))
                        .collect(),
                    None => vec![],
                };
                let is_base_getter = matches!(
                    super_method,
                    "save" | "destroy" | "errors" | "attributes"
                );
                let parenthesized = !args_vec.is_empty() || !is_base_getter;
                ExprNode::Send {
                    recv: Some(super_recv),
                    method: Symbol::from(super_method.to_string()),
                    args: args_vec,
                    block: None,
                    parenthesized,
                }
            }
        },
        ExprNode::Seq { exprs } => ExprNode::Seq {
            exprs: exprs.iter().map(|c| rewrite(c, super_method)).collect(),
        },
        ExprNode::If { cond, then_branch, else_branch } => ExprNode::If {
            cond: rewrite(cond, super_method),
            then_branch: rewrite(then_branch, super_method),
            else_branch: rewrite(else_branch, super_method),
        },
        ExprNode::BoolOp { op, surface, left, right } => ExprNode::BoolOp {
            op: *op,
            surface: *surface,
            left: rewrite(left, super_method),
            right: rewrite(right, super_method),
        },
        ExprNode::Array { elements, style } => ExprNode::Array {
            elements: elements.iter().map(|c| rewrite(c, super_method)).collect(),
            style: *style,
        },
        ExprNode::Hash { entries, braced } => ExprNode::Hash {
            entries: entries
                .iter()
                .map(|(k, v)| (rewrite(k, super_method), rewrite(v, super_method)))
                .collect(),
            braced: *braced,
        },
        ExprNode::StringInterp { parts } => ExprNode::StringInterp {
            parts: parts
                .iter()
                .map(|p| match p {
                    InterpPart::Text { value } => InterpPart::Text { value: value.clone() },
                    InterpPart::Expr { expr } => InterpPart::Expr {
                        expr: rewrite(expr, super_method),
                    },
                })
                .collect(),
        },
        ExprNode::Lambda { params, block_param, body, block_style } => ExprNode::Lambda {
            params: params.clone(),
            block_param: block_param.clone(),
            body: rewrite(body, super_method),
            block_style: *block_style,
        },
        ExprNode::Apply { fun, args, block } => ExprNode::Apply {
            fun: rewrite(fun, super_method),
            args: args.iter().map(|a| rewrite(a, super_method)).collect(),
            block: block.as_ref().map(|b| rewrite(b, super_method)),
        },
        ExprNode::Assign { target, value } => {
            let new_target = match target {
                LValue::Var { id, name } => LValue::Var { id: *id, name: name.clone() },
                LValue::Ivar { name } => LValue::Ivar { name: name.clone() },
                LValue::Attr { recv, name } => LValue::Attr {
                    recv: rewrite(recv, super_method),
                    name: name.clone(),
                },
                LValue::Index { recv, index } => LValue::Index {
                    recv: rewrite(recv, super_method),
                    index: rewrite(index, super_method),
                },
            };
            ExprNode::Assign {
                target: new_target,
                value: rewrite(value, super_method),
            }
        }
        ExprNode::Yield { args } => ExprNode::Yield {
            args: args.iter().map(|a| rewrite(a, super_method)).collect(),
        },
        ExprNode::Raise { value } => ExprNode::Raise {
            value: rewrite(value, super_method),
        },
        ExprNode::RescueModifier { expr, fallback } => ExprNode::RescueModifier {
            expr: rewrite(expr, super_method),
            fallback: rewrite(fallback, super_method),
        },
        ExprNode::Return { value } => ExprNode::Return {
            value: rewrite(value, super_method),
        },
        ExprNode::BeginRescue { body, rescues, else_branch, ensure, implicit } => {
            ExprNode::BeginRescue {
                body: rewrite(body, super_method),
                rescues: rescues
                    .iter()
                    .map(|rc| RescueClause {
                        classes: rc.classes.iter().map(|c| rewrite(c, super_method)).collect(),
                        binding: rc.binding.clone(),
                        body: rewrite(&rc.body, super_method),
                    })
                    .collect(),
                else_branch: else_branch.as_ref().map(|b| rewrite(b, super_method)),
                ensure: ensure.as_ref().map(|b| rewrite(b, super_method)),
                implicit: *implicit,
            }
        }
        ExprNode::Case { scrutinee, arms } => ExprNode::Case {
            scrutinee: rewrite(scrutinee, super_method),
            arms: arms
                .iter()
                .map(|arm| crate::expr::Arm {
                    pattern: arm.pattern.clone(),
                    guard: arm.guard.as_ref().map(|g| rewrite(g, super_method)),
                    body: rewrite(&arm.body, super_method),
                })
                .collect(),
        },
        ExprNode::Let { id, name, value, body } => ExprNode::Let {
            id: *id,
            name: name.clone(),
            value: rewrite(value, super_method),
            body: rewrite(body, super_method),
        },
        ExprNode::Next { value } => ExprNode::Next {
            value: value.as_ref().map(|v| rewrite(v, super_method)),
        },
        ExprNode::MultiAssign { targets, value } => ExprNode::MultiAssign {
            targets: targets.clone(),
            value: rewrite(value, super_method),
        },
        ExprNode::While { cond, body, until_form } => ExprNode::While {
            cond: rewrite(cond, super_method),
            body: rewrite(body, super_method),
            until_form: *until_form,
        },
        ExprNode::Range { begin, end, exclusive } => ExprNode::Range {
            begin: begin.as_ref().map(|b| rewrite(b, super_method)),
            end: end.as_ref().map(|e| rewrite(e, super_method)),
            exclusive: *exclusive,
        },
        // Leaves pass through unchanged.
        ExprNode::Lit { .. }
        | ExprNode::Var { .. }
        | ExprNode::Ivar { .. }
        | ExprNode::Const { .. }
        | ExprNode::SelfRef => (*e.node).clone(),
    };

    Expr {
        span: e.span,
        node: Box::new(new_node),
        ty: e.ty.clone(),
        effects: e.effects.clone(),
        leading_blank_line: e.leading_blank_line,
        diagnostic: e.diagnostic.clone(),
    }
}
