use std::fmt::Write;
use std::path::PathBuf;

use crate::App;
use crate::emit::EmittedFile;
use crate::naming::snake_case;

pub fn emit_main_ts(app: &App) -> EmittedFile {
    let has_app_layout = app
        .views
        .iter()
        .any(|v| v.name.as_str() == "layouts/application");
    let has_models = !app.models.is_empty();

    let mut content = String::new();
    content.push_str("// Generated by Roundhouse.\n\n");
    content.push_str("import { startServer } from \"./src/server.js\";\n");
    if has_models {
        content.push_str("import { CREATE_TABLES } from \"./src/schema_sql.js\";\n");
    }
    if has_app_layout {
        content.push_str(
            "import { renderLayoutsApplication } from \"./app/views/layouts/application.html.js\";\n",
        );
    }
    content.push_str("import \"./src/routes.js\";\n");

    let mut model_files: Vec<String> =
        app.models.iter().map(|m| snake_case(m.name.0.as_str())).collect();
    model_files.sort();
    for f in &model_files {
        writeln!(content, "import \"./app/models/{f}.js\";").unwrap();
    }

    content.push('\n');
    content.push_str("async function main(): Promise<void> {\n");
    content.push_str("  await startServer({\n");
    if has_models {
        content.push_str("    schemaSql: CREATE_TABLES,\n");
    } else {
        content.push_str("    schemaSql: \"\",\n");
    }
    if has_app_layout {
        content.push_str("    layout: () => renderLayoutsApplication(undefined as any),\n");
    }
    content.push_str("  });\n");
    content.push_str("}\n\n");
    content.push_str("main().catch((err) => {\n");
    content.push_str("  console.error(err);\n");
    content.push_str("  process.exit(1);\n");
    content.push_str("});\n");

    EmittedFile { path: PathBuf::from("main.ts"), content }
}
