use std::collections::BTreeSet;
use std::fmt::Write;
use std::path::PathBuf;

use crate::App;
use crate::dialect::{Association, Model};
use crate::emit::EmittedFile;
use crate::lower::validations::{Check, LoweredValidation};
use crate::naming::{pluralize_snake, snake_case};

use super::ty::{ts_default, ts_ty};

pub fn emit_models(app: &App) -> Vec<EmittedFile> {
    app.models.iter().map(|m| emit_model(m, app)).collect()
}

fn emit_model(model: &Model, _app: &App) -> EmittedFile {
    let class_name = model.name.0.as_str();
    let snake = snake_case(class_name);
    let path = PathBuf::from(format!("app/models/{snake}.ts"));

    let parent = model
        .parent
        .as_ref()
        .map(|p| match p.0.as_str() {
            "ActiveRecord::Base" => "ActiveRecord".to_string(),
            other => other.to_string(),
        })
        .unwrap_or_else(|| "ActiveRecord".to_string());

    let validations = crate::lower::lower_validations(model);
    let has_manys: Vec<&Association> = model
        .associations()
        .filter(|a| matches!(a, Association::HasMany { .. }))
        .collect();
    let belongs_tos: Vec<&Association> = model
        .associations()
        .filter(|a| matches!(a, Association::BelongsTo { .. }))
        .collect();

    let imports = compute_imports(&parent, &has_manys, &belongs_tos);

    let mut out = String::new();
    writeln!(out, "// Generated by Roundhouse.").unwrap();
    writeln!(out, "import {{ {} }} from \"juntos\";", imports.join(", ")).unwrap();
    writeln!(out).unwrap();

    writeln!(out, "export class {class_name} extends {parent} {{").unwrap();

    let table_name = pluralize_snake(class_name);
    writeln!(out, "  static table_name = \"{table_name}\";").unwrap();

    let columns: Vec<&str> = model
        .attributes
        .fields
        .keys()
        .map(|k| k.as_str())
        .filter(|n| *n != "id")
        .collect();
    let cols_lit = columns
        .iter()
        .map(|c| format!("\"{c}\""))
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(out, "  static columns: string[] = [{cols_lit}];").unwrap();

    for (field, ty) in &model.attributes.fields {
        if field.as_str() == "id" {
            continue;
        }
        writeln!(out, "  {}: {} = {};", field, ts_ty(ty), ts_default(ty)).unwrap();
    }

    if !has_manys.is_empty() {
        emit_dependent_children(&mut out, &has_manys);
    }
    if !belongs_tos.is_empty() {
        emit_belongs_to_checks(&mut out, &belongs_tos);
    }

    for assoc in model.associations() {
        emit_association_getter(&mut out, assoc);
    }

    if !validations.is_empty() {
        emit_validate_method(&mut out, &validations);
    }

    writeln!(out, "}}").unwrap();

    let broadcasts = crate::lower::lower_broadcasts(model);
    if !broadcasts.is_empty() {
        emit_broadcast_hooks(&mut out, class_name, &broadcasts);
    }

    writeln!(out).unwrap();
    writeln!(out, "modelRegistry[\"{class_name}\"] = {class_name};").unwrap();

    EmittedFile { path, content: out }
}

fn compute_imports(
    parent: &str,
    has_manys: &[&Association],
    belongs_tos: &[&Association],
) -> Vec<String> {
    let mut set: BTreeSet<&'static str> = BTreeSet::new();
    set.insert(parent_import(parent));
    if !has_manys.is_empty() {
        set.insert("CollectionProxy");
    }
    if !belongs_tos.is_empty() {
        set.insert("Reference");
    }
    set.insert("modelRegistry");
    set.into_iter().map(|s| s.to_string()).collect()
}

fn parent_import(parent: &str) -> &'static str {
    match parent {
        "ActiveRecord" => "ActiveRecord",
        "ActiveRecord::Base" => "ActiveRecord",
        _ => "ApplicationRecord",
    }
}

fn emit_dependent_children(out: &mut String, has_manys: &[&Association]) {
    writeln!(out, "  static dependentChildren = [").unwrap();
    let entries: Vec<String> = has_manys
        .iter()
        .map(|a| match a {
            Association::HasMany { foreign_key, target, .. } => format!(
                "    {{ fk: \"{}\", targetName: \"{}\" }}",
                foreign_key,
                target.0,
            ),
            _ => unreachable!(),
        })
        .collect();
    writeln!(out, "{}", entries.join(",\n")).unwrap();
    writeln!(out, "  ];").unwrap();
}

fn emit_belongs_to_checks(out: &mut String, belongs_tos: &[&Association]) {
    writeln!(out, "  static belongsToChecks = [").unwrap();
    let entries: Vec<String> = belongs_tos
        .iter()
        .map(|a| match a {
            Association::BelongsTo { foreign_key, target, .. } => format!(
                "    {{ fk: \"{}\", targetName: \"{}\" }}",
                foreign_key,
                target.0,
            ),
            _ => unreachable!(),
        })
        .collect();
    writeln!(out, "{}", entries.join(",\n")).unwrap();
    writeln!(out, "  ];").unwrap();
}

fn emit_association_getter(out: &mut String, assoc: &Association) {
    match assoc {
        Association::HasMany { name, target, foreign_key, .. } => {
            writeln!(out).unwrap();
            writeln!(out, "  get {name}() {{").unwrap();
            writeln!(out, "    return new CollectionProxy(this, {{").unwrap();
            writeln!(out, "      name: \"{name}\",").unwrap();
            writeln!(out, "      type: \"has_many\",").unwrap();
            writeln!(out, "      foreignKey: \"{foreign_key}\"").unwrap();
            writeln!(out, "    }}, modelRegistry.{});", target.0).unwrap();
            writeln!(out, "  }}").unwrap();
        }
        Association::BelongsTo { name, target, foreign_key, .. } => {
            writeln!(out).unwrap();
            writeln!(out, "  get {name}() {{").unwrap();
            writeln!(
                out,
                "    return new Reference(modelRegistry.{}, this.attributes.{foreign_key});",
                target.0
            )
            .unwrap();
            writeln!(out, "  }}").unwrap();
        }
        _ => {}
    }
}

fn emit_validate_method(out: &mut String, validations: &[LoweredValidation]) {
    writeln!(out).unwrap();
    writeln!(out, "  validate() {{").unwrap();
    for v in validations {
        let attr = v.attribute.as_str();
        for check in &v.checks {
            match check {
                Check::Presence => {
                    writeln!(out, "    this.validates_presence_of(\"{attr}\");").unwrap();
                }
                Check::Absence => {
                    writeln!(out, "    this.validates_absence_of(\"{attr}\");").unwrap();
                }
                Check::MinLength { n } => {
                    writeln!(
                        out,
                        "    this.validates_length_of(\"{attr}\", {{minimum: {n}}});"
                    )
                    .unwrap();
                }
                Check::MaxLength { n } => {
                    writeln!(
                        out,
                        "    this.validates_length_of(\"{attr}\", {{maximum: {n}}});"
                    )
                    .unwrap();
                }
                _ => {
                    writeln!(out, "    // unhandled validation: {check:?}").unwrap();
                }
            }
        }
    }
    writeln!(out, "  }}").unwrap();
}

fn emit_broadcast_hooks(
    out: &mut String,
    class: &str,
    broadcasts: &crate::lower::LoweredBroadcasts,
) {
    writeln!(out).unwrap();
    for b in &broadcasts.save {
        emit_one_broadcast_hook(out, class, "afterSave", b);
    }
    for b in &broadcasts.destroy {
        emit_one_broadcast_hook(out, class, "afterDestroy", b);
    }
}

fn emit_one_broadcast_hook(
    out: &mut String,
    class: &str,
    hook: &str,
    b: &crate::lower::LoweredBroadcast,
) {
    use crate::lower::BroadcastAction;
    let action = b.action.as_snake();
    let camel_action = capitalize_first(action);
    let channel = render_channel_expr(&b.channel, b.self_param.as_ref());
    // Remove actions identify the DOM node by record ID, so a
    // `target:` override on the broadcast declaration is irrelevant
    // — match the published shape and drop it for Remove only.
    let target_clause = if matches!(b.action, BroadcastAction::Remove) {
        String::new()
    } else {
        b.target
            .as_ref()
            .map(|t| {
                format!(", {{ target: {} }}", render_channel_expr(t, b.self_param.as_ref()))
            })
            .unwrap_or_default()
    };

    if let Some(assoc) = &b.on_association {
        let assoc_class = assoc.target_class.as_str();
        let fk = assoc.foreign_key.as_str();
        writeln!(
            out,
            "{class}.{hook}((record) => {{ const {assoc_name} = modelRegistry.{assoc_class}?.find(record.{fk}); if ({assoc_name}) {assoc_name}.broadcast{camel_action}To({channel}{target_clause}); }});",
            assoc_name = assoc.name.as_str(),
        )
        .unwrap();
    } else {
        writeln!(
            out,
            "{class}.{hook}((record) => record.broadcast{camel_action}To({channel}{target_clause}));"
        )
        .unwrap();
    }
}

fn capitalize_first(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(first) => first.to_uppercase().chain(c).collect(),
    }
}

/// Render a Ruby Expr to a TS string-literal-or-template expression for a
/// broadcast channel/target. Handles plain string literals and
/// interpolated strings referencing `self_param.column` or column refs.
fn render_channel_expr(e: &crate::expr::Expr, self_param: Option<&crate::ident::Symbol>) -> String {
    use crate::expr::{ExprNode, Literal};

    match &*e.node {
        ExprNode::Lit { value: Literal::Str { value } } => format!("\"{}\"", escape_ts_str(value)),
        ExprNode::StringInterp { parts } => render_str_interp(parts, self_param),
        _ => "\"\"".into(),
    }
}

fn render_str_interp(
    parts: &[crate::expr::InterpPart],
    self_param: Option<&crate::ident::Symbol>,
) -> String {
    use crate::expr::{ExprNode, InterpPart};

    let mut out = String::from("`");
    for p in parts {
        match p {
            InterpPart::Text { value } => out.push_str(&escape_template_literal(value)),
            InterpPart::Expr { expr } => {
                out.push_str("${");
                match &*expr.node {
                    ExprNode::Send { recv: Some(recv), method, args, .. }
                        if args.is_empty() =>
                    {
                        let recv_str = match &*recv.node {
                            ExprNode::Var { name, .. }
                                if self_param.map_or(false, |sp| sp == name) =>
                            {
                                "record".to_string()
                            }
                            ExprNode::Var { name, .. } => name.as_str().into(),
                            ExprNode::SelfRef => "record".into(),
                            _ => "?".into(),
                        };
                        out.push_str(&format!("{recv_str}.{}", method.as_str()));
                    }
                    ExprNode::Var { name, .. } => {
                        if self_param.map_or(false, |sp| sp == name) {
                            out.push_str("record");
                        } else {
                            out.push_str(&format!("record.{}", name.as_str()));
                        }
                    }
                    ExprNode::Ivar { name } => {
                        let n = name.as_str().trim_start_matches('@');
                        out.push_str(&format!("record.{n}"));
                    }
                    _ => out.push('?'),
                }
                out.push('}');
            }
        }
    }
    out.push('`');
    out
}

fn escape_ts_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn escape_template_literal(s: &str) -> String {
    s.replace('\\', "\\\\").replace('`', "\\`").replace("${", "\\${")
}
