//! Strangler-fig path for TS model emission. Routes each `Model` through
//! `lower::model_to_library` and renders the resulting `LibraryClass` as
//! a TypeScript model file. Models whose Rails-shape body carries idioms
//! the lowerer doesn't yet handle (broadcasts, callbacks beyond
//! `before_destroy`, scopes, custom methods, …) return `None` so the
//! caller can fall back to the rich-dialect path in `model.rs`.
//!
//! See `project_universal_post_lowering_ir.md`: the architectural goal
//! is "all emitters consume `LibraryClass`," with the rich `Model`
//! dialect serving only as input to lowerers. This module is the first
//! non-Ruby emitter to consume the lowered IR end-to-end.

use std::collections::{BTreeSet, HashMap};
use std::fmt::Write;
use std::path::PathBuf;

use crate::App;
use crate::dialect::{Association, Dependent, LibraryClass, MethodDef, Model, ModelBodyItem, ValidationRule};
use crate::lower::lower_model_to_library_class;

use super::super::EmittedFile;

/// Try emitting `model` via the lowered-IR path. Returns `None` when the
/// model uses idioms the lowerer doesn't yet cover; the caller is
/// expected to fall back to the rich-dialect path for those.
pub(super) fn try_emit(model: &Model, app: &App) -> Option<EmittedFile> {
    if !is_lowerable(model) {
        return None;
    }
    let lc = lower_model_to_library_class(model, &app.schema);
    Some(emit_model_class(&lc, app))
}

/// Strict policy: every body item must lower cleanly. The lowerer
/// silently skips unhandled items today, so a permissive admit-anything
/// gate would emit incomplete TS — strict gating preserves correctness
/// while the lowerer grows.
fn is_lowerable(model: &Model) -> bool {
    for item in &model.body {
        match item {
            ModelBodyItem::Association { assoc, .. } => match assoc {
                Association::HasMany { through, dependent, .. } => {
                    if through.is_some() {
                        return false;
                    }
                    if !matches!(dependent, Dependent::None | Dependent::Destroy) {
                        return false;
                    }
                }
                Association::BelongsTo { .. } => {}
                Association::HasOne { .. } | Association::HasAndBelongsToMany { .. } => {
                    return false;
                }
            },
            ModelBodyItem::Validation { validation, .. } => {
                for rule in &validation.rules {
                    if matches!(
                        rule,
                        ValidationRule::Uniqueness { .. } | ValidationRule::Custom { .. }
                    ) {
                        return false;
                    }
                }
            }
            ModelBodyItem::Scope { .. }
            | ModelBodyItem::Callback { .. }
            | ModelBodyItem::Method { .. }
            | ModelBodyItem::Unknown { .. } => return false,
        }
    }
    true
}

/// Names exported from `juntos.ts` that lowered-model bodies may
/// reference. Mirrors `library::JUNTOS_EXPORTS` but kept local so
/// changes here don't ripple into the existing library path.
const JUNTOS_EXPORTS: &[&str] = &[
    "ActiveRecord",
    "ApplicationRecord",
    "CollectionProxy",
    "ErrorCollection",
    "Reference",
    "Router",
    "modelRegistry",
    "conn",
];

fn emit_model_class(lc: &LibraryClass, app: &App) -> EmittedFile {
    let name = lc.name.0.as_str();
    let file_stem = crate::naming::snake_case(name);
    let mut s = String::new();

    writeln!(s, "// Generated by Roundhouse (lowered model).").unwrap();

    // Parent flattening: Ruby's `ActiveRecord::Base` maps to Juntos's
    // `ActiveRecord`; other qualified names flatten to their last
    // segment. Models without an explicit parent inherit
    // `ApplicationRecord` so the generated class still has the
    // expected runtime base.
    let parent = lc
        .parent
        .as_ref()
        .map(|p| {
            let raw = p.0.as_str();
            if raw == "ActiveRecord::Base" {
                "ActiveRecord".to_string()
            } else if let Some(last) = raw.rsplit("::").next() {
                last.to_string()
            } else {
                raw.to_string()
            }
        })
        .unwrap_or_else(|| "ApplicationRecord".to_string());

    let mut refs: BTreeSet<String> = BTreeSet::new();
    for m in &lc.methods {
        super::library::collect_class_refs(&m.body, &mut refs);
    }
    refs.remove(name);
    refs.remove(&parent);

    let mut juntos_imports: Vec<String> = Vec::new();
    juntos_imports.push(parent.clone());
    if !juntos_imports.contains(&"modelRegistry".to_string()) {
        juntos_imports.push("modelRegistry".to_string());
    }

    let mut sibling_imports: Vec<(String, String)> = Vec::new();
    for r in &refs {
        let r_str: &str = r;
        if JUNTOS_EXPORTS.contains(&r_str) {
            if !juntos_imports.iter().any(|j| j == r) {
                juntos_imports.push(r.clone());
            }
        } else if app.models.iter().any(|m| m.name.0.as_str() == r_str)
            || app.library_classes.iter().any(|lc| lc.name.0.as_str() == r_str)
        {
            sibling_imports.push((r.clone(), crate::naming::snake_case(r_str)));
        }
        // Unknown identifier — let tsc surface the missing import
        // rather than guess.
    }

    writeln!(
        s,
        "import {{ {} }} from \"juntos\";",
        juntos_imports.join(", ")
    )
    .unwrap();
    for (n, stem) in &sibling_imports {
        writeln!(s, "import {{ {n} }} from \"./{stem}.js\";").unwrap();
    }
    writeln!(s).unwrap();

    writeln!(s, "export class {name} extends {parent} {{").unwrap();

    let mut ivar_names: BTreeSet<String> = BTreeSet::new();
    for m in &lc.methods {
        super::library::collect_ivar_names(&m.body, &mut ivar_names);
    }
    if !ivar_names.is_empty() {
        for n in &ivar_names {
            writeln!(s, "  {n}: any;").unwrap();
        }
        writeln!(s).unwrap();
    }

    // Pair `x` / `x=` methods so attr_accessor lowering manifests as
    // TS `get`/`set` accessors. Without this, the setter would emit
    // as a method named `x=` — invalid TS.
    let mut setters: HashMap<String, &MethodDef> = HashMap::new();
    for m in &lc.methods {
        if let Some(base) = m.name.as_str().strip_suffix('=') {
            setters.insert(base.to_string(), m);
        }
    }

    let mut first = true;
    for m in &lc.methods {
        let n = m.name.as_str();
        if n.ends_with('=') {
            continue;
        }
        if !first {
            writeln!(s).unwrap();
        }
        first = false;
        if let Some(setter) = setters.get(n) {
            super::library::emit_getter_setter_pair(&mut s, m, setter);
        } else {
            super::library::emit_plain_method(&mut s, m);
        }
    }

    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "modelRegistry[{name:?}] = {name};").unwrap();

    EmittedFile {
        path: PathBuf::from(format!("app/models/{file_stem}.ts")),
        content: s,
    }
}
