//! Models — Juntos-shape TypeScript model classes.

use std::fmt::Write;
use std::path::PathBuf;

use crate::App;
use crate::dialect::{Association, MethodDef, Model};
use crate::expr::{Expr, ExprNode, LValue, Literal};
use crate::ident::Symbol;
use crate::lower::{BroadcastAction, LoweredBroadcast, LoweredBroadcasts};
use crate::ty::Ty;

use super::super::EmittedFile;
use super::expr::{emit_body, emit_expr};
use super::fixture::ts_field_type_and_default;
use super::naming::ts_method_name;
use super::ty::ts_ty;

/// Emit one `app/models/<snake>.ts` per model.
pub(super) fn emit_models(app: &App) -> Vec<EmittedFile> {
    app.models.iter().map(emit_model_file).collect()
}

fn emit_model_file(model: &Model) -> EmittedFile {
    let name = model.name.0.as_str();
    let file_stem = crate::naming::snake_case(name);
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    let parent = model
        .parent
        .as_ref()
        .map(|p| {
            let name = p.0.as_str();
            if name == "ActiveRecord::Base" {
                "ActiveRecord".to_string()
            } else {
                name.to_string()
            }
        })
        .unwrap_or_else(|| "ApplicationRecord".to_string());

    let mut imports: Vec<&str> = vec![parent.as_str()];
    let has_many = model.associations().any(|a| matches!(a, Association::HasMany { .. }));
    let has_one = model.associations().any(|a| matches!(a, Association::HasOne { .. }));
    let has_belongs_to = model
        .associations()
        .any(|a| matches!(a, Association::BelongsTo { .. }));
    let _unused_existing_gate = has_many || has_one || has_belongs_to;
    let uses_registry = true;
    if has_many {
        imports.push("CollectionProxy");
    }
    if has_belongs_to {
        imports.push("Reference");
    }
    if has_one {
        imports.push("HasOneReference");
    }
    if uses_registry {
        imports.push("modelRegistry");
    }
    writeln!(
        s,
        "import {{ {} }} from \"juntos\";",
        imports.join(", ")
    )
    .unwrap();
    writeln!(s).unwrap();

    writeln!(s, "export class {name} extends {parent} {{").unwrap();

    let table = model.table.0.as_str();
    writeln!(s, "  static table_name = {table:?};").unwrap();

    let columns: Vec<String> = model
        .attributes
        .fields
        .keys()
        .filter(|k| k.as_str() != "id")
        .map(|k| format!("{:?}", k.as_str()))
        .collect();
    if columns.is_empty() {
        writeln!(s, "  static columns: string[] = [];").unwrap();
    } else {
        writeln!(s, "  static columns = [{}];", columns.join(", ")).unwrap();
    }

    let field_defaults: Vec<(String, String, String)> = model
        .attributes
        .fields
        .iter()
        .filter(|(k, _)| k.as_str() != "id")
        .map(|(k, ty)| {
            let name = k.as_str().to_string();
            let (type_ann, default) = ts_field_type_and_default(ty);
            (name, type_ann, default)
        })
        .collect();
    for (name, ty, default) in &field_defaults {
        writeln!(s, "  {name}: {ty} = {default};").unwrap();
    }

    let bt_checks: Vec<String> = model
        .associations()
        .filter_map(|a| match a {
            Association::BelongsTo { foreign_key, target, optional: false, .. } => Some(
                format!(
                    "    {{ fk: {:?}, targetName: {:?} }}",
                    foreign_key.as_str(),
                    target.0.as_str(),
                ),
            ),
            _ => None,
        })
        .collect();
    if !bt_checks.is_empty() {
        writeln!(s, "  static belongsToChecks = [").unwrap();
        writeln!(s, "{}", bt_checks.join(",\n")).unwrap();
        writeln!(s, "  ];").unwrap();
    }

    let dep_children: Vec<String> = model
        .associations()
        .filter_map(|a| match a {
            Association::HasMany {
                foreign_key,
                target,
                dependent: crate::dialect::Dependent::Destroy,
                ..
            } => Some(format!(
                "    {{ fk: {:?}, targetName: {:?} }}",
                foreign_key.as_str(),
                target.0.as_str(),
            )),
            _ => None,
        })
        .collect();
    if !dep_children.is_empty() {
        writeln!(s, "  static dependentChildren = [").unwrap();
        writeln!(s, "{}", dep_children.join(",\n")).unwrap();
        writeln!(s, "  ];").unwrap();
    }

    for assoc in model.associations() {
        writeln!(s).unwrap();
        emit_association(&mut s, assoc);
    }

    let lowered = crate::lower::lower_validations(model);
    if !lowered.is_empty() {
        writeln!(s).unwrap();
        writeln!(s, "  validate() {{").unwrap();
        for lv in &lowered {
            for check in &lv.checks {
                if let Some(call) = emit_juntos_validate_call(lv.attribute.as_str(), check) {
                    writeln!(s, "    {call};").unwrap();
                }
            }
        }
        writeln!(s, "  }}").unwrap();
    }

    for method in model.methods() {
        writeln!(s).unwrap();
        emit_model_method(&mut s, method, model);
    }
    writeln!(s, "}}").unwrap();

    let broadcast_lines = render_broadcast_registrations(model);
    if !broadcast_lines.is_empty() {
        writeln!(s).unwrap();
        for line in broadcast_lines {
            writeln!(s, "{line}").unwrap();
        }
    }

    writeln!(s).unwrap();
    writeln!(s, "modelRegistry[{name:?}] = {name};").unwrap();

    EmittedFile {
        path: PathBuf::from(format!("app/models/{file_stem}.ts")),
        content: s,
    }
}

fn render_broadcast_registrations(model: &Model) -> Vec<String> {
    let lowered = crate::lower::lower_broadcasts(model);
    if lowered.is_empty() {
        return Vec::new();
    }
    let model_name = model.name.0.as_str();
    let mut lines = Vec::new();
    for b in &lowered.save {
        lines.push(render_broadcast_registration(
            model_name,
            "afterSave",
            b,
            &lowered,
        ));
    }
    for b in &lowered.destroy {
        lines.push(render_broadcast_registration(
            model_name,
            "afterDestroy",
            b,
            &lowered,
        ));
    }
    lines
}

fn render_broadcast_registration(
    model_name: &str,
    hook: &str,
    b: &LoweredBroadcast,
    _all: &LoweredBroadcasts,
) -> String {
    let channel_js = render_broadcast_channel(&b.channel, b.self_param.as_ref());
    let target_js = b
        .target
        .as_ref()
        .map(|t| render_broadcast_channel(t, b.self_param.as_ref()));
    let method = ts_broadcast_method(b.action);

    if let Some(assoc) = &b.on_association {
        let var = assoc.name.as_str();
        let target_class = assoc.target_class.as_str();
        let fk = assoc.foreign_key.as_str();
        let call = render_broadcast_call(method, &channel_js, target_js.as_deref(), var);
        return format!(
            "{model_name}.{hook}((record) => {{ const {var} = modelRegistry.{target_class}?.find(record.{fk}); if ({var}) {call}; }});"
        );
    }

    let call = render_broadcast_call(method, &channel_js, target_js.as_deref(), "record");
    format!("{model_name}.{hook}((record) => {call});")
}

fn render_broadcast_call(
    method: &str,
    channel_js: &str,
    target_js: Option<&str>,
    receiver: &str,
) -> String {
    match (method, target_js) {
        ("broadcastRemoveTo", _) => {
            format!("{receiver}.broadcastRemoveTo({channel_js})")
        }
        (m, Some(t)) => format!("{receiver}.{m}({channel_js}, {{ target: {t} }})"),
        (m, None) => format!("{receiver}.{m}({channel_js})"),
    }
}

fn ts_broadcast_method(action: BroadcastAction) -> &'static str {
    match action {
        BroadcastAction::Prepend => "broadcastPrependTo",
        BroadcastAction::Append => "broadcastAppendTo",
        BroadcastAction::Replace => "broadcastReplaceTo",
        BroadcastAction::Remove => "broadcastRemoveTo",
    }
}

fn render_broadcast_channel(expr: &Expr, self_param: Option<&Symbol>) -> String {
    let raw = match &*expr.node {
        ExprNode::Lit { value: Literal::Str { value } } => format!("{value:?}"),
        _ => emit_expr(expr),
    };
    let Some(p) = self_param else { return raw };
    rewrite_record_refs(&raw, Some(p.as_str()))
}

fn rewrite_record_refs(js: &str, param_name: Option<&str>) -> String {
    let Some(orig) = param_name else { return js.to_string() };
    let stripped = orig.strip_prefix('_').unwrap_or(orig).to_string();
    let mut out = replace_word(js, orig, "record");
    if stripped != orig {
        out = replace_word(&out, &stripped, "record");
    }
    out
}

fn replace_word(haystack: &str, needle: &str, replacement: &str) -> String {
    if needle.is_empty() {
        return haystack.to_string();
    }
    let bytes = haystack.as_bytes();
    let n = needle.len();
    let mut out = String::with_capacity(haystack.len());
    let mut i = 0;
    while i + n <= bytes.len() {
        if &bytes[i..i + n] == needle.as_bytes() {
            let prev_ok = i == 0 || !is_ident_byte(bytes[i - 1]);
            let next_ok = i + n == bytes.len() || !is_ident_byte(bytes[i + n]);
            if prev_ok && next_ok {
                out.push_str(replacement);
                i += n;
                continue;
            }
        }
        out.push(bytes[i] as char);
        i += 1;
    }
    if i < bytes.len() {
        out.push_str(&haystack[i..]);
    }
    out
}

fn is_ident_byte(b: u8) -> bool {
    b.is_ascii_alphanumeric() || b == b'_' || b == b'$'
}

fn emit_association(out: &mut String, assoc: &Association) {
    match assoc {
        Association::HasMany { name, target, foreign_key, .. } => {
            writeln!(out, "  get {name}() {{").unwrap();
            writeln!(out, "    return new CollectionProxy(this, {{").unwrap();
            writeln!(out, "      name: {:?},", name.as_str()).unwrap();
            writeln!(out, "      type: \"has_many\",").unwrap();
            writeln!(out, "      foreignKey: {:?}", foreign_key.as_str()).unwrap();
            writeln!(out, "    }}, modelRegistry.{});", target.0).unwrap();
            writeln!(out, "  }}").unwrap();
        }
        Association::HasOne { name, target, foreign_key, .. } => {
            writeln!(out, "  get {name}() {{").unwrap();
            writeln!(out, "    return new HasOneReference(this, {{").unwrap();
            writeln!(out, "      name: {:?},", name.as_str()).unwrap();
            writeln!(out, "      type: \"has_one\",").unwrap();
            writeln!(out, "      foreignKey: {:?}", foreign_key.as_str()).unwrap();
            writeln!(out, "    }}, modelRegistry.{});", target.0).unwrap();
            writeln!(out, "  }}").unwrap();
        }
        Association::BelongsTo { name, target, foreign_key, optional } => {
            writeln!(out, "  get {name}() {{").unwrap();
            let fk_access = format!("this.attributes.{}", foreign_key.as_str());
            if *optional {
                writeln!(
                    out,
                    "    return {fk_access} ? new Reference(modelRegistry.{}, {fk_access}) : null;",
                    target.0
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    "    return new Reference(modelRegistry.{}, {fk_access});",
                    target.0
                )
                .unwrap();
            }
            writeln!(out, "  }}").unwrap();
        }
        Association::HasAndBelongsToMany { name, target, join_table } => {
            writeln!(out, "  get {name}() {{").unwrap();
            writeln!(out, "    return new CollectionProxy(this, {{").unwrap();
            writeln!(out, "      name: {:?},", name.as_str()).unwrap();
            writeln!(out, "      type: \"has_and_belongs_to_many\",").unwrap();
            writeln!(out, "      joinTable: {:?}", join_table.as_str()).unwrap();
            writeln!(out, "    }}, modelRegistry.{});", target.0).unwrap();
            writeln!(out, "  }}").unwrap();
        }
    }
}

fn emit_juntos_validate_call(attr: &str, check: &crate::lower::Check) -> Option<String> {
    use crate::lower::Check;
    let attr_lit = format!("{attr:?}");
    Some(match check {
        Check::Presence => format!("this.validates_presence_of({attr_lit})"),
        Check::Absence => format!("this.validates_absence_of({attr_lit})"),
        Check::MinLength { n } => {
            format!("this.validates_length_of({attr_lit}, {{minimum: {n}}})")
        }
        Check::MaxLength { n } => {
            format!("this.validates_length_of({attr_lit}, {{maximum: {n}}})")
        }
        Check::GreaterThan { threshold } => format!(
            "this.validates_numericality_of({attr_lit}, {{greater_than: {threshold}}})"
        ),
        Check::LessThan { threshold } => format!(
            "this.validates_numericality_of({attr_lit}, {{less_than: {threshold}}})"
        ),
        Check::OnlyInteger => format!(
            "this.validates_numericality_of({attr_lit}, {{only_integer: true}})"
        ),
        Check::Inclusion { values } => {
            let parts: Vec<String> = values.iter().map(inclusion_value_to_js).collect();
            format!(
                "this.validates_inclusion_of({attr_lit}, {{in: [{}]}})",
                parts.join(", ")
            )
        }
        Check::Format { pattern } => format!(
            "this.validates_format_of({attr_lit}, {{with: /{pattern}/}})"
        ),
        Check::Uniqueness { scope, case_sensitive } => {
            let mut opts = Vec::new();
            if !scope.is_empty() {
                let parts: Vec<String> =
                    scope.iter().map(|s| format!("{:?}", s.as_str())).collect();
                opts.push(format!("scope: [{}]", parts.join(", ")));
            }
            if !*case_sensitive {
                opts.push("case_sensitive: false".to_string());
            }
            if opts.is_empty() {
                format!("this.validates_uniqueness_of({attr_lit})")
            } else {
                format!(
                    "this.validates_uniqueness_of({attr_lit}, {{{}}})",
                    opts.join(", ")
                )
            }
        }
        Check::Custom { method } => {
            format!("this.{method}()")
        }
    })
}

fn inclusion_value_to_js(v: &crate::lower::InclusionValue) -> String {
    use crate::lower::InclusionValue;
    match v {
        InclusionValue::Str { value } => format!("{value:?}"),
        InclusionValue::Int { value } => value.to_string(),
        InclusionValue::Float { value } => {
            let s = value.to_string();
            if s.contains('.') { s } else { format!("{s}.0") }
        }
        InclusionValue::Bool { value } => value.to_string(),
    }
}

fn emit_model_method(out: &mut String, m: &MethodDef, model: &Model) {
    let name = ts_method_name(m.name.as_str());
    let ret = m.body.ty.clone().unwrap_or(Ty::Nil);
    let ret_annot = if matches!(ret, Ty::Nil) {
        ": void".to_string()
    } else {
        format!(": {}", ts_ty(&ret))
    };
    let is_static = matches!(m.receiver, crate::dialect::MethodReceiver::Class);
    let static_prefix = if is_static { "static " } else { "" };
    let params: Vec<String> = m
        .params
        .iter()
        .map(|p| format!("{}: unknown", p.as_str()))
        .collect();
    writeln!(
        out,
        "  {static_prefix}{name}({}){ret_annot} {{",
        params.join(", ")
    )
    .unwrap();
    let attrs: Vec<crate::ident::Symbol> =
        model.attributes.fields.keys().cloned().collect();
    let rewritten = rewrite_bare_attrs_to_ivars(&m.body, &attrs);
    // Apply the same implicit-self / Super rewrite the library-shape
    // path uses. Without this, transpiled-shape model methods that
    // call sibling instance methods (e.g. `comments.each(...)` from
    // a `dependent: :destroy` override) emit as bare names — invalid
    // TS. `super` similarly needs to become `super.methodName(...)`.
    let rewritten = super::library::rewrite_for_class_method(&rewritten, m.name.as_str());
    let body_text = emit_body(&rewritten, &ret);
    for line in body_text.lines() {
        writeln!(out, "    {line}").unwrap();
    }
    writeln!(out, "  }}").unwrap();
}

fn rewrite_bare_attrs_to_ivars(
    e: &Expr,
    attrs: &[crate::ident::Symbol],
) -> Expr {
    use crate::expr::{Arm, InterpPart, Pattern};
    let rewrite = |child: &Expr| rewrite_bare_attrs_to_ivars(child, attrs);
    let new_node = match &*e.node {
        ExprNode::Send { recv: None, method, args, block: None, .. }
            if args.is_empty() && attrs.iter().any(|s| s == method) =>
        {
            ExprNode::Ivar { name: method.clone() }
        }
        ExprNode::Send { recv, method, args, block, parenthesized } => ExprNode::Send {
            recv: recv.as_ref().map(&rewrite),
            method: method.clone(),
            args: args.iter().map(&rewrite).collect(),
            block: block.as_ref().map(&rewrite),
            parenthesized: *parenthesized,
        },
        ExprNode::Seq { exprs } => ExprNode::Seq {
            exprs: exprs.iter().map(&rewrite).collect(),
        },
        ExprNode::Array { elements, style } => ExprNode::Array {
            elements: elements.iter().map(&rewrite).collect(),
            style: *style,
        },
        ExprNode::Hash { entries, braced } => ExprNode::Hash {
            entries: entries
                .iter()
                .map(|(k, v)| (rewrite(k), rewrite(v)))
                .collect(),
            braced: *braced,
        },
        ExprNode::If { cond, then_branch, else_branch } => ExprNode::If {
            cond: rewrite(cond),
            then_branch: rewrite(then_branch),
            else_branch: rewrite(else_branch),
        },
        ExprNode::Case { scrutinee, arms } => ExprNode::Case {
            scrutinee: rewrite(scrutinee),
            arms: arms
                .iter()
                .map(|arm| Arm {
                    pattern: arm.pattern.clone(),
                    guard: arm.guard.as_ref().map(&rewrite),
                    body: rewrite(&arm.body),
                })
                .collect(),
        },
        ExprNode::BoolOp { op, surface, left, right } => ExprNode::BoolOp {
            op: *op,
            surface: *surface,
            left: rewrite(left),
            right: rewrite(right),
        },
        ExprNode::StringInterp { parts } => ExprNode::StringInterp {
            parts: parts
                .iter()
                .map(|p| match p {
                    InterpPart::Text { value } => InterpPart::Text { value: value.clone() },
                    InterpPart::Expr { expr } => InterpPart::Expr { expr: rewrite(expr) },
                })
                .collect(),
        },
        ExprNode::Let { id, name, value, body } => ExprNode::Let {
            id: *id,
            name: name.clone(),
            value: rewrite(value),
            body: rewrite(body),
        },
        ExprNode::Lambda { params, block_param, body, block_style } => ExprNode::Lambda {
            params: params.clone(),
            block_param: block_param.clone(),
            body: rewrite(body),
            block_style: *block_style,
        },
        ExprNode::Apply { fun, args, block } => ExprNode::Apply {
            fun: rewrite(fun),
            args: args.iter().map(&rewrite).collect(),
            block: block.as_ref().map(&rewrite),
        },
        ExprNode::Assign { target, value } => {
            let new_target = match target {
                LValue::Var { id, name } => LValue::Var { id: *id, name: name.clone() },
                LValue::Ivar { name } => LValue::Ivar { name: name.clone() },
                LValue::Attr { recv, name } => LValue::Attr {
                    recv: rewrite(recv),
                    name: name.clone(),
                },
                LValue::Index { recv, index } => LValue::Index {
                    recv: rewrite(recv),
                    index: rewrite(index),
                },
            };
            ExprNode::Assign {
                target: new_target,
                value: rewrite(value),
            }
        }
        ExprNode::Yield { args } => ExprNode::Yield {
            args: args.iter().map(&rewrite).collect(),
        },
        ExprNode::Raise { value } => ExprNode::Raise { value: rewrite(value) },
        ExprNode::RescueModifier { expr, fallback } => ExprNode::RescueModifier {
            expr: rewrite(expr),
            fallback: rewrite(fallback),
        },
        ExprNode::Lit { .. }
        | ExprNode::Var { .. }
        | ExprNode::Ivar { .. }
        | ExprNode::Const { .. }
        | ExprNode::SelfRef => (*e.node).clone(),
        ExprNode::Return { value } => ExprNode::Return { value: rewrite(value) },
        ExprNode::Super { args } => ExprNode::Super {
            args: args.as_ref().map(|v| v.iter().map(&rewrite).collect()),
        },
        ExprNode::BeginRescue { body, rescues, else_branch, ensure, implicit } => {
            ExprNode::BeginRescue {
                body: rewrite(body),
                rescues: rescues
                    .iter()
                    .map(|rc| crate::expr::RescueClause {
                        classes: rc.classes.iter().map(&rewrite).collect(),
                        binding: rc.binding.clone(),
                        body: rewrite(&rc.body),
                    })
                    .collect(),
                else_branch: else_branch.as_ref().map(&rewrite),
                ensure: ensure.as_ref().map(&rewrite),
                implicit: *implicit,
            }
        }
    };
    let _ = Pattern::Wildcard;
    Expr {
        span: e.span,
        node: Box::new(new_node),
        ty: e.ty.clone(),
        effects: e.effects.clone(),
        leading_blank_line: e.leading_blank_line,
        diagnostic: e.diagnostic.clone(),
    }
}
