use std::collections::HashSet;
use std::fmt::Write;
use std::path::PathBuf;

use crate::App;
use crate::emit::EmittedFile;
use crate::lower::routes::{flatten_routes, FlatRoute};

pub fn emit_route_helpers(app: &App) -> EmittedFile {
    let routes = flatten_routes(app);

    let mut out = String::new();
    writeln!(out, "// Generated by Roundhouse.").unwrap();
    writeln!(out).unwrap();

    let mut seen: HashSet<String> = HashSet::new();
    for r in &routes {
        if !seen.insert(r.as_name.clone()) {
            continue;
        }
        emit_one_helper(&mut out, r);
    }

    EmittedFile { path: PathBuf::from("src/route_helpers.ts"), content: out }
}

fn emit_one_helper(out: &mut String, r: &FlatRoute) {
    let fn_name = format!("{}Path", lower_camel(&r.as_name));
    let params: Vec<String> = r.path_params.iter().map(|p| format!("{p}: number")).collect();

    if r.path_params.is_empty() {
        writeln!(
            out,
            "export function {fn_name}(): string {{ return \"{}\"; }}",
            r.path,
        )
        .unwrap();
    } else {
        let template = path_to_template(&r.path);
        writeln!(
            out,
            "export function {fn_name}({}): string {{ return `{template}`; }}",
            params.join(", "),
        )
        .unwrap();
    }
}

/// Convert a snake_case identifier to lowerCamelCase. The first
/// segment stays lowercase; subsequent segments capitalize the
/// first letter.
fn lower_camel(snake: &str) -> String {
    let mut out = String::with_capacity(snake.len());
    let mut upper_next = false;
    for (i, c) in snake.chars().enumerate() {
        if c == '_' {
            upper_next = true;
        } else if upper_next {
            out.push(c.to_ascii_uppercase());
            upper_next = false;
        } else {
            out.push(if i == 0 { c.to_ascii_lowercase() } else { c });
        }
    }
    out
}

/// Convert `/articles/:id/edit` → `/articles/${id}/edit`.
fn path_to_template(path: &str) -> String {
    let mut out = String::with_capacity(path.len() + 4);
    let mut chars = path.chars().peekable();
    while let Some(c) = chars.next() {
        if c == ':' {
            let mut ident = String::new();
            while let Some(&nc) = chars.peek() {
                if nc.is_alphanumeric() || nc == '_' {
                    ident.push(nc);
                    chars.next();
                } else {
                    break;
                }
            }
            out.push_str("${");
            out.push_str(&ident);
            out.push('}');
        } else {
            out.push(c);
        }
    }
    out
}
