//! Route emission — `src/routes.ts` (`Router.root` / `Router.resources`
//! calls, plus per-controller imports). Matches ruby2js's rails routes
//! filter (`spec/rails_routes_spec.rb`).

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use crate::App;
use crate::dialect::RouteSpec;

// Routes ---------------------------------------------------------------

/// Emit the Juntos-shaped routes file: `Router.root(...)` for any
/// `root "c#a"` entries and `Router.resources("name", XController,
/// { nested: [...] })` for each `resources :name` block. Per-
/// controller imports go at the top. Matches ruby2js's rails routes
/// filter (`spec/rails_routes_spec.rb`).
pub(super) fn emit_routes(app: &App) -> EmittedFile {
    // Collect every controller class-name the routes reference, so
    // we can emit one import per controller. Uses a Vec (preserving
    // source order) with de-duplication; a HashSet would lose
    // ordering and the deterministic import layout is nicer for
    // source-equivalence down the road.
    let mut controllers: Vec<String> = Vec::new();
    let mut push_controller = |name: String, out: &mut Vec<String>| {
        if !out.iter().any(|c| c == &name) {
            out.push(name);
        }
    };
    for entry in &app.routes.entries {
        collect_controller_refs(entry, &mut controllers, &mut push_controller);
    }

    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s, "import {{ Router }} from \"juntos\";").unwrap();
    for controller in &controllers {
        let file_stem = crate::naming::snake_case(controller);
        writeln!(
            s,
            "import {{ {controller} }} from \"../app/controllers/{file_stem}.js\";"
        )
        .unwrap();
    }
    writeln!(s).unwrap();
    for entry in &app.routes.entries {
        emit_route_spec(&mut s, entry);
    }
    EmittedFile { path: PathBuf::from("src/routes.ts"), content: s }
}

/// Walk the route spec tree and push every controller class-name
/// into `out` (via the dedup closure). Follows nested resources.
fn collect_controller_refs(
    spec: &RouteSpec,
    out: &mut Vec<String>,
    push: &mut impl FnMut(String, &mut Vec<String>),
) {
    match spec {
        RouteSpec::Explicit { controller, .. } => {
            push(controller.0.to_string(), out);
        }
        RouteSpec::Root { target } => {
            if let Some((c, _)) = target.split_once('#') {
                push(controller_class_name(c), out);
            }
        }
        RouteSpec::Resources { name, nested, .. } => {
            push(controller_class_name(name.as_str()), out);
            for child in nested {
                collect_controller_refs(child, out, push);
            }
        }
    }
}

/// Emit one route spec as a Router.* call. Nested resources appear
/// as a `{ nested: [...] }` option list on the outer resources call.
fn emit_route_spec(out: &mut String, spec: &RouteSpec) {
    match spec {
        RouteSpec::Explicit { method, path, controller, action, .. } => {
            // Ruby2js doesn't have a direct Router shortcut for raw
            // verb routes; emit a low-level `Router.add` call so the
            // route still registers. No fixture exercises this path
            // (tiny-blog has explicit routes; real-blog uses
            // resources) — sharpen when one does.
            let verb = match method {
                crate::dialect::HttpMethod::Get => "get",
                crate::dialect::HttpMethod::Post => "post",
                crate::dialect::HttpMethod::Put => "put",
                crate::dialect::HttpMethod::Patch => "patch",
                crate::dialect::HttpMethod::Delete => "delete",
                crate::dialect::HttpMethod::Head => "head",
                crate::dialect::HttpMethod::Options => "options",
                crate::dialect::HttpMethod::Any => "match",
            };
            writeln!(
                out,
                "Router.{verb}({:?}, {}, {:?});",
                path,
                controller.0,
                action.as_str(),
            )
            .unwrap();
        }
        RouteSpec::Root { target } => {
            let (controller, action) = target
                .split_once('#')
                .map(|(c, a)| (controller_class_name(c), a.to_string()))
                .unwrap_or_else(|| (target.clone(), "index".to_string()));
            writeln!(out, "Router.root(\"/\", {controller}, {action:?});").unwrap();
        }
        RouteSpec::Resources { name, only, except: _, nested } => {
            let controller = controller_class_name(name.as_str());
            let mut opts: Vec<String> = Vec::new();
            if !only.is_empty() {
                let parts: Vec<String> =
                    only.iter().map(|s| format!("{:?}", s.as_str())).collect();
                opts.push(format!("only: [{}]", parts.join(", ")));
            }
            // except: is handled at build time per ruby2js's filter —
            // not passed to Router.resources at runtime. We mirror.
            if !nested.is_empty() {
                let mut nested_parts: Vec<String> = Vec::new();
                for child in nested {
                    if let Some(part) = nested_spec_entry(child) {
                        nested_parts.push(part);
                    }
                }
                if !nested_parts.is_empty() {
                    opts.push(format!("nested: [{}]", nested_parts.join(", ")));
                }
            }
            if opts.is_empty() {
                writeln!(out, "Router.resources({:?}, {});", name.as_str(), controller).unwrap();
            } else {
                writeln!(
                    out,
                    "Router.resources({:?}, {}, {{{}}});",
                    name.as_str(),
                    controller,
                    opts.join(", "),
                )
                .unwrap();
            }
        }
    }
}

/// Turn a nested child (from `resources :x do ... end`) into the
/// object-literal entry Juntos expects inside the `nested: [...]`
/// array: `{ name: "comments", controller: CommentsController, only: [...] }`.
fn nested_spec_entry(spec: &RouteSpec) -> Option<String> {
    let RouteSpec::Resources { name, only, except: _, nested, .. } = spec else {
        // Non-resources entries inside a nested block (e.g. raw
        // `get "/x"`) don't have a direct Router.resources nested
        // shape; skip for now — no fixture uses this pattern.
        return None;
    };
    let controller = controller_class_name(name.as_str());
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("name: {:?}", name.as_str()));
    parts.push(format!("controller: {controller}"));
    if !only.is_empty() {
        let os: Vec<String> = only.iter().map(|s| format!("{:?}", s.as_str())).collect();
        parts.push(format!("only: [{}]", os.join(", ")));
    }
    if !nested.is_empty() {
        let mut inner: Vec<String> = Vec::new();
        for child in nested {
            if let Some(p) = nested_spec_entry(child) {
                inner.push(p);
            }
        }
        if !inner.is_empty() {
            parts.push(format!("nested: [{}]", inner.join(", ")));
        }
    }
    Some(format!("{{{}}}", parts.join(", ")))
}

fn controller_class_name(short: &str) -> String {
    let mut s = crate::naming::camelize(short);
    s.push_str("Controller");
    s
}
