use std::collections::HashSet;
use std::fmt::Write;
use std::path::PathBuf;

use crate::App;
use crate::emit::EmittedFile;
use crate::lower::routes::{flatten_routes, FlatRoute};

pub fn emit_route_helpers(app: &App) -> EmittedFile {
    let routes = flatten_routes(app);

    let mut out = String::new();
    writeln!(out, "// Generated by Roundhouse.").unwrap();
    writeln!(out).unwrap();

    // Each route gets a snake_case `articles_path` function as the
    // primary form (matching framework Ruby + Spinel emit), plus a
    // camelCase `articlesPath` alias so existing call sites keep
    // working through the view-emitter convergence. After convergence
    // the camelCase aliases can be dropped.
    let mut seen: HashSet<String> = HashSet::new();
    let mut emitted: Vec<String> = Vec::new();
    for r in &routes {
        if !seen.insert(r.as_name.clone()) {
            continue;
        }
        emit_one_helper(&mut out, r);
        emitted.push(format!("{}_path", r.as_name));
    }

    // RouteHelpers namespace export — same name + shape as Spinel's
    // Ruby-side `module RouteHelpers`. The thin TS view emitter
    // calls `RouteHelpers.articles_path(...)` directly; both forms
    // resolve to the same per-route function via this object.
    if !emitted.is_empty() {
        writeln!(out).unwrap();
        writeln!(out, "export const RouteHelpers = {{").unwrap();
        for name in &emitted {
            writeln!(out, "  {name},").unwrap();
        }
        writeln!(out, "}};").unwrap();
    }

    EmittedFile { path: PathBuf::from("src/route_helpers.ts"), content: out }
}

fn emit_one_helper(out: &mut String, r: &FlatRoute) {
    let snake_name = format!("{}_path", r.as_name);
    let camel_name = format!("{}Path", lower_camel(&r.as_name));
    let params: Vec<String> = r.path_params.iter().map(|p| format!("{p}: number")).collect();

    if r.path_params.is_empty() {
        writeln!(
            out,
            "export function {snake_name}(): string {{ return \"{}\"; }}",
            r.path,
        )
        .unwrap();
    } else {
        let template = path_to_template(&r.path);
        writeln!(
            out,
            "export function {snake_name}({}): string {{ return `{template}`; }}",
            params.join(", "),
        )
        .unwrap();
    }
    // camelCase alias — points at the snake_case function, no
    // extra runtime cost. Dropped after the view emitter migrates
    // entirely to snake_case + RouteHelpers namespace.
    writeln!(out, "export const {camel_name} = {snake_name};").unwrap();
}

/// Convert a snake_case identifier to lowerCamelCase. The first
/// segment stays lowercase; subsequent segments capitalize the
/// first letter.
fn lower_camel(snake: &str) -> String {
    let mut out = String::with_capacity(snake.len());
    let mut upper_next = false;
    for (i, c) in snake.chars().enumerate() {
        if c == '_' {
            upper_next = true;
        } else if upper_next {
            out.push(c.to_ascii_uppercase());
            upper_next = false;
        } else {
            out.push(if i == 0 { c.to_ascii_lowercase() } else { c });
        }
    }
    out
}

/// Convert `/articles/:id/edit` → `/articles/${id}/edit`.
fn path_to_template(path: &str) -> String {
    let mut out = String::with_capacity(path.len() + 4);
    let mut chars = path.chars().peekable();
    while let Some(c) = chars.next() {
        if c == ':' {
            let mut ident = String::new();
            while let Some(&nc) = chars.peek() {
                if nc.is_alphanumeric() || nc == '_' {
                    ident.push(nc);
                    chars.next();
                } else {
                    break;
                }
            }
            out.push_str("${");
            out.push_str(&ident);
            out.push('}');
        } else {
            out.push(c);
        }
    }
    out
}
