//! `src/schema_sql.ts` emission — TypeScript constant wrapping the
//! lowered DDL.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use crate::App;

/// `src/schema_sql.ts` — TypeScript constant wrapping the target-neutral
/// DDL produced by `lower::lower_schema`. `setupTestDb` executes the
/// string via `better-sqlite3`'s `Database#exec` (which handles
/// multi-statement batches natively).
pub(super) fn emit_schema_sql_ts(app: &App) -> EmittedFile {
    let ddl = crate::lower::lower_schema(&app.schema);
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s, "export const CREATE_TABLES = `").unwrap();
    s.push_str(&ddl);
    writeln!(s, "`;").unwrap();
    EmittedFile {
        path: PathBuf::from("src/schema_sql.ts"),
        content: s,
    }
}
