//! TypeScript spec emit — one `spec/models/<name>.test.ts` per
//! ingested test module. Model tests render through the local
//! `SpecCtx`-driven walker; controller tests delegate to
//! `emit_ts_controller_test`.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use super::emit_literal;
use crate::App;
use crate::dialect::{Test, TestModule};
use crate::expr::{Expr, ExprNode, LValue, Literal};
use crate::ident::Symbol;

pub(super) fn emit_ts_spec(tm: &TestModule, app: &App) -> EmittedFile {
    let fixture_names: Vec<Symbol> =
        app.fixtures.iter().map(|f| f.name.clone()).collect();
    let known_models: Vec<Symbol> =
        app.models.iter().map(|m| m.name.0.clone()).collect();
    let mut attrs_set: std::collections::BTreeSet<Symbol> =
        std::collections::BTreeSet::new();
    for m in &app.models {
        for attr in m.attributes.fields.keys() {
            attrs_set.insert(attr.clone());
        }
    }
    let model_attrs: Vec<Symbol> = attrs_set.into_iter().collect();

    let ctx = SpecCtx {
        app,
        fixture_names: &fixture_names,
        known_models: &known_models,
        model_attrs: &model_attrs,
    };

    let is_controller_test = tm.name.0.as_str().ends_with("ControllerTest");

    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s, "import {{ test, beforeEach }} from \"node:test\";").unwrap();
    writeln!(s, "import assert from \"node:assert/strict\";").unwrap();
    if is_controller_test {
        // Side-effect import: routes.ts pushes into the Router match
        // table at module load. Needed before any dispatch.
        writeln!(s, "import \"../../src/routes.js\";").unwrap();
        writeln!(s, "import {{ TestClient }} from \"../../src/test_support.js\";").unwrap();
        writeln!(s, "import * as routeHelpers from \"../../src/route_helpers.js\";").unwrap();
    }
    // Per-model class imports — one per known model, so `new Article()`
    // etc. in test bodies resolve. Models are siblings under
    // app/models/.
    for model_name in &known_models {
        let file = crate::naming::snake_case(model_name.as_str());
        writeln!(
            s,
            "import {{ {} }} from \"../../app/models/{}.js\";",
            model_name, file,
        )
        .unwrap();
    }
    for fixture in &app.fixtures {
        writeln!(
            s,
            "import * as {}Fixtures from \"../fixtures/{}.js\";",
            crate::naming::camelize(fixture.name.as_str()),
            fixture.name,
        )
        .unwrap();
    }
    // Every test starts on a fresh :memory: DB + fully-loaded
    // fixtures. `beforeEach` runs across the whole spec file, matching
    // Rails' transactional-fixture isolation.
    if !app.fixtures.is_empty() {
        writeln!(s, "import {{ setup }} from \"../fixtures.js\";").unwrap();
        writeln!(s).unwrap();
        writeln!(s, "beforeEach(() => setup());").unwrap();
    }

    for test in &tm.tests {
        writeln!(s).unwrap();
        let test_name = &test.name;
        if is_controller_test {
            emit_ts_controller_test(&mut s, test, app);
        } else if test_needs_runtime_unsupported_ts(test) {
            writeln!(
                s,
                "test.skip({test_name:?}, () => {{"
            )
            .unwrap();
            writeln!(s, "  // Phase 3: needs persistence runtime").unwrap();
            writeln!(s, "}});").unwrap();
        } else {
            writeln!(s, "test({test_name:?}, () => {{").unwrap();
            let body = emit_spec_body_ts(&test.body, ctx);
            for line in body.lines() {
                writeln!(s, "  {line}").unwrap();
            }
            writeln!(s, "}});").unwrap();
        }
    }

    let filename = crate::naming::snake_case(tm.name.0.as_str());
    let filename = filename.replace("_test", ".test");
    EmittedFile {
        path: PathBuf::from(format!("spec/models/{filename}.ts")),
        content: s,
    }
}

#[derive(Clone, Copy)]
struct SpecCtx<'a> {
    app: &'a App,
    fixture_names: &'a [Symbol],
    known_models: &'a [Symbol],
    model_attrs: &'a [Symbol],
}

fn emit_spec_body_ts(body: &Expr, ctx: SpecCtx) -> String {
    match &*body.node {
        ExprNode::Seq { exprs } if !exprs.is_empty() => exprs
            .iter()
            .map(|e| emit_spec_stmt_ts(e, ctx))
            .collect::<Vec<_>>()
            .join("\n"),
        _ => emit_spec_stmt_ts(body, ctx),
    }
}

fn emit_spec_stmt_ts(e: &Expr, ctx: SpecCtx) -> String {
    match &*e.node {
        ExprNode::Assign { target: LValue::Var { name, .. }, value } => {
            format!("const {} = {};", name, emit_spec_expr_ts(value, ctx))
        }
        _ => format!("{};", emit_spec_expr_ts(e, ctx)),
    }
}

fn emit_spec_expr_ts(e: &Expr, ctx: SpecCtx) -> String {
    use crate::expr::InterpPart;
    match &*e.node {
        ExprNode::Lit { value } => emit_literal(value),
        ExprNode::Var { name, .. } => name.to_string(),
        ExprNode::Const { path } => {
            path.iter().map(|s| s.to_string()).collect::<Vec<_>>().join(".")
        }
        ExprNode::Hash { entries, .. } => {
            let parts: Vec<String> = entries
                .iter()
                .map(|(k, v)| {
                    let key = match &*k.node {
                        ExprNode::Lit { value: Literal::Sym { value } } => {
                            value.as_str().to_string()
                        }
                        _ => emit_spec_expr_ts(k, ctx),
                    };
                    format!("{}: {}", key, emit_spec_expr_ts(v, ctx))
                })
                .collect();
            format!("{{ {} }}", parts.join(", "))
        }
        ExprNode::Array { elements, .. } => {
            let parts: Vec<String> =
                elements.iter().map(|e| emit_spec_expr_ts(e, ctx)).collect();
            format!("[{}]", parts.join(", "))
        }
        ExprNode::StringInterp { parts } => {
            let mut out = String::from("`");
            for p in parts {
                match p {
                    InterpPart::Text { value } => out.push_str(value),
                    InterpPart::Expr { expr } => {
                        out.push_str("${");
                        out.push_str(&emit_spec_expr_ts(expr, ctx));
                        out.push('}');
                    }
                }
            }
            out.push('`');
            out
        }
        ExprNode::Send { recv, method, args, block, .. } => {
            emit_spec_send_ts(recv.as_ref(), method.as_str(), args, block.as_ref(), ctx)
        }
        ExprNode::BoolOp { op, left, right, .. } => {
            use crate::expr::BoolOpKind;
            let op_s = match op {
                BoolOpKind::Or => "||",
                BoolOpKind::And => "&&",
            };
            format!(
                "{} {} {}",
                emit_spec_expr_ts(left, ctx),
                op_s,
                emit_spec_expr_ts(right, ctx)
            )
        }
        _ => format!("/* TODO: spec emit for {:?} */", std::mem::discriminant(&*e.node)),
    }
}

fn emit_spec_send_ts(
    recv: Option<&Expr>,
    method: &str,
    args: &[Expr],
    block: Option<&Expr>,
    ctx: SpecCtx,
) -> String {
    let args_s: Vec<String> = args.iter().map(|a| emit_spec_expr_ts(a, ctx)).collect();

    // Fixture accessor: articles(:one) → articlesFixtures.one()
    if recv.is_none()
        && args.len() == 1
        && ctx.fixture_names.iter().any(|s| s.as_str() == method)
    {
        if let ExprNode::Lit { value: Literal::Sym { value: sym } } = &*args[0].node {
            let ns = crate::naming::camelize(method);
            return format!("{ns}Fixtures.{}()", sym.as_str());
        }
    }

    // assert_difference("Class.count", delta) do ... end → inline
    // before/after capture + assert.strictEqual on the delta.
    if recv.is_none() && method == "assert_difference" {
        if let Some(body) = block {
            if let Some(count_expr) = args
                .first()
                .and_then(|a| match &*a.node {
                    ExprNode::Lit { value: Literal::Str { value } } => {
                        rewrite_ruby_dot_call_ts(value)
                    }
                    _ => None,
                })
            {
                let delta = args_s.get(1).cloned().unwrap_or_else(|| "1".into());
                let body_s = emit_block_body_ts(body, ctx);
                return format!(
                    "(() => {{\n  const _before = {count_expr};\n  {body_s}\n  const _after = {count_expr};\n  assert.strictEqual(_after - _before, {delta});\n}})()"
                );
            }
        }
    }

    // owner.<assoc>.create(hash) / .build(hash) — HasMany rewrite.
    if (method == "create" || method == "build") && args.len() == 1 {
        if let Some(outer_recv) = recv {
            if let ExprNode::Send {
                recv: Some(assoc_recv),
                method: assoc_method,
                args: inner_args,
                ..
            } = &*outer_recv.node
            {
                if inner_args.is_empty() {
                    if let Some(s) = try_emit_assoc_create_ts(
                        assoc_recv,
                        assoc_method.as_str(),
                        args,
                        method,
                        ctx,
                    ) {
                        return s;
                    }
                }
            }
        }
    }

    // Assertion mapping. node:test uses `node:assert/strict` which
    // provides `assert.strictEqual`, `assert.notStrictEqual`,
    // `assert.ok`, etc. Ruby's `assert_equal expected, actual`
    // argument order flips to actual-first for Node.
    if recv.is_none() {
        match (method, args_s.len()) {
            ("assert_equal", 2) => {
                return format!("assert.strictEqual({}, {})", args_s[1], args_s[0]);
            }
            ("assert_not_equal", 2) => {
                return format!("assert.notStrictEqual({}, {})", args_s[1], args_s[0]);
            }
            ("assert_not", 1) => {
                return format!("assert.ok(!({}))", args_s[0]);
            }
            ("assert", 1) => {
                return format!("assert.ok({})", args_s[0]);
            }
            ("assert_nil", 1) => {
                return format!("assert.strictEqual({}, null)", args_s[0]);
            }
            ("assert_not_nil", 1) => {
                return format!("assert.notStrictEqual({}, null)", args_s[0]);
            }
            _ => {}
        }
    }

    // `Class.new(hash)` → Object.assign(new Class(), { k: v, ... })
    if let Some(r) = recv {
        if method == "new" && args.len() == 1 {
            if let ExprNode::Const { path } = &*r.node {
                if let Some(class_name) = path.last() {
                    if ctx.known_models.iter().any(|s| s == class_name) {
                        if let ExprNode::Hash { entries, .. } = &*args[0].node {
                            let pairs: Vec<String> = entries
                                .iter()
                                .map(|(k, v)| {
                                    let key = match &*k.node {
                                        ExprNode::Lit {
                                            value: Literal::Sym { value: f },
                                        } => f.as_str().to_string(),
                                        _ => emit_spec_expr_ts(k, ctx),
                                    };
                                    format!("{}: {}", key, emit_spec_expr_ts(v, ctx))
                                })
                                .collect();
                            return format!(
                                "Object.assign(new {}(), {{ {} }})",
                                class_name,
                                pairs.join(", ")
                            );
                        }
                    }
                }
            }
        }
    }

    match recv {
        None => {
            if args_s.is_empty() {
                method.to_string()
            } else {
                format!("{}({})", method, args_s.join(", "))
            }
        }
        Some(r) => {
            let recv_s = emit_spec_expr_ts(r, ctx);
            let is_class_call = matches!(&*r.node, ExprNode::Const { .. });
            // Class-level calls are always methods (e.g. `Comment.count`).
            if is_class_call {
                if args_s.is_empty() {
                    return format!("{recv_s}.{method}()");
                } else {
                    return format!("{recv_s}.{method}({})", args_s.join(", "));
                }
            }
            // Instance-level calls: attribute reads + Juntos getters
            // (save, destroy) render without parens; other zero-arg
            // calls go method-style.
            let is_attr_read = args_s.is_empty()
                && ctx.model_attrs.iter().any(|s| s.as_str() == method);
            let is_juntos_getter =
                args_s.is_empty() && matches!(method, "save" | "destroy");
            if is_attr_read || is_juntos_getter {
                format!("{recv_s}.{method}")
            } else if args_s.is_empty() {
                format!("{recv_s}.{method}()")
            } else {
                format!("{recv_s}.{method}({})", args_s.join(", "))
            }
        }
    }
}

/// Parse a Ruby-style `"Class.method"` expression string into TS
/// `Class.method()` syntax. Used by `assert_difference` to re-
/// evaluate the captured count expression before and after the block.
fn rewrite_ruby_dot_call_ts(expr: &str) -> Option<String> {
    let trimmed = expr.trim();
    let (lhs, rhs) = trimmed.split_once('.')?;
    let is_ident = |s: &str| {
        !s.is_empty()
            && s.chars().next().is_some_and(|c| c.is_alphabetic() || c == '_')
            && s.chars().all(|c| c.is_alphanumeric() || c == '_')
    };
    if !is_ident(lhs) || !is_ident(rhs) {
        return None;
    }
    // Uppercase LHS → class-level call (`Comment.count()`).
    // Lowercase LHS → instance attribute read (`article.count`).
    let is_class = lhs.chars().next().is_some_and(|c| c.is_uppercase());
    if is_class {
        Some(format!("{lhs}.{rhs}()"))
    } else {
        Some(format!("{lhs}.{rhs}"))
    }
}

/// Render a Ruby block body as TS statements, peeling one Lambda
/// layer. Ruby `do ... end` lowers to `ExprNode::Lambda`.
fn emit_block_body_ts(e: &Expr, ctx: SpecCtx) -> String {
    let inner = match &*e.node {
        ExprNode::Lambda { body, .. } => body,
        _ => e,
    };
    match &*inner.node {
        ExprNode::Seq { exprs } if !exprs.is_empty() => exprs
            .iter()
            .map(|s| emit_spec_stmt_ts(s, ctx))
            .collect::<Vec<_>>()
            .join("\n  "),
        _ => emit_spec_stmt_ts(inner, ctx),
    }
}

fn try_emit_assoc_create_ts(
    owner: &Expr,
    assoc_name: &str,
    args: &[Expr],
    outer_method: &str,
    ctx: SpecCtx,
) -> Option<String> {
    let resolved = crate::lower::resolve_has_many(
        &Symbol::from(assoc_name),
        owner.ty.as_ref(),
        ctx.app,
    )?;
    let target_class = resolved.target_class.0.as_str();
    let foreign_key = resolved.foreign_key.as_str();

    let owner_s = emit_spec_expr_ts(owner, ctx);
    let hash_entries = match &args.first()?.node.as_ref() {
        ExprNode::Hash { entries, .. } => entries.clone(),
        _ => return None,
    };

    let mut pairs: Vec<String> =
        vec![format!("{foreign_key}: {owner_s}.id")];
    for (k, v) in &hash_entries {
        if let ExprNode::Lit { value: Literal::Sym { value: field_name } } = &*k.node {
            pairs.push(format!("{}: {}", field_name.as_str(), emit_spec_expr_ts(v, ctx)));
        }
    }
    // `.build` returns the unsaved record; `.create` runs save first.
    // Both evaluate to the record.
    let construct = format!(
        "Object.assign(new {target_class}(), {{ {} }})",
        pairs.join(", "),
    );
    if outer_method == "create" {
        Some(format!("(() => {{ const _r = {construct}; _r.save; return _r; }})()"))
    } else {
        Some(construct)
    }
}

fn test_needs_runtime_unsupported_ts(_test: &Test) -> bool {
    // Phase 3 rounded out the TS emitter's handling of the real-blog
    // test shapes. Keep as future-guard; no current pattern forces a
    // skip.
    false
}

#[allow(dead_code)]

fn test_body_uses_unsupported_ts(e: &Expr) -> bool {
    use crate::expr::InterpPart;
    let self_hit = match &*e.node {
        ExprNode::Send { recv, method, .. } => {
            let m = method.as_str();
            matches!(
                m,
                "assert_difference"
                    | "destroy"
                    | "destroy!"
                    | "build"
                    | "create"
                    | "create!"
            ) || (m == "count"
                && recv.as_ref().is_some_and(|r| matches!(&*r.node, ExprNode::Const { .. })))
        }
        _ => false,
    };
    if self_hit {
        return true;
    }
    match &*e.node {
        ExprNode::Send { recv, args, block, .. } => {
            if let Some(r) = recv {
                if test_body_uses_unsupported_ts(r) {
                    return true;
                }
            }
            for a in args {
                if test_body_uses_unsupported_ts(a) {
                    return true;
                }
            }
            if let Some(b) = block {
                if test_body_uses_unsupported_ts(b) {
                    return true;
                }
            }
        }
        ExprNode::Seq { exprs } | ExprNode::Array { elements: exprs, .. } => {
            for e in exprs {
                if test_body_uses_unsupported_ts(e) {
                    return true;
                }
            }
        }
        ExprNode::Hash { entries, .. } => {
            for (k, v) in entries {
                if test_body_uses_unsupported_ts(k) || test_body_uses_unsupported_ts(v) {
                    return true;
                }
            }
        }
        ExprNode::StringInterp { parts } => {
            for p in parts {
                if let InterpPart::Expr { expr } = p {
                    if test_body_uses_unsupported_ts(expr) {
                        return true;
                    }
                }
            }
        }
        ExprNode::BoolOp { left, right, .. }
        | ExprNode::RescueModifier { expr: left, fallback: right } => {
            if test_body_uses_unsupported_ts(left) || test_body_uses_unsupported_ts(right) {
                return true;
            }
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            if test_body_uses_unsupported_ts(cond)
                || test_body_uses_unsupported_ts(then_branch)
                || test_body_uses_unsupported_ts(else_branch)
            {
                return true;
            }
        }
        ExprNode::Let { value, body, .. } => {
            if test_body_uses_unsupported_ts(value) || test_body_uses_unsupported_ts(body) {
                return true;
            }
        }
        ExprNode::Lambda { body, .. } => {
            if test_body_uses_unsupported_ts(body) {
                return true;
            }
        }
        ExprNode::Assign { value, .. } => {
            if test_body_uses_unsupported_ts(value) {
                return true;
            }
        }
        _ => {}
    }
    false
}

/// Emit a single controller test (`test("name", async () => { ... })`).
/// Mirrors `emit_rust_controller_test`. Primes ivars from fixtures,
/// opens a fresh `TestClient`, then walks test-body statements.
fn emit_ts_controller_test(out: &mut String, test: &Test, app: &App) {
    writeln!(out, "test({:?}, async () => {{", test.name.as_str()).unwrap();
    writeln!(out, "  const client = new TestClient();").unwrap();

    let walked = crate::lower::walk_controller_ivars(&test.body);
    for ivar in walked.ivars_read_without_assign() {
        let plural = crate::naming::pluralize_snake(&crate::naming::camelize(ivar.as_str()));
        let fixt_ns = crate::naming::camelize(&plural);
        writeln!(
            out,
            "  const {} = {}Fixtures.one();",
            ivar.as_str(),
            fixt_ns,
        )
        .unwrap();
    }

    let stmts = ts_ctrl_test_body_stmts(&test.body);
    for stmt in stmts {
        let rendered = emit_ts_ctrl_test_stmt(stmt, app);
        for line in rendered.lines() {
            writeln!(out, "  {line}").unwrap();
        }
    }

    writeln!(out, "}});").unwrap();
}

fn ts_ctrl_test_body_stmts(body: &Expr) -> Vec<&Expr> {
    crate::lower::test_body_stmts(body)
}

fn emit_ts_ctrl_test_stmt(stmt: &Expr, app: &App) -> String {
    match &*stmt.node {
        ExprNode::Send { recv: None, method, args, block, .. } => {
            emit_ts_ctrl_test_send(method.as_str(), args, block.as_ref(), app)
        }
        ExprNode::Send { recv: Some(r), method, args, .. } => {
            if method.as_str() == "reload" {
                let recv_s = match &*r.node {
                    ExprNode::Ivar { name } | ExprNode::Var { name, .. } => name.to_string(),
                    _ => emit_ts_ctrl_test_expr(r, app),
                };
                return format!("{recv_s}.reload();");
            }
            let recv_s = emit_ts_ctrl_test_expr(r, app);
            let args_s: Vec<String> =
                args.iter().map(|a| emit_ts_ctrl_test_expr(a, app)).collect();
            if args_s.is_empty() {
                format!("{recv_s}.{method};")
            } else {
                format!("{recv_s}.{method}({});", args_s.join(", "))
            }
        }
        ExprNode::Assign { target: LValue::Var { name, .. }, value } => {
            format!("let {name} = {};", emit_ts_ctrl_test_expr(value, app))
        }
        ExprNode::Assign { target: LValue::Ivar { name }, value } => {
            format!("let {name} = {};", emit_ts_ctrl_test_expr(value, app))
        }
        _ => format!("{};", emit_ts_ctrl_test_expr(stmt, app)),
    }
}

fn emit_ts_ctrl_test_send(
    method: &str,
    args: &[Expr],
    block: Option<&Expr>,
    app: &App,
) -> String {
    use crate::lower::ControllerTestSend;
    match crate::lower::classify_controller_test_send(method, args, block) {
        Some(ControllerTestSend::HttpGet { url }) => {
            let u = emit_ts_url_expr(url, app);
            format!("const resp = await client.get({u});")
        }
        Some(ControllerTestSend::HttpWrite { method, url, params }) => {
            let u = emit_ts_url_expr(url, app);
            let body = params
                .map(|h| flatten_ts_params_to_form(h, None, app))
                .unwrap_or_else(|| "{}".to_string());
            format!("const resp = await client.{method}({u}, {body});")
        }
        Some(ControllerTestSend::HttpDelete { url }) => {
            let u = emit_ts_url_expr(url, app);
            format!("const resp = await client.delete({u});")
        }
        Some(ControllerTestSend::AssertResponse { sym }) => match sym.as_str() {
            "success" => "resp.assertOk();".to_string(),
            "unprocessable_entity" => "resp.assertUnprocessable();".to_string(),
            other => format!("resp.assertStatus(/* {other:?} */ 200);"),
        },
        Some(ControllerTestSend::AssertRedirectedTo { url }) => {
            let u = emit_ts_url_expr(url, app);
            format!("resp.assertRedirectedTo({u});")
        }
        Some(ControllerTestSend::AssertSelect { selector, kind }) => {
            emit_ts_assert_select_classified(selector, kind, app)
        }
        Some(ControllerTestSend::AssertDifference { method, count_expr, delta, block }) => {
            let _ = method;
            emit_ts_assert_difference_classified(count_expr, delta, block, app)
        }
        Some(ControllerTestSend::AssertEqual { expected, actual }) => {
            let e = emit_ts_ctrl_test_expr(expected, app);
            let a = emit_ts_ctrl_test_expr(actual, app);
            // Rails calls assert_equal(expected, actual); node:test
            // assert.equal takes (actual, expected) — swap order.
            format!("assert.equal({a}, {e});")
        }
        None => {
            let args_s: Vec<String> =
                args.iter().map(|a| emit_ts_ctrl_test_expr(a, app)).collect();
            if args_s.is_empty() {
                format!("{method}();")
            } else {
                format!("{method}({});", args_s.join(", "))
            }
        }
    }
}

/// `articles_url`, `article_url(@article)` → `routeHelpers.articlesPath()`,
/// `routeHelpers.articlePath(article.id)`. Uses the shared URL-helper
/// classifier; target-specific pieces are (a) helper name casing and
/// (b) the optional-unwrap syntax for `Model.last`.
fn emit_ts_url_expr(expr: &Expr, app: &App) -> String {
    use crate::lower::UrlArg;
    let Some(helper) = crate::lower::classify_url_expr(expr) else {
        return emit_ts_ctrl_test_expr(expr, app);
    };
    let camel = crate::naming::camelize(&helper.helper_base);
    let mut chars = camel.chars();
    let helper_name = match chars.next() {
        Some(c) => format!("{}{}Path", c.to_lowercase(), chars.as_str()),
        None => format!("{}Path", helper.helper_base),
    };
    let args_s: Vec<String> = helper
        .args
        .iter()
        .map(|a| match a {
            UrlArg::IvarOrVarId(name) => format!("{name}.id"),
            UrlArg::ModelLast(class) => format!("{}.last()!.id", class.as_str()),
            UrlArg::Raw(e) => emit_ts_ctrl_test_expr(e, app),
        })
        .collect();
    format!("routeHelpers.{helper_name}({})", args_s.join(", "))
}

fn emit_ts_assert_select_classified(
    selector_expr: &Expr,
    kind: crate::lower::AssertSelectKind<'_>,
    app: &App,
) -> String {
    use crate::lower::AssertSelectKind;
    let ExprNode::Lit { value: Literal::Str { value: selector } } = &*selector_expr.node
    else {
        return format!(
            "/* TODO: dynamic selector */ resp.assertSelect({});",
            emit_ts_ctrl_test_expr(selector_expr, app),
        );
    };
    match kind {
        AssertSelectKind::Text(expr) => {
            let text = emit_ts_ctrl_test_expr(expr, app);
            format!("resp.assertSelectText({selector:?}, {text});")
        }
        AssertSelectKind::Minimum(expr) => {
            let n = emit_ts_ctrl_test_expr(expr, app);
            format!("resp.assertSelectMin({selector:?}, {n});")
        }
        AssertSelectKind::SelectorBlock(b) => {
            let mut out = String::new();
            out.push_str(&format!("resp.assertSelect({selector:?});\n"));
            let inner_body = match &*b.node {
                ExprNode::Lambda { body, .. } => body,
                _ => b,
            };
            for stmt in ts_ctrl_test_body_stmts(inner_body) {
                out.push_str(&emit_ts_ctrl_test_stmt(stmt, app));
                out.push('\n');
            }
            out.trim_end().to_string()
        }
        AssertSelectKind::SelectorOnly => {
            format!("resp.assertSelect({selector:?});")
        }
    }
}

fn emit_ts_assert_difference_classified(
    count_expr_str: String,
    expected_delta: i64,
    block: Option<&Expr>,
    app: &App,
) -> String {
    // `Article.count` → `Article.count()`.
    let count_expr = count_expr_str
        .split_once('.')
        .map(|(cls, m)| format!("{cls}.{m}()"))
        .unwrap_or_else(|| count_expr_str.clone());

    let mut out = String::new();
    out.push_str(&format!("const _before = {count_expr};\n"));
    if let Some(b) = block {
        let inner_body = match &*b.node {
            ExprNode::Lambda { body, .. } => body,
            _ => b,
        };
        for stmt in ts_ctrl_test_body_stmts(inner_body) {
            out.push_str(&emit_ts_ctrl_test_stmt(stmt, app));
            out.push('\n');
        }
    }
    out.push_str(&format!("const _after = {count_expr};\n"));
    out.push_str(&format!("assert.equal(_after - _before, {expected_delta});"));
    out
}

fn emit_ts_ctrl_test_expr(expr: &Expr, app: &App) -> String {
    match &*expr.node {
        ExprNode::Lit { value } => emit_ts_literal(value),
        ExprNode::Ivar { name } => name.to_string(),
        ExprNode::Var { name, .. } => name.to_string(),
        ExprNode::Const { path } => {
            path.iter().map(|s| s.to_string()).collect::<Vec<_>>().join(".")
        }
        ExprNode::Send { recv: Some(r), method, args, .. } => {
            let m = method.as_str();
            if m == "last" && args.is_empty() {
                if let ExprNode::Const { path } = &*r.node {
                    let class = path.last().map(|s| s.as_str().to_string()).unwrap_or_default();
                    return format!("{class}.last()!");
                }
            }
            if m == "count" && args.is_empty() {
                if let ExprNode::Const { path } = &*r.node {
                    let class = path.last().map(|s| s.as_str().to_string()).unwrap_or_default();
                    return format!("{class}.count()");
                }
            }
            if args.is_empty() {
                let recv_s = match &*r.node {
                    ExprNode::Ivar { name } | ExprNode::Var { name, .. } => name.to_string(),
                    _ => emit_ts_ctrl_test_expr(r, app),
                };
                return format!("{recv_s}.{m}");
            }
            let recv_s = emit_ts_ctrl_test_expr(r, app);
            let args_s: Vec<String> =
                args.iter().map(|a| emit_ts_ctrl_test_expr(a, app)).collect();
            format!("{recv_s}.{m}({})", args_s.join(", "))
        }
        ExprNode::Send { recv: None, method, args, .. } => {
            if method.as_str().ends_with("_url") || method.as_str().ends_with("_path") {
                return emit_ts_url_expr(expr, app);
            }
            let args_s: Vec<String> =
                args.iter().map(|a| emit_ts_ctrl_test_expr(a, app)).collect();
            if args_s.is_empty() {
                method.to_string()
            } else {
                format!("{method}({})", args_s.join(", "))
            }
        }
        _ => format!("/* TODO expr {:?} */", std::mem::discriminant(&*expr.node)),
    }
}

fn emit_ts_literal(v: &Literal) -> String {
    match v {
        Literal::Str { value } => format!("{value:?}"),
        Literal::Int { value } => value.to_string(),
        Literal::Float { value } => value.to_string(),
        Literal::Bool { value } => value.to_string(),
        Literal::Nil => "null".to_string(),
        Literal::Sym { value } => format!("{:?}", value.as_str()),
    }
}

/// Flatten `{ article: { title: "X", body: "Y" } }` into a TS object
/// literal `{ "article[title]": "X", "article[body]": "Y" }` matching
/// the TestClient's form-body shape (which the controller template
/// destructures via `context.params["article[title]"]`). The key
/// flattening lives in `crate::lower::flatten_params_pairs`; this
/// function is just the TS-side value render.
fn flatten_ts_params_to_form(expr: &Expr, scope: Option<&str>, app: &App) -> String {
    let pairs: Vec<String> = crate::lower::flatten_params_pairs(expr, scope)
        .into_iter()
        .map(|(key, value)| {
            let val = emit_ts_ctrl_test_expr(value, app);
            format!("{key:?}: String({val})")
        })
        .collect();
    format!("{{ {} }}", pairs.join(", "))
}
