//! Thin TypeScript view emitter — convergence target for the
//! per-target redundancy reduction.
//!
//! Approach: lower each view through `lower::view_to_library`
//! (the same lowerer Spinel/Ruby uses) to get a canonical
//! `LibraryClass` whose method bodies are already in the
//! `io << ViewHelpers.x(...)` shape with path-arg `.id` extraction,
//! form_with restructuring, render-partial dispatch, and
//! conditional-class composition all done. This emitter just
//! renders that LibraryClass to TS via the standard expr emitter
//! plus a small statement-form wrapper for the buf-accumulate idiom.
//!
//! Activated by setting `ROUNDHOUSE_TS_VIEW_THIN=1`. Behind a flag
//! while the path is shaken out fixture-by-fixture against the
//! DOM-compare gate.

use std::fmt::Write;
use std::path::PathBuf;

use crate::App;
use crate::dialect::{LibraryClass, MethodDef, MethodReceiver};
use crate::expr::{Expr, ExprNode, Literal};
use crate::ident::Symbol;
use crate::ty::Ty;

use super::super::EmittedFile;

pub(super) fn emit_views_thin(app: &App) -> Vec<EmittedFile> {
    let known_models: Vec<Symbol> = app.models.iter().map(|m| m.name.0.clone()).collect();

    let mut files: Vec<EmittedFile> = app
        .views
        .iter()
        .map(|v| {
            let lc = crate::lower::lower_view_to_library_class(v, app);
            emit_view_class_thin(v, &lc, &known_models)
        })
        .collect();

    if let Some(stubs) = emit_ts_missing_view_stubs(app, &known_models) {
        files.push(stubs);
    }
    files.push(emit_ts_views_barrel(app));
    files
}

/// Build `app/views/all.ts` — the barrel that controllers import as
/// `Views.X`. Two export shapes:
///   - Flat: `Views.renderArticlesShow` (per-action PascalCase fn)
///   - Namespaced: `Views.Articles.show` (matches Spinel and the
///     lowered IR call shape).
/// The namespaced form casts each fn to `_ViewFn = (...args: unknown[])
/// => string` so call-site type narrowing (CollectionProxy<T>'s wider
/// element type) doesn't mismatch the per-fn typed signature.
fn emit_ts_views_barrel(app: &App) -> EmittedFile {
    use std::collections::BTreeMap;
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    for v in &app.views {
        let name = v.name.as_str();
        let path = format!("./{}.{}.js", name, v.format);
        let (dir, base) = name.rsplit_once('/').unwrap_or(("", name));
        let action = base.trim_start_matches('_');
        let render_fn = format!(
            "render{}{}",
            crate::naming::camelize(dir),
            crate::naming::camelize(action),
        );
        writeln!(s, "export {{ {render_fn} }} from {path:?};").unwrap();
        writeln!(s, "import {{ {render_fn} as _{render_fn} }} from {path:?};").unwrap();
    }
    writeln!(s, "export * from \"./_stubs.js\";").unwrap();
    writeln!(s, "import * as _stubs from \"./_stubs.js\";").unwrap();

    let mut by_dir: BTreeMap<String, Vec<(String, String)>> = BTreeMap::new();
    for v in &app.views {
        let name = v.name.as_str();
        let (dir, base) = name.rsplit_once('/').unwrap_or(("", name));
        if dir.is_empty() {
            continue;
        }
        let action = base.trim_start_matches('_').to_string();
        let render_fn = format!(
            "render{}{}",
            crate::naming::camelize(dir),
            crate::naming::camelize(&action),
        );
        by_dir
            .entry(dir.to_string())
            .or_default()
            .push((action, render_fn));
    }
    if !by_dir.is_empty() {
        writeln!(s).unwrap();
        writeln!(s, "type _ViewFn = (...args: unknown[]) => string;").unwrap();
    }
    for (dir, actions) in &by_dir {
        let ns = crate::naming::camelize(dir);
        writeln!(s, "export const {ns} = {{").unwrap();
        for (action, render_fn) in actions {
            writeln!(s, "  {action}: _{render_fn} as _ViewFn,").unwrap();
        }
        writeln!(s, "}};").unwrap();
    }

    let _ = _stubs_silencer();
    EmittedFile {
        path: PathBuf::from("app/views/all.ts"),
        content: s,
    }
}

// Compile-time noop — referencing `_stubs` in the emitted barrel
// keeps the symbol live for future namespace augmentation; this
// stub fn keeps the Rust-side import warning quiet without exposing
// public surface.
fn _stubs_silencer() -> &'static str {
    "_stubs"
}

/// Stub view fns for standard CRUD names the fixture doesn't supply
/// — controllers reference `Views.renderArticlesShow` etc. whether
/// or not an ERB template exists. Always emits the file (possibly
/// empty) so the barrel's `export * from "./_stubs.js"` resolves.
fn emit_ts_missing_view_stubs(app: &App, _known_models: &[Symbol]) -> Option<EmittedFile> {
    use std::collections::BTreeSet;
    let present: BTreeSet<String> =
        app.views.iter().map(|v| v.name.as_str().to_string()).collect();
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    let mut any = false;
    for model in &app.models {
        if model.attributes.fields.is_empty() {
            continue;
        }
        let class = model.name.0.as_str();
        let plural = crate::naming::pluralize_snake(class);
        let plural_camel = crate::naming::camelize(&plural);
        for (action, suffix) in [("Index", "index"), ("Show", "show"), ("New", "new"), ("Edit", "edit")] {
            let view_name = format!("{plural}/{suffix}");
            if present.contains(&view_name) {
                continue;
            }
            any = true;
            let fn_name = format!("render{plural_camel}{action}");
            writeln!(
                s,
                "export function {fn_name}(_record: unknown): string {{ return \"\"; }}",
            )
            .unwrap();
        }
    }
    if any {
        Some(EmittedFile {
            path: PathBuf::from("app/views/_stubs.ts"),
            content: s,
        })
    } else {
        Some(EmittedFile {
            path: PathBuf::from("app/views/_stubs.ts"),
            content: "// Generated by Roundhouse.\nexport {};\n".to_string(),
        })
    }
}

/// `articles/index` → `renderArticlesIndex`. Slashes become PascalCase
/// separators; partial-prefix underscores stay lowercased at the head
/// of the segment (`_article` → `Article` — underscore dropped).
fn view_function_name(name: &str) -> String {
    let mut out = String::from("render");
    for seg in name.split('/') {
        let trimmed = seg.strip_prefix('_').unwrap_or(seg);
        for word in trimmed.split('_') {
            let mut chars = word.chars();
            if let Some(first) = chars.next() {
                out.push(first.to_ascii_uppercase());
                out.push_str(chars.as_str());
            }
        }
    }
    out
}

fn emit_view_class_thin(
    view: &crate::dialect::View,
    lc: &LibraryClass,
    known_models: &[Symbol],
) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse (thin TS view emitter).").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "import {{ ViewHelpers }} from \"../../../src/view_helpers.js\";").unwrap();
    writeln!(s, "import {{ RouteHelpers }} from \"../../../src/route_helpers.js\";").unwrap();
    writeln!(s, "import * as Inflector from \"../../../src/inflector.js\";").unwrap();
    writeln!(s, "import * as Views from \"../all.js\";").unwrap();
    writeln!(s, "import * as Importmap from \"../../../src/importmap.js\";").unwrap();
    for m in known_models {
        writeln!(
            s,
            "import {{ {} }} from \"../../models/{}.js\";",
            m.as_str(),
            crate::naming::snake_case(m.as_str()),
        )
        .unwrap();
    }
    writeln!(s).unwrap();

    // The LibraryClass holds one method (the view's render fn). Emit
    // it as an exported TS function under the original render-name
    // (`renderArticlesShow`) so existing callers (controllers) keep
    // resolving without change. The class-wrapper shape (Spinel uses
    // `module Views::Articles; def self.show`) lowers to the same
    // function-equivalent in TS — we emit a flat function rather
    // than a class because the call site is `Views.renderArticlesX`.
    let fn_name = view_function_name(view.name.as_str());

    let method = lc.methods.iter().find(|m| matches!(m.receiver, MethodReceiver::Class));
    let Some(method) = method else {
        // Empty view — should be rare; emit a stub that returns "".
        writeln!(s, "export function {fn_name}(): string {{").unwrap();
        writeln!(s, "  return \"\";").unwrap();
        writeln!(s, "}}").unwrap();
        return EmittedFile {
            path: PathBuf::from(format!("app/views/{}.{}.ts", view.name, view.format)),
            content: s,
        };
    };

    let params_sig = render_params(method, known_models);
    writeln!(s, "export function {fn_name}({params_sig}): string {{").unwrap();
    for line in render_view_body(&method.body) {
        writeln!(s, "  {line}").unwrap();
    }
    writeln!(s, "}}").unwrap();

    EmittedFile {
        path: PathBuf::from(format!("app/views/{}.{}.ts", view.name, view.format)),
        content: s,
    }
}

/// Render the LibraryClass method's positional params as a TS arg
/// list. Model-typed args (matching a known model name from the app)
/// get the strict type; everything else falls back to `any`. The
/// lowerer surfaces `notice` / `alert` etc. as additional positional
/// params with `nil` defaults; mirror those defaults.
fn render_params(m: &MethodDef, known_models: &[Symbol]) -> String {
    m.params
        .iter()
        .map(|p| {
            let name = p.name.as_str();
            // Heuristic: if the param name matches the singular form
            // of any model in the app, type it as that model.
            let model_match = known_models.iter().find(|km| {
                let singular = crate::naming::snake_case(km.as_str());
                singular == name || crate::naming::pluralize_snake(&singular) == name
            });
            match model_match {
                Some(km) if crate::naming::snake_case(km.as_str()) == name => {
                    format!("{name}: {}", km.as_str())
                }
                Some(km) => {
                    // Plural — typed as Array of model.
                    format!("{name}: {}[]", km.as_str())
                }
                None => format!("{name}: any = null"),
            }
        })
        .collect::<Vec<_>>()
        .join(", ")
}

/// Render a view-method body into TS lines. The body shape produced
/// by `view_to_library` is:
///
///   io = String.new
///   io << ViewHelpers.x(...)
///   ...
///   io
///
/// Map `io = String.new` → `let io = "";`, `io << expr` → `io +=
/// expr;`, trailing `io` → `return io;`. Other statements (If, each,
/// content_for_set side effects) route through the standard expr
/// emitter via `super::expr::emit_expr`.
fn render_view_body(body: &Expr) -> Vec<String> {
    let reassigned = super::expr::collect_reassigned(body);
    let mut declared: std::collections::HashSet<crate::ident::Symbol> =
        std::collections::HashSet::new();
    render_view_body_with_state(body, &reassigned, &mut declared)
}

fn render_view_body_with_state(
    body: &Expr,
    reassigned: &std::collections::HashSet<crate::ident::Symbol>,
    declared: &mut std::collections::HashSet<crate::ident::Symbol>,
) -> Vec<String> {
    let stmts: Vec<&Expr> = match &*body.node {
        ExprNode::Seq { exprs } => exprs.iter().collect(),
        _ => vec![body],
    };
    let mut out: Vec<String> = Vec::new();
    for (i, stmt) in stmts.iter().enumerate() {
        let is_last = i + 1 == stmts.len();
        out.extend(render_view_stmt(stmt, is_last, reassigned, declared));
    }
    out
}

fn render_view_stmt(
    stmt: &Expr,
    is_last: bool,
    reassigned: &std::collections::HashSet<crate::ident::Symbol>,
    declared: &mut std::collections::HashSet<crate::ident::Symbol>,
) -> Vec<String> {
    // Trailing `io` (or any bare-Var) at the last statement position
    // → `return <var>;`. View bodies end with the accumulated buffer
    // as their value-position last statement; this is the view-shape
    // analog of Ruby's "the last expression is the return value."
    if let ExprNode::Var { name, .. } = &*stmt.node {
        if is_last {
            return vec![format!("return {};", name.as_str())];
        }
    }

    // `if cond ... else ... end` at statement position — block form,
    // recursing into each branch with shared reassigned/declared
    // state so nested `io << x` stmts emit as mutations of the
    // outer-scope `io` (no redeclaration).
    if let ExprNode::If { cond, then_branch, else_branch } = &*stmt.node {
        let cond_s = super::expr::emit_expr(cond);
        let mut out = vec![format!("if ({cond_s}) {{")];
        for line in render_view_body_with_state(then_branch, reassigned, declared) {
            out.push(format!("  {line}"));
        }
        let has_else = !matches!(
            &*else_branch.node,
            ExprNode::Lit { value: Literal::Nil }
        );
        if has_else {
            out.push("} else {".to_string());
            for line in render_view_body_with_state(else_branch, reassigned, declared) {
                out.push(format!("  {line}"));
            }
        }
        out.push("}".to_string());
        return out;
    }

    // `coll.each { |x| io << ... }` at statement position — for-of
    // loop. Inner body shares the outer declared/reassigned state.
    if let ExprNode::Send { recv: Some(recv), method, args, block: Some(block), .. } = &*stmt.node {
        if method.as_str() == "each" && args.is_empty() {
            let coll_s = super::expr::emit_expr(recv);
            if let ExprNode::Lambda { params, body, .. } = &*block.node {
                let var = params
                    .first()
                    .map(|p| p.as_str().to_string())
                    .unwrap_or_else(|| "item".to_string());
                let mut out = vec![format!("for (const {var} of {coll_s}) {{")];
                for line in render_view_body_with_state(body, reassigned, declared) {
                    out.push(format!("  {line}"));
                }
                out.push("}".to_string());
                return out;
            }
        }
    }

    // Anything else (Assign-Var with `let/const`, generalized
    // `buf << X` → `buf += X;`, side-effect helper calls, etc.):
    // delegate to `emit_stmt_with_state`. It handles the full
    // catalog of statement-form patterns (postfix-if, multi-branch
    // if-elsif-else block form, guard-return, let/const declarations,
    // buffer-accumulate `<<` for any local-var receiver, raise as
    // throw, etc.) consistently with everywhere else in the TS
    // emitter — and shares the reassigned/declared state across
    // statements within the same body.
    super::expr::emit_stmt_with_state(stmt, is_last, true, reassigned, declared)
        .lines()
        .map(|l| l.to_string())
        .collect()
}

#[allow(dead_code)]
fn ty_arg_default(_ty: &Ty) -> &'static str {
    "null"
}
