//! Thin TypeScript view emitter — convergence target for the
//! per-target redundancy reduction.
//!
//! Approach: consume the same lowered ERB IR that `view.rs` does,
//! but render it via the standard expr emitter (`expr.rs`) plus a
//! tiny view-shape transformer instead of re-deriving every helper
//! family. The lowerer already produced explicit `link_to`,
//! `content_for`, `each`, `form_with`, etc. Sends — this emitter
//! prefixes them with `ViewHelpers` / `RouteHelpers` and lets the
//! generic Send dispatch carry the rest.
//!
//! Activated by setting `ROUNDHOUSE_TS_VIEW_THIN=1`. Behind a flag
//! so the current emitter can stay live while the thin path is
//! shaken out fixture-by-fixture against the DOM-compare gate. Once
//! the thin emitter passes the gate on every fixture, the current
//! `view.rs` body — ~1280 LOC of name-translation derivation — can
//! be deleted.

use std::collections::HashSet;
use std::fmt::Write;
use std::path::PathBuf;

use crate::App;
use crate::expr::{Expr, ExprNode, InterpPart, LValue, Literal, RescueClause};
use crate::ident::Symbol;
use crate::span::Span;

use super::super::EmittedFile;
use super::controller::rewrite_for_controller;

/// View-helper method names recognized by `classify_view_helper`
/// plus the slot/yield namespace + a few more in the runtime
/// shim. Send-no-recv calls with one of these names get rewritten
/// to `ViewHelpers.<name>(...)`.
const VIEW_HELPERS: &[&str] = &[
    "csrf_meta_tags",
    "csp_meta_tag",
    "javascript_importmap_tags",
    "turbo_stream_from",
    "dom_id",
    "pluralize",
    "truncate",
    "stylesheet_link_tag",
    "content_for",
    "content_for_set",
    "content_for_get",
    "get_slot",
    "get_yield",
    "set_yield",
    "link_to",
    "button_to",
    "html_escape",
    "form_with",
    "field_has_error",
    "error_messages_for",
    "render_attrs",
    "stringify_keys",
    "reset_render_state",
    "reset_slots!",
];

/// Whether a Ruby method name looks like a route helper —
/// snake_case identifier ending in `_path`. The lowerer leaves
/// these as bare Sends; the rewrite below prefixes them with
/// `RouteHelpers`.
fn is_route_helper(name: &str) -> bool {
    name.ends_with("_path")
}

pub(super) fn emit_views_thin(app: &App) -> Vec<EmittedFile> {
    let known_models: Vec<Symbol> = app.models.iter().map(|m| m.name.0.clone()).collect();

    let mut files: Vec<EmittedFile> = app
        .views
        .iter()
        .map(|v| emit_view_file_thin(v, &known_models))
        .collect();

    // Reuse the existing barrel + stubs from view.rs by keeping the
    // same file paths. The thin path produces drop-in replacements.
    if let Some(stubs) = super::view::__emit_ts_missing_view_stubs_for_thin(app, &known_models) {
        files.push(stubs);
    }
    files.push(super::view::__emit_ts_views_barrel_for_thin(app));
    files
}

fn emit_view_file_thin(
    view: &crate::dialect::View,
    known_models: &[Symbol],
) -> EmittedFile {
    let helper_set: HashSet<&str> = VIEW_HELPERS.iter().copied().collect();

    let body = rewrite_for_controller(&view.body);
    let body = crate::lower::erb_trim::trim_view(&body);
    let body = rewrite_helper_calls(&body, &helper_set);

    let fn_name = super::view::__view_function_name_for_thin(view.name.as_str());
    let _ = known_models; // already passed via signature builder below

    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse (thin TS view emitter).").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "import {{ ViewHelpers }} from \"../../../src/view_helpers.js\";").unwrap();
    writeln!(s, "import {{ RouteHelpers }} from \"../../../src/route_helpers.js\";").unwrap();
    writeln!(s, "import * as Views from \"../all.js\";").unwrap();
    writeln!(s, "import * as Importmap from \"../../../src/importmap.js\";").unwrap();
    for m in known_models {
        writeln!(
            s,
            "import {{ {} }} from \"../../models/{}.js\";",
            m.as_str(),
            crate::naming::snake_case(m.as_str()),
        )
        .unwrap();
    }
    writeln!(s).unwrap();

    let (sig, _arg_name, _arg_model) =
        super::view::__ts_view_signature_for_thin(view.name.as_str(), known_models);

    writeln!(s, "export function {fn_name}({sig}): string {{").unwrap();
    writeln!(s, "  let _buf = \"\";").unwrap();

    for line in emit_thin_body(&body) {
        writeln!(s, "  {line}").unwrap();
    }

    writeln!(s, "  return _buf;").unwrap();
    writeln!(s, "}}").unwrap();

    let path = PathBuf::from(format!("app/views/{}.{}.ts", view.name, view.format));
    EmittedFile { path, content: s }
}

/// Walk a view body, emitting one or more TS lines per statement.
/// The body is a `Seq` of `_buf = ""`, `_buf = _buf + X`, and bare
/// `_buf` (the trailing return-value stmt). Anything else (If,
/// each, etc.) gets routed through the standard expr emitter via
/// `super::expr::emit_body`.
fn emit_thin_body(body: &Expr) -> Vec<String> {
    let stmts: Vec<&Expr> = match &*body.node {
        ExprNode::Seq { exprs } => exprs.iter().collect(),
        _ => vec![body],
    };
    let mut out = Vec::new();
    for stmt in &stmts {
        out.extend(emit_thin_stmt(stmt));
    }
    out
}

fn emit_thin_stmt(stmt: &Expr) -> Vec<String> {
    match &*stmt.node {
        // `_buf = ""` prologue — already emitted in the file header.
        ExprNode::Assign { target: LValue::Var { name, .. }, value }
            if name.as_str() == "_buf" =>
        {
            if let ExprNode::Lit { value: Literal::Str { value: s } } = &*value.node {
                if s.is_empty() {
                    return Vec::new();
                }
            }
            // `_buf = _buf + X` — buf-append. Render X via the
            // standard expr emitter.
            if let ExprNode::Send { recv: Some(recv), method, args, .. } = &*value.node {
                if method.as_str() == "+" && args.len() == 1 {
                    if let ExprNode::Var { name: rn, .. } = &*recv.node {
                        if rn.as_str() == "_buf" {
                            return emit_thin_append(&args[0]);
                        }
                    }
                }
            }
            // Some other assignment to _buf — emit verbatim via the
            // standard expr emitter.
            vec![format!("_buf = {};", super::expr::emit_expr(value))]
        }
        // Trailing `_buf` — the return value stmt; we emit `return
        // _buf;` after the body, so drop here.
        ExprNode::Var { name, .. } if name.as_str() == "_buf" => Vec::new(),
        // `if cond ... else ... end` at statement position. Recurse
        // on each branch — branches contain `_buf = _buf + X` stmts
        // that re-enter `emit_thin_stmt`. Wrap with block-form
        // `if (...) { ... } else { ... }`.
        ExprNode::If { cond, then_branch, else_branch } => {
            let cond_s = super::expr::emit_expr(cond);
            let mut out = vec![format!("if ({cond_s}) {{")];
            for line in emit_thin_body(then_branch) {
                out.push(format!("  {line}"));
            }
            let has_else = !matches!(
                &*else_branch.node,
                ExprNode::Lit { value: Literal::Nil }
            );
            if has_else {
                out.push("} else {".to_string());
                for line in emit_thin_body(else_branch) {
                    out.push(format!("  {line}"));
                }
            }
            out.push("}".to_string());
            out
        }
        // `coll.each { |x| ... }` — produce a for-of with body
        // expanded via the standard stmt emitter. Inside the body
        // are `_buf = _buf + X` stmts that recurse here.
        ExprNode::Send { recv: Some(recv), method, args, block: Some(block), .. }
            if method.as_str() == "each" && args.is_empty() =>
        {
            let coll_s = super::expr::emit_expr(recv);
            let ExprNode::Lambda { params, body, .. } = &*block.node else {
                return vec!["/* TODO: each block shape */".to_string()];
            };
            let var = params.first().map(|p| p.as_str().to_string()).unwrap_or_else(|| "item".into());
            let mut out = vec![format!("for (const {var} of {coll_s}) {{")];
            for line in emit_thin_body(body) {
                out.push(format!("  {line}"));
            }
            out.push("}".to_string());
            out
        }
        // Side-effect helper call at statement position
        // (e.g. `content_for_set(:title, "x")`). The expr is itself
        // a Send with no buffer-append.
        ExprNode::Send { .. } => {
            vec![format!("{};", super::expr::emit_expr(stmt))]
        }
        _ => vec![format!(
            "/* TODO thin: unknown stmt {:?} */",
            std::mem::discriminant(&*stmt.node)
        )],
    }
}

/// Render a `_buf += X` line. Splits text-only literals from
/// expression appends so the output reads naturally.
fn emit_thin_append(arg: &Expr) -> Vec<String> {
    if let ExprNode::Lit { value: Literal::Str { value: s } } = &*arg.node {
        return vec![format!(
            "_buf += {};",
            serde_json::to_string(s).unwrap_or_else(|_| format!("{s:?}"))
        )];
    }
    let inner = unwrap_to_s(arg);
    // Already-string-typed expressions don't need the wrapping
    // `String(...)` cast — strip it when the inner expr is a string
    // literal, interpolation, or known-string-returning helper call
    // (link_to, button_to, etc.). Otherwise wrap defensively.
    let s = super::expr::emit_expr(inner);
    if is_string_typed(inner) {
        vec![format!("_buf += {s};")]
    } else {
        vec![format!("_buf += String({s});")]
    }
}

/// `x.to_s` → `x` (the `to_s` is redundant for the string-concat
/// path; the `String(...)` wrap below covers conversion). Mirrors
/// the existing view.rs helper.
fn unwrap_to_s(expr: &Expr) -> &Expr {
    if let ExprNode::Send { recv: Some(inner), method, args, .. } = &*expr.node {
        if method.as_str() == "to_s" && args.is_empty() {
            return inner;
        }
    }
    expr
}

/// Heuristic: when does the emitted expression already produce a
/// string, so we can skip the defensive `String(...)` wrap? Covers
/// the cases the view emit hits: string literals, interpolations,
/// and ViewHelpers/RouteHelpers Sends (every helper returns String).
fn is_string_typed(e: &Expr) -> bool {
    match &*e.node {
        ExprNode::Lit { value: Literal::Str { .. } } => true,
        ExprNode::StringInterp { .. } => true,
        ExprNode::Send { recv: Some(r), .. } => {
            matches!(
                &*r.node,
                ExprNode::Const { path }
                    if path.first().map(|s| s.as_str()).is_some_and(
                        |s| s == "ViewHelpers" || s == "RouteHelpers"
                    )
            )
        }
        _ => false,
    }
}

/// Walk an `Expr` tree, rewriting `Send { recv: None, method: m }`
/// to `Send { recv: ViewHelpers, method: m }` when `m` is a known
/// view helper, or to `Send { recv: RouteHelpers, method: m }` when
/// `m` ends in `_path`. Other Sends pass through with children
/// rewritten. Idempotent.
fn rewrite_helper_calls(e: &Expr, helpers: &HashSet<&str>) -> Expr {
    let new_node = match &*e.node {
        ExprNode::Send { recv: None, method, args, block, parenthesized }
            if helpers.contains(method.as_str()) =>
        {
            ExprNode::Send {
                recv: Some(const_recv("ViewHelpers")),
                method: method.clone(),
                args: args.iter().map(|a| rewrite_helper_calls(a, helpers)).collect(),
                block: block.as_ref().map(|b| rewrite_helper_calls(b, helpers)),
                parenthesized: *parenthesized,
            }
        }
        ExprNode::Send { recv: None, method, args, block, parenthesized }
            if is_route_helper(method.as_str()) =>
        {
            ExprNode::Send {
                recv: Some(const_recv("RouteHelpers")),
                method: method.clone(),
                args: args.iter().map(|a| rewrite_helper_calls(a, helpers)).collect(),
                block: block.as_ref().map(|b| rewrite_helper_calls(b, helpers)),
                parenthesized: *parenthesized,
            }
        }
        ExprNode::Send { recv, method, args, block, parenthesized } => ExprNode::Send {
            recv: recv.as_ref().map(|r| rewrite_helper_calls(r, helpers)),
            method: method.clone(),
            args: args.iter().map(|a| rewrite_helper_calls(a, helpers)).collect(),
            block: block.as_ref().map(|b| rewrite_helper_calls(b, helpers)),
            parenthesized: *parenthesized,
        },
        ExprNode::Apply { fun, args, block } => ExprNode::Apply {
            fun: rewrite_helper_calls(fun, helpers),
            args: args.iter().map(|a| rewrite_helper_calls(a, helpers)).collect(),
            block: block.as_ref().map(|b| rewrite_helper_calls(b, helpers)),
        },
        ExprNode::Seq { exprs } => ExprNode::Seq {
            exprs: exprs.iter().map(|e| rewrite_helper_calls(e, helpers)).collect(),
        },
        ExprNode::If { cond, then_branch, else_branch } => ExprNode::If {
            cond: rewrite_helper_calls(cond, helpers),
            then_branch: rewrite_helper_calls(then_branch, helpers),
            else_branch: rewrite_helper_calls(else_branch, helpers),
        },
        ExprNode::BoolOp { op, surface, left, right } => ExprNode::BoolOp {
            op: *op,
            surface: *surface,
            left: rewrite_helper_calls(left, helpers),
            right: rewrite_helper_calls(right, helpers),
        },
        ExprNode::Array { elements, style } => ExprNode::Array {
            elements: elements.iter().map(|e| rewrite_helper_calls(e, helpers)).collect(),
            style: *style,
        },
        ExprNode::Hash { entries, braced } => ExprNode::Hash {
            entries: entries
                .iter()
                .map(|(k, v)| (rewrite_helper_calls(k, helpers), rewrite_helper_calls(v, helpers)))
                .collect(),
            braced: *braced,
        },
        ExprNode::StringInterp { parts } => ExprNode::StringInterp {
            parts: parts
                .iter()
                .map(|p| match p {
                    InterpPart::Text { value } => InterpPart::Text { value: value.clone() },
                    InterpPart::Expr { expr } => InterpPart::Expr {
                        expr: rewrite_helper_calls(expr, helpers),
                    },
                })
                .collect(),
        },
        ExprNode::Lambda { params, block_param, body, block_style } => ExprNode::Lambda {
            params: params.clone(),
            block_param: block_param.clone(),
            body: rewrite_helper_calls(body, helpers),
            block_style: *block_style,
        },
        ExprNode::Assign { target, value } => {
            let new_target = match target {
                LValue::Var { id, name } => LValue::Var { id: *id, name: name.clone() },
                LValue::Ivar { name } => LValue::Ivar { name: name.clone() },
                LValue::Attr { recv, name } => LValue::Attr {
                    recv: rewrite_helper_calls(recv, helpers),
                    name: name.clone(),
                },
                LValue::Index { recv, index } => LValue::Index {
                    recv: rewrite_helper_calls(recv, helpers),
                    index: rewrite_helper_calls(index, helpers),
                },
            };
            ExprNode::Assign {
                target: new_target,
                value: rewrite_helper_calls(value, helpers),
            }
        }
        ExprNode::Yield { args } => ExprNode::Yield {
            args: args.iter().map(|a| rewrite_helper_calls(a, helpers)).collect(),
        },
        ExprNode::Raise { value } => ExprNode::Raise {
            value: rewrite_helper_calls(value, helpers),
        },
        ExprNode::RescueModifier { expr, fallback } => ExprNode::RescueModifier {
            expr: rewrite_helper_calls(expr, helpers),
            fallback: rewrite_helper_calls(fallback, helpers),
        },
        ExprNode::Return { value } => ExprNode::Return {
            value: rewrite_helper_calls(value, helpers),
        },
        ExprNode::BeginRescue { body, rescues, else_branch, ensure, implicit } => {
            ExprNode::BeginRescue {
                body: rewrite_helper_calls(body, helpers),
                rescues: rescues
                    .iter()
                    .map(|rc| RescueClause {
                        classes: rc.classes.iter().map(|c| rewrite_helper_calls(c, helpers)).collect(),
                        binding: rc.binding.clone(),
                        body: rewrite_helper_calls(&rc.body, helpers),
                    })
                    .collect(),
                else_branch: else_branch.as_ref().map(|b| rewrite_helper_calls(b, helpers)),
                ensure: ensure.as_ref().map(|b| rewrite_helper_calls(b, helpers)),
                implicit: *implicit,
            }
        }
        ExprNode::Case { scrutinee, arms } => ExprNode::Case {
            scrutinee: rewrite_helper_calls(scrutinee, helpers),
            arms: arms
                .iter()
                .map(|arm| crate::expr::Arm {
                    pattern: arm.pattern.clone(),
                    guard: arm.guard.as_ref().map(|g| rewrite_helper_calls(g, helpers)),
                    body: rewrite_helper_calls(&arm.body, helpers),
                })
                .collect(),
        },
        ExprNode::Let { id, name, value, body } => ExprNode::Let {
            id: *id,
            name: name.clone(),
            value: rewrite_helper_calls(value, helpers),
            body: rewrite_helper_calls(body, helpers),
        },
        ExprNode::Next { value } => ExprNode::Next {
            value: value.as_ref().map(|v| rewrite_helper_calls(v, helpers)),
        },
        ExprNode::MultiAssign { targets, value } => ExprNode::MultiAssign {
            targets: targets.clone(),
            value: rewrite_helper_calls(value, helpers),
        },
        ExprNode::While { cond, body, until_form } => ExprNode::While {
            cond: rewrite_helper_calls(cond, helpers),
            body: rewrite_helper_calls(body, helpers),
            until_form: *until_form,
        },
        ExprNode::Range { begin, end, exclusive } => ExprNode::Range {
            begin: begin.as_ref().map(|b| rewrite_helper_calls(b, helpers)),
            end: end.as_ref().map(|e| rewrite_helper_calls(e, helpers)),
            exclusive: *exclusive,
        },
        ExprNode::Super { args } => ExprNode::Super {
            args: args
                .as_ref()
                .map(|v| v.iter().map(|a| rewrite_helper_calls(a, helpers)).collect()),
        },
        other => other.clone(),
    };

    Expr {
        span: e.span,
        node: Box::new(new_node),
        ty: e.ty.clone(),
        effects: e.effects.clone(),
        leading_blank_line: e.leading_blank_line,
        diagnostic: e.diagnostic.clone(),
    }
}

fn const_recv(name: &str) -> Expr {
    Expr::new(
        Span::synthetic(),
        ExprNode::Const { path: vec![Symbol::from(name)] },
    )
}
