//! Thin TypeScript view emitter — convergence target for the
//! per-target redundancy reduction.
//!
//! Approach: lower each view through `lower::view_to_library`
//! (the same lowerer Spinel/Ruby uses) to get a canonical
//! `LibraryClass` whose method bodies are already in the
//! `io << ViewHelpers.x(...)` shape with path-arg `.id` extraction,
//! form_with restructuring, render-partial dispatch, and
//! conditional-class composition all done. This emitter just
//! renders that LibraryClass to TS via the standard expr emitter
//! plus a small statement-form wrapper for the buf-accumulate idiom.
//!
//! Activated by setting `ROUNDHOUSE_TS_VIEW_THIN=1`. Behind a flag
//! while the path is shaken out fixture-by-fixture against the
//! DOM-compare gate.

use std::fmt::Write;
use std::path::PathBuf;

use crate::App;
use crate::dialect::{LibraryClass, MethodDef, MethodReceiver};
use crate::expr::{Expr, ExprNode, LValue, Literal};
use crate::ident::Symbol;
use crate::ty::Ty;

use super::super::EmittedFile;

pub(super) fn emit_views_thin(app: &App) -> Vec<EmittedFile> {
    let known_models: Vec<Symbol> = app.models.iter().map(|m| m.name.0.clone()).collect();

    let mut files: Vec<EmittedFile> = app
        .views
        .iter()
        .map(|v| {
            let lc = crate::lower::lower_view_to_library_class(v, app);
            emit_view_class_thin(v, &lc, &known_models)
        })
        .collect();

    if let Some(stubs) = super::view::__emit_ts_missing_view_stubs_for_thin(app, &known_models) {
        files.push(stubs);
    }
    files.push(super::view::__emit_ts_views_barrel_for_thin(app));
    files
}

fn emit_view_class_thin(
    view: &crate::dialect::View,
    lc: &LibraryClass,
    known_models: &[Symbol],
) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse (thin TS view emitter).").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "import {{ ViewHelpers }} from \"../../../src/view_helpers.js\";").unwrap();
    writeln!(s, "import {{ RouteHelpers }} from \"../../../src/route_helpers.js\";").unwrap();
    writeln!(s, "import * as Views from \"../all.js\";").unwrap();
    writeln!(s, "import * as Importmap from \"../../../src/importmap.js\";").unwrap();
    for m in known_models {
        writeln!(
            s,
            "import {{ {} }} from \"../../models/{}.js\";",
            m.as_str(),
            crate::naming::snake_case(m.as_str()),
        )
        .unwrap();
    }
    writeln!(s).unwrap();

    // The LibraryClass holds one method (the view's render fn). Emit
    // it as an exported TS function under the original render-name
    // (`renderArticlesShow`) so existing callers (controllers) keep
    // resolving without change. The class-wrapper shape (Spinel uses
    // `module Views::Articles; def self.show`) lowers to the same
    // function-equivalent in TS — we emit a flat function rather
    // than a class because the call site is `Views.renderArticlesX`.
    let fn_name = super::view::__view_function_name_for_thin(view.name.as_str());

    let method = lc.methods.iter().find(|m| matches!(m.receiver, MethodReceiver::Class));
    let Some(method) = method else {
        // Empty view — should be rare; emit a stub that returns "".
        writeln!(s, "export function {fn_name}(): string {{").unwrap();
        writeln!(s, "  return \"\";").unwrap();
        writeln!(s, "}}").unwrap();
        return EmittedFile {
            path: PathBuf::from(format!("app/views/{}.{}.ts", view.name, view.format)),
            content: s,
        };
    };

    let params_sig = render_params(method, known_models);
    writeln!(s, "export function {fn_name}({params_sig}): string {{").unwrap();
    for line in render_view_body(&method.body) {
        writeln!(s, "  {line}").unwrap();
    }
    writeln!(s, "}}").unwrap();

    EmittedFile {
        path: PathBuf::from(format!("app/views/{}.{}.ts", view.name, view.format)),
        content: s,
    }
}

/// Render the LibraryClass method's positional params as a TS arg
/// list. Model-typed args (matching a known model name from the app)
/// get the strict type; everything else falls back to `any`. The
/// lowerer surfaces `notice` / `alert` etc. as additional positional
/// params with `nil` defaults; mirror those defaults.
fn render_params(m: &MethodDef, known_models: &[Symbol]) -> String {
    m.params
        .iter()
        .map(|p| {
            let name = p.name.as_str();
            // Heuristic: if the param name matches the singular form
            // of any model in the app, type it as that model.
            let model_match = known_models.iter().find(|km| {
                let singular = crate::naming::snake_case(km.as_str());
                singular == name || crate::naming::pluralize_snake(&singular) == name
            });
            match model_match {
                Some(km) if crate::naming::snake_case(km.as_str()) == name => {
                    format!("{name}: {}", km.as_str())
                }
                Some(km) => {
                    // Plural — typed as Array of model.
                    format!("{name}: {}[]", km.as_str())
                }
                None => format!("{name}: any = null"),
            }
        })
        .collect::<Vec<_>>()
        .join(", ")
}

/// Render a view-method body into TS lines. The body shape produced
/// by `view_to_library` is:
///
///   io = String.new
///   io << ViewHelpers.x(...)
///   ...
///   io
///
/// Map `io = String.new` → `let io = "";`, `io << expr` → `io +=
/// expr;`, trailing `io` → `return io;`. Other statements (If, each,
/// content_for_set side effects) route through the standard expr
/// emitter via `super::expr::emit_expr`.
fn render_view_body(body: &Expr) -> Vec<String> {
    let stmts: Vec<&Expr> = match &*body.node {
        ExprNode::Seq { exprs } => exprs.iter().collect(),
        _ => vec![body],
    };
    let mut out: Vec<String> = Vec::new();
    let mut emitted_init = false;
    for (i, stmt) in stmts.iter().enumerate() {
        let is_last = i + 1 == stmts.len();
        out.extend(render_view_stmt(stmt, is_last, &mut emitted_init));
    }
    out
}

fn render_view_stmt(stmt: &Expr, is_last: bool, emitted_init: &mut bool) -> Vec<String> {
    // `io = String.new` → `let io = "";`. The lowerer always uses
    // `io` as the buffer name; matching it here keeps the output
    // readable.
    if let ExprNode::Assign { target: LValue::Var { name, .. }, value } = &*stmt.node {
        if name.as_str() == "io" {
            // Recognize `String.new` (Send on String const) as the
            // initializer; treat any other init as the same empty
            // string for simplicity — bodies always start fresh.
            *emitted_init = true;
            return vec![format!("let io = \"\";")];
        }
    }

    // Trailing `io` (the method's return value) → `return io;`. Only
    // happens at the last statement.
    if let ExprNode::Var { name, .. } = &*stmt.node {
        if name.as_str() == "io" && is_last {
            return vec![format!("return io;")];
        }
    }

    // `io << X` → `io += <emit X>;`. The lowerer emits these as the
    // primary append form.
    if let ExprNode::Send { recv: Some(recv), method, args, .. } = &*stmt.node {
        if method.as_str() == "<<" && args.len() == 1 {
            if let ExprNode::Var { name, .. } = &*recv.node {
                if name.as_str() == "io" {
                    let val = super::expr::emit_expr(&args[0]);
                    return vec![format!("io += {val};")];
                }
            }
        }
    }

    // `if cond ... else ... end` at statement position — block form,
    // recursing into each branch via render_view_body so nested
    // `io << x` stmts get the same treatment.
    if let ExprNode::If { cond, then_branch, else_branch } = &*stmt.node {
        let cond_s = super::expr::emit_expr(cond);
        let mut out = vec![format!("if ({cond_s}) {{")];
        for line in render_view_body(then_branch) {
            out.push(format!("  {line}"));
        }
        let has_else = !matches!(
            &*else_branch.node,
            ExprNode::Lit { value: Literal::Nil }
        );
        if has_else {
            out.push("} else {".to_string());
            for line in render_view_body(else_branch) {
                out.push(format!("  {line}"));
            }
        }
        out.push("}".to_string());
        let _ = emitted_init;
        return out;
    }

    // `coll.each { |x| io << ... }` at statement position — for-of
    // loop. Other Send-with-block shapes (like form_with) appear
    // inside `io << ...`, not as standalone statements, so they
    // route through the value-position path.
    if let ExprNode::Send { recv: Some(recv), method, args, block: Some(block), .. } = &*stmt.node {
        if method.as_str() == "each" && args.is_empty() {
            let coll_s = super::expr::emit_expr(recv);
            if let ExprNode::Lambda { params, body, .. } = &*block.node {
                let var = params
                    .first()
                    .map(|p| p.as_str().to_string())
                    .unwrap_or_else(|| "item".to_string());
                let mut out = vec![format!("for (const {var} of {coll_s}) {{")];
                for line in render_view_body(body) {
                    out.push(format!("  {line}"));
                }
                out.push("}".to_string());
                return out;
            }
        }
    }

    // Anything else: side-effect statement (e.g. `ViewHelpers.content_for_set(:title, "x")`).
    // Route through the standard expr emitter and append a `;`.
    let val = super::expr::emit_expr(stmt);
    let val = if is_last && !val.starts_with("return ") {
        // Last statement that isn't already a return: when the body's
        // final expression is value-producing, treat it as the return
        // value. Common case is `io` (handled above) but defensive
        // here too.
        let _ = val;
        format!("return {};", super::expr::emit_expr(stmt))
    } else {
        format!("{val};")
    };
    vec![val]
}

#[allow(dead_code)]
fn ty_arg_default(_ty: &Ty) -> &'static str {
    "null"
}
