//! Views — translate compiled-ERB IR into TypeScript view functions.

use std::fmt::Write;
use std::path::PathBuf;

use crate::App;
use crate::expr::{Expr, ExprNode, LValue, Literal};
use crate::ident::Symbol;

use super::super::EmittedFile;
use super::controller::{lower_first_char, rewrite_for_controller};
use super::expr::emit_literal;

/// Emit each view as a TypeScript function that takes a `locals`
/// object and returns the rendered HTML string. Walks the compiled-
/// ERB body (a `Seq` of `_buf = _buf + …` assignments) and translates
/// each statement into its JS equivalent:
///
/// ```text
/// _buf = ""                  → dropped (prologue)
/// _buf = _buf + "text"       → _buf += "text";
/// _buf = _buf + (expr).to_s  → _buf += String(expr);
/// _buf                       → return _buf;
/// ```
///
/// Control-flow statements (e.g. `<% if cond %>`) ingested into the
/// body as `If` / Send-with-block nodes pass through the normal
/// `emit_expr` path.
pub(super) fn emit_views(app: &App) -> Vec<EmittedFile> {
    let known_models: Vec<Symbol> = app.models.iter().map(|m| m.name.0.clone()).collect();
    let attrs_by_class: std::collections::BTreeMap<String, Vec<String>> = app
        .models
        .iter()
        .map(|m| {
            (
                m.name.0.as_str().to_string(),
                m.attributes
                    .fields
                    .keys()
                    .map(|k| k.as_str().to_string())
                    .collect(),
            )
        })
        .collect();

    let mut files: Vec<EmittedFile> = app
        .views
        .iter()
        .map(|v| emit_view_file_pass2(v, &known_models, &attrs_by_class, &app.stylesheets))
        .collect();

    // Stubs for missing standard CRUD views (same posture as Rust).
    if let Some(stubs) = emit_ts_missing_view_stubs(app, &known_models) {
        files.push(stubs);
    }

    // Barrel — one file re-exporting every view fn, so controllers
    // can `import * as Views from "../views/all.js"`.
    files.push(emit_ts_views_barrel(app));

    files
}

fn emit_ts_views_barrel(app: &App) -> EmittedFile {
    use std::collections::BTreeMap;
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    // Re-export every per-action render fn at the top level (the
    // existing TS view emitter calls `Views.renderArticlesShow` —
    // backward-compat). Plus pull each render fn into local scope
    // so the namespace objects below can reference them.
    for v in &app.views {
        let name = v.name.as_str();
        let path = format!("./{}.{}.js", name, v.format);
        let (dir, base) = name.rsplit_once('/').unwrap_or(("", name));
        let action = base.trim_start_matches('_');
        let render_fn = format!(
            "render{}{}",
            crate::naming::camelize(dir),
            crate::naming::camelize(action),
        );
        writeln!(s, "export {{ {render_fn} }} from {path:?};").unwrap();
        writeln!(s, "import {{ {render_fn} as _{render_fn} }} from {path:?};").unwrap();
    }
    // Stubs file: re-export *and* import-with-prefix so the namespace
    // objects below find missing actions through the stubs.
    writeln!(s, "export * from \"./_stubs.js\";").unwrap();
    writeln!(s, "import * as _stubs from \"./_stubs.js\";").unwrap();

    // Namespace shape: `Views.Articles.show(...)`, `Views.Comments.comment(...)`,
    // `Views.Layouts.application(...)`. Mirrors Spinel's `Views::Articles.show`
    // emit and matches what `lower_view_to_library` produces in lowered
    // bodies. The thin TS view emitter calls these; the existing flat
    // `renderArticlesShow` re-exports above remain for the current TS
    // view emitter.
    //
    // Build one TS object literal per view-directory grouping. The
    // action-name comes from the partial-stripped basename
    // (`_article` → `article`); the function the object points to is
    // the existing `render<Dir><Action>` PascalCase fn imported from
    // its per-action file. Stub-only namespaces (e.g. all-stub
    // articles when no fixtures exist) still get a populated object
    // because the stubs file declares the same render-fn names.
    let mut by_dir: BTreeMap<String, Vec<(String, String)>> = BTreeMap::new();
    for v in &app.views {
        let name = v.name.as_str();
        let (dir, base) = name.rsplit_once('/').unwrap_or(("", name));
        if dir.is_empty() {
            continue;
        }
        let action = base.trim_start_matches('_').to_string();
        let render_fn = format!(
            "render{}{}",
            crate::naming::camelize(dir),
            crate::naming::camelize(&action),
        );
        by_dir
            .entry(dir.to_string())
            .or_default()
            .push((action, render_fn));
    }
    if !by_dir.is_empty() {
        writeln!(s).unwrap();
    }
    for (dir, actions) in &by_dir {
        let ns = crate::naming::camelize(dir);
        writeln!(s, "export const {ns} = {{").unwrap();
        for (action, render_fn) in actions {
            writeln!(s, "  {action}: _{render_fn},").unwrap();
        }
        writeln!(s, "}};").unwrap();
    }

    EmittedFile {
        path: PathBuf::from("app/views/all.ts"),
        content: s,
    }
}

/// Stub view fns for standard CRUD names the fixture doesn't
/// supply — controllers reference `Views.renderArticlesShow` etc.
/// whether or not an ERB template exists. Returns None when the
/// fixture supplies every standard view (no stub file needed).
fn emit_ts_missing_view_stubs(app: &App, known_models: &[Symbol]) -> Option<EmittedFile> {
    use std::collections::BTreeSet;
    let present: BTreeSet<String> =
        app.views.iter().map(|v| v.name.as_str().to_string()).collect();
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    let mut any = false;
    for model in &app.models {
        if model.attributes.fields.is_empty() {
            continue;
        }
        let class = model.name.0.as_str();
        let plural = crate::naming::pluralize_snake(class);
        let plural_camel = crate::naming::camelize(&plural);
        for (action, suffix) in [
            ("Index", "index"),
            ("Show", "show"),
            ("New", "new"),
            ("Edit", "edit"),
        ] {
            let view_name = format!("{plural}/{suffix}");
            if present.contains(&view_name) {
                continue;
            }
            any = true;
            let fn_name = format!("render{plural_camel}{action}");
            writeln!(
                s,
                "export function {fn_name}(_record: unknown): string {{ return \"\"; }}",
            )
            .unwrap();
        }
    }
    let _ = known_models;
    if any {
        Some(EmittedFile {
            path: PathBuf::from("app/views/_stubs.ts"),
            content: s,
        })
    } else {
        // Empty stub file so barrel's re-export doesn't break.
        Some(EmittedFile {
            path: PathBuf::from("app/views/_stubs.ts"),
            content: "// Generated by Roundhouse.\nexport {};\n".to_string(),
        })
    }
}

fn emit_view_file_pass2(
    view: &crate::dialect::View,
    known_models: &[Symbol],
    attrs_by_class: &std::collections::BTreeMap<String, Vec<String>>,
    stylesheets: &[String],
) -> EmittedFile {
    let rewritten_body = rewrite_for_controller(&view.body);
    // Apply the shared erubi-trim lowering. Produces a body
    // where every `<% %>` tag's leading indent and trailing
    // newline are already consumed (matching Rails' erubi render
    // behavior), plus the view's trailing whitespace-only text
    // append is dropped. After this, emit can walk the IR
    // straight through without re-applying trim rules per-
    // statement.
    let rewritten_body = crate::lower::erb_trim::trim_view(&rewritten_body);
    let ivar_names = collect_ivar_names(&view.body);
    let fn_name = view_function_name(view.name.as_str());

    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s).unwrap();
    writeln!(
        s,
        "import * as Helpers from \"../../../src/view_helpers.js\";",
    )
    .unwrap();
    writeln!(s, "import * as routeHelpers from \"../../../src/route_helpers.js\";").unwrap();
    writeln!(s, "import * as Views from \"../all.js\";").unwrap();
    writeln!(s, "import * as Importmap from \"../../../src/importmap.js\";").unwrap();
    if !known_models.is_empty() {
        for m in known_models {
            writeln!(
                s,
                "import {{ {} }} from \"../../models/{}.js\";",
                m.as_str(),
                crate::naming::snake_case(m.as_str()),
            )
            .unwrap();
        }
    }
    writeln!(s).unwrap();

    // Signature: single positional arg matching the resource's
    // singular/plural name. Controllers call with the right record.
    let (sig, arg_name, arg_model) =
        ts_view_signature(view.name.as_str(), known_models);
    let attrs = arg_model
        .as_ref()
        .and_then(|c| attrs_by_class.get(c).cloned())
        .unwrap_or_default();

    writeln!(s, "export function {fn_name}({sig}): string {{").unwrap();
    writeln!(s, "  let _buf = \"\";").unwrap();
    let mut locals: Vec<String> = vec!["_buf".to_string(), arg_name.clone()];
    for n in &ivar_names {
        // Ivars listed (originals) — rewrite_for_controller already
        // mapped them to locals matching the arg name when the ivar
        // is the main record.
        if !locals.iter().any(|x| x == n) {
            locals.push(n.clone());
        }
    }
    let resource_dir = view
        .name
        .as_str()
        .rsplit_once('/')
        .map(|(d, _): (&str, &str)| d.to_string())
        .unwrap_or_default();
    let ctx = TsViewCtx {
        locals,
        arg_name: arg_name.clone(),
        arg_attrs: attrs,
        resource_dir,
        stylesheets: stylesheets.to_vec(),
    };

    let body_lines = emit_ts_view_body(&rewritten_body, &ctx);
    for line in body_lines {
        writeln!(s, "  {line}").unwrap();
    }
    writeln!(s, "  return _buf;").unwrap();
    writeln!(s, "}}").unwrap();

    let path = PathBuf::from(format!("app/views/{}.{}.ts", view.name, view.format));
    EmittedFile { path, content: s }
}

struct TsViewCtx {
    locals: Vec<String>,
    arg_name: String,
    arg_attrs: Vec<String>,
    resource_dir: String,
    /// Discovered stylesheet names (stems). Feeds the
    /// `stylesheet_link_tag :app` expansion in the layout.
    stylesheets: Vec<String>,
}

impl TsViewCtx {
    fn is_local(&self, n: &str) -> bool {
        self.locals.iter().any(|x| x == n)
    }
    fn arg_has_attr(&self, name: &str, attr: &str) -> bool {
        name == self.arg_name && self.arg_attrs.iter().any(|a| a == attr)
    }
}

/// Build the single-arg signature for a view fn + return the arg
/// name and (optional) model class.
fn ts_view_signature(
    view_name: &str,
    known_models: &[Symbol],
) -> (String, String, Option<String>) {
    let (dir, base) = view_name.rsplit_once('/').unwrap_or(("", view_name));
    let is_partial = base.starts_with('_');
    let stem = base.trim_start_matches('_');
    let model_class = crate::naming::singularize_camelize(dir);
    let model_exists = known_models.iter().any(|m| m.as_str() == model_class);
    let singular = crate::naming::singularize(dir);

    if is_partial {
        let arg_name = if model_exists { singular.clone() } else { stem.to_string() };
        if model_exists {
            return (format!("{arg_name}: {model_class}"), arg_name, Some(model_class));
        }
        return (format!("{arg_name}: any"), arg_name, None);
    }
    match stem {
        "index" => {
            let arg_name = dir.to_string();
            if model_exists {
                return (format!("{arg_name}: {model_class}[]"), arg_name, Some(model_class));
            }
            return (format!("{arg_name}: any[]"), arg_name, None);
        }
        _ => {
            let arg_name = singular.clone();
            if model_exists {
                return (format!("{arg_name}: {model_class}"), arg_name, Some(model_class));
            }
            return (format!("{arg_name}: any"), arg_name, None);
        }
    }
}

fn emit_ts_view_body(body: &Expr, ctx: &TsViewCtx) -> Vec<String> {
    // The view body arrives pre-trimmed via
    // `lower::erb_trim::trim_view` (applied once per view at the
    // top of `emit_view_file_pass2`). Nested Seqs/If branches are
    // trimmed in that same pass, so here we just iterate stmts.
    let stmts: Vec<&Expr> = match &*body.node {
        ExprNode::Seq { exprs } => exprs.iter().collect(),
        _ => vec![body],
    };
    let mut out = Vec::new();
    for stmt in &stmts {
        out.extend(emit_ts_view_stmt_pass2(stmt, ctx));
    }
    out
}

fn emit_ts_view_stmt_pass2(stmt: &Expr, ctx: &TsViewCtx) -> Vec<String> {
    match &*stmt.node {
        // Prologue `_buf = ""` — emit_view_body already wrote it.
        ExprNode::Assign { target: LValue::Var { name, .. }, value }
            if name.as_str() == "_buf" =>
        {
            if let ExprNode::Lit { value: Literal::Str { value: s } } = &*value.node {
                if s.is_empty() {
                    return Vec::new();
                }
            }
            // `_buf = _buf + X` — the working shape.
            if let ExprNode::Send { recv: Some(recv), method, args, .. } = &*value.node {
                if method.as_str() == "+" && args.len() == 1 {
                    if let ExprNode::Var { name: rn, .. } = &*recv.node {
                        if rn.as_str() == "_buf" {
                            return vec![emit_ts_view_append_pass2(&args[0], ctx)];
                        }
                    }
                }
            }
            vec![format!("/* TODO ERB: _buf shape */;")]
        }
        // Epilogue: bare `_buf` — dropped; we emit `return _buf;` elsewhere.
        ExprNode::Var { name, .. } if name.as_str() == "_buf" => Vec::new(),
        // `if cond ... else ... end` — degrade cond if complex.
        // Branch-edge trim happens upstream in
        // `lower::erb_trim::trim_view`; the branches arrive with
        // their first/last text stmts already adjusted.
        ExprNode::If { cond, then_branch, else_branch } => {
            let cond_js = if is_ts_simple_expr(cond, ctx) {
                emit_ts_view_expr_raw(cond, ctx)
            } else {
                "false /* TODO ERB cond */".to_string()
            };
            let mut out = vec![format!("if ({cond_js}) {{")];
            for line in emit_ts_view_body(then_branch, ctx) {
                out.push(format!("  {line}"));
            }
            let has_else = !matches!(
                &*else_branch.node,
                ExprNode::Lit { value: Literal::Nil }
            );
            if has_else {
                out.push("} else {".to_string());
                for line in emit_ts_view_body(else_branch, ctx) {
                    out.push(format!("  {line}"));
                }
            }
            out.push("}".to_string());
            out
        }
        // `<% content_for :slot, "value" %>` — statement-form
        // setter. Classifier recognizes the shape; render the
        // side-effect call without a `_buf +=` (nothing goes
        // into the view output — the slot is read later by the
        // layout's `<%= yield :slot %>`).
        ExprNode::Send { recv: None, method, args, block: None, .. }
            if matches!(
                crate::lower::classify_view_helper(method.as_str(), args),
                Some(crate::lower::ViewHelperKind::ContentForSetter { .. })
            ) =>
        {
            if let Some(crate::lower::ViewHelperKind::ContentForSetter { slot, body }) =
                crate::lower::classify_view_helper(method.as_str(), args)
            {
                if is_ts_simple_expr(body, ctx) {
                    let body_s = emit_ts_view_expr_raw(body, ctx);
                    return vec![format!("Helpers.contentFor({slot:?}, {body_s});")];
                }
            }
            vec!["/* TODO ERB: content_for with complex body */".to_string()]
        }
        // `coll.each do |x| ... end` — only if coll is simple.
        ExprNode::Send { recv: Some(recv), method, args, block: Some(block), .. }
            if method.as_str() == "each" && args.is_empty() =>
        {
            if !is_ts_simple_expr(recv, ctx) {
                return vec!["/* TODO ERB: each over complex coll */".to_string()];
            }
            let ExprNode::Lambda { params, body, .. } = &*block.node else {
                return vec!["/* unexpected each block */".to_string()];
            };
            let coll_s = emit_ts_view_expr_raw(recv, ctx);
            let var = params.first().map(|p| p.as_str().to_string()).unwrap_or_else(|| "item".into());
            let inner_ctx = TsViewCtx {
                locals: {
                    let mut l = ctx.locals.clone();
                    if !l.iter().any(|x| x == &var) {
                        l.push(var.clone());
                    }
                    l
                },
                arg_name: ctx.arg_name.clone(),
                arg_attrs: ctx.arg_attrs.clone(),
                resource_dir: ctx.resource_dir.clone(),
                stylesheets: ctx.stylesheets.clone(),
            };
            let mut out = vec![format!("for (const {var} of {coll_s}) {{")];
            for line in emit_ts_view_body(body, &inner_ctx) {
                out.push(format!("  {line}"));
            }
            out.push("}".to_string());
            out
        }
        _ => vec!["/* TODO ERB: unknown stmt */".to_string()],
    }
}

fn emit_ts_view_append_pass2(arg: &Expr, ctx: &TsViewCtx) -> String {
    // Text chunk.
    if let ExprNode::Lit { value: Literal::Str { value: s } } = &*arg.node {
        return format!("_buf += {};", ts_string_literal(s));
    }
    let inner = unwrap_to_s_ts(arg);

    // `render @coll` / `render "partial", locals` — expand.
    if let ExprNode::Send { recv, method, args, block, .. } = &*inner.node {
        if let Some(rp) = crate::lower::classify_render_partial(
            recv.as_ref(),
            method.as_str(),
            args,
            block.as_ref(),
            &|n| ctx.is_local(n),
        ) {
            return emit_ts_render_partial(&rp, ctx);
        }
    }

    // Capturing helpers (form_with, content_for) — inner buffer.
    if let ExprNode::Send {
        recv: None,
        method,
        args,
        block: Some(block),
        ..
    } = &*inner.node
    {
        if is_ts_capturing_helper(method.as_str()) {
            return emit_ts_captured_helper(method.as_str(), args, block, ctx);
        }
    }

    // `<%= yield %>` / `<%= yield :slot %>` — ExprNode::Yield,
    // not a Send. Maps to the runtime's yield-body / named-slot
    // getters populated by the request dispatcher + content_for
    // setters.
    if let ExprNode::Yield { args } = &*inner.node {
        if args.is_empty() {
            return "_buf += Helpers.getYield();".to_string();
        }
        if args.len() == 1 {
            if let ExprNode::Lit { value: Literal::Sym { value } } = &*args[0].node {
                return format!("_buf += Helpers.getSlot({:?});", value.as_str());
            }
        }
    }

    // Bare view-helper call — single classifier-backed dispatch
    // for every Rails helper we recognize (csrf_meta_tags,
    // dom_id, link_to, etc). The classifier in `lower::view`
    // enforces the method-name + arity match once; this function
    // owns the TS-specific rendering per variant.
    if let ExprNode::Send { recv: None, method, args, block: None, .. } = &*inner.node {
        if let Some(kind) =
            crate::lower::classify_view_helper(method.as_str(), args)
        {
            if let Some(out) = emit_ts_view_helper(&kind, ctx) {
                return out;
            }
        }
    }

    // `content_for(:title) || "Real Blog"` — ingested as a BoolOp
    // (Or) not a Send, so the classifier doesn't see it. Match
    // here; lower to JS `||` which has matching empty-string
    // falsy semantics since `contentFor` returns "" for unset
    // slots.
    if let ExprNode::BoolOp { op: crate::expr::BoolOpKind::Or, left, right, .. } = &*inner.node
    {
        if let ExprNode::Send {
            recv: None, method, args, block: None, ..
        } = &*left.node
        {
            if let Some(crate::lower::ViewHelperKind::ContentForGetter { slot }) =
                crate::lower::classify_view_helper(method.as_str(), args)
            {
                if is_ts_simple_expr(right, ctx) {
                    let fallback = emit_ts_view_expr_raw(right, ctx);
                    return format!(
                        "_buf += (Helpers.contentFor({slot:?}) || {fallback});",
                    );
                }
            }
        }
    }

    // `form.label :title` / `form.text_field :title, class: "..."` /
    // `form.text_area :body, rows: 4, class: "..."` /
    // `form.submit class: "..."` — FormBuilder method calls.
    // Recognize when `form` is a local (bound by the enclosing
    // form_with's block param). Hash arguments (class, rows, etc.)
    // pass through as an options object; non-hash args (first
    // arg is typically a field symbol) go positionally.
    if let ExprNode::Send { recv: Some(r), method, args, block: None, .. } = &*inner.node {
        if let ExprNode::Var { name: recv_name, .. } = &*r.node {
            if ctx.is_local(recv_name.as_str()) {
                if let Some(fb_method) =
                    crate::lower::classify_form_builder_method(method.as_str())
                {
                    // Translate the shared kind into TS's camelCased
                    // FormBuilder API. Other targets pick the
                    // language-appropriate mapping (snake_case in
                    // rust/python, etc.) from the same classifier.
                    let js_method = match fb_method {
                        crate::lower::FormBuilderMethod::Label => "label",
                        crate::lower::FormBuilderMethod::TextField => "textField",
                        crate::lower::FormBuilderMethod::TextArea => "textArea",
                        crate::lower::FormBuilderMethod::Submit => "submit",
                    };
                    return emit_ts_form_builder_call(
                        recv_name.as_str(),
                        js_method,
                        args,
                        ctx,
                    );
                }
            }
        }
    }

    // Simple interpolation.
    if is_ts_simple_expr(inner, ctx) {
        return format!(
            "_buf += String({});",
            emit_ts_view_expr_raw(inner, ctx),
        );
    }

    "_buf += \"\"; /* TODO ERB: complex interpolation */".to_string()
}

fn is_ts_capturing_helper(method: &str) -> bool {
    matches!(method, "form_with" | "content_for")
}

/// Emit a FormBuilder method call (`form.label("title")` etc.)
/// that produces HTML appended to the surrounding view buffer.
fn emit_ts_form_builder_call(
    recv: &str,
    js_method: &str,
    args: &[Expr],
    ctx: &TsViewCtx,
) -> String {
    // `submit` takes a positional String label (not a Sym field),
    // plus optional opts.
    if js_method == "submit" {
        let label_str = args.iter().find_map(|a| match &*a.node {
            ExprNode::Lit { value: Literal::Str { value } } => Some(value.clone()),
            _ => None,
        });
        let opts_hash: Option<String> = args.iter().find_map(|a| match &*a.node {
            ExprNode::Hash { entries, .. } => Some(ts_hash_to_object_literal(entries, ctx)),
            _ => None,
        });
        let opts_with_label = match (label_str, opts_hash) {
            (Some(lbl), Some(opts)) => {
                let trimmed = opts.trim_end_matches(" }").trim_end_matches('}');
                if trimmed.ends_with('{') {
                    format!("{{ \"label\": {lbl:?} }}")
                } else {
                    format!("{trimmed}, \"label\": {lbl:?} }}")
                }
            }
            (Some(lbl), None) => format!("{{ \"label\": {lbl:?} }}"),
            (None, Some(opts)) => opts,
            (None, None) => String::new(),
        };
        return format!("_buf += {recv}.submit({opts_with_label});");
    }

    let (field_raw, opts_entries) = crate::lower::classify_form_builder_args(args);
    let field_arg = field_raw.map(|f| format!("{f:?}"));
    let opts_arg = opts_entries.map(|entries| ts_hash_to_object_literal(entries, ctx));
    let call_args = match (field_arg, opts_arg) {
        (Some(field), Some(opts)) => format!("{field}, {opts}"),
        (Some(field), None) => field,
        (None, Some(opts)) => opts,
        (None, None) => String::new(),
    };
    format!("_buf += {recv}.{js_method}({call_args});")
}

/// Render a classified `ViewHelperKind` as a TS statement.
fn emit_ts_view_helper(
    kind: &crate::lower::ViewHelperKind<'_>,
    ctx: &TsViewCtx,
) -> Option<String> {
    use crate::lower::ViewHelperKind::*;
    match kind {
        CsrfMetaTags => Some("_buf += Helpers.csrfMetaTags();".to_string()),
        CspMetaTag => Some("_buf += Helpers.cspMetaTag();".to_string()),
        JavascriptImportmapTags => {
            Some("_buf += Helpers.javascriptImportmapTags(Importmap.PINS);".to_string())
        }
        TurboStreamFrom { channel } => {
            if !is_ts_simple_expr(channel, ctx) {
                return None;
            }
            let arg = emit_ts_view_expr_raw(channel, ctx);
            Some(format!("_buf += Helpers.turboStreamFrom({arg});"))
        }
        DomId { record, prefix } => {
            if !is_ts_simple_expr(record, ctx) {
                return None;
            }
            let rec = emit_ts_view_expr_raw(record, ctx);
            match prefix {
                None => Some(format!("_buf += Helpers.domId({rec});")),
                Some(p) => {
                    let prefix_expr = match &*p.node {
                        ExprNode::Lit { value: Literal::Sym { value } } => {
                            format!("{:?}", value.as_str())
                        }
                        ExprNode::Lit { value: Literal::Str { value } } => {
                            format!("{value:?}")
                        }
                        _ if is_ts_simple_expr(p, ctx) => emit_ts_view_expr_raw(p, ctx),
                        _ => return Some(format!("_buf += Helpers.domId({rec});")),
                    };
                    Some(format!("_buf += Helpers.domId({rec}, {prefix_expr});"))
                }
            }
        }
        Pluralize { count, word } => {
            if !is_ts_simple_expr(count, ctx) || !is_ts_simple_expr(word, ctx) {
                return None;
            }
            let c = emit_ts_view_expr_raw(count, ctx);
            let w = emit_ts_view_expr_raw(word, ctx);
            Some(format!("_buf += Helpers.pluralize({c}, {w});"))
        }
        Truncate { text, opts } => {
            if !is_ts_simple_expr(text, ctx) {
                return None;
            }
            let t = emit_ts_view_expr_raw(text, ctx);
            let opts_s = match opts {
                Some(e) => match &*e.node {
                    ExprNode::Hash { entries, .. } => ts_hash_to_object_literal(entries, ctx),
                    _ => "{}".to_string(),
                },
                None => "{}".to_string(),
            };
            Some(format!("_buf += Helpers.truncate({t}, {opts_s});"))
        }
        StylesheetLinkTag { name, opts } => {
            let opts_s = match opts {
                Some(e) => match &*e.node {
                    ExprNode::Hash { entries, .. } => ts_hash_to_object_literal(entries, ctx),
                    _ => "{}".to_string(),
                },
                None => "{}".to_string(),
            };
            // `:app` is the scaffold shorthand Rails expands to
            // every stylesheet in the asset path; mirror by
            // emitting one link per ingested stylesheet name.
            if let ExprNode::Lit { value: Literal::Sym { value } } = &*name.node {
                if value.as_str() == "app" && !ctx.stylesheets.is_empty() {
                    let calls: Vec<String> = ctx
                        .stylesheets
                        .iter()
                        .map(|n| format!("_buf += Helpers.stylesheetLinkTag({n:?}, {opts_s});"))
                        .collect();
                    return Some(calls.join("\n_buf += \"\\n\";\n"));
                }
            }
            let name_expr = match &*name.node {
                ExprNode::Lit { value: Literal::Sym { value } } => format!("{:?}", value.as_str()),
                ExprNode::Lit { value: Literal::Str { value } } => format!("{value:?}"),
                _ => return None,
            };
            Some(format!("_buf += Helpers.stylesheetLinkTag({name_expr}, {opts_s});"))
        }
        ContentForGetter { slot } => {
            Some(format!("_buf += Helpers.contentFor({slot:?});"))
        }
        ContentForSetter { .. } => None,
        LinkTo { text, url, opts } => {
            let args = build_link_like_args(text, url, *opts);
            try_emit_link_or_button("link_to", &args, ctx).map(|call| format!("_buf += {call};"))
        }
        ButtonTo { text, target, opts } => {
            let args = build_link_like_args(text, target, *opts);
            try_emit_link_or_button("button_to", &args, ctx).map(|call| format!("_buf += {call};"))
        }
    }
}

fn build_link_like_args<'a>(
    text: &'a Expr,
    url: &'a Expr,
    opts: Option<&'a Expr>,
) -> Vec<Expr> {
    let mut out = vec![text.clone(), url.clone()];
    if let Some(o) = opts {
        out.push(o.clone());
    }
    out
}

fn try_emit_link_or_button(
    method: &str,
    args: &[Expr],
    ctx: &TsViewCtx,
) -> Option<String> {
    let js_helper = match method {
        "link_to" => "linkTo",
        "button_to" => "buttonTo",
        _ => return None,
    };

    if !is_ts_simple_expr(&args[0], ctx) {
        return None;
    }
    let text = emit_ts_view_expr_raw(&args[0], ctx);

    let url = if args.len() >= 2 {
        ts_emit_url_arg(&args[1], ctx)?
    } else {
        return None;
    };

    let opts = args.iter().skip(2).find_map(|a| match &*a.node {
        ExprNode::Hash { entries, .. } => Some(ts_link_opts_literal(entries, ctx)),
        _ => None,
    });
    let opts_s = opts.unwrap_or_else(|| "{}".to_string());

    Some(format!("Helpers.{js_helper}({text}, {url}, {opts_s})"))
}

fn ts_emit_url_arg(arg: &Expr, ctx: &TsViewCtx) -> Option<String> {
    match &*arg.node {
        ExprNode::Send { recv: None, method, args, block: None, .. }
            if method.as_str().ends_with("_path") && args.is_empty() =>
        {
            let js = format!(
                "routeHelpers.{}()",
                lower_first_char(&crate::naming::camelize(method.as_str())),
            );
            Some(js)
        }
        ExprNode::Send { recv: None, method, args, block: None, .. }
            if method.as_str().ends_with("_path") && !args.is_empty() =>
        {
            let fn_js = lower_first_char(&crate::naming::camelize(method.as_str()));
            let emitted_args: Vec<String> = args
                .iter()
                .map(|a| ts_emit_path_arg(a, ctx))
                .collect();
            Some(format!("routeHelpers.{fn_js}({})", emitted_args.join(", ")))
        }
        ExprNode::Var { name, .. } | ExprNode::Ivar { name } => {
            let local = name.as_str();
            if !ctx.is_local(local) {
                return None;
            }
            Some(format!("routeHelpers.{local}Path({local}.id)"))
        }
        ExprNode::Send {
            recv: None,
            method,
            args,
            block: None,
            ..
        } if args.is_empty() && ctx.is_local(method.as_str()) => {
            let local = method.as_str();
            Some(format!("routeHelpers.{local}Path({local}.id)"))
        }
        ExprNode::Lit { value: Literal::Str { .. } } => {
            Some(emit_ts_view_expr_raw(arg, ctx))
        }
        ExprNode::Array { elements, .. } if elements.len() >= 2 => {
            ts_emit_nested_path(elements, ctx)
        }
        _ => None,
    }
}

fn ts_emit_nested_path(elements: &[Expr], ctx: &TsViewCtx) -> Option<String> {
    let mut singulars: Vec<String> = Vec::new();
    let mut args: Vec<String> = Vec::new();
    for el in elements {
        let (singular, id_expr) = ts_classify_nested_element(el, ctx)?;
        singulars.push(singular);
        args.push(id_expr);
    }
    let mut name = String::new();
    for (i, s) in singulars.iter().enumerate() {
        if i == 0 {
            name.push_str(s);
        } else {
            name.push_str(&crate::naming::camelize(s));
        }
    }
    name.push_str("Path");
    Some(format!("routeHelpers.{name}({})", args.join(", ")))
}

fn ts_classify_nested_element(el: &Expr, ctx: &TsViewCtx) -> Option<(String, String)> {
    let is_local = |n: &str| ctx.is_local(n);
    let kind = crate::lower::classify_nested_url_element(el, &is_local)?;
    Some(match kind {
        crate::lower::NestedUrlElement::DirectLocal { name } => {
            (name.to_string(), format!("{name}.id"))
        }
        crate::lower::NestedUrlElement::Association { owner, assoc } => {
            (assoc.to_string(), format!("{owner}.{assoc}_id"))
        }
    })
}

fn ts_emit_path_arg(arg: &Expr, ctx: &TsViewCtx) -> String {
    match &*arg.node {
        ExprNode::Var { name, .. } | ExprNode::Ivar { name } => {
            if ctx.is_local(name.as_str()) {
                format!("{local}.id", local = name.as_str())
            } else {
                name.as_str().to_string()
            }
        }
        ExprNode::Send {
            recv: None,
            method,
            args,
            block: None,
            ..
        } if args.is_empty() && ctx.is_local(method.as_str()) => {
            format!("{local}.id", local = method.as_str())
        }
        _ => emit_ts_view_expr_raw(arg, ctx),
    }
}

fn ts_link_opts_literal(entries: &[(Expr, Expr)], ctx: &TsViewCtx) -> String {
    let mut parts: Vec<String> = Vec::new();
    for (k, v) in entries {
        let key = match &*k.node {
            ExprNode::Lit { value: Literal::Sym { value } } => value.as_str().to_string(),
            ExprNode::Lit { value: Literal::Str { value } } => value.clone(),
            _ => continue,
        };
        if key == "data" {
            if let ExprNode::Hash { entries: data_entries, .. } = &*v.node {
                for (dk, dv) in data_entries {
                    let dk_str = match &*dk.node {
                        ExprNode::Lit { value: Literal::Sym { value } } => {
                            value.as_str().replace('_', "-")
                        }
                        ExprNode::Lit { value: Literal::Str { value } } => {
                            value.replace('_', "-")
                        }
                        _ => continue,
                    };
                    let dv_s = if is_ts_simple_expr(dv, ctx) {
                        emit_ts_view_expr_raw(dv, ctx)
                    } else {
                        continue;
                    };
                    parts.push(format!("\"data-{dk_str}\": {dv_s}"));
                }
                continue;
            }
        }
        let val = match &*v.node {
            ExprNode::Lit { value: Literal::Sym { value } } => format!("{:?}", value.as_str()),
            _ if is_ts_simple_expr(v, ctx) => emit_ts_view_expr_raw(v, ctx),
            _ => continue,
        };
        parts.push(format!("{key:?}: {val}"));
    }
    format!("{{ {} }}", parts.join(", "))
}

fn ts_hash_to_object_literal(
    entries: &[(Expr, Expr)],
    ctx: &TsViewCtx,
) -> String {
    let mut parts = Vec::new();
    for (k, v) in entries {
        let key = match &*k.node {
            ExprNode::Lit { value: Literal::Sym { value } } => value.as_str().to_string(),
            ExprNode::Lit { value: Literal::Str { value } } => value.clone(),
            _ => continue,
        };
        let val = if key == "class" {
            ts_class_value(v, ctx)
        } else if is_ts_simple_expr(v, ctx) {
            emit_ts_view_expr_raw(v, ctx)
        } else if let ExprNode::Array { elements, .. } = &*v.node {
            match elements.first() {
                Some(first) if is_ts_simple_expr(first, ctx) => emit_ts_view_expr_raw(first, ctx),
                _ => "\"\"".to_string(),
            }
        } else {
            "\"\"".to_string()
        };
        parts.push(format!("{key:?}: {val}"));
    }
    format!("{{ {} }}", parts.join(", "))
}

fn ts_class_value(v: &Expr, ctx: &TsViewCtx) -> String {
    let is_local = |n: &str| ctx.is_local(n);
    let simple_as_js = |e: &Expr| -> Option<String> {
        if is_ts_simple_expr(e, ctx) {
            Some(emit_ts_view_expr_raw(e, ctx))
        } else {
            None
        }
    };
    match crate::lower::classify_class_value(v, &is_local) {
        crate::lower::ClassValueShape::Simple { expr } => {
            simple_as_js(expr).unwrap_or_else(|| "\"\"".to_string())
        }
        crate::lower::ClassValueShape::Conditional { base, clauses } => {
            let Some(base_js) = simple_as_js(base) else {
                return "\"\"".to_string();
            };
            if clauses.is_empty() {
                return base_js;
            }
            let extras: Vec<String> = clauses
                .iter()
                .map(|(cls_text, pred)| {
                    let cond_js = ts_render_errors_field_predicate(pred);
                    format!(" + ({cond_js} ? \" {cls_text}\" : \"\")")
                })
                .collect();
            format!("({base_js}{})", extras.join(""))
        }
        crate::lower::ClassValueShape::Unknown => "\"\"".to_string(),
    }
}

fn ts_render_errors_field_predicate(pred: &crate::lower::ErrorsFieldPredicate<'_>) -> String {
    let call = format!(
        "Helpers.fieldHasError({}.errors, {:?})",
        pred.record, pred.field,
    );
    if pred.expect_present {
        call
    } else {
        format!("!{call}")
    }
}

fn emit_ts_captured_helper(
    method: &str,
    args: &[Expr],
    block: &Expr,
    ctx: &TsViewCtx,
) -> String {
    let ExprNode::Lambda { params, body, .. } = &*block.node else {
        return format!("_buf += \"\"; /* TODO ERB: {method} */");
    };
    let cls_expr = args
        .iter()
        .find_map(|a| ts_extract_kwarg(a, "class"))
        .filter(|e| is_ts_simple_expr(e, ctx))
        .map(|e| emit_ts_view_expr_raw(e, ctx))
        .unwrap_or_else(|| "\"\"".to_string());
    let model_kwarg = args
        .iter()
        .find_map(|a| ts_extract_kwarg(a, "model"));
    let model_nested = model_kwarg.and_then(|e| match &*e.node {
        ExprNode::Array { elements, .. } if elements.len() >= 2 => Some(elements.clone()),
        _ => None,
    });
    let model_expr = if model_nested.is_some() {
        let elems = model_nested.as_ref().unwrap();
        Some(emit_ts_nested_form_record(&elems[elems.len() - 1]))
    } else {
        model_kwarg
            .filter(|e| is_ts_simple_expr(e, ctx))
            .map(|e| emit_ts_view_expr_raw(e, ctx))
            .or_else(|| {
                if !ctx.arg_name.is_empty() && ctx.is_local(&ctx.arg_name) {
                    Some(ctx.arg_name.clone())
                } else {
                    None
                }
            })
    };
    let inner_body = match method {
        "form_with" => {
            let pname = params.first().map(|p| p.as_str()).unwrap_or("form");
            let record_arg = model_expr.clone().unwrap_or_else(|| "null".to_string());
            let prefix = if let Some(elems) = &model_nested {
                ts_nested_form_child_prefix(&elems[elems.len() - 1])
                    .unwrap_or_else(|| ctx.arg_name.clone())
            } else if !ctx.resource_dir.is_empty() {
                crate::naming::singularize(&ctx.resource_dir)
            } else {
                ctx.arg_name.clone()
            };
            let mut lines = vec![
                "{".to_string(),
                "  let _buf = \"\";".to_string(),
                format!(
                    "  const {pname} = new Helpers.FormBuilder({record_arg} as any, \"{prefix}\");",
                ),
                format!(
                    "  _buf += Helpers.errorMessagesFor({record_arg} as any, \"{prefix}\");",
                ),
            ];
            let inner_ctx = TsViewCtx {
                locals: {
                    let mut l = ctx.locals.clone();
                    l.push(pname.to_string());
                    l
                },
                arg_name: ctx.arg_name.clone(),
                arg_attrs: ctx.arg_attrs.clone(),
                resource_dir: ctx.resource_dir.clone(),
                stylesheets: ctx.stylesheets.clone(),
            };
            for line in emit_ts_view_body(body, &inner_ctx) {
                lines.push(format!("  {line}"));
            }
            let plural = if !ctx.resource_dir.is_empty() {
                ctx.resource_dir.clone()
            } else {
                crate::naming::pluralize_snake(&prefix)
            };
            let plural_camel = lower_first_char(&crate::naming::camelize(&plural));
            let singular_camel = lower_first_char(&crate::naming::camelize(&prefix));
            let record_ref = model_expr.clone().unwrap_or_else(|| "null".to_string());
            let path_expr = if let Some(elems) = &model_nested {
                ts_nested_form_path_expr(elems, ctx, &record_ref, &prefix)
            } else {
                format!(
                    "(({record_ref} as any)?.id ? routeHelpers.{singular_camel}Path(({record_ref} as any).id) : routeHelpers.{plural_camel}Path())",
                )
            };
            lines.push(format!(
                "  return Helpers.formWrap({record_arg} as any, {path_expr}, {cls_expr}, _buf);",
            ));
            lines.push("}".to_string());
            lines.join("\n  ")
        }
        _ => "\"\"".to_string(),
    };
    match method {
        "form_with" => format!("_buf += (() => {inner_body})();"),
        "content_for" => {
            let _ = args;
            let _ = cls_expr;
            format!("/* content_for stashed */")
        }
        _ => format!("_buf += \"\";"),
    }
}

fn emit_ts_render_partial(
    rp: &crate::lower::RenderPartial<'_>,
    ctx: &TsViewCtx,
) -> String {
    use crate::lower::RenderPartial;
    match rp {
        RenderPartial::Collection { name, .. } => {
            let plural_pascal = crate::naming::camelize(name);
            let singular_pascal =
                crate::naming::camelize(&crate::naming::singularize(name));
            let partial_fn = format!("Views.render{plural_pascal}{singular_pascal}");
            format!(
                "_buf += {name}.map((__r: any) => {partial_fn}(__r)).join(\"\");",
            )
        }
        RenderPartial::Association { receiver, method } => {
            let plural_pascal = crate::naming::camelize(method);
            let singular_pascal =
                crate::naming::camelize(&crate::naming::singularize(method));
            let partial_fn = format!("Views.render{plural_pascal}{singular_pascal}");
            let parent_name = match &*receiver.node {
                ExprNode::Var { name, .. } | ExprNode::Ivar { name } => name.to_string(),
                _ => return "_buf += \"\"; /* TODO ERB: render */".to_string(),
            };
            format!(
                "_buf += {parent_name}.{method}.map((__c: any) => {partial_fn}(__c)).join(\"\");",
            )
        }
        RenderPartial::Named { partial, arg } => {
            let plural_pascal = crate::naming::camelize(&ctx.resource_dir);
            let partial_fn = format!(
                "Views.render{}{}",
                plural_pascal,
                crate::naming::camelize(partial),
            );
            match arg {
                Some(v) if is_ts_simple_expr(v, ctx) => {
                    let arg_expr = emit_ts_view_expr_raw(v, ctx);
                    format!("_buf += {partial_fn}({arg_expr});")
                }
                _ => format!("_buf += {partial_fn}(undefined as any);"),
            }
        }
    }
}

fn emit_ts_nested_form_record(el: &Expr) -> String {
    match crate::lower::classify_nested_form_child(el) {
        Some(crate::lower::NestedFormChild::ClassNew { class }) => format!("new {class}()"),
        Some(crate::lower::NestedFormChild::Local { name }) => name.to_string(),
        None => "null".to_string(),
    }
}

fn ts_nested_form_child_prefix(el: &Expr) -> Option<String> {
    crate::lower::classify_nested_form_child(el).map(|k| k.prefix())
}

fn ts_nested_form_path_expr(
    elems: &[Expr],
    ctx: &TsViewCtx,
    record_ref: &str,
    child_prefix: &str,
) -> String {
    let mut parent_ids: Vec<String> = Vec::new();
    let mut parent_singulars: Vec<String> = Vec::new();
    for parent in &elems[..elems.len() - 1] {
        let (singular, id_expr) = match ts_classify_nested_element(parent, ctx) {
            Some(x) => x,
            None => return format!("\"\" /* TODO: nested form parent */"),
        };
        parent_singulars.push(singular);
        parent_ids.push(id_expr);
    }
    let mut member_name = String::new();
    for (i, s) in parent_singulars.iter().enumerate() {
        if i == 0 {
            member_name.push_str(s);
        } else {
            member_name.push_str(&crate::naming::camelize(s));
        }
    }
    member_name.push_str(&crate::naming::camelize(child_prefix));
    member_name.push_str("Path");
    let mut collection_name = String::new();
    for (i, s) in parent_singulars.iter().enumerate() {
        if i == 0 {
            collection_name.push_str(s);
        } else {
            collection_name.push_str(&crate::naming::camelize(s));
        }
    }
    let child_plural = crate::naming::pluralize_snake(child_prefix);
    collection_name.push_str(&crate::naming::camelize(&child_plural));
    collection_name.push_str("Path");
    let parent_args = parent_ids.join(", ");
    format!(
        "(({record_ref} as any)?.id ? routeHelpers.{member_name}({parent_args}, ({record_ref} as any).id) : routeHelpers.{collection_name}({parent_args}))",
    )
}

fn ts_extract_kwarg<'a>(arg: &'a Expr, key: &str) -> Option<&'a Expr> {
    if let ExprNode::Hash { entries, .. } = &*arg.node {
        for (k, v) in entries {
            if let ExprNode::Lit { value: Literal::Sym { value } } = &*k.node {
                if value.as_str() == key {
                    return Some(v);
                }
            }
        }
    }
    None
}

fn unwrap_to_s_ts(expr: &Expr) -> &Expr {
    if let ExprNode::Send { recv: Some(inner), method, args, .. } = &*expr.node {
        if method.as_str() == "to_s" && args.is_empty() {
            return inner;
        }
    }
    expr
}

fn ts_string_literal(s: &str) -> String {
    serde_json::to_string(s).unwrap_or_else(|_| format!("{s:?}"))
}

fn is_ts_simple_expr(expr: &Expr, ctx: &TsViewCtx) -> bool {
    match &*expr.node {
        ExprNode::Lit { .. } => true,
        ExprNode::Var { name, .. } | ExprNode::Ivar { name } => ctx.is_local(name.as_str()),
        ExprNode::Send {
            recv: None,
            method,
            args,
            block: None,
            ..
        } if args.is_empty() && ctx.is_local(method.as_str()) => true,
        ExprNode::Send { recv: Some(r), method, args, block, .. } => {
            if !args.is_empty() || block.is_some() {
                return false;
            }
            let clean = method.as_str().trim_end_matches('?').trim_end_matches('!');
            if clean.is_empty() {
                return false;
            }
            let recv_local = match &*r.node {
                ExprNode::Var { name, .. } | ExprNode::Ivar { name } => Some(name.as_str()),
                ExprNode::Send {
                    recv: None,
                    method: m,
                    args: ra,
                    block: None,
                    ..
                } if ra.is_empty() && ctx.is_local(m.as_str()) => Some(m.as_str()),
                _ => None,
            };
            if let Some(local_name) = recv_local {
                if ctx.arg_has_attr(local_name, clean) {
                    return true;
                }
                if ctx.is_local(local_name)
                    && matches!(method.as_str(), "any?" | "none?" | "present?" | "empty?")
                {
                    return true;
                }
                if ctx.is_local(local_name) {
                    return true;
                }
            }
            if is_ts_simple_expr(r, ctx) {
                return true;
            }
            false
        }
        ExprNode::StringInterp { parts } => parts.iter().all(|p| match p {
            crate::expr::InterpPart::Text { .. } => true,
            crate::expr::InterpPart::Expr { expr } => is_ts_simple_expr(expr, ctx),
        }),
        _ => false,
    }
}

fn emit_ts_view_expr_raw(expr: &Expr, ctx: &TsViewCtx) -> String {
    match &*expr.node {
        ExprNode::Lit { value } => emit_literal(value),
        ExprNode::Var { name, .. } | ExprNode::Ivar { name } => name.to_string(),
        ExprNode::Send {
            recv: None,
            method,
            args,
            block: None,
            ..
        } if args.is_empty() && ctx.is_local(method.as_str()) => method.to_string(),
        ExprNode::Send { recv: Some(r), method, args, .. } => {
            let method_s = method.as_str();
            if args.is_empty() {
                if let ExprNode::Var { name, .. } | ExprNode::Ivar { name } = &*r.node {
                    if ctx.is_local(name.as_str()) {
                        match method_s {
                            "any?" | "present?" => {
                                return format!("({name}.length > 0)");
                            }
                            "none?" | "empty?" => {
                                return format!("({name}.length === 0)");
                            }
                            _ => {}
                        }
                    }
                }
            }
            let recv_s = emit_ts_view_expr_raw(r, ctx);
            let clean = method_s.trim_end_matches('?').trim_end_matches('!');
            if args.is_empty() {
                format!("{recv_s}.{clean}")
            } else {
                let args_s: Vec<String> =
                    args.iter().map(|a| emit_ts_view_expr_raw(a, ctx)).collect();
                format!("{recv_s}.{clean}({})", args_s.join(", "))
            }
        }
        ExprNode::StringInterp { parts } => {
            use crate::expr::InterpPart;
            let mut out = String::from("`");
            for p in parts {
                match p {
                    InterpPart::Text { value } => {
                        for c in value.chars() {
                            if c == '`' || c == '\\' || c == '$' {
                                out.push('\\');
                            }
                            out.push(c);
                        }
                    }
                    InterpPart::Expr { expr } => {
                        out.push_str("${");
                        out.push_str(&emit_ts_view_expr_raw(expr, ctx));
                        out.push('}');
                    }
                }
            }
            out.push('`');
            out
        }
        _ => "\"\"".to_string(),
    }
}

/// Walk the view body and collect every ivar name referenced, in
/// source order, de-duplicated.
fn collect_ivar_names(expr: &Expr) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    collect_ivars_into(expr, &mut out);
    out
}

fn collect_ivars_into(expr: &Expr, out: &mut Vec<String>) {
    match &*expr.node {
        ExprNode::Ivar { name } => {
            let n = name.to_string();
            if !out.iter().any(|existing| existing == &n) {
                out.push(n);
            }
        }
        ExprNode::Assign { target, value } => {
            if let LValue::Ivar { name } = target {
                let n = name.to_string();
                if !out.iter().any(|existing| existing == &n) {
                    out.push(n);
                }
            }
            collect_ivars_into(value, out);
        }
        ExprNode::Send { recv, args, block, .. } => {
            if let Some(r) = recv {
                collect_ivars_into(r, out);
            }
            for a in args {
                collect_ivars_into(a, out);
            }
            if let Some(b) = block {
                collect_ivars_into(b, out);
            }
        }
        ExprNode::Seq { exprs } => {
            for e in exprs {
                collect_ivars_into(e, out);
            }
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            collect_ivars_into(cond, out);
            collect_ivars_into(then_branch, out);
            collect_ivars_into(else_branch, out);
        }
        ExprNode::BoolOp { left, right, .. } => {
            collect_ivars_into(left, out);
            collect_ivars_into(right, out);
        }
        ExprNode::Array { elements, .. } => {
            for e in elements {
                collect_ivars_into(e, out);
            }
        }
        ExprNode::Hash { entries, .. } => {
            for (k, v) in entries {
                collect_ivars_into(k, out);
                collect_ivars_into(v, out);
            }
        }
        ExprNode::Lambda { body, .. } => collect_ivars_into(body, out),
        ExprNode::Apply { fun, args, block } => {
            collect_ivars_into(fun, out);
            for a in args {
                collect_ivars_into(a, out);
            }
            if let Some(b) = block {
                collect_ivars_into(b, out);
            }
        }
        ExprNode::Let { value, body, .. } => {
            collect_ivars_into(value, out);
            collect_ivars_into(body, out);
        }
        ExprNode::Case { scrutinee, arms } => {
            collect_ivars_into(scrutinee, out);
            for arm in arms {
                if let Some(g) = &arm.guard {
                    collect_ivars_into(g, out);
                }
                collect_ivars_into(&arm.body, out);
            }
        }
        ExprNode::Yield { args } => {
            for a in args {
                collect_ivars_into(a, out);
            }
        }
        ExprNode::Raise { value } => collect_ivars_into(value, out),
        ExprNode::RescueModifier { expr, fallback } => {
            collect_ivars_into(expr, out);
            collect_ivars_into(fallback, out);
        }
        ExprNode::StringInterp { parts } => {
            for p in parts {
                if let crate::expr::InterpPart::Expr { expr } = p {
                    collect_ivars_into(expr, out);
                }
            }
        }
        // Leaves without subexpressions.
        ExprNode::Lit { .. }
        | ExprNode::Var { .. }
        | ExprNode::Const { .. }
        | ExprNode::SelfRef => {}

        ExprNode::Return { value } => collect_ivars_into(value, out),
        ExprNode::Super { args } => {
            if let Some(args) = args {
                for a in args {
                    collect_ivars_into(a, out);
                }
            }
        }
        ExprNode::BeginRescue { body, rescues, else_branch, ensure, .. } => {
            collect_ivars_into(body, out);
            for rc in rescues {
                for c in &rc.classes {
                    collect_ivars_into(c, out);
                }
                collect_ivars_into(&rc.body, out);
            }
            if let Some(e) = else_branch {
                collect_ivars_into(e, out);
            }
            if let Some(e) = ensure {
                collect_ivars_into(e, out);
            }
        }
        ExprNode::Next { value } => {
            if let Some(v) = value { collect_ivars_into(v, out); }
        }
        ExprNode::MultiAssign { value, .. } => collect_ivars_into(value, out),
        ExprNode::While { cond, body, .. } => {
            collect_ivars_into(cond, out);
            collect_ivars_into(body, out);
        }
        ExprNode::Range { begin, end, .. } => {
            if let Some(b) = begin { collect_ivars_into(b, out); }
            if let Some(e) = end { collect_ivars_into(e, out); }
        }
    }
}

// ── Public shims for the thin emitter (`view_thin.rs`) ──
// The thin emitter wants to reuse the file-name conversion, the
// signature builder, and the barrel/stubs file producers without
// duplicating them. Expose them under `__*_for_thin` names so the
// parent module finds them but the underscore-prefix marks them as
// transitional plumbing — drop when the thin emitter replaces this
// file entirely.

pub(super) fn __view_function_name_for_thin(name: &str) -> String {
    view_function_name(name)
}

pub(super) fn __ts_view_signature_for_thin(
    view_name: &str,
    known_models: &[Symbol],
) -> (String, String, Option<String>) {
    ts_view_signature(view_name, known_models)
}

pub(super) fn __emit_ts_views_barrel_for_thin(app: &App) -> EmittedFile {
    emit_ts_views_barrel(app)
}

pub(super) fn __emit_ts_missing_view_stubs_for_thin(
    app: &App,
    known_models: &[Symbol],
) -> Option<EmittedFile> {
    emit_ts_missing_view_stubs(app, known_models)
}

/// `articles/index` → `renderArticlesIndex`. Slashes become PascalCase
/// separators; partial-prefix underscores stay lowercased at the head
/// of the segment (`_article` → `Article` — underscore dropped).
fn view_function_name(name: &str) -> String {
    let mut out = String::from("render");
    for seg in name.split('/') {
        let trimmed = seg.strip_prefix('_').unwrap_or(seg);
        for word in trimmed.split('_') {
            let mut chars = word.chars();
            if let Some(first) = chars.next() {
                out.push(first.to_ascii_uppercase());
                out.push_str(chars.as_str());
            }
        }
    }
    out
}
