//! `src/app.cr` emission — top-level entry that requires the rest.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use crate::App;

/// `src/app.cr` — Crystal entry point. Requires the emitted modules we
/// expect to compile.
pub(super) fn emit_app_cr(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    if !app.models.is_empty() {
        writeln!(s, "require \"./runtime\"").unwrap();
        writeln!(s, "require \"./db\"").unwrap();
        writeln!(s, "require \"./schema_sql\"").unwrap();
        writeln!(s, "require \"./models\"").unwrap();
    }
    if !app.controllers.is_empty() {
        writeln!(s, "require \"./http\"").unwrap();
        writeln!(s, "require \"./view_helpers\"").unwrap();
        writeln!(s, "require \"./route_helpers\"").unwrap();
        writeln!(s, "require \"./importmap\"").unwrap();
        writeln!(s, "require \"./views\"").unwrap();
        writeln!(s, "require \"./controllers\"").unwrap();
        writeln!(s, "require \"./routes\"").unwrap();
        writeln!(s, "require \"./test_support\"").unwrap();
        writeln!(s, "require \"./cable\"").unwrap();
        writeln!(s, "require \"./server\"").unwrap();
        // Entry point — run the server when crystal-built binary is
        // invoked. Test specs require `src/app.cr` for type defs
    }
    EmittedFile {
        path: PathBuf::from("src/app.cr"),
        content: s,
    }
}
