//! Controller emission — `module FooActions` with one `def self.<action>`
//! per Rails action. Walks the lowered action body through `CrEmitter`,
//! a `CtrlWalker` impl that performs the controller-scope Send rewrites.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use super::expr::emit_expr;
use super::view::apply_cr_chain_modifier;
use crate::App;
use crate::dialect::Controller;
use crate::expr::{Expr, ExprNode, Literal};
use crate::ident::Symbol;
use crate::lower::CtrlWalker as _;

// Controllers ----------------------------------------------------------
//
// Phase 4c: actions and private helpers render through the controller-
// scope Send rewrites (`emit_controller_send_cr`), matching the Rust
// emitter's shape. Every action returns `Roundhouse::Http::Response`;
// bodies emit their natural content as statements, with `Response.new`
// tacked on as the tail (Rails' convention: ivars feed the view, not
// the action's return value).
//
// Rewrites handled for controller-body Sends:
//   * bare `params`          → `Roundhouse::Http.params`
//   * `params.expect(...)`   → passes through; `Params#expect` is a
//                              stub that accepts any shape
//   * `respond_to { ... }`   → `Roundhouse::Http.respond_to do |__fr|
//                              ... end`
//   * `format.html { body }` → `__fr.html { body }`
//   * `format.json { body }` → replaced by a `# TODO: JSON branch`
//                              comment at the call site
//   * bare `redirect_to` / `render` / `head` → `Roundhouse::Http.*`
//   * bare `*_path` / `*_url` → `""` (placeholder string — Crystal
//                              lacks Rust's `!` divergence trick, so
//                              we emit a typed default)
//   * `Model.new(anything)`  → `Model.new` (emitted models have no
//                              keyword/positional arg constructor)
//   * `Model.find(x)`        → `Model.find(x).not_nil!` (the class
//                              method returns `Model?`; the declared
//                              ivar type is non-nil)
//   * unsupported query chains (`.all`, `.order`, `.includes`, …) →
//                              `[] of Target`

pub(super) fn emit_controllers(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "require \"./http\"").unwrap();
    if !app.models.is_empty() {
        writeln!(s, "require \"./models\"").unwrap();
    }
    writeln!(s, "require \"./route_helpers\"").unwrap();
    writeln!(s, "require \"./views\"").unwrap();
    for controller in &app.controllers {
        writeln!(s).unwrap();
        emit_controller_pass2(&mut s, controller, app);
    }
    EmittedFile { path: PathBuf::from("src/controllers.cr"), content: s }
}

pub(super) fn emit_controller_pass2(out: &mut String, c: &Controller, app: &App) {
    let name = c.name.0.as_str();
    let actions_mod = format!("{name}Actions");
    writeln!(out, "module {actions_mod}").unwrap();

    // Crystal traditionally computed a plural `resource` and singular
    // separately; with the shared helpers, we take the singular from
    // `resource_from_controller_name` and derive plural for downstream
    // uses (emit helpers still key off plural).
    let singular = crate::lower::resource_from_controller_name(name);
    let resource = crate::naming::pluralize_snake(&crate::naming::camelize(&singular));
    let model_class = crate::naming::camelize(&singular);
    let known_models: Vec<Symbol> =
        app.models.iter().map(|m| m.name.0.clone()).collect();
    let has_model = known_models.iter().any(|m| m.as_str() == model_class);
    let parent = crate::lower::find_nested_parent(app, name);
    let permitted = crate::lower::permitted_fields_for(c, &singular)
        .unwrap_or_else(|| crate::lower::default_permitted_fields(app, &model_class));

    let _ = resource; // Plural-resource path only appears in destroy's index redirect.
    for action in c.actions() {
        let name = action.name.as_str();
        if !matches!(
            name,
            "index" | "show" | "new" | "edit" | "create" | "update" | "destroy"
        ) {
            continue;
        }
        writeln!(out).unwrap();
        let la = crate::lower::lower_action(
            name,
            &singular,
            &model_class,
            has_model,
            parent.as_ref(),
            &permitted,
        );
        emit_cr_action(out, &la, &action.body, &known_models, c);
    }

    writeln!(out, "end").unwrap();
}

/// Render one LoweredAction as a Crystal `def self.*`. Crystal's
/// `new` action renames to `new_action` (avoids collision with
/// Crystal's type-level `.new`). Body emission delegates to the
/// walker; the ActionKind dispatch is gone (TS/Rust/Python precedent).
pub(super) fn emit_cr_action(
    out: &mut String,
    la: &crate::lower::LoweredAction,
    body: &Expr,
    known_models: &[Symbol],
    controller: &Controller,
) {
    let response_ty = "Roundhouse::Http::ActionResponse";
    let ctx_ty = "Roundhouse::Http::ActionContext";
    let action_method_name = match la.name.as_str() {
        "new" => "new_action",
        other => other,
    };

    let mut body_src = String::new();
    let mut uses_context = false;
    if la.has_model {
        use crate::lower::CtrlWalker;
        let normalized =
            crate::lower::normalize_action_body(controller, la.name.as_str(), body);
        let mut emitter = CrEmitter {
            ctx: crate::lower::WalkCtx {
                known_models,
                model_class: la.model_class.as_str(),
                resource: la.resource.as_str(),
                parent: la.parent.as_ref(),
                permitted: &la.permitted,
                adapter: &crate::adapter::SqliteAdapter,
            },
            state: crate::lower::WalkState::new(),
        };
        body_src = emitter.walk_action_body(&normalized);
        uses_context = emitter.state.uses_context;
    } else {
        writeln!(body_src, "  {response_ty}.new").unwrap();
    }

    let ctx_param = if uses_context || body_src.contains("context") {
        "context"
    } else {
        "_context"
    };
    writeln!(
        out,
        "  def self.{action_method_name}({ctx_param} : {ctx_ty}) : {response_ty}"
    )
    .unwrap();
    out.push_str(&body_src);
    writeln!(out, "  end").unwrap();
}

struct CrEmitter<'a> {
    ctx: crate::lower::WalkCtx<'a>,
    state: crate::lower::WalkState,
}

impl<'a> crate::lower::CtrlWalker<'a> for CrEmitter<'a> {
    fn ctx(&self) -> &crate::lower::WalkCtx<'a> { &self.ctx }
    fn state_mut(&mut self) -> &mut crate::lower::WalkState { &mut self.state }
    fn indent_unit(&self) -> &'static str { "  " }

    fn write_assign(&mut self, name: &str, value: &Expr, indent: &str, out: &mut String) {
        let rhs = self.render_expr(value);
        writeln!(out, "{indent}{name} = {rhs}").unwrap();
    }

    fn write_create_expansion(
        &mut self,
        var_name: &str,
        class: &str,
        indent: &str,
        out: &mut String,
    ) {
        writeln!(out, "{indent}{var_name} = {class}.new").unwrap();
        if let Some(parent) = self.ctx.parent {
            writeln!(
                out,
                "{indent}{var_name}.{0}_id = context.params.fetch(\"{0}_id\", \"0\").to_i64",
                parent.singular,
            )
            .unwrap();
            self.state.uses_context = true;
        }
        let permitted: Vec<String> = self.ctx.permitted.iter().cloned().collect();
        let resource = self.ctx.resource.to_string();
        for field in &permitted {
            writeln!(
                out,
                "{indent}{var_name}.{field} = context.params.fetch(\"{resource}[{field}]\", \"\")",
            )
            .unwrap();
            self.state.uses_context = true;
        }
    }

    fn write_if(
        &mut self,
        cond: &Expr,
        then_branch: &Expr,
        else_branch: &Expr,
        indent: &str,
        depth: usize,
        is_tail: bool,
        out: &mut String,
    ) {
        let cond_s = self.render_expr(cond);
        writeln!(out, "{indent}if {cond_s}").unwrap();
        self.walk_stmt(then_branch, out, depth + 1, is_tail);
        if !crate::lower::is_empty_body(else_branch) {
            writeln!(out, "{indent}else").unwrap();
            self.walk_stmt(else_branch, out, depth + 1, is_tail);
        }
        writeln!(out, "{indent}end").unwrap();
    }

    fn write_update_if(
        &mut self,
        recv: &Expr,
        then_branch: &Expr,
        else_branch: &Expr,
        indent: &str,
        depth: usize,
        is_tail: bool,
        out: &mut String,
    ) {
        let recv_s = self.render_expr(recv);
        let permitted: Vec<String> = self.ctx.permitted.iter().cloned().collect();
        let resource = self.ctx.resource.to_string();
        for field in &permitted {
            writeln!(out, "{indent}if v = context.params[\"{resource}[{field}]\"]?").unwrap();
            writeln!(out, "{indent}  {recv_s}.{field} = v").unwrap();
            writeln!(out, "{indent}end").unwrap();
            self.state.uses_context = true;
        }
        writeln!(out, "{indent}if {recv_s}.save").unwrap();
        self.walk_stmt(then_branch, out, depth + 1, is_tail);
        if !crate::lower::is_empty_body(else_branch) {
            writeln!(out, "{indent}else").unwrap();
            self.walk_stmt(else_branch, out, depth + 1, is_tail);
        }
        writeln!(out, "{indent}end").unwrap();
    }

    fn write_response_stmt(&mut self, r: &str, _is_tail: bool, indent: &str, out: &mut String) {
        writeln!(out, "{indent}{r}").unwrap();
    }

    fn write_expr_stmt(&mut self, s: &str, indent: &str, out: &mut String) {
        writeln!(out, "{indent}{s}").unwrap();
    }

    fn render_expr(&mut self, expr: &Expr) -> String {
        if let ExprNode::Send { recv, method, args, block, .. } = &*expr.node {
            if let Some(stmt) = self.render_send_stmt(
                recv.as_ref(), method.as_str(), args, block.as_ref(), "",
            ) {
                return match stmt {
                    crate::lower::Stmt::Response(r) => r,
                    crate::lower::Stmt::Expr(s) => s,
                };
            }
            let args_s: Vec<String> = args.iter().map(|a| self.render_expr(a)).collect();
            return match recv {
                None if args.is_empty() => method.to_string(),
                None => format!("{method}({})", args_s.join(", ")),
                Some(r) => {
                    let recv_s = self.render_expr(r);
                    if args.is_empty() {
                        format!("{recv_s}.{method}")
                    } else {
                        format!("{recv_s}.{method}({})", args_s.join(", "))
                    }
                }
            };
        }
        if let ExprNode::Ivar { name } = &*expr.node {
            return name.to_string();
        }
        emit_expr(expr)
    }

    fn render_send_stmt(
        &mut self,
        recv: Option<&Expr>,
        method: &str,
        args: &[Expr],
        block: Option<&Expr>,
        // Crystal concurrency lives in fibers; no async syntax,
        // prefix unused.
        _suspending_prefix: &str,
    ) -> Option<crate::lower::Stmt> {
        use crate::lower::{SendKind, Stmt};
        let kind = crate::lower::classify_controller_send(
            recv, method, args, block, self.ctx.known_models,
        )?;
        Some(match kind {
            SendKind::ParamsAccess => {
                self.state.uses_context = true;
                Stmt::Expr("context.params".to_string())
            }
            SendKind::ParamsIndex { key } => {
                self.state.uses_context = true;
                let s = match &*key.node {
                    ExprNode::Lit { value: Literal::Sym { value: k } } => {
                        format!("context.params[\"{}\"].to_i64", k.as_str())
                    }
                    _ => {
                        let k = self.render_expr(key);
                        format!("context.params[{k}]")
                    }
                };
                Stmt::Expr(s)
            }
            SendKind::ParamsExpect { args: pe_args } => {
                self.state.uses_context = true;
                let s = match pe_args.first().map(|e| &*e.node) {
                    Some(ExprNode::Lit { value: Literal::Sym { value: k } }) => {
                        format!("context.params[\"{}\"].to_i64", k.as_str())
                    }
                    _ => "context.params # TODO: params.expect hash".to_string(),
                };
                Stmt::Expr(s)
            }
            SendKind::ModelNew { class } => Stmt::Expr(format!("{}.new", class.as_str())),
            SendKind::ModelFind { class, id } => {
                let id_s = self.render_expr(id);
                Stmt::Expr(format!("{0}.find({id_s}) || {0}.new", class.as_str()))
            }
            SendKind::QueryChain { target: Some(target), method: cm, args: ca, recv: cr } => {
                let mut out = format!("{}.all", target.as_str());
                let mods = crate::lower::collect_chain_modifiers(cm, ca, cr.as_deref());
                for m in mods {
                    out = apply_cr_chain_modifier(out, m);
                }
                Stmt::Expr(out)
            }
            SendKind::QueryChain { target: None, .. } => Stmt::Expr("[] of String".to_string()),
            SendKind::AssocLookup { target, outer_method } => match outer_method {
                "find" => {
                    let id_s = args.first().map(|a| self.render_expr(a))
                        .unwrap_or_else(|| "0_i64".to_string());
                    Stmt::Expr(format!("{0}.find({id_s}) || {0}.new", target.as_str()))
                }
                _ => Stmt::Expr(format!("{}.new", target.as_str())),
            },
            SendKind::BangStrip { recv, stripped_method, args: bs_args } => {
                let recv_s = self.render_expr(recv);
                if bs_args.is_empty() {
                    Stmt::Expr(format!("{recv_s}.{stripped_method}"))
                } else {
                    let args_s: Vec<String> =
                        bs_args.iter().map(|a| self.render_expr(a)).collect();
                    Stmt::Expr(format!("{recv_s}.{stripped_method}({})", args_s.join(", ")))
                }
            }
            SendKind::InstanceUpdate => Stmt::Expr("false".to_string()),
            SendKind::PathOrUrlHelper => {
                let helper = method.strip_suffix("_path").or_else(|| method.strip_suffix("_url"))
                    .unwrap_or(method);
                Stmt::Expr(format!("RouteHelpers.{helper}_path"))
            }
            SendKind::Render { args: r_args } => Stmt::Response(self.render_cr_render(r_args)),
            SendKind::RedirectTo { args: r_args } => Stmt::Response(self.render_cr_redirect(r_args)),
            SendKind::Head { args: h_args } => {
                let status = h_args.first().and_then(|a| match &*a.node {
                    ExprNode::Lit { value: Literal::Sym { value: s } } =>
                        Some(crate::lower::status_sym_to_code(s.as_str())),
                    ExprNode::Lit { value: Literal::Int { value: n } } => Some(*n as u16),
                    _ => None,
                }).unwrap_or(200);
                Stmt::Response(format!(
                    "Roundhouse::Http::ActionResponse.new(status: {status})"
                ))
            }
            SendKind::RespondToBlock { .. }
            | SendKind::FormatHtml { .. }
            | SendKind::FormatJson => Stmt::Expr(
                "Roundhouse::Http::ActionResponse.new # unreachable: respond_to not normalized".to_string(),
            ),
        })
    }
}

impl<'a> CrEmitter<'a> {
    fn render_cr_render(&mut self, args: &[Expr]) -> String {
        let response_ty = "Roundhouse::Http::ActionResponse";
        if let Some(first) = args.first() {
            if let ExprNode::Lit { value: Literal::Sym { value: sym } } = &*first.node {
                let view_fn = cr_view_fn(self.ctx.model_class, sym.as_str());
                let arg = self.state.last_local.clone().unwrap_or_else(|| "nil".to_string());
                let body_part = format!("body: Views.{view_fn}({arg})");
                return match crate::lower::extract_status_from_kwargs(&args[1..]) {
                    Some(status) => format!("{response_ty}.new(status: {status}, {body_part})"),
                    None => format!("{response_ty}.new({body_part})"),
                };
            }
            let body_s = self.render_expr(first);
            return format!("{response_ty}.new(body: {body_s})");
        }
        format!("{response_ty}.new")
    }

    fn render_cr_redirect(&mut self, args: &[Expr]) -> String {
        let response_ty = "Roundhouse::Http::ActionResponse";
        let Some(first) = args.first() else {
            return format!("{response_ty}.new(status: 303)");
        };
        let loc = self.render_expr(first);
        let status = crate::lower::extract_status_from_kwargs(&args[1..]).unwrap_or(303);
        if is_bare_cr_ident(&loc) {
            let id_access = format!("{loc}.id");
            return format!(
                "{response_ty}.new(status: {status}, location: RouteHelpers.{loc}_path({id_access}))",
            );
        }
        format!("{response_ty}.new(status: {status}, location: {loc})")
    }
}

fn is_bare_cr_ident(s: &str) -> bool {
    let bytes = s.as_bytes();
    if bytes.is_empty() { return false; }
    let first = bytes[0];
    if !(first.is_ascii_lowercase() || first == b'_') { return false; }
    bytes.iter().all(|&b| b.is_ascii_alphanumeric() || b == b'_')
}


/// Map a model class name + view action (`"Article" + "Show"`) to
/// the Crystal view fn name (`render_articles_show`). Still used by
/// the controller template-per-action emit to reference views.
fn cr_view_fn(model_class: &str, suffix: &str) -> String {
    let plural = crate::naming::pluralize_snake(model_class);
    format!("render_{plural}_{}", suffix.to_lowercase())
}
