//! Crystal fixture emit — `spec/fixtures/<table>.cr` per fixture set
//! plus the `spec/fixtures.cr` lookup helper.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use super::ty::crystal_literal_for;

// Fixtures + specs ----------------------------------------------------

/// Emit one fixture file as `spec/fixtures/<table>.cr` — a `Fixtures::X`
/// module with one `self.<label>` accessor per fixture record. IDs
/// assigned in insertion order (1..N), matching the Rust emitter.
pub(super) fn emit_crystal_fixture(lowered: &crate::lower::LoweredFixture) -> EmittedFile {
    let fixture_name = lowered.name.as_str();
    let class_name = lowered.class.0.as_str();
    let module_name = crate::naming::camelize(fixture_name);

    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "require \"../../src/app\"").unwrap();
    writeln!(s, "require \"../fixtures\"").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "module Fixtures").unwrap();
    writeln!(s, "  module {module_name}").unwrap();

    // `_load_all` — called from Fixtures.setup. Builds each record
    // through the model's `save` (so validations apply), captures
    // the AUTOINCREMENT id, registers it with the shared lookup map.
    writeln!(s, "    def self._load_all").unwrap();
    for record in &lowered.records {
        let label = record.label.as_str();
        writeln!(s, "      record = {class_name}.new").unwrap();
        for field in &record.fields {
            let col = field.column.as_str();
            let val = match &field.value {
                crate::lower::LoweredFixtureValue::Literal { ty, raw } => {
                    crystal_literal_for(raw, ty)
                }
                crate::lower::LoweredFixtureValue::FkLookup {
                    target_fixture,
                    target_label,
                } => format!(
                    "Fixtures.fixture_id({:?}, {:?})",
                    target_fixture.as_str(),
                    target_label.as_str(),
                ),
            };
            writeln!(s, "      record.{col} = {val}").unwrap();
        }
        writeln!(
            s,
            "      raise \"fixture {fixture_name}/{label} failed to save\" unless record.save",
        )
        .unwrap();
        writeln!(
            s,
            "      Fixtures::FIXTURE_IDS[{{{fixture_name:?}, {label:?}}}] = record.id",
        )
        .unwrap();
    }
    writeln!(s, "    end").unwrap();

    // Named getters — `Fixtures::Articles.one` reads the record this
    // thread's `_load_all` inserted. A nil `find` means the spec's
    // before_each didn't fire.
    for record in &lowered.records {
        let label = record.label.as_str();
        writeln!(s).unwrap();
        writeln!(s, "    def self.{label} : {class_name}").unwrap();
        writeln!(
            s,
            "      id = Fixtures.fixture_id({fixture_name:?}, {label:?})",
        )
        .unwrap();
        writeln!(
            s,
            "      {class_name}.find(id).not_nil!"
        )
        .unwrap();
        writeln!(s, "    end").unwrap();
    }
    writeln!(s, "  end").unwrap();
    writeln!(s, "end").unwrap();

    EmittedFile {
        path: PathBuf::from(format!("spec/fixtures/{fixture_name}.cr")),
        content: s,
    }
}

/// `spec/fixtures.cr` — top-level `Fixtures` module that owns the
/// `(fixture_name, label) → id` lookup and the `setup` entrypoint
/// every spec's `before_each` calls. Per-class submodules reopen
/// `Fixtures` in `spec/fixtures/<table>.cr`.
pub(super) fn emit_fixtures_helper(lowered: &crate::lower::LoweredFixtureSet) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "require \"../src/app\"").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "module Fixtures").unwrap();
    writeln!(s, "  FIXTURE_IDS = {{}} of {{String, String}} => Int64").unwrap();
    writeln!(s).unwrap();
    writeln!(
        s,
        "  # Per-spec entry point. Opens a fresh :memory: SQLite\n  # connection, runs the schema DDL, and loads every fixture in\n  # declaration order. Idempotent across repeat calls.",
    )
    .unwrap();
    writeln!(s, "  def self.setup").unwrap();
    writeln!(
        s,
        "    Roundhouse::Db.setup_test_db(Roundhouse::SchemaSQL::CREATE_TABLES)"
    )
    .unwrap();
    writeln!(s, "    FIXTURE_IDS.clear").unwrap();
    for f in &lowered.fixtures {
        let mod_name = crate::naming::camelize(f.name.as_str());
        writeln!(s, "    {mod_name}._load_all").unwrap();
    }
    writeln!(s, "  end").unwrap();
    writeln!(s).unwrap();
    writeln!(
        s,
        "  def self.fixture_id(fixture : String, label : String) : Int64",
    )
    .unwrap();
    writeln!(s, "    FIXTURE_IDS[{{fixture, label}}]").unwrap();
    writeln!(s, "  end").unwrap();
    writeln!(s, "end").unwrap();
    EmittedFile {
        path: PathBuf::from("spec/fixtures.cr"),
        content: s,
    }
}
