//! `src/importmap.cr` emission — `PINS` constant from importmap.rb.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use crate::App;

/// Emit `src/importmap.cr` — a `PINS` constant of `(name, path)`
/// tuples ingested from `config/importmap.rb`.
pub(super) fn emit_cr_importmap(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "module Importmap").unwrap();
    writeln!(s, "  PINS = [").unwrap();
    if let Some(importmap) = &app.importmap {
        for pin in &importmap.pins {
            writeln!(s, "    {{ {:?}, {:?} }},", pin.name, pin.path).unwrap();
        }
    }
    writeln!(s, "  ] of Tuple(String, String)").unwrap();
    writeln!(s, "end").unwrap();
    EmittedFile {
        path: PathBuf::from("src/importmap.cr"),
        content: s,
    }
}
