//! `src/main.cr` emission — runtime server entry point.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use crate::App;

/// Emit `src/main.cr` — the server entry point. `shard.yml`'s
/// `main:` points here; test specs require `./app` directly for
/// type defs without triggering the `Server.start` call.
pub(super) fn emit_cr_main(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "require \"./app\"").unwrap();
    writeln!(s).unwrap();
    // Register partial renderers for any model whose plural
    // resource has a scaffold partial (`_<singular>.html.erb`).
    // Cable's broadcast_*_to resolves the partial by model class
    // name through this registry. Only register partials whose
    // singular matches a known model class — `_form.html.erb` is
    // a view-only partial, not a model.
    let known_model_names: std::collections::BTreeSet<String> = app
        .models
        .iter()
        .map(|m| m.name.0.as_str().to_string())
        .collect();
    let mut registered: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
    for v in &app.views {
        let name = v.name.as_str();
        if let Some((dir, base)) = name.rsplit_once('/') {
            if let Some(singular) = base.strip_prefix('_') {
                let class = crate::naming::camelize(singular);
                if !known_model_names.contains(&class) {
                    continue;
                }
                if registered.insert(class.clone()) {
                    let fn_name = format!("render_{}_{singular}", dir);
                    writeln!(
                        s,
                        "Roundhouse::Cable.register_partial({class:?}, ->(id : Int64) {{",
                    )
                    .unwrap();
                    writeln!(s, "  record = {class}.find(id)").unwrap();
                    writeln!(s, "  record ? Views.{fn_name}(record) : \"\"").unwrap();
                    writeln!(s, "}})").unwrap();
                }
            }
        }
    }
    writeln!(s).unwrap();
    let has_layout = app
        .views
        .iter()
        .any(|v| v.name.as_str() == "layouts/application");
    let layout_arg = if has_layout {
        "layout: ->{ Views.render_layouts_application(\"\") },"
    } else {
        ""
    };
    writeln!(
        s,
        "Roundhouse::Server.start(schema_sql: Roundhouse::SchemaSQL::CREATE_TABLES, {layout_arg})"
    )
    .unwrap();
    EmittedFile {
        path: PathBuf::from("src/main.cr"),
        content: s,
    }
}
