//! Model emission — `class Foo` with typed properties, validations,
//! persistence, and broadcaster glue. Bundles everything that lands in
//! `src/models.cr`.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use super::expr::emit_body;
use super::ty::{crystal_default, crystal_ty};
use crate::App;
use crate::dialect::{MethodDef, Model};
use crate::expr::{Expr, ExprNode, Literal};
use crate::ident::Symbol;
use crate::ty::Ty;

pub(super) fn emit_models(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    for (i, model) in app.models.iter().enumerate() {
        if i > 0 {
            writeln!(s).unwrap();
        }
        emit_model(&mut s, model, app);
    }
    EmittedFile { path: PathBuf::from("src/models.cr"), content: s }
}

pub(super) fn emit_model(out: &mut String, model: &Model, app: &App) {
    let name = model.name.0.as_str();
    writeln!(out, "class {name}").unwrap();
    for (field, ty) in &model.attributes.fields {
        writeln!(
            out,
            "  property {} : {} = {}",
            field,
            crystal_ty(ty),
            crystal_default(ty),
        )
        .unwrap();
    }
    // Validation-error state — views read `article.errors.any?` +
    // `error_messages_for(article.errors, …)`. Default empty;
    // populated by a failed `save` (below).
    if !model.attributes.fields.is_empty() {
        writeln!(
            out,
            "  property errors : Array(Roundhouse::ValidationError) = [] of Roundhouse::ValidationError",
        )
        .unwrap();
    }
    for method in model.methods() {
        writeln!(out).unwrap();
        emit_model_method(out, method);
    }
    let lowered = crate::lower::lower_validations(model);
    if !lowered.is_empty() {
        writeln!(out).unwrap();
        emit_validate_method(out, &lowered);
    }
    // Skip persistence for abstract base classes (no columns beyond
    // maybe an `id`) — ApplicationRecord et al. have nothing to save.
    let has_table = model
        .attributes
        .fields
        .keys()
        .any(|k| k.as_str() != "id");
    if has_table {
        writeln!(out).unwrap();
        let broadcasts = crate::lower::lower_broadcasts(model);
        emit_persistence_methods_cr(
            out,
            model,
            !lowered.is_empty(),
            app,
            !broadcasts.is_empty(),
        );
        if !broadcasts.is_empty() {
            let lp = crate::lower::lower_persistence(model, app);
            emit_cr_broadcaster_methods(
                out,
                lp.class.0.as_str(),
                lp.table.as_str(),
                &broadcasts,
            );
        }
    }
    writeln!(out, "end").unwrap();
}

// ── Broadcaster emission ────────────────────────────────────────

pub(super) fn emit_cr_broadcaster_methods(
    out: &mut String,
    class: &str,
    table: &str,
    decls: &crate::lower::LoweredBroadcasts,
) {
    writeln!(out).unwrap();
    writeln!(out, "  def _broadcast_after_save : Nil").unwrap();
    if decls.save.is_empty() {
        writeln!(out, "    nil").unwrap();
    } else {
        for b in &decls.save {
            emit_cr_one_broadcast_call(out, class, table, b);
        }
    }
    writeln!(out, "  end").unwrap();

    writeln!(out).unwrap();
    writeln!(out, "  def _broadcast_after_delete : Nil").unwrap();
    if decls.destroy.is_empty() {
        writeln!(out, "    nil").unwrap();
    } else {
        for b in &decls.destroy {
            emit_cr_one_broadcast_call(out, class, table, b);
        }
    }
    writeln!(out, "  end").unwrap();
}

pub(super) fn emit_cr_one_broadcast_call(
    out: &mut String,
    class: &str,
    table: &str,
    b: &crate::lower::LoweredBroadcast,
) {
    let channel = cr_render_broadcast_expr(&b.channel, b.self_param.as_ref());
    let target = b
        .target
        .as_ref()
        .map(|t| cr_render_broadcast_expr(t, b.self_param.as_ref()))
        .unwrap_or_else(|| "\"\"".to_string());
    if let Some(assoc) = &b.on_association {
        let var = assoc.name.as_str();
        let target_class = assoc.target_class.as_str();
        let target_table = assoc.target_table.as_str();
        let fk = assoc.foreign_key.as_str();
        writeln!(out, "    {var} = {target_class}.find({fk})").unwrap();
        writeln!(out, "    if {var}").unwrap();
        if b.action == crate::lower::BroadcastAction::Remove {
            writeln!(
                out,
                "      Roundhouse::Cable.broadcast_remove_to({target_table:?}, {var}.id, {channel}, {target})",
            )
            .unwrap();
        } else {
            let func = cr_action_fn(b.action);
            writeln!(
                out,
                "      Roundhouse::Cable.{func}({target_table:?}, {var}.id, {target_class:?}, {channel}, {target})",
            )
            .unwrap();
        }
        writeln!(out, "    end").unwrap();
        return;
    }
    if b.action == crate::lower::BroadcastAction::Remove {
        writeln!(
            out,
            "    Roundhouse::Cable.broadcast_remove_to({table:?}, id, {channel}, {target})",
        )
        .unwrap();
    } else {
        let func = cr_action_fn(b.action);
        writeln!(
            out,
            "    Roundhouse::Cable.{func}({table:?}, id, {class:?}, {channel}, {target})",
        )
        .unwrap();
    }
}

pub(super) fn cr_action_fn(action: crate::lower::BroadcastAction) -> &'static str {
    match action {
        crate::lower::BroadcastAction::Prepend => "broadcast_prepend_to",
        crate::lower::BroadcastAction::Append => "broadcast_append_to",
        crate::lower::BroadcastAction::Replace => "broadcast_replace_to",
        crate::lower::BroadcastAction::Remove => "broadcast_remove_to",
    }
}

pub(super) fn cr_render_broadcast_expr(expr: &Expr, self_param: Option<&Symbol>) -> String {
    let p = self_param.map(|s| s.as_str());
    match &*expr.node {
        ExprNode::Lit { value: Literal::Str { value } } => format!("{value:?}"),
        ExprNode::Lit { value: Literal::Int { value } } => format!("{value}"),
        ExprNode::Var { name, .. } => {
            if let Some(pname) = p {
                let stripped = pname.strip_prefix('_').unwrap_or(pname);
                if name.as_str() == pname || name.as_str() == stripped {
                    return "self".to_string();
                }
            }
            name.as_str().to_string()
        }
        ExprNode::Send { recv: Some(r), method, .. } => {
            let recv_s = cr_render_broadcast_expr(r, self_param);
            format!("{recv_s}.{}", method.as_str())
        }
        ExprNode::StringInterp { parts } => {
            use crate::expr::InterpPart;
            let mut out = String::from("\"");
            for part in parts {
                match part {
                    InterpPart::Text { value } => {
                        for c in value.chars() {
                            match c {
                                '"' => out.push_str("\\\""),
                                '\\' => out.push_str("\\\\"),
                                '\n' => out.push_str("\\n"),
                                '#' => out.push_str("\\#"),
                                _ => out.push(c),
                            }
                        }
                    }
                    InterpPart::Expr { expr } => {
                        out.push_str("#{");
                        out.push_str(&cr_render_broadcast_expr(expr, self_param));
                        out.push('}');
                    }
                }
            }
            out.push('"');
            out
        }
        _ => "nil".to_string(),
    }
}

/// Render save/destroy/count/find for a model against the test
/// connection. SQL strings come from `LoweredPersistence`; per-target
/// concerns are placeholder dialect (`?N` → `?`) and the crystal-db
/// API shape (exec/scalar/query_one? with block hydration).
pub(super) fn emit_persistence_methods_cr(
    out: &mut String,
    model: &Model,
    has_validate: bool,
    app: &App,
    has_broadcasts: bool,
) {
    let lp = crate::lower::lower_persistence(model, app);
    let class = lp.class.0.as_str();

    let insert_sql = positional_placeholders(&lp.insert_sql);
    let update_sql = positional_placeholders(&lp.update_sql);
    let delete_sql = positional_placeholders(&lp.delete_sql);
    let select_by_id_sql = positional_placeholders(&lp.select_by_id_sql);
    let count_sql = lp.count_sql.clone(); // no placeholders

    let non_id_args: Vec<String> = lp
        .non_id_columns
        .iter()
        .map(|s| s.as_str().to_string())
        .collect();

    // ----- save -----
    writeln!(out, "  def save : Bool").unwrap();
    if has_validate {
        writeln!(out, "    errs = validate").unwrap();
        writeln!(out, "    unless errs.empty?").unwrap();
        writeln!(out, "      @errors = errs").unwrap();
        writeln!(out, "      return false").unwrap();
        writeln!(out, "    end").unwrap();
        writeln!(out, "    @errors = [] of Roundhouse::ValidationError").unwrap();
    }
    for check in &lp.belongs_to_checks {
        let fk = check.foreign_key.as_str();
        let target = check.target_class.0.as_str();
        writeln!(
            out,
            "    return false if {fk} == 0_i64 || {target}.find({fk}).nil?",
        )
        .unwrap();
    }
    writeln!(out, "    db = Roundhouse::Db.conn").unwrap();
    writeln!(out, "    if id == 0_i64").unwrap();
    writeln!(
        out,
        "      result = db.exec({insert_sql:?}, {})",
        non_id_args.join(", "),
    )
    .unwrap();
    writeln!(out, "      @id = result.last_insert_id").unwrap();
    writeln!(out, "    else").unwrap();
    writeln!(
        out,
        "      db.exec({update_sql:?}, {}, id)",
        non_id_args.join(", "),
    )
    .unwrap();
    writeln!(out, "    end").unwrap();
    if has_broadcasts {
        writeln!(out, "    _broadcast_after_save").unwrap();
    }
    writeln!(out, "    true").unwrap();
    writeln!(out, "  end").unwrap();

    // ----- destroy -----
    writeln!(out).unwrap();
    writeln!(out, "  def destroy").unwrap();
    for dc in &lp.dependent_children {
        let child_class = dc.child_class.0.as_str();
        let child_select = positional_placeholders(&dc.select_by_parent_sql);
        writeln!(out, "    dependents = [] of {child_class}").unwrap();
        writeln!(
            out,
            "    Roundhouse::Db.conn.query_all({child_select:?}, id) do |rs|"
        )
        .unwrap();
        writeln!(out, "      record = {child_class}.new").unwrap();
        for col in &dc.child_columns {
            let col_name = col.as_str();
            let ty = cr_rs_reader_type(col_name);
            writeln!(out, "      record.{col_name} = rs.read({ty})").unwrap();
        }
        writeln!(out, "      dependents << record").unwrap();
        writeln!(out, "    end").unwrap();
        writeln!(out, "    dependents.each(&.destroy)").unwrap();
    }
    writeln!(
        out,
        "    Roundhouse::Db.conn.exec({delete_sql:?}, id)",
    )
    .unwrap();
    if has_broadcasts {
        writeln!(out, "    _broadcast_after_delete").unwrap();
    }
    writeln!(out, "  end").unwrap();

    // ----- count -----
    writeln!(out).unwrap();
    writeln!(out, "  def self.count : Int64").unwrap();
    writeln!(
        out,
        "    Roundhouse::Db.conn.scalar({count_sql:?}).as(Int64)",
    )
    .unwrap();
    writeln!(out, "  end").unwrap();

    // ----- find -----
    writeln!(out).unwrap();
    writeln!(out, "  def self.find(id : Int64) : {class}?").unwrap();
    writeln!(
        out,
        "    Roundhouse::Db.conn.query_one?({select_by_id_sql:?}, id) do |rs|",
    )
    .unwrap();
    writeln!(out, "      record = {class}.new").unwrap();
    for col in &lp.columns {
        let col_name = col.as_str();
        let ty = cr_rs_reader_type_for(model, col_name);
        writeln!(out, "      record.{col_name} = rs.read({ty})").unwrap();
    }
    writeln!(out, "      record").unwrap();
    writeln!(out, "    end").unwrap();
    writeln!(out, "  end").unwrap();

    // ----- all -----
    writeln!(out).unwrap();
    let select_all_sql = &lp.select_all_sql;
    writeln!(out, "  def self.all : Array({class})").unwrap();
    writeln!(out, "    records = [] of {class}").unwrap();
    writeln!(
        out,
        "    Roundhouse::Db.conn.query_all({select_all_sql:?}) do |rs|"
    )
    .unwrap();
    writeln!(out, "      record = {class}.new").unwrap();
    for col in &lp.columns {
        let col_name = col.as_str();
        let ty = cr_rs_reader_type_for(model, col_name);
        writeln!(out, "      record.{col_name} = rs.read({ty})").unwrap();
    }
    writeln!(out, "      records << record").unwrap();
    writeln!(out, "    end").unwrap();
    writeln!(out, "    records").unwrap();
    writeln!(out, "  end").unwrap();

    // ----- last -----
    writeln!(out).unwrap();
    let last_sql = format!("{select_all_sql} ORDER BY id DESC LIMIT 1");
    writeln!(out, "  def self.last : {class}?").unwrap();
    writeln!(
        out,
        "    Roundhouse::Db.conn.query_one?({last_sql:?}) do |rs|"
    )
    .unwrap();
    writeln!(out, "      record = {class}.new").unwrap();
    for col in &lp.columns {
        let col_name = col.as_str();
        let ty = cr_rs_reader_type_for(model, col_name);
        writeln!(out, "      record.{col_name} = rs.read({ty})").unwrap();
    }
    writeln!(out, "      record").unwrap();
    writeln!(out, "    end").unwrap();
    writeln!(out, "  end").unwrap();

    // ----- reload -----
    writeln!(out).unwrap();
    writeln!(out, "  def reload : self").unwrap();
    writeln!(out, "    fresh = {class}.find(id)").unwrap();
    writeln!(out, "    return self if fresh.nil?").unwrap();
    for col in &lp.columns {
        let col_name = col.as_str();
        writeln!(out, "    @{col_name} = fresh.{col_name}").unwrap();
    }
    writeln!(out, "    self").unwrap();
    writeln!(out, "  end").unwrap();
}

/// SQLite numbered placeholders (`?1`, `?2`) → crystal-db positional
/// (`?`). Same table, same semantics, different wire syntax — a
/// driver-level quirk we absorb at emit time. Keyed on `?` + digit
/// run; non-placeholder `?`s pass through.
pub(super) fn positional_placeholders(sql: &str) -> String {
    let mut out = String::new();
    let chars: Vec<char> = sql.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        if chars[i] == '?' {
            out.push('?');
            i += 1;
            while i < chars.len() && chars[i].is_ascii_digit() {
                i += 1;
            }
        } else {
            out.push(chars[i]);
            i += 1;
        }
    }
    out
}

/// Crystal reader type for a struct field during cascade hydration.
/// Uses the model's declared type when available; defaults to
/// Int64/String by column-name heuristic otherwise (only happens when
/// a LoweredPersistence DependentChild carries columns whose owning
/// model isn't on hand in this callsite).
pub(super) fn cr_rs_reader_type(col_name: &str) -> &'static str {
    match col_name {
        "id" => "Int64",
        _ if col_name.ends_with("_id") => "Int64",
        "created_at" | "updated_at" => "Time",
        _ => "String",
    }
}

pub(super) fn cr_rs_reader_type_for(model: &Model, col_name: &str) -> String {
    if let Some(ty) = model
        .attributes
        .fields
        .iter()
        .find(|(k, _)| k.as_str() == col_name)
        .map(|(_, v)| v)
    {
        match ty {
            Ty::Int => "Int64".to_string(),
            Ty::Float => "Float64".to_string(),
            Ty::Bool => "Bool".to_string(),
            Ty::Str | Ty::Sym => "String".to_string(),
            Ty::Class { id, .. } if id.0.as_str() == "Time" => "Time".to_string(),
            _ => "String".to_string(),
        }
    } else {
        cr_rs_reader_type(col_name).to_string()
    }
}

pub(super) fn emit_validate_method(
    out: &mut String,
    validations: &[crate::lower::LoweredValidation],
) {
    writeln!(out, "  def validate : Array(Roundhouse::ValidationError)").unwrap();
    writeln!(out, "    errors = [] of Roundhouse::ValidationError").unwrap();
    for lv in validations {
        for check in &lv.checks {
            emit_check_inline_cr(out, lv.attribute.as_str(), check);
        }
    }
    writeln!(out, "    errors").unwrap();
    writeln!(out, "  end").unwrap();
}

pub(super) fn emit_check_inline_cr(out: &mut String, attr: &str, check: &crate::lower::Check) {
    use crate::lower::Check;
    let msg = check.default_message();
    let push = |cond: &str| -> String {
        format!(
            "    if {cond}\n      errors << Roundhouse::ValidationError.new({attr:?}, {msg:?})\n    end",
        )
    };
    let block = match check {
        Check::Presence => push(&format!("{attr}.empty?")),
        Check::Absence => push(&format!("!{attr}.empty?")),
        Check::MinLength { n } => push(&format!("{attr}.size < {n}")),
        Check::MaxLength { n } => push(&format!("{attr}.size > {n}")),
        Check::GreaterThan { threshold } => push(&format!("{attr} <= {threshold}")),
        Check::LessThan { threshold } => push(&format!("{attr} >= {threshold}")),
        Check::OnlyInteger => {
            format!("    # OnlyInteger on {attr:?} — enforced by Crystal's type system")
        }
        Check::Inclusion { values } => {
            let parts: Vec<String> = values.iter().map(inclusion_value_to_cr).collect();
            push(&format!("![{}].includes?({attr})", parts.join(", ")))
        }
        Check::Format { pattern } => {
            format!(
                "    # TODO: Format check on {attr:?} requires runtime regex ({pattern:?})"
            )
        }
        Check::Uniqueness { .. } => format!(
            "    # TODO: Uniqueness on {attr:?} requires DB access at runtime"
        ),
        Check::Custom { method } => format!("    {method}(errors)"),
    };
    writeln!(out, "{block}").unwrap();
}

pub(super) fn inclusion_value_to_cr(v: &crate::lower::InclusionValue) -> String {
    use crate::lower::InclusionValue;
    match v {
        InclusionValue::Str { value } => format!("{value:?}"),
        InclusionValue::Int { value } => format!("{value}_i64"),
        InclusionValue::Float { value } => {
            let s = value.to_string();
            if s.contains('.') { format!("{s}_f64") } else { format!("{s}.0_f64") }
        }
        InclusionValue::Bool { value } => value.to_string(),
    }
}

pub(super) fn emit_model_method(out: &mut String, m: &MethodDef) {
    let name = m.name.as_str();
    let ret = m.body.ty.clone().unwrap_or(Ty::Nil);
    let ret_annot = format!(" : {}", crystal_ty(&ret));
    let receiver = match m.receiver {
        crate::dialect::MethodReceiver::Instance => "",
        crate::dialect::MethodReceiver::Class => "self.",
    };
    let params = if m.params.is_empty() {
        String::new()
    } else {
        let ps: Vec<String> = m.params.iter().map(|p| p.to_string()).collect();
        format!("({})", ps.join(", "))
    };
    writeln!(out, "  def {receiver}{name}{params}{ret_annot}").unwrap();
    let body = emit_body(&m.body);
    for line in body.lines() {
        writeln!(out, "    {line}").unwrap();
    }
    writeln!(out, "  end").unwrap();
}
