//! Route emission — `src/routes.cr` (Router.add registrations) and
//! `src/route_helpers.cr` (`<name>_path` functions).

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use crate::App;

// Routes ---------------------------------------------------------------

pub(super) fn emit_routes(app: &App) -> EmittedFile {
    let flat = crate::lower::flatten_routes(app);
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "require \"./http\"").unwrap();
    writeln!(s, "require \"./controllers\"").unwrap();
    writeln!(s).unwrap();
    for r in &flat {
        let action_str = r.action.as_str();
        let handler_method = if action_str == "new" { "new_action" } else { action_str };
        writeln!(
            s,
            "Roundhouse::Http::Router.add({:?}, {:?}, ->(ctx : Roundhouse::Http::ActionContext) {{ {}Actions.{}(ctx) }})",
            http_verb_cr(&r.method),
            r.path,
            r.controller.0,
            handler_method,
        )
        .unwrap();
    }
    EmittedFile { path: PathBuf::from("src/routes.cr"), content: s }
}

// --- Pass-2 route helpers + views + router --------------------------------

/// `src/route_helpers.cr` — `def self.<name>_path(...) : String` per
/// entry in the flat route table. Mirrors `src/route_helpers.rs`/.ts
/// in shape; Crystal naming stays snake_case.
pub(super) fn emit_route_helpers_cr(app: &App) -> EmittedFile {
    let flat = crate::lower::flatten_routes(app);
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "module RouteHelpers").unwrap();
    let mut seen: std::collections::BTreeSet<(String, usize)> =
        std::collections::BTreeSet::new();
    for r in &flat {
        if !seen.insert((r.as_name.clone(), r.path_params.len())) {
            continue;
        }
        let params_sig: Vec<String> = r
            .path_params
            .iter()
            .map(|p| format!("{p} : Int64"))
            .collect();
        let sig = if params_sig.is_empty() {
            String::new()
        } else {
            format!("({})", params_sig.join(", "))
        };
        let path_expr = if r.path_params.is_empty() {
            format!("{:?}", r.path)
        } else {
            let mut out = String::from("\"");
            for part in r.path.split('/') {
                if part.is_empty() {
                    continue;
                }
                out.push('/');
                if let Some(name) = part.strip_prefix(':') {
                    out.push_str(&format!("#{{{}}}", name));
                } else {
                    out.push_str(part);
                }
            }
            out.push('"');
            out
        };
        writeln!(s, "  def self.{}_path{sig} : String", r.as_name).unwrap();
        writeln!(s, "    {path_expr}").unwrap();
        writeln!(s, "  end").unwrap();
    }
    writeln!(s, "end").unwrap();
    EmittedFile {
        path: PathBuf::from("src/route_helpers.cr"),
        content: s,
    }
}

/// Map `dialect::HttpMethod` to the Crystal runtime's uppercase
/// method-string form used when registering routes.
pub(super) fn http_verb_cr(m: &crate::dialect::HttpMethod) -> &'static str {
    use crate::dialect::HttpMethod;
    match m {
        HttpMethod::Get => "GET",
        HttpMethod::Post => "POST",
        HttpMethod::Put => "PUT",
        HttpMethod::Patch => "PATCH",
        HttpMethod::Delete => "DELETE",
        HttpMethod::Head => "HEAD",
        HttpMethod::Options => "OPTIONS",
        HttpMethod::Any => "ANY",
    }
}
