//! `src/schema_sql.cr` emission — wraps the lowered DDL.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use crate::App;

/// `src/schema_sql.cr` — Crystal constant wrapping the target-neutral
/// DDL produced by `emit::shared::schema_sql`. `Roundhouse::Db.setup_test_db`
/// reads it to initialize a fresh :memory: SQLite connection per spec.
pub(super) fn emit_schema_sql(app: &App) -> EmittedFile {
    let ddl = crate::emit::shared::schema_sql::render_schema_sql(&app.schema);
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "module Roundhouse").unwrap();
    writeln!(s, "  module SchemaSQL").unwrap();
    writeln!(s, "    CREATE_TABLES = <<-SQL").unwrap();
    s.push_str(&ddl);
    writeln!(s, "SQL").unwrap();
    writeln!(s, "  end").unwrap();
    writeln!(s, "end").unwrap();
    EmittedFile {
        path: PathBuf::from("src/schema_sql.cr"),
        content: s,
    }
}
