//! `src/schema_sql.cr` emission — wraps the lowered DDL.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use crate::App;

/// `src/schema_sql.cr` — Crystal constant wrapping the target-neutral
/// DDL produced by `lower::lower_schema`. `Roundhouse::Db.setup_test_db`
/// reads it to initialize a fresh :memory: SQLite connection per spec.
pub(super) fn emit_schema_sql(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "module Roundhouse").unwrap();
    writeln!(s, "  module SchemaSQL").unwrap();
    writeln!(s, "    CREATE_TABLES = <<-SQL").unwrap();
    let ddl = crate::lower::lower_schema(&app.schema);
    for line in ddl.lines() {
        writeln!(s, "      {line}").unwrap();
    }
    writeln!(s, "    SQL").unwrap();
    writeln!(s, "  end").unwrap();
    writeln!(s, "end").unwrap();
    EmittedFile {
        path: PathBuf::from("src/schema_sql.cr"),
        content: s,
    }
}
