//! Crystal spec emit — `spec/spec_helper.cr` plus one
//! `spec/models/<name>_spec.cr` per ingested test module. Model tests
//! render through the local `SpecCtx`-driven walker; controller tests
//! delegate to `controller_test::emit_cr_controller_test`.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use super::controller_test::emit_cr_controller_test;
use super::expr::emit_literal;
use crate::App;
use crate::dialect::{Test, TestModule};
use crate::expr::{Expr, ExprNode, LValue, Literal};
use crate::ident::Symbol;

pub(super) fn emit_spec_helper(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "require \"spec\"").unwrap();
    writeln!(s, "require \"../src/app\"").unwrap();
    if !app.fixtures.is_empty() {
        writeln!(s, "require \"./fixtures\"").unwrap();
    }
    for fixture in &app.fixtures {
        writeln!(s, "require \"./fixtures/{}\"", fixture.name).unwrap();
    }
    if !app.fixtures.is_empty() {
        writeln!(s).unwrap();
        // Fresh :memory: DB + reloaded fixtures before every spec,
        // mirroring Rails' transactional-fixture isolation.
        writeln!(s, "Spec.before_each do").unwrap();
        writeln!(s, "  Fixtures.setup").unwrap();
        writeln!(s, "end").unwrap();
    }
    EmittedFile {
        path: PathBuf::from("spec/spec_helper.cr"),
        content: s,
    }
}

pub(super) fn emit_crystal_spec(tm: &TestModule, app: &App) -> EmittedFile {
    // Target class: Article for ArticleTest. Used as the `describe`
    // subject so the spec output reads naturally. For controller
    // tests we use the test-module name as a string instead —
    // Crystal resolves bare-identifier describe subjects at parse
    // time and the controller class isn't required into the spec
    // build yet (Phase 4 skips).
    let is_controller_test = tm.name.0.as_str().ends_with("ControllerTest");
    let subject = if is_controller_test {
        format!("{:?}", tm.name.0.as_str())
    } else {
        tm.target
            .as_ref()
            .map(|c| c.0.as_str().to_string())
            .unwrap_or_else(|| tm.name.0.as_str().to_string())
    };

    let fixture_names: Vec<Symbol> =
        app.fixtures.iter().map(|f| f.name.clone()).collect();
    let known_models: Vec<Symbol> =
        app.models.iter().map(|m| m.name.0.clone()).collect();
    let mut attrs_set: std::collections::BTreeSet<Symbol> =
        std::collections::BTreeSet::new();
    for m in &app.models {
        for attr in m.attributes.fields.keys() {
            attrs_set.insert(attr.clone());
        }
    }
    let model_attrs: Vec<Symbol> = attrs_set.into_iter().collect();

    let ctx = SpecCtx {
        app,
        fixture_names: &fixture_names,
        known_models: &known_models,
        model_attrs: &model_attrs,
    };

    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "require \"../spec_helper\"").unwrap();
    if is_controller_test {
        writeln!(s, "require \"../../src/routes\"").unwrap();
        writeln!(s, "require \"../../src/route_helpers\"").unwrap();
        writeln!(s, "require \"../../src/test_support\"").unwrap();
    }
    writeln!(s).unwrap();
    writeln!(s, "describe {subject} do").unwrap();

    let is_controller_test = tm.name.0.as_str().ends_with("ControllerTest");
    for test in &tm.tests {
        if is_controller_test {
            emit_cr_controller_test(&mut s, test, app);
        } else if test_needs_runtime_unsupported_cr(test) {
            writeln!(
                s,
                "  pending {:?} do",
                test.name
            )
            .unwrap();
            writeln!(s, "    # Phase 3: needs persistence runtime").unwrap();
            writeln!(s, "  end").unwrap();
        } else {
            writeln!(s, "  it {:?} do", test.name).unwrap();
            for line in emit_spec_body(&test.body, ctx).lines() {
                writeln!(s, "    {line}").unwrap();
            }
            writeln!(s, "  end").unwrap();
        }
    }

    writeln!(s, "end").unwrap();

    let filename = crate::naming::snake_case(tm.name.0.as_str());
    // spec/models/article_spec.cr from ArticleTest.
    let filename = filename.replace("_test", "_spec");
    EmittedFile {
        path: PathBuf::from(format!("spec/models/{filename}.cr")),
        content: s,
    }
}

/// Context threaded through spec body emission.
#[derive(Clone, Copy)]
pub(super) struct SpecCtx<'a> {
    app: &'a App,
    fixture_names: &'a [Symbol],
    known_models: &'a [Symbol],
    model_attrs: &'a [Symbol],
}

/// Top-level emit for a test body — a `Seq` renders line by line; a
/// single expression renders as one line.
pub(super) fn emit_spec_body(body: &Expr, ctx: SpecCtx) -> String {
    match &*body.node {
        ExprNode::Seq { exprs } if !exprs.is_empty() => exprs
            .iter()
            .map(|e| emit_spec_stmt(e, ctx))
            .collect::<Vec<_>>()
            .join("\n"),
        _ => emit_spec_stmt(body, ctx),
    }
}

pub(super) fn emit_spec_stmt(e: &Expr, ctx: SpecCtx) -> String {
    match &*e.node {
        ExprNode::Assign { target: LValue::Var { name, .. }, value } => {
            format!("{} = {}", name, emit_spec_expr(value, ctx))
        }
        _ => emit_spec_expr(e, ctx),
    }
}

pub(super) fn emit_spec_expr(e: &Expr, ctx: SpecCtx) -> String {
    use crate::expr::InterpPart;
    match &*e.node {
        ExprNode::Lit { value } => emit_literal(value),
        ExprNode::Var { name, .. } => name.to_string(),
        ExprNode::Const { path } => {
            path.iter().map(|s| s.to_string()).collect::<Vec<_>>().join("::")
        }
        ExprNode::Hash { entries, .. } => {
            let parts: Vec<String> = entries
                .iter()
                .map(|(k, v)| {
                    format!("{} => {}", emit_spec_expr(k, ctx), emit_spec_expr(v, ctx))
                })
                .collect();
            format!("{{{}}}", parts.join(", "))
        }
        ExprNode::Array { elements, .. } => {
            let parts: Vec<String> = elements.iter().map(|e| emit_spec_expr(e, ctx)).collect();
            format!("[{}]", parts.join(", "))
        }
        ExprNode::StringInterp { parts } => {
            let mut out = String::from("\"");
            for p in parts {
                match p {
                    InterpPart::Text { value } => out.push_str(value),
                    InterpPart::Expr { expr } => {
                        out.push_str("#{");
                        out.push_str(&emit_spec_expr(expr, ctx));
                        out.push('}');
                    }
                }
            }
            out.push('"');
            out
        }
        ExprNode::Send { recv, method, args, block, .. } => {
            emit_spec_send(recv.as_ref(), method.as_str(), args, block.as_ref(), ctx)
        }
        ExprNode::BoolOp { op, left, right, .. } => {
            use crate::expr::BoolOpKind;
            let op_s = match op {
                BoolOpKind::Or => "||",
                BoolOpKind::And => "&&",
            };
            format!(
                "{} {} {}",
                emit_spec_expr(left, ctx),
                op_s,
                emit_spec_expr(right, ctx)
            )
        }
        ExprNode::Assign { target, value } => {
            // Only in rare inline positions; renders as a Crystal
            // assignment expression.
            let v = emit_spec_expr(value, ctx);
            match target {
                LValue::Var { name, .. } => format!("{name} = {v}"),
                LValue::Ivar { name } => format!("@{name} = {v}"),
                _ => v,
            }
        }
        _ => format!("# TODO: spec emit for {:?}", std::mem::discriminant(&*e.node)),
    }
}

pub(super) fn emit_spec_send(
    recv: Option<&Expr>,
    method: &str,
    args: &[Expr],
    block: Option<&Expr>,
    ctx: SpecCtx,
) -> String {
    let args_s: Vec<String> = args.iter().map(|a| emit_spec_expr(a, ctx)).collect();

    // Fixture accessor: articles(:one) → Fixtures::Articles.one
    if recv.is_none()
        && args.len() == 1
        && ctx.fixture_names.iter().any(|s| s.as_str() == method)
    {
        if let ExprNode::Lit { value: Literal::Sym { value: sym } } = &*args[0].node {
            let module_name = crate::naming::camelize(method);
            return format!("Fixtures::{module_name}.{}", sym.as_str());
        }
    }

    // assert_difference("Class.count", delta) do ... end
    if recv.is_none() && method == "assert_difference" {
        if let Some(body) = block {
            if let Some(count_expr) = args
                .first()
                .and_then(|a| match &*a.node {
                    ExprNode::Lit { value: Literal::Str { value } } => {
                        rewrite_ruby_dot_call_cr(value)
                    }
                    _ => None,
                })
            {
                let delta = args_s.get(1).cloned().unwrap_or_else(|| "1_i64".into());
                let body_s = emit_block_body_cr(body, ctx);
                return format!(
                    "_before = {count_expr}\n    {body_s}\n    ({count_expr} - _before).should eq({delta})"
                );
            }
        }
    }

    // owner.<assoc>.create(hash) / .build(hash) — HasMany rewrite.
    if (method == "create" || method == "build") && args.len() == 1 {
        if let Some(outer_recv) = recv {
            if let ExprNode::Send {
                recv: Some(assoc_recv),
                method: assoc_method,
                args: inner_args,
                ..
            } = &*outer_recv.node
            {
                if inner_args.is_empty() {
                    if let Some(s) = try_emit_assoc_create_cr(
                        assoc_recv,
                        assoc_method.as_str(),
                        args,
                        method,
                        ctx,
                    ) {
                        return s;
                    }
                }
            }
        }
    }

    // Assertion macros → Crystal spec's `should` matchers.
    // Ruby's `assert_equal expected, actual` → `actual.should eq(expected)`.
    if recv.is_none() {
        match (method, args_s.len()) {
            ("assert_equal", 2) => {
                return format!("{}.should eq({})", args_s[1], args_s[0]);
            }
            ("assert_not_equal", 2) => {
                return format!("{}.should_not eq({})", args_s[1], args_s[0]);
            }
            ("assert_not", 1) => {
                return format!("{}.should be_false", args_s[0]);
            }
            ("assert", 1) => {
                return format!("{}.should be_true", args_s[0]);
            }
            ("assert_nil", 1) => {
                return format!("{}.should be_nil", args_s[0]);
            }
            ("assert_not_nil", 1) => {
                return format!("{}.should_not be_nil", args_s[0]);
            }
            _ => {}
        }
    }

    // `Class.new(hash)` → Crystal requires setting properties after .new.
    // Use `.tap do |r| r.k = v end` pattern when the target is a known
    // model.
    if let Some(r) = recv {
        if method == "new" && args.len() == 1 {
            if let ExprNode::Const { path } = &*r.node {
                if let Some(class_name) = path.last() {
                    if ctx.known_models.iter().any(|s| s == class_name) {
                        if let ExprNode::Hash { entries, .. } = &*args[0].node {
                            let mut lines: Vec<String> =
                                vec![format!("{class_name}.new.tap do |record|")];
                            for (k, v) in entries {
                                if let ExprNode::Lit {
                                    value: Literal::Sym { value: f },
                                } = &*k.node
                                {
                                    lines.push(format!(
                                        "      record.{} = {}",
                                        f.as_str(),
                                        emit_spec_expr(v, ctx)
                                    ));
                                }
                            }
                            lines.push("    end".to_string());
                            return lines.join("\n");
                        }
                    }
                }
            }
        }
    }

    match recv {
        None => {
            if args_s.is_empty() {
                method.to_string()
            } else {
                format!("{}({})", method, args_s.join(", "))
            }
        }
        Some(r) => {
            let recv_s = emit_spec_expr(r, ctx);
            let is_class_call = matches!(&*r.node, ExprNode::Const { .. });
            let sep = if is_class_call { "." } else { "." };
            // Crystal doesn't distinguish field vs method call syntactically
            // (property getters ARE method calls), so we can emit both as
            // `recv.method` regardless — but attribute reads should be
            // bare, no parens.
            let is_attr_read = !is_class_call
                && args_s.is_empty()
                && ctx.model_attrs.iter().any(|s| s.as_str() == method);
            if is_attr_read {
                format!("{recv_s}{sep}{method}")
            } else if args_s.is_empty() {
                // Crystal allows omitting parens for zero-arg calls;
                // keep them off for consistency with Ruby idiom.
                format!("{recv_s}{sep}{method}")
            } else {
                format!("{recv_s}{sep}{method}({})", args_s.join(", "))
            }
        }
    }
}

/// Phase 3 rounded out the Crystal emitter's handling of
/// assert_difference, destroy, Class.count, build/create, and
/// belongs_to existence. Keep the predicate as a future-guard; no
/// real-blog shape currently forces a skip.
pub(super) fn test_needs_runtime_unsupported_cr(_test: &Test) -> bool {
    false
}

/// Parse a Ruby-style `"Class.method"` expression string into Crystal
/// `Class.method` syntax (Crystal uses `.` for both class and instance
/// method calls). Only alphanumeric identifiers on both sides.
pub(super) fn rewrite_ruby_dot_call_cr(expr: &str) -> Option<String> {
    let trimmed = expr.trim();
    let (lhs, rhs) = trimmed.split_once('.')?;
    let is_ident = |s: &str| {
        !s.is_empty()
            && s.chars().next().is_some_and(|c| c.is_alphabetic() || c == '_')
            && s.chars().all(|c| c.is_alphanumeric() || c == '_')
    };
    if !is_ident(lhs) || !is_ident(rhs) {
        return None;
    }
    Some(format!("{lhs}.{rhs}"))
}

/// Render a Ruby block body (a single expression or a Seq) as Crystal
/// spec statements at spec-body indent. Peels one Lambda layer — Ruby
/// `do ... end` lowers to `ExprNode::Lambda` in the IR but translates
/// to plain statements in Crystal.
pub(super) fn emit_block_body_cr(e: &Expr, ctx: SpecCtx) -> String {
    let inner = match &*e.node {
        ExprNode::Lambda { body, .. } => body,
        _ => e,
    };
    match &*inner.node {
        ExprNode::Seq { exprs } if !exprs.is_empty() => exprs
            .iter()
            .map(|s| emit_spec_stmt(s, ctx))
            .collect::<Vec<_>>()
            .join("\n    "),
        _ => emit_spec_stmt(inner, ctx),
    }
}

pub(super) fn try_emit_assoc_create_cr(
    owner: &Expr,
    assoc_name: &str,
    args: &[Expr],
    outer_method: &str,
    ctx: SpecCtx,
) -> Option<String> {
    let resolved = crate::lower::resolve_has_many(
        &Symbol::from(assoc_name),
        owner.ty.as_ref(),
        ctx.app,
    )?;
    let target_class = resolved.target_class.0.as_str();
    let foreign_key = resolved.foreign_key.as_str();

    let owner_s = emit_spec_expr(owner, ctx);
    let hash_entries = match &args.first()?.node.as_ref() {
        ExprNode::Hash { entries, .. } => entries.clone(),
        _ => return None,
    };

    let mut lines: Vec<String> = Vec::new();
    lines.push(format!("{target_class}.new.tap do |record|"));
    lines.push(format!("      record.{foreign_key} = {owner_s}.id"));
    for (k, v) in &hash_entries {
        if let ExprNode::Lit { value: Literal::Sym { value: field_name } } = &*k.node {
            lines.push(format!(
                "      record.{} = {}",
                field_name.as_str(),
                emit_spec_expr(v, ctx),
            ));
        }
    }
    // `.build` returns the unsaved record; `.create` saves it first.
    // Both yield the record so tests can read `.article_id` etc.
    if outer_method == "create" {
        lines.push("      record.save".to_string());
    }
    lines.push("    end".to_string());
    Some(lines.join("\n"))
}

#[allow(dead_code)]
pub(super) fn test_body_uses_unsupported_cr(e: &Expr) -> bool {
    use crate::expr::InterpPart;
    let self_hit = false;
    if self_hit {
        return true;
    }
    match &*e.node {
        ExprNode::Send { recv, args, block, .. } => {
            if let Some(r) = recv {
                if test_body_uses_unsupported_cr(r) {
                    return true;
                }
            }
            for a in args {
                if test_body_uses_unsupported_cr(a) {
                    return true;
                }
            }
            if let Some(b) = block {
                if test_body_uses_unsupported_cr(b) {
                    return true;
                }
            }
        }
        ExprNode::Seq { exprs } | ExprNode::Array { elements: exprs, .. } => {
            for e in exprs {
                if test_body_uses_unsupported_cr(e) {
                    return true;
                }
            }
        }
        ExprNode::Hash { entries, .. } => {
            for (k, v) in entries {
                if test_body_uses_unsupported_cr(k) || test_body_uses_unsupported_cr(v) {
                    return true;
                }
            }
        }
        ExprNode::StringInterp { parts } => {
            for p in parts {
                if let InterpPart::Expr { expr } = p {
                    if test_body_uses_unsupported_cr(expr) {
                        return true;
                    }
                }
            }
        }
        ExprNode::BoolOp { left, right, .. }
        | ExprNode::RescueModifier { expr: left, fallback: right } => {
            if test_body_uses_unsupported_cr(left) || test_body_uses_unsupported_cr(right) {
                return true;
            }
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            if test_body_uses_unsupported_cr(cond)
                || test_body_uses_unsupported_cr(then_branch)
                || test_body_uses_unsupported_cr(else_branch)
            {
                return true;
            }
        }
        ExprNode::Let { value, body, .. } => {
            if test_body_uses_unsupported_cr(value) || test_body_uses_unsupported_cr(body) {
                return true;
            }
        }
        ExprNode::Lambda { body, .. } => {
            if test_body_uses_unsupported_cr(body) {
                return true;
            }
        }
        ExprNode::Assign { value, .. } => {
            if test_body_uses_unsupported_cr(value) {
                return true;
            }
        }
        _ => {}
    }
    false
}
