//! Thin Crystal view emitter — convergence target mirroring the TS
//! `view_thin.rs` pattern. Lowers each View through `view_to_library`
//! to get a canonical `LibraryClass` whose body is in the
//! `io = String.new ; io << ViewHelpers.x(...) ; io` shape, then
//! renders via the standard Crystal `emit_expr` plus a small
//! buffer-accumulate idiom recognizer.
//!
//! Crystal's surface is Ruby-syntax-compatible for nearly every
//! lowered-IR construct — `<<`, `is_a?`, `nil?`, `empty?`, blocks,
//! `Const::Path.method(...)`, all native — so the catalog work
//! that TS needed (snake↔camel rename, predicate dispatch,
//! coercion mapping, …) collapses to almost nothing here. The
//! method body emits as a `String.build do |io| ... end` block:
//! Crystal idiom, equivalent semantics to the lowered shape with
//! the explicit `io = String.new` / trailing `io` collapsed into
//! the block.
//!
//! Activated by `ROUNDHOUSE_CR_VIEW_THIN=1`. Behind a flag while
//! the path is shaken out fixture-by-fixture.

use std::fmt::Write;
use std::path::PathBuf;

use crate::App;
use crate::dialect::{LibraryClass, MethodDef, MethodReceiver};
use crate::expr::{Expr, ExprNode, InterpPart, LValue, Literal, RescueClause};
use crate::ident::Symbol;
use crate::span::Span;

use super::super::EmittedFile;

pub(super) fn emit_views_thin(app: &App) -> Vec<EmittedFile> {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse (thin Crystal view emitter).").unwrap();
    writeln!(s, "require \"./view_helpers\"").unwrap();
    writeln!(s, "require \"./route_helpers\"").unwrap();
    writeln!(s, "require \"./importmap\"").unwrap();
    if !app.models.is_empty() {
        writeln!(s, "require \"./models\"").unwrap();
    }
    writeln!(s).unwrap();
    writeln!(s, "module Views").unwrap();

    let mut emitted: std::collections::BTreeSet<String> =
        std::collections::BTreeSet::new();

    for view in &app.views {
        let mut lc = crate::lower::lower_view_to_library_class(view, app);
        // Crystal-specific Const rewrites:
        //   ViewHelpers → Roundhouse::ViewHelpers (framework lives
        //     under the Roundhouse:: namespace in Crystal).
        //   Views::<Dir>.<action>(...) → Views.render_<dir>_<action>(...)
        //     (existing controller emit calls flat names; aligning
        //     view emit to the same shape avoids per-call rewrites in
        //     controller emit).
        for m in &mut lc.methods {
            m.body = crystal_view_const_rewrite(&m.body);
        }
        emit_view_method(&mut s, view, &lc);
        emitted.insert(view_function_name(view.name.as_str()));
    }

    emit_missing_view_stubs(&mut s, app, &emitted);

    writeln!(s, "end").unwrap();
    vec![EmittedFile {
        path: PathBuf::from("src/views.cr"),
        content: s,
    }]
}

/// Emit one view as a Crystal `def self.<fn_name>(args) : String`
/// inside the surrounding `module Views`. The body wraps the lowered
/// LibraryClass method's middle statements in `String.build do |io|
/// ... end`, dropping the explicit `io = String.new` head and trailing
/// `io` tail (their roles are taken by the block builder).
fn emit_view_method(out: &mut String, view: &crate::dialect::View, lc: &LibraryClass) {
    let fn_name = view_function_name(view.name.as_str());

    let method = lc
        .methods
        .iter()
        .find(|m| matches!(m.receiver, MethodReceiver::Class));
    let Some(method) = method else {
        writeln!(out).unwrap();
        writeln!(out, "  def self.{fn_name} : String").unwrap();
        writeln!(out, "    \"\"").unwrap();
        writeln!(out, "  end").unwrap();
        return;
    };

    let sig = render_params(method);
    writeln!(out).unwrap();
    writeln!(out, "  def self.{fn_name}({sig}) : String").unwrap();
    writeln!(out, "    String.build do |io|").unwrap();
    for line in render_body_inside_string_build(&method.body) {
        writeln!(out, "      {line}").unwrap();
    }
    writeln!(out, "    end").unwrap();
    writeln!(out, "  end").unwrap();
}

/// Render the params from a typed `MethodDef` as a Crystal arg list.
/// Uses the signature (when present) for typed annotations; falls
/// back to untyped param-name only.
fn render_params(m: &MethodDef) -> String {
    use crate::ty::Ty;
    let sig_params: &[crate::ty::Param] = match &m.signature {
        Some(Ty::Fn { params, .. }) => params.as_slice(),
        _ => &[],
    };
    m.params
        .iter()
        .enumerate()
        .map(|(i, p)| {
            let name = p.name.as_str();
            let ty = sig_params.get(i).map(|sp| &sp.ty);
            let type_str = match ty {
                Some(Ty::Class { id, .. }) => format!("{name} : {}", id.0.as_str()),
                Some(Ty::Array { elem }) => match elem.as_ref() {
                    Ty::Class { id, .. } => format!("{name} : Array({})", id.0.as_str()),
                    _ => format!("{name}"),
                },
                Some(Ty::Str) => format!("{name} : String"),
                // `Union<Str, Nil>` (e.g. flash params like `notice`,
                // `alert`) maps to Crystal's nilable `String?` shape.
                Some(Ty::Union { variants })
                    if variants.iter().any(|v| matches!(v, Ty::Nil))
                        && variants.iter().any(|v| matches!(v, Ty::Str)) =>
                {
                    format!("{name} : String?")
                }
                _ => format!("{name}"),
            };
            // Optional params (e.g. `notice`, `alert`) have a `nil`
            // default in the lowered IR — preserve as a Crystal
            // default-arg so callers without the kwarg work
            // (controllers pass only the main record arg).
            if p.default.is_some() {
                format!("{type_str} = nil")
            } else {
                type_str
            }
        })
        .collect::<Vec<_>>()
        .join(", ")
}

/// Render the body's statements inside a `String.build do |io| ... end`
/// block. Drops the `io = String.new` initializer and the trailing
/// bare `io` return — the block builder takes over those roles. All
/// other statements (`io << X`, `if cond`, `each`, etc.) render
/// directly via Crystal's standard `emit_expr` since the lowered IR
/// uses Ruby-syntax-compatible shapes Crystal accepts natively.
fn render_body_inside_string_build(body: &Expr) -> Vec<String> {
    let stmts: Vec<&Expr> = match &*body.node {
        ExprNode::Seq { exprs } => exprs.iter().collect(),
        _ => vec![body],
    };
    let mut out = Vec::new();
    let last_idx = stmts.len().saturating_sub(1);
    for (i, stmt) in stmts.iter().enumerate() {
        // Drop `io = String.new` head — `String.build do |io|` already
        // declares `io` and starts it empty.
        if i == 0 {
            if let ExprNode::Assign { target: LValue::Var { name, .. }, value } = &*stmt.node {
                if name.as_str() == "io" {
                    if let ExprNode::Send { recv: Some(recv), method, args, .. } = &*value.node {
                        if method.as_str() == "new" && args.is_empty() {
                            if let ExprNode::Const { path } = &*recv.node {
                                if path.last().map(|s| s.as_str()) == Some("String") {
                                    continue;
                                }
                            }
                        }
                    }
                    if let ExprNode::Lit { value: Literal::Str { value: s } } = &*value.node {
                        if s.is_empty() {
                            continue;
                        }
                    }
                }
            }
        }
        // Drop trailing bare `io` — the block's value is the built
        // string, so we don't need an explicit return.
        if i == last_idx {
            if let ExprNode::Var { name, .. } = &*stmt.node {
                if name.as_str() == "io" {
                    continue;
                }
            }
        }
        // Render any other stmt via Crystal's standard expr emit.
        // The lowered IR uses constructs Crystal handles natively
        // (Send-with-Const-recv, `<<` on Var, blocks, if/else, each)
        // so almost everything passes through unchanged.
        let line = render_stmt(stmt);
        for inner in line.lines() {
            out.push(inner.to_string());
        }
    }
    out
}

/// Statement-position render. For most nodes, Crystal's `emit_expr`
/// produces a syntactically-correct expression; we just append it as
/// a line. `If` and `each` get block-form rendering so Crystal's
/// indentation reads naturally.
fn render_stmt(stmt: &Expr) -> String {
    match &*stmt.node {
        // `if cond ... else ... end` — Crystal block-form.
        ExprNode::If { cond, then_branch, else_branch } => {
            let cond_s = super::expr::emit_expr(cond);
            let mut out = format!("if {cond_s}\n");
            for line in render_body_lines(then_branch) {
                out.push_str("  ");
                out.push_str(&line);
                out.push('\n');
            }
            let has_else = !matches!(
                &*else_branch.node,
                ExprNode::Lit { value: Literal::Nil }
            );
            if has_else {
                out.push_str("else\n");
                for line in render_body_lines(else_branch) {
                    out.push_str("  ");
                    out.push_str(&line);
                    out.push('\n');
                }
            }
            out.push_str("end");
            out
        }
        // `coll.each { |x| ... }` — keep as a block expression. Crystal
        // accepts `coll.each do |x| ... end` directly.
        ExprNode::Send { recv: Some(recv), method, args, block: Some(block), .. }
            if method.as_str() == "each" && args.is_empty() =>
        {
            let coll_s = super::expr::emit_expr(recv);
            if let ExprNode::Lambda { params, body, .. } = &*block.node {
                let var = params
                    .first()
                    .map(|p| p.as_str().to_string())
                    .unwrap_or_else(|| "item".to_string());
                let mut out = format!("{coll_s}.each do |{var}|\n");
                for line in render_body_lines(body) {
                    out.push_str("  ");
                    out.push_str(&line);
                    out.push('\n');
                }
                out.push_str("end");
                return out;
            }
            super::expr::emit_expr(stmt)
        }
        // Default: render as expression, expr emit handles it.
        _ => super::expr::emit_expr(stmt),
    }
}

/// Render an inner body (then-branch, each-block, etc.) as multiple
/// lines. Drops nothing — these aren't view bodies that need
/// `io = String.new` head removal.
fn render_body_lines(body: &Expr) -> Vec<String> {
    let stmts: Vec<&Expr> = match &*body.node {
        ExprNode::Seq { exprs } => exprs.iter().collect(),
        _ => vec![body],
    };
    let mut out = Vec::new();
    for stmt in stmts {
        let line = render_stmt(stmt);
        for inner in line.lines() {
            out.push(inner.to_string());
        }
    }
    out
}

/// Emit stub `def self.render_<plural>_<action>` for standard CRUD
/// names not supplied by the fixture. Keeps controllers' references
/// to `Views.render_*` resolvable regardless of which .erb files the
/// user provides.
fn emit_missing_view_stubs(
    out: &mut String,
    app: &App,
    emitted: &std::collections::BTreeSet<String>,
) {
    for model in &app.models {
        if model.attributes.fields.is_empty() {
            continue;
        }
        let class = model.name.0.as_str();
        let plural = crate::naming::pluralize_snake(class);
        for action in ["index", "show", "new", "edit"] {
            let fn_name = format!("render_{plural}_{action}");
            if emitted.contains(&fn_name) {
                continue;
            }
            writeln!(out).unwrap();
            writeln!(
                out,
                "  def self.{fn_name}(_record : Roundhouse::Value) : String",
            )
            .unwrap();
            writeln!(out, "    \"\"").unwrap();
            writeln!(out, "  end").unwrap();
        }
    }
}

/// Per-target body rewrite for Crystal view emit. Two transformations:
///
///   1. `Const("ViewHelpers")` → `Const("Roundhouse::ViewHelpers")`.
///      Crystal's framework runtime nests under the `Roundhouse::`
///      namespace; the lowered IR uses bare `ViewHelpers` per the
///      universal-IR contract. This prefix is per-target.
///
///   2. `Send { recv: Const("Views::<Dir>"), method: "<action>" }` →
///      `Send { recv: Const("Views"), method: "render_<dir>_<action>" }`.
///      The existing Crystal controller emit calls views as flat
///      `Views.render_<dir>_<action>`; the lowered IR uses Spinel's
///      namespace shape. Rewriting view-side calls to match the
///      flat shape avoids per-call rewrites in controller emit.
fn crystal_view_const_rewrite(e: &Expr) -> Expr {
    let new_node = match &*e.node {
        ExprNode::Const { path } => {
            let s = path.iter().map(|s| s.as_str()).collect::<Vec<_>>().join("::");
            if s == "ViewHelpers" {
                ExprNode::Const {
                    path: vec![Symbol::from("Roundhouse"), Symbol::from("ViewHelpers")],
                }
            } else {
                ExprNode::Const { path: path.clone() }
            }
        }
        // Views::<Dir>.<action>(args) → Views.render_<dir>_<action>(args).
        ExprNode::Send { recv: Some(recv), method, args, block, parenthesized }
            if matches!(
                &*recv.node,
                ExprNode::Const { path }
                    if path.len() == 2 && path[0].as_str() == "Views"
            ) =>
        {
            let dir = if let ExprNode::Const { path } = &*recv.node {
                path[1].as_str().to_string()
            } else {
                unreachable!()
            };
            let new_method = format!("render_{}_{}", crate::naming::snake_case(&dir), method.as_str());
            ExprNode::Send {
                recv: Some(Expr::new(
                    Span::synthetic(),
                    ExprNode::Const { path: vec![Symbol::from("Views")] },
                )),
                method: Symbol::from(new_method),
                args: args.iter().map(crystal_view_const_rewrite).collect(),
                block: block.as_ref().map(crystal_view_const_rewrite),
                parenthesized: *parenthesized,
            }
        }
        ExprNode::Send { recv, method, args, block, parenthesized } => ExprNode::Send {
            recv: recv.as_ref().map(crystal_view_const_rewrite),
            method: method.clone(),
            args: args.iter().map(crystal_view_const_rewrite).collect(),
            block: block.as_ref().map(crystal_view_const_rewrite),
            parenthesized: *parenthesized,
        },
        ExprNode::Apply { fun, args, block } => ExprNode::Apply {
            fun: crystal_view_const_rewrite(fun),
            args: args.iter().map(crystal_view_const_rewrite).collect(),
            block: block.as_ref().map(crystal_view_const_rewrite),
        },
        ExprNode::Seq { exprs } => ExprNode::Seq {
            exprs: exprs.iter().map(crystal_view_const_rewrite).collect(),
        },
        ExprNode::If { cond, then_branch, else_branch } => ExprNode::If {
            cond: crystal_view_const_rewrite(cond),
            then_branch: crystal_view_const_rewrite(then_branch),
            else_branch: crystal_view_const_rewrite(else_branch),
        },
        ExprNode::BoolOp { op, surface, left, right } => ExprNode::BoolOp {
            op: *op,
            surface: *surface,
            left: crystal_view_const_rewrite(left),
            right: crystal_view_const_rewrite(right),
        },
        ExprNode::Array { elements, style } => ExprNode::Array {
            elements: elements.iter().map(crystal_view_const_rewrite).collect(),
            style: *style,
        },
        ExprNode::Hash { entries, braced } => ExprNode::Hash {
            entries: entries
                .iter()
                .map(|(k, v)| (crystal_view_const_rewrite(k), crystal_view_const_rewrite(v)))
                .collect(),
            braced: *braced,
        },
        ExprNode::StringInterp { parts } => ExprNode::StringInterp {
            parts: parts
                .iter()
                .map(|p| match p {
                    InterpPart::Text { value } => InterpPart::Text { value: value.clone() },
                    InterpPart::Expr { expr } => InterpPart::Expr {
                        expr: crystal_view_const_rewrite(expr),
                    },
                })
                .collect(),
        },
        ExprNode::Lambda { params, block_param, body, block_style } => ExprNode::Lambda {
            params: params.clone(),
            block_param: block_param.clone(),
            body: crystal_view_const_rewrite(body),
            block_style: *block_style,
        },
        ExprNode::Assign { target, value } => {
            let new_target = match target {
                LValue::Var { id, name } => LValue::Var { id: *id, name: name.clone() },
                LValue::Ivar { name } => LValue::Ivar { name: name.clone() },
                LValue::Attr { recv, name } => LValue::Attr {
                    recv: crystal_view_const_rewrite(recv),
                    name: name.clone(),
                },
                LValue::Index { recv, index } => LValue::Index {
                    recv: crystal_view_const_rewrite(recv),
                    index: crystal_view_const_rewrite(index),
                },
            };
            ExprNode::Assign {
                target: new_target,
                value: crystal_view_const_rewrite(value),
            }
        }
        ExprNode::Yield { args } => ExprNode::Yield {
            args: args.iter().map(crystal_view_const_rewrite).collect(),
        },
        ExprNode::Raise { value } => ExprNode::Raise {
            value: crystal_view_const_rewrite(value),
        },
        ExprNode::RescueModifier { expr, fallback } => ExprNode::RescueModifier {
            expr: crystal_view_const_rewrite(expr),
            fallback: crystal_view_const_rewrite(fallback),
        },
        ExprNode::Return { value } => ExprNode::Return {
            value: crystal_view_const_rewrite(value),
        },
        ExprNode::Super { args } => ExprNode::Super {
            args: args
                .as_ref()
                .map(|v| v.iter().map(crystal_view_const_rewrite).collect()),
        },
        ExprNode::BeginRescue { body, rescues, else_branch, ensure, implicit } => {
            ExprNode::BeginRescue {
                body: crystal_view_const_rewrite(body),
                rescues: rescues
                    .iter()
                    .map(|rc| RescueClause {
                        classes: rc.classes.iter().map(crystal_view_const_rewrite).collect(),
                        binding: rc.binding.clone(),
                        body: crystal_view_const_rewrite(&rc.body),
                    })
                    .collect(),
                else_branch: else_branch.as_ref().map(crystal_view_const_rewrite),
                ensure: ensure.as_ref().map(crystal_view_const_rewrite),
                implicit: *implicit,
            }
        }
        ExprNode::Case { scrutinee, arms } => ExprNode::Case {
            scrutinee: crystal_view_const_rewrite(scrutinee),
            arms: arms
                .iter()
                .map(|arm| crate::expr::Arm {
                    pattern: arm.pattern.clone(),
                    guard: arm.guard.as_ref().map(crystal_view_const_rewrite),
                    body: crystal_view_const_rewrite(&arm.body),
                })
                .collect(),
        },
        ExprNode::Let { id, name, value, body } => ExprNode::Let {
            id: *id,
            name: name.clone(),
            value: crystal_view_const_rewrite(value),
            body: crystal_view_const_rewrite(body),
        },
        ExprNode::Next { value } => ExprNode::Next {
            value: value.as_ref().map(crystal_view_const_rewrite),
        },
        ExprNode::MultiAssign { targets, value } => ExprNode::MultiAssign {
            targets: targets.clone(),
            value: crystal_view_const_rewrite(value),
        },
        ExprNode::While { cond, body, until_form } => ExprNode::While {
            cond: crystal_view_const_rewrite(cond),
            body: crystal_view_const_rewrite(body),
            until_form: *until_form,
        },
        ExprNode::Range { begin, end, exclusive } => ExprNode::Range {
            begin: begin.as_ref().map(crystal_view_const_rewrite),
            end: end.as_ref().map(crystal_view_const_rewrite),
            exclusive: *exclusive,
        },
        other => other.clone(),
    };
    Expr {
        span: e.span,
        node: Box::new(new_node),
        ty: e.ty.clone(),
        effects: e.effects.clone(),
        leading_blank_line: e.leading_blank_line,
        diagnostic: e.diagnostic.clone(),
    }
}

/// `articles/index` → `render_articles_index`. Snake_case throughout
/// (matches the existing Crystal naming convention; the verbatim-input
/// policy means we don't translate from Ruby's snake_case anyway).
fn view_function_name(name: &str) -> String {
    let mut out = String::from("render");
    for seg in name.split('/') {
        let trimmed = seg.strip_prefix('_').unwrap_or(seg);
        out.push('_');
        out.push_str(trimmed);
    }
    out
}
