//! View emission — `src/views.cr`, one `def self.render_*` per view
//! plus the FormBuilder/link/render helpers that fan out from the
//! ERB walker.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use super::expr::emit_literal;
use crate::App;
use crate::expr::{Expr, ExprNode, LValue, Literal};
use crate::ident::Symbol;

/// Emit `src/views.cr` — a single Views module holding one
/// `def self.render_<plural>_<action>` per ingested view plus
/// stubs for standard CRUD views the fixture didn't supply.
/// Walks the ERB IR (`_buf = _buf + X`) produced by `src/erb.rs`,
/// same shape the TS/Rust degrade-gracefully consumers use;
/// unknown shapes become `io << "" # TODO ERB …` so the module
/// still compiles under Crystal's strict typing.
pub(super) fn emit_views_cr(app: &App) -> Vec<EmittedFile> {
    let known_models: Vec<Symbol> =
        app.models.iter().map(|m| m.name.0.clone()).collect();
    let attrs_by_class: std::collections::BTreeMap<String, Vec<String>> = app
        .models
        .iter()
        .map(|m| {
            (
                m.name.0.as_str().to_string(),
                m.attributes
                    .fields
                    .keys()
                    .map(|k| k.as_str().to_string())
                    .collect(),
            )
        })
        .collect();
    let has_manys = crate::lower::build_has_many_table(app);
    let stylesheets = app.stylesheets.clone();

    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "require \"./view_helpers\"").unwrap();
    writeln!(s, "require \"./route_helpers\"").unwrap();
    writeln!(s, "require \"./importmap\"").unwrap();
    if !app.models.is_empty() {
        writeln!(s, "require \"./models\"").unwrap();
    }
    writeln!(s).unwrap();
    writeln!(s, "module Views").unwrap();

    let mut emitted: std::collections::BTreeSet<String> =
        std::collections::BTreeSet::new();

    for view in &app.views {
        emit_cr_view_fn(&mut s, view, &known_models, &attrs_by_class, &has_manys, &stylesheets);
        emitted.insert(cr_view_function_name(view.name.as_str()));
    }

    emit_cr_missing_view_stubs(&mut s, app, &known_models, &emitted);

    writeln!(s, "end").unwrap();
    vec![EmittedFile {
        path: PathBuf::from("src/views.cr"),
        content: s,
    }]
}

fn emit_cr_view_fn(
    out: &mut String,
    view: &crate::dialect::View,
    known_models: &[Symbol],
    attrs_by_class: &std::collections::BTreeMap<String, Vec<String>>,
    has_manys: &[crate::lower::HasManyRow],
    stylesheets: &[String],
) {
    let rewritten = rewrite_view_body_ivars_cr(&view.body);
    let ivar_names = collect_ivar_names_cr(&view.body);
    let fn_name = cr_view_function_name(view.name.as_str());

    let (sig, arg_name, arg_model) = cr_view_signature(view.name.as_str(), known_models);
    let attrs = arg_model
        .as_ref()
        .and_then(|c| attrs_by_class.get(c).cloned())
        .unwrap_or_default();
    let resource_dir = view
        .name
        .as_str()
        .rsplit_once('/')
        .map(|(d, _): (&str, &str)| d.to_string())
        .unwrap_or_default();

    let mut locals: Vec<String> = vec![arg_name.clone()];
    for n in &ivar_names {
        if !locals.iter().any(|x| x == n) {
            locals.push(n.clone());
        }
    }
    let ctx = CrViewCtx {
        locals,
        arg_name: arg_name.clone(),
        arg_attrs: attrs,
        resource_dir,
        has_manys: has_manys.to_vec(),
        stylesheets: stylesheets.to_vec(),
        form_records: Vec::new(),
        attrs_by_class: attrs_by_class.clone(),
    };

    // Apply the shared erubi-trim pass so `<% %>` statement tags
    // drop their trailing newline + leading indent the same way
    // Rails does. Same call site as rust/ts/python/go.
    let trimmed = crate::lower::erb_trim::trim_view(&rewritten);

    writeln!(out).unwrap();
    writeln!(out, "  def self.{fn_name}({sig}) : String").unwrap();
    writeln!(out, "    String.build do |io|").unwrap();
    for line in emit_cr_view_body_walker(&trimmed, &ctx) {
        writeln!(out, "      {line}").unwrap();
    }
    writeln!(out, "    end").unwrap();
    writeln!(out, "  end").unwrap();
}

/// Emit stub `def self.render_<plural>_<action>` for every standard
/// CRUD view the fixture didn't supply. Keeps controllers
/// referencing `Views.render_*` resolvable regardless of which .erb
/// files the user provides.
fn emit_cr_missing_view_stubs(
    out: &mut String,
    app: &App,
    _known_models: &[Symbol],
    emitted: &std::collections::BTreeSet<String>,
) {
    for model in &app.models {
        if model.attributes.fields.is_empty() {
            continue;
        }
        let class = model.name.0.as_str();
        let plural = crate::naming::pluralize_snake(class);
        for action_stem in ["index", "show", "new", "edit"] {
            let view_name = format!("{plural}/{action_stem}");
            let fn_name = cr_view_function_name(&view_name);
            if emitted.contains(&fn_name) {
                continue;
            }
            let (arg_ty, arg_name) = if action_stem == "index" {
                (format!("Array({class})"), plural.clone())
            } else {
                (class.to_string(), crate::naming::singularize(&plural))
            };
            writeln!(out).unwrap();
            writeln!(
                out,
                "  def self.{fn_name}({arg_name} : {arg_ty}) : String"
            )
            .unwrap();
            writeln!(out, "    _ = {arg_name}").unwrap();
            writeln!(out, "    \"\"").unwrap();
            writeln!(out, "  end").unwrap();
        }
    }
}

/// Map a view path to its Crystal function name —
/// `articles/index` → `render_articles_index`; partial paths like
/// `articles/_article` map to `render_articles_article` (prefix
/// underscore dropped).
fn cr_view_function_name(name: &str) -> String {
    let mut out = String::from("render_");
    let mut first = true;
    for seg in name.split('/') {
        let trimmed = seg.strip_prefix('_').unwrap_or(seg);
        if !first {
            out.push('_');
        }
        first = false;
        out.push_str(trimmed);
    }
    out
}

/// Build the single-arg Crystal signature for a view function.
/// Returns `(signature, arg_name, model_class)` where `model_class`
/// is `Some(class)` when the resource name resolves to a known
/// model (used for `ctx.arg_has_attr` checks).
fn cr_view_signature(
    view_name: &str,
    known_models: &[Symbol],
) -> (String, String, Option<String>) {
    let (dir, base) = view_name.rsplit_once('/').unwrap_or(("", view_name));
    let is_partial = base.starts_with('_');
    let stem = base.trim_start_matches('_');
    let model_class = crate::naming::singularize_camelize(dir);
    let model_exists = known_models.iter().any(|m| m.as_str() == model_class);
    let singular = crate::naming::singularize(dir);

    if is_partial {
        let arg_name = if model_exists { singular.clone() } else { stem.to_string() };
        if model_exists {
            return (format!("{arg_name} : {model_class}"), arg_name, Some(model_class));
        }
        return (format!("{arg_name} : String"), arg_name, None);
    }
    match stem {
        "index" => {
            let arg_name = dir.to_string();
            if model_exists {
                return (
                    format!("{arg_name} : Array({model_class})"),
                    arg_name,
                    Some(model_class),
                );
            }
            (format!("{arg_name} : Array(String)"), arg_name, None)
        }
        _ => {
            let arg_name = singular.clone();
            if model_exists {
                return (format!("{arg_name} : {model_class}"), arg_name, Some(model_class));
            }
            (format!("{arg_name} : String"), arg_name, None)
        }
    }
}

/// Rewrite `@ivar` references inside a view body to bare locals,
/// matching the arg name the signature declared. Mirrors the
/// controller-side rewrite; views don't reference `params[:key]`
/// so we skip that intercept.
fn rewrite_view_body_ivars_cr(expr: &Expr) -> Expr {
    use crate::ident::VarId;
    let new_node: ExprNode = match &*expr.node {
        ExprNode::Ivar { name } => ExprNode::Var { id: VarId(0), name: name.clone() },
        ExprNode::Assign { target: LValue::Ivar { name }, value } => ExprNode::Assign {
            target: LValue::Var { id: VarId(0), name: name.clone() },
            value: rewrite_view_body_ivars_cr(value),
        },
        ExprNode::Assign { target: LValue::Var { id, name }, value } => ExprNode::Assign {
            target: LValue::Var { id: *id, name: name.clone() },
            value: rewrite_view_body_ivars_cr(value),
        },
        ExprNode::Assign { target: LValue::Attr { recv, name }, value } => ExprNode::Assign {
            target: LValue::Attr {
                recv: rewrite_view_body_ivars_cr(recv),
                name: name.clone(),
            },
            value: rewrite_view_body_ivars_cr(value),
        },
        ExprNode::Assign { target: LValue::Index { recv, index }, value } => ExprNode::Assign {
            target: LValue::Index {
                recv: rewrite_view_body_ivars_cr(recv),
                index: rewrite_view_body_ivars_cr(index),
            },
            value: rewrite_view_body_ivars_cr(value),
        },
        ExprNode::Send { recv, method, args, block, parenthesized } => ExprNode::Send {
            recv: recv.as_ref().map(rewrite_view_body_ivars_cr),
            method: method.clone(),
            args: args.iter().map(rewrite_view_body_ivars_cr).collect(),
            block: block.as_ref().map(rewrite_view_body_ivars_cr),
            parenthesized: *parenthesized,
        },
        ExprNode::Seq { exprs } => ExprNode::Seq {
            exprs: exprs.iter().map(rewrite_view_body_ivars_cr).collect(),
        },
        ExprNode::If { cond, then_branch, else_branch } => ExprNode::If {
            cond: rewrite_view_body_ivars_cr(cond),
            then_branch: rewrite_view_body_ivars_cr(then_branch),
            else_branch: rewrite_view_body_ivars_cr(else_branch),
        },
        ExprNode::BoolOp { op, surface, left, right } => ExprNode::BoolOp {
            op: *op,
            surface: *surface,
            left: rewrite_view_body_ivars_cr(left),
            right: rewrite_view_body_ivars_cr(right),
        },
        ExprNode::Array { elements, style } => ExprNode::Array {
            elements: elements.iter().map(rewrite_view_body_ivars_cr).collect(),
            style: *style,
        },
        ExprNode::Hash { entries, braced } => ExprNode::Hash {
            entries: entries
                .iter()
                .map(|(k, v)| (rewrite_view_body_ivars_cr(k), rewrite_view_body_ivars_cr(v)))
                .collect(),
            braced: *braced,
        },
        ExprNode::Lambda { params, block_param, body, block_style } => ExprNode::Lambda {
            params: params.clone(),
            block_param: block_param.clone(),
            body: rewrite_view_body_ivars_cr(body),
            block_style: *block_style,
        },
        other => other.clone(),
    };
    Expr {
        span: expr.span,
        node: Box::new(new_node),
        ty: expr.ty.clone(),
        effects: expr.effects.clone(),
        leading_blank_line: expr.leading_blank_line,
        diagnostic: expr.diagnostic.clone(),
    }
}

fn collect_ivar_names_cr(expr: &Expr) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    collect_ivars_into_cr(expr, &mut out);
    out
}

fn collect_ivars_into_cr(expr: &Expr, out: &mut Vec<String>) {
    match &*expr.node {
        ExprNode::Ivar { name } => {
            let n = name.to_string();
            if !out.iter().any(|e| e == &n) {
                out.push(n);
            }
        }
        ExprNode::Assign { target, value } => {
            if let LValue::Ivar { name } = target {
                let n = name.to_string();
                if !out.iter().any(|e| e == &n) {
                    out.push(n);
                }
            }
            collect_ivars_into_cr(value, out);
        }
        ExprNode::Send { recv, args, block, .. } => {
            if let Some(r) = recv {
                collect_ivars_into_cr(r, out);
            }
            for a in args {
                collect_ivars_into_cr(a, out);
            }
            if let Some(b) = block {
                collect_ivars_into_cr(b, out);
            }
        }
        ExprNode::Seq { exprs } => {
            for e in exprs {
                collect_ivars_into_cr(e, out);
            }
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            collect_ivars_into_cr(cond, out);
            collect_ivars_into_cr(then_branch, out);
            collect_ivars_into_cr(else_branch, out);
        }
        ExprNode::BoolOp { left, right, .. } => {
            collect_ivars_into_cr(left, out);
            collect_ivars_into_cr(right, out);
        }
        ExprNode::Array { elements, .. } => {
            for e in elements {
                collect_ivars_into_cr(e, out);
            }
        }
        ExprNode::Hash { entries, .. } => {
            for (k, v) in entries {
                collect_ivars_into_cr(k, out);
                collect_ivars_into_cr(v, out);
            }
        }
        ExprNode::Lambda { body, .. } => collect_ivars_into_cr(body, out),
        ExprNode::StringInterp { parts } => {
            for p in parts {
                if let crate::expr::InterpPart::Expr { expr } = p {
                    collect_ivars_into_cr(expr, out);
                }
            }
        }
        _ => {}
    }
}

#[derive(Clone)]
struct CrViewCtx {
    locals: Vec<String>,
    arg_name: String,
    arg_attrs: Vec<String>,
    resource_dir: String,
    has_manys: Vec<crate::lower::HasManyRow>,
    stylesheets: Vec<String>,
    /// Active FormBuilder bindings: `(builder_local_name,
    /// record_crystal_expr)` pairs. Populated on `form_with` block
    /// entry; consumed by FormBuilder field emit so `form.text_field
    /// :title` resolves to the bound record's attr.
    form_records: Vec<(String, String)>,
    attrs_by_class: std::collections::BTreeMap<String, Vec<String>>,
}

impl CrViewCtx {
    fn is_local(&self, n: &str) -> bool {
        self.locals.iter().any(|x| x == n)
    }
    fn arg_has_attr(&self, name: &str, attr: &str) -> bool {
        name == self.arg_name && self.arg_attrs.iter().any(|a| a == attr)
    }
    fn local_has_attr(&self, local: &str, attr: &str) -> bool {
        if self.arg_has_attr(local, attr) {
            return true;
        }
        let class = crate::naming::singularize_camelize(local);
        self.attrs_by_class
            .get(&class)
            .map(|attrs| attrs.iter().any(|a| a == attr))
            .unwrap_or(false)
    }
    fn with_locals(&self, more: impl IntoIterator<Item = String>) -> Self {
        let mut next = self.clone();
        for n in more {
            if !next.locals.iter().any(|x| x == &n) {
                next.locals.push(n);
            }
        }
        next
    }
    fn resolve_has_many_on_local(&self, local: &str, assoc: &str) -> Option<(String, String)> {
        if !self.is_local(local) {
            return None;
        }
        crate::lower::resolve_has_many_on_local(&self.has_manys, local, assoc)
    }
}

fn emit_cr_view_body_walker(body: &Expr, ctx: &CrViewCtx) -> Vec<String> {
    let stmts: Vec<&Expr> = match &*body.node {
        ExprNode::Seq { exprs } => exprs.iter().collect(),
        _ => vec![body],
    };
    let mut out = Vec::new();
    for stmt in &stmts {
        out.extend(emit_cr_view_stmt(stmt, ctx));
    }
    out
}

fn emit_cr_view_stmt(stmt: &Expr, ctx: &CrViewCtx) -> Vec<String> {
    match &*stmt.node {
        // Prologue `_buf = ""` — String.build already owns the buffer.
        ExprNode::Assign { target: LValue::Var { name, .. }, value }
            if name.as_str() == "_buf" =>
        {
            if let ExprNode::Lit { value: Literal::Str { value: s } } = &*value.node {
                if s.is_empty() {
                    return Vec::new();
                }
            }
            // `_buf = _buf + X` — the working shape.
            if let ExprNode::Send { recv: Some(recv), method, args, .. } = &*value.node {
                if method.as_str() == "+" && args.len() == 1 {
                    if let ExprNode::Var { name: rn, .. } = &*recv.node {
                        if rn.as_str() == "_buf" {
                            return vec![emit_cr_view_append(&args[0], ctx)];
                        }
                    }
                }
            }
            vec!["io << \"\" # TODO ERB: _buf shape".to_string()]
        }
        // Epilogue: bare `_buf` — dropped; String.build returns
        // the buffer implicitly.
        ExprNode::Var { name, .. } if name.as_str() == "_buf" => Vec::new(),
        // `if cond ... else ... end`.
        ExprNode::If { cond, then_branch, else_branch } => {
            let cond_cr = if is_cr_simple_expr(cond, ctx) {
                emit_cr_view_expr_raw(cond, ctx)
            } else {
                "false # TODO ERB cond".to_string()
            };
            let mut out = vec![format!("if {cond_cr}")];
            for line in emit_cr_view_body_walker(then_branch, ctx) {
                out.push(format!("  {line}"));
            }
            let has_else = !matches!(
                &*else_branch.node,
                ExprNode::Lit { value: Literal::Nil }
            );
            if has_else {
                out.push("else".to_string());
                for line in emit_cr_view_body_walker(else_branch, ctx) {
                    out.push(format!("  {line}"));
                }
            }
            out.push("end".to_string());
            out
        }
        // `coll.each do |x| ... end` — only if coll is a simple
        // local; Crystal can't iterate an unresolved association.
        ExprNode::Send { recv: Some(recv), method, args, block: Some(block), .. }
            if method.as_str() == "each" && args.is_empty() =>
        {
            if !is_cr_simple_expr(recv, ctx) {
                return vec!["io << \"\" # TODO ERB: each over complex coll".to_string()];
            }
            let ExprNode::Lambda { params, body, .. } = &*block.node else {
                return vec!["io << \"\" # TODO ERB: each block shape".to_string()];
            };
            let coll_s = emit_cr_view_expr_raw(recv, ctx);
            let var = params
                .first()
                .map(|p| p.as_str().to_string())
                .unwrap_or_else(|| "item".into());
            let inner_ctx = ctx.with_locals([var.clone()]);
            let mut out = vec![format!("{coll_s}.each do |{var}|")];
            for line in emit_cr_view_body_walker(body, &inner_ctx) {
                out.push(format!("  {line}"));
            }
            out.push("end".to_string());
            out
        }
        // Statement-form `<% content_for :title, "Articles" %>`.
        ExprNode::Send { recv: None, method, args, block: None, .. } => {
            if let Some(crate::lower::ViewHelperKind::ContentForSetter { slot, body }) =
                crate::lower::classify_view_helper(method.as_str(), args)
            {
                if is_cr_simple_expr(body, ctx) {
                    let body_cr = emit_cr_view_expr_raw(body, ctx);
                    return vec![format!(
                        "Roundhouse::ViewHelpers.content_for_set({slot:?}, ({body_cr}).to_s)"
                    )];
                }
            }
            vec!["io << \"\" # TODO ERB: unknown stmt".to_string()]
        }
        _ => vec!["io << \"\" # TODO ERB: unknown stmt".to_string()],
    }
}

fn emit_cr_view_append(arg: &Expr, ctx: &CrViewCtx) -> String {
    if let ExprNode::Lit { value: Literal::Str { value: s } } = &*arg.node {
        return format!("io << {}", cr_string_literal(s));
    }
    let inner = unwrap_to_s_cr(arg);

    // `<%= yield %>` / `<%= yield :head %>`.
    if let ExprNode::Yield { args } = &*inner.node {
        if let Some(first) = args.first() {
            if let Some(slot) = cr_extract_slot_name(first) {
                return format!("io << Roundhouse::ViewHelpers.get_slot({slot:?})");
            }
        }
        return "io << Roundhouse::ViewHelpers.get_yield".to_string();
    }

    // `<%= content_for(:slot) || "default" %>` — BoolOp fallback.
    if let ExprNode::BoolOp { op, left, right, .. } = &*inner.node {
        if matches!(op, crate::expr::BoolOpKind::Or) {
            if let ExprNode::Send { recv: None, method, args, block: None, .. } = &*left.node {
                if method.as_str() == "content_for" && args.len() == 1 {
                    if let Some(slot) = cr_extract_slot_name(&args[0]) {
                        if is_cr_simple_expr(right, ctx) {
                            let fb = emit_cr_view_expr_raw(right, ctx);
                            return format!(
                                "io << (Roundhouse::ViewHelpers.content_for_get({slot:?}).presence || ({fb}).to_s)"
                            );
                        }
                    }
                }
            }
        }
    }

    // `render @coll` / `render "partial", hash`.
    if let ExprNode::Send { recv: None, method, args, block: None, .. } = &*inner.node {
        if method.as_str() == "render" {
            if args.len() == 1 {
                return emit_cr_render_call(&args[0], ctx);
            }
            if args.len() == 2 {
                if let (
                    ExprNode::Lit { value: Literal::Str { value: partial } },
                    ExprNode::Hash { entries, .. },
                ) = (&*args[0].node, &*args[1].node)
                {
                    let partial_fn = format!("render_{}_{}", ctx.resource_dir, partial);
                    if let Some((_, v)) = entries.first() {
                        if is_cr_simple_expr(v, ctx) {
                            let arg_expr = emit_cr_view_expr_raw(v, ctx);
                            return format!("io << Views.{partial_fn}({arg_expr})");
                        }
                    }
                    return "io << \"\" # TODO ERB: render partial".to_string();
                }
            }
        }
    }

    // Capturing helpers.
    if let ExprNode::Send {
        recv: None,
        method,
        args,
        block: Some(block),
        ..
    } = &*inner.node
    {
        if is_cr_capturing_helper(method.as_str()) {
            return emit_cr_captured_helper(method.as_str(), args, block, ctx);
        }
    }

    // View-helper classifier dispatch.
    if let ExprNode::Send { recv: None, method, args, block: None, .. } = &*inner.node {
        if let Some(kind) = crate::lower::classify_view_helper(method.as_str(), args) {
            if let Some(line) = emit_cr_view_helper(&kind, ctx) {
                return line;
            }
        }
    }

    // FormBuilder method calls (`form.label :title`, etc.).
    if let ExprNode::Send { recv: Some(r), method, args, block: None, .. } = &*inner.node {
        if let ExprNode::Var { name, .. } | ExprNode::Ivar { name } = &*r.node {
            if ctx.form_records.iter().any(|(n, _)| n == name.as_str()) {
                if let Some(fb) = crate::lower::classify_form_builder_method(method.as_str()) {
                    if let Some(call) = emit_cr_form_builder_call(name.as_str(), fb, args, ctx)
                    {
                        return format!("io << {call}");
                    }
                }
            }
        }
    }

    if is_cr_simple_expr(inner, ctx) {
        let raw = emit_cr_view_expr_raw(inner, ctx);
        if matches!(&*inner.node, ExprNode::Lit { value: Literal::Str { .. } }) {
            return format!("io << {raw}");
        }
        return format!("io << ({raw}).to_s");
    }

    "io << \"\" # TODO ERB: complex interpolation".to_string()
}

fn cr_extract_slot_name(arg: &Expr) -> Option<&str> {
    match &*arg.node {
        ExprNode::Lit { value: Literal::Sym { value } } => Some(value.as_str()),
        ExprNode::Lit { value: Literal::Str { value } } => Some(value.as_str()),
        _ => None,
    }
}

fn is_cr_capturing_helper(method: &str) -> bool {
    matches!(method, "form_with" | "content_for")
}

fn emit_cr_captured_helper(
    method: &str,
    args: &[Expr],
    block: &Expr,
    ctx: &CrViewCtx,
) -> String {
    let ExprNode::Lambda { params, body, .. } = &*block.node else {
        return format!("io << \"\" # TODO ERB: {method}");
    };
    let cls_expr = args
        .iter()
        .find_map(|a| cr_extract_kwarg(a, "class"))
        .filter(|e| is_cr_simple_expr(e, ctx))
        .map(|e| emit_cr_view_expr_raw(e, ctx))
        .unwrap_or_else(|| "\"\"".to_string());
    match method {
        "form_with" => {
            let model_expr = args.iter().find_map(|a| cr_extract_kwarg(a, "model"));
            let model_nested: Option<Vec<Expr>> = model_expr.and_then(|e| match &*e.node {
                ExprNode::Array { elements, .. } if elements.len() >= 2 => {
                    Some(elements.clone())
                }
                _ => None,
            });
            let record_ref: Option<String> = if let Some(elems) = &model_nested {
                Some(emit_cr_nested_form_record(&elems[elems.len() - 1]))
            } else {
                model_expr
                    .filter(|e| is_cr_simple_expr(e, ctx))
                    .map(|e| emit_cr_view_expr_raw(e, ctx))
                    .or_else(|| {
                        if !ctx.arg_name.is_empty() && ctx.is_local(&ctx.arg_name) {
                            Some(ctx.arg_name.clone())
                        } else {
                            None
                        }
                    })
            };
            let prefix = if let Some(elems) = &model_nested {
                cr_nested_form_child_prefix(&elems[elems.len() - 1])
                    .unwrap_or_else(|| ctx.arg_name.clone())
            } else if !ctx.resource_dir.is_empty() {
                crate::naming::singularize(&ctx.resource_dir)
            } else {
                ctx.arg_name.clone()
            };

            let pname = params.first().map(|p| p.as_str()).unwrap_or("form");
            let plural = if !ctx.resource_dir.is_empty() {
                ctx.resource_dir.clone()
            } else {
                crate::naming::pluralize_snake(&prefix)
            };
            // Crystal's route helpers are snake_case fns like
            // rails (ArticlePath → article_path) — use naming.
            let prefix_snake = crate::naming::snake_case(&prefix);
            let plural_snake = crate::naming::snake_case(&plural);

            let is_persisted_expr = record_ref
                .as_deref()
                .map(|r| format!("({r}.id != 0)"))
                .unwrap_or_else(|| "false".to_string());
            let action_expr = match (&record_ref, &model_nested) {
                (Some(record), Some(elems)) => {
                    cr_nested_form_path_expr(elems, ctx, record, &prefix)
                }
                (Some(record), None) => format!(
                    "({record}.id != 0 ? RouteHelpers.{prefix_snake}_path({record}.id) : RouteHelpers.{plural_snake}_path)",
                ),
                (None, _) => format!("RouteHelpers.{plural_snake}_path"),
            };

            let mut inner_ctx = ctx.with_locals([pname.to_string()]);
            if let Some(record) = &record_ref {
                inner_ctx
                    .form_records
                    .push((pname.to_string(), record.clone()));
            }
            let mut lines: Vec<String> = Vec::new();
            lines.push("io << (begin".to_string());
            lines.push("  __inner = String.build do |io|".to_string());
            lines.push(format!(
                "    {pname} = Roundhouse::ViewHelpers::FormBuilder.new({prefix:?}, {cls_expr}, {is_persisted_expr})"
            ));
            if let Some(record) = &record_ref {
                lines.push(format!(
                    "    io << Roundhouse::ViewHelpers.error_messages_for({record}.errors, {prefix:?})"
                ));
            }
            for line in emit_cr_view_body_walker(body, &inner_ctx) {
                lines.push(format!("    {line}"));
            }
            lines.push("  end".to_string());
            lines.push(format!(
                "  Roundhouse::ViewHelpers.form_wrap({action_expr}, {is_persisted_expr}, {cls_expr}, __inner)"
            ));
            lines.push("end)".to_string());
            lines.join("\n")
        }
        "content_for" => {
            let slot = args.first().and_then(cr_extract_slot_name);
            let Some(slot) = slot else {
                let _ = cls_expr;
                return "io << \"\"".to_string();
            };
            let mut lines: Vec<String> = Vec::new();
            lines.push("(begin".to_string());
            lines.push("  __cf = String.build do |io|".to_string());
            for line in emit_cr_view_body_walker(body, ctx) {
                lines.push(format!("    {line}"));
            }
            lines.push("  end".to_string());
            lines.push(format!(
                "  Roundhouse::ViewHelpers.content_for_set({slot:?}, __cf)"
            ));
            lines.push("end)".to_string());
            lines.join("\n")
        }
        _ => "io << \"\"".to_string(),
    }
}

fn emit_cr_nested_form_record(el: &Expr) -> String {
    match crate::lower::classify_nested_form_child(el) {
        Some(crate::lower::NestedFormChild::ClassNew { class }) => format!("{class}.new"),
        Some(crate::lower::NestedFormChild::Local { name }) => name.to_string(),
        None => "nil".to_string(),
    }
}

fn cr_nested_form_child_prefix(el: &Expr) -> Option<String> {
    crate::lower::classify_nested_form_child(el).map(|k| k.prefix())
}

fn cr_nested_element_parts(kind: &crate::lower::NestedUrlElement<'_>) -> (String, String) {
    match kind {
        crate::lower::NestedUrlElement::DirectLocal { name } => {
            ((*name).to_string(), format!("{name}.id"))
        }
        crate::lower::NestedUrlElement::Association { owner, assoc } => {
            ((*assoc).to_string(), format!("{owner}.{assoc}_id"))
        }
    }
}

fn cr_nested_form_path_expr(
    elems: &[Expr],
    ctx: &CrViewCtx,
    record_ref: &str,
    child_prefix: &str,
) -> String {
    let is_local = |n: &str| ctx.is_local(n);
    let mut parent_ids: Vec<String> = Vec::new();
    let mut parent_singulars: Vec<String> = Vec::new();
    for parent in &elems[..elems.len() - 1] {
        let Some(kind) = crate::lower::classify_nested_url_element(parent, &is_local) else {
            return "\"\"".to_string();
        };
        let (singular, id_expr) = cr_nested_element_parts(&kind);
        parent_singulars.push(singular);
        parent_ids.push(id_expr);
    }
    let member_name = format!(
        "{}_{}_path",
        parent_singulars.join("_"),
        child_prefix,
    );
    let child_plural = crate::naming::pluralize_snake(child_prefix);
    let collection_name = format!(
        "{}_{}_path",
        parent_singulars.join("_"),
        child_plural,
    );
    let parent_args = parent_ids.join(", ");
    let member_args = if parent_args.is_empty() {
        format!("{record_ref}.id")
    } else {
        format!("{parent_args}, {record_ref}.id")
    };
    let collection_call = if parent_args.is_empty() {
        format!("RouteHelpers.{collection_name}")
    } else {
        format!("RouteHelpers.{collection_name}({parent_args})")
    };
    format!(
        "({record_ref}.id != 0 ? RouteHelpers.{member_name}({member_args}) : {collection_call})",
    )
}

/// Render a classified `ViewHelperKind` to a Crystal `io << …`
/// statement. Returns None when arg shapes aren't renderable.
/// Compose one AR chain modifier onto a running Crystal slice
/// expression. Mirrors rust/ts/python/go: `all`/`includes`/etc.
/// pass through; `order({field: :dir})` wraps with `sort_by`;
/// `limit(N)` slices `[0, N]`.
pub(super) fn apply_cr_chain_modifier(prev: String, m: crate::lower::ChainModifier<'_>) -> String {
    match m.method {
        "all" | "includes" | "preload" | "joins" | "distinct" | "select" => prev,
        "order" => {
            let Some(hash) = m.args.first() else { return prev };
            let ExprNode::Hash { entries, .. } = &*hash.node else { return prev };
            let Some((k, v)) = entries.first() else { return prev };
            let field = match &*k.node {
                ExprNode::Lit { value: Literal::Sym { value } } => value.as_str().to_string(),
                ExprNode::Lit { value: Literal::Str { value } } => value.clone(),
                _ => return prev,
            };
            let dir = match &*v.node {
                ExprNode::Lit { value: Literal::Sym { value } } => value.as_str().to_string(),
                ExprNode::Lit { value: Literal::Str { value } } => value.clone(),
                _ => "asc".to_string(),
            };
            if dir == "desc" {
                format!("{prev}.sort_by(&.{field}).reverse")
            } else {
                format!("{prev}.sort_by(&.{field})")
            }
        }
        "limit" => {
            let Some(n) = m.args.first() else { return prev };
            if let ExprNode::Lit { value: Literal::Int { value, .. } } = &*n.node {
                return format!("{prev}[0, {value}]");
            }
            prev
        }
        _ => prev,
    }
}

fn emit_cr_view_helper(
    kind: &crate::lower::ViewHelperKind<'_>,
    ctx: &CrViewCtx,
) -> Option<String> {
    use crate::lower::ViewHelperKind::*;
    match kind {
        CsrfMetaTags => Some("io << Roundhouse::ViewHelpers.csrf_meta_tags".to_string()),
        CspMetaTag => Some("io << Roundhouse::ViewHelpers.csp_meta_tag".to_string()),
        JavascriptImportmapTags => Some(
            "io << Roundhouse::ViewHelpers.javascript_importmap_tags(Importmap::PINS, \"application\")"
                .to_string(),
        ),
        TurboStreamFrom { channel } => {
            if !is_cr_simple_expr(channel, ctx) {
                return None;
            }
            let arg = emit_cr_view_expr_raw(channel, ctx);
            Some(format!("io << Roundhouse::ViewHelpers.turbo_stream_from({arg})"))
        }
        DomId { record, prefix } => {
            let (singular, id_expr) = cr_resolve_dom_id_record(record, ctx)?;
            match prefix {
                None => Some(format!(
                    "io << Roundhouse::ViewHelpers.dom_id({singular:?}, {id_expr})"
                )),
                Some(p) => {
                    let prefix_str = match &*p.node {
                        ExprNode::Lit { value: Literal::Sym { value } } => {
                            format!("{:?}", value.as_str())
                        }
                        ExprNode::Lit { value: Literal::Str { value } } => format!("{value:?}"),
                        _ if is_cr_simple_expr(p, ctx) => emit_cr_view_expr_raw(p, ctx),
                        _ => return None,
                    };
                    Some(format!(
                        "io << Roundhouse::ViewHelpers.dom_id({singular:?}, {id_expr}, {prefix_str})"
                    ))
                }
            }
        }
        Pluralize { count, word } => {
            if !is_cr_simple_expr(count, ctx) || !is_cr_simple_expr(word, ctx) {
                return None;
            }
            let c = emit_cr_view_expr_raw(count, ctx);
            let w = emit_cr_view_expr_raw(word, ctx);
            Some(format!("io << Roundhouse::ViewHelpers.pluralize({c}, {w})"))
        }
        Truncate { text, opts } => {
            if !is_cr_simple_expr(text, ctx) {
                return None;
            }
            let t = emit_cr_view_expr_raw(text, ctx);
            let opts_code = cr_opts_from_expr(opts.as_deref(), ctx);
            Some(format!("io << Roundhouse::ViewHelpers.truncate({t}, {opts_code})"))
        }
        StylesheetLinkTag { name, opts } => {
            let opts_code = cr_opts_from_expr(opts.as_deref(), ctx);
            if let ExprNode::Lit { value: Literal::Sym { value } } = &*name.node {
                if value.as_str() == "app" && !ctx.stylesheets.is_empty() {
                    let lines: Vec<String> = ctx
                        .stylesheets
                        .iter()
                        .map(|n| {
                            format!("io << Roundhouse::ViewHelpers.stylesheet_link_tag({n:?}, {opts_code})")
                        })
                        .collect();
                    return Some(lines.join("\nio << \"\\n\"\n"));
                }
            }
            let name_expr = match &*name.node {
                ExprNode::Lit { value: Literal::Sym { value } } => format!("{:?}", value.as_str()),
                ExprNode::Lit { value: Literal::Str { value } } => format!("{value:?}"),
                _ => return None,
            };
            Some(format!(
                "io << Roundhouse::ViewHelpers.stylesheet_link_tag({name_expr}, {opts_code})"
            ))
        }
        ContentForGetter { slot } => {
            Some(format!("io << Roundhouse::ViewHelpers.content_for_get({slot:?})"))
        }
        ContentForSetter { .. } => None,
        LinkTo { text, url, opts } => {
            emit_cr_link_or_button("link_to", text, url, *opts, ctx)
                .map(|call| format!("io << {call}"))
        }
        ButtonTo { text, target, opts } => {
            emit_cr_link_or_button("button_to", text, target, *opts, ctx)
                .map(|call| format!("io << {call}"))
        }
    }
}

fn cr_resolve_dom_id_record(record: &Expr, ctx: &CrViewCtx) -> Option<(String, String)> {
    let name = match &*record.node {
        ExprNode::Var { name, .. } | ExprNode::Ivar { name } if ctx.is_local(name.as_str()) => {
            name.as_str().to_string()
        }
        ExprNode::Send {
            recv: None,
            method,
            args,
            block: None,
            ..
        } if args.is_empty() && ctx.is_local(method.as_str()) => method.as_str().to_string(),
        _ => return None,
    };
    let singular = crate::naming::singularize(&name);
    Some((singular, format!("{name}.id")))
}

fn emit_cr_link_or_button(
    helper: &str,
    text: &Expr,
    url: &Expr,
    opts: Option<&Expr>,
    ctx: &CrViewCtx,
) -> Option<String> {
    if !is_cr_simple_expr(text, ctx) {
        return None;
    }
    let text_raw = emit_cr_view_expr_raw(text, ctx);
    let text_expr = match &*text.node {
        ExprNode::Lit { value: Literal::Str { .. } } => text_raw,
        _ => format!("({text_raw}).to_s"),
    };
    let is_local = |n: &str| ctx.is_local(n);
    let url_kind = crate::lower::classify_view_url_arg(url, &is_local)?;
    let url_expr = match url_kind {
        crate::lower::ViewUrlArg::Literal { value } => format!("{value:?}"),
        crate::lower::ViewUrlArg::PathHelper { name, args } => {
            let args_s: Vec<String> = args.iter().map(|a| cr_path_arg(a, ctx)).collect();
            if args_s.is_empty() {
                format!("RouteHelpers.{name}")
            } else {
                format!("RouteHelpers.{name}({})", args_s.join(", "))
            }
        }
        crate::lower::ViewUrlArg::RecordRef { name } => {
            format!(
                "RouteHelpers.{}_path({name}.id)",
                crate::naming::singularize(name),
            )
        }
        crate::lower::ViewUrlArg::NestedArray { elements } => cr_emit_nested_path(elements, ctx)?,
    };
    let opts_code = cr_opts_from_expr(opts, ctx);
    Some(format!(
        "Roundhouse::ViewHelpers.{helper}({text_expr}, {url_expr}, {opts_code})"
    ))
}

fn cr_path_arg(arg: &Expr, ctx: &CrViewCtx) -> String {
    match &*arg.node {
        ExprNode::Var { name, .. } | ExprNode::Ivar { name } if ctx.is_local(name.as_str()) => {
            format!("{}.id", name.as_str())
        }
        ExprNode::Send { recv: None, method, args, block: None, .. }
            if args.is_empty() && ctx.is_local(method.as_str()) =>
        {
            format!("{}.id", method.as_str())
        }
        _ => emit_cr_view_expr_raw(arg, ctx),
    }
}

fn cr_emit_nested_path(elements: &[Expr], ctx: &CrViewCtx) -> Option<String> {
    let is_local = |n: &str| ctx.is_local(n);
    let mut singulars: Vec<String> = Vec::new();
    let mut args: Vec<String> = Vec::new();
    for el in elements {
        let kind = crate::lower::classify_nested_url_element(el, &is_local)?;
        let (singular, id_expr) = cr_nested_element_parts(&kind);
        singulars.push(singular);
        args.push(id_expr);
    }
    let name = format!("{}_path", singulars.join("_"));
    Some(format!("RouteHelpers.{name}({})", args.join(", ")))
}

fn cr_opts_from_expr(opts: Option<&Expr>, ctx: &CrViewCtx) -> String {
    match opts.map(|e| &*e.node) {
        Some(ExprNode::Hash { entries, .. }) => cr_hash_to_map(entries, ctx),
        _ => "{} of String => String".to_string(),
    }
}

fn cr_hash_to_map(entries: &[(Expr, Expr)], ctx: &CrViewCtx) -> String {
    let mut items: Vec<(String, String)> = Vec::new();
    for (k, v) in entries {
        let key = match &*k.node {
            ExprNode::Lit { value: Literal::Sym { value } } => value.as_str().to_string(),
            ExprNode::Lit { value: Literal::Str { value } } => value.clone(),
            _ => continue,
        };
        if key == "data" {
            if let ExprNode::Hash { entries: de, .. } = &*v.node {
                for (dk, dv) in de {
                    let dk_str = match &*dk.node {
                        ExprNode::Lit { value: Literal::Sym { value } } => {
                            value.as_str().replace('_', "-")
                        }
                        ExprNode::Lit { value: Literal::Str { value } } => {
                            value.replace('_', "-")
                        }
                        _ => continue,
                    };
                    let dv_s = cr_opt_value(dv, ctx);
                    items.push((format!("data-{dk_str}"), dv_s));
                }
                continue;
            }
        }
        let val = if key == "class" {
            cr_class_value(v, ctx)
        } else {
            cr_opt_value(v, ctx)
        };
        items.push((key, val));
    }
    if items.is_empty() {
        return "{} of String => String".to_string();
    }
    let parts: Vec<String> = items
        .into_iter()
        .map(|(k, v)| format!("{k:?} => {v}"))
        .collect();
    format!("{{{}}}", parts.join(", "))
}

fn cr_opt_value(v: &Expr, ctx: &CrViewCtx) -> String {
    match &*v.node {
        ExprNode::Lit { value: Literal::Str { value } } => format!("{value:?}"),
        ExprNode::Lit { value: Literal::Int { value, .. } } => {
            format!("\"{value}\"")
        }
        ExprNode::Lit { value: Literal::Sym { value } } => format!("{:?}", value.as_str()),
        ExprNode::Array { elements, .. } => match elements.first() {
            Some(first) => match &*first.node {
                ExprNode::Lit { value: Literal::Str { value } } => format!("{value:?}"),
                _ => "\"\"".to_string(),
            },
            None => "\"\"".to_string(),
        },
        _ if is_cr_simple_expr(v, ctx) => {
            let raw = emit_cr_view_expr_raw(v, ctx);
            match &*v.node {
                ExprNode::Lit { .. } => raw,
                _ => format!("({raw}).to_s"),
            }
        }
        _ => "\"\"".to_string(),
    }
}

fn cr_class_value(v: &Expr, ctx: &CrViewCtx) -> String {
    let is_local = |n: &str| ctx.is_local(n);
    let simple_as_cr = |e: &Expr| -> Option<String> {
        if is_cr_simple_expr(e, ctx) {
            Some(match &*e.node {
                ExprNode::Lit { value: Literal::Str { value } } => format!("{value:?}"),
                _ => {
                    let raw = emit_cr_view_expr_raw(e, ctx);
                    match &*e.node {
                        ExprNode::Lit { .. } => raw,
                        _ => format!("({raw}).to_s"),
                    }
                }
            })
        } else {
            None
        }
    };
    match crate::lower::classify_class_value(v, &is_local) {
        crate::lower::ClassValueShape::Simple { expr } => {
            simple_as_cr(expr).unwrap_or_else(|| "\"\"".to_string())
        }
        crate::lower::ClassValueShape::Conditional { base, clauses } => {
            let Some(base_cr) = simple_as_cr(base) else {
                return "\"\"".to_string();
            };
            if clauses.is_empty() {
                return base_cr;
            }
            let extras: Vec<String> = clauses
                .iter()
                .map(|(cls_text, pred)| {
                    let cond = cr_render_errors_field_predicate(pred);
                    format!(" + ({cond} ? \" {cls_text}\" : \"\")")
                })
                .collect();
            format!("({base_cr}{})", extras.join(""))
        }
        crate::lower::ClassValueShape::Unknown => "\"\"".to_string(),
    }
}

fn cr_render_errors_field_predicate(pred: &crate::lower::ErrorsFieldPredicate<'_>) -> String {
    let call = format!(
        "Roundhouse::ViewHelpers.field_has_error({}.errors, {:?})",
        pred.record, pred.field,
    );
    if pred.expect_present {
        call
    } else {
        format!("!{call}")
    }
}

fn emit_cr_form_builder_call(
    recv: &str,
    kind: crate::lower::FormBuilderMethod,
    args: &[Expr],
    ctx: &CrViewCtx,
) -> Option<String> {
    use crate::lower::FormBuilderMethod::*;
    let (field, opts_entries) = crate::lower::classify_form_builder_args(args);
    let field = field.map(str::to_string);
    let opts = opts_entries
        .map(|entries| cr_hash_to_map(entries, ctx))
        .unwrap_or_else(|| "{} of String => String".to_string());
    match kind {
        Label => {
            let field = field?;
            Some(format!("{recv}.label({field:?}, {opts})"))
        }
        TextField | TextArea => {
            let cr_method = if matches!(kind, TextField) { "text_field" } else { "textarea" };
            let field = field?;
            let value_expr = ctx
                .form_records
                .iter()
                .find(|(name, _)| name == recv)
                .and_then(|(_, record)| {
                    if ctx.local_has_attr(record, &field) {
                        Some(format!("{record}.{field}"))
                    } else {
                        None
                    }
                })
                .unwrap_or_else(|| "\"\"".to_string());
            Some(format!(
                "{recv}.{cr_method}({field:?}, {value_expr}, {opts})"
            ))
        }
        Submit => {
            let label_str = args.iter().find_map(|a| match &*a.node {
                ExprNode::Lit { value: Literal::Str { value } } => Some(value.clone()),
                _ => None,
            });
            let opts_expr = if let Some(lbl) = label_str {
                format!(
                    "({opts}).merge({{\"label\" => {lbl:?}}})",
                )
            } else {
                opts
            };
            Some(format!("{recv}.submit({opts_expr})"))
        }
    }
}


fn emit_cr_render_call(arg: &Expr, ctx: &CrViewCtx) -> String {
    match &*arg.node {
        ExprNode::Var { name, .. } | ExprNode::Ivar { name }
            if ctx.is_local(name.as_str()) =>
        {
            let plural = name.as_str();
            let singular = crate::naming::singularize(plural);
            let partial_fn = format!("render_{plural}_{singular}");
            let coll = name.to_string();
            format!("{coll}.each {{ |__r| io << Views.{partial_fn}(__r) }}")
        }
        ExprNode::Send { recv: Some(r), method, args, .. }
            if args.is_empty()
                && matches!(&*r.node, ExprNode::Var { .. } | ExprNode::Ivar { .. }) =>
        {
            // `render @article.comments` — has_many association.
            // Resolve via the flattened `has_manys` table and inline
            // a filter query, matching the expr_raw path.
            let owner_name = match &*r.node {
                ExprNode::Var { name, .. } | ExprNode::Ivar { name } => name.as_str().to_string(),
                _ => return "io << \"\" # TODO ERB: render".to_string(),
            };
            if let Some((target_class, fk)) =
                ctx.resolve_has_many_on_local(&owner_name, method.as_str())
            {
                let assoc_plural = method.as_str();
                let singular = crate::naming::singularize(assoc_plural);
                let partial_fn = format!("render_{assoc_plural}_{singular}");
                return format!(
                    "{target_class}.all.select {{ |__r| __r.{fk} == {owner_name}.id }}.each {{ |__r| io << Views.{partial_fn}(__r) }}"
                );
            }
            "io << \"\" # TODO ERB: render assoc (unresolved)".to_string()
        }
        _ => "io << \"\" # TODO ERB: render".to_string(),
    }
}

fn cr_extract_kwarg<'a>(arg: &'a Expr, key: &str) -> Option<&'a Expr> {
    if let ExprNode::Hash { entries, .. } = &*arg.node {
        for (k, v) in entries {
            if let ExprNode::Lit { value: Literal::Sym { value } } = &*k.node {
                if value.as_str() == key {
                    return Some(v);
                }
            }
        }
    }
    None
}

fn unwrap_to_s_cr(expr: &Expr) -> &Expr {
    if let ExprNode::Send { recv: Some(inner), method, args, .. } = &*expr.node {
        if method.as_str() == "to_s" && args.is_empty() {
            return inner;
        }
    }
    expr
}

/// Escape a string for a Crystal double-quoted literal. Rust's
/// debug format (`{:?}`) handles the common cases (quote, backslash,
/// newline) the same way Crystal does; `#` also needs escaping to
/// avoid accidental `#{...}` interpolation.
fn cr_string_literal(s: &str) -> String {
    let mut out = String::from("\"");
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '#' => out.push_str("\\#"),
            c if c.is_control() => out.push_str(&format!("\\u{{{:x}}}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn is_cr_simple_expr(expr: &Expr, ctx: &CrViewCtx) -> bool {
    match &*expr.node {
        ExprNode::Lit { .. } => true,
        ExprNode::Var { name, .. } | ExprNode::Ivar { name } => ctx.is_local(name.as_str()),
        // Partial-scope local parsed as bare Send — same as rust/
        // python/go: treat as a simple local-read.
        ExprNode::Send { recv: None, method, args, block: None, .. }
            if args.is_empty() && ctx.is_local(method.as_str()) =>
        {
            true
        }
        ExprNode::Send { recv: Some(r), method, args, block, .. } => {
            if !args.is_empty() || block.is_some() {
                return false;
            }
            let clean = method.as_str().trim_end_matches('?').trim_end_matches('!');
            if clean.is_empty() {
                return false;
            }
            let recv_local = match &*r.node {
                ExprNode::Var { name, .. } | ExprNode::Ivar { name } => Some(name.as_str()),
                ExprNode::Send {
                    recv: None,
                    method: m,
                    args: ra,
                    block: None,
                    ..
                } if ra.is_empty() && ctx.is_local(m.as_str()) => Some(m.as_str()),
                _ => None,
            };
            if let Some(local_name) = recv_local {
                if ctx.local_has_attr(local_name, clean) {
                    return true;
                }
                if ctx.is_local(local_name)
                    && matches!(method.as_str(), "any?" | "none?" | "present?" | "empty?")
                {
                    return true;
                }
                if ctx
                    .resolve_has_many_on_local(local_name, method.as_str())
                    .is_some()
                {
                    return true;
                }
            }
            if is_cr_simple_expr(r, ctx) {
                return true;
            }
            false
        }
        ExprNode::StringInterp { parts } => parts.iter().all(|p| match p {
            crate::expr::InterpPart::Text { .. } => true,
            crate::expr::InterpPart::Expr { expr } => is_cr_simple_expr(expr, ctx),
        }),
        _ => false,
    }
}

fn emit_cr_view_expr_raw(expr: &Expr, ctx: &CrViewCtx) -> String {
    match &*expr.node {
        ExprNode::Lit { value } => emit_literal(value),
        ExprNode::Var { name, .. } | ExprNode::Ivar { name } => name.to_string(),
        ExprNode::Send { recv, method, args, .. } => {
            let method_s = method.as_str();
            // Bare local ref (partial scope).
            if recv.is_none() && args.is_empty() && ctx.is_local(method_s) {
                return method_s.to_string();
            }
            if let Some(r) = recv {
                if args.is_empty() {
                    // has_many association read → inline filter.
                    // Crystal is statically typed; the target class
                    // has a `Class.all` and each record has
                    // `.field_name_id` fields, so we build an array
                    // via select.
                    let owner_local = match &*r.node {
                        ExprNode::Var { name, .. } | ExprNode::Ivar { name }
                            if ctx.is_local(name.as_str()) =>
                        {
                            Some(name.as_str().to_string())
                        }
                        ExprNode::Send {
                            recv: None,
                            method: m,
                            args: ra,
                            block: None,
                            ..
                        } if ra.is_empty() && ctx.is_local(m.as_str()) => {
                            Some(m.as_str().to_string())
                        }
                        _ => None,
                    };
                    if let Some(owner) = &owner_local {
                        if let Some((target_class, fk)) =
                            ctx.resolve_has_many_on_local(owner, method_s)
                        {
                            return format!(
                                "{target_class}.all.select {{ |__r| __r.{fk} == {owner}.id }}"
                            );
                        }
                    }
                    // Collection predicates on any recv.
                    match method_s {
                        "any?" | "present?" => {
                            let recv_s = emit_cr_view_expr_raw(r, ctx);
                            return format!("!{recv_s}.empty?");
                        }
                        "none?" | "empty?" => {
                            let recv_s = emit_cr_view_expr_raw(r, ctx);
                            return format!("{recv_s}.empty?");
                        }
                        "size" | "count" | "length" => {
                            let recv_s = emit_cr_view_expr_raw(r, ctx);
                            return format!("{recv_s}.size");
                        }
                        "full_message" => {
                            let recv_s = emit_cr_view_expr_raw(r, ctx);
                            return format!("{recv_s}.full_message");
                        }
                        _ => {}
                    }
                }
                let recv_s = emit_cr_view_expr_raw(r, ctx);
                let clean = method_s.trim_end_matches('?').trim_end_matches('!');
                if args.is_empty() {
                    return format!("{recv_s}.{clean}");
                }
                let args_s: Vec<String> =
                    args.iter().map(|a| emit_cr_view_expr_raw(a, ctx)).collect();
                return format!("{recv_s}.{clean}({})", args_s.join(", "));
            }
            // Bare fn call with no recv → assume helper.
            let args_s: Vec<String> =
                args.iter().map(|a| emit_cr_view_expr_raw(a, ctx)).collect();
            if args.is_empty() {
                format!("Roundhouse::ViewHelpers.{method_s}")
            } else {
                format!("Roundhouse::ViewHelpers.{method_s}({})", args_s.join(", "))
            }
        }
        ExprNode::StringInterp { parts } => {
            use crate::expr::InterpPart;
            let mut out = String::from("\"");
            for p in parts {
                match p {
                    InterpPart::Text { value } => {
                        for c in value.chars() {
                            if c == '"' || c == '\\' {
                                out.push('\\');
                            }
                            if c == '#' {
                                out.push('\\');
                            }
                            out.push(c);
                        }
                    }
                    InterpPart::Expr { expr } => {
                        out.push_str("#{");
                        out.push_str(&emit_cr_view_expr_raw(expr, ctx));
                        out.push('}');
                    }
                }
            }
            out.push('"');
            out
        }
        _ => "\"\"".to_string(),
    }
}
