//! Ecosystem files for the emitted C# project — the .NET scaffold.
//! The analog of `src/emit/kotlin/package.rs` (the Gradle scaffold) and
//! `src/emit/typescript/package.rs` (`package.json`/`tsconfig.json`).
//! Locked stack: .NET SDK + ASP.NET Core / Kestrel (HTTP),
//! `Microsoft.Data.Sqlite` (DB), System.Text.Json (JSON), built-in
//! WebSockets (Action Cable) — see `docs/csharp-migration-plan.md`.

use std::path::PathBuf;

use crate::emit::EmittedFile;

// `Microsoft.NET.Sdk.Web` pulls in ASP.NET Core (Kestrel) — the per-target
// HTTP server primitive, the .NET analog of Javalin (kotlin) / Vapor
// (swift). `net10.0` matches the current SDK (`dotnet 10.0.x`); pinned via
// mise/brew on the build host, not here. `Nullable` + `ImplicitUsings` are
// on so the emitter can lean on declared nullability (the `ty` mapping's
// `T?` / `object?`) the way the Kotlin renderer leans on `Any?`.
const CSPROJ: &str = r#"<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Roundhouse</RootNamespace>
    <AssemblyName>roundhouse-app</AssemblyName>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.0" />
    <!-- Override the native sqlite bundle to a patched build (Microsoft.Data.
         Sqlite 10.0.0 pulls a transitive version flagged by GHSA-2m69-gcr7-jv3q). -->
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.3" />
  </ItemGroup>

  <!-- The SDK globs **/*.cs, which would otherwise compile the emitted test
       project (tests/App.Tests.csproj — xUnit references this project) into
       the app itself. Harmless when there is no tests/ directory. -->
  <ItemGroup>
    <Compile Remove="tests/**" />
  </ItemGroup>

</Project>
"#;

// Phase 1 placeholder entry point. Phase 4 replaces this with the routes
// table + controller factory map wired into a Kestrel pipeline (the C#
// analog of Kotlin's generated `Main.kt` handing off to `Server.kt`).
const PROGRAM_CS: &str = r#"// Generated by Roundhouse (csharp). Entry point — Phase 1 scaffold.
// Later phases wire the routes table + controllers into the ASP.NET Core
// (Kestrel) pipeline, mirroring Kotlin's Main.kt / Server.kt.

var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

app.MapGet("/", () =>
    "Roundhouse C# target — scaffold. Models, controllers, and views are " +
    "emitted in later phases (see docs/csharp-migration-plan.md).");

var port = Environment.GetEnvironmentVariable("PORT") ?? "3000";
app.Run($"http://0.0.0.0:{port}");
"#;

const GITIGNORE: &str = "/bin/\n/obj/\n/storage/\ntests/bin/\ntests/obj/\n";

// The test project (`tests/App.Tests.csproj`), emitted alongside the
// transpiled suite. It's a SEPARATE project rather than test files inside the
// app project because `Microsoft.NET.Test.Sdk` generates its own entry point,
// which collides with the Web SDK app's top-level `Program.cs`.
//
// `xunit.runner.visualstudio` is what makes `dotnet test` discover `[Fact]`s;
// without it the run reports zero tests and exits 0 — the exact silent-pass
// this suite exists to end (#34 §0).
const TEST_CSPROJ: &str = r#"<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Roundhouse</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../roundhouse-app.csproj" />
  </ItemGroup>

</Project>
"#;

// The transpiled suite drives one process-wide `Db` (a static class with a
// pooled connection and one test database path), so the tests must not run
// concurrently — xUnit parallelizes across test classes by default.
const TEST_ASSEMBLY_INFO: &str = r#"// Generated by Roundhouse (csharp).
//
// The emitted suite shares one process-wide Db (static, one test database
// path reset per test), so test classes must run one at a time. xUnit
// parallelizes across collections by default; this turns that off.
using Xunit;

[assembly: CollectionBehavior(DisableTestParallelization = true)]
"#;

/// The .NET scaffold files (`Program.cs` is generated by `csharp::emit`,
/// wiring the routes table + controllers into the Kestrel `Server`).
pub fn scaffold() -> Vec<EmittedFile> {
    let _ = PROGRAM_CS;
    vec![
        EmittedFile {
            path: PathBuf::from("roundhouse-app.csproj"),
            content: CSPROJ.to_string(),
        },
        EmittedFile {
            path: PathBuf::from(".gitignore"),
            content: GITIGNORE.to_string(),
        },
    ]
}

/// The test project's ecosystem files, emitted only when the App carries
/// tests (`csharp::emit_tests`).
pub fn test_scaffold() -> Vec<EmittedFile> {
    vec![
        EmittedFile {
            path: PathBuf::from("tests/App.Tests.csproj"),
            content: TEST_CSPROJ.to_string(),
        },
        EmittedFile {
            path: PathBuf::from("tests/AssemblyInfo.cs"),
            content: TEST_ASSEMBLY_INFO.to_string(),
        },
    ]
}
