//! Ecosystem files for the emitted C# project — the .NET scaffold.
//! The analog of `src/emit/kotlin/package.rs` (the Gradle scaffold) and
//! `src/emit/typescript/package.rs` (`package.json`/`tsconfig.json`).
//! Locked stack: .NET SDK + ASP.NET Core / Kestrel (HTTP),
//! `Microsoft.Data.Sqlite` (DB), System.Text.Json (JSON), built-in
//! WebSockets (Action Cable) — see `docs/csharp-migration-plan.md`.

use std::path::PathBuf;

use crate::emit::EmittedFile;

// `Microsoft.NET.Sdk.Web` pulls in ASP.NET Core (Kestrel) — the per-target
// HTTP server primitive, the .NET analog of Javalin (kotlin) / Vapor
// (swift). `net10.0` matches the current SDK (`dotnet 10.0.x`); pinned via
// mise/brew on the build host, not here. `Nullable` + `ImplicitUsings` are
// on so the emitter can lean on declared nullability (the `ty` mapping's
// `T?` / `object?`) the way the Kotlin renderer leans on `Any?`.
const CSPROJ: &str = r#"<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Roundhouse</RootNamespace>
    <AssemblyName>roundhouse-app</AssemblyName>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.0" />
    <!-- Override the native sqlite bundle to a patched build (Microsoft.Data.
         Sqlite 10.0.0 pulls a transitive version flagged by GHSA-2m69-gcr7-jv3q). -->
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.3" />
  </ItemGroup>

</Project>
"#;

// Phase 1 placeholder entry point. Phase 4 replaces this with the routes
// table + controller factory map wired into a Kestrel pipeline (the C#
// analog of Kotlin's generated `Main.kt` handing off to `Server.kt`).
const PROGRAM_CS: &str = r#"// Generated by Roundhouse (csharp). Entry point — Phase 1 scaffold.
// Later phases wire the routes table + controllers into the ASP.NET Core
// (Kestrel) pipeline, mirroring Kotlin's Main.kt / Server.kt.

var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

app.MapGet("/", () =>
    "Roundhouse C# target — scaffold. Models, controllers, and views are " +
    "emitted in later phases (see docs/csharp-migration-plan.md).");

var port = Environment.GetEnvironmentVariable("PORT") ?? "3000";
app.Run($"http://0.0.0.0:{port}");
"#;

const GITIGNORE: &str = "/bin/\n/obj/\n/storage/\n";

/// The .NET scaffold files. Phase 1 emits only these; Phase 2+ adds the
/// `*.cs` sources (models, controllers, views, transpiled runtime).
pub fn scaffold() -> Vec<EmittedFile> {
    vec![
        EmittedFile {
            path: PathBuf::from("roundhouse-app.csproj"),
            content: CSPROJ.to_string(),
        },
        EmittedFile {
            path: PathBuf::from("Program.cs"),
            content: PROGRAM_CS.to_string(),
        },
        EmittedFile {
            path: PathBuf::from(".gitignore"),
            content: GITIGNORE.to_string(),
        },
    ]
}
