//! Project skeleton: `Cargo.toml` + `src/lib.rs`. These tag along
//! unconditionally so the emitted output is a self-contained Cargo
//! project the target toolchain will accept.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use crate::App;

/// Cargo.toml for the generated crate. Includes axum (with ws for
/// Action Cable) for the HTTP runtime, serde + serde_json for typed
/// form decoding and JSON frame encoding, tokio for the async
/// runtime axum depends on, rusqlite for persistence, futures-util
/// for the WebSocket stream combinators, and axum-test (dev-only)
/// for the controller test client.
pub(super) fn emit_cargo_toml() -> EmittedFile {
    let content = "\
[package]
name = \"app\"
version = \"0.1.0\"
edition = \"2024\"

[lib]
path = \"src/lib.rs\"

[[bin]]
name = \"app\"
path = \"src/main.rs\"

[dependencies]
axum = { version = \"0.8\", features = [\"ws\"] }
base64 = \"0.22\"
futures-util = \"0.3\"
rusqlite = { version = \"0.33\", features = [\"bundled\"] }
serde = { version = \"1\", features = [\"derive\"] }
serde_json = \"1\"
tokio = { version = \"1\", features = [\"rt-multi-thread\", \"macros\", \"net\", \"sync\", \"time\"] }

[dev-dependencies]
axum-test = \"18\"
";
    EmittedFile {
        path: PathBuf::from("Cargo.toml"),
        content: content.to_string(),
    }
}

/// `src/lib.rs` — declares the crate modules Roundhouse emitted.
pub(super) fn emit_lib_rs(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s).unwrap();
    if !app.models.is_empty() {
        writeln!(s, "pub mod runtime;").unwrap();
        writeln!(s, "pub mod db;").unwrap();
        writeln!(s, "pub mod schema_sql;").unwrap();
        writeln!(s, "pub mod models;").unwrap();
    }
    if !app.controllers.is_empty() {
        writeln!(s, "pub mod http;").unwrap();
        writeln!(s, "pub mod controllers;").unwrap();
        writeln!(s, "pub mod router;").unwrap();
        writeln!(s, "pub mod route_helpers;").unwrap();
        writeln!(s, "pub mod importmap;").unwrap();
        writeln!(s, "pub mod view_helpers;").unwrap();
        writeln!(s, "pub mod views;").unwrap();
        writeln!(s, "pub mod server;").unwrap();
        writeln!(s, "pub mod cable;").unwrap();
        writeln!(s).unwrap();
        writeln!(s, "#[cfg(test)]").unwrap();
        writeln!(s, "pub mod test_support;").unwrap();
    }
    if !app.fixtures.is_empty() {
        writeln!(s).unwrap();
        writeln!(s, "#[cfg(test)]").unwrap();
        writeln!(s, "pub mod fixtures;").unwrap();
    }
    if !app.test_modules.is_empty() {
        writeln!(s).unwrap();
        writeln!(s, "#[cfg(test)]").unwrap();
        writeln!(s, "pub mod tests;").unwrap();
    }
    EmittedFile {
        path: PathBuf::from("src/lib.rs"),
        content: s,
    }
}
