//! Controllers — axum-shaped free fns per action, plus the shared
//! expression/statement emission machinery (`EmitCtx`, `emit_expr`,
//! `emit_send`, …) consumed by both controller bodies and test bodies.

use std::fmt::Write;
use std::path::PathBuf;

use crate::App;
use crate::dialect::Controller;
use crate::expr::{Expr, ExprNode, LValue, Literal};
use crate::ident::Symbol;
use crate::naming::snake_case;
use crate::ty::Ty;
// Trait import for the walker — used by RsEmitter's inherent helpers
// to call `self.render_expr(...)` via trait-method dispatch.
use crate::lower::CtrlWalker as _;

use super::super::EmittedFile;
use super::{apply_rust_chain_modifier, emit_literal};

/// `src/controllers.rs` — declares each emitted controller submodule
/// so `src/controllers/<name>_controller.rs` files land on the module
/// tree. Separate file rather than inlining `pub mod` declarations
/// into `lib.rs` keeps the controllers directory self-contained.
pub(super) fn emit_controllers_mod(controllers: &[Controller]) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s).unwrap();
    for c in controllers {
        writeln!(s, "pub mod {};", snake_case(c.name.0.as_str())).unwrap();
    }
    EmittedFile {
        path: PathBuf::from("src/controllers.rs"),
        content: s,
    }
}

// Controllers ----------------------------------------------------------
//
// Phase 4c: every action and private helper is emitted as a free-standing
// `fn` inside the controller's `impl` block. Bodies go through the same
// `emit_body` / `emit_expr` machinery as model methods, with a few
// controller-specific Send rewrites turned on via `EmitCtx::in_controller`:
//
//   * bare `params`          → `crate::http::params()`
//   * `params.expect(...)`   → `todo!("params.expect")` (divergent, so
//                              its `!` type unifies with whatever the
//                              call site expects, e.g. `i64` in
//                              `Article::find(params.expect(:id))`)
//   * `respond_to { ... }`   → `crate::http::respond_to(|__fr| { ... })`
//   * `format.html { body }` → `__fr.html(|| { body })`
//   * `format.json { body }` → emitted as a comment placeholder (the
//                              JSON branch is deferred per scope)
//   * `redirect_to`, `render`, `head` (bare) → `crate::http::*`
//   * `x.destroy!()`         → `x.destroy()` (Rust forbids `!` in idents)
//   * bare Send to a name in `self_methods` → `Self::name(...)`
//     (so `article_params` inside `create` compiles as `Self::article_params()`)
//
// Action bodies always return `crate::http::Response`. The emitter
// discards each action body's natural tail (Rails' convention: ivars
// feed the view) and appends `crate::http::Response::default()`.




/// Phase 4d controller emit — produces axum-shaped free fns per
/// action. For each of Rails' seven standard RESTful actions
/// (index/show/new/edit/create/update/destroy), emit a template body
/// that wires the action to the model runtime + route helpers +
/// views. Non-standard actions collapse to a stub that returns 501
/// Not Implemented; the scaffold blog doesn't have any.
pub(super) fn emit_controller_axum(
    controller: &Controller,
    app: &App,
    known_models: &[Symbol],
) -> EmittedFile {
    let controller_name = controller.name.0.as_str();
    let resource = crate::lower::resource_from_controller_name(controller_name);
    let model_class = crate::naming::singularize_camelize(&resource);
    let has_model = known_models
        .iter()
        .any(|m| m.as_str() == model_class);
    let parent = crate::lower::find_nested_parent(app, controller_name);
    let permitted = crate::lower::permitted_fields_for(controller, &resource)
        .unwrap_or_else(|| crate::lower::default_permitted_fields(app, &model_class));

    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s, "#![allow(unused_imports, unused_variables, unused_mut)]").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "use std::collections::HashMap;").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "use axum::extract::{{Form, Path}};").unwrap();
    writeln!(s, "use axum::response::{{IntoResponse, Response}};").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "use crate::http::{{self, Params}};").unwrap();
    if has_model {
        writeln!(s, "use crate::models::*;").unwrap();
    }
    writeln!(s, "use crate::route_helpers;").unwrap();
    writeln!(s, "use crate::views;").unwrap();
    writeln!(s).unwrap();

    let (public_actions, _private_actions) = crate::lower::split_public_private(controller);
    for (i, action) in public_actions.iter().enumerate() {
        if i > 0 {
            writeln!(s).unwrap();
        }
        let la = crate::lower::lower_action(
            action.name.as_str(),
            &resource,
            &model_class,
            has_model,
            parent.as_ref(),
            &permitted,
        );
        emit_rust_action(&mut s, &la, &action.body, known_models, controller);
    }

    let filename = format!("src/controllers/{}.rs", snake_case(controller_name));
    EmittedFile { path: PathBuf::from(filename), content: s }
}

/// Render one LoweredAction as an axum handler. Rust-specific
/// shapes: `Path(id): Path<i64>` extractors on routes with `:id`,
/// `Form(form): Form<HashMap<...>>` on POST/PATCH, `Response`
/// (not `ActionResponse`) returned via `into_response()`.
/// Render one LoweredAction as an axum handler. Signature-derivation
/// keys off `la.name` (show/edit/update/destroy carry a Path-extracted
/// `id`; create/update also take a `Form(form)` extractor; nested
/// controllers prepend the parent's id). Body emission delegates to
/// the action walker — the scaffold templates are gone.
fn emit_rust_action(
    out: &mut String,
    la: &crate::lower::LoweredAction,
    body: &Expr,
    known_models: &[Symbol],
    controller: &Controller,
) {
    let name = la.name.as_str();
    let has_id_in_path = matches!(name, "show" | "edit" | "update" | "destroy");
    let has_form = matches!(name, "create" | "update");

    // Collect signature params first so we can collapse to
    // `pub async fn name() -> Response {` when there are none.
    let mut sig_params = String::new();
    emit_path_params(&mut sig_params, la.parent.as_ref(), has_id_in_path);
    if has_form {
        writeln!(&mut sig_params, "    Form(form): Form<HashMap<String, String>>,").unwrap();
    }
    if sig_params.is_empty() {
        writeln!(out, "pub async fn {name}() -> Response {{").unwrap();
    } else {
        writeln!(out, "pub async fn {name}(").unwrap();
        out.push_str(&sig_params);
        writeln!(out, ") -> Response {{").unwrap();
    }

    if !la.has_model {
        writeln!(out, "    http::html(String::new()).into_response()").unwrap();
        writeln!(out, "}}").unwrap();
        return;
    }

    use crate::lower::CtrlWalker;
    let normalized = crate::lower::normalize_action_body(controller, name, body);
    let mut emitter = RsEmitter {
        ctx: crate::lower::WalkCtx {
            known_models,
            model_class: la.model_class.as_str(),
            resource: la.resource.as_str(),
            parent: la.parent.as_ref(),
            permitted: &la.permitted,
            adapter: &crate::adapter::SqliteAdapter,
        },
        state: crate::lower::WalkState::new(),
    };
    let body_src = emitter.walk_action_body(&normalized);
    out.push_str(&body_src);
    writeln!(out, "}}").unwrap();
}

/// Rust's controller-body emitter. See `src/lower/controller_walk.rs`
/// for the trait's shared walker dispatch.
struct RsEmitter<'a> {
    ctx: crate::lower::WalkCtx<'a>,
    state: crate::lower::WalkState,
}

impl<'a> crate::lower::CtrlWalker<'a> for RsEmitter<'a> {
    fn ctx(&self) -> &crate::lower::WalkCtx<'a> { &self.ctx }
    fn state_mut(&mut self) -> &mut crate::lower::WalkState { &mut self.state }
    fn indent_unit(&self) -> &'static str { "    " }

    fn write_assign(&mut self, name: &str, value: &Expr, indent: &str, out: &mut String) {
        let rhs = self.render_expr(value);
        writeln!(out, "{indent}let mut {name} = {rhs};").unwrap();
    }

    fn write_create_expansion(
        &mut self,
        var_name: &str,
        class: &str,
        indent: &str,
        out: &mut String,
    ) {
        writeln!(out, "{indent}let p = Params::new(form);").unwrap();
        let keys = self.ctx.permitted.iter()
            .map(|k| format!("{k:?}")).collect::<Vec<_>>().join(", ");
        writeln!(out, "{indent}let fields = p.expect({:?}, &[{keys}]);", self.ctx.resource).unwrap();
        writeln!(out, "{indent}let mut {var_name} = {class} {{").unwrap();
        if let Some(parent) = self.ctx.parent {
            writeln!(out, "{indent}    {}_id,", parent.singular).unwrap();
        }
        for field in self.ctx.permitted {
            writeln!(
                out,
                "{indent}    {field}: fields.get({field:?}).cloned().unwrap_or_default(),",
            )
            .unwrap();
        }
        writeln!(out, "{indent}    ..Default::default()").unwrap();
        writeln!(out, "{indent}}};").unwrap();
    }

    fn write_if(
        &mut self,
        cond: &Expr,
        then_branch: &Expr,
        else_branch: &Expr,
        indent: &str,
        depth: usize,
        is_tail: bool,
        out: &mut String,
    ) {
        let cond_s = self.render_expr(cond);
        writeln!(out, "{indent}if {cond_s} {{").unwrap();
        self.walk_stmt(then_branch, out, depth + 1, is_tail);
        writeln!(out, "{indent}}} else {{").unwrap();
        if !crate::lower::is_empty_body(else_branch) {
            self.walk_stmt(else_branch, out, depth + 1, is_tail);
        }
        writeln!(out, "{indent}}}").unwrap();
    }

    fn write_update_if(
        &mut self,
        recv: &Expr,
        then_branch: &Expr,
        else_branch: &Expr,
        indent: &str,
        depth: usize,
        is_tail: bool,
        out: &mut String,
    ) {
        let recv_s = self.render_expr(recv);
        writeln!(out, "{indent}let p = Params::new(form);").unwrap();
        let keys = self.ctx.permitted.iter()
            .map(|k| format!("{k:?}")).collect::<Vec<_>>().join(", ");
        writeln!(out, "{indent}let fields = p.expect({:?}, &[{keys}]);", self.ctx.resource).unwrap();
        for field in self.ctx.permitted {
            writeln!(
                out,
                "{indent}if let Some(v) = fields.get({field:?}) {{ {recv_s}.{field} = v.clone(); }}",
            )
            .unwrap();
        }
        writeln!(out, "{indent}if {recv_s}.save() {{").unwrap();
        self.walk_stmt(then_branch, out, depth + 1, is_tail);
        writeln!(out, "{indent}}} else {{").unwrap();
        if !crate::lower::is_empty_body(else_branch) {
            self.walk_stmt(else_branch, out, depth + 1, is_tail);
        }
        writeln!(out, "{indent}}}").unwrap();
    }

    fn write_response_stmt(&mut self, r: &str, is_tail: bool, indent: &str, out: &mut String) {
        // Rust distinguishes trailing expression (no `return`/`;`)
        // from early-return. Only the function's final tail position
        // can use the bare-expression form; other positions need
        // an explicit `return`.
        if is_tail {
            writeln!(out, "{indent}{r}").unwrap();
        } else {
            writeln!(out, "{indent}return {r};").unwrap();
        }
    }

    fn write_expr_stmt(&mut self, s: &str, indent: &str, out: &mut String) {
        writeln!(out, "{indent}{s};").unwrap();
    }

    fn render_expr(&mut self, expr: &Expr) -> String {
        if let ExprNode::Send { recv, method, args, block, .. } = &*expr.node {
            if let Some(stmt) = self.render_send_stmt(
                recv.as_ref(), method.as_str(), args, block.as_ref(), "",
            ) {
                return match stmt {
                    crate::lower::Stmt::Response(r) => r,
                    crate::lower::Stmt::Expr(s) => s,
                };
            }
            let ctx_inner = EmitCtx {
                known_models: self.ctx.known_models,
                ..EmitCtx::default()
            };
            return emit_send(recv.as_ref(), method.as_str(), args, block.as_ref(), ctx_inner);
        }
        let ctx_inner = EmitCtx {
            known_models: self.ctx.known_models,
            ..EmitCtx::default()
        };
        emit_expr(expr, ctx_inner)
    }

    fn render_send_stmt(
        &mut self,
        recv: Option<&Expr>,
        method: &str,
        args: &[Expr],
        block: Option<&Expr>,
        // Rust async consumption not wired yet; prefix unused for now.
        _suspending_prefix: &str,
    ) -> Option<crate::lower::Stmt> {
        use crate::lower::{SendKind, Stmt};
        let kind = crate::lower::classify_controller_send(
            recv, method, args, block, self.ctx.known_models,
        )?;
        Some(match kind {
            // params surface: `id` / `article_id` come in via axum's
            // Path extractor; render the bare local name.
            SendKind::ParamsIndex { key } => {
                let s = match &*key.node {
                    ExprNode::Lit { value: Literal::Sym { value: s } } => s.as_str().to_string(),
                    _ => self.render_expr(key),
                };
                Stmt::Expr(s)
            }
            SendKind::ParamsExpect { args: pe_args } => {
                let s = match pe_args.first().map(|e| &*e.node) {
                    Some(ExprNode::Lit { value: Literal::Sym { value: s } }) => s.as_str().to_string(),
                    _ => "todo!(\"params.expect hash\")".to_string(),
                };
                Stmt::Expr(s)
            }
            SendKind::ParamsAccess => Stmt::Expr("todo!(\"bare params\")".to_string()),

            SendKind::ModelNew { class } => {
                Stmt::Expr(format!("{}::default()", class.as_str()))
            }
            SendKind::ModelFind { class, id } => {
                let id_s = self.render_expr(id);
                Stmt::Expr(format!("{}::find({id_s}).unwrap_or_default()", class.as_str()))
            }
            SendKind::QueryChain { target: Some(target), method, args, recv } => {
                // Walk the chain bottom-up, then compose modifiers
                // onto `{Target}::all()`. `order`/`limit` produce
                // observable output; `includes`/`preload`/etc are
                // no-ops for sqlite.
                let modifiers = crate::lower::collect_chain_modifiers(method, args, recv.as_deref());
                let mut s = format!("{}::all()", target.as_str());
                for m in modifiers {
                    s = apply_rust_chain_modifier(s, m);
                }
                Stmt::Expr(s)
            }
            SendKind::QueryChain { target: None, .. } => {
                Stmt::Expr("todo!(\"unresolved query chain\")".to_string())
            }
            SendKind::AssocLookup { target, outer_method } => match outer_method {
                "find" => {
                    let id_s = args.first().map(|a| self.render_expr(a))
                        .unwrap_or_else(|| "0".to_string());
                    Stmt::Expr(format!(
                        "{}::find({id_s}).unwrap_or_default()", target.as_str(),
                    ))
                }
                _ => Stmt::Expr(format!("{}::default()", target.as_str())),
            },
            SendKind::BangStrip { recv, stripped_method, args: bs_args } => {
                let recv_s = self.render_expr(recv);
                let args_s: Vec<String> =
                    bs_args.iter().map(|a| self.render_expr(a)).collect();
                Stmt::Expr(format!("{recv_s}.{stripped_method}({})", args_s.join(", ")))
            }
            SendKind::InstanceUpdate => Stmt::Expr("false".to_string()),
            SendKind::PathOrUrlHelper => {
                let helper = method.strip_suffix("_url").or_else(|| method.strip_suffix("_path"))
                    .unwrap_or(method);
                Stmt::Expr(format!("route_helpers::{helper}_path()"))
            }
            SendKind::Render { args: r_args } => Stmt::Response(self.render_rs_render(r_args)),
            SendKind::RedirectTo { args: r_args } => Stmt::Response(self.render_rs_redirect(r_args)),
            SendKind::Head { args: h_args } => {
                let status = h_args.first().and_then(|a| match &*a.node {
                    ExprNode::Lit { value: Literal::Sym { value: s } } =>
                        Some(crate::lower::status_sym_to_code(s.as_str())),
                    ExprNode::Lit { value: Literal::Int { value: n } } => Some(*n as u16),
                    _ => None,
                }).unwrap_or(200);
                Stmt::Response(format!(
                    "(axum::http::StatusCode::from_u16({status}).unwrap(), \"\").into_response()"
                ))
            }
            SendKind::RespondToBlock { .. }
            | SendKind::FormatHtml { .. }
            | SendKind::FormatJson => Stmt::Expr(
                "Response::default() /* unreachable: respond_to not normalized */".to_string(),
            ),
        })
    }
}

impl<'a> RsEmitter<'a> {
    fn render_rs_render(&mut self, args: &[Expr]) -> String {
        if let Some(first) = args.first() {
            if let ExprNode::Lit { value: Literal::Sym { value: sym } } = &*first.node {
                let suffix = sym.as_str();
                let plural = crate::naming::pluralize_snake(self.ctx.model_class);
                let view_fn = format!("{plural}_{suffix}");
                let arg = self.state.last_local.clone()
                    .unwrap_or_else(|| "&Default::default()".to_string());
                let wrapper = match crate::lower::extract_status_from_kwargs(&args[1..]) {
                    Some(422) => "http::unprocessable",
                    _ => "http::html",
                };
                return format!("{wrapper}(views::{view_fn}(&{arg})).into_response()");
            }
            let body_s = self.render_expr(first);
            return format!("http::html({body_s}).into_response()");
        }
        "http::html(String::new()).into_response()".to_string()
    }

    fn render_rs_redirect(&mut self, args: &[Expr]) -> String {
        let Some(first) = args.first() else {
            return "http::redirect(\"/\").into_response()".to_string();
        };
        let loc = self.render_expr(first);
        if is_bare_rs_ident(&loc) {
            let id_access = format!("{loc}.id");
            return format!(
                "http::redirect(&route_helpers::{loc}_path({id_access})).into_response()",
            );
        }
        if loc.starts_with("route_helpers::") {
            return format!("http::redirect(&{loc}).into_response()");
        }
        format!("http::redirect(&{loc}).into_response()")
    }
}

fn is_bare_rs_ident(s: &str) -> bool {
    let bytes = s.as_bytes();
    if bytes.is_empty() { return false; }
    let first = bytes[0];
    if !(first.is_ascii_lowercase() || first == b'_') { return false; }
    bytes.iter().all(|&b| b.is_ascii_alphanumeric() || b == b'_')
}


/// Emit the axum Path extractor(s) for an action. `with_id` adds the
/// leaf `:id` param; nested routes always include the parent.
fn emit_path_params(out: &mut String, parent: Option<&crate::lower::NestedParent>, with_id: bool) {
    match (parent, with_id) {
        (Some(parent), true) => {
            writeln!(
                out,
                "    Path(({}_id, id)): Path<(i64, i64)>,",
                parent.singular,
            )
            .unwrap();
        }
        (Some(parent), false) => {
            writeln!(out, "    Path({}_id): Path<i64>,", parent.singular).unwrap();
        }
        (None, true) => {
            writeln!(out, "    Path(id): Path<i64>,").unwrap();
        }
        (None, false) => {}
    }
}


/// Context threaded through expression emission. Grows as emission
/// shapes demand more information at leaf sites.
///
/// - `self_methods`: names of attributes/methods on the enclosing
///   `Self` class. Bare-name Sends matching one emit as `self.method`
///   rather than a bare identifier. Populated inside model methods.
/// - `in_test`: true when emitting a test-body expression. Enables
///   fixture accessors (`articles(:one)` → `fixtures::articles::one()`),
///   `Class.new(hash)` → struct-literal, and assertion mapping.
/// - `fixture_names`: fixture module names available in test scope
///   (e.g. `articles`, `comments`). Only consulted when `in_test`.
/// - `known_models`: names of emitted model classes. Used to decide
///   whether `Class.new(hash)` is a model constructor to be rendered
///   as a struct literal. Only consulted when `in_test`.
#[derive(Default, Clone, Copy)]
pub(in crate::emit::rust) struct EmitCtx<'a> {
    pub(in crate::emit::rust) self_methods: &'a [Symbol],
    pub(in crate::emit::rust) in_test: bool,
    /// Enables Phase 4c controller-body Send rewrites: bare `params`,
    /// `params.expect`, `respond_to` + `format.html/json`, bare
    /// `redirect_to`/`render`/`head`, and `x.destroy!` → `x.destroy()`.
    pub(in crate::emit::rust) in_controller: bool,
    pub(in crate::emit::rust) fixture_names: &'a [Symbol],
    pub(in crate::emit::rust) known_models: &'a [Symbol],
    /// Union of attribute names across every emitted model. Used as a
    /// fallback for the field-access heuristic when the receiver's type
    /// annotation isn't populated (the analyzer doesn't walk test
    /// bodies today; a future pass could remove this fallback).
    pub(in crate::emit::rust) model_attrs: &'a [Symbol],
    /// `Some` when test-body emission needs to consult cross-model
    /// associations (`owner.assoc.create(hash)` rewrite). Defaults to
    /// `None` for emit paths outside tests.
    pub(in crate::emit::rust) app: Option<&'a App>,
}

pub(in crate::emit::rust) fn emit_body(body: &Expr, ctx: EmitCtx) -> String {
    // An action body like `@posts = Post.all` drops the ivar assignment and
    // just returns the RHS (Rails convention: ivars pass data to the view).
    // Local-variable assignments become `let` bindings. Multi-statement
    // bodies join with newlines, tail-expression is the function's return.
    match &*body.node {
        ExprNode::Assign { target: LValue::Ivar { .. }, value } => emit_expr(value, ctx),
        ExprNode::Seq { exprs } if !exprs.is_empty() => {
            let mut lines: Vec<String> = Vec::new();
            for (i, e) in exprs.iter().enumerate() {
                lines.push(emit_stmt(e, i == exprs.len() - 1, ctx));
            }
            lines.join("\n")
        }
        _ => emit_expr(body, ctx),
    }
}

fn emit_stmt(e: &Expr, is_last: bool, ctx: EmitCtx) -> String {
    match &*e.node {
        // Local `foo = expr` -> `let foo = expr;`.
        ExprNode::Assign { target: LValue::Var { name, .. }, value } => {
            if ctx.in_test {
                // Save/destroy take `&mut self`; mark every local as
                // mut so test bindings work uniformly. The allow-attr
                // on each test fn swallows the resulting unused-mut
                // warnings.
                format!("let mut {} = {};", name, emit_expr(value, ctx))
            } else {
                format!("let {} = {};", name, emit_expr(value, ctx))
            }
        }
        // Ivars in a multi-statement body: treat as locals. Later stmts can
        // read them via `ExprNode::Ivar` which also emits as the bare name.
        ExprNode::Assign { target: LValue::Ivar { name }, value } => {
            if ctx.in_test {
                // Save/destroy take `&mut self`; mark every local as
                // mut so test bindings work uniformly. The allow-attr
                // on each test fn swallows the resulting unused-mut
                // warnings.
                format!("let mut {} = {};", name, emit_expr(value, ctx))
            } else {
                format!("let {} = {};", name, emit_expr(value, ctx))
            }
        }
        _ => {
            if is_last {
                emit_expr(e, ctx)
            } else {
                format!("{};", emit_expr(e, ctx))
            }
        }
    }
}

pub(in crate::emit::rust) fn emit_expr(e: &Expr, ctx: EmitCtx) -> String {
    match &*e.node {
        ExprNode::Lit { value } => emit_literal(value),
        ExprNode::Const { path } => {
            path.iter().map(|s| s.to_string()).collect::<Vec<_>>().join("::")
        }
        ExprNode::Var { name, .. } => name.to_string(),
        // Rails ivars become plain locals in the action body's Rust scope.
        // Cross-action ivar handoff (via filters, views) is a separate concern.
        ExprNode::Ivar { name } => name.to_string(),
        ExprNode::Hash { entries, .. } => {
            // Rough approximation — real target code would probably want a
            // strongly-typed struct. HashMap::from is the dumbest-that-works.
            let parts: Vec<String> = entries
                .iter()
                .map(|(k, v)| format!("({}, {})", emit_expr(k, ctx), emit_expr(v, ctx)))
                .collect();
            format!("HashMap::from([{}])", parts.join(", "))
        }
        ExprNode::Array { elements, .. } => {
            let parts: Vec<String> = elements.iter().map(|e| emit_expr(e, ctx)).collect();
            format!("vec![{}]", parts.join(", "))
        }
        ExprNode::BoolOp { op, left, right, .. } => {
            use crate::expr::BoolOpKind;
            let op_s = match op {
                BoolOpKind::Or => "||",
                BoolOpKind::And => "&&",
            };
            format!("{} {} {}", emit_expr(left, ctx), op_s, emit_expr(right, ctx))
        }
        ExprNode::StringInterp { parts } => {
            use crate::expr::InterpPart;
            let mut fmt = String::new();
            let mut args: Vec<String> = Vec::new();
            for p in parts {
                match p {
                    InterpPart::Text { value } => {
                        for c in value.chars() {
                            if c == '{' || c == '}' {
                                fmt.push(c);
                                fmt.push(c);
                            } else {
                                fmt.push(c);
                            }
                        }
                    }
                    InterpPart::Expr { expr } => {
                        fmt.push_str("{}");
                        args.push(emit_expr(expr, ctx));
                    }
                }
            }
            if args.is_empty() {
                format!("{fmt:?}.to_string()")
            } else {
                format!("format!({fmt:?}, {})", args.join(", "))
            }
        }
        ExprNode::Send { recv, method, args, block, .. } => {
            emit_send(recv.as_ref(), method.as_str(), args, block.as_ref(), ctx)
        }
        ExprNode::Assign { target: _, value } => emit_expr(value, ctx),
        ExprNode::Seq { exprs } => {
            exprs.iter().map(|e| emit_expr(e, ctx)).collect::<Vec<_>>().join("; ")
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            let cond_s = emit_expr(cond, ctx);
            let then_s = emit_block_body(then_branch, ctx);
            let else_s = emit_block_body(else_branch, ctx);
            format!("if {cond_s} {{\n{then_s}\n}} else {{\n{else_s}\n}}")
        }
        other => format!("/* TODO: emit {:?} */", std::mem::discriminant(other)),
    }
}

/// Emit an expression as the body of a `{ ... }` block, indented one level.
/// For a Seq, each non-tail statement gets a trailing `;`; the tail stays
/// as the block's value expression. For a single expression, emit it alone.
/// Ruby blocks lower to `ExprNode::Lambda` in the IR, so peel one Lambda
/// layer and emit its body — callers treat Ruby `do ... end` as block
/// statements, not as closures.
fn emit_block_body(e: &Expr, ctx: EmitCtx) -> String {
    let inner = match &*e.node {
        ExprNode::Lambda { body, .. } => body,
        _ => e,
    };
    let raw = match &*inner.node {
        ExprNode::Seq { exprs } => {
            let mut lines: Vec<String> = Vec::new();
            for (i, stmt) in exprs.iter().enumerate() {
                if i == exprs.len() - 1 {
                    lines.push(emit_expr(stmt, ctx));
                } else {
                    lines.push(format!("{};", emit_expr(stmt, ctx)));
                }
            }
            lines.join("\n")
        }
        _ => emit_expr(inner, ctx),
    };
    raw.lines().map(|l| format!("    {l}")).collect::<Vec<_>>().join("\n")
}

fn emit_send(
    recv: Option<&Expr>,
    method: &str,
    args: &[Expr],
    block: Option<&Expr>,
    ctx: EmitCtx,
) -> String {
    let args_s: Vec<String> = args.iter().map(|a| emit_expr(a, ctx)).collect();

    // Controller-scope rewrites check first so `params[:id]` doesn't
    // fall through to the generic `recv[args]` sugar (Params has no
    // Index impl).
    if ctx.in_controller {
        if let Some(s) = emit_controller_send(recv, method, args, &args_s, block, ctx) {
            return s;
        }
    }

    // `recv[args]` sugar for the `[]` method.
    if method == "[]" && recv.is_some() {
        return format!("{}[{}]", emit_expr(recv.unwrap(), ctx), args_s.join(", "));
    }

    // Test-scope rewrites, only when ctx.in_test:
    //   - `articles(:one)` bare Send → `fixtures::articles::one()`
    //   - `assert_equal a, b` → `assert_eq!(a, b)`
    //   - `assert_not x` → `assert!(!x)`
    //   - `assert_not_nil x` → type-aware truthiness check
    //   - `Class.new(hash)` where Class is a known model → struct literal
    //   - `owner.assoc.{build,create}(hash)` → struct-literal rewrite
    //   - `assert_difference(expr, delta) { body }` → inline before/after
    if ctx.in_test {
        if let Some(s) = emit_test_send(recv, method, args, &args_s, block, ctx) {
            return s;
        }
    }

    match recv {
        None => {
            // Bare-name Send on implicit self: if the enclosing class has
            // this method/attribute, emit as `self.method` — Ruby's
            // self-dispatch doesn't translate to Rust's bare-name scope.
            // Controllers use `Self::name(...)` (associated fn, no &self)
            // since actions and private helpers are zero-arg free fns.
            if ctx.self_methods.iter().any(|s| s.as_str() == method) {
                if ctx.in_controller {
                    if args_s.is_empty() {
                        return format!("Self::{method}()");
                    } else {
                        return format!("Self::{method}({})", args_s.join(", "));
                    }
                }
                if args_s.is_empty() {
                    return format!("self.{method}");
                } else {
                    return format!("self.{method}({})", args_s.join(", "));
                }
            }
            if args_s.is_empty() {
                method.to_string()
            } else {
                format!("{}({})", method, args_s.join(", "))
            }
        }
        Some(r) => {
            let recv_s = emit_expr(r, ctx);
            // Class method dispatch (`Post.all`) uses `::`; instance method
            // dispatch (`post.title`) uses `.`. Heuristic: constants look
            // class-ish.
            let is_class_call = matches!(&*r.node, ExprNode::Const { .. });
            let sep = if is_class_call { "::" } else { "." };

            // Zero-arg Send on a model struct: a Ruby attribute read like
            // `comment.article_id` is a method call in Ruby but a plain
            // field access in Rust. Emit without parens when:
            //   - recv.ty is Ty::Class (authoritative), OR
            //   - method name matches a known model attribute (fallback
            //     for when the analyzer hasn't populated recv.ty, which
            //     today is the case for test bodies)
            // AND the method isn't a known AR/predicate name.
            if !is_class_call && args_s.is_empty() && !is_known_model_method(method) {
                let recv_is_model = matches!(&r.ty, Some(Ty::Class { .. }));
                let matches_attr = ctx.model_attrs.iter().any(|s| s.as_str() == method);
                if recv_is_model || matches_attr {
                    return format!("{recv_s}.{method}");
                }
            }

            // Ruby→Rust instance-method name mapping (e.g., `String#strip`
            // → `str::trim` + `.to_string()` so the return type stays
            // `String`). Only applies to instance dispatch — class calls
            // keep the Ruby name untouched.
            let (rust_method, suffix) = if is_class_call {
                (method.to_string(), String::new())
            } else {
                map_instance_method(method, r.ty.as_ref())
            };
            if args_s.is_empty() {
                format!("{recv_s}{sep}{rust_method}(){suffix}")
            } else {
                format!("{recv_s}{sep}{rust_method}({}){suffix}", args_s.join(", "))
            }
        }
    }
}

/// Test-scope Send rewrites. Returns `Some(rendered)` when a rule
/// applies, `None` to fall through to the normal emit paths.
fn emit_test_send(
    recv: Option<&Expr>,
    method: &str,
    args: &[Expr],
    args_s: &[String],
    block: Option<&Expr>,
    ctx: EmitCtx,
) -> Option<String> {
    // `assert_difference("Class.count", delta) { body }` — measures the
    // named count expression before and after the block, asserts the
    // delta matches. Rails' convention is a string holding the Ruby
    // expression to re-evaluate; we parse the common `Class.count`
    // shape into `Class::count()` at emit time.
    if recv.is_none() && method == "assert_difference" {
        if let Some(body) = block {
            if let Some(count_expr) = args
                .first()
                .and_then(|a| match &*a.node {
                    ExprNode::Lit { value: Literal::Str { value } } => rewrite_ruby_dot_call(value),
                    _ => None,
                })
            {
                let delta = args_s.get(1).cloned().unwrap_or_else(|| "1_i64".into());
                let body_s = emit_block_body(body, ctx);
                return Some(format!(
                    "{{\n            let _before = {count_expr};\n            {{\n{body_s}\n            }}\n            let _after = {count_expr};\n            assert_eq!(_after - _before, {delta})\n        }}",
                ));
            }
        }
    }
    // `articles(:one)` → `fixtures::articles::one()`
    if recv.is_none()
        && args.len() == 1
        && ctx.fixture_names.iter().any(|s| s.as_str() == method)
    {
        if let ExprNode::Lit { value: Literal::Sym { value: sym } } = &*args[0].node {
            return Some(format!("fixtures::{}::{}()", method, sym.as_str()));
        }
    }

    // Assertion macros.
    if recv.is_none() {
        match (method, args_s.len()) {
            ("assert_equal", 2) => {
                return Some(format!("assert_eq!({}, {})", args_s[0], args_s[1]));
            }
            ("assert_not_equal", 2) => {
                return Some(format!("assert_ne!({}, {})", args_s[0], args_s[1]));
            }
            ("assert_not", 1) => {
                return Some(format!("assert!(!{})", args_s[0]));
            }
            ("assert", 1) => {
                return Some(format!("assert!({})", args_s[0]));
            }
            ("assert_nil", 1) => {
                return Some(emit_assert_nil(&args_s[0], args[0].ty.as_ref(), false));
            }
            ("assert_not_nil", 1) => {
                return Some(emit_assert_nil(&args_s[0], args[0].ty.as_ref(), true));
            }
            _ => {}
        }
    }

    // `owner.<assoc>.create(hash)` / `.build(hash)` — HasMany association
    // surface. Rewrite to a struct-literal of the target model with the
    // foreign key pre-filled from `owner.id`, plus `save()` for the
    // `create` variant. No runtime association proxy required.
    if (method == "create" || method == "build") && args.len() == 1 {
        if let Some(outer_recv) = recv {
            if let ExprNode::Send { recv: Some(assoc_recv), method: assoc_method, args: inner_args, .. } = &*outer_recv.node {
                if inner_args.is_empty() {
                    if let Some(s) = try_emit_assoc_create(
                        assoc_recv,
                        assoc_method.as_str(),
                        args,
                        method,
                        ctx,
                    ) {
                        return Some(s);
                    }
                }
            }
        }
    }

    // `Class.new(hash)` → struct literal when Class is a known model.
    if let Some(r) = recv {
        if method == "new" && args.len() == 1 {
            if let ExprNode::Const { path } = &*r.node {
                if let Some(class_name) = path.last() {
                    if ctx.known_models.iter().any(|s| s == class_name) {
                        if let ExprNode::Hash { entries, .. } = &*args[0].node {
                            let mut fields: Vec<String> = Vec::new();
                            for (k, v) in entries {
                                if let ExprNode::Lit {
                                    value: Literal::Sym { value: field_name },
                                } = &*k.node
                                {
                                    fields.push(format!(
                                        "            {}: {},",
                                        field_name.as_str(),
                                        emit_expr(v, ctx)
                                    ));
                                }
                            }
                            return Some(format!(
                                "{} {{\n{}\n            ..Default::default()\n        }}",
                                class_name,
                                fields.join("\n"),
                            ));
                        }
                    }
                }
            }
        }
    }

    None
}

/// Parse a Ruby-style `"Class.method"` expression string into Rust
/// `Class::method()` syntax, for use inside `assert_difference` and
/// similar helpers that take a string expression. Returns `None` for
/// shapes we don't handle; caller falls back to a TODO.
fn rewrite_ruby_dot_call(expr: &str) -> Option<String> {
    let trimmed = expr.trim();
    let (lhs, rhs) = trimmed.split_once('.')?;
    let is_ident = |s: &str| {
        !s.is_empty() && s.chars().next().is_some_and(|c| c.is_alphabetic() || c == '_')
            && s.chars().all(|c| c.is_alphanumeric() || c == '_')
    };
    if !is_ident(lhs) || !is_ident(rhs) {
        return None;
    }
    // Capitalized LHS looks like a class name → `Class::method()`.
    // Lowercase LHS looks like an instance → `lhs.method()`.
    let is_class = lhs.chars().next().is_some_and(|c| c.is_uppercase());
    if is_class {
        Some(format!("{lhs}::{rhs}()"))
    } else {
        Some(format!("{lhs}.{rhs}"))
    }
}

/// Controller-scope Send rewrites. Drives off the shared classifier
/// `lower::classify_controller_send`; every arm below is a
/// render-table entry from `SendKind` → Rust syntax. Returns `None`
/// when the classifier doesn't match (falls through to plain Send).
fn emit_controller_send(
    recv: Option<&Expr>,
    method: &str,
    args: &[Expr],
    args_s: &[String],
    block: Option<&Expr>,
    ctx: EmitCtx,
) -> Option<String> {
    use crate::lower::SendKind;
    let kind =
        crate::lower::classify_controller_send(recv, method, args, block, ctx.known_models)?;
    Some(match kind {
        SendKind::ParamsAccess => "crate::http::params()".to_string(),

        SendKind::ParamsExpect { .. } => "todo!(\"params.expect\")".to_string(),

        SendKind::ParamsIndex { .. } => {
            let arg = args_s.first().cloned().unwrap_or_default();
            format!("crate::http::params().expect({arg})")
        }

        SendKind::ModelNew { class } => format!("{}::default()", class.as_str()),

        SendKind::ModelFind { class, .. } => {
            let arg = args_s.first().cloned().unwrap_or_default();
            format!("{}::find({arg}).unwrap_or_default()", class.as_str())
        }

        SendKind::AssocLookup { target, .. } => format!("{}::default()", target.as_str()),

        SendKind::QueryChain { target: Some(target), .. } => {
            format!("Vec::<{}>::new()", target.as_str())
        }
        SendKind::QueryChain { target: None, .. } => "todo!(\"query chain\")".to_string(),

        SendKind::PathOrUrlHelper => "todo!(\"route helper\")".to_string(),

        SendKind::BangStrip { recv, stripped_method, .. } => {
            let recv_s = emit_expr(recv, ctx);
            format!("{recv_s}.{stripped_method}()")
        }

        SendKind::InstanceUpdate => "todo!(\"Model::update\")".to_string(),

        SendKind::Render { .. } => {
            let arg = args_tuple_or_single(args_s);
            format!("crate::http::render({arg})")
        }

        SendKind::RedirectTo { .. } => match args_s.len() {
            0 => "crate::http::redirect_to(())".to_string(),
            1 => format!("crate::http::redirect_to({})", args_s[0]),
            _ => format!(
                "crate::http::redirect_to_with({}, ({}))",
                args_s[0],
                args_s[1..].join(", "),
            ),
        },

        SendKind::Head { .. } => {
            let arg = args_tuple_or_single(args_s);
            format!("crate::http::head({arg})")
        }

        SendKind::RespondToBlock { body } => {
            let body_rendered = emit_respond_to_body(body, ctx);
            let indented = body_rendered
                .lines()
                .map(|l| format!("    {l}"))
                .collect::<Vec<_>>()
                .join("\n");
            format!(
                "crate::http::respond_to(|__fr| {{\n{indented}\n    Response::default()\n}})"
            )
        }

        SendKind::FormatHtml { body } => {
            // Re-wrap in a synthetic expr so emit_block_body sees the
            // same shape it did under the old code path (a Seq or
            // single expr as the block body).
            let body_s = emit_block_body(body, ctx);
            format!("__fr.html(|| {{\n{body_s}\n}})")
        }

        SendKind::FormatJson => {
            "/* TODO: JSON branch (Phase 4e) */ Response::default()".to_string()
        }
    })
}

/// Render a `respond_to` block body. The body is usually an
/// `if article.save ... else ... end` with `format.html/.json` calls
/// in each branch. We emit each such call as a `;`-terminated
/// statement against `__fr` (for `.html`) or a TODO comment (for
/// `.json`), then let the outer emitter append `Response::default()`.
fn emit_respond_to_body(body: &Expr, ctx: EmitCtx) -> String {
    match &*body.node {
        ExprNode::Seq { exprs } if !exprs.is_empty() => exprs
            .iter()
            .map(|e| format!("{};", emit_expr(e, ctx)))
            .collect::<Vec<_>>()
            .join("\n"),
        ExprNode::If { cond, then_branch, else_branch } => {
            // Recurse into branches so nested `format.*` calls still
            // get rewritten. Tail of the if-else is discarded; the
            // outer emitter emits `Response::default()` after.
            let cond_s = emit_expr(cond, ctx);
            let then_s = emit_respond_to_body(then_branch, ctx)
                .lines()
                .map(|l| format!("    {l}"))
                .collect::<Vec<_>>()
                .join("\n");
            let else_s = emit_respond_to_body(else_branch, ctx)
                .lines()
                .map(|l| format!("    {l}"))
                .collect::<Vec<_>>()
                .join("\n");
            format!("if {cond_s} {{\n{then_s}\n}} else {{\n{else_s}\n}};")
        }
        _ => format!("{};", emit_expr(body, ctx)),
    }
}

/// When a `render`/`head` call has a single arg, pass it through as-is.
/// Multiple args pack into a tuple the stub's generic `T` accepts.
fn args_tuple_or_single(args_s: &[String]) -> String {
    match args_s.len() {
        0 => "()".to_string(),
        1 => args_s[0].clone(),
        _ => format!("({})", args_s.join(", ")),
    }
}

/// Rewrite `owner.<assoc>.create(hash)` / `.build(hash)` into a
/// struct-literal construction of the target model, with the foreign
/// key prefilled from `owner.id`. Returns `None` when the pattern
/// doesn't apply (e.g. we can't identify `<assoc>` as a HasMany on any
/// known model) so callers fall through to generic emission.
fn try_emit_assoc_create(
    owner: &Expr,
    assoc_name: &str,
    args: &[Expr],
    outer_method: &str,
    ctx: EmitCtx,
) -> Option<String> {
    let app = ctx.app?;
    let resolved = crate::lower::resolve_has_many(
        &Symbol::from(assoc_name),
        owner.ty.as_ref(),
        app,
    )?;
    let target_class = resolved.target_class.0.as_str();
    let foreign_key = resolved.foreign_key.as_str();

    let owner_s = emit_expr(owner, ctx);
    let hash_entries = match &args.first()?.node.as_ref() {
        ExprNode::Hash { entries, .. } => entries.clone(),
        _ => return None,
    };

    let mut field_lines: Vec<String> = Vec::new();
    field_lines.push(format!("                {foreign_key}: {owner_s}.id,"));
    for (k, v) in &hash_entries {
        if let ExprNode::Lit { value: Literal::Sym { value: field_name } } = &*k.node {
            field_lines.push(format!(
                "                {}: {},",
                field_name.as_str(),
                emit_expr(v, ctx),
            ));
        }
    }

    let struct_lit = format!(
        "{target_class} {{\n{}\n                ..Default::default()\n            }}",
        field_lines.join("\n"),
    );
    // `.build` returns the unsaved record; `.create` saves it first.
    // Both yield the record so tests can read `.article_id` etc. The
    // `let mut` is needed for the `save()` path; harmless for build.
    let body = if outer_method == "create" {
        format!(
            "{{\n            let mut r = {struct_lit};\n            r.save();\n            r\n        }}"
        )
    } else {
        format!("{{\n            let mut r = {struct_lit};\n            r\n        }}")
    };
    Some(body)
}

/// Render an `assert_not_nil` (or `assert_nil`) with type-aware truthiness.
/// Truthy side when `expect_present` is true (assert_not_nil); falsy side
/// otherwise (assert_nil). Ruby's `nil?` has no universal Rust equivalent —
/// the right check depends on the value's type.
fn emit_assert_nil(expr: &str, ty: Option<&Ty>, expect_present: bool) -> String {
    let (truthy, falsy) = match ty {
        Some(Ty::Int) | Some(Ty::Float) => (
            format!("{expr} != 0"),
            format!("{expr} == 0"),
        ),
        Some(Ty::Str) => (
            format!("!{expr}.is_empty()"),
            format!("{expr}.is_empty()"),
        ),
        Some(Ty::Union { variants }) if variants.iter().any(|v| matches!(v, Ty::Nil)) => {
            (format!("{expr}.is_some()"), format!("{expr}.is_none()"))
        }
        _ => (
            format!("/* TODO: assert_nil on unknown ty */ true"),
            format!("/* TODO: assert_nil on unknown ty */ false"),
        ),
    };
    if expect_present {
        format!("assert!({truthy})")
    } else {
        format!("assert!({falsy})")
    }
}

/// Methods that are calls with parens on an emitted model struct (not
/// attribute reads). Used by emit_send to decide whether a zero-arg
/// Send should render as `x.method()` or as `x.method` field access.
/// Custom user-defined methods on a specific model would ideally extend
/// this list; for now the AR core + predicates covers real-blog.
fn is_known_model_method(name: &str) -> bool {
    matches!(
        name,
        "save" | "save!" | "destroy" | "destroy!" | "update" | "update!"
            | "delete" | "touch" | "reload" | "valid?" | "invalid?"
            | "persisted?" | "new_record?" | "destroyed?" | "changed?"
            | "validate" | "attributes" | "errors"
    )
}

/// Map a Ruby instance-method call to its Rust equivalent, returning the
/// Rust method name and an optional call-site suffix (commonly `.to_string()`
/// when a `&str`-returning Rust method replaces a `String`-returning Ruby
/// one). Grows as new fixtures surface new cases; unmapped methods pass
/// through with their Ruby name.
fn map_instance_method(method: &str, recv_ty: Option<&Ty>) -> (String, String) {
    match recv_ty {
        Some(Ty::Str) => match method {
            // Ruby's `strip` returns a new String; Rust's `trim` returns
            // `&str`. Wrap in `.to_string()` so the type matches.
            "strip" => ("trim".into(), ".to_string()".into()),
            _ => (method.into(), String::new()),
        },
        _ => (method.into(), String::new()),
    }
}
