//! Fixtures — emit YAML fixtures as Rust modules of labeled accessor
//! fns returning struct instances, plus the `src/fixtures/mod.rs`
//! entry point (`setup`) every emitted test calls first.

use std::fmt::Write;
use std::path::PathBuf;

use crate::ty::Ty;

use super::super::EmittedFile;

/// Emit a single `src/fixtures/<name>.rs` file — one `pub fn <label>()`
/// accessor per fixture record, returning the corresponding model
/// struct. IDs are assigned sequentially from 1 (Rails hashes labels
/// into ints; we assign in insertion order for simplicity).
pub(super) fn emit_rust_fixture(lowered: &crate::lower::LoweredFixture) -> EmittedFile {
    let fixture_name = lowered.name.as_str();
    let class_name = lowered.class.0.as_str();

    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "use crate::models::{};", class_name).unwrap();

    // `_load_all` — invoked from `crate::fixtures::setup()` at the top
    // of every test. Inserts each record via the model's `save` (so
    // validations apply), captures the AUTOINCREMENT id, and records
    // it in the shared FIXTURE_IDS map so associated fixtures and
    // test getters can look each record up by label.
    writeln!(s).unwrap();
    writeln!(s, "pub fn _load_all() {{").unwrap();
    for record in &lowered.records {
        let label = record.label.as_str();
        writeln!(s, "    let mut r = {} {{", class_name).unwrap();
        for field in &record.fields {
            let col = field.column.as_str();
            let rust_val = match &field.value {
                crate::lower::LoweredFixtureValue::Literal { ty, raw } => {
                    rust_literal_for(raw, ty)
                }
                crate::lower::LoweredFixtureValue::FkLookup {
                    target_fixture,
                    target_label,
                } => format!(
                    "crate::fixtures::fixture_id({:?}, {:?})",
                    target_fixture.as_str(),
                    target_label.as_str(),
                ),
            };
            writeln!(s, "        {col}: {rust_val},").unwrap();
        }
        writeln!(s, "        ..Default::default()").unwrap();
        writeln!(s, "    }};").unwrap();
        writeln!(
            s,
            "    assert!(r.save(), \"fixture {fixture_name}/{label} failed to save\");",
        )
        .unwrap();
        writeln!(
            s,
            "    crate::fixtures::FIXTURE_IDS.with(|m| {{ m.borrow_mut().insert(({fixture_name:?}, {label:?}), r.id); }});",
        )
        .unwrap();
    }
    writeln!(s, "}}").unwrap();

    // Named-fixture getters — `articles::one()` reads back the record
    // this thread's `_load_all` inserted. A failed `find` means the
    // test forgot to call `crate::fixtures::setup()` or the schema
    // doesn't match the model's field list.
    for record in &lowered.records {
        let label = record.label.as_str();
        writeln!(s).unwrap();
        writeln!(s, "pub fn {label}() -> {class_name} {{").unwrap();
        writeln!(
            s,
            "    let id = crate::fixtures::fixture_id({fixture_name:?}, {label:?});",
        )
        .unwrap();
        writeln!(
            s,
            "    {class_name}::find(id).expect(\"fixture {fixture_name}/{label} not loaded — call crate::fixtures::setup() first\")",
        )
        .unwrap();
        writeln!(s, "}}").unwrap();
    }

    EmittedFile {
        path: PathBuf::from(format!("src/fixtures/{fixture_name}.rs")),
        content: s,
    }
}

/// `src/fixtures/mod.rs` — declares the per-table fixture modules plus
/// the test-harness entry point (`setup`) that every emitted test
/// calls first. Owns the thread-local (fixture_name, label) → DB id
/// map that fixture getters and cross-fixture belongs_to refs read
/// through at runtime.
pub(super) fn emit_fixtures_mod(lowered: &crate::lower::LoweredFixtureSet) -> EmittedFile {
    let fixtures = &lowered.fixtures;
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "use std::cell::RefCell;").unwrap();
    writeln!(s, "use std::collections::HashMap;").unwrap();
    writeln!(s).unwrap();
    for fixture in fixtures {
        writeln!(s, "pub mod {};", fixture.name).unwrap();
    }
    writeln!(s).unwrap();
    writeln!(s, "thread_local! {{").unwrap();
    writeln!(
        s,
        "    pub static FIXTURE_IDS: RefCell<HashMap<(&'static str, &'static str), i64>> ="
    )
    .unwrap();
    writeln!(s, "        RefCell::new(HashMap::new());").unwrap();
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
    writeln!(
        s,
        "/// Per-test entry point. Opens a fresh :memory: SQLite connection,"
    )
    .unwrap();
    writeln!(
        s,
        "/// runs the schema DDL, and loads every fixture in declaration order."
    )
    .unwrap();
    writeln!(
        s,
        "/// Idempotent across repeat calls on the same thread — each call replaces"
    )
    .unwrap();
    writeln!(s, "/// the prior connection, so tests start from a clean slate.").unwrap();
    writeln!(s, "pub fn setup() {{").unwrap();
    writeln!(
        s,
        "    crate::db::setup_test_db(crate::schema_sql::CREATE_TABLES);"
    )
    .unwrap();
    writeln!(s, "    FIXTURE_IDS.with(|m| m.borrow_mut().clear());").unwrap();
    for fixture in fixtures {
        writeln!(s, "    {}::_load_all();", fixture.name).unwrap();
    }
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "pub fn fixture_id(fixture: &'static str, label: &'static str) -> i64 {{").unwrap();
    writeln!(s, "    FIXTURE_IDS.with(|m| {{").unwrap();
    writeln!(s, "        *m.borrow().get(&(fixture, label)).unwrap_or_else(|| {{").unwrap();
    writeln!(
        s,
        "            panic!(\"fixture {{}}:{{}} not loaded\", fixture, label)"
    )
    .unwrap();
    writeln!(s, "        }})").unwrap();
    writeln!(s, "    }})").unwrap();
    writeln!(s, "}}").unwrap();
    EmittedFile {
        path: PathBuf::from("src/fixtures/mod.rs"),
        content: s,
    }
}


/// Render a fixture field value as a Rust literal matching the column's
/// static type. Strings go via `"..".to_string()` to produce `String`
/// instead of `&'static str`; numbers and bools pass through as-is.
fn rust_literal_for(value: &str, ty: &Ty) -> String {
    match ty {
        Ty::Str | Ty::Sym => format!("{value:?}.to_string()"),
        Ty::Int => {
            if value.parse::<i64>().is_ok() {
                format!("{value}_i64")
            } else {
                format!("0_i64 /* TODO: coerce {value:?} */")
            }
        }
        Ty::Float => {
            if value.parse::<f64>().is_ok() {
                format!("{value}_f64")
            } else {
                format!("0.0_f64 /* TODO: coerce {value:?} */")
            }
        }
        Ty::Bool => match value {
            "true" | "1" => "true".into(),
            "false" | "0" => "false".into(),
            _ => format!("false /* TODO: coerce {value:?} */"),
        },
        Ty::Class { id, .. } if id.0.as_str() == "Time" => format!("{value:?}.to_string()"),
        _ => format!("{value:?}.to_string()"),
    }
}
