//! Emit `src/importmap.rs` — the app's ingested importmap pins as a
//! static `PINS` slice. The layout's `javascript_importmap_tags`
//! helper call passes this slice in. Mirrors the TS target's
//! `src/importmap.ts` emit.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use crate::App;

/// Emit `src/importmap.rs` — the app's ingested importmap pins
/// as a static `PINS` slice. The layout's `javascript_importmap_
/// tags` helper call passes this slice in. Mirrors the TS
/// target's `src/importmap.ts` emit.
pub(super) fn emit_rust_importmap(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s).unwrap();
    writeln!(
        s,
        "pub static PINS: &[(&str, &str)] = &["
    )
    .unwrap();
    if let Some(importmap) = &app.importmap {
        for pin in &importmap.pins {
            writeln!(s, "    ({:?}, {:?}),", pin.name, pin.path).unwrap();
        }
    }
    writeln!(s, "];").unwrap();
    EmittedFile {
        path: PathBuf::from("src/importmap.rs"),
        content: s,
    }
}
