//! `src/main.rs` — server entry point. Opens the DB, applies the
//! schema, and starts axum with the generated router. Uses
//! `#[tokio::main]` so tokio's multi-thread runtime bootstraps
//! before calling into `server::start`, which needs the runtime
//! active to bind the listener.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use crate::App;
use crate::naming::snake_case;

pub(super) fn emit_main_rs(app: &App) -> EmittedFile {
    let has_app_layout = app
        .views
        .iter()
        .any(|v| v.name.as_str() == "layouts/application");
    let layout_import = if has_app_layout {
        "use app::views::layouts_application;\n"
    } else {
        ""
    };
    let layout_field = if has_app_layout {
        "            layout: Some(|| layouts_application(&())),\n"
    } else {
        "            layout: None,\n"
    };

    // Register a partial renderer for each model that broadcasts.
    // `crate::cable::broadcast_{prepend,append,replace}_to` calls
    // `render_partial(type_name, id)` internally; we connect it
    // here to the model's actual view partial. Models without
    // broadcasts skip registration — their records never trigger
    // a partial render through the cable path.
    let mut partial_registrations = String::new();
    for model in &app.models {
        if crate::lower::lower_broadcasts(model).is_empty() {
            continue;
        }
        let class = model.name.0.as_str();
        let singular = snake_case(class);
        writeln!(
            partial_registrations,
            "    app::cable::register_partial({class:?}, |id| {{\n        match app::models::{class}::find(id) {{\n            Some(r) => app::views::render_{singular}(&r),\n            None => String::new(),\n        }}\n    }});",
        )
        .unwrap();
    }
    let partial_section = if partial_registrations.is_empty() {
        String::new()
    } else {
        format!("\n{partial_registrations}")
    };

    let content = format!(
        "// Generated by Roundhouse.

use app::{{router, schema_sql, server}};
{layout_import}
#[tokio::main]
async fn main() {{
    let db_path = std::env::var(\"DATABASE_PATH\").ok();
    let port = std::env::var(\"PORT\").ok().and_then(|s| s.parse().ok());
{partial_section}    server::start(
        router::router(),
        server::StartOptions {{
            db_path,
            port,
            schema_sql: schema_sql::CREATE_TABLES,
{layout_field}        }},
    )
    .await;
}}
"
    );
    EmittedFile {
        path: PathBuf::from("src/main.rs"),
        content,
    }
}
