//! Routes — emit `src/router.rs` with `pub fn router() -> Router`
//! wiring the route table to the controller action fns, plus
//! `src/route_helpers.rs` with one `pub fn` per route that takes the
//! route's typed path params and returns a String (used by both the
//! emitted controller actions for redirects and the emitted tests for
//! URLs).

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use crate::App;
use crate::dialect::HttpMethod;
use crate::lower::FlatRoute;
use crate::naming::snake_case;

/// Emit `src/router.rs` — `pub fn router() -> Router` wiring the
/// flat route table to controller action fns. Groups routes by path
/// so axum's MethodRouter chain (`.get(...).post(...)`) handles
/// multi-verb endpoints correctly.
pub(super) fn emit_router(app: &App) -> EmittedFile {
    let flat = crate::lower::flatten_routes(app);
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "use axum::Router;").unwrap();
    writeln!(s, "use axum::routing::{{delete, get, patch, post}};").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "use crate::controllers;").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "pub fn router() -> Router {{").unwrap();
    writeln!(s, "    Router::new()").unwrap();

    // Group by axum path (translated from Rails' `:id` to axum's
    // `{id}`) so we can stack MethodRouters per path.
    use std::collections::BTreeMap;
    let mut by_path: BTreeMap<String, Vec<&FlatRoute>> = BTreeMap::new();
    for route in &flat {
        by_path
            .entry(to_axum_path(&route.path))
            .or_default()
            .push(route);
    }
    for (path, routes) in &by_path {
        let verbs: Vec<String> = routes
            .iter()
            .map(|r| {
                let handler_path = controller_module_path(r.controller.0.as_str());
                let verb = axum_verb_fn(&r.method);
                format!("{verb}({handler_path}::{})", r.action)
            })
            .collect();
        writeln!(s, "        .route(\"{path}\", {})", verbs.join(".")).unwrap();
    }
    writeln!(s, "}}").unwrap();
    EmittedFile {
        path: PathBuf::from("src/router.rs"),
        content: s,
    }
}

/// Translate `/articles/:id` → `/articles/{id}` for axum 0.8.
fn to_axum_path(rails_path: &str) -> String {
    let mut out = String::new();
    let mut chars = rails_path.chars().peekable();
    while let Some(c) = chars.next() {
        if c == ':' {
            let mut ident = String::new();
            while let Some(&nc) = chars.peek() {
                if nc.is_alphanumeric() || nc == '_' {
                    ident.push(nc);
                    chars.next();
                } else {
                    break;
                }
            }
            out.push('{');
            out.push_str(&ident);
            out.push('}');
        } else {
            out.push(c);
        }
    }
    out
}

fn axum_verb_fn(method: &HttpMethod) -> &'static str {
    match method {
        HttpMethod::Get => "get",
        HttpMethod::Post => "post",
        HttpMethod::Put => "put",
        HttpMethod::Patch => "patch",
        HttpMethod::Delete => "delete",
        _ => "get",
    }
}

fn controller_module_path(class: &str) -> String {
    format!("controllers::{}", snake_case(class))
}

/// Emit `src/route_helpers.rs` — one `pub fn <as_name>_path(...)` per
/// flattened route (indexed by `as_name`, which is already unique
/// per path shape). Path params are `i64` by convention (Rails'
/// default integer primary key).
pub(super) fn emit_route_helpers(app: &App) -> EmittedFile {
    let flat = crate::lower::flatten_routes(app);
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s).unwrap();

    // One entry per unique `as_name`. If two routes share a name
    // (e.g. index + create on the same path), they also share a
    // path so one helper suffices — emit in first-seen order.
    use std::collections::BTreeSet;
    let mut seen: BTreeSet<String> = BTreeSet::new();
    for route in &flat {
        if !seen.insert(route.as_name.clone()) {
            continue;
        }
        let sig_params: Vec<String> = route
            .path_params
            .iter()
            .map(|p| format!("{p}: i64"))
            .collect();
        let sig = sig_params.join(", ");

        // Body: literal path segments + `format!` interpolation
        // when there are params.
        let body = if route.path_params.is_empty() {
            format!("{:?}.to_string()", route.path)
        } else {
            // Rails' `:param` → Rust's `{}` in a format! string.
            let mut fmt = String::new();
            let mut chars = route.path.chars().peekable();
            while let Some(c) = chars.next() {
                if c == ':' {
                    while let Some(&nc) = chars.peek() {
                        if nc.is_alphanumeric() || nc == '_' {
                            chars.next();
                        } else {
                            break;
                        }
                    }
                    fmt.push_str("{}");
                } else {
                    fmt.push(c);
                }
            }
            format!("format!({fmt:?}, {})", route.path_params.join(", "))
        };

        writeln!(
            s,
            "pub fn {}_path({sig}) -> String {{ {body} }}",
            route.as_name,
        )
        .unwrap();
    }
    EmittedFile {
        path: PathBuf::from("src/route_helpers.rs"),
        content: s,
    }
}
