//! Emit `src/schema_sql.rs` — the target-neutral DDL produced by
//! `emit::shared::schema_sql` wrapped in a `pub const CREATE_TABLES`.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use crate::App;

/// Emit `src/schema_sql.rs` — a single `pub const CREATE_TABLES: &str`
/// wrapping the target-neutral DDL produced by `emit::shared::schema_sql`.
/// The Phase 3 test harness executes this string on a fresh `:memory:`
/// connection per test. FK declarations stay at the AR layer (via
/// `belongs_to` existence checks and `dependent: :destroy` cascades in
/// model methods), not as SQLite `FOREIGN KEY` constraints — Rails'
/// `dependent:` is an ActiveRecord callback, mirroring it at the DB
/// layer would drift from Rails semantics.
pub(super) fn emit_schema_sql(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "pub const CREATE_TABLES: &str = r#\"").unwrap();
    write!(s, "{}", crate::emit::shared::schema_sql::render_schema_sql(&app.schema)).unwrap();
    writeln!(s, "\"#;").unwrap();
    EmittedFile {
        path: PathBuf::from("src/schema_sql.rs"),
        content: s,
    }
}
