//! Views — translate compiled-ERB IR into Rust view fns.

use std::fmt::Write;
use std::path::PathBuf;

use crate::App;
use crate::expr::{Expr, ExprNode, LValue, Literal};
use crate::ident::Symbol;

use super::super::EmittedFile;
use super::emit_literal;

pub(super) fn emit_views(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s, "#![allow(unused_imports, unused_variables, unused_mut)]").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "use crate::models::*;").unwrap();
    writeln!(s, "use crate::route_helpers;").unwrap();
    writeln!(s, "use crate::view_helpers::{{self, FormBuilder, RenderCtx}};").unwrap();
    writeln!(s).unwrap();

    let has_manys = crate::lower::build_has_many_table(app);

    let view_ctx = ViewEmitCtx {
        known_models: app.models.iter().map(|m| m.name.0.clone()).collect(),
        locals: Vec::new(),
        local_attrs: Vec::new(),
        arg_name: String::new(),
        resource_dir: String::new(),
        form_records: Vec::new(),
        stylesheets: app.stylesheets.clone(),
        has_manys,
    };

    let attrs_by_class: std::collections::BTreeMap<String, Vec<Symbol>> = app
        .models
        .iter()
        .map(|m| {
            (
                m.name.0.as_str().to_string(),
                m.attributes.fields.keys().cloned().collect(),
            )
        })
        .collect();
    let attrs_by_class = &attrs_by_class;

    for view in &app.views {
        emit_view_fn(&mut s, view, &view_ctx, attrs_by_class);
        writeln!(s).unwrap();
    }

    emit_missing_view_stubs(&mut s, app, &view_ctx);

    EmittedFile {
        path: PathBuf::from("src/views.rs"),
        content: s,
    }
}

#[derive(Clone)]
struct ViewEmitCtx {
    known_models: Vec<Symbol>,
    locals: Vec<String>,
    local_attrs: Vec<(String, Vec<Symbol>)>,
    arg_name: String,
    resource_dir: String,
    form_records: Vec<(String, String)>,
    stylesheets: Vec<String>,
    has_manys: Vec<crate::lower::HasManyRow>,
}

impl ViewEmitCtx {
    fn with_locals(&self, more: impl IntoIterator<Item = String>) -> Self {
        let mut next = self.clone();
        for n in more {
            if !next.locals.iter().any(|x| x == &n) {
                next.locals.push(n);
            }
        }
        next
    }

    fn with_local_attrs(&self, name: String, attrs: Vec<Symbol>) -> Self {
        let mut next = self.clone();
        if !next.locals.iter().any(|x| x == &name) {
            next.locals.push(name.clone());
        }
        next.local_attrs.retain(|(n, _)| n != &name);
        next.local_attrs.push((name, attrs));
        next
    }

    fn is_local(&self, name: &str) -> bool {
        self.locals.iter().any(|x| x == name)
    }

    fn local_has_attr(&self, local: &str, attr: &str) -> bool {
        self.local_attrs
            .iter()
            .find(|(n, _)| n == local)
            .map(|(_, attrs)| attrs.iter().any(|a| a.as_str() == attr))
            .unwrap_or(false)
    }

    fn resolve_has_many_on_local(&self, local: &str, assoc: &str) -> Option<(String, String)> {
        if !self.is_local(local) {
            return None;
        }
        crate::lower::resolve_has_many_on_local(&self.has_manys, local, assoc)
    }
}

fn emit_view_fn(
    out: &mut String,
    view: &crate::dialect::View,
    ctx: &ViewEmitCtx,
    attrs_by_class: &std::collections::BTreeMap<String, Vec<Symbol>>,
) {
    let name = view.name.as_str();
    let (fn_name, sig, arg_name) = view_fn_signature(name, ctx);
    writeln!(out, "pub fn {fn_name}({sig}) -> String {{").unwrap();
    writeln!(out, "    let mut _buf = String::new();").unwrap();
    writeln!(out, "    let ctx = RenderCtx::default();").unwrap();

    let model_class = arg_model_class(name, ctx);
    let resource_dir = name.split('/').next().unwrap_or("").to_string();
    let mut scoped = if let Some(class) = model_class {
        let attrs = attrs_by_class.get(&class).cloned().unwrap_or_default();
        ctx.with_local_attrs(arg_name.clone(), attrs)
    } else {
        ctx.with_locals([arg_name.clone()])
    };
    scoped.arg_name = arg_name.clone();
    scoped.resource_dir = resource_dir;
    scoped = scoped.with_locals(["_buf".to_string(), "ctx".to_string()]);

    let trimmed_body = crate::lower::erb_trim::trim_view(&view.body);
    let stmts: Vec<&Expr> = match &*trimmed_body.node {
        ExprNode::Seq { exprs } => exprs.iter().collect(),
        _ => vec![&trimmed_body],
    };
    for stmt in &stmts {
        for line in emit_view_stmt_rust(stmt, &scoped, "_buf") {
            writeln!(out, "    {line}").unwrap();
        }
    }
    writeln!(out, "    _buf").unwrap();
    writeln!(out, "}}").unwrap();
}

fn emit_missing_view_stubs(out: &mut String, app: &App, ctx: &ViewEmitCtx) {
    use std::collections::BTreeSet;
    let present: BTreeSet<String> =
        app.views.iter().map(|v| v.name.as_str().to_string()).collect();
    for model in &app.models {
        if model.attributes.fields.is_empty() {
            continue;
        }
        let class = model.name.0.as_str();
        let plural = crate::naming::pluralize_snake(class);
        for action in ["index", "show", "new", "edit"] {
            let name = format!("{plural}/{action}");
            if present.contains(&name) {
                continue;
            }
            let (fn_name, sig, _arg) = view_fn_signature(&name, ctx);
            writeln!(out, "pub fn {fn_name}({sig}) -> String {{").unwrap();
            writeln!(out, "    String::new()").unwrap();
            writeln!(out, "}}").unwrap();
            writeln!(out).unwrap();
        }
    }
}

fn arg_model_class(view_name: &str, ctx: &ViewEmitCtx) -> Option<String> {
    let (dir, _) = view_name.rsplit_once('/').unwrap_or(("", view_name));
    let class = crate::naming::singularize_camelize(dir);
    if ctx.known_models.iter().any(|m| m.as_str() == class) {
        Some(class)
    } else {
        None
    }
}

fn view_fn_signature(name: &str, ctx: &ViewEmitCtx) -> (String, String, String) {
    let (dir, base) = name.rsplit_once('/').unwrap_or(("", name));
    let resource = dir;
    let is_partial = base.starts_with('_');
    let stem = base.trim_start_matches('_');
    let model_class = crate::naming::singularize_camelize(resource);
    let model_exists = ctx.known_models.iter().any(|m| m.as_str() == model_class);
    let singular = crate::naming::singularize(resource);

    if is_partial {
        let fn_name = format!("render_{stem}");
        let (arg_name, arg_ty) = if model_exists {
            (singular.clone(), format!("{singular}: &{model_class}"))
        } else {
            (stem.to_string(), format!("{stem}: &crate::models::{model_class}"))
        };
        (fn_name, arg_ty, arg_name)
    } else {
        let fn_name = format!("{resource}_{stem}");
        let (arg_name, sig) = match stem {
            "index" => {
                if model_exists {
                    (resource.to_string(), format!("{resource}: &[{model_class}]"))
                } else {
                    (resource.to_string(), format!("{resource}: &[()]"))
                }
            }
            _ => {
                if model_exists {
                    (singular.clone(), format!("{singular}: &{model_class}"))
                } else {
                    (singular.clone(), format!("{singular}: &()"))
                }
            }
        };
        (fn_name, sig, arg_name)
    }
}

fn emit_view_stmt_rust(stmt: &Expr, ctx: &ViewEmitCtx, buf_name: &str) -> Vec<String> {
    match &*stmt.node {
        ExprNode::Assign { target: LValue::Var { name, .. }, value }
            if name.as_str() == buf_name =>
        {
            if let ExprNode::Lit { value: Literal::Str { value: s } } = &*value.node {
                if s.is_empty() {
                    return Vec::new();
                }
            }
            if let ExprNode::Send { recv: Some(recv), method, args, .. } = &*value.node {
                if method.as_str() == "+" && args.len() == 1 {
                    if let ExprNode::Var { name: rn, .. } = &*recv.node {
                        if rn.as_str() == buf_name {
                            return emit_view_append(&args[0], ctx, buf_name);
                        }
                    }
                }
            }
            vec![format!("/* unexpected _buf shape */ {};", emit_view_expr(stmt, ctx))]
        }
        ExprNode::Var { name, .. } if name.as_str() == buf_name => Vec::new(),
        ExprNode::If { cond, then_branch, else_branch } => {
            let cond_s = if is_simple_view_expr(cond, ctx) {
                emit_view_expr_raw(cond, ctx)
            } else {
                "false /* TODO ERB cond */".to_string()
            };
            let mut out = vec![format!("if {cond_s} {{")];
            for line in emit_view_branch_rust(then_branch, ctx, buf_name) {
                out.push(format!("    {line}"));
            }
            let has_else = !matches!(
                &*else_branch.node,
                ExprNode::Lit { value: Literal::Nil }
            );
            if has_else {
                out.push("} else {".to_string());
                for line in emit_view_branch_rust(else_branch, ctx, buf_name) {
                    out.push(format!("    {line}"));
                }
            }
            out.push("}".to_string());
            out
        }
        ExprNode::Send { recv: None, method, args, block: None, .. }
            if matches!(
                crate::lower::classify_view_helper(method.as_str(), args),
                Some(crate::lower::ViewHelperKind::ContentForSetter { .. })
            ) =>
        {
            if let Some(crate::lower::ViewHelperKind::ContentForSetter { slot, body }) =
                crate::lower::classify_view_helper(method.as_str(), args)
            {
                if is_simple_view_expr(body, ctx) {
                    let body_s = emit_view_expr_raw(body, ctx);
                    return vec![format!(
                        "view_helpers::content_for_set({slot:?}, &{body_s});"
                    )];
                }
            }
            vec!["/* TODO ERB: content_for with complex body */".to_string()]
        }
        ExprNode::Send { recv: Some(recv), method, args, block: Some(block), .. }
            if method.as_str() == "each" && args.is_empty() =>
        {
            emit_view_each_rust(recv, block, ctx, buf_name)
        }
        _ => vec![format!("{};", emit_view_expr(stmt, ctx))],
    }
}

fn emit_view_branch_rust(expr: &Expr, ctx: &ViewEmitCtx, buf_name: &str) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    let stmts: Vec<&Expr> = match &*expr.node {
        ExprNode::Seq { exprs } => exprs.iter().collect(),
        _ => vec![expr],
    };
    for stmt in &stmts {
        out.extend(emit_view_stmt_rust(stmt, ctx, buf_name));
    }
    out
}

fn emit_view_each_rust(
    coll: &Expr,
    block: &Expr,
    ctx: &ViewEmitCtx,
    buf_name: &str,
) -> Vec<String> {
    let ExprNode::Lambda { params, body, .. } = &*block.node else {
        return vec![format!("/* unexpected each block */")];
    };
    if !is_simple_view_expr(coll, ctx) {
        return vec!["/* TODO ERB: each over complex collection */".to_string()];
    }
    let coll_s = emit_view_expr_raw(coll, ctx);
    let var = params.first().map(|p| p.as_str().to_string()).unwrap_or_else(|| "item".into());
    let mut out = vec![format!("for {var} in {coll_s}.iter() {{")];
    let body_ctx = ctx.with_locals([var.clone()]);
    for line in emit_view_branch_rust(body, &body_ctx, buf_name) {
        out.push(format!("    {line}"));
    }
    out.push("}".to_string());
    out
}

fn emit_view_append(arg: &Expr, ctx: &ViewEmitCtx, buf_name: &str) -> Vec<String> {
    if let ExprNode::Lit { value: Literal::Str { value: s } } = &*arg.node {
        return vec![format!("{buf_name}.push_str({s:?});")];
    }
    let inner = unwrap_to_s_rust(arg);

    if let ExprNode::Send { recv: None, method, args, block: None, .. } = &*inner.node {
        if method.as_str() == "render" {
            if args.len() == 1 {
                let loop_expr = emit_view_render_call(&args[0], ctx);
                return vec![format!("{buf_name}.push_str(&{loop_expr});")];
            }
            if args.len() == 2 {
                if let (
                    ExprNode::Lit { value: Literal::Str { value: partial } },
                    ExprNode::Hash { entries, .. },
                ) = (&*args[0].node, &*args[1].node)
                {
                    let partial_fn = format!("render_{partial}");
                    for (k, v) in entries {
                        if let ExprNode::Lit { value: Literal::Sym { value: kname } } = &*k.node {
                            let arg_expr = emit_view_expr(v, ctx);
                            let _ = kname;
                            return vec![format!(
                                "{buf_name}.push_str(&{partial_fn}({arg_expr}));"
                            )];
                        }
                    }
                }
            }
        }
    }

    if let ExprNode::Send {
        recv: None,
        method,
        args,
        block: Some(block),
        ..
    } = &*inner.node
    {
        if is_capturing_helper(method.as_str()) {
            return emit_captured_block_helper(
                method.as_str(),
                args,
                block,
                ctx,
                buf_name,
            );
        }
    }

    if let ExprNode::Yield { args } = &*inner.node {
        if args.is_empty() {
            return vec![format!("{buf_name}.push_str(&view_helpers::get_yield());")];
        }
        if args.len() == 1 {
            if let ExprNode::Lit { value: Literal::Sym { value } } = &*args[0].node {
                return vec![format!(
                    "{buf_name}.push_str(&view_helpers::get_slot({:?}));",
                    value.as_str(),
                )];
            }
        }
    }

    if let ExprNode::Send { recv: None, method, args, block: None, .. } = &*inner.node {
        if let Some(kind) = crate::lower::classify_view_helper(method.as_str(), args) {
            if let Some(line) = emit_rust_view_helper(&kind, ctx, buf_name) {
                return line;
            }
        }
    }

    if let ExprNode::BoolOp { op: crate::expr::BoolOpKind::Or, left, right, .. } = &*inner.node {
        if let ExprNode::Send { recv: None, method, args, block: None, .. } = &*left.node {
            if let Some(crate::lower::ViewHelperKind::ContentForGetter { slot }) =
                crate::lower::classify_view_helper(method.as_str(), args)
            {
                if is_simple_view_expr(right, ctx) {
                    let fallback = emit_view_expr_raw(right, ctx);
                    return vec![format!(
                        "{{ let __cf = view_helpers::content_for_get({slot:?}); let __fb = {fallback}; {buf_name}.push_str(if __cf.is_empty() {{ &__fb }} else {{ __cf.as_str() }}); }}"
                    )];
                }
            }
        }
    }

    if let ExprNode::Send { recv: Some(r), method, args, block: None, .. } = &*inner.node {
        if let ExprNode::Var { name: recv_name, .. } = &*r.node {
            if ctx.is_local(recv_name.as_str()) {
                if let Some(fb) = crate::lower::classify_form_builder_method(method.as_str()) {
                    let rs_method = match fb {
                        crate::lower::FormBuilderMethod::Label => "label",
                        crate::lower::FormBuilderMethod::TextField => "text_field",
                        crate::lower::FormBuilderMethod::TextArea => "textarea",
                        crate::lower::FormBuilderMethod::Submit => "submit",
                    };
                    if let Some(call) = emit_rust_form_builder_call(
                        recv_name.as_str(),
                        rs_method,
                        args,
                        ctx,
                    ) {
                        return vec![format!("{buf_name}.push_str(&{call});")];
                    }
                }
            }
        }
    }

    if is_simple_view_expr(inner, ctx) {
        return vec![format!(
            "{buf_name}.push_str(&{}.to_string());",
            emit_view_expr(inner, ctx),
        )];
    }

    vec![format!(
        "/* TODO ERB: complex expression — see fixture view source */ {buf_name}.push_str(\"\");",
    )]
}

fn is_simple_view_expr(expr: &Expr, ctx: &ViewEmitCtx) -> bool {
    match &*expr.node {
        ExprNode::Lit { .. } => true,
        ExprNode::Var { name, .. } | ExprNode::Ivar { name } => ctx.is_local(name.as_str()),
        ExprNode::Send { recv: None, method, args, block: None, .. }
            if args.is_empty() && ctx.is_local(method.as_str()) =>
        {
            true
        }
        ExprNode::Send { recv: Some(r), method, args, block, .. } => {
            if !args.is_empty() || block.is_some() {
                return false;
            }
            let clean = sanitize_method_name(method.as_str());
            if clean.is_empty() {
                return false;
            }
            let recv_local = match &*r.node {
                ExprNode::Var { name, .. } | ExprNode::Ivar { name } => Some(name.as_str()),
                ExprNode::Send {
                    recv: None,
                    method: m,
                    args: ra,
                    block: None,
                    ..
                } if ra.is_empty() && ctx.is_local(m.as_str()) => Some(m.as_str()),
                _ => None,
            };
            if let Some(local_name) = recv_local {
                if ctx.local_has_attr(local_name, &clean) {
                    return true;
                }
                if ctx.is_local(local_name)
                    && matches!(method.as_str(), "any?" | "none?" | "present?" | "empty?")
                {
                    return true;
                }
                if ctx.resolve_has_many_on_local(local_name, method.as_str()).is_some() {
                    return true;
                }
            }
            if is_simple_view_expr(r, ctx) {
                return true;
            }
            false
        }
        ExprNode::StringInterp { parts } => parts.iter().all(|p| match p {
            crate::expr::InterpPart::Text { .. } => true,
            crate::expr::InterpPart::Expr { expr } => is_simple_view_expr(expr, ctx),
        }),
        _ => false,
    }
}

fn unwrap_to_s_rust(expr: &Expr) -> &Expr {
    if let ExprNode::Send { recv: Some(inner), method, args, .. } = &*expr.node {
        if method.as_str() == "to_s" && args.is_empty() {
            return inner;
        }
    }
    expr
}

fn is_capturing_helper(method: &str) -> bool {
    matches!(method, "form_with" | "content_for")
}

fn emit_captured_block_helper(
    method: &str,
    args: &[Expr],
    block: &Expr,
    ctx: &ViewEmitCtx,
    outer_buf: &str,
) -> Vec<String> {
    let ExprNode::Lambda { params, body, .. } = &*block.node else {
        return vec![format!("/* unexpected {method} block */")];
    };

    let html_class = extract_kwarg(args, "class")
        .filter(|e| is_simple_view_expr(e, ctx))
        .map(|e| emit_view_expr_raw(e, ctx))
        .unwrap_or_else(|| "String::new()".to_string());

    let model_expr = extract_kwarg(args, "model");
    let model_nested: Option<Vec<Expr>> = model_expr.and_then(|e| match &*e.node {
        ExprNode::Array { elements, .. } if elements.len() >= 2 => Some(elements.clone()),
        _ => None,
    });
    let record_ref: Option<String> = if let Some(elems) = &model_nested {
        Some(emit_rust_nested_form_record(&elems[elems.len() - 1]))
    } else {
        model_expr
            .filter(|e| is_simple_view_expr(e, ctx))
            .map(|e| emit_view_expr_raw(e, ctx))
            .or_else(|| {
                if !ctx.arg_name.is_empty() && ctx.is_local(&ctx.arg_name) {
                    Some(ctx.arg_name.clone())
                } else {
                    None
                }
            })
    };

    let prefix = if let Some(elems) = &model_nested {
        rust_nested_form_child_prefix(&elems[elems.len() - 1])
            .unwrap_or_else(|| ctx.arg_name.clone())
    } else if !ctx.resource_dir.is_empty() {
        crate::naming::singularize(&ctx.resource_dir)
    } else {
        ctx.arg_name.clone()
    };

    let mut out = Vec::new();
    out.push(format!("{outer_buf}.push_str(&{{"));
    out.push("    let mut _buf = String::new();".to_string());

    if let Some(p) = params.first() {
        let pname = p.as_str();
        match method {
            "form_with" => {
                let is_persisted_expr = record_ref
                    .as_deref()
                    .map(|r| format!("{r}.id != 0"))
                    .unwrap_or_else(|| "false".to_string());
                out.push(format!(
                    "    let {pname} = FormBuilder::new(\"{prefix}\", &{html_class}, {is_persisted_expr});",
                ));
                if let Some(record) = &record_ref {
                    out.push(format!(
                        "    _buf.push_str(&view_helpers::error_messages_for(&{record}.errors, \"{prefix}\"));",
                    ));
                }
            }
            _ => {
                out.push(format!("    let {pname} = ();"));
            }
        }
    }

    let inner_ctx = if let Some(p) = params.first() {
        let mut c = ctx.with_locals([p.as_str().to_string()]);
        if let Some(record) = &record_ref {
            c.form_records
                .push((p.as_str().to_string(), record.clone()));
        }
        c
    } else {
        ctx.clone()
    };
    for line in emit_view_branch_rust(body, &inner_ctx, "_buf") {
        out.push(format!("    {line}"));
    }

    match method {
        "form_with" => {
            let plural = if !ctx.resource_dir.is_empty() {
                ctx.resource_dir.clone()
            } else {
                crate::naming::pluralize_snake(&prefix)
            };
            let (resource_path_expr, is_persisted_expr) = match (&record_ref, &model_nested) {
                (Some(record), Some(elems)) => (
                    rust_nested_form_path_expr(elems, ctx, record, &prefix),
                    format!("{record}.id != 0"),
                ),
                (Some(record), None) => (
                    format!(
                        "if {record}.id != 0 {{ route_helpers::{prefix}_path({record}.id) }} else {{ route_helpers::{plural}_path() }}",
                    ),
                    format!("{record}.id != 0"),
                ),
                (None, _) => (
                    format!("route_helpers::{plural}_path()"),
                    "false".to_string(),
                ),
            };
            out.push(format!(
                "    let __action = {resource_path_expr};",
            ));
            out.push(format!(
                "    view_helpers::form_wrap(&__action, {is_persisted_expr}, &{html_class}, &_buf)",
            ));
        }
        "content_for" => {
            out.push("    let _ = _buf; String::new()".to_string());
        }
        _ => {
            out.push("    String::new()".to_string());
        }
    }

    out.push("});".to_string());
    out
}

fn emit_rust_nested_form_record(el: &Expr) -> String {
    match crate::lower::classify_nested_form_child(el) {
        Some(crate::lower::NestedFormChild::ClassNew { class }) => format!("{class}::default()"),
        Some(crate::lower::NestedFormChild::Local { name }) => name.to_string(),
        None => "Default::default()".to_string(),
    }
}

fn rust_nested_form_child_prefix(el: &Expr) -> Option<String> {
    crate::lower::classify_nested_form_child(el).map(|k| k.prefix())
}

fn rust_nested_form_path_expr(
    elems: &[Expr],
    ctx: &ViewEmitCtx,
    record_ref: &str,
    child_prefix: &str,
) -> String {
    let is_local = |n: &str| ctx.is_local(n);
    let mut parent_ids: Vec<String> = Vec::new();
    let mut parent_singulars: Vec<String> = Vec::new();
    for parent in &elems[..elems.len() - 1] {
        let Some(kind) = crate::lower::classify_nested_url_element(parent, &is_local) else {
            return "String::new()".to_string();
        };
        let (singular, id_expr) = rust_nested_element_parts(&kind);
        parent_singulars.push(singular);
        parent_ids.push(id_expr);
    }
    let member_name = format!(
        "{}_{}_path",
        parent_singulars.join("_"),
        child_prefix,
    );
    let child_plural = crate::naming::pluralize_snake(child_prefix);
    let collection_name = format!(
        "{}_{}_path",
        parent_singulars.join("_"),
        child_plural,
    );
    let parent_args = parent_ids.join(", ");
    let member_args = if parent_args.is_empty() {
        format!("{record_ref}.id")
    } else {
        format!("{parent_args}, {record_ref}.id")
    };
    format!(
        "if {record_ref}.id != 0 {{ route_helpers::{member_name}({member_args}) }} else {{ route_helpers::{collection_name}({parent_args}) }}",
    )
}

fn emit_rust_view_helper(
    kind: &crate::lower::ViewHelperKind<'_>,
    ctx: &ViewEmitCtx,
    buf_name: &str,
) -> Option<Vec<String>> {
    use crate::lower::ViewHelperKind::*;
    match kind {
        CsrfMetaTags => Some(vec![format!(
            "{buf_name}.push_str(&view_helpers::csrf_meta_tags());"
        )]),
        CspMetaTag => Some(vec![format!(
            "{buf_name}.push_str(&view_helpers::csp_meta_tag());"
        )]),
        JavascriptImportmapTags => Some(vec![format!(
            "{buf_name}.push_str(&view_helpers::javascript_importmap_tags(crate::importmap::PINS, \"application\"));"
        )]),
        TurboStreamFrom { channel } => {
            let chan = emit_view_string_arg(channel, ctx)?;
            Some(vec![format!(
                "{buf_name}.push_str(&view_helpers::turbo_stream_from(&{chan}));"
            )])
        }
        DomId { record, prefix } => {
            let singular = match &*record.node {
                ExprNode::Var { name, .. } | ExprNode::Ivar { name }
                    if ctx.is_local(name.as_str()) =>
                {
                    name.as_str().to_string()
                }
                ExprNode::Send {
                    recv: None,
                    method,
                    args,
                    block: None,
                    ..
                } if args.is_empty() && ctx.is_local(method.as_str()) => method.as_str().to_string(),
                _ => return None,
            };
            let id_expr = format!("{singular}.id");
            let prefix_expr = match prefix {
                None => "None".to_string(),
                Some(p) => match &*p.node {
                    ExprNode::Lit { value: Literal::Sym { value } } => {
                        format!("Some({:?})", value.as_str())
                    }
                    ExprNode::Lit { value: Literal::Str { value } } => {
                        format!("Some({value:?})")
                    }
                    _ => "None".to_string(),
                },
            };
            Some(vec![format!(
                "{buf_name}.push_str(&view_helpers::dom_id({singular:?}, {id_expr}, {prefix_expr}));"
            )])
        }
        Pluralize { count, word } => {
            if !is_simple_view_expr(count, ctx) || !is_simple_view_expr(word, ctx) {
                return None;
            }
            let c = emit_view_expr_raw(count, ctx);
            let w = emit_view_expr_raw(word, ctx);
            Some(vec![format!(
                "{buf_name}.push_str(&view_helpers::pluralize({c} as i64, &{w}));"
            )])
        }
        Truncate { text, opts } => {
            if !is_simple_view_expr(text, ctx) {
                return None;
            }
            let t = emit_view_expr_raw(text, ctx);
            let opts_code = rust_opts_from_expr(opts.as_deref(), ctx);
            Some(vec![format!(
                "{buf_name}.push_str(&view_helpers::truncate(&{t}, &{opts_code}));"
            )])
        }
        StylesheetLinkTag { name, opts } => {
            let opts_code = rust_opts_from_expr(opts.as_deref(), ctx);
            if let ExprNode::Lit { value: Literal::Sym { value } } = &*name.node {
                if value.as_str() == "app" && !ctx.stylesheets.is_empty() {
                    let mut out: Vec<String> = Vec::new();
                    for (i, n) in ctx.stylesheets.iter().enumerate() {
                        if i > 0 {
                            out.push(format!("{buf_name}.push_str(\"\\n\");"));
                        }
                        out.push(format!(
                            "{buf_name}.push_str(&view_helpers::stylesheet_link_tag({n:?}, &{opts_code}));"
                        ));
                    }
                    return Some(out);
                }
            }
            let name_str = match &*name.node {
                ExprNode::Lit { value: Literal::Sym { value } } => value.as_str().to_string(),
                ExprNode::Lit { value: Literal::Str { value } } => value.clone(),
                _ => return None,
            };
            Some(vec![format!(
                "{buf_name}.push_str(&view_helpers::stylesheet_link_tag({name_str:?}, &{opts_code}));"
            )])
        }
        ContentForGetter { slot } => Some(vec![format!(
            "{buf_name}.push_str(&view_helpers::content_for_get({slot:?}));"
        )]),
        ContentForSetter { .. } => None,
        LinkTo { text, url, opts } => {
            let call = emit_rust_link_or_button("link_to", text, url, opts.as_deref(), ctx)?;
            Some(vec![format!("{buf_name}.push_str(&{call});")])
        }
        ButtonTo { text, target, opts } => {
            let call = emit_rust_link_or_button("button_to", text, target, opts.as_deref(), ctx)?;
            Some(vec![format!("{buf_name}.push_str(&{call});")])
        }
    }
}

fn rust_opts_from_expr(opts: Option<&Expr>, ctx: &ViewEmitCtx) -> String {
    match opts.map(|e| &*e.node) {
        Some(ExprNode::Hash { entries, .. }) => rust_hash_to_hashmap_literal(entries, ctx),
        _ => "std::collections::HashMap::<String, String>::new()".to_string(),
    }
}

fn emit_rust_link_or_button(
    helper: &str,
    text: &Expr,
    url: &Expr,
    opts: Option<&Expr>,
    ctx: &ViewEmitCtx,
) -> Option<String> {
    if !is_simple_view_expr(text, ctx) {
        return None;
    }
    let text_expr = emit_view_expr_raw(text, ctx);
    let text_val = match &*text.node {
        ExprNode::Lit { value: Literal::Str { .. } } => text_expr,
        _ => format!("&{text_expr}.to_string()"),
    };
    let text_borrow = if text_val.starts_with('&') {
        text_val
    } else {
        format!("&{text_val}")
    };
    let is_local_fn = |n: &str| ctx.is_local(n);
    let url_kind = crate::lower::classify_view_url_arg(url, &is_local_fn)?;
    let url_expr = match url_kind {
        crate::lower::ViewUrlArg::Literal { value } => format!("{value:?}.to_string()"),
        crate::lower::ViewUrlArg::PathHelper { name, args } => {
            let args_s: Vec<String> = args
                .iter()
                .map(|a| rust_path_arg(a, ctx))
                .collect();
            format!("route_helpers::{name}({})", args_s.join(", "))
        }
        crate::lower::ViewUrlArg::RecordRef { name } => {
            format!("route_helpers::{name}_path({name}.id)")
        }
        crate::lower::ViewUrlArg::NestedArray { elements } => {
            rust_emit_nested_path(elements, ctx)?
        }
    };
    let opts_code = rust_opts_from_expr(opts, ctx);
    Some(format!(
        "view_helpers::{helper}({text_borrow}, &{url_expr}, &{opts_code})"
    ))
}

fn rust_emit_nested_path(elements: &[Expr], ctx: &ViewEmitCtx) -> Option<String> {
    let is_local = |n: &str| ctx.is_local(n);
    let mut singulars: Vec<String> = Vec::new();
    let mut args: Vec<String> = Vec::new();
    for el in elements {
        let kind = crate::lower::classify_nested_url_element(el, &is_local)?;
        let (singular, id_expr) = rust_nested_element_parts(&kind);
        singulars.push(singular);
        args.push(id_expr);
    }
    let name = format!("{}_path", singulars.join("_"));
    Some(format!("route_helpers::{name}({})", args.join(", ")))
}

fn rust_nested_element_parts(kind: &crate::lower::NestedUrlElement<'_>) -> (String, String) {
    match kind {
        crate::lower::NestedUrlElement::DirectLocal { name } => {
            ((*name).to_string(), format!("{name}.id"))
        }
        crate::lower::NestedUrlElement::Association { owner, assoc } => {
            ((*assoc).to_string(), format!("{owner}.{assoc}_id"))
        }
    }
}

fn rust_path_arg(arg: &Expr, ctx: &ViewEmitCtx) -> String {
    match &*arg.node {
        ExprNode::Var { name, .. } | ExprNode::Ivar { name } if ctx.is_local(name.as_str()) => {
            format!("{}.id", name.as_str())
        }
        ExprNode::Send { recv: None, method, args, block: None, .. }
            if args.is_empty() && ctx.is_local(method.as_str()) =>
        {
            format!("{}.id", method.as_str())
        }
        _ => emit_view_expr_raw(arg, ctx),
    }
}

fn emit_rust_form_builder_call(
    recv: &str,
    rs_method: &str,
    args: &[Expr],
    ctx: &ViewEmitCtx,
) -> Option<String> {
    let (field, opts_entries) = crate::lower::classify_form_builder_args(args);
    let field = field.map(str::to_string);
    let opts = opts_entries
        .map(|entries| rust_hash_to_hashmap_literal(entries, ctx))
        .unwrap_or_else(|| "std::collections::HashMap::new()".to_string());
    match rs_method {
        "label" => {
            let field = field?;
            Some(format!("{recv}.label({field:?}, &{opts})"))
        }
        "text_field" | "textarea" => {
            let field = field?;
            let value_expr = ctx
                .form_records
                .iter()
                .find(|(name, _)| name == recv)
                .and_then(|(_, record)| {
                    if ctx.local_has_attr(record, &field) {
                        Some(format!("&{record}.{field}"))
                    } else {
                        None
                    }
                })
                .unwrap_or_else(|| "\"\"".to_string());
            Some(format!(
                "{recv}.{rs_method}({field:?}, {value_expr}, &{opts})",
            ))
        }
        "submit" => {
            let label_str = args.iter().find_map(|a| match &*a.node {
                ExprNode::Lit { value: Literal::Str { value } } => Some(value.clone()),
                _ => None,
            });
            let opts_expr = if let Some(lbl) = label_str {
                format!(
                    "{{ let mut __m = {opts}; __m.insert(\"label\".to_string(), {lbl:?}.to_string()); __m }}",
                )
            } else {
                opts
            };
            Some(format!("{recv}.submit(&{opts_expr})"))
        }
        _ => None,
    }
}

fn rust_hash_to_hashmap_literal(
    entries: &[(Expr, Expr)],
    ctx: &ViewEmitCtx,
) -> String {
    let mut parts: Vec<(String, String)> = Vec::new();
    for (k, v) in entries {
        let key = match &*k.node {
            ExprNode::Lit { value: Literal::Sym { value } } => value.as_str().to_string(),
            ExprNode::Lit { value: Literal::Str { value } } => value.clone(),
            _ => continue,
        };
        if key == "data" {
            if let ExprNode::Hash { entries: data_entries, .. } = &*v.node {
                for (dk, dv) in data_entries {
                    let dk_str = match &*dk.node {
                        ExprNode::Lit { value: Literal::Sym { value } } => {
                            value.as_str().replace('_', "-")
                        }
                        ExprNode::Lit { value: Literal::Str { value } } => {
                            value.replace('_', "-")
                        }
                        _ => continue,
                    };
                    let dv_s = match &*dv.node {
                        ExprNode::Lit { value: Literal::Str { value } } => {
                            format!("{value:?}.to_string()")
                        }
                        _ if is_simple_view_expr(dv, ctx) => {
                            format!("{}.to_string()", emit_view_expr_raw(dv, ctx))
                        }
                        _ => continue,
                    };
                    parts.push((format!("data-{dk_str}"), dv_s));
                }
                continue;
            }
        }
        let val = if key == "class" {
            rust_class_value(v, ctx)
        } else {
            match &*v.node {
                ExprNode::Lit { value: Literal::Str { value } } => format!("{value:?}.to_string()"),
                ExprNode::Lit { value: Literal::Int { value } } => {
                    format!("{value}.to_string()")
                }
                ExprNode::Lit { value: Literal::Sym { value } } => {
                    format!("{:?}.to_string()", value.as_str())
                }
                ExprNode::Array { elements, .. } => match elements.first() {
                    Some(first) => match &*first.node {
                        ExprNode::Lit { value: Literal::Str { value } } => {
                            format!("{value:?}.to_string()")
                        }
                        _ => "String::new()".to_string(),
                    },
                    None => "String::new()".to_string(),
                },
                _ if is_simple_view_expr(v, ctx) => {
                    format!("{}.to_string()", emit_view_expr_raw(v, ctx))
                }
                _ => "String::new()".to_string(),
            }
        };
        parts.push((key, val));
    }
    let inserts: Vec<String> = parts
        .into_iter()
        .map(|(k, v)| format!("{{ let (k, v) = ({k:?}.to_string(), {v}); __m.insert(k, v); }}"))
        .collect();
    format!(
        "{{ let mut __m: std::collections::HashMap<String, String> = std::collections::HashMap::new(); {} __m }}",
        inserts.join(" "),
    )
}

fn rust_class_value(v: &Expr, ctx: &ViewEmitCtx) -> String {
    let is_local = |n: &str| ctx.is_local(n);
    let simple_as_string = |e: &Expr| -> Option<String> {
        if is_simple_view_expr(e, ctx) {
            Some(match &*e.node {
                ExprNode::Lit { value: Literal::Str { value } } => {
                    format!("{value:?}.to_string()")
                }
                _ => format!("{}.to_string()", emit_view_expr_raw(e, ctx)),
            })
        } else {
            None
        }
    };
    match crate::lower::classify_class_value(v, &is_local) {
        crate::lower::ClassValueShape::Simple { expr } => {
            simple_as_string(expr).unwrap_or_else(|| "String::new()".to_string())
        }
        crate::lower::ClassValueShape::Conditional { base, clauses } => {
            let Some(base_s) = simple_as_string(base) else {
                return "String::new()".to_string();
            };
            if clauses.is_empty() {
                return base_s;
            }
            let extras: Vec<String> = clauses
                .iter()
                .map(|(cls_text, pred)| {
                    let cond_rs = rust_render_errors_field_predicate(pred);
                    format!(" + if {cond_rs} {{ \" {cls_text}\" }} else {{ \"\" }}")
                })
                .collect();
            format!("({base_s}{})", extras.join(""))
        }
        crate::lower::ClassValueShape::Unknown => "String::new()".to_string(),
    }
}

fn rust_render_errors_field_predicate(pred: &crate::lower::ErrorsFieldPredicate<'_>) -> String {
    let call = format!(
        "view_helpers::field_has_error(&{}.errors, {:?})",
        pred.record, pred.field,
    );
    if pred.expect_present {
        call
    } else {
        format!("!{call}")
    }
}

fn emit_view_string_arg(arg: &Expr, ctx: &ViewEmitCtx) -> Option<String> {
    if let ExprNode::Lit { value: Literal::Str { value } } = &*arg.node {
        return Some(format!("{value:?}"));
    }
    if is_simple_view_expr(arg, ctx) {
        return Some(format!("{}.to_string()", emit_view_expr_raw(arg, ctx)));
    }
    None
}

fn extract_kwarg<'a>(args: &'a [Expr], key: &str) -> Option<&'a Expr> {
    for arg in args {
        if let ExprNode::Hash { entries, .. } = &*arg.node {
            for (k, v) in entries {
                if let ExprNode::Lit { value: Literal::Sym { value } } = &*k.node {
                    if value.as_str() == key {
                        return Some(v);
                    }
                }
            }
        }
    }
    None
}

fn emit_view_expr(expr: &Expr, ctx: &ViewEmitCtx) -> String {
    let container =
        matches!(&*expr.node, ExprNode::Hash { .. } | ExprNode::Array { .. });
    let is_render_call = matches!(
        &*expr.node,
        ExprNode::Send { recv: None, method, args, block: None, .. }
            if method.as_str() == "render" && args.len() == 1
    );
    if !container && !is_render_call && !is_simple_view_expr(expr, ctx) {
        return "/* TODO ERB */ String::new()".to_string();
    }
    emit_view_expr_raw(expr, ctx)
}

fn emit_view_expr_raw(expr: &Expr, ctx: &ViewEmitCtx) -> String {
    match &*expr.node {
        ExprNode::Lit { value } => emit_literal(value),
        ExprNode::Ivar { name } => name.to_string(),
        ExprNode::Var { name, .. } => name.to_string(),
        ExprNode::Const { path } => {
            path.iter().map(|s| s.to_string()).collect::<Vec<_>>().join("::")
        }
        ExprNode::Send { recv, method, args, block, .. } => {
            emit_view_send(recv.as_ref(), method.as_str(), args, block.as_ref(), ctx)
        }
        ExprNode::Hash { entries, .. } => {
            let parts: Vec<String> = entries
                .iter()
                .map(|(k, v)| {
                    let k_s = emit_view_expr(k, ctx);
                    let v_s = emit_view_expr(v, ctx);
                    format!("({k_s}.to_string(), {v_s}.to_string())")
                })
                .collect();
            format!(
                "std::collections::HashMap::<String, String>::from([{}])",
                parts.join(", "),
            )
        }
        ExprNode::Array { elements, .. } => {
            let parts: Vec<String> = elements.iter().map(|e| emit_view_expr(e, ctx)).collect();
            format!("vec![{}]", parts.join(", "))
        }
        ExprNode::StringInterp { parts } => {
            use crate::expr::InterpPart;
            let mut fmt = String::new();
            let mut args: Vec<String> = Vec::new();
            for p in parts {
                match p {
                    InterpPart::Text { value } => {
                        for c in value.chars() {
                            if c == '{' {
                                fmt.push_str("{{");
                            } else if c == '}' {
                                fmt.push_str("}}");
                            } else {
                                fmt.push(c);
                            }
                        }
                    }
                    InterpPart::Expr { expr } => {
                        fmt.push_str("{}");
                        args.push(emit_view_expr(expr, ctx));
                    }
                }
            }
            if args.is_empty() {
                format!("{fmt:?}.to_string()")
            } else {
                format!("format!({fmt:?}, {})", args.join(", "))
            }
        }
        _ => format!("/* TODO view expr {:?} */", std::mem::discriminant(&*expr.node)),
    }
}

fn emit_view_send(
    recv: Option<&Expr>,
    method: &str,
    args: &[Expr],
    block: Option<&Expr>,
    ctx: &ViewEmitCtx,
) -> String {
    if recv.is_none() && method == "render" && args.len() == 1 && block.is_none() {
        return emit_view_render_call(&args[0], ctx);
    }
    let sanitized_method = sanitize_method_name(method);
    if recv.is_none()
        && block.is_none()
        && (method.ends_with("_path") || method.ends_with("_url"))
    {
        let name = if let Some(stem) = method.strip_suffix("_url") {
            format!("{stem}_path")
        } else {
            method.to_string()
        };
        let args_s: Vec<String> = args
            .iter()
            .map(|a| emit_view_url_arg(a, ctx))
            .collect();
        return format!("route_helpers::{name}({})", args_s.join(", "));
    }
    if recv.is_none() && args.is_empty() && block.is_none() && ctx.is_local(method) {
        return method.to_string();
    }
    if recv.is_none() && is_rails_view_helper(method) {
        let args_s: Vec<String> = args.iter().map(|a| emit_view_expr(a, ctx)).collect();
        return format!("view_helpers::{method}({})", args_s.join(", "));
    }
    if let Some(r) = recv {
        if args.is_empty() && block.is_none() {
            if method == "to_s" {
                return format!("{}.to_string()", emit_view_expr(r, ctx));
            }
            let owner_local = match &*r.node {
                ExprNode::Var { name, .. } | ExprNode::Ivar { name }
                    if ctx.is_local(name.as_str()) =>
                {
                    Some(name.as_str().to_string())
                }
                ExprNode::Send {
                    recv: None,
                    method: m,
                    args: ra,
                    block: None,
                    ..
                } if ra.is_empty() && ctx.is_local(m.as_str()) => Some(m.as_str().to_string()),
                _ => None,
            };
            if let Some(owner) = owner_local {
                if let Some((target_class, fk)) =
                    ctx.resolve_has_many_on_local(&owner, method)
                {
                    return format!(
                        "{target_class}::all().into_iter().filter(|__r| __r.{fk} == {owner}.id).collect::<Vec<_>>()",
                    );
                }
            }
            match method {
                "any?" | "present?" => {
                    let recv_s = emit_view_expr(r, ctx);
                    return format!("!{recv_s}.is_empty()");
                }
                "none?" | "empty?" => {
                    let recv_s = emit_view_expr(r, ctx);
                    return format!("{recv_s}.is_empty()");
                }
                "size" | "count" | "length" => {
                    let recv_s = emit_view_expr(r, ctx);
                    return format!("{recv_s}.len() as i64");
                }
                "full_message" => {
                    let recv_s = emit_view_expr(r, ctx);
                    return format!("{recv_s}.full_message()");
                }
                _ => {}
            }
            let recv_s = emit_view_expr(r, ctx);
            return format!("{recv_s}.{sanitized_method}");
        }
        let recv_s = emit_view_expr(r, ctx);
        let args_s: Vec<String> = args.iter().map(|a| emit_view_expr(a, ctx)).collect();
        return format!("{recv_s}.{sanitized_method}({})", args_s.join(", "));
    }
    let args_s: Vec<String> = args.iter().map(|a| emit_view_expr(a, ctx)).collect();
    if args_s.is_empty() {
        format!("view_helpers::{method}()")
    } else {
        format!("view_helpers::{method}({})", args_s.join(", "))
    }
}

fn sanitize_method_name(name: &str) -> String {
    let name = name.trim_end_matches('?');
    let name = name.trim_end_matches('!');
    name.to_string()
}

fn emit_view_url_arg(arg: &Expr, ctx: &ViewEmitCtx) -> String {
    match &*arg.node {
        ExprNode::Var { name, .. } | ExprNode::Ivar { name } => {
            let class = crate::naming::singularize_camelize(name.as_str());
            if ctx.known_models.iter().any(|m| m.as_str() == class) {
                format!("{}.id", name.as_str())
            } else {
                name.to_string()
            }
        }
        _ => emit_view_expr(arg, ctx),
    }
}

fn emit_view_render_call(arg: &Expr, ctx: &ViewEmitCtx) -> String {
    match &*arg.node {
        ExprNode::Var { name, .. } | ExprNode::Ivar { name } if ctx.is_local(name.as_str()) => {
            let singular = crate::naming::singularize(name.as_str());
            let partial_name = format!("render_{singular}");
            let coll = name.to_string();
            format!(
                "{{ let mut __s = String::new(); for __r in {coll} {{ __s.push_str(&{partial_name}(__r)); }} __s }}",
            )
        }
        ExprNode::Send { recv: Some(r), method, args, .. }
            if args.is_empty()
                && matches!(&*r.node, ExprNode::Var { .. } | ExprNode::Ivar { .. }) =>
        {
            let assoc_plural = method.as_str();
            let target_class = crate::naming::singularize_camelize(assoc_plural);
            if !ctx.known_models.iter().any(|m| m.as_str() == target_class) {
                return "/* TODO ERB: render over unknown collection */ String::new()".to_string();
            }
            let parent_name = match &*r.node {
                ExprNode::Var { name, .. } | ExprNode::Ivar { name } => name.to_string(),
                _ => unreachable!(),
            };
            let parent_singular = crate::naming::singularize(
                &crate::naming::singularize(&parent_name),
            );
            let fk = format!("{parent_singular}_id");
            let singular = crate::naming::singularize(assoc_plural);
            let partial_name = format!("render_{singular}");
            format!(
                "{{ let mut __s = String::new(); for __r in {target_class}::all().into_iter().filter(|__c| __c.{fk} == {parent_name}.id) {{ __s.push_str(&{partial_name}(&__r)); }} __s }}",
            )
        }
        _ => "/* TODO ERB: render */ String::new()".to_string(),
    }
}

fn is_rails_view_helper(name: &str) -> bool {
    matches!(
        name,
        "link_to"
            | "button_to"
            | "content_for"
            | "form_with"
            | "turbo_stream_from"
            | "dom_id"
            | "pluralize"
            | "number_to_currency"
            | "truncate"
            | "time_ago_in_words"
            | "image_tag"
            | "yield"
    )
}
