//! Go emitter smoke test.

use std::path::{Path, PathBuf};

use roundhouse::analyze::Analyzer;
use roundhouse::emit::go;
use roundhouse::ingest::ingest_app;

fn fixture_path() -> &'static Path {
    Path::new("fixtures/tiny-blog")
}

fn analyzed_app() -> roundhouse::App {
    let mut app = ingest_app(fixture_path()).expect("ingest");
    Analyzer::new(&app).analyze(&mut app);
    app
}

#[test]
fn models_file_is_emitted() {
    let app = analyzed_app();
    let files = go::emit(&app);
    let paths: Vec<_> = files.iter().map(|f| f.path.display().to_string()).collect();
    assert!(paths.contains(&"app/models.go".to_string()), "got {paths:?}");
}

#[test]
fn models_output_is_stable() {
    let app = analyzed_app();
    let files = go::emit(&app);
    let models = files
        .iter()
        .find(|f| f.path == PathBuf::from("app/models.go"))
        .unwrap();
    let expected = "\
// Generated by Roundhouse.
package app

type Comment struct {
\tID int64
\tBody string
\tPostID int64
}

type Post struct {
\tID int64
\tTitle string
}

func (p *Post) NormalizeTitle() string {
\treturn Title.Strip()
}
";
    assert_eq!(models.content, expected);
}

#[test]
fn controller_file_is_emitted() {
    let app = analyzed_app();
    let files = go::emit(&app);
    let paths: Vec<_> = files.iter().map(|f| f.path.display().to_string()).collect();
    assert!(
        paths.contains(&"app/controllers/posts_controller.go".to_string()),
        "got {paths:?}"
    );
}

#[test]
fn index_action_returns_slice_of_post() {
    let app = analyzed_app();
    let files = go::emit(&app);
    let ctrl = files
        .iter()
        .find(|f| f.path == PathBuf::from("app/controllers/posts_controller.go"))
        .unwrap();
    assert!(
        ctrl.content.contains("func (c *PostsController) Index() []Post"),
        "expected Index returning []Post; got:\n{}",
        ctrl.content
    );
    assert!(
        ctrl.content.contains("return Post.All()"),
        "expected `return Post.All()`; got:\n{}",
        ctrl.content
    );
}

#[test]
fn destroy_action_is_void_with_no_return_type() {
    let app = analyzed_app();
    let files = go::emit(&app);
    let ctrl = files
        .iter()
        .find(|f| f.path == PathBuf::from("app/controllers/posts_controller.go"))
        .unwrap();
    // Void function: no return-type annotation.
    assert!(
        ctrl.content.contains("func (c *PostsController) Destroy() {"),
        "expected void Destroy; got:\n{}",
        ctrl.content
    );
    // Short-var decl for locals + ivars.
    assert!(
        ctrl.content.contains("post := Post.Find(Params[\"id\"])"),
        "expected short-var decl; got:\n{}",
        ctrl.content
    );
    assert!(
        ctrl.content.contains("post.Destroy()"),
        "expected instance call; got:\n{}",
        ctrl.content
    );
}

#[test]
fn controller_output_is_stable() {
    let app = analyzed_app();
    let files = go::emit(&app);
    let ctrl = files
        .iter()
        .find(|f| f.path == PathBuf::from("app/controllers/posts_controller.go"))
        .unwrap();
    let expected = "\
// Generated by Roundhouse.
package app

type PostsController struct{}

func (c *PostsController) Index() []Post {
\treturn Post.All()
}

func (c *PostsController) Show() Post {
\treturn Post.Find(Params[\"id\"])
}

func (c *PostsController) Create() {
\tpost := Post.New(PostParams)
\tif post.Save() {
\t\tRedirectTo(post)
\t} else {
\t\tRender(\"new\")
\t}
}

func (c *PostsController) Destroy() {
\tpost := Post.Find(Params[\"id\"])
\tpost.Destroy()
\tRedirectTo(PostsPath)
}
";
    assert_eq!(ctrl.content, expected);
}
