//! Rust emitter smoke test.
//!
//! Scope for now: emit model structs. Expand as the emitter grows.

use std::path::{Path, PathBuf};

use roundhouse::analyze::Analyzer;
use roundhouse::emit::rust;
use roundhouse::ingest::ingest_app;

fn fixture_path() -> &'static Path {
    Path::new("fixtures/tiny-blog")
}

fn analyzed_app() -> roundhouse::App {
    let mut app = ingest_app(fixture_path()).expect("ingest");
    Analyzer::new(&app).analyze(&mut app);
    app
}

#[test]
fn emits_a_models_file() {
    let app = ingest_app(fixture_path()).expect("ingest");
    let files = rust::emit(&app);
    let paths: Vec<_> = files.iter().map(|f| f.path.display().to_string()).collect();
    assert!(paths.contains(&"src/models.rs".to_string()), "got {paths:?}");
}

#[test]
fn runtime_is_emitted_alongside_models() {
    // The generated `src/models.rs` references `crate::runtime::
    // ValidationError`; the runtime file has to ship with it so the
    // project compiles. It's copied verbatim from the hand-written
    // source under `runtime/rust/`.
    let app = ingest_app(fixture_path()).expect("ingest");
    let files = rust::emit(&app);
    let runtime = files
        .iter()
        .find(|f| f.path == PathBuf::from("src/runtime.rs"))
        .expect("runtime file should be emitted when any model is emitted");
    assert!(
        runtime.content.contains("pub struct ValidationError"),
        "got:\n{}",
        runtime.content
    );
    assert!(
        runtime
            .content
            .contains("pub fn new(field: &str, message: &str) -> Self"),
        "got:\n{}",
        runtime.content
    );
    assert!(
        runtime.content.contains("pub fn full_message(&self) -> String"),
        "got:\n{}",
        runtime.content
    );
}

#[test]
fn runtime_compiles_as_rust() {
    // The runtime source is `include_str!`d at compile time from
    // `runtime/rust/runtime.rs`. If that file ever stops being valid
    // Rust, the build of *this crate* fails, which is a strong enough
    // check for most changes. The inline `#[cfg(test)]` tests inside
    // runtime.rs itself aren't run by our test harness (they're not
    // compiled into *our* crate — they're part of the string), so
    // this stub just pins the file's presence and non-emptiness.
    let app = ingest_app(fixture_path()).expect("ingest");
    let files = rust::emit(&app);
    let runtime = files
        .iter()
        .find(|f| f.path == PathBuf::from("src/runtime.rs"))
        .unwrap();
    assert!(!runtime.content.is_empty());
    // The include_str! preserves the file verbatim including the
    // `#[cfg(test)] mod tests` block, which means a generated project
    // running `cargo test` also exercises the runtime's own tests.
    assert!(runtime.content.contains("#[cfg(test)]"));
}

#[test]
fn post_struct_is_emitted() {
    let app = ingest_app(fixture_path()).expect("ingest");
    let files = rust::emit(&app);
    let models = files
        .iter()
        .find(|f| f.path == PathBuf::from("src/models.rs"))
        .unwrap();
    assert!(models.content.contains("pub struct Post {"), "got:\n{}", models.content);
    assert!(models.content.contains("pub id: i64,"), "got:\n{}", models.content);
    assert!(models.content.contains("pub title: String,"), "got:\n{}", models.content);
}

#[test]
fn comment_struct_is_emitted_with_foreign_key() {
    let app = ingest_app(fixture_path()).expect("ingest");
    let files = rust::emit(&app);
    let models = files
        .iter()
        .find(|f| f.path == PathBuf::from("src/models.rs"))
        .unwrap();
    assert!(models.content.contains("pub struct Comment {"));
    assert!(models.content.contains("pub body: String,"));
    assert!(models.content.contains("pub post_id: i64,"));
}

#[test]
fn emitted_rust_output_is_stable() {
    // Needs the analyzer — model methods have inferred return types.
    let app = analyzed_app();
    let files = rust::emit(&app);
    let models = files
        .iter()
        .find(|f| f.path == PathBuf::from("src/models.rs"))
        .unwrap();
    let expected = "\
// Generated by Roundhouse.

use crate::runtime;

pub struct Comment {
    pub id: i64,
    pub body: String,
    pub post_id: i64,
}

pub struct Post {
    pub id: i64,
    pub title: String,
}

impl Post {
    pub fn normalize_title(&self) -> String {
        title.strip()
    }

    pub fn validate(&self) -> Vec<runtime::ValidationError> {
        let mut errors = Vec::new();
        if self.title.is_empty() {
            errors.push(runtime::ValidationError::new(\"title\", \"can't be blank\"));
        }
        errors
    }
}
";
    assert_eq!(models.content, expected);
}

#[test]
fn validations_emit_as_inline_evaluator() {
    // Build an ad-hoc model with multiple rules to exercise the full
    // Check-to-Rust rendering. tiny-blog's Post only covers Presence;
    // this pins down MinLength and the error-push boilerplate.
    use roundhouse::{
        ClassId, Model, ModelBodyItem, Row, Symbol, TableRef, Validation, ValidationRule,
    };
    use indexmap::IndexMap;
    let mut attrs = IndexMap::new();
    attrs.insert(Symbol::from("id"), roundhouse::Ty::Int);
    attrs.insert(Symbol::from("title"), roundhouse::Ty::Str);
    attrs.insert(Symbol::from("body"), roundhouse::Ty::Str);
    let mut app = roundhouse::App::new();
    app.models.push(Model {
        name: ClassId(Symbol::from("Article")),
        parent: None,
        table: TableRef(Symbol::from("articles")),
        attributes: Row { fields: attrs, rest: None },
        body: vec![
            ModelBodyItem::Validation {
                validation: Validation {
                    attribute: Symbol::from("title"),
                    rules: vec![ValidationRule::Presence],
                },
                leading_comments: vec![],
                leading_blank_line: false,
            },
            ModelBodyItem::Validation {
                validation: Validation {
                    attribute: Symbol::from("body"),
                    rules: vec![
                        ValidationRule::Presence,
                        ValidationRule::Length { min: Some(10), max: None },
                    ],
                },
                leading_comments: vec![],
                leading_blank_line: false,
            },
        ],
    });
    let files = rust::emit(&app);
    let models = files
        .iter()
        .find(|f| f.path == PathBuf::from("src/models.rs"))
        .unwrap();
    // Import is added when any model has validations.
    assert!(
        models.content.contains("use crate::runtime;"),
        "got:\n{}",
        models.content
    );
    // validate() signature uses the runtime-provided error type.
    assert!(
        models
            .content
            .contains("pub fn validate(&self) -> Vec<runtime::ValidationError>"),
        "got:\n{}",
        models.content
    );
    // Presence renders as `.is_empty()`, message is the Rails default.
    assert!(
        models.content.contains("if self.title.is_empty() {"),
        "got:\n{}",
        models.content
    );
    assert!(
        models
            .content
            .contains("runtime::ValidationError::new(\"title\", \"can't be blank\")"),
        "got:\n{}",
        models.content
    );
    // Length fans out into a separate `.len() < n` check.
    assert!(
        models.content.contains("if self.body.len() < 10 {"),
        "got:\n{}",
        models.content
    );
    assert!(
        models.content.contains("is too short (minimum is 10 characters)"),
        "got:\n{}",
        models.content
    );
    // Trailing `errors` return value wraps the evaluator.
    assert!(models.content.contains("        errors\n    }"),
        "got:\n{}", models.content);
}

// Controller emission --------------------------------------------------

#[test]
fn controller_file_is_emitted() {
    let app = analyzed_app();
    let files = rust::emit(&app);
    let paths: Vec<_> = files.iter().map(|f| f.path.display().to_string()).collect();
    assert!(
        paths.contains(&"src/controllers/posts_controller.rs".to_string()),
        "got {paths:?}"
    );
}

#[test]
fn index_action_returns_vec_of_post() {
    let app = analyzed_app();
    let files = rust::emit(&app);
    let ctrl = files
        .iter()
        .find(|f| f.path == PathBuf::from("src/controllers/posts_controller.rs"))
        .unwrap();
    assert!(
        ctrl.content.contains("pub fn index() -> Vec<Post>"),
        "expected index to return Vec<Post>; got:\n{}",
        ctrl.content
    );
    assert!(
        ctrl.content.contains("Post::all()"),
        "expected Post::all() in body; got:\n{}",
        ctrl.content
    );
}

#[test]
fn show_action_returns_post_and_uses_params() {
    let app = analyzed_app();
    let files = rust::emit(&app);
    let ctrl = files
        .iter()
        .find(|f| f.path == PathBuf::from("src/controllers/posts_controller.rs"))
        .unwrap();
    assert!(
        ctrl.content.contains("pub fn show() -> Post"),
        "expected show to return Post; got:\n{}",
        ctrl.content
    );
    assert!(
        ctrl.content.contains("Post::find(params[\"id\"])"),
        "expected Post::find(params[\"id\"]) in body; got:\n{}",
        ctrl.content
    );
}

#[test]
fn controller_output_is_stable() {
    let app = analyzed_app();
    let files = rust::emit(&app);
    let ctrl = files
        .iter()
        .find(|f| f.path == PathBuf::from("src/controllers/posts_controller.rs"))
        .unwrap();
    let expected = "\
// Generated by Roundhouse.

pub struct PostsController;

impl PostsController {
    pub fn index() -> Vec<Post> {
        Post::all()
    }

    pub fn show() -> Post {
        Post::find(params[\"id\"])
    }

    pub fn create() -> () {
        let post = Post::new(post_params);
        if post.save() {
            redirect_to(post)
        } else {
            render(\"new\")
        }
    }

    pub fn destroy() -> () {
        let post = Post::find(params[\"id\"]);
        post.destroy();
        redirect_to(posts_path)
    }
}
";
    assert_eq!(ctrl.content, expected);
}
