//! Rust emitter smoke test.
//!
//! Scope for now: emit model structs. Expand as the emitter grows.

use std::path::{Path, PathBuf};

use roundhouse::analyze::Analyzer;
use roundhouse::emit::rust;
use roundhouse::ingest::ingest_app;

fn fixture_path() -> &'static Path {
    Path::new("fixtures/tiny-blog")
}

fn analyzed_app() -> roundhouse::App {
    let mut app = ingest_app(fixture_path()).expect("ingest");
    Analyzer::new(&app).analyze(&mut app);
    app
}

#[test]
fn emits_a_models_file() {
    let app = ingest_app(fixture_path()).expect("ingest");
    let files = rust::emit(&app);
    let paths: Vec<_> = files.iter().map(|f| f.path.display().to_string()).collect();
    assert!(paths.contains(&"src/models.rs".to_string()), "got {paths:?}");
}

#[test]
fn post_struct_is_emitted() {
    let app = ingest_app(fixture_path()).expect("ingest");
    let files = rust::emit(&app);
    let models = files
        .iter()
        .find(|f| f.path == PathBuf::from("src/models.rs"))
        .unwrap();
    assert!(models.content.contains("pub struct Post {"), "got:\n{}", models.content);
    assert!(models.content.contains("pub id: i64,"), "got:\n{}", models.content);
    assert!(models.content.contains("pub title: String,"), "got:\n{}", models.content);
}

#[test]
fn comment_struct_is_emitted_with_foreign_key() {
    let app = ingest_app(fixture_path()).expect("ingest");
    let files = rust::emit(&app);
    let models = files
        .iter()
        .find(|f| f.path == PathBuf::from("src/models.rs"))
        .unwrap();
    assert!(models.content.contains("pub struct Comment {"));
    assert!(models.content.contains("pub body: String,"));
    assert!(models.content.contains("pub post_id: i64,"));
}

#[test]
fn emitted_rust_output_is_stable() {
    // Needs the analyzer — model methods have inferred return types.
    let app = analyzed_app();
    let files = rust::emit(&app);
    let models = files
        .iter()
        .find(|f| f.path == PathBuf::from("src/models.rs"))
        .unwrap();
    let expected = "\
// Generated by Roundhouse.

pub struct Comment {
    pub id: i64,
    pub body: String,
    pub post_id: i64,
}

pub struct Post {
    pub id: i64,
    pub title: String,
}

impl Post {
    pub fn normalize_title(&self) -> String {
        title.strip()
    }
}
";
    assert_eq!(models.content, expected);
}

// Controller emission --------------------------------------------------

#[test]
fn controller_file_is_emitted() {
    let app = analyzed_app();
    let files = rust::emit(&app);
    let paths: Vec<_> = files.iter().map(|f| f.path.display().to_string()).collect();
    assert!(
        paths.contains(&"src/controllers/posts_controller.rs".to_string()),
        "got {paths:?}"
    );
}

#[test]
fn index_action_returns_vec_of_post() {
    let app = analyzed_app();
    let files = rust::emit(&app);
    let ctrl = files
        .iter()
        .find(|f| f.path == PathBuf::from("src/controllers/posts_controller.rs"))
        .unwrap();
    assert!(
        ctrl.content.contains("pub fn index() -> Vec<Post>"),
        "expected index to return Vec<Post>; got:\n{}",
        ctrl.content
    );
    assert!(
        ctrl.content.contains("Post::all()"),
        "expected Post::all() in body; got:\n{}",
        ctrl.content
    );
}

#[test]
fn show_action_returns_post_and_uses_params() {
    let app = analyzed_app();
    let files = rust::emit(&app);
    let ctrl = files
        .iter()
        .find(|f| f.path == PathBuf::from("src/controllers/posts_controller.rs"))
        .unwrap();
    assert!(
        ctrl.content.contains("pub fn show() -> Post"),
        "expected show to return Post; got:\n{}",
        ctrl.content
    );
    assert!(
        ctrl.content.contains("Post::find(params[\"id\"])"),
        "expected Post::find(params[\"id\"]) in body; got:\n{}",
        ctrl.content
    );
}

#[test]
fn controller_output_is_stable() {
    let app = analyzed_app();
    let files = rust::emit(&app);
    let ctrl = files
        .iter()
        .find(|f| f.path == PathBuf::from("src/controllers/posts_controller.rs"))
        .unwrap();
    let expected = "\
// Generated by Roundhouse.

pub struct PostsController;

impl PostsController {
    pub fn index() -> Vec<Post> {
        Post::all()
    }

    pub fn show() -> Post {
        Post::find(params[\"id\"])
    }

    pub fn create() -> () {
        let post = Post::new(post_params);
        if post.save() {
            redirect_to(post)
        } else {
            render(\"new\")
        }
    }

    pub fn destroy() -> () {
        let post = Post::find(params[\"id\"]);
        post.destroy();
        redirect_to(posts_path)
    }
}
";
    assert_eq!(ctrl.content, expected);
}
