//! Rust emitter smoke test.
//!
//! Scope for now: emit model structs. Expand as the emitter grows.

use std::path::{Path, PathBuf};

use roundhouse::emit::rust;
use roundhouse::ingest::ingest_app;

fn fixture_path() -> &'static Path {
    Path::new("fixtures/tiny-blog")
}

#[test]
fn emits_a_models_file() {
    let app = ingest_app(fixture_path()).expect("ingest");
    let files = rust::emit(&app);
    let paths: Vec<_> = files.iter().map(|f| f.path.display().to_string()).collect();
    assert!(paths.contains(&"src/models.rs".to_string()), "got {paths:?}");
}

#[test]
fn post_struct_is_emitted() {
    let app = ingest_app(fixture_path()).expect("ingest");
    let files = rust::emit(&app);
    let models = files
        .iter()
        .find(|f| f.path == PathBuf::from("src/models.rs"))
        .unwrap();
    assert!(models.content.contains("pub struct Post {"), "got:\n{}", models.content);
    assert!(models.content.contains("pub id: i64,"), "got:\n{}", models.content);
    assert!(models.content.contains("pub title: String,"), "got:\n{}", models.content);
}

#[test]
fn comment_struct_is_emitted_with_foreign_key() {
    let app = ingest_app(fixture_path()).expect("ingest");
    let files = rust::emit(&app);
    let models = files
        .iter()
        .find(|f| f.path == PathBuf::from("src/models.rs"))
        .unwrap();
    assert!(models.content.contains("pub struct Comment {"));
    assert!(models.content.contains("pub body: String,"));
    assert!(models.content.contains("pub post_id: i64,"));
}

#[test]
fn emitted_rust_output_is_stable() {
    let app = ingest_app(fixture_path()).expect("ingest");
    let files = rust::emit(&app);
    let models = files
        .iter()
        .find(|f| f.path == PathBuf::from("src/models.rs"))
        .unwrap();
    let expected = "\
// Generated by Roundhouse.

pub struct Comment {
    pub id: i64,
    pub body: String,
    pub post_id: i64,
}

pub struct Post {
    pub id: i64,
    pub title: String,
}
";
    assert_eq!(models.content, expected);
}
