# Top-level entry point for the spinel-blog application.
#
# Reads a CGI request from ENV + $stdin, dispatches through the router
# + controller, writes the CGI response to $stdout. The shape spinel
# can ingest (no sockets, just env-vars + stdin + stdout) and the
# shape any CGI-aware web server can drive.
#
# Library usage (from tests):
#   require_relative "main"
#   Main.run(env_hash, body_io, response_io)
#
# Script usage:
#   REQUEST_METHOD=GET PATH_INFO=/articles ruby main.rb
# Or behind a CGI-aware server:
#   AddHandler cgi-script .rb       (apache)
#   alias /blog /path/to/main.rb    (nginx + fcgiwrap)

require_relative "runtime/in_memory_adapter"
# SqliteAdapter is hoisted to top-level so the spinel-AOT compile
# can statically resolve the `SqliteAdapter` constant referenced
# from `Base#save` etc. via the adapter dispatcher. Under CRuby the
# require is harmless (the gem-backed shim only opens a DB on
# `configure`); under spinel the FFI-backed shim only emits when
# `runtime/sqlite_adapter` is in the require graph.
require_relative "runtime/sqlite_adapter"
# Db primitive surface — backs the lowerer-emitted `_adapter_*`
# methods (Level-3 emit + Phase 1 Arel inline-SELECT expansions).
# Required before active_record so Base.rb's default `_adapter_*`
# helpers and per-model overrides find `Db` at constant-resolution
# time. See project_arel_compile_time_first.md.
require_relative "runtime/db"
# Base64 + Importmap shims. Both are required before any framework
# Ruby file that references them so spinel-AOT's static resolver
# sees them. The per-app config/importmap.rb (when emitted) reopens
# Importmap with the source-derived pins/entry; Base64 has no per-
# app override.
require_relative "runtime/base64"
require_relative "runtime/importmap"
require_relative "runtime/active_record"
require_relative "config/schema"
require_relative "runtime/action_dispatch"
require_relative "runtime/action_controller"
require_relative "runtime/broadcasts"
require_relative "runtime/cgi_io"
require_relative "config/routes"
# Per-app Importmap override (generated by Roundhouse from the source
# app's config/importmap.rb). Conditional because source apps without
# an importmap don't have this file emitted; the runtime/importmap.rb
# fallback stands in that case. The `begin/rescue` is CRuby-style
# error handling — spinel's static analyzer ignores the rescue path,
# which is fine here because Importmap is already defined by the
# fallback require above.
begin
  require_relative "config/importmap"
rescue LoadError
end
require_relative "app/views"

module Main
  # Dispatch one request. Pure function over (env, stdin, stdout) — no
  # global I/O. Tests construct env hashes + StringIO and call this
  # directly; the script path at the bottom of this file calls it
  # with real ENV + $stdin + $stdout.
  #
  # `ActionView::ViewHelpers` and `ActionDispatch::Router` are
  # written fully-qualified (rather than the prior `include
  # ActionView`/`include ActionDispatch` + bare names) so spinel-AOT's
  # constant resolver sees the references without walking included-
  # module namespaces — a path it doesn't currently follow.
  def self.run(env, stdin, stdout)
    ActionView::ViewHelpers.reset_slots!
    Broadcasts.reset_log!

    request = CgiIo.parse_request(env, stdin)
    # Prepend ROOT so a GET / request matches before falling through
    # to TABLE. ROOT is kept as a separate constant in routes.rb for
    # legibility (it's the only literal-pattern entry); the dispatch
    # composes them here so Router.match stays a flat-table walk.
    matched = ActionDispatch::Router.match(request[:method], request[:path],
                           [Routes.root] + Routes.table)
    if matched.nil?
      CgiIo.write_response(stdout, 404, "<h1>404 Not Found</h1>")
      return
    end

    controller = Main.instantiate_controller(matched[:controller])
    merged = matched[:path_params].dup
    request[:params].each { |k, v| merged[k] = v }
    controller.params  = ActionController::Parameters.new(merged)
    controller.session = {}

    # Decode inbound flash from cookies. Each flash key carries via
    # its own cookie (`flash_notice`, `flash_alert`) so the cookie
    # plumbing stays format-free.
    cookies = request[:cookies] || {}
    inbound_flash = {}
    inbound_flash[:notice] = cookies[:flash_notice] if cookies.key?(:flash_notice)
    inbound_flash[:alert]  = cookies[:flash_alert]  if cookies.key?(:flash_alert)
    controller.flash = inbound_flash

    controller.request_method = request[:method]
    controller.request_path   = request[:path]

    begin
      controller.process_action(matched[:action])
    rescue ActiveRecord::RecordNotFound
      CgiIo.write_response(stdout, 404, "<h1>404 Not Found</h1>")
      return
    end

    # Encode outbound flash. On render: clear the inbound cookies
    # (the action used flash for display; the next request shouldn't
    # see the same notice again). On redirect: ship the controller's
    # current flash as cookies for the next request to consume.
    out_cookies = {}
    if controller.location.nil?
      out_cookies[:flash_notice] = nil if cookies.key?(:flash_notice)
      out_cookies[:flash_alert]  = nil if cookies.key?(:flash_alert)
      page = Views::Layouts.application(controller.body)
      CgiIo.write_response(stdout, controller.status, page, set_cookies: out_cookies)
    else
      out_cookies[:flash_notice] = controller.flash[:notice] unless controller.flash[:notice].nil?
      out_cookies[:flash_alert]  = controller.flash[:alert]  unless controller.flash[:alert].nil?
      # Redirects: short-circuit body to a one-line "redirecting"
      # message; real browsers follow the Location header without
      # rendering the body anyway.
      CgiIo.write_response(stdout, controller.status,
        %(<a href="#{controller.location}">Redirecting</a>),
        location: controller.location,
        set_cookies: out_cookies)
    end
  end

  # Maps the routes-table controller symbol to a literal `.new`
  # constructor call. Spinel's hash specializations don't accept class
  # references as values, so the route table stores symbols and this
  # case turns the symbol back into an instance via direct
  # constructor calls (statically resolvable; no `.send`).
  def self.instantiate_controller(sym)
    case sym
    when :articles then ArticlesController.new
    when :comments then CommentsController.new
    end
  end

  # First-time setup. Idempotent: skips when already configured (so
  # tests that load main.rb don't conflict with their own test_helper
  # setup).
  #
  # When `BLOG_DB` env var names a path, configure SqliteAdapter
  # against that file — required for the dev server, which forks a
  # fresh CGI process per request and would otherwise lose all data
  # between requests if every fork got its own InMemoryAdapter. CRuby
  # tests bypass this entirely (they configure SqliteAdapter via
  # test_helper before main.rb loads).
  #
  # The eventual Spinel-target build uses InMemoryAdapter (no FFI
  # required); leave that as the unset-env fallback so the
  # Spinel-compiled binary still has a working default.
  def self.configure_default_adapter!
    return unless ActiveRecord.adapter.nil?
    db_path = ENV["BLOG_DB"]
    # Db (the primitive surface backing lowerer-emitted `_adapter_*`)
    # is configured unconditionally — `:memory:` when no BLOG_DB is
    # supplied, the named path otherwise. The higher-level adapter
    # slot (SqliteAdapter / InMemoryAdapter) handles the legacy
    # dispatcher path; Level-3 per-model primitives go through Db
    # directly and need it open before any model method runs.
    if !db_path.nil? && !db_path.empty?
      Db.configure(db_path)
      SqliteAdapter.configure(db_path)
      ActiveRecord.adapter = SqliteAdapter
      Schema.statements.each { |sql| SqliteAdapter.execute_ddl(sql) }
    else
      Db.configure(":memory:")
      InMemoryAdapter.configure
      ActiveRecord.adapter = InMemoryAdapter
      Schema.statements.each { |sql| InMemoryAdapter.execute_ddl(sql) }
      Schema.statements.each { |sql| Db.exec(sql) }
    end
  end
end

# Auto-run only when invoked as a script (`ruby main.rb`). When loaded
# via `require_relative "main"` from tests, the dispatch isn't
# triggered — tests call Main.run themselves with constructed I/O.
#
# The env hash is built explicitly from the CGI variables we read,
# rather than `ENV.to_h` — Spinel supports `ENV[]` indexing reliably
# but `.to_h` is on the verify list.
if __FILE__ == $PROGRAM_NAME
  Main.configure_default_adapter!
  env = {
    "REQUEST_METHOD" => ENV["REQUEST_METHOD"],
    "PATH_INFO"      => ENV["PATH_INFO"],
    "QUERY_STRING"   => ENV["QUERY_STRING"],
    "CONTENT_LENGTH" => ENV["CONTENT_LENGTH"],
    "CONTENT_TYPE"   => ENV["CONTENT_TYPE"],
    "HTTP_COOKIE"    => ENV["HTTP_COOKIE"],
  }
  Main.run(env, $stdin, $stdout)
end
