# Top-level entry point for the spinel-blog application.
#
# Reads a CGI request from ENV + $stdin, dispatches through the router
# + controller, writes the CGI response to $stdout. The shape spinel
# can ingest (no sockets, just env-vars + stdin + stdout) and the
# shape any CGI-aware web server can drive.
#
# Library usage (from tests):
#   require_relative "main"
#   Main.run(env_hash, body_io, response_io)
#
# Script usage:
#   REQUEST_METHOD=GET PATH_INFO=/articles ruby main.rb
# Or behind a CGI-aware server:
#   AddHandler cgi-script .rb       (apache)
#   alias /blog /path/to/main.rb    (nginx + fcgiwrap)

# SqliteAdapter is hoisted to top-level so the spinel-AOT compile
# can statically resolve the `SqliteAdapter` constant referenced
# from `Base#save` etc. via the adapter dispatcher. Under CRuby the
# require is harmless (the gem-backed shim only opens a DB on
# `configure`); under spinel the FFI-backed shim only emits when
# `runtime/sqlite_adapter` is in the require graph.
require_relative "runtime/sqlite_adapter"
# Db primitive surface — backs the lowerer-emitted `_adapter_*`
# methods (Level-3 emit + Phase 1 Arel inline-SELECT expansions).
# Required before active_record so Base.rb's default `_adapter_*`
# helpers and per-model overrides find `Db` at constant-resolution
# time. See project_arel_compile_time_first.md.
require_relative "runtime/db"
# Base64 + JSON + Importmap shims. All required before any framework
# Ruby file that references them so spinel-AOT's static resolver
# sees the constants. The per-app config/importmap.rb (when emitted)
# reopens Importmap with the source-derived pins/entry; Base64 and
# JSON have no per-app override. Under CRuby these shims override
# the stdlib equivalents with semantically-identical implementations
# for the surface framework Ruby actually uses.
require_relative "runtime/base64"
require_relative "runtime/json"
# JsonBuilder — the JSON encoding primitives the Jbuilder lowerer
# emits calls to (`Views::Articles.article_json` etc.). Separate from
# `runtime/json.rb`'s `JSON.generate` shim: this module exposes
# `JsonBuilder.encode_value` / `encode_string` for per-value encoding.
require_relative "runtime/json_builder"
require_relative "runtime/importmap"
# ActiveSupport::Duration value class — the emit grounds `70.days` etc.
# to `ActiveSupport::Duration.days(70)`, so the class must be loadable
# on every tree (the CRuby overlay swaps in its Time-reopen-augmented
# sibling at the same path).
require_relative "runtime/active_support_duration"
require_relative "runtime/rails"
# Park RAILS_ENV where the typed runtime can read it (`Rails.env`
# defaults to development when unset).
Rails.env_name = ENV["RAILS_ENV"]
# Per-app Rails::Application reopen — the app's real config methods
# (`Rails.application.name` in layouts). Emitted unconditionally (a
# stub reopen when the source app has none); loads right after the
# runtime shim it reopens.
require_relative "config/application"
require_relative "runtime/active_record"
require_relative "config/schema"
require_relative "runtime/action_dispatch"
# Typed Request value object (remote_ip / referer / xhr? / env bag) —
# spinel-tree only; the CRuby overlay keeps its CGI-env-backed Request
# at runtime/action_dispatch_request.rb and the two shapes must not
# blend.
require_relative "runtime/action_dispatch/request"
require_relative "runtime/action_controller"
require_relative "runtime/broadcasts"
require_relative "runtime/tep/tep"
# Action Cable WebSocket glue — the /cable endpoint + the Broadcasts
# transport that fans Turbo Stream fragments out to subscribers. Loaded
# after tep (uses Tep::WebSocket / Scheduler / Broadcast) and broadcasts
# (registers as its transport at boot).
require_relative "runtime/cable"
require_relative "config/routes"
# Per-app Importmap override (generated by Roundhouse from the source
# app's config/importmap.rb). Reopens the fallback module to supply
# the source's actual pins. spinel/master fixed module-reopen with
# same-name cmeth dispatch (matz/spinel#517), so this is now a plain
# require_relative under both CRuby and spinel.
require_relative "config/importmap"
# The app/models.rb aggregator (generated — see apply_models_aggregator)
# loads every model/support class. Model files only require their own
# LOAD-time deps (superclass, class-body consts); method-body references
# between them count on this line — and spinel-AOT's static require
# graph reaches every model file through it.
require_relative "app/models"
require_relative "app/views"
# Session-backed CSRF token — reopens ViewHelpers, so it must load
# AFTER everything that defines the shared empty-string default (the
# same ordering contract as the CRuby overlay's
# action_controller_session require).
require_relative "runtime/csrf_token"

module Main

  # Maps the routes-table controller symbol to a literal `.new`
  # constructor call. Spinel's hash specializations don't accept class
  # references as values, so the route table stores symbols and this
  # case turns the symbol back into an instance via direct
  # constructor calls (statically resolvable; no `.send`).
  def self.instantiate_controller(sym)
    case sym
    when :articles then ArticlesController.new
    when :comments then CommentsController.new
    end
  end

  # Re-nest tep's flat bracket-keyed params into the Rails-style nested
  # hash the per-resource *Params.from_raw factories expect, and merge
  # the route's path captures (id, ...).
  #
  # tep parses a form body into flat keys (`article[title]` -> "..."`).
  # The blog nests exactly one resource per request, so collect its
  # bracketed fields into a single String->String sub-hash, then assign
  # that sub-hash into the outer poly hash alongside the bare-key
  # scalars + path captures. The "assign a String or a whole sub-hash"
  # shape (rather than mutating `out[outer][inner]` in place) is what
  # makes spinel type `out` as the String->(String|Hash) the controller
  # reads — same discipline as test_helper's stringify_keys.
  def self.nest_params(flat, path_params)
    # Split the flat bracket-keyed params into String->String locals
    # FIRST (sub = the one nested resource's fields, scalars = bare
    # keys). Iterating `flat` only into String-typed str_hashes keeps
    # `flat` (req.req_params) itself String->String — assigning its values
    # straight into the poly `out` below would back-propagate and widen
    # req.req_params to poly, breaking unrelated String reads of it.
    sub = Tep.str_hash
    scalars = Tep.str_hash
    outer_name = +""
    flat.each do |k, v|
      ob = k.index("[")
      if ob.nil?
        scalars[k] = v
      else
        cb = k.index("]", ob + 1)
        if cb.nil?
          scalars[k] = v
        else
          outer_name = k[0, ob]
          sub[k[(ob + 1)...cb]] = v
        end
      end
    end
    # Assemble the poly result. deep_dup yields Hash[String, untyped],
    # wide enough to hold both String scalars and the nested sub-hash;
    # poly-into-poly unifies (a raw StrStrHash value would not).
    out = Main.deep_dup(path_params)
    scalars.each { |k, v| out[k] = v }
    if outer_name.length > 0
      out[outer_name] = Main.deep_dup(sub)
    end
    out
  end

  # Rebuild a string-keyed Hash, recursing into nested Hash values.
  # Strictly typed `(Hash) -> Hash`; the return is Hash[String, untyped]
  # because `out` is assigned both a Hash (deep_dup(v)) and a leaf (v).
  # Identical shape to test_helper's stringify_keys — the construction
  # spinel reliably types as a poly-valued hash.
  def self.deep_dup(h)
    out = {}
    h.each do |k, v|
      if v.is_a?(Hash)
        out[k.to_s] = Main.deep_dup(v)
      else
        out[k.to_s] = v
      end
    end
    out
  end

  # First-time setup. Idempotent: skips when already configured (so
  # tests that load main.rb don't conflict with their own test_helper
  # setup).
  #
  # When `BLOG_DB` env var names a path, configure SqliteAdapter
  # against that file. Otherwise default to the Rails-traditional
  # `storage/development.sqlite3` — persisted across requests and
  # consistent with every other target's default. The archive ships
  # `storage/.keep`, so the directory exists for first-run open.
  # Tests configure `:memory:` explicitly through their own setup, so
  # this server default never reaches them (the `adapter.nil?` guard
  # also short-circuits when a test already configured the adapter).
  def self.configure_default_adapter!
    return unless ActiveRecord.adapter.nil?
    db_path = ENV["BLOG_DB"]
    path = (!db_path.nil? && !db_path.empty?) ? db_path : "storage/development.sqlite3"
    # SqliteAdapter.configure delegates to Db.configure (single shared
    # connection); both the legacy AR-adapter dispatch path and the
    # Level-3 lowerer-emitted `_adapter_*` path read through one handle.
    SqliteAdapter.configure(path)
    ActiveRecord.adapter = SqliteAdapter
    Schema.statements.each { |sql| SqliteAdapter.execute_ddl(sql) }
  end

  # True for request paths that map to a file under static/: the
  # importmap-pinned assets at /assets/* plus the layout's root icons.
  # The `..` guard blocks path-traversal escapes (`/assets/../../etc`)
  # before the path is concatenated onto the static/ root.
  def self.static_asset?(path)
    if path.include?("..")
      return false
    end
    path.start_with?("/assets/") || path == "/icon.png" || path == "/icon.svg"
  end

  # Resolve a (pre-validated) static URL to its on-disk path under
  # static/ and hand it to the Tep server to sendfile. sphttp can't
  # infer Content-Type, so set it from the extension here; a missing
  # file 404s (Sock.sphttp_filesize returns -1 when stat fails). The
  # working directory is the app root — where `make assets` writes
  # static/ and `./build/blog` is launched from.
  def self.serve_static(path, res)
    disk = "static" + path
    if Sock.sphttp_filesize(disk) < 0
      res.status = 404
      res.body = "<h1>404 Not Found</h1>"
      return nil
    end
    res.headers["Content-Type"] = Main.asset_content_type(path)
    res.send_file(disk)
    nil
  end

  # Minimal filename-extension → MIME map for the asset kinds this app
  # serves. Anything unrecognized falls back to octet-stream.
  def self.asset_content_type(path)
    if path.end_with?(".css")
      "text/css; charset=utf-8"
    elsif path.end_with?(".js")
      "text/javascript; charset=utf-8"
    elsif path.end_with?(".svg")
      "image/svg+xml"
    elsif path.end_with?(".png")
      "image/png"
    elsif path.end_with?(".json")
      "application/json"
    else
      "application/octet-stream"
    end
  end

  # Tep::Server callback. Routes, runs the controller, copies
  # status/body/location back, and persists per-request flash via
  # cookies (flash_notice / flash_alert) so a `redirect_to … notice:`
  # shows once on the redirect target and is then swept — matching the
  # cookie-backed Rack path in ruby_overlay/main.rb. Session is still a
  # fresh per-request object (not yet cookie-persisted), same as Rack.
  def self.dispatch(req, res)
    ActionView::ViewHelpers.reset_slots!
    Broadcasts.reset_log!

    # Action Cable: upgrade /cable to a WebSocket and hand off to the
    # Cable glue. Tep::Server::Scheduled's write path runs the recv
    # loop once res.start_websocket is set; none of the HTTP routing
    # below applies to the upgraded connection.
    if req.path == "/cable"
      Cable.upgrade(req, res)
      return
    end

    # Static assets: the importmap-pinned JS + the stylesheets, laid
    # out by `make assets` under static/assets/, plus the layout's root
    # icons. The Tep server sphttp-sendfiles whatever res.send_file
    # names; resolve the URL to its on-disk path + Content-Type here.
    # None of the dynamic routing below applies to a served file.
    if Main.static_asset?(req.path)
      Main.serve_static(req.path, res)
      return
    end

    request_format = :html
    request_path = req.path
    if request_path.end_with?(".json")
      request_format = :json
      request_path = request_path[0...-5]
    end

    # Rails-style method override: destroy/update forms POST a hidden
    # `_method=delete|patch|put` (browsers can't emit those verbs from a
    # form). Honor it before route matching so the right action runs.
    verb = req.verb
    if verb == "POST"
      override = req.req_params.fetch("_method", "").upcase
      if override == "PATCH" || override == "PUT" || override == "DELETE"
        verb = override
      end
    end

    matched = ActionDispatch::Router.match(verb, request_path,
                           [RouteTable.root] + RouteTable.table)
    if matched.nil?
      res.status = 404
      res.body = "<h1>404 Not Found</h1>"
      return
    end

    controller = Main.instantiate_controller(matched.controller)
    # Build the nested Rails-style params (params["article"]["title"])
    # that the per-resource *Params.from_raw factories expect. tep parses
    # the form body into flat bracket keys (req.req_params["article[title]"]);
    # re-nest them + merge the route's path captures (id, ...).
    controller.params = Main.nest_params(req.req_params, matched.path_params)
    # Typed request object + per-request context statics. Helpers are
    # module functions with no controller in scope; the emit rewrites
    # their bare `request` reads to `ActionController::Current.request`
    # and the layout reaches flash through `Current.controller`.
    request_obj = ActionDispatch::Request.new
    request_obj.request_method = verb
    request_obj.path = request_path
    qm = req.raw_path.index("?")
    request_obj.query_string = req.raw_path[qm + 1, req.raw_path.length].to_s unless qm.nil?
    request_obj.remote_ip = req.remote_host
    request_obj.referer = req.req_headers.fetch("referer", "")
    request_obj.host = req.req_headers.fetch("host", "localhost")
    request_obj.format = request_format == :json ? "json" : "html"
    request_obj.body = req.raw_body
    env = {}
    env["HTTP_USER_AGENT"] = req.req_headers.fetch("user-agent", "")
    env["HTTP_X_REQUESTED_WITH"] = req.req_headers.fetch("x-requested-with", "")
    request_obj.env = env
    controller.request = request_obj
    ActionController::Current.request = request_obj
    ActionController::Current.controller = controller
    # Cookie-carried session: restore the whole session from the
    # `_session` cookie (url-encoded k=v pairs; empty when absent or
    # garbled). Persisted below only when the encoding changed — an
    # action that leaves the session untouched emits no Set-Cookie.
    session_in = req.cookies.fetch("_session", "")
    controller.session = ActionDispatch::Session.from_cookie(session_in)
    # Inbound flash: each message rides its own cookie (flash_notice /
    # flash_alert) so the value carries verbatim, no serialization. Load
    # through the constructor (NOT flash[:k]=) so to_persisted's show-once
    # diff sees them as carried-in (value == @notice_was) and sweeps them.
    # `fetch(name, "")` avoids a missing-key raise; a flash message is
    # never empty, so non-empty == present.
    inbound_flash = Tep.str_hash
    cin = req.cookies.fetch("flash_notice", "")
    inbound_flash["notice"] = cin if cin.length > 0
    ain = req.cookies.fetch("flash_alert", "")
    inbound_flash["alert"] = ain if ain.length > 0
    controller.flash = ActionDispatch::Flash.new(inbound_flash)
    controller.request_format = request_format

    begin
      controller.process_action(matched.action)
    rescue ActiveRecord::RecordNotFound
      res.status = 404
      res.body = "<h1>404 Not Found</h1>"
      return
    end

    res.status = controller.status
    if controller.request_format == :json
      res.body = controller.body
    else
      res.body = Views::Layouts.application(controller.body)
    end
    res.headers["Location"] = controller.location unless controller.location.nil?

    # Outbound flash: persist messages set THIS request for the NEXT one.
    # `to_persisted` returns only notice/alert that differ from the
    # carried-in value (show-once); clear any inbound cookie that wasn't
    # re-persisted so a consumed flash doesn't stick on the next nav.
    persisted = controller.flash.to_persisted
    pn = persisted.fetch("notice", "")
    if pn.length > 0
      Main.set_flash_cookie(res, "flash_notice", pn)
    elsif req.cookies.fetch("flash_notice", "").length > 0
      Main.clear_flash_cookie(res, "flash_notice")
    end
    pa = persisted.fetch("alert", "")
    if pa.length > 0
      Main.set_flash_cookie(res, "flash_alert", pa)
    elsif req.cookies.fetch("flash_alert", "").length > 0
      Main.clear_flash_cookie(res, "flash_alert")
    end

    # Session persistence: re-encode whatever the action (or a lazy
    # CSRF token generated during the layout render above) left in the
    # session; Set-Cookie only on change. An emptied session
    # (reset_session) clears the cookie. Runs after the render so
    # lazily-created tokens are captured, and on redirects too (login
    # sets `session[:u]` then 302s).
    session_out = controller.session.to_cookie
    if session_out != session_in
      if session_out == ""
        Main.clear_flash_cookie(res, "_session")
      else
        Main.set_flash_cookie(res, "_session", session_out)
      end
    end
  end

  # Flash cookies are HttpOnly + Path=/; the read side is server-only
  # (no JS access). A set carries the message to the next request; a
  # clear (empty value + Max-Age=0) expires a consumed one.
  def self.set_flash_cookie(res, name, value)
    opts = Tep.str_hash
    opts["Path"] = "/"
    opts["HttpOnly"] = +""
    res.set_cookie(name, value, opts)
  end

  def self.clear_flash_cookie(res, name)
    opts = Tep.str_hash
    opts["Path"] = "/"
    opts["Max-Age"] = "0"
    opts["HttpOnly"] = +""
    res.set_cookie(name, "", opts)
  end
end

# Auto-run only when invoked as a script (`ruby main.rb`). When loaded
# via `require_relative "main"` from tests, the dispatch isn't
# triggered — tests call Main.run themselves with constructed I/O.
#
# Spinel-AOT entry: configure DB, register the Action Cable transport,
# then start the scheduled Tep server with Main as the app. This file
# is the spinel-target main.rb — only consumed by `make build` →
# compiled native binary. The CRuby development path uses
# `ruby_overlay/main.rb` (Puma/Rack), which keeps the
# `__FILE__ == $PROGRAM_NAME` guard because under Puma the file is
# required, not invoked directly.
#
# Tep::Server::Scheduled expects an app object with a `dispatch(req,
# res)` instance method. Wrap Main's class-method dispatch in a thin
# instance so spinel resolves @app.dispatch through normal user-class
# dispatch instead of trying to call a module method. (The scheduled
# server's cmeth handlers actually dispatch via Tep::APP.dispatch,
# which Tep::App delegates to Main.dispatch — same destination.)
class MainApp
  def dispatch(req, res)
    # Lease one pooled DB connection for the whole request so concurrent
    # connection-fibers each read/write through their own handle rather
    # than serializing on a single shared one. Mirrors the ruby target's
    # config.ru wrap; the cooperative-fiber analog of Puma's thread pool.
    Db.with_connection { Main.dispatch(req, res) }
  end
end

# Unconditional entry — the spinel-compiled binary's sole purpose is
# to start the server. `if __FILE__ == $PROGRAM_NAME` would have
# gated this in CRuby script mode, but under spinel-AOT `__FILE__`
# is the source file name (`"main.rb"`) and `$PROGRAM_NAME` is the
# binary's argv[0] (e.g. `"./build/blog"`), so the guard always
# returns false. The Ruby-overlay sibling keeps the guard for its
# Puma/Rack-required-from-config.ru shape.
#
# CLI surface. Flags override the PORT/WORKERS env vars; --help exits
# before any DB or server setup runs. Parsed with a plain while loop
# (no OptionParser — stdlib optparse isn't in the spinel subset).
port = (ENV["PORT"] || "3000").to_i
workers = (ENV["WORKERS"] || "1").to_i
i = 0
while i < ARGV.length
  arg = ARGV[i]
  if arg == "--help" || arg == "-h"
    puts "usage: " + $PROGRAM_NAME + " [options]"
    puts ""
    puts "  -p, --port N     listen port (default 3000; PORT env)"
    puts "  -w, --workers N  prefork workers (default 1; WORKERS env)"
    puts "  -h, --help       show this help and exit"
    puts ""
    puts "  SQLite file: BLOG_DB env (default storage/development.sqlite3)"
    exit(0)
  elsif (arg == "--port" || arg == "-p") && i + 1 < ARGV.length
    port = ARGV[i + 1].to_i
    i += 2
  elsif (arg == "--workers" || arg == "-w") && i + 1 < ARGV.length
    workers = ARGV[i + 1].to_i
    i += 2
  else
    $stderr.puts "unknown option: " + arg + " (try --help)"
    exit(1)
  end
end
if port <= 0 || port > 65535
  $stderr.puts "invalid port: " + port.to_s
  exit(1)
end
Main.configure_default_adapter!
# Wire model after-commit Turbo Stream broadcasts to the live WebSocket
# fan-out. Without this, broadcasts only land in the in-memory log.
Broadcasts.set_transport(Cable::Transport.new)
# Tep::Server::Scheduled is the fiber-per-connection server (Falcon-
# shape). Required for WebSockets: the /cable recv loop parks on
# Tep::Scheduler.io_wait so a held-open connection doesn't pin the
# worker. It serves plain HTTP too — a superset of the blocking
# Tep::Server the binary used before cable landed.
Tep::Server::Scheduled.new(MainApp.new).run(port, workers, false)
