# Top-level entry point for the spinel-blog application.
#
# Reads a CGI request from ENV + $stdin, dispatches through the router
# + controller, writes the CGI response to $stdout. The shape spinel
# can ingest (no sockets, just env-vars + stdin + stdout) and the
# shape any CGI-aware web server can drive.
#
# Library usage (from tests):
#   require_relative "main"
#   Main.run(env_hash, body_io, response_io)
#
# Script usage:
#   REQUEST_METHOD=GET PATH_INFO=/articles ruby main.rb
# Or behind a CGI-aware server:
#   AddHandler cgi-script .rb       (apache)
#   alias /blog /path/to/main.rb    (nginx + fcgiwrap)

# SqliteAdapter is hoisted to top-level so the spinel-AOT compile
# can statically resolve the `SqliteAdapter` constant referenced
# from `Base#save` etc. via the adapter dispatcher. Under CRuby the
# require is harmless (the gem-backed shim only opens a DB on
# `configure`); under spinel the FFI-backed shim only emits when
# `runtime/sqlite_adapter` is in the require graph.
require_relative "runtime/sqlite_adapter"
# Db primitive surface — backs the lowerer-emitted `_adapter_*`
# methods (Level-3 emit + Phase 1 Arel inline-SELECT expansions).
# Required before active_record so Base.rb's default `_adapter_*`
# helpers and per-model overrides find `Db` at constant-resolution
# time. See project_arel_compile_time_first.md.
require_relative "runtime/db"
# Base64 + JSON + Importmap shims. All required before any framework
# Ruby file that references them so spinel-AOT's static resolver
# sees the constants. The per-app config/importmap.rb (when emitted)
# reopens Importmap with the source-derived pins/entry; Base64 and
# JSON have no per-app override. Under CRuby these shims override
# the stdlib equivalents with semantically-identical implementations
# for the surface framework Ruby actually uses.
require_relative "runtime/base64"
require_relative "runtime/json"
# JsonBuilder — the JSON encoding primitives the Jbuilder lowerer
# emits calls to (`Views::Articles.article_json` etc.). Separate from
# `runtime/json.rb`'s `JSON.generate` shim: this module exposes
# `JsonBuilder.encode_value` / `encode_string` for per-value encoding.
require_relative "runtime/json_builder"
require_relative "runtime/importmap"
require_relative "runtime/active_record"
require_relative "config/schema"
require_relative "runtime/action_dispatch"
require_relative "runtime/action_controller"
require_relative "runtime/broadcasts"
require_relative "runtime/tep/tep"
require_relative "config/routes"
# Per-app Importmap override (generated by Roundhouse from the source
# app's config/importmap.rb). Reopens the fallback module to supply
# the source's actual pins. spinel/master fixed module-reopen with
# same-name cmeth dispatch (matz/spinel#517), so this is now a plain
# require_relative under both CRuby and spinel.
require_relative "config/importmap"
require_relative "app/views"

module Main

  # Maps the routes-table controller symbol to a literal `.new`
  # constructor call. Spinel's hash specializations don't accept class
  # references as values, so the route table stores symbols and this
  # case turns the symbol back into an instance via direct
  # constructor calls (statically resolvable; no `.send`).
  def self.instantiate_controller(sym)
    case sym
    when :articles then ArticlesController.new
    when :comments then CommentsController.new
    end
  end

  # First-time setup. Idempotent: skips when already configured (so
  # tests that load main.rb don't conflict with their own test_helper
  # setup).
  #
  # When `BLOG_DB` env var names a path, configure SqliteAdapter
  # against that file — required for the dev server, which forks a
  # fresh CGI process per request and would otherwise lose all data
  # between requests. Without BLOG_DB, fall back to `:memory:` — works
  # for the spinel-compiled binary (FFI sqlite is universal) and the
  # one-shot CGI invocation, and is per-process (no persistence across
  # forks, which is fine for both).
  def self.configure_default_adapter!
    return unless ActiveRecord.adapter.nil?
    db_path = ENV["BLOG_DB"]
    path = (!db_path.nil? && !db_path.empty?) ? db_path : ":memory:"
    # SqliteAdapter.configure delegates to Db.configure (single shared
    # connection); both the legacy AR-adapter dispatch path and the
    # Level-3 lowerer-emitted `_adapter_*` path read through one handle.
    SqliteAdapter.configure(path)
    ActiveRecord.adapter = SqliteAdapter
    Schema.statements.each { |sql| SqliteAdapter.execute_ddl(sql) }
  end

  # Tep::Server callback — MINIMAL form. Routes, runs the controller,
  # copies status/body back. Skips flash + session lifecycle for now
  # so the transport-only validation (sphttp eliminates io.write/read
  # on int) can be measured without poly-dispatch collisions from
  # cookie/session data flow narrowing field types.
  #
  # Discovery loop: add features back one at a time, each time noting
  # what shape pressure the integration produces. See WHY.md /
  # tep-transport-experiment branch notes for the inventory.
  def self.dispatch(req, res)
    ActionView::ViewHelpers.reset_slots!
    Broadcasts.reset_log!

    request_format = :html
    request_path = req.path
    if request_path.end_with?(".json")
      request_format = :json
      request_path = request_path[0...-5]
    end

    matched = ActionDispatch::Router.match(req.verb, request_path,
                           [Routes.root] + Routes.table)
    if matched.nil?
      res.status = 404
      res.body = "<h1>404 Not Found</h1>"
      return
    end

    controller = Main.instantiate_controller(matched[:controller])
    merged = matched[:path_params].dup
    req.params.each { |k, v| merged[k] = v }
    controller.params  = merged
    controller.session = ActionDispatch::Session.new
    controller.flash   = ActionDispatch::Flash.new
    controller.request_format = request_format

    begin
      controller.process_action(matched[:action])
    rescue ActiveRecord::RecordNotFound
      res.status = 404
      res.body = "<h1>404 Not Found</h1>"
      return
    end

    res.status = controller.status
    if controller.request_format == :json
      res.body = controller.body
    else
      res.body = Views::Layouts.application(controller.body)
    end
    res.headers["Location"] = controller.location unless controller.location.nil?
  end
end

# Auto-run only when invoked as a script (`ruby main.rb`). When loaded
# via `require_relative "main"` from tests, the dispatch isn't
# triggered — tests call Main.run themselves with constructed I/O.
#
# Spinel-AOT entry: configure DB then start Tep::Server with Main as
# the app. CRuby script-mode also takes this path now; the prior CGI
# smoke (REQUEST_METHOD=GET PATH_INFO=/articles ruby main.rb) is parked
# behind the Tep::Server adoption.
# Tep::Server expects an app object with a `dispatch(req, res)`
# instance method. Wrap Main's class-method dispatch in a thin
# instance so spinel resolves @app.dispatch through normal user-class
# dispatch instead of trying to call a module method.
class MainApp
  def dispatch(req, res)
    Main.dispatch(req, res)
  end
end

if __FILE__ == $PROGRAM_NAME
  Main.configure_default_adapter!
  port = (ENV["PORT"] || "3000").to_i
  workers = (ENV["WORKERS"] || "1").to_i
  Tep::Server.new(MainApp.new).run(port, workers, false)
end
