//! Pass-2 controller emission — each public action becomes a top-level
//! `func ArticlesIndex(ctx *ActionContext) ActionResponse` returning
//! ActionResponse directly. The router registers these as Handler values
//! at package init time.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use super::expr::emit_expr;
use super::shared::{go_action_handler_name, go_field_name, pascalize_word};
use crate::App;
use crate::dialect::Controller;
use crate::expr::{Expr, ExprNode, Literal};
use crate::ident::Symbol;
use crate::lower::CtrlWalker as _;
use crate::naming::snake_case;

pub(super) fn emit_controller_pass2(
    c: &Controller,
    known_models: &[Symbol],
    app: &App,
) -> EmittedFile {
    let name = c.name.0.as_str();
    let resource = crate::lower::resource_from_controller_name(name);
    let model_class = crate::naming::singularize_camelize(&resource);
    let has_model = known_models.iter().any(|m| m.as_str() == model_class);
    let parent = crate::lower::find_nested_parent(app, name);
    let permitted = crate::lower::permitted_fields_for(c, &resource)
        .unwrap_or_else(|| crate::lower::default_permitted_fields(app, &model_class));

    let (public_actions, _private) = crate::lower::split_public_private(c);
    let mut body = String::new();
    for action in &public_actions {
        writeln!(body).unwrap();
        let la = crate::lower::lower_action(
            action.name.as_str(),
            &resource,
            &model_class,
            has_model,
            parent.as_ref(),
            &permitted,
        );
        emit_go_action(&mut body, c.name.0.as_str(), &la, &action.body, known_models, c);
    }

    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s, "package app").unwrap();
    writeln!(s).unwrap();
    // Conditional imports: Go errors on unused imports, so only
    // pull in packages the emitted body actually references.
    let mut imports: Vec<&str> = vec!["strconv"];
    if body.contains("sort.") {
        imports.push("sort");
    }
    if imports.len() == 1 {
        writeln!(s, "import \"{}\"", imports[0]).unwrap();
    } else {
        writeln!(s, "import (").unwrap();
        for imp in &imports {
            writeln!(s, "\t\"{imp}\"").unwrap();
        }
        writeln!(s, ")").unwrap();
    }
    writeln!(s).unwrap();
    writeln!(s, "var _ = strconv.Itoa").unwrap();
    if imports.contains(&"sort") {
        writeln!(s, "var _ = sort.Slice").unwrap();
    }
    s.push_str(&body);

    let fname = format!("app/{}.go", snake_case(name));
    EmittedFile { path: PathBuf::from(fname), content: s }
}

fn go_view_fn(model_class: &str, suffix: &str) -> String {
    let plural = crate::naming::pluralize_snake(model_class);
    format!("Render{}{}", pascalize_word(&plural), pascalize_word(suffix))
}

/// Render one LoweredAction as a top-level Go handler function.
/// Body emission flows through the walker; the ActionKind dispatch
/// is gone (TS/Rust/Python/Crystal precedent). Go's one wrinkle is
/// nullable ModelFind — a pointer that may be nil — handled with a
/// post-Assign nil-guard synthesized by the walker.
fn emit_go_action(
    out: &mut String,
    controller: &str,
    la: &crate::lower::LoweredAction,
    body: &Expr,
    known_models: &[Symbol],
    controller_item: &Controller,
) {
    let handler = go_action_handler_name(controller, &la.name);

    if !la.has_model {
        writeln!(out, "func {handler}(_ctx *ActionContext) ActionResponse {{").unwrap();
        writeln!(out, "\treturn ActionResponse{{}}").unwrap();
        writeln!(out, "}}").unwrap();
        return;
    }

    use crate::lower::CtrlWalker;
    let normalized =
        crate::lower::normalize_action_body(controller_item, la.name.as_str(), body);
    let mut emitter = GoEmitter {
        ctx: crate::lower::WalkCtx {
            known_models,
            model_class: la.model_class.as_str(),
            resource: la.resource.as_str(),
            parent: la.parent.as_ref(),
            permitted: &la.permitted,
            adapter: &crate::adapter::SqliteAdapter,
        },
        state: crate::lower::WalkState::new(),
    };
    let body_src = emitter.walk_action_body(&normalized);
    let ctx_name = if emitter.state.uses_context { "ctx" } else { "_ctx" };
    writeln!(out, "func {handler}({ctx_name} *ActionContext) ActionResponse {{").unwrap();
    out.push_str(&body_src);
    writeln!(out, "}}").unwrap();
}

struct GoEmitter<'a> {
    ctx: crate::lower::WalkCtx<'a>,
    state: crate::lower::WalkState,
}

impl<'a> crate::lower::CtrlWalker<'a> for GoEmitter<'a> {
    fn ctx(&self) -> &crate::lower::WalkCtx<'a> { &self.ctx }
    fn state_mut(&mut self) -> &mut crate::lower::WalkState { &mut self.state }
    fn indent_unit(&self) -> &'static str { "\t" }

    fn write_assign(&mut self, name: &str, value: &Expr, indent: &str, out: &mut String) {
        // Go's one per-target Assign nuance: when the RHS is a
        // ModelFind on a known model, append a nil-guard so
        // downstream `record.Method()` doesn't nil-panic.
        if let Some((class, id_expr)) = model_find_shape(value, self.ctx.known_models) {
            let id_s = self.render_expr(id_expr);
            writeln!(out, "{indent}{name} := {class}Find({id_s})").unwrap();
            writeln!(out, "{indent}if {name} == nil {{ {name} = &{class}{{}} }}").unwrap();
            return;
        }
        let rhs = self.render_expr(value);
        writeln!(out, "{indent}{name} := {rhs}").unwrap();
    }

    fn write_create_expansion(
        &mut self,
        var_name: &str,
        class: &str,
        indent: &str,
        out: &mut String,
    ) {
        writeln!(out, "{indent}{var_name} := &{class}{{}}").unwrap();
        if let Some(parent) = self.ctx.parent {
            let fk = go_field_name(&format!("{}_id", parent.singular));
            writeln!(
                out,
                "{indent}{var_name}.{fk}, _ = strconv.ParseInt(ctx.Params[\"{}_id\"], 10, 64)",
                parent.singular,
            )
            .unwrap();
            self.state.uses_context = true;
        }
        let permitted: Vec<String> = self.ctx.permitted.iter().cloned().collect();
        let resource = self.ctx.resource.to_string();
        for field in &permitted {
            let go_field = go_field_name(field);
            writeln!(
                out,
                "{indent}{var_name}.{go_field} = ctx.Params[\"{resource}[{field}]\"]",
            )
            .unwrap();
            self.state.uses_context = true;
        }
    }

    fn write_if(
        &mut self,
        cond: &Expr,
        then_branch: &Expr,
        else_branch: &Expr,
        indent: &str,
        depth: usize,
        is_tail: bool,
        out: &mut String,
    ) {
        let cond_s = self.render_expr(cond);
        writeln!(out, "{indent}if {cond_s} {{").unwrap();
        self.walk_stmt(then_branch, out, depth + 1, is_tail);
        if !crate::lower::is_empty_body(else_branch) {
            writeln!(out, "{indent}}} else {{").unwrap();
            self.walk_stmt(else_branch, out, depth + 1, is_tail);
        }
        writeln!(out, "{indent}}}").unwrap();
    }

    fn write_update_if(
        &mut self,
        recv: &Expr,
        then_branch: &Expr,
        else_branch: &Expr,
        indent: &str,
        depth: usize,
        is_tail: bool,
        out: &mut String,
    ) {
        let recv_s = self.render_expr(recv);
        let permitted: Vec<String> = self.ctx.permitted.iter().cloned().collect();
        let resource = self.ctx.resource.to_string();
        for field in &permitted {
            let go_field = go_field_name(field);
            writeln!(
                out,
                "{indent}if v, ok := ctx.Params[\"{resource}[{field}]\"]; ok {{ {recv_s}.{go_field} = v }}",
            )
            .unwrap();
            self.state.uses_context = true;
        }
        writeln!(out, "{indent}if {recv_s}.Save() {{").unwrap();
        self.walk_stmt(then_branch, out, depth + 1, is_tail);
        if !crate::lower::is_empty_body(else_branch) {
            writeln!(out, "{indent}}} else {{").unwrap();
            self.walk_stmt(else_branch, out, depth + 1, is_tail);
        }
        writeln!(out, "{indent}}}").unwrap();
    }

    fn write_response_stmt(&mut self, r: &str, _is_tail: bool, indent: &str, out: &mut String) {
        writeln!(out, "{indent}return {r}").unwrap();
    }

    fn write_expr_stmt(&mut self, s: &str, indent: &str, out: &mut String) {
        writeln!(out, "{indent}{s}").unwrap();
    }

    fn render_expr(&mut self, expr: &Expr) -> String {
        if let ExprNode::Send { recv, method, args, block, .. } = &*expr.node {
            if let Some(stmt) = self.render_send_stmt(
                recv.as_ref(), method.as_str(), args, block.as_ref(), "",
            ) {
                return match stmt {
                    crate::lower::Stmt::Response(r) => r,
                    crate::lower::Stmt::Expr(s) => s,
                };
            }
            let args_s: Vec<String> = args.iter().map(|a| self.render_expr(a)).collect();
            return match recv {
                None if args.is_empty() => method.to_string(),
                None => format!("{method}({})", args_s.join(", ")),
                Some(r) => {
                    let recv_s = self.render_expr(r);
                    if args.is_empty() {
                        format!("{recv_s}.{}()", pascalize_word(method.as_str()))
                    } else {
                        format!("{recv_s}.{}({})", pascalize_word(method.as_str()), args_s.join(", "))
                    }
                }
            };
        }
        if let ExprNode::Ivar { name } = &*expr.node {
            return name.to_string();
        }
        emit_expr(expr)
    }

    fn render_send_stmt(
        &mut self,
        recv: Option<&Expr>,
        method: &str,
        args: &[Expr],
        block: Option<&Expr>,
        // Go multiplexes via goroutines; no async syntax, prefix unused.
        _suspending_prefix: &str,
    ) -> Option<crate::lower::Stmt> {
        use crate::lower::{SendKind, Stmt};
        let kind = crate::lower::classify_controller_send(
            recv, method, args, block, self.ctx.known_models,
        )?;
        Some(match kind {
            SendKind::ParamsAccess => {
                self.state.uses_context = true;
                Stmt::Expr("ctx.Params".to_string())
            }
            SendKind::ParamsIndex { key } => {
                self.state.uses_context = true;
                match &*key.node {
                    ExprNode::Lit { value: Literal::Sym { value: k } } => {
                        Stmt::Expr(format!("parseInt64(ctx.Params[\"{}\"])", k.as_str()))
                    }
                    _ => {
                        let k = self.render_expr(key);
                        Stmt::Expr(format!("ctx.Params[{k}]"))
                    }
                }
            }
            SendKind::ParamsExpect { args: pe_args } => {
                self.state.uses_context = true;
                match pe_args.first().map(|e| &*e.node) {
                    Some(ExprNode::Lit { value: Literal::Sym { value: k } }) =>
                        Stmt::Expr(format!("parseInt64(ctx.Params[\"{}\"])", k.as_str())),
                    _ => Stmt::Expr("ctx.Params /* TODO: params.expect hash */".to_string()),
                }
            }
            SendKind::ModelNew { class } => Stmt::Expr(format!("&{}{{}}", class.as_str())),
            SendKind::ModelFind { class, id } => {
                let id_s = self.render_expr(id);
                Stmt::Expr(format!("{}Find({id_s})", class.as_str()))
            }
            SendKind::QueryChain { target: Some(target), method: cm, args: ca, recv: cr } => {
                let mut out = format!("{}All()", target.as_str());
                let mods = crate::lower::collect_chain_modifiers(cm, ca, cr.as_deref());
                for m in mods {
                    out = apply_go_chain_modifier(out, m, target.as_str());
                }
                Stmt::Expr(out)
            }
            SendKind::QueryChain { target: None, .. } => {
                Stmt::Expr("nil /* TODO: unresolved query chain */".to_string())
            }
            SendKind::AssocLookup { target, outer_method } => match outer_method {
                "find" => {
                    let id_s = args.first().map(|a| self.render_expr(a))
                        .unwrap_or_else(|| "0".to_string());
                    Stmt::Expr(format!("{}Find({id_s})", target.as_str()))
                }
                _ => Stmt::Expr(format!("&{}{{}}", target.as_str())),
            },
            SendKind::BangStrip { recv, stripped_method, args: bs_args } => {
                let recv_s = self.render_expr(recv);
                let args_s: Vec<String> =
                    bs_args.iter().map(|a| self.render_expr(a)).collect();
                Stmt::Expr(format!(
                    "{recv_s}.{}({})",
                    pascalize_word(stripped_method),
                    args_s.join(", "),
                ))
            }
            SendKind::InstanceUpdate => Stmt::Expr("false".to_string()),
            SendKind::PathOrUrlHelper => {
                let helper = method.strip_suffix("_path").or_else(|| method.strip_suffix("_url"))
                    .unwrap_or(method);
                Stmt::Expr(format!("{}Path()", pascalize_word(helper)))
            }
            SendKind::Render { args: r_args } => Stmt::Response(self.render_go_render(r_args)),
            SendKind::RedirectTo { args: r_args } => Stmt::Response(self.render_go_redirect(r_args)),
            SendKind::Head { args: h_args } => {
                let status = h_args.first().and_then(|a| match &*a.node {
                    ExprNode::Lit { value: Literal::Sym { value: s } } =>
                        Some(crate::lower::status_sym_to_code(s.as_str())),
                    ExprNode::Lit { value: Literal::Int { value: n } } => Some(*n as u16),
                    _ => None,
                }).unwrap_or(200);
                Stmt::Response(format!("ActionResponse{{Status: {status}}}"))
            }
            SendKind::RespondToBlock { .. }
            | SendKind::FormatHtml { .. }
            | SendKind::FormatJson => Stmt::Expr(
                "ActionResponse{} /* unreachable: respond_to not normalized */".to_string(),
            ),
        })
    }
}

impl<'a> GoEmitter<'a> {
    fn render_go_render(&mut self, args: &[Expr]) -> String {
        if let Some(first) = args.first() {
            if let ExprNode::Lit { value: Literal::Sym { value: sym } } = &*first.node {
                let view_fn = go_view_fn(self.ctx.model_class, sym.as_str());
                let arg = self.state.last_local.clone().unwrap_or_else(|| "nil".to_string());
                let body_part = format!("Body: {view_fn}({arg})");
                return match crate::lower::extract_status_from_kwargs(&args[1..]) {
                    Some(status) => format!("ActionResponse{{Status: {status}, {body_part}}}"),
                    None => format!("ActionResponse{{{body_part}}}"),
                };
            }
            let body_s = self.render_expr(first);
            return format!("ActionResponse{{Body: {body_s}}}");
        }
        "ActionResponse{}".to_string()
    }

    fn render_go_redirect(&mut self, args: &[Expr]) -> String {
        let Some(first) = args.first() else {
            return "ActionResponse{Status: 303}".to_string();
        };
        let loc = self.render_expr(first);
        let status = crate::lower::extract_status_from_kwargs(&args[1..]).unwrap_or(303);
        if is_bare_go_ident(&loc) {
            let helper = pascalize_word(&loc);
            let id_access = format!("{loc}.ID");
            return format!("ActionResponse{{Status: {status}, Location: {helper}Path({id_access})}}");
        }
        format!("ActionResponse{{Status: {status}, Location: {loc}}}")
    }
}

/// Detect `Class.find(id)` — the walker's Assign arm synthesizes a
/// nil-guard for this shape so subsequent `record.Method()` calls
/// don't panic. Go's lone per-target Assign-level macro.
fn model_find_shape<'a>(value: &'a Expr, known_models: &[Symbol]) -> Option<(Symbol, &'a Expr)> {
    let ExprNode::Send { recv, method, args, .. } = &*value.node else { return None };
    if method.as_str() != "find" || args.len() != 1 {
        return None;
    }
    let r = recv.as_ref()?;
    let ExprNode::Const { path } = &*r.node else { return None };
    let class = path.last()?;
    known_models.iter().find(|m| *m == class)?;
    Some((class.clone(), &args[0]))
}

fn is_bare_go_ident(s: &str) -> bool {
    let bytes = s.as_bytes();
    if bytes.is_empty() { return false; }
    let first = bytes[0];
    if !(first.is_ascii_lowercase() || first == b'_') { return false; }
    bytes.iter().all(|&b| b.is_ascii_alphanumeric() || b == b'_')
}

/// Compose one AR chain modifier onto a running Go slice
/// expression. `all`/`includes`/etc. pass through unchanged.
/// `order({field: :dir})` emits a `sort.Slice` wrapper with an
/// IIFE so the sort runs inline. `limit(N)` slices `[:N]`.
fn apply_go_chain_modifier(
    prev: String,
    m: crate::lower::ChainModifier<'_>,
    target_class: &str,
) -> String {
    match m.method {
        "all" | "includes" | "preload" | "joins" | "distinct" | "select" => prev,
        "order" => {
            let Some(hash) = m.args.first() else { return prev };
            let ExprNode::Hash { entries, .. } = &*hash.node else { return prev };
            let Some((k, v)) = entries.first() else { return prev };
            let field = match &*k.node {
                ExprNode::Lit { value: Literal::Sym { value } } => value.as_str().to_string(),
                ExprNode::Lit { value: Literal::Str { value } } => value.clone(),
                _ => return prev,
            };
            let dir = match &*v.node {
                ExprNode::Lit { value: Literal::Sym { value } } => value.as_str().to_string(),
                ExprNode::Lit { value: Literal::Str { value } } => value.clone(),
                _ => "asc".to_string(),
            };
            let field_go = go_field_name(&field);
            let cmp = if dir == "desc" {
                format!("__s[i].{field_go} > __s[j].{field_go}")
            } else {
                format!("__s[i].{field_go} < __s[j].{field_go}")
            };
            format!(
                "func() []*{target_class} {{ __s := {prev}; sort.Slice(__s, func(i, j int) bool {{ return {cmp} }}); return __s }}()"
            )
        }
        "limit" => {
            let Some(n) = m.args.first() else { return prev };
            if let ExprNode::Lit { value: Literal::Int { value, .. } } = &*n.node {
                return format!(
                    "func() []*{target_class} {{ __s := {prev}; if len(__s) > {value} {{ __s = __s[:{value}] }}; return __s }}()"
                );
            }
            prev
        }
        _ => prev,
    }
}
