//! Fixture emission — `app/fixtures_test.go` keeps fixtures inside
//! the package's test build (not shipped in production). Go's
//! `_test.go` suffix excludes files from `go build`; `go test` picks
//! them up.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use super::shared::go_field_name;
use crate::App;
use crate::ty::Ty;

pub(super) fn emit_go_fixtures(app: &App) -> EmittedFile {
    let lowered = crate::lower::lower_fixtures(app);
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s, "package app").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "// FixtureIDs maps (fixture_name, label) → AUTOINCREMENT id").unwrap();
    writeln!(s, "// assigned when the fixture loaded. Reset by setupTest.").unwrap();
    writeln!(s, "var FixtureIDs = map[[2]string]int64{{}}").unwrap();
    writeln!(s).unwrap();
    writeln!(
        s,
        "// setupTest opens a fresh :memory: SQLite DB, runs the schema DDL,"
    )
    .unwrap();
    writeln!(s, "// and reloads every fixture in declaration order. Each generated").unwrap();
    writeln!(s, "// test calls this at the top of its body.").unwrap();
    writeln!(s, "func setupTest() {{").unwrap();
    writeln!(s, "\tSetupTestDB(CreateTables)").unwrap();
    writeln!(s, "\tFixtureIDs = map[[2]string]int64{{}}").unwrap();
    for f in &lowered.fixtures {
        let mod_ns = crate::naming::camelize(f.name.as_str());
        writeln!(s, "\t{mod_ns}LoadAll()").unwrap();
    }
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "func FixtureID(fixture, label string) int64 {{").unwrap();
    writeln!(s, "\tid, ok := FixtureIDs[[2]string{{fixture, label}}]").unwrap();
    writeln!(s, "\tif !ok {{").unwrap();
    writeln!(
        s,
        "\t\tpanic(\"fixture \" + fixture + \"/\" + label + \" not loaded\")"
    )
    .unwrap();
    writeln!(s, "\t}}").unwrap();
    writeln!(s, "\treturn id").unwrap();
    writeln!(s, "}}").unwrap();

    for fixture in &lowered.fixtures {
        let class_name = fixture.class.0.as_str();
        let ns = crate::naming::camelize(fixture.name.as_str());

        // LoadAll — insert each record via Save (validations +
        // INSERT via the juntos-style runtime) and record the
        // AUTOINCREMENT id in FixtureIDs.
        writeln!(s).unwrap();
        writeln!(s, "func {ns}LoadAll() {{").unwrap();
        for record in &fixture.records {
            let label = record.label.as_str();
            writeln!(s, "\t{{").unwrap();
            writeln!(s, "\t\tr := &{class_name}{{}}").unwrap();
            for field in &record.fields {
                let col = go_field_name(field.column.as_str());
                let val = match &field.value {
                    crate::lower::LoweredFixtureValue::Literal { ty, raw } => {
                        go_literal_for(raw, ty)
                    }
                    crate::lower::LoweredFixtureValue::FkLookup {
                        target_fixture,
                        target_label,
                    } => format!(
                        "FixtureID({:?}, {:?})",
                        target_fixture.as_str(),
                        target_label.as_str(),
                    ),
                };
                writeln!(s, "\t\tr.{col} = {val}").unwrap();
            }
            writeln!(
                s,
                "\t\tif !r.Save() {{ panic(\"fixture {}/{label} failed to save\") }}",
                fixture.name.as_str(),
            )
            .unwrap();
            writeln!(
                s,
                "\t\tFixtureIDs[[2]string{{{:?}, {:?}}}] = r.ID",
                fixture.name.as_str(),
                label,
            )
            .unwrap();
            writeln!(s, "\t}}").unwrap();
        }
        writeln!(s, "}}").unwrap();

        // Named-record getters: look up id + Find.
        for record in &fixture.records {
            let label = record.label.as_str();
            let label_pascal = go_field_name(label);
            writeln!(s).unwrap();
            writeln!(s, "func {ns}{label_pascal}() *{class_name} {{").unwrap();
            writeln!(
                s,
                "\tid := FixtureID({:?}, {:?})",
                fixture.name.as_str(),
                label,
            )
            .unwrap();
            writeln!(s, "\tr := {class_name}Find(id)").unwrap();
            writeln!(
                s,
                "\tif r == nil {{ panic(\"fixture {}/{label} not loaded\") }}",
                fixture.name.as_str(),
            )
            .unwrap();
            writeln!(s, "\treturn r").unwrap();
            writeln!(s, "}}").unwrap();
        }
    }

    EmittedFile {
        path: PathBuf::from("app/fixtures_test.go"),
        content: s,
    }
}

pub(super) fn go_literal_for(value: &str, ty: &Ty) -> String {
    match ty {
        Ty::Str | Ty::Sym => format!("{value:?}"),
        Ty::Int => {
            if value.parse::<i64>().is_ok() {
                value.to_string()
            } else {
                format!("0 /* TODO: coerce {value:?} */")
            }
        }
        Ty::Float => {
            if value.parse::<f64>().is_ok() {
                value.to_string()
            } else {
                format!("0.0 /* TODO: coerce {value:?} */")
            }
        }
        Ty::Bool => match value {
            "true" | "1" => "true".into(),
            "false" | "0" => "false".into(),
            _ => format!("false /* TODO: coerce {value:?} */"),
        },
        Ty::Class { id, .. } if id.0.as_str() == "Time" => format!("{value:?}"),
        _ => format!("{value:?}"),
    }
}
