//! `app/importmap.go` emission — flat `Pins` slice ingested from
//! `config/importmap.rb`.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use crate::App;

/// `app/importmap.go` — a flat `Pins` slice of `[name, path]`
/// tuples ingested from `config/importmap.rb`. Feeds
/// `JavascriptImportmapTags` in the emitted layout. Mirrors
/// `emit_rust_importmap` / the TS+Python twins.
pub(super) fn emit_go_importmap(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s, "package app").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "var Pins = [][2]string{{").unwrap();
    if let Some(importmap) = &app.importmap {
        for pin in &importmap.pins {
            writeln!(s, "\t{{{:?}, {:?}}},", pin.name, pin.path).unwrap();
        }
    }
    writeln!(s, "}}").unwrap();
    EmittedFile {
        path: PathBuf::from("app/importmap.go"),
        content: s,
    }
}
