//! `main.go` emission — the `go run .` entry point.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use super::shared::pascalize_word;
use crate::App;

/// `main.go` — the `go run .` entry point. Opens the DB via
/// `app.Start(StartOptions{...})`, passing the emitted layout
/// renderer when one exists.
pub(super) fn emit_go_main(app: &App) -> EmittedFile {
    let has_layout = app
        .views
        .iter()
        .any(|v| v.name.as_str() == "layouts/application");
    let layout_field = if has_layout {
        "\t\tLayout:    func() string { return app.RenderLayoutsApplication(nil) },\n"
    } else {
        ""
    };
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s, "package main").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "import (").unwrap();
    writeln!(s, "\t\"app/app\"").unwrap();
    writeln!(s, ")").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "func main() {{").unwrap();
    // Register partial renderers for any model whose plural
    // resource has a scaffold partial (`_<singular>.html.erb`).
    // Cable's broadcast_*_to resolves the partial by model class
    // name through this registry. Only register partials whose
    // singular matches a known model class — `_form.html.erb` is
    // a view-only partial, not a model.
    let known_model_names: std::collections::BTreeSet<String> = app
        .models
        .iter()
        .map(|m| m.name.0.as_str().to_string())
        .collect();
    let mut registered: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
    for v in &app.views {
        let name = v.name.as_str();
        if let Some((dir, base)) = name.rsplit_once('/') {
            if let Some(singular) = base.strip_prefix('_') {
                let class = crate::naming::camelize(singular);
                if !known_model_names.contains(&class) {
                    continue;
                }
                if registered.insert(class.clone()) {
                    let fn_name = format!(
                        "Render{}{}",
                        pascalize_word(dir),
                        pascalize_word(singular),
                    );
                    writeln!(
                        s,
                        "\tapp.RegisterPartial({class:?}, func(id int64) string {{",
                    )
                    .unwrap();
                    writeln!(s, "\t\tr := app.{class}Find(id)").unwrap();
                    writeln!(s, "\t\tif r == nil {{ return \"\" }}").unwrap();
                    writeln!(s, "\t\treturn app.{fn_name}(r)").unwrap();
                    writeln!(s, "\t}})").unwrap();
                }
            }
        }
    }
    writeln!(s, "\tapp.Start(app.StartOptions{{").unwrap();
    writeln!(s, "\t\tSchemaSQL: app.CreateTables,").unwrap();
    if !layout_field.is_empty() {
        s.push_str(layout_field);
    }
    writeln!(s, "\t}})").unwrap();
    writeln!(s, "}}").unwrap();
    EmittedFile {
        path: PathBuf::from("main.go"),
        content: s,
    }
}
