//! Model emission — `app/models.go` with structs, methods,
//! validations, persistence, and broadcaster glue.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use super::expr::emit_expr;
use super::shared::{go_field_name, go_method_name, pascalize_word};
use super::ty::go_ty;
use crate::App;
use crate::dialect::{MethodDef, Model};
use crate::expr::{Expr, ExprNode, LValue, Literal};
use crate::ident::Symbol;
use crate::ty::Ty;

pub(super) fn emit_models(app: &App) -> EmittedFile {
    let mut body = String::new();
    for model in &app.models {
        writeln!(body).unwrap();
        emit_struct(&mut body, model);
        for method in model.methods() {
            writeln!(body).unwrap();
            emit_model_method(&mut body, model, method);
        }
        let lowered = crate::lower::lower_validations(model);
        if !lowered.is_empty() {
            writeln!(body).unwrap();
            emit_validate_method_go(&mut body, model, &lowered);
        }
        // Persistence emitted for any model with table columns beyond
        // `id`. Abstract base classes (ApplicationRecord) get skipped.
        let has_table = model
            .attributes
            .fields
            .keys()
            .any(|k| k.as_str() != "id");
        if has_table {
            writeln!(body).unwrap();
            let broadcasts = crate::lower::lower_broadcasts(model);
            emit_persistence_methods_go(
                &mut body,
                model,
                !lowered.is_empty(),
                app,
                !broadcasts.is_empty(),
            );
            if !broadcasts.is_empty() {
                let lp = crate::lower::lower_persistence(model, app);
                emit_go_broadcaster_methods(
                    &mut body,
                    lp.class.0.as_str(),
                    lp.table.as_str(),
                    receiver_letter(model).as_str(),
                    &broadcasts,
                );
            }
        }
    }
    // Conditional imports: scan the emitted body for package prefixes
    // that indicate which stdlib we need. Go errors on unused imports,
    // so we only emit what's actually referenced.
    let mut imports: Vec<&str> = Vec::new();
    if body.contains("fmt.") {
        imports.push("fmt");
    }
    if body.contains("strings.") {
        imports.push("strings");
    }

    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s, "package app").unwrap();
    if !imports.is_empty() {
        writeln!(s).unwrap();
        if imports.len() == 1 {
            writeln!(s, "import \"{}\"", imports[0]).unwrap();
        } else {
            writeln!(s, "import (").unwrap();
            for imp in &imports {
                writeln!(s, "\t\"{imp}\"").unwrap();
            }
            writeln!(s, ")").unwrap();
        }
    }
    s.push_str(&body);
    EmittedFile { path: PathBuf::from("app/models.go"), content: s }
}

fn emit_struct(out: &mut String, model: &Model) {
    writeln!(out, "type {} struct {{", model.name.0).unwrap();
    for (name, ty) in &model.attributes.fields {
        writeln!(out, "\t{} {}", go_field_name(name.as_str()), go_ty(ty)).unwrap();
    }
    // Validation-error state — views read `article.errors.any?` to
    // drive conditional input styling; `error_messages_for` reads
    // the slice. Rust/python emit the same field.
    if !model.attributes.fields.is_empty() {
        writeln!(out, "\tErrors []ValidationError").unwrap();
    }
    writeln!(out, "}}").unwrap();
}

fn emit_model_method(out: &mut String, model: &Model, m: &MethodDef) {
    let ret_ty = m.body.ty.clone().unwrap_or(Ty::Nil);
    let method_name = go_method_name(m.name.as_str());
    let ret_annot = match &ret_ty {
        Ty::Nil => String::new(),
        other => format!(" {}", go_ty(other)),
    };
    let (receiver, receiver_var) = match m.receiver {
        crate::dialect::MethodReceiver::Instance => {
            // Single-letter receiver name — Go idiom (`p *Post`).
            let first = model
                .name
                .0
                .as_str()
                .chars()
                .next()
                .unwrap_or('r')
                .to_ascii_lowercase();
            (format!("({first} *{})", model.name.0), first.to_string())
        }
        crate::dialect::MethodReceiver::Class => {
            // Class method: emit as package-level function (pseudo-Go, since
            // Go has no class methods).
            (String::new(), String::new())
        }
    };
    let space_before_name = if receiver.is_empty() { "" } else { " " };
    writeln!(
        out,
        "func {}{}{}(){} {{",
        receiver, space_before_name, method_name, ret_annot,
    )
    .unwrap();
    // Pre-emit rewrite: bare `title` inside a method body → `p.Title`
    // (receiver-var + PascalCased field). Same pattern as the other
    // typed emitters; Go makes it the receiver variable rather than
    // `self`/`this`.
    let attrs: Vec<Symbol> = model.attributes.fields.keys().cloned().collect();
    let rewritten = if !receiver_var.is_empty() {
        rewrite_bare_attrs_to_receiver(&m.body, &attrs, &receiver_var)
    } else {
        m.body.clone()
    };
    let body_s = if matches!(ret_ty, Ty::Nil) {
        emit_expr(&rewritten)
    } else {
        format!("return {}", emit_expr(&rewritten))
    };
    for line in body_s.lines() {
        writeln!(out, "\t{}", line).unwrap();
    }
    writeln!(out, "}}").unwrap();
}

/// Pre-emit rewrite for model method bodies: turn any bare-name Send
/// whose method matches a model attribute into a receiver-prefixed
/// Send. Ruby's implicit self becomes Go's explicit receiver variable
/// (`p` on `Post`, `c` on `Comment`, etc.). Emit then renders the
/// outer Send as `p.Title` — modulo go_method_name PascalCasing the
/// field, matching the struct definition.
fn rewrite_bare_attrs_to_receiver(
    e: &Expr,
    attrs: &[Symbol],
    receiver_var: &str,
) -> Expr {
    use crate::expr::{Arm, InterpPart, Pattern};
    use crate::ident::VarId;
    let rewrite = |child: &Expr| rewrite_bare_attrs_to_receiver(child, attrs, receiver_var);
    let receiver_ref = |span: crate::span::Span| Expr {
        span,
        node: Box::new(ExprNode::Var {
            id: VarId(0),
            name: Symbol::from(receiver_var),
        }),
        ty: None,
        effects: crate::effect::EffectSet::pure(),
        leading_blank_line: false,
    };
    let new_node = match &*e.node {
        ExprNode::Send { recv: None, method, args, block: None, parenthesized }
            if args.is_empty() && attrs.iter().any(|s| s == method) =>
        {
            ExprNode::Send {
                recv: Some(receiver_ref(e.span)),
                method: method.clone(),
                args: vec![],
                block: None,
                parenthesized: *parenthesized,
            }
        }
        ExprNode::Send { recv, method, args, block, parenthesized } => ExprNode::Send {
            recv: recv.as_ref().map(&rewrite),
            method: method.clone(),
            args: args.iter().map(&rewrite).collect(),
            block: block.as_ref().map(&rewrite),
            parenthesized: *parenthesized,
        },
        ExprNode::Seq { exprs } => ExprNode::Seq {
            exprs: exprs.iter().map(&rewrite).collect(),
        },
        ExprNode::Array { elements, style } => ExprNode::Array {
            elements: elements.iter().map(&rewrite).collect(),
            style: *style,
        },
        ExprNode::Hash { entries, braced } => ExprNode::Hash {
            entries: entries.iter().map(|(k, v)| (rewrite(k), rewrite(v))).collect(),
            braced: *braced,
        },
        ExprNode::If { cond, then_branch, else_branch } => ExprNode::If {
            cond: rewrite(cond),
            then_branch: rewrite(then_branch),
            else_branch: rewrite(else_branch),
        },
        ExprNode::Case { scrutinee, arms } => ExprNode::Case {
            scrutinee: rewrite(scrutinee),
            arms: arms
                .iter()
                .map(|arm| Arm {
                    pattern: arm.pattern.clone(),
                    guard: arm.guard.as_ref().map(&rewrite),
                    body: rewrite(&arm.body),
                })
                .collect(),
        },
        ExprNode::BoolOp { op, surface, left, right } => ExprNode::BoolOp {
            op: *op,
            surface: *surface,
            left: rewrite(left),
            right: rewrite(right),
        },
        ExprNode::StringInterp { parts } => ExprNode::StringInterp {
            parts: parts
                .iter()
                .map(|p| match p {
                    InterpPart::Text { value } => InterpPart::Text { value: value.clone() },
                    InterpPart::Expr { expr } => InterpPart::Expr { expr: rewrite(expr) },
                })
                .collect(),
        },
        ExprNode::Let { id, name, value, body } => ExprNode::Let {
            id: *id,
            name: name.clone(),
            value: rewrite(value),
            body: rewrite(body),
        },
        ExprNode::Lambda { params, block_param, body, block_style } => ExprNode::Lambda {
            params: params.clone(),
            block_param: block_param.clone(),
            body: rewrite(body),
            block_style: *block_style,
        },
        ExprNode::Apply { fun, args, block } => ExprNode::Apply {
            fun: rewrite(fun),
            args: args.iter().map(&rewrite).collect(),
            block: block.as_ref().map(&rewrite),
        },
        ExprNode::Assign { target, value } => {
            let new_target = match target {
                LValue::Var { id, name } => LValue::Var { id: *id, name: name.clone() },
                LValue::Ivar { name } => LValue::Ivar { name: name.clone() },
                LValue::Attr { recv, name } => LValue::Attr {
                    recv: rewrite(recv),
                    name: name.clone(),
                },
                LValue::Index { recv, index } => LValue::Index {
                    recv: rewrite(recv),
                    index: rewrite(index),
                },
            };
            ExprNode::Assign {
                target: new_target,
                value: rewrite(value),
            }
        }
        ExprNode::Yield { args } => ExprNode::Yield {
            args: args.iter().map(&rewrite).collect(),
        },
        ExprNode::Raise { value } => ExprNode::Raise { value: rewrite(value) },
        ExprNode::RescueModifier { expr, fallback } => ExprNode::RescueModifier {
            expr: rewrite(expr),
            fallback: rewrite(fallback),
        },
        // Leaves.
        ExprNode::Lit { .. }
        | ExprNode::Var { .. }
        | ExprNode::Ivar { .. }
        | ExprNode::Const { .. } => (*e.node).clone(),
    };
    let _ = Pattern::Wildcard;
    Expr {
        span: e.span,
        node: Box::new(new_node),
        ty: e.ty.clone(),
        effects: e.effects.clone(),
        leading_blank_line: e.leading_blank_line,
    }
}

// Validations ----------------------------------------------------------

fn emit_validate_method_go(
    out: &mut String,
    model: &Model,
    validations: &[crate::lower::LoweredValidation],
) {
    let recv_var = receiver_letter(model);
    writeln!(
        out,
        "func ({recv_var} *{}) Validate() []ValidationError {{",
        model.name.0
    )
    .unwrap();
    writeln!(out, "\tvar errors []ValidationError").unwrap();
    for lv in validations {
        for check in &lv.checks {
            emit_check_inline_go(out, &recv_var, lv.attribute.as_str(), check);
        }
    }
    writeln!(out, "\treturn errors").unwrap();
    writeln!(out, "}}").unwrap();
}

fn emit_check_inline_go(
    out: &mut String,
    recv: &str,
    attr: &str,
    check: &crate::lower::Check,
) {
    use crate::lower::Check;
    let field = go_field_name(attr);
    let msg = check.default_message();
    let push = |cond: &str| -> String {
        format!(
            "\tif {cond} {{\n\t\terrors = append(errors, NewValidationError({attr:?}, {msg:?}))\n\t}}"
        )
    };
    let block = match check {
        Check::Presence => push(&format!("{recv}.{field} == \"\"")),
        Check::Absence => push(&format!("{recv}.{field} != \"\"")),
        Check::MinLength { n } => push(&format!("len({recv}.{field}) < {n}")),
        Check::MaxLength { n } => push(&format!("len({recv}.{field}) > {n}")),
        Check::GreaterThan { threshold } => push(&format!("{recv}.{field} <= {threshold}")),
        Check::LessThan { threshold } => push(&format!("{recv}.{field} >= {threshold}")),
        Check::OnlyInteger => {
            format!("\t// OnlyInteger on {attr:?} — enforced by Go's type system")
        }
        Check::Inclusion { values } => {
            let parts: Vec<String> =
                values.iter().map(inclusion_value_to_go).collect();
            // Emit an inline membership check via a switch-style OR.
            let cond = parts
                .iter()
                .map(|p| format!("{recv}.{field} != {p}"))
                .collect::<Vec<_>>()
                .join(" && ");
            push(&cond)
        }
        Check::Format { pattern } => {
            format!("\t// TODO: Format check on {attr:?} requires runtime regex ({pattern:?})")
        }
        Check::Uniqueness { .. } => {
            format!("\t// TODO: Uniqueness on {attr:?} requires DB access at runtime")
        }
        Check::Custom { method } => {
            format!("\t{recv}.{}(errors)", go_field_name(method.as_str()))
        }
    };
    writeln!(out, "{block}").unwrap();
}

fn inclusion_value_to_go(v: &crate::lower::InclusionValue) -> String {
    use crate::lower::InclusionValue;
    match v {
        InclusionValue::Str { value } => format!("{value:?}"),
        InclusionValue::Int { value } => value.to_string(),
        InclusionValue::Float { value } => {
            let s = value.to_string();
            if s.contains('.') { s } else { format!("{s}.0") }
        }
        InclusionValue::Bool { value } => value.to_string(),
    }
}

// Persistence ----------------------------------------------------------

/// Render Save/Destroy/Count/Find for a model against the test DB.
/// SQL strings come from LoweredPersistence; the per-target surface
/// is database/sql API shape, the `?N → ?` placeholder rewrite, and
/// class-method-as-package-function naming (`Article.count` →
/// `ArticleCount()`).
fn emit_persistence_methods_go(
    out: &mut String,
    model: &Model,
    has_validate: bool,
    app: &App,
    has_broadcasts: bool,
) {
    let lp = crate::lower::lower_persistence(model, app);
    let class = lp.class.0.as_str();
    let recv = receiver_letter(model);

    let insert_sql = positional_placeholders_go(&lp.insert_sql);
    let update_sql = positional_placeholders_go(&lp.update_sql);
    let delete_sql = positional_placeholders_go(&lp.delete_sql);
    let select_by_id_sql = positional_placeholders_go(&lp.select_by_id_sql);

    let non_id_args: Vec<String> = lp
        .non_id_columns
        .iter()
        .map(|s| format!("{recv}.{}", go_field_name(s.as_str())))
        .collect();

    // ----- Save -----
    writeln!(out, "func ({recv} *{class}) Save() bool {{").unwrap();
    if has_validate {
        writeln!(
            out,
            "\tif errs := {recv}.Validate(); len(errs) > 0 {{ {recv}.Errors = errs; return false }}"
        )
        .unwrap();
        writeln!(out, "\t{recv}.Errors = nil").unwrap();
    }
    // belongs_to existence: FK must be non-zero and refer to an
    // existing row in the target table.
    for check in &lp.belongs_to_checks {
        let fk_field = go_field_name(check.foreign_key.as_str());
        let target = check.target_class.0.as_str();
        writeln!(
            out,
            "\tif {recv}.{fk_field} == 0 || {target}Find({recv}.{fk_field}) == nil {{ return false }}",
        )
        .unwrap();
    }
    writeln!(out, "\tdb := Conn()").unwrap();
    writeln!(out, "\tif {recv}.ID == 0 {{").unwrap();
    writeln!(
        out,
        "\t\tres, err := db.Exec({insert_sql:?}, {})",
        non_id_args.join(", "),
    )
    .unwrap();
    writeln!(out, "\t\tif err != nil {{ panic(err) }}").unwrap();
    writeln!(out, "\t\tid, _ := res.LastInsertId()").unwrap();
    writeln!(out, "\t\t{recv}.ID = id").unwrap();
    writeln!(out, "\t}} else {{").unwrap();
    writeln!(
        out,
        "\t\t_, err := db.Exec({update_sql:?}, {}, {recv}.ID)",
        non_id_args.join(", "),
    )
    .unwrap();
    writeln!(out, "\t\tif err != nil {{ panic(err) }}").unwrap();
    writeln!(out, "\t}}").unwrap();
    if has_broadcasts {
        writeln!(out, "\t{recv}.broadcastAfterSave()").unwrap();
    }
    writeln!(out, "\treturn true").unwrap();
    writeln!(out, "}}").unwrap();

    // ----- Destroy -----
    writeln!(out).unwrap();
    writeln!(out, "func ({recv} *{class}) Destroy() {{").unwrap();
    for dc in &lp.dependent_children {
        let child_class = dc.child_class.0.as_str();
        let child_select = positional_placeholders_go(&dc.select_by_parent_sql);
        writeln!(out, "\t{{").unwrap();
        writeln!(
            out,
            "\t\trows, err := Conn().Query({child_select:?}, {recv}.ID)",
        )
        .unwrap();
        writeln!(out, "\t\tif err != nil {{ panic(err) }}").unwrap();
        writeln!(out, "\t\tvar children []{child_class}").unwrap();
        writeln!(out, "\t\tfor rows.Next() {{").unwrap();
        writeln!(out, "\t\t\tvar c {child_class}").unwrap();
        let scans: Vec<String> = dc
            .child_columns
            .iter()
            .map(|s| format!("&c.{}", go_field_name(s.as_str())))
            .collect();
        writeln!(out, "\t\t\tif err := rows.Scan({}); err != nil {{ panic(err) }}", scans.join(", ")).unwrap();
        writeln!(out, "\t\t\tchildren = append(children, c)").unwrap();
        writeln!(out, "\t\t}}").unwrap();
        writeln!(out, "\t\trows.Close()").unwrap();
        writeln!(out, "\t\tfor i := range children {{").unwrap();
        writeln!(out, "\t\t\tchildren[i].Destroy()").unwrap();
        writeln!(out, "\t\t}}").unwrap();
        writeln!(out, "\t}}").unwrap();
    }
    writeln!(
        out,
        "\tif _, err := Conn().Exec({delete_sql:?}, {recv}.ID); err != nil {{ panic(err) }}",
    )
    .unwrap();
    if has_broadcasts {
        writeln!(out, "\t{recv}.broadcastAfterDelete()").unwrap();
    }
    writeln!(out, "}}").unwrap();

    // ----- Count (package-level function, since Go has no class methods) -----
    writeln!(out).unwrap();
    writeln!(out, "func {class}Count() int64 {{").unwrap();
    writeln!(out, "\tvar n int64").unwrap();
    writeln!(
        out,
        "\tif err := Conn().QueryRow({:?}).Scan(&n); err != nil {{ panic(err) }}",
        lp.count_sql,
    )
    .unwrap();
    writeln!(out, "\treturn n").unwrap();
    writeln!(out, "}}").unwrap();

    // ----- Find (package-level function) -----
    writeln!(out).unwrap();
    writeln!(out, "func {class}Find(id int64) *{class} {{").unwrap();
    writeln!(
        out,
        "\trow := Conn().QueryRow({select_by_id_sql:?}, id)",
    )
    .unwrap();
    writeln!(out, "\tvar r {class}").unwrap();
    let scans: Vec<String> = lp
        .columns
        .iter()
        .map(|s| format!("&r.{}", go_field_name(s.as_str())))
        .collect();
    writeln!(
        out,
        "\tif err := row.Scan({}); err != nil {{ return nil }}",
        scans.join(", ")
    )
    .unwrap();
    writeln!(out, "\treturn &r").unwrap();
    writeln!(out, "}}").unwrap();

    // ----- All (package-level function) -----
    let select_all_sql = positional_placeholders_go(&lp.select_all_sql);
    writeln!(out).unwrap();
    writeln!(out, "func {class}All() []*{class} {{").unwrap();
    writeln!(out, "\trows, err := Conn().Query({select_all_sql:?})").unwrap();
    writeln!(out, "\tif err != nil {{ panic(err) }}").unwrap();
    writeln!(out, "\tdefer rows.Close()").unwrap();
    writeln!(out, "\tvar out []*{class}").unwrap();
    writeln!(out, "\tfor rows.Next() {{").unwrap();
    writeln!(out, "\t\tvar r {class}").unwrap();
    writeln!(
        out,
        "\t\tif err := rows.Scan({}); err != nil {{ panic(err) }}",
        scans.join(", ")
    )
    .unwrap();
    writeln!(out, "\t\tout = append(out, &r)").unwrap();
    writeln!(out, "\t}}").unwrap();
    writeln!(out, "\treturn out").unwrap();
    writeln!(out, "}}").unwrap();

    // ----- Last (package-level function) -----
    let select_last_sql = positional_placeholders_go(&lp.select_last_sql);
    writeln!(out).unwrap();
    writeln!(out, "func {class}Last() *{class} {{").unwrap();
    writeln!(
        out,
        "\trow := Conn().QueryRow({select_last_sql:?})",
    )
    .unwrap();
    writeln!(out, "\tvar r {class}").unwrap();
    writeln!(
        out,
        "\tif err := row.Scan({}); err != nil {{ return nil }}",
        scans.join(", ")
    )
    .unwrap();
    writeln!(out, "\treturn &r").unwrap();
    writeln!(out, "}}").unwrap();

    // ----- Reload (instance method) -----
    writeln!(out).unwrap();
    writeln!(out, "func ({recv} *{class}) Reload() {{").unwrap();
    writeln!(out, "\tfresh := {class}Find({recv}.ID)").unwrap();
    writeln!(out, "\tif fresh == nil {{ return }}").unwrap();
    writeln!(out, "\t*{recv} = *fresh").unwrap();
    writeln!(out, "}}").unwrap();

    // ----- has_many accessors (package-level functions: Model.assoc → ModelAssoc(parent)) -----
    for dc in &lp.dependent_children {
        let child_class = dc.child_class.0.as_str();
        let assoc_plural = crate::naming::pluralize_snake(child_class);
        let assoc_pascal = pascalize_word(&assoc_plural);
        let child_select = positional_placeholders_go(&dc.select_by_parent_sql);
        writeln!(out).unwrap();
        writeln!(
            out,
            "func ({recv} *{class}) {assoc_pascal}() []*{child_class} {{"
        )
        .unwrap();
        writeln!(
            out,
            "\trows, err := Conn().Query({child_select:?}, {recv}.ID)"
        )
        .unwrap();
        writeln!(out, "\tif err != nil {{ panic(err) }}").unwrap();
        writeln!(out, "\tdefer rows.Close()").unwrap();
        writeln!(out, "\tvar out []*{child_class}").unwrap();
        writeln!(out, "\tfor rows.Next() {{").unwrap();
        writeln!(out, "\t\tvar c {child_class}").unwrap();
        let cscans: Vec<String> = dc
            .child_columns
            .iter()
            .map(|s| format!("&c.{}", go_field_name(s.as_str())))
            .collect();
        writeln!(
            out,
            "\t\tif err := rows.Scan({}); err != nil {{ panic(err) }}",
            cscans.join(", ")
        )
        .unwrap();
        writeln!(out, "\t\tout = append(out, &c)").unwrap();
        writeln!(out, "\t}}").unwrap();
        writeln!(out, "\treturn out").unwrap();
        writeln!(out, "}}").unwrap();
    }
}

/// SQLite `?N` → database/sql `?`. `database/sql` doesn't support
/// numbered placeholders in the same positional style; drop the
/// trailing digits.
fn positional_placeholders_go(sql: &str) -> String {
    let mut out = String::new();
    let chars: Vec<char> = sql.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        if chars[i] == '?' {
            out.push('?');
            i += 1;
            while i < chars.len() && chars[i].is_ascii_digit() {
                i += 1;
            }
        } else {
            out.push(chars[i]);
            i += 1;
        }
    }
    out
}

fn receiver_letter(model: &Model) -> String {
    model
        .name
        .0
        .as_str()
        .chars()
        .next()
        .unwrap_or('r')
        .to_ascii_lowercase()
        .to_string()
}

// Broadcaster emission ─────────────────────────────────────────────────

fn emit_go_broadcaster_methods(
    out: &mut String,
    class: &str,
    table: &str,
    recv: &str,
    decls: &crate::lower::LoweredBroadcasts,
) {
    writeln!(out).unwrap();
    writeln!(out, "func ({recv} *{class}) broadcastAfterSave() {{").unwrap();
    if decls.save.is_empty() {
        writeln!(out, "\t_ = {recv}").unwrap();
    } else {
        for b in &decls.save {
            emit_go_one_broadcast_call(out, class, table, recv, b);
        }
    }
    writeln!(out, "}}").unwrap();

    writeln!(out).unwrap();
    writeln!(out, "func ({recv} *{class}) broadcastAfterDelete() {{").unwrap();
    if decls.destroy.is_empty() {
        writeln!(out, "\t_ = {recv}").unwrap();
    } else {
        for b in &decls.destroy {
            emit_go_one_broadcast_call(out, class, table, recv, b);
        }
    }
    writeln!(out, "}}").unwrap();
}

fn emit_go_one_broadcast_call(
    out: &mut String,
    class: &str,
    table: &str,
    recv: &str,
    b: &crate::lower::LoweredBroadcast,
) {
    let channel = go_render_broadcast_expr(&b.channel, b.self_param.as_ref(), recv);
    let target = b
        .target
        .as_ref()
        .map(|t| go_render_broadcast_expr(t, b.self_param.as_ref(), recv))
        .unwrap_or_else(|| "\"\"".to_string());
    if let Some(assoc) = &b.on_association {
        let var = assoc.name.as_str();
        let target_class = assoc.target_class.as_str();
        let target_table = assoc.target_table.as_str();
        let fk_field = go_field_name(assoc.foreign_key.as_str());
        writeln!(out, "\t{var} := {target_class}Find({recv}.{fk_field})").unwrap();
        writeln!(out, "\tif {var} != nil {{").unwrap();
        if b.action == crate::lower::BroadcastAction::Remove {
            writeln!(
                out,
                "\t\tBroadcastRemoveTo({target_table:?}, {var}.ID, {channel}, {target})",
            )
            .unwrap();
        } else {
            let func = go_action_fn(b.action);
            writeln!(
                out,
                "\t\t{func}({target_table:?}, {var}.ID, {target_class:?}, {channel}, {target})",
            )
            .unwrap();
        }
        writeln!(out, "\t}}").unwrap();
        return;
    }
    if b.action == crate::lower::BroadcastAction::Remove {
        writeln!(
            out,
            "\tBroadcastRemoveTo({table:?}, {recv}.ID, {channel}, {target})",
        )
        .unwrap();
    } else {
        let func = go_action_fn(b.action);
        writeln!(
            out,
            "\t{func}({table:?}, {recv}.ID, {class:?}, {channel}, {target})",
        )
        .unwrap();
    }
}

fn go_action_fn(action: crate::lower::BroadcastAction) -> &'static str {
    match action {
        crate::lower::BroadcastAction::Prepend => "BroadcastPrependTo",
        crate::lower::BroadcastAction::Append => "BroadcastAppendTo",
        crate::lower::BroadcastAction::Replace => "BroadcastReplaceTo",
        crate::lower::BroadcastAction::Remove => "BroadcastRemoveTo",
    }
}

/// Render a broadcast channel/target expression as a Go
/// expression. Literals → quoted string/int; bare references to the
/// broadcasts_to param → `{recv}`; `param.field` reads →
/// `{recv}.{GoField}`; interpolated strings → `fmt.Sprintf`. Any
/// shape we haven't taught the emitter falls through to `""` so the
/// resulting call is still syntactically valid.
fn go_render_broadcast_expr(
    expr: &Expr,
    self_param: Option<&Symbol>,
    recv: &str,
) -> String {
    let p = self_param.map(|s| s.as_str());
    match &*expr.node {
        ExprNode::Lit { value: Literal::Str { value } } => format!("{value:?}"),
        ExprNode::Lit { value: Literal::Int { value } } => format!("{value}"),
        ExprNode::Var { name, .. } => {
            if let Some(pname) = p {
                let stripped = pname.strip_prefix('_').unwrap_or(pname);
                if name.as_str() == pname || name.as_str() == stripped {
                    return recv.to_string();
                }
            }
            name.as_str().to_string()
        }
        ExprNode::Send { recv: Some(r), method, .. } => {
            let recv_s = go_render_broadcast_expr(r, self_param, recv);
            format!("{recv_s}.{}", go_field_name(method.as_str()))
        }
        ExprNode::StringInterp { parts } => {
            use crate::expr::InterpPart;
            let mut fmt = String::from("\"");
            let mut args: Vec<String> = Vec::new();
            for part in parts {
                match part {
                    InterpPart::Text { value } => {
                        for c in value.chars() {
                            match c {
                                '"' => fmt.push_str("\\\""),
                                '\\' => fmt.push_str("\\\\"),
                                '\n' => fmt.push_str("\\n"),
                                '%' => fmt.push_str("%%"),
                                _ => fmt.push(c),
                            }
                        }
                    }
                    InterpPart::Expr { expr } => {
                        fmt.push_str("%v");
                        args.push(go_render_broadcast_expr(expr, self_param, recv));
                    }
                }
            }
            fmt.push('"');
            if args.is_empty() {
                fmt
            } else {
                format!("fmt.Sprintf({fmt}, {})", args.join(", "))
            }
        }
        _ => "\"\"".to_string(),
    }
}
