//! Pass-2 route emission — `app/routes.go` (Router.Add registrations)
//! and `app/route_helpers.go` (`<name>Path` functions).

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use super::shared::{go_action_handler_name, go_field_name, go_param_name};
use crate::App;

pub(super) fn emit_go_route_helpers(app: &App) -> EmittedFile {
    let flat = crate::lower::flatten_routes(app);
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s, "package app").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "import \"strconv\"").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "var _ = strconv.Itoa").unwrap();

    use std::collections::BTreeSet;
    let mut seen: BTreeSet<String> = BTreeSet::new();
    for route in &flat {
        if !seen.insert(route.as_name.clone()) {
            continue;
        }
        let fn_name = format!("{}Path", go_field_name(&route.as_name));
        let params: Vec<String> = route
            .path_params
            .iter()
            .map(|p| format!("{} int64", go_param_name(p)))
            .collect();
        let sig = params.join(", ");
        let body = if route.path_params.is_empty() {
            format!("\treturn {:?}", route.path)
        } else {
            // Build path with strconv.FormatInt.
            let mut chars = route.path.chars().peekable();
            let mut parts: Vec<String> = Vec::new();
            let mut current = String::new();
            while let Some(c) = chars.next() {
                if c == ':' {
                    let mut ident = String::new();
                    while let Some(&nc) = chars.peek() {
                        if nc.is_alphanumeric() || nc == '_' {
                            ident.push(nc);
                            chars.next();
                        } else {
                            break;
                        }
                    }
                    if !current.is_empty() {
                        parts.push(format!("{current:?}"));
                        current.clear();
                    }
                    let go_param = go_param_name(&ident);
                    parts.push(format!("strconv.FormatInt({go_param}, 10)"));
                } else {
                    current.push(c);
                }
            }
            if !current.is_empty() {
                parts.push(format!("{current:?}"));
            }
            format!("\treturn {}", parts.join(" + "))
        };
        writeln!(s).unwrap();
        writeln!(s, "func {fn_name}({sig}) string {{").unwrap();
        for line in body.lines() {
            writeln!(s, "{line}").unwrap();
        }
        writeln!(s, "}}").unwrap();
    }
    EmittedFile {
        path: PathBuf::from("app/route_helpers.go"),
        content: s,
    }
}

pub(super) fn emit_go_routes(app: &App) -> EmittedFile {
    let flat = crate::lower::flatten_routes(app);
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s, "package app").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "func init() {{").unwrap();
    writeln!(s, "\tRouter.Reset()").unwrap();
    for route in &flat {
        let verb = go_http_verb(&route.method);
        let handler = go_action_handler_name(route.controller.0.as_str(), route.action.as_str());
        writeln!(s, "\tRouter.{verb}({:?}, {})", route.path, handler).unwrap();
    }
    writeln!(s, "}}").unwrap();
    EmittedFile {
        path: PathBuf::from("app/routes.go"),
        content: s,
    }
}

/// Map `dialect::HttpMethod` to the Go router's Title-cased verb
/// name (`Get` / `Post` / etc.). Unknown methods fall back to `Get`
/// — the emitted code is for pass-2 tests, not production routing.
fn go_http_verb(m: &crate::dialect::HttpMethod) -> &'static str {
    use crate::dialect::HttpMethod;
    match m {
        HttpMethod::Get => "Get",
        HttpMethod::Post => "Post",
        HttpMethod::Put => "Put",
        HttpMethod::Patch => "Patch",
        HttpMethod::Delete => "Delete",
        _ => "Get",
    }
}
