//! `app/schema_sql.go` emission — Go constant wrapping the
//! target-neutral DDL produced by `lower::lower_schema`.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use crate::App;

/// `app/schema_sql.go` — Go constant wrapping the target-neutral DDL
/// produced by `lower::lower_schema`. `SetupTestDB` splits it on
/// `;\n` and execs each statement against a fresh :memory: database.
pub(super) fn emit_schema_sql_go(app: &App) -> EmittedFile {
    let ddl = crate::lower::lower_schema(&app.schema);
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s, "package app").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "const CreateTables = `").unwrap();
    s.push_str(&ddl);
    writeln!(s, "`").unwrap();
    EmittedFile {
        path: PathBuf::from("app/schema_sql.go"),
        content: s,
    }
}
