//! Test/spec emission. Routes regular tests through the in-process
//! Go test path; controller tests delegate to the
//! [`controller_test`](super::controller_test) module via the shared
//! `GoTestCtx`.

use std::fmt::Write;
use std::path::PathBuf;

use crate::App;
use crate::dialect::{Test, TestModule};
use crate::expr::{Expr, ExprNode, LValue, Literal};
use crate::naming::snake_case;

use super::super::EmittedFile;
use super::controller_test::{emit_go_controller_test_body, GoTestCtx};
use super::expr::emit_literal;
use super::shared::go_field_name;

pub(super) fn emit_go_tests(tm: &TestModule, app: &App) -> EmittedFile {
    let fixture_names: Vec<crate::ident::Symbol> =
        app.fixtures.iter().map(|f| f.name.clone()).collect();
    let known_models: Vec<crate::ident::Symbol> =
        app.models.iter().map(|m| m.name.0.clone()).collect();
    let mut attrs_set: std::collections::BTreeSet<crate::ident::Symbol> =
        std::collections::BTreeSet::new();
    for m in &app.models {
        for attr in m.attributes.fields.keys() {
            attrs_set.insert(attr.clone());
        }
    }
    let model_attrs: Vec<crate::ident::Symbol> = attrs_set.into_iter().collect();

    let ctx = GoTestCtx {
        app,
        fixture_names: &fixture_names,
        known_models: &known_models,
        model_attrs: &model_attrs,
    };

    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s, "package app").unwrap();
    writeln!(s).unwrap();
    let is_controller_test = tm.name.0.as_str().ends_with("ControllerTest");
    if is_controller_test {
        // Controller tests reference fmt.Sprint via the form-body
        // flattener; testing is required for *testing.T regardless.
        writeln!(s, "import (").unwrap();
        writeln!(s, "\t\"fmt\"").unwrap();
        writeln!(s, "\t\"testing\"").unwrap();
        writeln!(s, ")").unwrap();
        writeln!(s).unwrap();
        writeln!(s, "var _ = fmt.Sprint").unwrap();
    } else {
        writeln!(s, "import \"testing\"").unwrap();
    }
    for test in &tm.tests {
        let fn_name = format!("Test{}", go_field_name(&test_name_snake(&test.name)));
        writeln!(s).unwrap();
        writeln!(s, "func {fn_name}(t *testing.T) {{").unwrap();
        if is_controller_test {
            // Pass-2: dispatch through TestClient via the shared
            // controller_test classifier + a Go render table.
            if !app.fixtures.is_empty() {
                writeln!(s, "\tsetupTest()").unwrap();
            }
            let body = emit_go_controller_test_body(test, app, &ctx);
            for line in body.lines() {
                writeln!(s, "\t{line}").unwrap();
            }
        } else if test_needs_runtime_unsupported_go(test) {
            writeln!(
                s,
                "\tt.Skip(\"Phase 3: needs persistence runtime\")"
            )
            .unwrap();
        } else {
            if !app.fixtures.is_empty() {
                // Every test starts on a fresh :memory: DB with all
                // fixtures loaded — Rails' transactional-fixture shape.
                writeln!(s, "\tsetupTest()").unwrap();
            }
            let body = emit_test_body_go(&test.body, ctx);
            for line in body.lines() {
                writeln!(s, "\t{line}").unwrap();
            }
        }
        writeln!(s, "}}").unwrap();
    }

    let filename = snake_case(tm.name.0.as_str());
    let filename = filename.replace("_test", "");
    EmittedFile {
        path: PathBuf::from(format!("app/{filename}_test.go")),
        content: s,
    }
}

fn test_name_snake(desc: &str) -> String {
    let mut s: String = desc
        .chars()
        .map(|c| if c.is_alphanumeric() { c.to_ascii_lowercase() } else { '_' })
        .collect();
    while s.contains("__") {
        s = s.replace("__", "_");
    }
    s.trim_matches('_').to_string()
}

fn emit_test_body_go(body: &Expr, ctx: GoTestCtx) -> String {
    match &*body.node {
        ExprNode::Seq { exprs } if !exprs.is_empty() => exprs
            .iter()
            .map(|e| emit_test_stmt_go(e, ctx))
            .collect::<Vec<_>>()
            .join("\n"),
        _ => emit_test_stmt_go(body, ctx),
    }
}

fn emit_test_stmt_go(e: &Expr, ctx: GoTestCtx) -> String {
    match &*e.node {
        ExprNode::Assign { target: LValue::Var { name, .. }, value } => {
            format!("{} := {}", name, emit_test_expr_go(value, ctx))
        }
        _ => emit_test_expr_go(e, ctx),
    }
}

fn emit_test_expr_go(e: &Expr, ctx: GoTestCtx) -> String {
    match &*e.node {
        ExprNode::Lit { value } => emit_literal(value),
        ExprNode::Var { name, .. } => name.to_string(),
        ExprNode::Const { path } => path
            .iter()
            .map(|s| s.to_string())
            .collect::<Vec<_>>()
            .join("."),
        ExprNode::Send { recv, method, args, block, .. } => {
            emit_test_send_go(recv.as_ref(), method.as_str(), args, block.as_ref(), ctx)
        }
        ExprNode::Hash { entries, .. } => {
            // Rough: only used inside Class.new(hash) — handled above.
            let parts: Vec<String> = entries
                .iter()
                .map(|(k, v)| format!("{}: {}", emit_test_expr_go(k, ctx), emit_test_expr_go(v, ctx)))
                .collect();
            format!("map[string]interface{{}}{{{}}}", parts.join(", "))
        }
        ExprNode::BoolOp { op, left, right, .. } => {
            use crate::expr::BoolOpKind;
            let op_s = match op {
                BoolOpKind::Or => "||",
                BoolOpKind::And => "&&",
            };
            format!(
                "{} {} {}",
                emit_test_expr_go(left, ctx),
                op_s,
                emit_test_expr_go(right, ctx)
            )
        }
        _ => format!("/* TODO: Go test emit for {:?} */", std::mem::discriminant(&*e.node)),
    }
}

fn emit_test_send_go(
    recv: Option<&Expr>,
    method: &str,
    args: &[Expr],
    block: Option<&Expr>,
    ctx: GoTestCtx,
) -> String {
    let args_s: Vec<String> = args.iter().map(|a| emit_test_expr_go(a, ctx)).collect();

    // Fixture accessor: articles(:one) → ArticlesOne()
    if recv.is_none()
        && args.len() == 1
        && ctx.fixture_names.iter().any(|s| s.as_str() == method)
    {
        if let ExprNode::Lit { value: Literal::Sym { value: sym } } = &*args[0].node {
            return format!(
                "{}{}()",
                go_field_name(method),
                go_field_name(sym.as_str())
            );
        }
    }

    // assert_difference("Class.count", delta) do ... end →
    // before/after capture + inline Go comparison. Parses the Ruby
    // string into a Go expression (`Comment.count` → `CommentCount()`).
    if recv.is_none() && method == "assert_difference" {
        if let Some(body) = block {
            if let Some(count_expr) = args
                .first()
                .and_then(|a| match &*a.node {
                    ExprNode::Lit { value: Literal::Str { value } } => {
                        rewrite_ruby_dot_call_go(value)
                    }
                    _ => None,
                })
            {
                let delta = args_s.get(1).cloned().unwrap_or_else(|| "1".into());
                let body_s = emit_block_body_go(body, ctx);
                return format!(
                    "_before := {count_expr}\n{body_s}\n_after := {count_expr}\nif _after - _before != int64({delta}) {{ t.Errorf(\"expected delta {delta}, got %d\", _after - _before) }}",
                );
            }
        }
    }

    // owner.<assoc>.create(hash) / .build(hash) — HasMany rewrite.
    // Renders as a Go IIFE so the surrounding assignment/expression
    // context still gets a value.
    if (method == "create" || method == "build") && args.len() == 1 {
        if let Some(outer_recv) = recv {
            if let ExprNode::Send {
                recv: Some(assoc_recv),
                method: assoc_method,
                args: inner_args,
                ..
            } = &*outer_recv.node
            {
                if inner_args.is_empty() {
                    if let Some(s) = try_emit_assoc_create_go(
                        assoc_recv,
                        assoc_method.as_str(),
                        args,
                        method,
                        ctx,
                    ) {
                        return s;
                    }
                }
            }
        }
    }

    // Assertion macros → Go's inline `if ... { t.Errorf(...) }` pattern.
    if recv.is_none() {
        match (method, args_s.len()) {
            ("assert_equal", 2) => {
                return format!(
                    "if {actual} != {expected} {{ t.Errorf(\"expected %v, got %v\", {expected}, {actual}) }}",
                    expected = args_s[0],
                    actual = args_s[1],
                );
            }
            ("assert_not_equal", 2) => {
                return format!(
                    "if {actual} == {expected} {{ t.Errorf(\"expected not equal to %v\", {expected}) }}",
                    expected = args_s[0],
                    actual = args_s[1],
                );
            }
            ("assert_not", 1) => {
                return format!(
                    "if {cond} {{ t.Errorf(\"expected false\") }}",
                    cond = args_s[0]
                );
            }
            ("assert", 1) => {
                return format!(
                    "if !({cond}) {{ t.Errorf(\"expected true\") }}",
                    cond = args_s[0]
                );
            }
            ("assert_nil", 1) => {
                // Go's "nil-ness" varies. Ints test against zero; pointers
                // against nil. We pick based on whether the arg expression
                // looks like a method chain (assume it's a primitive value).
                return format!(
                    "if {expr} != 0 {{ t.Errorf(\"expected zero/nil, got %v\", {expr}) }}",
                    expr = args_s[0]
                );
            }
            ("assert_not_nil", 1) => {
                return format!(
                    "if {expr} == 0 {{ t.Errorf(\"expected non-zero\") }}",
                    expr = args_s[0]
                );
            }
            _ => {}
        }
    }

    // `Class.new(hash)` → `&Class{ Field: val, ... }` struct literal.
    if let Some(r) = recv {
        if method == "new" && args.len() == 1 {
            if let ExprNode::Const { path } = &*r.node {
                if let Some(class_name) = path.last() {
                    if ctx.known_models.iter().any(|s| s == class_name) {
                        if let ExprNode::Hash { entries, .. } = &*args[0].node {
                            let pairs: Vec<String> = entries
                                .iter()
                                .filter_map(|(k, v)| {
                                    if let ExprNode::Lit {
                                        value: Literal::Sym { value: f },
                                    } = &*k.node
                                    {
                                        Some(format!(
                                            "{}: {}",
                                            go_field_name(f.as_str()),
                                            emit_test_expr_go(v, ctx)
                                        ))
                                    } else {
                                        None
                                    }
                                })
                                .collect();
                            return format!(
                                "&{}{{{}}}",
                                class_name,
                                pairs.join(", ")
                            );
                        }
                    }
                }
            }
        }
    }

    match recv {
        None => {
            if args_s.is_empty() {
                method.to_string()
            } else {
                format!("{}({})", method, args_s.join(", "))
            }
        }
        Some(r) => {
            let recv_s = emit_test_expr_go(r, ctx);
            let is_class_call = matches!(&*r.node, ExprNode::Const { .. });
            // Class-level calls flatten to `ClassMethod(args)` — Go
            // has no class methods, and our persistence emitter laid
            // down package-level `ArticleFind` / `CommentCount` /
            // etc. to stand in.
            if is_class_call {
                if args_s.is_empty() {
                    return format!("{recv_s}{}()", go_field_name(method));
                } else {
                    return format!(
                        "{recv_s}{}({})",
                        go_field_name(method),
                        args_s.join(", ")
                    );
                }
            }
            let is_attr = args_s.is_empty()
                && ctx.model_attrs.iter().any(|s| s.as_str() == method);
            if is_attr {
                format!("{recv_s}.{}", go_field_name(method))
            } else if args_s.is_empty() {
                format!("{recv_s}.{}()", go_field_name(method))
            } else {
                format!(
                    "{recv_s}.{}({})",
                    go_field_name(method),
                    args_s.join(", ")
                )
            }
        }
    }
}

/// Parse a Ruby-style `"Class.method"` expression into Go syntax.
/// Capitalized LHS → package-level function (`Comment.count` →
/// `CommentCount()`); lowercase LHS → instance field read.
fn rewrite_ruby_dot_call_go(expr: &str) -> Option<String> {
    let trimmed = expr.trim();
    let (lhs, rhs) = trimmed.split_once('.')?;
    let is_ident = |s: &str| {
        !s.is_empty()
            && s.chars().next().is_some_and(|c| c.is_alphabetic() || c == '_')
            && s.chars().all(|c| c.is_alphanumeric() || c == '_')
    };
    if !is_ident(lhs) || !is_ident(rhs) {
        return None;
    }
    let is_class = lhs.chars().next().is_some_and(|c| c.is_uppercase());
    if is_class {
        Some(format!("{lhs}{}()", go_field_name(rhs)))
    } else {
        Some(format!("{lhs}.{}", go_field_name(rhs)))
    }
}

/// Render a Ruby block body as Go statements, peeling one Lambda
/// layer (Ruby `do ... end` lowers to `ExprNode::Lambda` in the IR).
fn emit_block_body_go(e: &Expr, ctx: GoTestCtx) -> String {
    let inner = match &*e.node {
        ExprNode::Lambda { body, .. } => body,
        _ => e,
    };
    match &*inner.node {
        ExprNode::Seq { exprs } if !exprs.is_empty() => exprs
            .iter()
            .map(|s| emit_test_stmt_go(s, ctx))
            .collect::<Vec<_>>()
            .join("\n"),
        _ => emit_test_stmt_go(inner, ctx),
    }
}

fn try_emit_assoc_create_go(
    owner: &Expr,
    assoc_name: &str,
    args: &[Expr],
    outer_method: &str,
    ctx: GoTestCtx,
) -> Option<String> {
    let resolved = crate::lower::resolve_has_many(
        &crate::ident::Symbol::from(assoc_name),
        owner.ty.as_ref(),
        ctx.app,
    )?;
    let target_class = resolved.target_class.0.as_str();
    let foreign_key = go_field_name(resolved.foreign_key.as_str());

    let owner_s = emit_test_expr_go(owner, ctx);
    let hash_entries = match &args.first()?.node.as_ref() {
        ExprNode::Hash { entries, .. } => entries.clone(),
        _ => return None,
    };

    let mut pairs: Vec<String> =
        vec![format!("{foreign_key}: {owner_s}.ID")];
    for (k, v) in &hash_entries {
        if let ExprNode::Lit { value: Literal::Sym { value: field_name } } = &*k.node {
            pairs.push(format!(
                "{}: {}",
                go_field_name(field_name.as_str()),
                emit_test_expr_go(v, ctx),
            ));
        }
    }
    let struct_lit = format!("&{target_class}{{{}}}", pairs.join(", "));
    // Go IIFE — wraps the multi-statement build+save+return so the
    // caller can use it in an expression position (e.g. RHS of :=).
    if outer_method == "create" {
        Some(format!(
            "func() *{target_class} {{ r := {struct_lit}; r.Save(); return r }}()"
        ))
    } else {
        Some(format!(
            "func() *{target_class} {{ r := {struct_lit}; return r }}()"
        ))
    }
}

fn test_needs_runtime_unsupported_go(_test: &Test) -> bool {
    // Phase 3 rounded out the Go emitter's coverage. Keep the
    // predicate as a future-guard; no real-blog shape forces a
    // skip today.
    false
}

#[allow(dead_code)]
fn test_body_uses_unsupported_go(e: &Expr) -> bool {
    use crate::expr::InterpPart;
    let self_hit = match &*e.node {
        ExprNode::Send { recv, method, .. } => {
            let m = method.as_str();
            matches!(
                m,
                "assert_difference"
                    | "destroy"
                    | "destroy!"
                    | "build"
                    | "create"
                    | "create!"
            ) || (m == "count"
                && recv.as_ref().is_some_and(|r| matches!(&*r.node, ExprNode::Const { .. })))
        }
        _ => false,
    };
    if self_hit {
        return true;
    }
    match &*e.node {
        ExprNode::Send { recv, args, block, .. } => {
            if let Some(r) = recv {
                if test_body_uses_unsupported_go(r) {
                    return true;
                }
            }
            for a in args {
                if test_body_uses_unsupported_go(a) {
                    return true;
                }
            }
            if let Some(b) = block {
                if test_body_uses_unsupported_go(b) {
                    return true;
                }
            }
        }
        ExprNode::Seq { exprs } | ExprNode::Array { elements: exprs, .. } => {
            for e in exprs {
                if test_body_uses_unsupported_go(e) {
                    return true;
                }
            }
        }
        ExprNode::Hash { entries, .. } => {
            for (k, v) in entries {
                if test_body_uses_unsupported_go(k) || test_body_uses_unsupported_go(v) {
                    return true;
                }
            }
        }
        ExprNode::StringInterp { parts } => {
            for p in parts {
                if let InterpPart::Expr { expr } = p {
                    if test_body_uses_unsupported_go(expr) {
                        return true;
                    }
                }
            }
        }
        ExprNode::BoolOp { left, right, .. }
        | ExprNode::RescueModifier { expr: left, fallback: right } => {
            if test_body_uses_unsupported_go(left) || test_body_uses_unsupported_go(right) {
                return true;
            }
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            if test_body_uses_unsupported_go(cond)
                || test_body_uses_unsupported_go(then_branch)
                || test_body_uses_unsupported_go(else_branch)
            {
                return true;
            }
        }
        ExprNode::Let { value, body, .. } => {
            if test_body_uses_unsupported_go(value) || test_body_uses_unsupported_go(body) {
                return true;
            }
        }
        ExprNode::Lambda { body, .. } => {
            if test_body_uses_unsupported_go(body) {
                return true;
            }
        }
        ExprNode::Assign { value, .. } => {
            if test_body_uses_unsupported_go(value) {
                return true;
            }
        }
        _ => {}
    }
    false
}
