//! View emission — `app/views.go` with one `func Render<Plural><Action>`
//! per ingested view plus stubs for standard CRUD views the fixture
//! didn't supply. Walks the ERB IR (`_buf = _buf + X`) produced by
//! `src/erb.rs`, same shape the TS/Rust degrade-gracefully consumers
//! use; unknown shapes become `_buf += "" // TODO view …` so the file
//! still compiles.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use super::shared::{go_field_name, pascalize_word};
use crate::App;
use crate::expr::{Expr, ExprNode, LValue, Literal};
use crate::ident::Symbol;

pub(super) fn emit_go_views(app: &App, known_models: &[Symbol]) -> EmittedFile {
    let attrs_by_class: std::collections::BTreeMap<String, Vec<String>> = app
        .models
        .iter()
        .map(|m| {
            (
                m.name.0.as_str().to_string(),
                m.attributes
                    .fields
                    .keys()
                    .map(|k| k.as_str().to_string())
                    .collect(),
            )
        })
        .collect();
    let has_manys = crate::lower::build_has_many_table(app);
    let stylesheets = app.stylesheets.clone();

    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s, "package app").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "import (").unwrap();
    writeln!(s, "\t\"fmt\"").unwrap();
    writeln!(s, "\t\"strconv\"").unwrap();
    writeln!(s, ")").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "var _ = fmt.Sprint").unwrap();
    writeln!(s, "var _ = strconv.Itoa").unwrap();

    let mut emitted: std::collections::BTreeSet<String> =
        std::collections::BTreeSet::new();
    for v in &app.views {
        let fn_name = go_view_function_name(v.name.as_str());
        if !emitted.insert(fn_name.clone()) {
            continue;
        }
        writeln!(s).unwrap();
        emit_go_view_file(&mut s, v, known_models, &attrs_by_class, &has_manys, &stylesheets);
    }
    // Stub missing standard CRUD views so controllers always link.
    for model in &app.models {
        if model.attributes.fields.is_empty() {
            continue;
        }
        let class = model.name.0.as_str();
        let plural = crate::naming::pluralize_snake(class);
        for suffix in ["index", "show", "new", "edit"] {
            let view_name = format!("{plural}/{suffix}");
            let fn_name = go_view_function_name(&view_name);
            if emitted.insert(fn_name.clone()) {
                let arg_ty = if suffix == "index" {
                    format!("[]*{class}")
                } else {
                    format!("*{class}")
                };
                writeln!(s).unwrap();
                writeln!(s, "func {fn_name}(_record {arg_ty}) string {{").unwrap();
                writeln!(s, "\treturn \"\"").unwrap();
                writeln!(s, "}}").unwrap();
            }
        }
    }
    EmittedFile {
        path: PathBuf::from("app/views.go"),
        content: s,
    }
}

fn go_view_function_name(name: &str) -> String {
    let mut parts: Vec<String> = Vec::new();
    for seg in name.split('/') {
        let trimmed = seg.strip_prefix('_').unwrap_or(seg);
        parts.push(pascalize_word(trimmed));
    }
    format!("Render{}", parts.join(""))
}

fn emit_go_view_file(
    out: &mut String,
    view: &crate::dialect::View,
    known_models: &[Symbol],
    attrs_by_class: &std::collections::BTreeMap<String, Vec<String>>,
    has_manys: &[crate::lower::HasManyRow],
    stylesheets: &[String],
) {
    let fn_name = go_view_function_name(view.name.as_str());
    let (sig, arg_name, arg_class) = go_view_signature(view.name.as_str(), known_models);
    let attrs = arg_class
        .as_ref()
        .and_then(|c| attrs_by_class.get(c).cloned())
        .unwrap_or_default();
    let resource_dir = view
        .name
        .as_str()
        .rsplit_once('/')
        .map(|(d, _): (&str, &str)| d.to_string())
        .unwrap_or_default();

    writeln!(out, "func {fn_name}({sig}) string {{").unwrap();
    writeln!(out, "\t_ = {arg_name}").unwrap();
    writeln!(out, "\t_buf := \"\"").unwrap();

    let mut locals: Vec<String> = vec!["_buf".to_string(), arg_name.clone()];
    let ivar_names = go_collect_ivar_names(&view.body);
    for n in &ivar_names {
        if !locals.iter().any(|x| x == n) {
            locals.push(n.clone());
        }
    }
    let ctx = GoViewCtx {
        locals,
        arg_name: arg_name.clone(),
        arg_attrs: attrs,
        resource_dir,
        has_manys: has_manys.to_vec(),
        stylesheets: stylesheets.to_vec(),
        form_records: Vec::new(),
        attrs_by_class: attrs_by_class.clone(),
    };
    // Apply the shared erubi-trim pass — same as rust/ts/python.
    let trimmed_body = crate::lower::erb_trim::trim_view(&view.body);
    let lines = emit_go_view_body(&trimmed_body, &ctx);
    for line in &lines {
        writeln!(out, "\t{line}").unwrap();
    }
    writeln!(out, "\treturn _buf").unwrap();
    writeln!(out, "}}").unwrap();
}

#[derive(Clone)]
struct GoViewCtx {
    locals: Vec<String>,
    arg_name: String,
    arg_attrs: Vec<String>,
    resource_dir: String,
    has_manys: Vec<crate::lower::HasManyRow>,
    stylesheets: Vec<String>,
    /// Active FormBuilder bindings: `(builder_local_name,
    /// record_go_expr)` pairs. Populated on `form_with` block entry;
    /// consumed by FormBuilder field emit so `form.text_field :title`
    /// resolves to the bound record's field.
    form_records: Vec<(String, String)>,
    attrs_by_class: std::collections::BTreeMap<String, Vec<String>>,
}

impl GoViewCtx {
    fn is_local(&self, n: &str) -> bool {
        self.locals.iter().any(|x| x == n)
    }
    fn arg_has_attr(&self, name: &str, attr: &str) -> bool {
        name == self.arg_name && self.arg_attrs.iter().any(|a| a == attr)
    }
    fn local_has_attr(&self, local: &str, attr: &str) -> bool {
        if self.arg_has_attr(local, attr) {
            return true;
        }
        let class = crate::naming::singularize_camelize(local);
        self.attrs_by_class
            .get(&class)
            .map(|attrs| attrs.iter().any(|a| a == attr))
            .unwrap_or(false)
    }
    fn with_locals(&self, more: impl IntoIterator<Item = String>) -> Self {
        let mut next = self.clone();
        for n in more {
            if !next.locals.iter().any(|x| x == &n) {
                next.locals.push(n);
            }
        }
        next
    }
    fn resolve_has_many_on_local(&self, local: &str, assoc: &str) -> Option<(String, String)> {
        if !self.is_local(local) {
            return None;
        }
        crate::lower::resolve_has_many_on_local(&self.has_manys, local, assoc)
    }
}

fn go_collect_ivar_names(expr: &Expr) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    go_collect_ivars_into(expr, &mut out);
    out
}

fn go_collect_ivars_into(expr: &Expr, out: &mut Vec<String>) {
    match &*expr.node {
        ExprNode::Ivar { name } => {
            let n = name.to_string();
            if !out.iter().any(|x| x == &n) {
                out.push(n);
            }
        }
        ExprNode::Assign { target, value } => {
            if let LValue::Ivar { name } = target {
                let n = name.to_string();
                if !out.iter().any(|x| x == &n) {
                    out.push(n);
                }
            }
            go_collect_ivars_into(value, out);
        }
        ExprNode::Send { recv, args, block, .. } => {
            if let Some(r) = recv {
                go_collect_ivars_into(r, out);
            }
            for a in args {
                go_collect_ivars_into(a, out);
            }
            if let Some(b) = block {
                go_collect_ivars_into(b, out);
            }
        }
        ExprNode::Seq { exprs } | ExprNode::Array { elements: exprs, .. } => {
            for e in exprs {
                go_collect_ivars_into(e, out);
            }
        }
        ExprNode::Hash { entries, .. } => {
            for (k, v) in entries {
                go_collect_ivars_into(k, out);
                go_collect_ivars_into(v, out);
            }
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            go_collect_ivars_into(cond, out);
            go_collect_ivars_into(then_branch, out);
            go_collect_ivars_into(else_branch, out);
        }
        ExprNode::BoolOp { left, right, .. } => {
            go_collect_ivars_into(left, out);
            go_collect_ivars_into(right, out);
        }
        ExprNode::Lambda { body, .. } => go_collect_ivars_into(body, out),
        _ => {}
    }
}

fn go_view_signature(
    view_name: &str,
    known_models: &[Symbol],
) -> (String, String, Option<String>) {
    let (dir, base) = view_name.rsplit_once('/').unwrap_or(("", view_name));
    let is_partial = base.starts_with('_');
    let stem = base.trim_start_matches('_');
    let model_class = crate::naming::singularize_camelize(dir);
    let model_exists = known_models.iter().any(|m| m.as_str() == model_class);
    let singular = crate::naming::singularize(dir);

    if is_partial {
        let arg_name = if model_exists { singular.clone() } else { stem.to_string() };
        if model_exists {
            return (format!("{arg_name} *{model_class}"), arg_name, Some(model_class));
        }
        return (format!("{arg_name} interface{{}}"), arg_name, None);
    }
    match stem {
        "index" => {
            let arg_name = dir.to_string();
            if model_exists {
                return (
                    format!("{arg_name} []*{model_class}"),
                    arg_name,
                    Some(model_class),
                );
            }
            (format!("{arg_name} []interface{{}}"), arg_name, None)
        }
        _ => {
            let arg_name = singular.clone();
            if model_exists {
                return (format!("{arg_name} *{model_class}"), arg_name, Some(model_class));
            }
            (format!("{arg_name} interface{{}}"), arg_name, None)
        }
    }
}

fn emit_go_view_body(body: &Expr, ctx: &GoViewCtx) -> Vec<String> {
    let stmts: Vec<&Expr> = match &*body.node {
        ExprNode::Seq { exprs } => exprs.iter().collect(),
        _ => vec![body],
    };
    let mut out = Vec::new();
    for stmt in &stmts {
        out.extend(emit_go_view_stmt(stmt, ctx));
    }
    out
}

fn emit_go_view_stmt(stmt: &Expr, ctx: &GoViewCtx) -> Vec<String> {
    match &*stmt.node {
        // Prologue _buf assignment is emitted by emit_go_view_file.
        ExprNode::Assign { target: LValue::Var { name, .. }, value }
            if name.as_str() == "_buf" =>
        {
            if let ExprNode::Lit { value: Literal::Str { value: s } } = &*value.node {
                if s.is_empty() {
                    return Vec::new();
                }
            }
            // `_buf = _buf + X` shape.
            if let ExprNode::Send { recv: Some(recv), method, args, .. } = &*value.node {
                if method.as_str() == "+" && args.len() == 1 {
                    if let ExprNode::Var { name: rn, .. } = &*recv.node {
                        if rn.as_str() == "_buf" {
                            return emit_go_view_append(&args[0], ctx);
                        }
                    }
                }
            }
            vec!["// TODO view: unknown _buf shape".to_string()]
        }
        // Trailing `_buf` reference.
        ExprNode::Var { name, .. } if name.as_str() == "_buf" => Vec::new(),
        ExprNode::Ivar { .. } => Vec::new(),
        ExprNode::If { cond, then_branch, else_branch } => {
            let cond_go = if is_go_simple_view_expr(cond, ctx) {
                emit_go_view_expr_raw(cond, ctx)
            } else {
                "false".to_string()
            };
            let mut out = vec![format!("if {cond_go} {{")];
            for line in emit_go_view_body(then_branch, ctx) {
                out.push(format!("\t{line}"));
            }
            // Always emit an else branch; Go is fine with empty blocks.
            let else_lines = emit_go_view_body(else_branch, ctx);
            if !else_lines.is_empty() {
                out.push("} else {".to_string());
                for line in else_lines {
                    out.push(format!("\t{line}"));
                }
            }
            out.push("}".to_string());
            out
        }
        // `<% article.errors.each do |error| %> … <% end %>`
        ExprNode::Send { recv: Some(recv), method, args, block: Some(block), .. }
            if method.as_str() == "each" && args.is_empty() =>
        {
            if !is_go_simple_view_expr(recv, ctx) {
                return vec!["// TODO view: each over complex coll".to_string()];
            }
            let ExprNode::Lambda { params, body, .. } = &*block.node else {
                return vec!["// TODO view: each block shape".to_string()];
            };
            let coll_s = emit_go_view_expr_raw(recv, ctx);
            let var = params
                .first()
                .map(|p| p.as_str().to_string())
                .unwrap_or_else(|| "item".into());
            let inner_ctx = ctx.with_locals([var.clone()]);
            let mut out = vec![format!("for _, {var} := range {coll_s} {{")];
            out.push(format!("\t_ = {var}"));
            for line in emit_go_view_body(body, &inner_ctx) {
                out.push(format!("\t{line}"));
            }
            out.push("}".to_string());
            out
        }
        // Statement-form `<% content_for :title, "Articles" %>`.
        ExprNode::Send { recv: None, method, args, block: None, .. } => {
            if let Some(crate::lower::ViewHelperKind::ContentForSetter { slot, body }) =
                crate::lower::classify_view_helper(method.as_str(), args)
            {
                if is_go_simple_view_expr(body, ctx) {
                    let body_s = emit_go_view_expr_raw(body, ctx);
                    return vec![format!(
                        "ContentForSet({slot:?}, fmt.Sprint({body_s}))"
                    )];
                }
            }
            vec!["// TODO view: unknown stmt".to_string()]
        }
        _ => vec!["// TODO view: unknown stmt".to_string()],
    }
}

fn emit_go_view_append(arg: &Expr, ctx: &GoViewCtx) -> Vec<String> {
    // Text chunk.
    if let ExprNode::Lit { value: Literal::Str { value: s } } = &*arg.node {
        return vec![format!("_buf += {}", go_string_literal(s))];
    }
    let inner = unwrap_to_s_go(arg);

    // `<%= yield %>` / `<%= yield :head %>`.
    if let ExprNode::Yield { args } = &*inner.node {
        if let Some(first) = args.first() {
            if let Some(slot) = go_extract_slot_name(first) {
                return vec![format!("_buf += GetSlot({slot:?})")];
            }
        }
        return vec!["_buf += GetYield()".to_string()];
    }

    // `<%= content_for(:slot) || "default" %>` — BoolOp fallback.
    if let ExprNode::BoolOp { op, left, right, .. } = &*inner.node {
        if matches!(op, crate::expr::BoolOpKind::Or) {
            if let ExprNode::Send { recv: None, method, args, block: None, .. } = &*left.node {
                if method.as_str() == "content_for" && args.len() == 1 {
                    if let Some(slot) = go_extract_slot_name(&args[0]) {
                        if is_go_simple_view_expr(right, ctx) {
                            let fb = emit_go_view_expr_raw(right, ctx);
                            return vec![format!(
                                "if __cf := ContentForGet({slot:?}); __cf != \"\" {{ _buf += __cf }} else {{ _buf += fmt.Sprint({fb}) }}"
                            )];
                        }
                    }
                }
            }
        }
    }

    // `render @coll` or `render "partial", locals` — expand.
    if let ExprNode::Send { recv: None, method, args, block: None, .. } = &*inner.node {
        if method.as_str() == "render" {
            if args.len() == 1 {
                return emit_go_render_call(&args[0], ctx);
            }
            if args.len() == 2 {
                if let (
                    ExprNode::Lit { value: Literal::Str { value: partial } },
                    ExprNode::Hash { entries, .. },
                ) = (&*args[0].node, &*args[1].node)
                {
                    let partial_trim = partial.trim_start_matches('_');
                    let partial_fn = format!(
                        "Render{}{}",
                        pascalize_word(&ctx.resource_dir),
                        pascalize_word(partial_trim),
                    );
                    if let Some((_, v)) = entries.first() {
                        if is_go_simple_view_expr(v, ctx) {
                            let arg_expr = emit_go_view_expr_raw(v, ctx);
                            return vec![format!("_buf += {partial_fn}({arg_expr})")];
                        }
                    }
                    return vec![format!("_buf += {partial_fn}(nil)")];
                }
            }
        }
    }

    // form_with / content_for(do block) — capturing helpers.
    if let ExprNode::Send {
        recv: None,
        method,
        args,
        block: Some(block),
        ..
    } = &*inner.node
    {
        if is_go_capturing_helper(method.as_str()) {
            return emit_go_captured_helper(method.as_str(), args, block, ctx);
        }
    }

    // View-helper classifier dispatch.
    if let ExprNode::Send { recv: None, method, args, block: None, .. } = &*inner.node {
        if let Some(kind) = crate::lower::classify_view_helper(method.as_str(), args) {
            if let Some(line) = emit_go_view_helper(&kind, ctx) {
                return vec![line];
            }
        }
    }

    // FormBuilder method calls (`form.label :title`, etc.).
    if let ExprNode::Send { recv: Some(r), method, args, block: None, .. } = &*inner.node {
        if let ExprNode::Var { name, .. } | ExprNode::Ivar { name } = &*r.node {
            if ctx.form_records.iter().any(|(n, _)| n == name.as_str()) {
                if let Some(fb) = crate::lower::classify_form_builder_method(method.as_str()) {
                    if let Some(call) = emit_go_form_builder_call(name.as_str(), fb, args, ctx)
                    {
                        return vec![format!("_buf += {call}")];
                    }
                }
            }
        }
    }

    // Simple interpolation → render via fmt.Sprint for non-string
    // values.
    if is_go_simple_view_expr(inner, ctx) {
        let raw = emit_go_view_expr_raw(inner, ctx);
        // Literal strings pass through without fmt.Sprint.
        if matches!(&*inner.node, ExprNode::Lit { value: Literal::Str { .. } }) {
            return vec![format!("_buf += {raw}")];
        }
        return vec![format!("_buf += fmt.Sprint({raw})")];
    }
    vec!["_buf += \"\" // TODO view: complex interpolation".to_string()]
}

fn go_extract_slot_name(arg: &Expr) -> Option<&str> {
    match &*arg.node {
        ExprNode::Lit { value: Literal::Sym { value } } => Some(value.as_str()),
        ExprNode::Lit { value: Literal::Str { value } } => Some(value.as_str()),
        _ => None,
    }
}

fn is_go_capturing_helper(method: &str) -> bool {
    matches!(method, "form_with" | "content_for")
}

/// Render a classified `ViewHelperKind` to a Go `_buf += …` line.
fn emit_go_view_helper(
    kind: &crate::lower::ViewHelperKind<'_>,
    ctx: &GoViewCtx,
) -> Option<String> {
    use crate::lower::ViewHelperKind::*;
    match kind {
        CsrfMetaTags => Some("_buf += CsrfMetaTags()".to_string()),
        CspMetaTag => Some("_buf += CspMetaTag()".to_string()),
        JavascriptImportmapTags => {
            Some("_buf += JavascriptImportmapTags(Pins, \"application\")".to_string())
        }
        TurboStreamFrom { channel } => {
            if !is_go_simple_view_expr(channel, ctx) {
                return None;
            }
            let arg = emit_go_view_expr_raw(channel, ctx);
            Some(format!("_buf += TurboStreamFrom({arg})"))
        }
        DomId { record, prefix } => {
            let (singular, id_expr) = go_resolve_dom_id_record(record, ctx)?;
            match prefix {
                None => Some(format!(
                    "_buf += DomId({singular:?}, {id_expr}, \"\")"
                )),
                Some(p) => {
                    let prefix_str = match &*p.node {
                        ExprNode::Lit { value: Literal::Sym { value } } => {
                            format!("{:?}", value.as_str())
                        }
                        ExprNode::Lit { value: Literal::Str { value } } => format!("{value:?}"),
                        _ if is_go_simple_view_expr(p, ctx) => emit_go_view_expr_raw(p, ctx),
                        _ => return None,
                    };
                    Some(format!(
                        "_buf += DomId({singular:?}, {id_expr}, {prefix_str})"
                    ))
                }
            }
        }
        Pluralize { count, word } => {
            if !is_go_simple_view_expr(count, ctx) || !is_go_simple_view_expr(word, ctx) {
                return None;
            }
            let c = emit_go_view_expr_raw(count, ctx);
            let w = emit_go_view_expr_raw(word, ctx);
            Some(format!("_buf += Pluralize(int64({c}), {w})"))
        }
        Truncate { text, opts } => {
            if !is_go_simple_view_expr(text, ctx) {
                return None;
            }
            let t = emit_go_view_expr_raw(text, ctx);
            let opts_code = go_opts_from_expr(opts.as_deref(), ctx);
            Some(format!("_buf += Truncate({t}, {opts_code})"))
        }
        StylesheetLinkTag { name, opts } => {
            let opts_code = go_opts_from_expr(opts.as_deref(), ctx);
            if let ExprNode::Lit { value: Literal::Sym { value } } = &*name.node {
                if value.as_str() == "app" && !ctx.stylesheets.is_empty() {
                    let lines: Vec<String> = ctx
                        .stylesheets
                        .iter()
                        .map(|n| format!("_buf += StylesheetLinkTag({n:?}, {opts_code})"))
                        .collect();
                    return Some(lines.join("\n_buf += \"\\n\"\n"));
                }
            }
            let name_expr = match &*name.node {
                ExprNode::Lit { value: Literal::Sym { value } } => format!("{:?}", value.as_str()),
                ExprNode::Lit { value: Literal::Str { value } } => format!("{value:?}"),
                _ => return None,
            };
            Some(format!(
                "_buf += StylesheetLinkTag({name_expr}, {opts_code})"
            ))
        }
        ContentForGetter { slot } => Some(format!("_buf += ContentForGet({slot:?})")),
        ContentForSetter { .. } => None,
        LinkTo { text, url, opts } => {
            emit_go_link_or_button("LinkTo", text, url, *opts, ctx)
                .map(|call| format!("_buf += {call}"))
        }
        ButtonTo { text, target, opts } => {
            emit_go_link_or_button("ButtonTo", text, target, *opts, ctx)
                .map(|call| format!("_buf += {call}"))
        }
    }
}

fn go_resolve_dom_id_record(record: &Expr, ctx: &GoViewCtx) -> Option<(String, String)> {
    let name = match &*record.node {
        ExprNode::Var { name, .. } | ExprNode::Ivar { name } if ctx.is_local(name.as_str()) => {
            name.as_str().to_string()
        }
        ExprNode::Send {
            recv: None,
            method,
            args,
            block: None,
            ..
        } if args.is_empty() && ctx.is_local(method.as_str()) => method.as_str().to_string(),
        _ => return None,
    };
    let singular = crate::naming::singularize(&name);
    Some((singular, format!("{name}.ID")))
}

fn emit_go_link_or_button(
    helper: &str,
    text: &Expr,
    url: &Expr,
    opts: Option<&Expr>,
    ctx: &GoViewCtx,
) -> Option<String> {
    if !is_go_simple_view_expr(text, ctx) {
        return None;
    }
    let text_raw = emit_go_view_expr_raw(text, ctx);
    let text_expr = match &*text.node {
        ExprNode::Lit { value: Literal::Str { .. } } => text_raw,
        _ => format!("fmt.Sprint({text_raw})"),
    };
    let is_local = |n: &str| ctx.is_local(n);
    let url_kind = crate::lower::classify_view_url_arg(url, &is_local)?;
    let url_expr = match url_kind {
        crate::lower::ViewUrlArg::Literal { value } => format!("{value:?}"),
        crate::lower::ViewUrlArg::PathHelper { name, args } => {
            let args_s: Vec<String> = args.iter().map(|a| go_path_arg(a, ctx)).collect();
            // `articles_path` → `ArticlesPath` via PascalCase of
            // the snake_case stem. go_field_name handles
            // multi-word snake_case.
            let stem = name.strip_suffix("_path").unwrap_or(name);
            format!("{}Path({})", go_field_name(stem), args_s.join(", "))
        }
        crate::lower::ViewUrlArg::RecordRef { name } => {
            format!(
                "{}Path({name}.ID)",
                go_field_name(&crate::naming::singularize(name)),
            )
        }
        crate::lower::ViewUrlArg::NestedArray { elements } => go_emit_nested_path(elements, ctx)?,
    };
    let opts_code = go_opts_from_expr(opts, ctx);
    Some(format!("{helper}({text_expr}, {url_expr}, {opts_code})"))
}

fn go_path_arg(arg: &Expr, ctx: &GoViewCtx) -> String {
    match &*arg.node {
        ExprNode::Var { name, .. } | ExprNode::Ivar { name } if ctx.is_local(name.as_str()) => {
            format!("{}.ID", name.as_str())
        }
        ExprNode::Send { recv: None, method, args, block: None, .. }
            if args.is_empty() && ctx.is_local(method.as_str()) =>
        {
            format!("{}.ID", method.as_str())
        }
        _ => emit_go_view_expr_raw(arg, ctx),
    }
}

fn go_emit_nested_path(elements: &[Expr], ctx: &GoViewCtx) -> Option<String> {
    let is_local = |n: &str| ctx.is_local(n);
    let mut singulars: Vec<String> = Vec::new();
    let mut args: Vec<String> = Vec::new();
    for el in elements {
        let kind = crate::lower::classify_nested_url_element(el, &is_local)?;
        let (singular, id_expr) = go_nested_element_parts(&kind);
        singulars.push(singular);
        args.push(id_expr);
    }
    // Member path: [article, comment] → ArticleCommentPath.
    let mut name = String::new();
    for s in &singulars {
        name.push_str(&pascalize_word(s));
    }
    name.push_str("Path");
    Some(format!("{name}({})", args.join(", ")))
}

fn go_opts_from_expr(opts: Option<&Expr>, ctx: &GoViewCtx) -> String {
    match opts.map(|e| &*e.node) {
        Some(ExprNode::Hash { entries, .. }) => go_hash_to_map(entries, ctx),
        _ => "map[string]string{}".to_string(),
    }
}

fn go_hash_to_map(entries: &[(Expr, Expr)], ctx: &GoViewCtx) -> String {
    let mut items: Vec<(String, String)> = Vec::new();
    for (k, v) in entries {
        let key = match &*k.node {
            ExprNode::Lit { value: Literal::Sym { value } } => value.as_str().to_string(),
            ExprNode::Lit { value: Literal::Str { value } } => value.clone(),
            _ => continue,
        };
        if key == "data" {
            if let ExprNode::Hash { entries: de, .. } = &*v.node {
                for (dk, dv) in de {
                    let dk_str = match &*dk.node {
                        ExprNode::Lit { value: Literal::Sym { value } } => {
                            value.as_str().replace('_', "-")
                        }
                        ExprNode::Lit { value: Literal::Str { value } } => {
                            value.replace('_', "-")
                        }
                        _ => continue,
                    };
                    let dv_s = go_opt_value(dv, ctx);
                    items.push((format!("data-{dk_str}"), dv_s));
                }
                continue;
            }
        }
        let val = if key == "class" {
            go_class_value(v, ctx)
        } else {
            go_opt_value(v, ctx)
        };
        items.push((key, val));
    }
    let parts: Vec<String> = items
        .into_iter()
        .map(|(k, v)| format!("{k:?}: {v}"))
        .collect();
    format!("map[string]string{{{}}}", parts.join(", "))
}

fn go_opt_value(v: &Expr, ctx: &GoViewCtx) -> String {
    match &*v.node {
        ExprNode::Lit { value: Literal::Str { value } } => format!("{value:?}"),
        ExprNode::Lit { value: Literal::Int { value, .. } } => {
            format!("strconv.Itoa({value})")
        }
        ExprNode::Lit { value: Literal::Sym { value } } => format!("{:?}", value.as_str()),
        ExprNode::Array { elements, .. } => match elements.first() {
            Some(first) => match &*first.node {
                ExprNode::Lit { value: Literal::Str { value } } => format!("{value:?}"),
                _ => "\"\"".to_string(),
            },
            None => "\"\"".to_string(),
        },
        _ if is_go_simple_view_expr(v, ctx) => {
            let raw = emit_go_view_expr_raw(v, ctx);
            match &*v.node {
                ExprNode::Lit { .. } => raw,
                _ => format!("fmt.Sprint({raw})"),
            }
        }
        _ => "\"\"".to_string(),
    }
}

fn go_class_value(v: &Expr, ctx: &GoViewCtx) -> String {
    let is_local = |n: &str| ctx.is_local(n);
    let simple_as_go = |e: &Expr| -> Option<String> {
        if is_go_simple_view_expr(e, ctx) {
            Some(match &*e.node {
                ExprNode::Lit { value: Literal::Str { value } } => format!("{value:?}"),
                _ => {
                    let raw = emit_go_view_expr_raw(e, ctx);
                    match &*e.node {
                        ExprNode::Lit { .. } => raw,
                        _ => format!("fmt.Sprint({raw})"),
                    }
                }
            })
        } else {
            None
        }
    };
    match crate::lower::classify_class_value(v, &is_local) {
        crate::lower::ClassValueShape::Simple { expr } => {
            simple_as_go(expr).unwrap_or_else(|| "\"\"".to_string())
        }
        crate::lower::ClassValueShape::Conditional { base, clauses } => {
            let Some(base_go) = simple_as_go(base) else {
                return "\"\"".to_string();
            };
            if clauses.is_empty() {
                return base_go;
            }
            // Build: (base + func() string { if P1 { return " C1" }; return "" }() + … )
            let mut out = base_go;
            for (cls_text, pred) in &clauses {
                let cond = go_render_errors_field_predicate(pred);
                out = format!(
                    "{out} + func() string {{ if {cond} {{ return \" {cls_text}\" }}; return \"\" }}()"
                );
            }
            format!("({out})")
        }
        crate::lower::ClassValueShape::Unknown => "\"\"".to_string(),
    }
}

fn go_render_errors_field_predicate(pred: &crate::lower::ErrorsFieldPredicate<'_>) -> String {
    let call = format!(
        "FieldHasError({}.Errors, {:?})",
        pred.record, pred.field,
    );
    if pred.expect_present {
        call
    } else {
        format!("!{call}")
    }
}

fn emit_go_form_builder_call(
    recv: &str,
    kind: crate::lower::FormBuilderMethod,
    args: &[Expr],
    ctx: &GoViewCtx,
) -> Option<String> {
    use crate::lower::FormBuilderMethod::*;
    let (field, opts_entries) = crate::lower::classify_form_builder_args(args);
    let field = field.map(str::to_string);
    let opts = opts_entries
        .map(|entries| go_hash_to_map(entries, ctx))
        .unwrap_or_else(|| "map[string]string{}".to_string());
    match kind {
        Label => {
            let field = field?;
            Some(format!("{recv}.Label({field:?}, {opts})"))
        }
        TextField | TextArea => {
            let go_method = if matches!(kind, TextField) { "TextField" } else { "Textarea" };
            let field = field?;
            let value_expr = ctx
                .form_records
                .iter()
                .find(|(name, _)| name == recv)
                .and_then(|(_, record)| {
                    if ctx.local_has_attr(record, &field) {
                        Some(format!(
                            "{record}.{}",
                            go_field_name(&field),
                        ))
                    } else {
                        None
                    }
                })
                .unwrap_or_else(|| "\"\"".to_string());
            Some(format!(
                "{recv}.{go_method}({field:?}, {value_expr}, {opts})"
            ))
        }
        Submit => {
            let label_str = args.iter().find_map(|a| match &*a.node {
                ExprNode::Lit { value: Literal::Str { value } } => Some(value.clone()),
                _ => None,
            });
            let opts_expr = if let Some(lbl) = label_str {
                format!(
                    "func() map[string]string {{ m := {opts}; m[\"label\"] = {lbl:?}; return m }}()",
                )
            } else {
                opts
            };
            Some(format!("{recv}.Submit({opts_expr})"))
        }
    }
}


/// Emit a `render @coll` / `render parent.assoc` call by expanding
/// into a Go `for` loop that concatenates the partial's rendering.
fn emit_go_render_call(arg: &Expr, _ctx: &GoViewCtx) -> Vec<String> {
    match &*arg.node {
        ExprNode::Var { name, .. } | ExprNode::Ivar { name } => {
            let singular = crate::naming::singularize(name.as_str());
            let partial_fn =
                format!("Render{}{}", pascalize_word(name.as_str()), pascalize_word(&singular));
            let coll = name.to_string();
            vec![format!(
                "for _, _r := range {coll} {{ _buf += {partial_fn}(_r) }}"
            )]
        }
        ExprNode::Send { recv: Some(r), method, args, .. }
            if args.is_empty()
                && matches!(&*r.node, ExprNode::Var { .. } | ExprNode::Ivar { .. }) =>
        {
            let assoc_plural = method.as_str();
            let singular = crate::naming::singularize(assoc_plural);
            let partial_fn = format!(
                "Render{}{}",
                pascalize_word(assoc_plural),
                pascalize_word(&singular),
            );
            let parent_name = match &*r.node {
                ExprNode::Var { name, .. } | ExprNode::Ivar { name } => name.to_string(),
                _ => unreachable!(),
            };
            vec![format!(
                "for _, _c := range {parent_name}.{}() {{ _buf += {partial_fn}(_c) }}",
                pascalize_word(assoc_plural),
            )]
        }
        _ => vec!["_buf += \"\" // TODO view: render".to_string()],
    }
}

/// Emit a captured-block helper (`form_with` / `content_for`)
/// using the snapshot-and-slice idiom — remember `len(_buf)` at the
/// block's start, let the body append inline, then wrap/stash the
/// appended span. Matches the python port's shape.
fn emit_go_captured_helper(
    method: &str,
    args: &[Expr],
    block: &Expr,
    ctx: &GoViewCtx,
) -> Vec<String> {
    let ExprNode::Lambda { params, body, .. } = &*block.node else {
        return vec![format!("_buf += \"\" // TODO view: {method}")];
    };
    let cls_expr = args
        .iter()
        .find_map(|a| go_extract_kwarg(a, "class"))
        .filter(|e| is_go_simple_view_expr(e, ctx))
        .map(|e| emit_go_view_expr_raw(e, ctx))
        .unwrap_or_else(|| "\"\"".to_string());
    match method {
        "form_with" => {
            let model_expr = args
                .iter()
                .find_map(|a| go_extract_kwarg(a, "model"));
            let model_nested: Option<Vec<Expr>> = model_expr.and_then(|e| match &*e.node {
                ExprNode::Array { elements, .. } if elements.len() >= 2 => {
                    Some(elements.clone())
                }
                _ => None,
            });
            let record_ref: Option<String> = if let Some(elems) = &model_nested {
                Some(emit_go_nested_form_record(&elems[elems.len() - 1]))
            } else {
                model_expr
                    .filter(|e| is_go_simple_view_expr(e, ctx))
                    .map(|e| emit_go_view_expr_raw(e, ctx))
                    .or_else(|| {
                        if !ctx.arg_name.is_empty() && ctx.is_local(&ctx.arg_name) {
                            Some(ctx.arg_name.clone())
                        } else {
                            None
                        }
                    })
            };
            let prefix = if let Some(elems) = &model_nested {
                go_nested_form_child_prefix(&elems[elems.len() - 1])
                    .unwrap_or_else(|| ctx.arg_name.clone())
            } else if !ctx.resource_dir.is_empty() {
                crate::naming::singularize(&ctx.resource_dir)
            } else {
                ctx.arg_name.clone()
            };

            let pname = params.first().map(|p| p.as_str()).unwrap_or("form");
            let plural = if !ctx.resource_dir.is_empty() {
                ctx.resource_dir.clone()
            } else {
                crate::naming::pluralize_snake(&prefix)
            };
            let prefix_pascal = pascalize_word(&prefix);
            let plural_pascal = pascalize_word(&plural);

            // Stash the record in a local so downstream `.ID` /
            // `.Errors` accesses have a clean lvalue to address
            // (Go forbids `&Comment{}.ID` without parens — and
            // reusing the literal allocates each time). We only
            // introduce the `_formRec` local when record_ref is a
            // complex expression (`&Comment{}`); when it's already
            // a bare local (`article`) the downstream code can read
            // attrs directly via `ctx.local_has_attr`.
            let record_is_bare_local = record_ref
                .as_deref()
                .map(|r| {
                    r.chars().all(|c| c.is_alphanumeric() || c == '_')
                        && ctx.is_local(r)
                })
                .unwrap_or(false);
            let record_local = if record_is_bare_local {
                None
            } else {
                record_ref.as_ref().map(|_| "_formRec".to_string())
            };
            let record_access = record_local.clone().or_else(|| record_ref.clone());
            let is_persisted_expr = record_access
                .as_deref()
                .map(|r| format!("({r}.ID != 0)"))
                .unwrap_or_else(|| "false".to_string());
            let action_expr = match (&record_access, &model_nested) {
                (Some(record), Some(elems)) => {
                    go_nested_form_path_expr(elems, ctx, record, &prefix)
                }
                (Some(record), None) => format!(
                    "func() string {{ if {record}.ID != 0 {{ return {prefix_pascal}Path({record}.ID) }}; return {plural_pascal}Path() }}()",
                ),
                (None, _) => format!("{plural_pascal}Path()"),
            };
            let mut inner_ctx = ctx.with_locals([pname.to_string()]);
            if let Some(record) = &record_access {
                inner_ctx
                    .form_records
                    .push((pname.to_string(), record.clone()));
            }
            let mut lines: Vec<String> = Vec::new();
            lines.push("_formBegin := len(_buf)".to_string());
            if let (Some(local), Some(record_expr)) = (&record_local, &record_ref) {
                lines.push(format!("{local} := {record_expr}"));
                lines.push(format!("_ = {local}"));
            }
            lines.push(format!(
                "{pname} := NewFormBuilder({prefix:?}, {cls_expr}, {is_persisted_expr})"
            ));
            lines.push(format!("_ = {pname}"));
            if let Some(record) = &record_access {
                lines.push(format!(
                    "_buf += ErrorMessagesFor({record}.Errors, {prefix:?})"
                ));
            }
            for line in emit_go_view_body(body, &inner_ctx) {
                lines.push(line);
            }
            lines.push(format!(
                "_buf = _buf[:_formBegin] + FormWrap({action_expr}, {is_persisted_expr}, {cls_expr}, _buf[_formBegin:])"
            ));
            lines
        }
        "content_for" => {
            let slot = args.first().and_then(go_extract_slot_name);
            let Some(slot) = slot else {
                let _ = cls_expr;
                return vec!["_buf += \"\"".to_string()];
            };
            let mut lines: Vec<String> = Vec::new();
            lines.push("_cfBegin := len(_buf)".to_string());
            for line in emit_go_view_body(body, ctx) {
                lines.push(line);
            }
            lines.push(format!("ContentForSet({slot:?}, _buf[_cfBegin:])"));
            lines.push("_buf = _buf[:_cfBegin]".to_string());
            lines
        }
        _ => {
            let _ = cls_expr;
            vec!["_buf += \"\"".to_string()]
        }
    }
}

fn go_extract_kwarg<'a>(arg: &'a Expr, key: &str) -> Option<&'a Expr> {
    if let ExprNode::Hash { entries, .. } = &*arg.node {
        for (k, v) in entries {
            if let ExprNode::Lit { value: Literal::Sym { value } } = &*k.node {
                if value.as_str() == key {
                    return Some(v);
                }
            }
        }
    }
    None
}

fn emit_go_nested_form_record(el: &Expr) -> String {
    match crate::lower::classify_nested_form_child(el) {
        Some(crate::lower::NestedFormChild::ClassNew { class }) => {
            format!("&{class}{{}}")
        }
        Some(crate::lower::NestedFormChild::Local { name }) => name.to_string(),
        None => "nil".to_string(),
    }
}

fn go_nested_form_child_prefix(el: &Expr) -> Option<String> {
    crate::lower::classify_nested_form_child(el).map(|k| k.prefix())
}

fn go_nested_element_parts(kind: &crate::lower::NestedUrlElement<'_>) -> (String, String) {
    match kind {
        crate::lower::NestedUrlElement::DirectLocal { name } => {
            ((*name).to_string(), format!("{name}.ID"))
        }
        crate::lower::NestedUrlElement::Association { owner, assoc } => {
            let fk = format!("{assoc}_id");
            let fk_field = go_field_name(&fk);
            ((*assoc).to_string(), format!("{owner}.{fk_field}"))
        }
    }
}

fn go_nested_form_path_expr(
    elems: &[Expr],
    ctx: &GoViewCtx,
    record_ref: &str,
    child_prefix: &str,
) -> String {
    let is_local = |n: &str| ctx.is_local(n);
    let mut parent_ids: Vec<String> = Vec::new();
    let mut parent_singulars: Vec<String> = Vec::new();
    for parent in &elems[..elems.len() - 1] {
        let Some(kind) = crate::lower::classify_nested_url_element(parent, &is_local) else {
            return "\"\"".to_string();
        };
        let (singular, id_expr) = go_nested_element_parts(&kind);
        parent_singulars.push(singular);
        parent_ids.push(id_expr);
    }
    // Compose PascalCase helper names. [article, comment] →
    // ArticleCommentPath (member) / ArticleCommentsPath (collection).
    let mut member_name = String::new();
    for s in &parent_singulars {
        member_name.push_str(&pascalize_word(s));
    }
    member_name.push_str(&pascalize_word(child_prefix));
    member_name.push_str("Path");
    let mut collection_name = String::new();
    for s in &parent_singulars {
        collection_name.push_str(&pascalize_word(s));
    }
    let child_plural = crate::naming::pluralize_snake(child_prefix);
    collection_name.push_str(&pascalize_word(&child_plural));
    collection_name.push_str("Path");
    let parent_args = parent_ids.join(", ");
    let member_args = if parent_args.is_empty() {
        format!("{record_ref}.ID")
    } else {
        format!("{parent_args}, {record_ref}.ID")
    };
    format!(
        "func() string {{ if {record_ref}.ID != 0 {{ return {member_name}({member_args}) }}; return {collection_name}({parent_args}) }}()"
    )
}

fn unwrap_to_s_go(expr: &Expr) -> &Expr {
    match &*expr.node {
        ExprNode::Send { recv: Some(r), method, args, .. }
            if (method.as_str() == "to_s" || method.as_str() == "to_str")
                && args.is_empty() =>
        {
            unwrap_to_s_go(r)
        }
        _ => expr,
    }
}

fn go_string_literal(s: &str) -> String {
    // Go double-quoted strings allow escape sequences; reuse Rust's
    // {:?} formatter which produces a compatible escaped form.
    format!("{s:?}")
}

#[allow(dead_code)]
fn is_go_simple_cond(expr: &Expr, ctx: &GoViewCtx) -> bool {
    is_go_simple_view_expr(expr, ctx)
}

/// True when a view-body expression is safe to render as-is.
/// Mirrors rust's `is_simple_view_expr` with Go-specific recognition
/// of partial-scope bare-Send locals and chained has_many reads.
fn is_go_simple_view_expr(expr: &Expr, ctx: &GoViewCtx) -> bool {
    match &*expr.node {
        ExprNode::Lit { .. } => true,
        ExprNode::Var { name, .. } | ExprNode::Ivar { name } => {
            ctx.is_local(name.as_str())
        }
        ExprNode::Send { recv: None, method, args, block: None, .. }
            if args.is_empty() && ctx.is_local(method.as_str()) =>
        {
            true
        }
        ExprNode::Send { recv: Some(r), method, args, block, .. } => {
            if !args.is_empty() || block.is_some() {
                return false;
            }
            let clean = method.as_str().trim_end_matches('?').trim_end_matches('!');
            if clean.is_empty() {
                return false;
            }
            let recv_local = match &*r.node {
                ExprNode::Var { name, .. } | ExprNode::Ivar { name } => Some(name.as_str()),
                ExprNode::Send {
                    recv: None,
                    method: m,
                    args: ra,
                    block: None,
                    ..
                } if ra.is_empty() && ctx.is_local(m.as_str()) => Some(m.as_str()),
                _ => None,
            };
            if let Some(local_name) = recv_local {
                if ctx.local_has_attr(local_name, clean) {
                    return true;
                }
                if ctx.is_local(local_name)
                    && matches!(method.as_str(), "any?" | "none?" | "present?" | "empty?")
                {
                    return true;
                }
                if ctx
                    .resolve_has_many_on_local(local_name, method.as_str())
                    .is_some()
                {
                    return true;
                }
            }
            if is_go_simple_view_expr(r, ctx) {
                return true;
            }
            false
        }
        ExprNode::StringInterp { parts } => parts.iter().all(|p| match p {
            crate::expr::InterpPart::Text { .. } => true,
            crate::expr::InterpPart::Expr { expr } => is_go_simple_view_expr(expr, ctx),
        }),
        _ => false,
    }
}

fn emit_go_view_expr_raw(expr: &Expr, ctx: &GoViewCtx) -> String {
    let unwrapped = unwrap_to_s_go(expr);
    match &*unwrapped.node {
        ExprNode::Lit { value: Literal::Str { value: s } } => go_string_literal(s),
        ExprNode::Lit { value: Literal::Int { value, .. } } => value.to_string(),
        ExprNode::Lit { value: Literal::Bool { value } } => value.to_string(),
        ExprNode::Var { name, .. } | ExprNode::Ivar { name } => name.to_string(),
        ExprNode::Send { recv, method, args, .. } => {
            let method_s = method.as_str();
            // Bare local ref (partial scope).
            if recv.is_none() && args.is_empty() && ctx.is_local(method_s) {
                return method_s.to_string();
            }
            if let Some(r) = recv {
                if args.is_empty() {
                    // has_many assoc read → inline filter: the target
                    // model has an emitter-generated FilterBy<FkField>
                    // method. Mirrors rust's inline filter, but Go's
                    // static types need a helper rather than a closure.
                    let owner_local = match &*r.node {
                        ExprNode::Var { name, .. } | ExprNode::Ivar { name }
                            if ctx.is_local(name.as_str()) =>
                        {
                            Some(name.as_str().to_string())
                        }
                        ExprNode::Send {
                            recv: None,
                            method: m,
                            args: ra,
                            block: None,
                            ..
                        } if ra.is_empty() && ctx.is_local(m.as_str()) => {
                            Some(m.as_str().to_string())
                        }
                        _ => None,
                    };
                    if let Some(owner) = &owner_local {
                        if let Some((target_class, fk)) =
                            ctx.resolve_has_many_on_local(owner, method_s)
                        {
                            let fk_field = go_field_name(&fk);
                            // Inline filter, matches rust's posture
                            // (`Comment::all().into_iter().filter(…)`):
                            // an IIFE iterating `{Target}All()` and
                            // collecting rows whose FK equals the
                            // owner's ID.
                            return format!(
                                "func() []*{target_class} {{ var __r []*{target_class}; for _, __c := range {target_class}All() {{ if __c.{fk_field} == {owner}.ID {{ __r = append(__r, __c) }} }}; return __r }}()",
                            );
                        }
                    }
                    // Collection predicates on any recv.
                    match method_s {
                        "any?" | "present?" => {
                            let recv_s = emit_go_view_expr_raw(r, ctx);
                            return format!("len({recv_s}) > 0");
                        }
                        "none?" | "empty?" => {
                            let recv_s = emit_go_view_expr_raw(r, ctx);
                            return format!("len({recv_s}) == 0");
                        }
                        "size" | "count" | "length" => {
                            let recv_s = emit_go_view_expr_raw(r, ctx);
                            return format!("int64(len({recv_s}))");
                        }
                        "full_message" => {
                            let recv_s = emit_go_view_expr_raw(r, ctx);
                            return format!("{recv_s}.FullMessage()");
                        }
                        _ => {}
                    }
                }
                let recv_s = emit_go_view_expr_raw(r, ctx);
                let clean = method_s.trim_end_matches('?').trim_end_matches('!');
                let go_name = go_field_name(clean);
                if args.is_empty() {
                    return format!("{recv_s}.{go_name}");
                }
                let args_s: Vec<String> = args
                    .iter()
                    .map(|a| emit_go_view_expr_raw(a, ctx))
                    .collect();
                return format!("{recv_s}.{go_name}({})", args_s.join(", "));
            }
            // No recv — emit as a helper call.
            let args_s: Vec<String> = args
                .iter()
                .map(|a| emit_go_view_expr_raw(a, ctx))
                .collect();
            let helper = pascalize_word(method_s);
            if args.is_empty() {
                format!("{helper}()")
            } else {
                format!("{helper}({})", args_s.join(", "))
            }
        }
        ExprNode::StringInterp { parts } => {
            use crate::expr::InterpPart;
            let mut fmt = String::new();
            let mut args: Vec<String> = Vec::new();
            for p in parts {
                match p {
                    InterpPart::Text { value } => {
                        for c in value.chars() {
                            if c == '%' {
                                fmt.push_str("%%");
                            } else {
                                fmt.push(c);
                            }
                        }
                    }
                    InterpPart::Expr { expr } => {
                        fmt.push_str("%v");
                        args.push(emit_go_view_expr_raw(expr, ctx));
                    }
                }
            }
            if args.is_empty() {
                go_string_literal(&fmt)
            } else {
                format!("fmt.Sprintf({}, {})", go_string_literal(&fmt), args.join(", "))
            }
        }
        _ => "\"\"".to_string(),
    }
}
