module ActiveRecord
  class InMemoryAdapter
    def initialize: () -> void
    def create_table: (Symbol name, columns: Array[Symbol], ?foreign_keys: Array[Hash[Symbol, String]]) -> void
    def drop_table: (Symbol name) -> void
    def schema: (Symbol table) -> Hash[Symbol, Array[Symbol]]?
    def insert: (Symbol table, Hash[Symbol, String] row) -> Integer
    def update: (Symbol table, Integer id, Hash[Symbol, String] row) -> bool
    def delete: (Symbol table, Integer id) -> bool
    def find: (Symbol table, Integer id) -> Hash[Symbol, String]?
    def all: (Symbol table) -> Array[Hash[Symbol, String]]
    def where: (Symbol table, Hash[Symbol, String] conditions) -> Array[Hash[Symbol, String]]
    def count: (Symbol table) -> Integer
    def exists?: (Symbol table, Integer id) -> bool
  end
end
