module ActiveRecord
  module Validations
    def errors: () -> Array[String]
    def validates_presence_of: (Symbol attr) -> void
    def validates_absence_of: (Symbol attr) -> void
    def validates_length_of: (Symbol attr, ?minimum: Integer?, ?maximum: Integer?, ?is: Integer?) -> void
    def validates_numericality_of: (Symbol attr, ?greater_than: Numeric?, ?less_than: Numeric?, ?only_integer: bool) -> void
    def validates_inclusion_of: (Symbol attr, in: Array[String]) -> void
    def validates_format_of: (Symbol attr, with: Regexp) -> void
    def validates_uniqueness_of: (Symbol attr, ?scope: Array[Symbol], ?case_sensitive: bool) -> void

    private
    def read_for_validation: (Symbol attr) -> String
    def blank?: (String? value) -> bool
  end
end
