//! Controllers + actions.
//!
//! Phase 4c: controllers emit as Python classes with one `async def`
//! per action. Action bodies render through the shared `SendKind`
//! classifier from `lower::controller`; the Python render table
//! handles HTTP surface (`http.render` / `redirect_to` / `head`),
//! `respond_to` as a lambda, params access, model / association
//! shapes, and bang stripping (Python forbids `!` in identifiers).
//!
//! Private helpers get a leading-underscore name prefix (`_set_article`)
//! so Python's unused-method warnings stay quiet — `@unittest.skip`-ped
//! controller tests never invoke them at runtime.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use super::expr::emit_expr;
use super::shared::{indent_py, is_bare_py_ident, py_view_fn};
use crate::App;
use crate::dialect::{Action, Controller};
use crate::expr::{Expr, ExprNode, LValue, Literal};
use crate::ident::Symbol;
use crate::lower::CtrlWalker as _;

/// Pass-2 controller emit — one module per controller under
/// `app/controllers/`. Each action is a module-level function
/// returning `http.ActionResponse`. The `Router` in
/// `app/http.py` resolves handlers via `getattr(module, action)`,
/// so controllers are registered by module reference rather than
/// as class-level methods.
pub(super) fn emit_controllers_pass2(app: &App) -> Vec<EmittedFile> {
    let known_models: Vec<Symbol> =
        app.models.iter().map(|m| m.name.0.clone()).collect();
    let mut files = Vec::new();
    files.push(EmittedFile {
        path: PathBuf::from("app/controllers/__init__.py"),
        content: String::new(),
    });
    for c in &app.controllers {
        files.push(emit_controller_file_pass2(c, &known_models, app));
    }
    files
}

fn emit_controller_file_pass2(
    c: &Controller,
    known_models: &[Symbol],
    app: &App,
) -> EmittedFile {
    let name = c.name.0.as_str();
    let file_stem = crate::naming::snake_case(name);
    let resource = crate::lower::resource_from_controller_name(name);
    let model_class = crate::naming::singularize_camelize(&resource);
    let has_model = known_models.iter().any(|m| m.as_str() == model_class);
    let parent = crate::lower::find_nested_parent(app, name);
    let permitted = crate::lower::permitted_fields_for(c, &resource)
        .unwrap_or_else(|| crate::lower::default_permitted_fields(app, &model_class));

    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "from __future__ import annotations").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "from app import http, views").unwrap();
    writeln!(s, "from app.route_helpers import *  # noqa: F401, F403").unwrap();
    if !known_models.is_empty() {
        writeln!(s, "from app.models import *  # noqa: F401, F403").unwrap();
    }
    writeln!(s).unwrap();

    let (public_actions, _private) = crate::lower::split_public_private(c);
    for action in &public_actions {
        let la = crate::lower::lower_action(
            action.name.as_str(),
            &resource,
            &model_class,
            has_model,
            parent.as_ref(),
            &permitted,
        );
        emit_py_action(&mut s, &la, &action.body, known_models, c);
        writeln!(s).unwrap();
    }

    EmittedFile {
        path: PathBuf::from(format!("app/controllers/{file_stem}.py")),
        content: s,
    }
}

/// Render one LoweredAction as a Python `def`. Mangles `new` to
/// `new_` (matches the router's `_resolve_handler` mapping) so the
/// action name doesn't collide with Python's `Model.new(...)`
/// idioms. Delegates body emission to the walker; the ActionKind
/// dispatch is gone (TS/Rust precedent).
fn emit_py_action(
    out: &mut String,
    la: &crate::lower::LoweredAction,
    body: &Expr,
    known_models: &[Symbol],
    controller: &Controller,
) {
    let name = if la.name == "new" { "new_" } else { la.name.as_str() };

    if !la.has_model {
        writeln!(
            out,
            "def {name}(_context: http.ActionContext) -> http.ActionResponse:"
        )
        .unwrap();
        writeln!(out, "    return http.ActionResponse(body=\"\")").unwrap();
        return;
    }

    use crate::lower::CtrlWalker;
    let normalized = crate::lower::normalize_action_body(controller, la.name.as_str(), body);
    let mut emitter = PyEmitter {
        ctx: crate::lower::WalkCtx {
            known_models,
            model_class: la.model_class.as_str(),
            resource: la.resource.as_str(),
            parent: la.parent.as_ref(),
            permitted: &la.permitted,
            adapter: &crate::adapter::SqliteAdapter,
        },
        state: crate::lower::WalkState::new(),
    };
    let body_src = emitter.walk_action_body(&normalized);
    let uses_context = emitter.state.uses_context
        || body_src.contains("context.") || body_src.contains("context[");
    let ctx_param = if uses_context { "context" } else { "_context" };
    writeln!(
        out,
        "def {name}({ctx_param}: http.ActionContext) -> http.ActionResponse:"
    )
    .unwrap();
    if body_src.is_empty() {
        writeln!(out, "    pass").unwrap();
    } else {
        out.push_str(&body_src);
    }
}

struct PyEmitter<'a> {
    ctx: crate::lower::WalkCtx<'a>,
    state: crate::lower::WalkState,
}

impl<'a> crate::lower::CtrlWalker<'a> for PyEmitter<'a> {
    fn ctx(&self) -> &crate::lower::WalkCtx<'a> { &self.ctx }
    fn state_mut(&mut self) -> &mut crate::lower::WalkState { &mut self.state }
    fn indent_unit(&self) -> &'static str { "    " }

    fn write_assign(&mut self, name: &str, value: &Expr, indent: &str, out: &mut String) {
        let rhs = self.render_expr(value);
        writeln!(out, "{indent}{name} = {rhs}").unwrap();
    }

    fn write_create_expansion(
        &mut self,
        var_name: &str,
        class: &str,
        indent: &str,
        out: &mut String,
    ) {
        writeln!(out, "{indent}{var_name} = {class}()").unwrap();
        if let Some(parent) = self.ctx.parent {
            writeln!(
                out,
                "{indent}{var_name}.{0}_id = int(context.params[\"{0}_id\"])",
                parent.singular,
            )
            .unwrap();
            self.state.uses_context = true;
        }
        let permitted: Vec<String> = self.ctx.permitted.iter().cloned().collect();
        let resource = self.ctx.resource.to_string();
        for field in &permitted {
            writeln!(
                out,
                "{indent}{var_name}.{field} = context.params.get(\"{resource}[{field}]\", \"\")",
            )
            .unwrap();
            self.state.uses_context = true;
        }
    }

    fn write_if(
        &mut self,
        cond: &Expr,
        then_branch: &Expr,
        else_branch: &Expr,
        indent: &str,
        depth: usize,
        is_tail: bool,
        out: &mut String,
    ) {
        let cond_s = self.render_expr(cond);
        writeln!(out, "{indent}if {cond_s}:").unwrap();
        self.walk_stmt(then_branch, out, depth + 1, is_tail);
        if !crate::lower::is_empty_body(else_branch) {
            writeln!(out, "{indent}else:").unwrap();
            self.walk_stmt(else_branch, out, depth + 1, is_tail);
        }
    }

    fn write_update_if(
        &mut self,
        recv: &Expr,
        then_branch: &Expr,
        else_branch: &Expr,
        indent: &str,
        depth: usize,
        is_tail: bool,
        out: &mut String,
    ) {
        let recv_s = self.render_expr(recv);
        let permitted: Vec<String> = self.ctx.permitted.iter().cloned().collect();
        let resource = self.ctx.resource.to_string();
        for field in &permitted {
            writeln!(
                out,
                "{indent}if \"{resource}[{field}]\" in context.params: {recv_s}.{field} = context.params[\"{resource}[{field}]\"]",
            )
            .unwrap();
            self.state.uses_context = true;
        }
        writeln!(out, "{indent}if {recv_s}.save():").unwrap();
        self.walk_stmt(then_branch, out, depth + 1, is_tail);
        if !crate::lower::is_empty_body(else_branch) {
            writeln!(out, "{indent}else:").unwrap();
            self.walk_stmt(else_branch, out, depth + 1, is_tail);
        }
    }

    fn write_response_stmt(&mut self, r: &str, _is_tail: bool, indent: &str, out: &mut String) {
        writeln!(out, "{indent}{r}").unwrap();
    }

    fn write_expr_stmt(&mut self, s: &str, indent: &str, out: &mut String) {
        writeln!(out, "{indent}{s}").unwrap();
    }

    fn render_expr(&mut self, expr: &Expr) -> String {
        if let ExprNode::Send { recv, method, args, block, .. } = &*expr.node {
            if let Some(stmt) = self.render_send_stmt(
                recv.as_ref(), method.as_str(), args, block.as_ref(), "",
            ) {
                return match stmt {
                    crate::lower::Stmt::Response(r) => r.trim_start_matches("return ").to_string(),
                    crate::lower::Stmt::Expr(s) => s,
                };
            }
            let args_s: Vec<String> = args.iter().map(|a| self.render_expr(a)).collect();
            return match recv {
                None if args.is_empty() => method.to_string(),
                None => format!("{method}({})", args_s.join(", ")),
                Some(r) => {
                    let recv_s = self.render_expr(r);
                    if args.is_empty() {
                        format!("{recv_s}.{method}()")
                    } else {
                        format!("{recv_s}.{method}({})", args_s.join(", "))
                    }
                }
            };
        }
        if let ExprNode::Ivar { name } = &*expr.node {
            return name.to_string();
        }
        emit_expr(expr)
    }

    fn render_send_stmt(
        &mut self,
        recv: Option<&Expr>,
        method: &str,
        args: &[Expr],
        block: Option<&Expr>,
        // Python async consumption not wired yet; prefix unused for now.
        _suspending_prefix: &str,
    ) -> Option<crate::lower::Stmt> {
        use crate::lower::{SendKind, Stmt};
        let kind = crate::lower::classify_controller_send(
            recv, method, args, block, self.ctx.known_models,
        )?;
        Some(match kind {
            SendKind::ParamsAccess => {
                self.state.uses_context = true;
                Stmt::Expr("context.params".to_string())
            }
            SendKind::ParamsIndex { key } => {
                self.state.uses_context = true;
                let key_s = match &*key.node {
                    ExprNode::Lit { value: Literal::Sym { value: s } } => {
                        format!("context.params[\"{}\"]", s.as_str())
                    }
                    _ => {
                        let k = self.render_expr(key);
                        format!("context.params[{k}]")
                    }
                };
                Stmt::Expr(format!("int({key_s})"))
            }
            SendKind::ParamsExpect { args: pe_args } => {
                self.state.uses_context = true;
                let s = match pe_args.first().map(|e| &*e.node) {
                    Some(ExprNode::Lit { value: Literal::Sym { value: k } }) => {
                        format!("int(context.params[\"{}\"])", k.as_str())
                    }
                    _ => "context.params  # TODO: params.expect hash".to_string(),
                };
                Stmt::Expr(s)
            }
            SendKind::ModelNew { class } => Stmt::Expr(format!("{}()", class.as_str())),
            SendKind::ModelFind { class, id } => {
                let id_s = self.render_expr(id);
                Stmt::Expr(format!("{0}.find({id_s}) or {0}()", class.as_str()))
            }
            SendKind::QueryChain { target: Some(target), method: chain_method, args: chain_args, recv: chain_recv } => {
                let mut out = format!("{}.all()", target.as_str());
                let mods = crate::lower::collect_chain_modifiers(chain_method, chain_args, chain_recv.as_deref());
                for m in mods {
                    out = apply_py_chain_modifier(out, m);
                }
                Stmt::Expr(out)
            }
            SendKind::QueryChain { target: None, .. } => Stmt::Expr("[]".to_string()),
            SendKind::AssocLookup { target, outer_method } => match outer_method {
                "find" => {
                    let id_s = args.first().map(|a| self.render_expr(a))
                        .unwrap_or_else(|| "0".to_string());
                    Stmt::Expr(format!("{0}.find({id_s}) or {0}()", target.as_str()))
                }
                _ => Stmt::Expr(format!("{}()", target.as_str())),
            },
            SendKind::BangStrip { recv, stripped_method, args: bs_args } => {
                let recv_s = self.render_expr(recv);
                let args_s: Vec<String> =
                    bs_args.iter().map(|a| self.render_expr(a)).collect();
                Stmt::Expr(format!("{recv_s}.{stripped_method}({})", args_s.join(", ")))
            }
            SendKind::InstanceUpdate => Stmt::Expr("False".to_string()),
            SendKind::PathOrUrlHelper => Stmt::Expr(format!("{method}()")),
            SendKind::Render { args: r_args } => Stmt::Response(self.render_py_render(r_args)),
            SendKind::RedirectTo { args: r_args } => Stmt::Response(self.render_py_redirect(r_args)),
            SendKind::Head { args: h_args } => {
                let status = h_args.first().and_then(|a| match &*a.node {
                    ExprNode::Lit { value: Literal::Sym { value: s } } =>
                        Some(crate::lower::status_sym_to_code(s.as_str())),
                    ExprNode::Lit { value: Literal::Int { value: n } } => Some(*n as u16),
                    _ => None,
                }).unwrap_or(200);
                Stmt::Response(format!("return http.ActionResponse(status={status})"))
            }
            SendKind::RespondToBlock { .. }
            | SendKind::FormatHtml { .. }
            | SendKind::FormatJson => Stmt::Expr(
                "None  # unreachable: respond_to not normalized".to_string(),
            ),
        })
    }
}

impl<'a> PyEmitter<'a> {
    fn render_py_render(&mut self, args: &[Expr]) -> String {
        if let Some(first) = args.first() {
            if let ExprNode::Lit { value: Literal::Sym { value: sym } } = &*first.node {
                let view_fn = py_view_fn(self.ctx.model_class, sym.as_str());
                let arg = self.state.last_local.clone().unwrap_or_else(|| "None".to_string());
                let body_part = format!("body=views.{view_fn}({arg})");
                return match crate::lower::extract_status_from_kwargs(&args[1..]) {
                    Some(status) => format!("return http.ActionResponse(status={status}, {body_part})"),
                    None => format!("return http.ActionResponse({body_part})"),
                };
            }
            let body_s = self.render_expr(first);
            return format!("return http.ActionResponse(body={body_s})");
        }
        "return http.ActionResponse(body=\"\")".to_string()
    }

    fn render_py_redirect(&mut self, args: &[Expr]) -> String {
        let Some(first) = args.first() else {
            return "return http.ActionResponse(status=303)".to_string();
        };
        let loc = self.render_expr(first);
        let status = crate::lower::extract_status_from_kwargs(&args[1..]).unwrap_or(303);
        if is_bare_py_ident(&loc) {
            let id_access = format!("{loc}.id");
            return format!(
                "return http.ActionResponse(status={status}, location={loc}_path({id_access}))"
            );
        }
        format!("return http.ActionResponse(status={status}, location={loc})")
    }
}


/// Compose one AR chain modifier onto a running python list
/// expression. `all`/`includes`/etc. are no-ops. `order({field:
/// :dir})` lowers to a `sorted(..., key=..., reverse=...)` wrapper.
/// `limit(N)` slices `[:N]`.
///
/// Chain-walk lives in `src/lower/chain.rs`; this fn just renders
/// one already-classified layer.
fn apply_py_chain_modifier(prev: String, m: crate::lower::ChainModifier<'_>) -> String {
    match m.method {
        "all" | "includes" | "preload" | "joins" | "distinct" | "select" => prev,
        "order" => {
            let Some(hash) = m.args.first() else { return prev };
            let ExprNode::Hash { entries, .. } = &*hash.node else { return prev };
            let Some((k, v)) = entries.first() else { return prev };
            let field = match &*k.node {
                ExprNode::Lit { value: Literal::Sym { value } } => value.as_str().to_string(),
                ExprNode::Lit { value: Literal::Str { value } } => value.clone(),
                _ => return prev,
            };
            let dir = match &*v.node {
                ExprNode::Lit { value: Literal::Sym { value } } => value.as_str().to_string(),
                ExprNode::Lit { value: Literal::Str { value } } => value.clone(),
                _ => "asc".to_string(),
            };
            let reverse = if dir == "desc" { "True" } else { "False" };
            format!(
                "sorted({prev}, key=lambda __r: __r.{field}, reverse={reverse})"
            )
        }
        "limit" => {
            let Some(n) = m.args.first() else { return prev };
            if let ExprNode::Lit { value: Literal::Int { value } } = &*n.node {
                return format!("{prev}[:{value}]");
            }
            prev
        }
        _ => prev,
    }
}

// Legacy pass-1 emit retained for any code that still references
// `emit_controllers`; the public entry point is `emit_controllers_pass2`.
#[allow(dead_code)]
fn emit_controllers(app: &App, known_models: &[Symbol]) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "from __future__ import annotations").unwrap();
    writeln!(s, "from . import http").unwrap();
    if !known_models.is_empty() {
        writeln!(s, "from .models import *  # noqa: F401, F403").unwrap();
    }
    for controller in &app.controllers {
        writeln!(s).unwrap();
        emit_controller(&mut s, controller, known_models);
    }
    EmittedFile { path: PathBuf::from("app/controllers.py"), content: s }
}

fn emit_controller(out: &mut String, c: &Controller, known_models: &[Symbol]) {
    let name = c.name.0.as_str();
    writeln!(out, "class {name}:").unwrap();

    let (public_actions, private_actions) = crate::lower::split_public_private(c);
    if public_actions.is_empty() && private_actions.is_empty() {
        writeln!(out, "    pass").unwrap();
        return;
    }

    let ctx = PyCtrlCtx { known_models };

    let mut first = true;
    for action in &public_actions {
        if !first {
            writeln!(out).unwrap();
        }
        first = false;
        emit_action(out, action, &ctx, false);
    }
    for action in &private_actions {
        if !first {
            writeln!(out).unwrap();
        }
        first = false;
        emit_action(out, action, &ctx, true);
    }
}

fn emit_action(out: &mut String, a: &Action, ctx: &PyCtrlCtx, private: bool) {
    let raw = a.name.as_str();
    // Private helpers get a leading `_` — Python convention for
    // "internal to the class." Public actions keep their Rails name.
    let rendered_name = if private {
        format!("_{raw}")
    } else {
        raw.to_string()
    };
    writeln!(out, "    async def {rendered_name}(self):").unwrap();

    // Prime before_action ivars: any `@foo` the body reads without
    // first assigning gets `self.foo = Foo()` at the top. Same
    // posture as the other Phase-4c targets.
    let walked = crate::lower::walk_controller_ivars(&a.body);
    let primed_ivars = walked.ivars_read_without_assign();
    for ivar in &primed_ivars {
        let default = py_ivar_default(ivar.as_str(), ctx.known_models);
        writeln!(out, "        self.{} = {default}", ivar.as_str()).unwrap();
    }

    let body_text = emit_py_controller_body(&a.body, ctx);
    if body_text.is_empty() && primed_ivars.is_empty() {
        writeln!(out, "        pass").unwrap();
    } else {
        for line in body_text.lines() {
            if line.is_empty() {
                writeln!(out).unwrap();
            } else {
                writeln!(out, "        {line}").unwrap();
            }
        }
    }
}

/// Python default value for a controller action's primed ivar.
/// Singular known model → `Model()`, plural → `[]`, unresolved →
/// `None`.
fn py_ivar_default(name: &str, known_models: &[Symbol]) -> String {
    let singular_class = crate::naming::singularize_camelize(name);
    let is_plural = singular_class.to_lowercase() != name.to_lowercase();
    if known_models.iter().any(|m| m.as_str() == singular_class) {
        if is_plural {
            return "[]".to_string();
        }
        return format!("{singular_class}()");
    }
    "None".to_string()
}

#[derive(Clone, Copy)]
struct PyCtrlCtx<'a> {
    known_models: &'a [Symbol],
}

/// Emit a controller action body as Python statements. Ivar writes
/// land as `self.foo = expr`; expression statements terminate with a
/// newline (Python doesn't use `;`).
fn emit_py_controller_body(body: &Expr, ctx: &PyCtrlCtx) -> String {
    match &*body.node {
        ExprNode::Seq { exprs } if exprs.is_empty() => String::new(),
        ExprNode::Seq { exprs } => exprs
            .iter()
            .map(|e| emit_py_controller_stmt(e, ctx))
            .collect::<Vec<_>>()
            .join("\n"),
        _ => emit_py_controller_stmt(body, ctx),
    }
}

fn emit_py_controller_stmt(e: &Expr, ctx: &PyCtrlCtx) -> String {
    match &*e.node {
        ExprNode::Assign { target: LValue::Var { name, .. }, value } => {
            format!("{} = {}", name, emit_py_controller_expr(value, ctx))
        }
        ExprNode::Assign { target: LValue::Ivar { name }, value } => {
            format!("self.{} = {}", name, emit_py_controller_expr(value, ctx))
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            let cond_s = emit_py_controller_expr(cond, ctx);
            let then_s = emit_py_block_body(then_branch, ctx);
            let else_s = emit_py_block_body(else_branch, ctx);
            format!("if {cond_s}:\n{}\nelse:\n{}", indent_py(&then_s), indent_py(&else_s))
        }
        _ => emit_py_controller_expr(e, ctx),
    }
}

fn emit_py_controller_expr(e: &Expr, ctx: &PyCtrlCtx) -> String {
    match &*e.node {
        ExprNode::Send { recv, method, args, block, .. } => {
            if let Some(s) = emit_py_controller_send(
                recv.as_ref(),
                method.as_str(),
                args,
                block.as_ref(),
                ctx,
            ) {
                return s;
            }
            // Fall through to generic emit_expr for unclassified
            // Sends, but re-render args/recv with ctx-aware dispatch
            // so nested rewrites apply.
            let args_s: Vec<String> = args
                .iter()
                .map(|a| emit_py_controller_expr(a, ctx))
                .collect();
            match recv {
                None => {
                    if args.is_empty() {
                        method.to_string()
                    } else {
                        format!("{}({})", method, args_s.join(", "))
                    }
                }
                Some(r) => {
                    let recv_s = emit_py_controller_expr(r, ctx);
                    if args.is_empty() {
                        format!("{recv_s}.{method}()")
                    } else {
                        format!("{recv_s}.{method}({})", args_s.join(", "))
                    }
                }
            }
        }
        ExprNode::Ivar { name } => format!("self.{name}"),
        _ => emit_expr(e),
    }
}

fn emit_py_block_body(e: &Expr, ctx: &PyCtrlCtx) -> String {
    let body = match &*e.node {
        ExprNode::Lambda { body, .. } => body,
        _ => e,
    };
    match &*body.node {
        ExprNode::Seq { exprs } if !exprs.is_empty() => exprs
            .iter()
            .map(|s| emit_py_controller_stmt(s, ctx))
            .collect::<Vec<_>>()
            .join("\n"),
        _ => emit_py_controller_stmt(body, ctx),
    }
}

/// Python render table over `SendKind` from `lower::controller`.
fn emit_py_controller_send(
    recv: Option<&Expr>,
    method: &str,
    args: &[Expr],
    block: Option<&Expr>,
    ctx: &PyCtrlCtx,
) -> Option<String> {
    use crate::lower::SendKind;
    let args_s: Vec<String> =
        args.iter().map(|a| emit_py_controller_expr(a, ctx)).collect();

    let kind = crate::lower::classify_controller_send(
        recv,
        method,
        args,
        block,
        ctx.known_models,
    )?;
    Some(match kind {
        SendKind::ParamsAccess => "http.params()".to_string(),
        SendKind::ParamsExpect { .. } => {
            format!("http.params().expect({})", args_s.join(", "))
        }
        SendKind::ParamsIndex { .. } => {
            let arg = args_s.first().cloned().unwrap_or_default();
            format!("http.params()[{arg}]")
        }

        SendKind::ModelNew { class } => format!("{}()", class.as_str()),

        SendKind::ModelFind { class, .. } => {
            // Python `Model.find(x)` may return None; the declared
            // Phase-4c flow doesn't unwrap since actions never run.
            let arg = args_s.first().cloned().unwrap_or_default();
            format!("{}.find({arg})", class.as_str())
        }

        SendKind::AssocLookup { target, .. } => format!("{}()", target.as_str()),

        SendKind::QueryChain { target: Some(target), .. } => {
            // List comprehension would be idiomatic later; for 4c a
            // bare empty list with a comment preserves the target
            // hint. Same rationale discussed for TS's `[] as Post[]`.
            format!("[]  # {}[] placeholder", target.as_str())
        }
        SendKind::QueryChain { target: None, .. } => "[]".to_string(),

        SendKind::PathOrUrlHelper => "\"\"".to_string(),

        SendKind::BangStrip { recv, stripped_method, .. } => {
            // Python forbids `!` in identifiers. Strip like Rust / Go
            // / Elixir / TS do. No parens-vs-none distinction: Python
            // methods always require `()`, so emit as a call.
            let recv_s = emit_py_controller_expr(recv, ctx);
            format!("{recv_s}.{stripped_method}()")
        }

        SendKind::InstanceUpdate => "False".to_string(),

        SendKind::Render { .. } => format!("http.render({})", args_s.join(", ")),
        SendKind::RedirectTo { .. } => {
            format!("http.redirect_to({})", args_s.join(", "))
        }
        SendKind::Head { .. } => format!("http.head({})", args_s.join(", ")),

        // Python lambdas can't hold statements, and `respond_to` /
        // `format.html` block bodies contain if/else control flow.
        // Flatten inline like Elixir: the HTML branch body emits
        // directly at the call site; the JSON branch becomes a TODO
        // comment. The `http.respond_to` / `fr.html` stubs stay
        // callable for hand-written code that wants the real shape.
        SendKind::RespondToBlock { body } => emit_py_block_body(body, ctx),

        SendKind::FormatHtml { body } => emit_py_block_body(body, ctx),

        SendKind::FormatJson => "# TODO: JSON branch (Phase 4e)".to_string(),
    })
}
