//! Test fixtures — emits `tests/fixtures.py` with one record-loader
//! per fixture set.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use super::ty::py_literal_for;
use crate::App;

pub(super) fn emit_py_fixtures(app: &App) -> EmittedFile {
    let lowered = crate::lower::lower_fixtures(app);
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "from __future__ import annotations").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "from app import db").unwrap();
    writeln!(s, "from app.schema_sql import CREATE_TABLES").unwrap();
    writeln!(s, "from app.models import {}", app
        .models
        .iter()
        .map(|m| m.name.0.as_str().to_string())
        .collect::<Vec<_>>()
        .join(", ")).unwrap();

    writeln!(s).unwrap();
    writeln!(s, "FIXTURE_IDS: dict[tuple[str, str], int] = {{}}").unwrap();

    // Fixtures.setup — called from each TestCase's setUp. Opens a
    // fresh :memory: DB, runs schema DDL, clears the fixture id
    // map, and reloads all fixtures in declaration order.
    writeln!(s).unwrap();
    writeln!(s, "def setup() -> None:").unwrap();
    writeln!(s, "    db.setup_test_db(CREATE_TABLES)").unwrap();
    writeln!(s, "    FIXTURE_IDS.clear()").unwrap();
    for f in &lowered.fixtures {
        let ns = f.name.as_str();
        writeln!(s, "    {ns}_load_all()").unwrap();
    }

    writeln!(s).unwrap();
    writeln!(s, "def fixture_id(fixture: str, label: str) -> int:").unwrap();
    writeln!(s, "    key = (fixture, label)").unwrap();
    writeln!(s, "    if key not in FIXTURE_IDS:").unwrap();
    writeln!(s, "        raise RuntimeError(f\"fixture {{fixture}}/{{label}} not loaded\")").unwrap();
    writeln!(s, "    return FIXTURE_IDS[key]").unwrap();

    for fixture in &lowered.fixtures {
        let class_name = fixture.class.0.as_str();
        let ns = fixture.name.as_str();

        // <ns>_load_all — insert each record via Class.save (which
        // runs validate + INSERT) then capture the assigned id via
        // the mutated self.id attribute.
        writeln!(s).unwrap();
        writeln!(s, "def {ns}_load_all() -> None:").unwrap();
        for record in &fixture.records {
            let label = record.label.as_str();
            let kwargs: Vec<String> = record
                .fields
                .iter()
                .map(|f| {
                    let col = f.column.as_str();
                    let val = match &f.value {
                        crate::lower::LoweredFixtureValue::Literal { ty, raw } => {
                            py_literal_for(raw, ty)
                        }
                        crate::lower::LoweredFixtureValue::FkLookup {
                            target_fixture,
                            target_label,
                        } => format!(
                            "fixture_id({:?}, {:?})",
                            target_fixture.as_str(),
                            target_label.as_str(),
                        ),
                    };
                    format!("        {col}={val}")
                })
                .collect();
            writeln!(s, "    r = {class_name}(").unwrap();
            writeln!(s, "{}", kwargs.join(",\n")).unwrap();
            writeln!(s, "    )").unwrap();
            writeln!(
                s,
                "    if not r.save():\n        raise RuntimeError(\"fixture {ns}/{label} failed to save\")"
            )
            .unwrap();
            writeln!(
                s,
                "    FIXTURE_IDS[({ns:?}, {label:?})] = r.id",
            )
            .unwrap();
        }

        // Named-record getters — lookup id + Class.find.
        for record in &fixture.records {
            let label = record.label.as_str();
            writeln!(s).unwrap();
            writeln!(s, "def {ns}_{label}() -> {class_name}:").unwrap();
            writeln!(s, "    id = fixture_id({ns:?}, {label:?})").unwrap();
            writeln!(s, "    record = {class_name}.find(id)").unwrap();
            writeln!(
                s,
                "    if record is None:\n        raise RuntimeError(\"fixture {ns}/{label} not loaded\")"
            )
            .unwrap();
            writeln!(s, "    return record").unwrap();
        }
    }

    EmittedFile {
        path: PathBuf::from("tests/fixtures.py"),
        content: s,
    }
}
