//! Importmap — emits `app/importmap.py`.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use crate::App;

/// Emit `app/importmap.py` — a flat `PINS` list of `(name, path)`
/// tuples ingested from config/importmap.rb, consumed by the
/// layout's `javascript_importmap_tags` helper. Mirrors
/// `emit_rust_importmap` / the TS twin.
pub(super) fn emit_py_importmap(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "from __future__ import annotations").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "PINS: list[tuple[str, str]] = [").unwrap();
    if let Some(importmap) = &app.importmap {
        for pin in &importmap.pins {
            writeln!(s, "    ({:?}, {:?}),", pin.name, pin.path).unwrap();
        }
    }
    writeln!(s, "]").unwrap();
    EmittedFile {
        path: PathBuf::from("app/importmap.py"),
        content: s,
    }
}
