//! Entry point — emits `app/__main__.py`.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use crate::App;
use crate::dialect::Model;

/// Emit `app/__main__.py` — the `python -m app` entry point that
/// the compare driver invokes. Opens the DB, imports routes (which
/// registers them with the Router), registers a partial renderer
/// for each model that broadcasts (so `cable.broadcast_*_to` can
/// reach the emitted view), and calls `server.start` with the
/// emitted layout renderer when one exists.
pub(super) fn emit_py_main(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "from __future__ import annotations").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "from app import server").unwrap();
    writeln!(s, "from app.schema_sql import CREATE_TABLES").unwrap();
    writeln!(s, "from app import routes as _routes  # noqa: F401").unwrap();
    // Import views module so its side-effect imports (models,
    // view_helpers) are satisfied and the layout fn is bound.
    let has_layout = app
        .views
        .iter()
        .any(|v| v.name.as_str() == "layouts/application");
    if !app.views.is_empty() {
        writeln!(s, "from app import views").unwrap();
    }

    // Models that broadcast need a partial renderer registered so
    // `cable.broadcast_{prepend,append,replace}_to` can reach the
    // emitted view. Partial fn names follow Python view emission:
    // `render_<plural>_<singular>` (e.g. `render_articles_article`).
    let broadcasting_models: Vec<&Model> = app
        .models
        .iter()
        .filter(|m| !crate::lower::lower_broadcasts(m).is_empty())
        .collect();
    if !broadcasting_models.is_empty() {
        writeln!(s, "from app import cable").unwrap();
        writeln!(s, "from app import models as _models").unwrap();
    }

    writeln!(s).unwrap();
    writeln!(s, "def main() -> None:").unwrap();
    for model in &broadcasting_models {
        let class = model.name.0.as_str();
        let singular = crate::naming::snake_case(class);
        let plural = crate::naming::pluralize_snake(class);
        // Register a closure that finds the record and renders its
        // partial. The closure is a `def` (not lambda) so the
        // interpreter reports a real frame if rendering raises.
        writeln!(s, "    def _render_{singular}_partial(id: int) -> str:").unwrap();
        writeln!(s, "        record = _models.{class}.find(id)").unwrap();
        writeln!(s, "        if record is None:").unwrap();
        writeln!(s, "            return \"\"").unwrap();
        writeln!(s, "        return views.render_{plural}_{singular}(record)").unwrap();
        writeln!(s, "    cable.register_partial({class:?}, _render_{singular}_partial)").unwrap();
    }
    if has_layout {
        writeln!(
            s,
            "    server.start(schema_sql=CREATE_TABLES, layout=lambda: views.render_layouts_application(None))"
        )
        .unwrap();
    } else {
        writeln!(s, "    server.start(schema_sql=CREATE_TABLES)").unwrap();
    }
    writeln!(s).unwrap();
    writeln!(s, "if __name__ == \"__main__\":").unwrap();
    writeln!(s, "    main()").unwrap();
    EmittedFile {
        path: PathBuf::from("app/__main__.py"),
        content: s,
    }
}
