//! Models — class definitions, persistence methods, validations,
//! and broadcaster helpers.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use super::expr::emit_body;
use super::shared::first_param;
use super::ty::{python_default, python_ty};
use crate::App;
use crate::dialect::{MethodDef, Model};
use crate::expr::{Expr, ExprNode, InterpPart, LValue, Literal};
use crate::ident::Symbol;
use crate::lower::{BroadcastAction, LoweredBroadcast, LoweredBroadcasts};
use crate::ty::Ty;

// Models ---------------------------------------------------------------

pub(super) fn emit_models(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "from __future__ import annotations").unwrap();
    let any_validations = app
        .models
        .iter()
        .any(|m| !crate::lower::lower_validations(m).is_empty());
    if any_validations {
        writeln!(s).unwrap();
        writeln!(s, "from app.runtime import ValidationError").unwrap();
    }
    for model in &app.models {
        writeln!(s).unwrap();
        emit_model(&mut s, model, app);
    }
    EmittedFile { path: PathBuf::from("app/models.py"), content: s }
}

fn emit_model(out: &mut String, model: &Model, app: &App) {
    let name = model.name.0.as_str();
    writeln!(out, "class {name}:").unwrap();
    let has_fields = !model.attributes.fields.is_empty();
    let has_methods = model.methods().next().is_some();
    let lowered = crate::lower::lower_validations(model);
    if !has_fields && !has_methods && lowered.is_empty() {
        writeln!(out, "    pass").unwrap();
        return;
    }
    // Class-level type hints (documentation; not assigned).
    for (field, ty) in &model.attributes.fields {
        writeln!(out, "    {}: {}", field, python_ty(ty)).unwrap();
    }
    if has_fields {
        // Instance constructor: `Article(title="X", body="Y")` assigns
        // each kwarg to self, defaulting missing fields to type-
        // appropriate zero values so bare `Article()` also works.
        writeln!(out).unwrap();
        writeln!(out, "    def __init__(self, **kwargs):").unwrap();
        for (field, ty) in &model.attributes.fields {
            let fname = field.as_str();
            writeln!(
                out,
                "        self.{fname} = kwargs.get({fname:?}, {})",
                python_default(ty)
            )
            .unwrap();
        }
        // Validation-error state — views read `.errors[:field].any?`
        // to drive conditional input styling; `error_messages_for`
        // reads the list. Default empty, populated by a failed
        // `save()`.
        writeln!(out, "        self.errors: list[ValidationError] = []").unwrap();
    }
    let model_attrs: Vec<Symbol> = model.attributes.fields.keys().cloned().collect();
    for method in model.methods() {
        writeln!(out).unwrap();
        emit_model_method_with_attrs(out, method, &model_attrs);
    }
    if !lowered.is_empty() {
        writeln!(out).unwrap();
        emit_validate_method_py(out, &lowered);
    }
    // Skip persistence for abstract models (no columns beyond id).
    let has_table = model
        .attributes
        .fields
        .keys()
        .any(|k| k.as_str() != "id");
    if has_table {
        let broadcasts = crate::lower::lower_broadcasts(model);
        emit_persistence_methods_py(
            out,
            model,
            !lowered.is_empty(),
            app,
            !broadcasts.is_empty(),
        );
        if !broadcasts.is_empty() {
            let lp = crate::lower::lower_persistence(model, app);
            emit_py_broadcaster_methods(
                out,
                lp.class.0.as_str(),
                lp.table.as_str(),
                &broadcasts,
            );
        }
    }
}

// ── Broadcaster emission ───────────────────────────────────────
//
// Broadcast declarations are parsed in `lower::broadcasts`; this
// section renders them as Python. The generated model gets two
// helper methods — `_broadcast_after_save` and
// `_broadcast_after_delete` — invoked from save/destroy. Each
// broadcast call targets `app.cable.broadcast_*_to` (the hand-
// written runtime). `broadcasts_to` with a channel-lambda that
// references the record's fields (e.g. `"article_#{c.article_id}
// _comments"`) lowers to an f-string whose bare param references
// become `self.field` access.

/// Emit the two `_broadcast_after_save` / `_broadcast_after_delete`
/// helper methods into the class body. Assumes the model is
/// non-empty (caller checks `broadcasts.is_empty()`).
fn emit_py_broadcaster_methods(
    out: &mut String,
    class: &str,
    table: &str,
    decls: &LoweredBroadcasts,
) {
    writeln!(out).unwrap();
    writeln!(out, "    def _broadcast_after_save(self) -> None:").unwrap();
    writeln!(out, "        from app import cable").unwrap();
    if decls.save.is_empty() {
        writeln!(out, "        pass").unwrap();
    } else {
        for b in &decls.save {
            emit_py_one_broadcast_call(out, class, table, b);
        }
    }

    writeln!(out).unwrap();
    writeln!(out, "    def _broadcast_after_delete(self) -> None:").unwrap();
    writeln!(out, "        from app import cable").unwrap();
    if decls.destroy.is_empty() {
        writeln!(out, "        pass").unwrap();
    } else {
        for b in &decls.destroy {
            emit_py_one_broadcast_call(out, class, table, b);
        }
    }
}

fn emit_py_one_broadcast_call(
    out: &mut String,
    class: &str,
    table: &str,
    b: &LoweredBroadcast,
) {
    let channel = py_render_broadcast_expr(&b.channel, b.self_param.as_ref());
    let target = b
        .target
        .as_ref()
        .map(|t| py_render_broadcast_expr(t, b.self_param.as_ref()))
        .unwrap_or_else(|| "\"\"".to_string());
    if let Some(assoc) = &b.on_association {
        // `<parent>.broadcast_*_to(channel)` — resolve parent via
        // belongs_to foreign key, fire on it. `if parent is not None`
        // swallows orphans and missing-record cases (matches the
        // seeding `rescue nil` intent).
        let var = assoc.name.as_str();
        let target_class = assoc.target_class.as_str();
        let target_table = assoc.target_table.as_str();
        let fk = assoc.foreign_key.as_str();
        writeln!(
            out,
            "        {var} = {target_class}.find(self.{fk})"
        )
        .unwrap();
        writeln!(out, "        if {var} is not None:").unwrap();
        if b.action == BroadcastAction::Remove {
            writeln!(
                out,
                "            cable.broadcast_remove_to({target_table:?}, {var}.id, {channel}, {target})",
            )
            .unwrap();
        } else {
            let func = py_action_fn(b.action);
            writeln!(
                out,
                "            cable.{func}({target_table:?}, {var}.id, {target_class:?}, {channel}, {target})",
            )
            .unwrap();
        }
        return;
    }
    if b.action == BroadcastAction::Remove {
        writeln!(
            out,
            "        cable.broadcast_remove_to({table:?}, self.id, {channel}, {target})",
        )
        .unwrap();
    } else {
        let func = py_action_fn(b.action);
        writeln!(
            out,
            "        cable.{func}({table:?}, self.id, {class:?}, {channel}, {target})",
        )
        .unwrap();
    }
}

fn py_action_fn(action: BroadcastAction) -> &'static str {
    match action {
        BroadcastAction::Prepend => "broadcast_prepend_to",
        BroadcastAction::Append => "broadcast_append_to",
        BroadcastAction::Replace => "broadcast_replace_to",
        BroadcastAction::Remove => "broadcast_remove_to",
    }
}

/// Render a broadcast channel/target expression as a Python
/// expression. Bare string literals → `"str"`, interpolated
/// strings → f-strings, `<self_param>.field` references rewritten
/// to `self.field`. Falls through to `None` for shapes we haven't
/// taught the emitter — the resulting `cable.broadcast_*_to(...,
/// None, ...)` would crash at runtime, making the miss visible
/// rather than silently producing wrong output.
fn py_render_broadcast_expr(expr: &Expr, self_param: Option<&Symbol>) -> String {
    let p = self_param.map(|s| s.as_str());
    match &*expr.node {
        ExprNode::Lit {
            value: Literal::Str { value },
        } => format!("{value:?}"),
        ExprNode::Lit {
            value: Literal::Int { value },
        } => format!("{value}"),
        ExprNode::Var { name, .. } => {
            if let Some(pname) = p {
                let stripped = pname.strip_prefix('_').unwrap_or(pname);
                if name.as_str() == pname || name.as_str() == stripped {
                    return "self".to_string();
                }
            }
            name.as_str().to_string()
        }
        ExprNode::Send {
            recv: Some(r),
            method,
            ..
        } => {
            let recv_s = py_render_broadcast_expr(r, self_param);
            format!("{recv_s}.{}", method.as_str())
        }
        ExprNode::StringInterp { parts } => {
            // Build a Python f-string. Text runs are embedded
            // verbatim (with `{` / `}` escaped as `{{` / `}}`),
            // Expr parts become `{<rendered>}`.
            let mut out = String::from("f\"");
            for part in parts {
                match part {
                    InterpPart::Text { value } => {
                        for c in value.chars() {
                            match c {
                                '{' => out.push_str("{{"),
                                '}' => out.push_str("}}"),
                                '\\' => out.push_str("\\\\"),
                                '"' => out.push_str("\\\""),
                                '\n' => out.push_str("\\n"),
                                '\r' => out.push_str("\\r"),
                                '\t' => out.push_str("\\t"),
                                _ => out.push(c),
                            }
                        }
                    }
                    InterpPart::Expr { expr } => {
                        out.push('{');
                        out.push_str(&py_render_broadcast_expr(expr, self_param));
                        out.push('}');
                    }
                }
            }
            out.push('"');
            out
        }
        _ => "None".to_string(),
    }
}

/// Render save/destroy/count/find for a model against the stdlib
/// `sqlite3`-backed test connection. Save/destroy are instance
/// methods; count/find are classmethods. When `has_broadcasts` is
/// true, the generated save/destroy call the class's
/// `_broadcast_after_save` / `_broadcast_after_delete` helpers
/// (emitted separately by `emit_py_broadcaster_methods`).
fn emit_persistence_methods_py(
    out: &mut String,
    model: &Model,
    has_validate: bool,
    app: &App,
    has_broadcasts: bool,
) {
    let lp = crate::lower::lower_persistence(model, app);
    let class = lp.class.0.as_str();

    let insert_sql = positional_placeholders_py(&lp.insert_sql);
    let update_sql = positional_placeholders_py(&lp.update_sql);
    let delete_sql = positional_placeholders_py(&lp.delete_sql);
    let select_by_id_sql = positional_placeholders_py(&lp.select_by_id_sql);

    let non_id_args: Vec<String> = lp
        .non_id_columns
        .iter()
        .map(|s| format!("self.{}", s.as_str()))
        .collect();

    // ----- save -----
    writeln!(out).unwrap();
    writeln!(out, "    def save(self) -> bool:").unwrap();
    if has_validate {
        writeln!(out, "        errs = self.validate()").unwrap();
        writeln!(out, "        if errs:").unwrap();
        writeln!(out, "            self.errors = errs").unwrap();
        writeln!(out, "            return False").unwrap();
        writeln!(out, "        self.errors = []").unwrap();
    }
    for check in &lp.belongs_to_checks {
        let fk = check.foreign_key.as_str();
        let target = check.target_class.0.as_str();
        writeln!(
            out,
            "        if not self.{fk} or {target}.find(self.{fk}) is None:",
        )
        .unwrap();
        writeln!(out, "            return False").unwrap();
    }
    writeln!(out, "        from app import db").unwrap();
    writeln!(out, "        if not self.id:").unwrap();
    writeln!(
        out,
        "            self.id = db.execute(\n                {insert_sql:?},\n                [{}],\n            )",
        non_id_args.join(", "),
    )
    .unwrap();
    writeln!(out, "        else:").unwrap();
    writeln!(
        out,
        "            db.execute(\n                {update_sql:?},\n                [{}, self.id],\n            )",
        non_id_args.join(", "),
    )
    .unwrap();
    if has_broadcasts {
        writeln!(out, "        self._broadcast_after_save()").unwrap();
    }
    writeln!(out, "        return True").unwrap();

    // ----- destroy -----
    writeln!(out).unwrap();
    writeln!(out, "    def destroy(self) -> None:").unwrap();
    writeln!(out, "        from app import db").unwrap();
    for dc in &lp.dependent_children {
        let child_class = dc.child_class.0.as_str();
        let child_select = positional_placeholders_py(&dc.select_by_parent_sql);
        writeln!(
            out,
            "        children = db.query_all({child_select:?}, [self.id])",
        )
        .unwrap();
        writeln!(out, "        for row in children:").unwrap();
        writeln!(out, "            child = {child_class}(").unwrap();
        let kw: Vec<String> = dc
            .child_columns
            .iter()
            .map(|c| format!("                {0}=row[{0:?}]", c.as_str()))
            .collect();
        writeln!(out, "{}", kw.join(",\n")).unwrap();
        writeln!(out, "            )").unwrap();
        writeln!(out, "            child.destroy()").unwrap();
    }
    writeln!(
        out,
        "        db.execute({delete_sql:?}, [self.id])",
    )
    .unwrap();
    if has_broadcasts {
        writeln!(out, "        self._broadcast_after_delete()").unwrap();
    }

    // ----- count -----
    writeln!(out).unwrap();
    writeln!(out, "    @classmethod").unwrap();
    writeln!(out, "    def count(cls) -> int:").unwrap();
    writeln!(out, "        from app import db").unwrap();
    writeln!(
        out,
        "        return db.scalar({:?}) or 0",
        lp.count_sql,
    )
    .unwrap();

    // ----- find -----
    writeln!(out).unwrap();
    writeln!(out, "    @classmethod").unwrap();
    writeln!(out, "    def find(cls, id: int) -> {class} | None:").unwrap();
    writeln!(out, "        from app import db").unwrap();
    writeln!(
        out,
        "        row = db.query_one({select_by_id_sql:?}, [id])",
    )
    .unwrap();
    writeln!(out, "        if row is None:").unwrap();
    writeln!(out, "            return None").unwrap();
    writeln!(out, "        return cls(").unwrap();
    let kw: Vec<String> = lp
        .columns
        .iter()
        .map(|c| format!("            {0}=row[{0:?}]", c.as_str()))
        .collect();
    writeln!(out, "{}", kw.join(",\n")).unwrap();
    writeln!(out, "        )").unwrap();

    // ----- all -----
    let select_all_sql = positional_placeholders_py(&lp.select_all_sql);
    writeln!(out).unwrap();
    writeln!(out, "    @classmethod").unwrap();
    writeln!(out, "    def all(cls) -> list[{class}]:").unwrap();
    writeln!(out, "        from app import db").unwrap();
    writeln!(out, "        rows = db.query_all({select_all_sql:?})").unwrap();
    writeln!(out, "        return [cls(").unwrap();
    writeln!(out, "{}", kw.join(",\n")).unwrap();
    writeln!(out, "        ) for row in rows]").unwrap();

    // ----- last -----
    let select_last_sql = positional_placeholders_py(&lp.select_last_sql);
    writeln!(out).unwrap();
    writeln!(out, "    @classmethod").unwrap();
    writeln!(out, "    def last(cls) -> {class} | None:").unwrap();
    writeln!(out, "        from app import db").unwrap();
    writeln!(out, "        row = db.query_one({select_last_sql:?})").unwrap();
    writeln!(out, "        if row is None:").unwrap();
    writeln!(out, "            return None").unwrap();
    writeln!(out, "        return cls(").unwrap();
    writeln!(out, "{}", kw.join(",\n")).unwrap();
    writeln!(out, "        )").unwrap();

    // ----- reload -----
    writeln!(out).unwrap();
    writeln!(out, "    def reload(self) -> None:").unwrap();
    writeln!(out, "        fresh = type(self).find(self.id)").unwrap();
    writeln!(out, "        if fresh is not None:").unwrap();
    for col in &lp.columns {
        writeln!(out, "            self.{0} = fresh.{0}", col.as_str()).unwrap();
    }

    // ----- has_many associations as property accessors -----
    for dc in &lp.dependent_children {
        let child_class = dc.child_class.0.as_str();
        let assoc = crate::naming::pluralize_snake(child_class);
        let child_select = positional_placeholders_py(&dc.select_by_parent_sql);
        writeln!(out).unwrap();
        writeln!(out, "    @property").unwrap();
        writeln!(out, "    def {assoc}(self) -> list[{child_class}]:").unwrap();
        writeln!(out, "        from app import db").unwrap();
        writeln!(out, "        rows = db.query_all({child_select:?}, [self.id])").unwrap();
        let ckw: Vec<String> = dc
            .child_columns
            .iter()
            .map(|c| format!("            {0}=row[{0:?}]", c.as_str()))
            .collect();
        writeln!(out, "        return [{child_class}(").unwrap();
        writeln!(out, "{}", ckw.join(",\n")).unwrap();
        writeln!(out, "        ) for row in rows]").unwrap();
    }
}

/// SQLite `?N` → Python's stdlib sqlite3 positional `?`. Same
/// workaround as Crystal / Go / TS / Elixir.
fn positional_placeholders_py(sql: &str) -> String {
    let mut out = String::new();
    let chars: Vec<char> = sql.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        if chars[i] == '?' {
            out.push('?');
            i += 1;
            while i < chars.len() && chars[i].is_ascii_digit() {
                i += 1;
            }
        } else {
            out.push(chars[i]);
            i += 1;
        }
    }
    out
}

fn emit_validate_method_py(
    out: &mut String,
    validations: &[crate::lower::LoweredValidation],
) {
    writeln!(out, "    def validate(self) -> list[ValidationError]:").unwrap();
    writeln!(out, "        errors: list[ValidationError] = []").unwrap();
    for lv in validations {
        for check in &lv.checks {
            emit_check_inline_py(out, lv.attribute.as_str(), check);
        }
    }
    writeln!(out, "        return errors").unwrap();
}

fn emit_check_inline_py(out: &mut String, attr: &str, check: &crate::lower::Check) {
    use crate::lower::Check;
    let msg = check.default_message();
    let push = |cond: &str| -> String {
        format!(
            "        if {cond}:\n            errors.append(ValidationError({attr:?}, {msg:?}))"
        )
    };
    let block = match check {
        Check::Presence => push(&format!("not self.{attr}")),
        Check::Absence => push(&format!("self.{attr}")),
        Check::MinLength { n } => push(&format!("len(self.{attr}) < {n}")),
        Check::MaxLength { n } => push(&format!("len(self.{attr}) > {n}")),
        Check::GreaterThan { threshold } => push(&format!("self.{attr} <= {threshold}")),
        Check::LessThan { threshold } => push(&format!("self.{attr} >= {threshold}")),
        Check::OnlyInteger => {
            format!("        # OnlyInteger on {attr:?} — type hint documents, Python doesn't enforce")
        }
        Check::Inclusion { values } => {
            let parts: Vec<String> = values.iter().map(inclusion_value_to_py).collect();
            push(&format!("self.{attr} not in [{}]", parts.join(", ")))
        }
        Check::Format { pattern } => {
            format!("        # TODO: Format check on {attr:?} requires re module ({pattern:?})")
        }
        Check::Uniqueness { .. } => {
            format!("        # TODO: Uniqueness on {attr:?} requires DB access at runtime")
        }
        Check::Custom { method } => {
            format!("        self.{method}(errors)", method = method.as_str())
        }
    };
    writeln!(out, "{block}").unwrap();
}

fn inclusion_value_to_py(v: &crate::lower::InclusionValue) -> String {
    use crate::lower::InclusionValue;
    match v {
        InclusionValue::Str { value } => format!("{value:?}"),
        InclusionValue::Int { value } => value.to_string(),
        InclusionValue::Float { value } => {
            let s = value.to_string();
            if s.contains('.') { s } else { format!("{s}.0") }
        }
        InclusionValue::Bool { value } => {
            if *value { "True".into() } else { "False".into() }
        }
    }
}

fn emit_model_method_with_attrs(out: &mut String, m: &MethodDef, attrs: &[Symbol]) {
    let name = m.name.as_str();
    let ret = m.body.ty.clone().unwrap_or(Ty::Nil);
    let ret_annot = format!(" -> {}", python_ty(&ret));
    let (def_kind, params, is_instance) = match m.receiver {
        crate::dialect::MethodReceiver::Instance => {
            ("def", first_param("self", &m.params), true)
        }
        crate::dialect::MethodReceiver::Class => {
            // Class methods get a `@classmethod` decorator on the
            // previous line (written by the caller) and `cls` as the
            // first positional arg — Python's class-method shape.
            writeln!(out, "    @classmethod").unwrap();
            ("def", first_param("cls", &m.params), false)
        }
    };
    writeln!(out, "    {def_kind} {name}({params}){ret_annot}:").unwrap();
    // Pre-emit rewrite: inside an instance method, bare `title` →
    // `self.title` via Ivar substitution (emit already renders Ivars
    // as `self.<name>` in Python).
    let rewritten = if is_instance {
        rewrite_bare_attrs_to_ivars_py(&m.body, attrs)
    } else {
        m.body.clone()
    };
    let body = emit_body(&rewritten, &ret);
    if body.is_empty() {
        writeln!(out, "        pass").unwrap();
    } else {
        for line in body.lines() {
            writeln!(out, "        {line}").unwrap();
        }
    }
}

fn rewrite_bare_attrs_to_ivars_py(e: &Expr, attrs: &[Symbol]) -> Expr {
    use crate::expr::{Arm, InterpPart, Pattern};
    let rewrite = |child: &Expr| rewrite_bare_attrs_to_ivars_py(child, attrs);
    let new_node = match &*e.node {
        ExprNode::Send { recv: None, method, args, block: None, .. }
            if args.is_empty() && attrs.iter().any(|s| s == method) =>
        {
            ExprNode::Ivar { name: method.clone() }
        }
        ExprNode::Send { recv, method, args, block, parenthesized } => ExprNode::Send {
            recv: recv.as_ref().map(&rewrite),
            method: method.clone(),
            args: args.iter().map(&rewrite).collect(),
            block: block.as_ref().map(&rewrite),
            parenthesized: *parenthesized,
        },
        ExprNode::Seq { exprs } => ExprNode::Seq {
            exprs: exprs.iter().map(&rewrite).collect(),
        },
        ExprNode::Array { elements, style } => ExprNode::Array {
            elements: elements.iter().map(&rewrite).collect(),
            style: *style,
        },
        ExprNode::Hash { entries, kwargs } => ExprNode::Hash {
            entries: entries.iter().map(|(k, v)| (rewrite(k), rewrite(v))).collect(),
            kwargs: *kwargs,
        },
        ExprNode::If { cond, then_branch, else_branch } => ExprNode::If {
            cond: rewrite(cond),
            then_branch: rewrite(then_branch),
            else_branch: rewrite(else_branch),
        },
        ExprNode::Case { scrutinee, arms } => ExprNode::Case {
            scrutinee: rewrite(scrutinee),
            arms: arms
                .iter()
                .map(|arm| Arm {
                    pattern: arm.pattern.clone(),
                    guard: arm.guard.as_ref().map(&rewrite),
                    body: rewrite(&arm.body),
                })
                .collect(),
        },
        ExprNode::BoolOp { op, surface, left, right } => ExprNode::BoolOp {
            op: *op,
            surface: *surface,
            left: rewrite(left),
            right: rewrite(right),
        },
        ExprNode::StringInterp { parts } => ExprNode::StringInterp {
            parts: parts
                .iter()
                .map(|p| match p {
                    InterpPart::Text { value } => InterpPart::Text { value: value.clone() },
                    InterpPart::Expr { expr } => InterpPart::Expr { expr: rewrite(expr) },
                })
                .collect(),
        },
        ExprNode::Let { id, name, value, body } => ExprNode::Let {
            id: *id,
            name: name.clone(),
            value: rewrite(value),
            body: rewrite(body),
        },
        ExprNode::Lambda { params, block_param, body, block_style } => ExprNode::Lambda {
            params: params.clone(),
            block_param: block_param.clone(),
            body: rewrite(body),
            block_style: *block_style,
        },
        ExprNode::Apply { fun, args, block } => ExprNode::Apply {
            fun: rewrite(fun),
            args: args.iter().map(&rewrite).collect(),
            block: block.as_ref().map(&rewrite),
        },
        ExprNode::Assign { target, value } => {
            let new_target = match target {
                LValue::Var { id, name } => LValue::Var { id: *id, name: name.clone() },
                LValue::Ivar { name } => LValue::Ivar { name: name.clone() },
                LValue::Attr { recv, name } => LValue::Attr {
                    recv: rewrite(recv),
                    name: name.clone(),
                },
                LValue::Index { recv, index } => LValue::Index {
                    recv: rewrite(recv),
                    index: rewrite(index),
                },
            };
            ExprNode::Assign {
                target: new_target,
                value: rewrite(value),
            }
        }
        ExprNode::Yield { args } => ExprNode::Yield {
            args: args.iter().map(&rewrite).collect(),
        },
        ExprNode::Raise { value } => ExprNode::Raise { value: rewrite(value) },
        ExprNode::RescueModifier { expr, fallback } => ExprNode::RescueModifier {
            expr: rewrite(expr),
            fallback: rewrite(fallback),
        },
        ExprNode::Cast { value, target_ty } => ExprNode::Cast {
            value: rewrite(value),
            target_ty: target_ty.clone(),
        },
        ExprNode::Lit { .. }
        | ExprNode::Var { .. }
        | ExprNode::Ivar { .. }
        | ExprNode::Const { .. }
        | ExprNode::SelfRef => (*e.node).clone(),
        ExprNode::Return { value } => ExprNode::Return { value: rewrite(value) },
        ExprNode::Super { args } => ExprNode::Super {
            args: args.as_ref().map(|v| v.iter().map(&rewrite).collect()),
        },
        ExprNode::BeginRescue { body, rescues, else_branch, ensure, implicit } => {
            ExprNode::BeginRescue {
                body: rewrite(body),
                rescues: rescues
                    .iter()
                    .map(|rc| crate::expr::RescueClause {
                        classes: rc.classes.iter().map(&rewrite).collect(),
                        binding: rc.binding.clone(),
                        body: rewrite(&rc.body),
                    })
                    .collect(),
                else_branch: else_branch.as_ref().map(&rewrite),
                ensure: ensure.as_ref().map(&rewrite),
                implicit: *implicit,
            }
        }
        ExprNode::Next { value } => ExprNode::Next {
            value: value.as_ref().map(&rewrite),
        },
        ExprNode::MultiAssign { targets, value } => ExprNode::MultiAssign {
            targets: targets.clone(),
            value: rewrite(value),
        },
        ExprNode::While { cond, body, until_form } => ExprNode::While {
            cond: rewrite(cond),
            body: rewrite(body),
            until_form: *until_form,
        },
        ExprNode::Range { begin, end, exclusive } => ExprNode::Range {
            begin: begin.as_ref().map(&rewrite),
            end: end.as_ref().map(&rewrite),
            exclusive: *exclusive,
        },
    };
    let _ = Pattern::Wildcard;
    Expr {
        span: e.span,
        node: Box::new(new_node),
        ty: e.ty.clone(),
        effects: e.effects.clone(),
        leading_blank_line: e.leading_blank_line,
        diagnostic: e.diagnostic.clone(),
    }
}
