//! Models — `app/models.py`. Each model lowers to a `LibraryClass`
//! (extending `ApplicationRecord` -> `Base`, carrying per-model
//! `_adapter_*` SQL over the `Db` primitive) and is rendered by the
//! generic `emit_library_class`, exactly as `emit::typescript` does.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use crate::App;
use crate::ident::Symbol;

// Models ---------------------------------------------------------------

pub(super) fn emit_models(app: &App) -> EmittedFile {
    use std::collections::BTreeMap;
    // Lowered-IR path (mirrors `emit::typescript`): each model lowers to a
    // LibraryClass extending ApplicationRecord -> Base, carrying per-model
    // `_adapter_*` SQL over the `Db` primitive, and is rendered by the
    // generic `emit_library_class`. Preliminary view extras + permitted-
    // params specs feed the model lowering exactly as the TS emitter
    // threads them, so `<Model>Row`/`<Model>Params` and the typed
    // `update(p: <Model>Params)` factories come out right.
    let preliminary_views: Vec<crate::dialect::LibraryClass> = app
        .views
        .iter()
        .map(|v| crate::lower::lower_view_to_library_class(v, app))
        .collect();
    let view_extras = crate::lower::extras_from_lcs(&preliminary_views);
    let params_specs: BTreeMap<Symbol, Vec<Symbol>> =
        crate::lower::controller_to_library::params::collect_specs(&app.controllers)
            .iter()
            .map(|(r, s)| (r.clone(), s.fields.clone()))
            .collect();
    let (model_lcs, _registry) = crate::lower::lower_models_with_registry_and_params(
        &app.models,
        &app.schema,
        view_extras,
        &params_specs,
    );

    let mut body = String::new();
    for lc in &model_lcs {
        match super::library::emit_library_class(lc) {
            Ok(rendered) => {
                body.push_str(&rendered);
                body.push('\n');
            }
            Err(e) => {
                let _ = writeln!(body, "# emit error: {e}");
            }
        }
    }

    // Break the models<->views import cycle: reach the `Views` facade
    // through the views *module* (`views.Views.X`) rather than importing
    // the `Views` name. `from app.views import Views` binds a name that
    // doesn't exist yet when views.py is imported first (the server path)
    // — views.py imports models at its top, so models runs while views is
    // only partially initialized and its `Views` class isn't defined.
    // `from app import views` binds the (possibly partial) module object,
    // and the attribute access resolves late at broadcast time. Mirrors
    // the `from app import models` qualification on the views side.
    let body = body.replace("Views.", "views.Views.");

    // External module references the rendered bodies use (intra-file refs
    // — ApplicationRecord, <Model>Row/Params, sibling models — resolve
    // within this single file and need no import). Each line emits only
    // when its symbol actually appears.
    let mut imports = String::new();
    let mut want = |needle: &str, line: &str| {
        if body.contains(needle) {
            let _ = writeln!(imports, "{line}");
        }
    };
    want("(Base)", "from app.active_record_base import Base");
    want("Db.", "from app.db import Db");
    want("views.Views", "from app import views");
    want("Broadcasts", "from app.cable import Broadcasts");
    want("ValidationError", "from app.runtime import ValidationError");

    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "from __future__ import annotations").unwrap();
    if !imports.is_empty() {
        writeln!(s).unwrap();
        s.push_str(&imports);
    }
    writeln!(s).unwrap();
    s.push_str(&body);
    EmittedFile { path: PathBuf::from("app/models.py"), content: s }
}
