//! Routes — emits `app/route_helpers.py` (path helper functions).
//! The legacy `app/routes.py` (module-handler Router registration)
//! retired with the CtrlWalker teardown: dispatch rides the overlay's
//! `app/v2/routes.py` RouteTable + transpiled Router.match.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use crate::App;

/// Emit `app/route_helpers.py` — one `<as_name>_path(args)`
/// function per unique route `as_name`, derived from the
/// flattened route table. Mirrors the Rust/TS/Crystal twins with
/// Python naming (snake_case, no `Path` suffix).
pub(super) fn emit_py_route_helpers(app: &App) -> EmittedFile {
    let flat = crate::lower::flatten_routes(app);
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "from __future__ import annotations").unwrap();
    writeln!(s).unwrap();
    use std::collections::BTreeSet;
    let mut seen: BTreeSet<String> = BTreeSet::new();
    for route in &flat {
        if !seen.insert(route.as_name.clone()) {
            continue;
        }
        let fn_name = format!("{}_path", route.as_name);
        let sig_params: Vec<String> = route
            .path_params
            .iter()
            .map(|p| format!("{p}: int = 0"))
            .collect();
        let sig = sig_params.join(", ");
        let body = if route.path_params.is_empty() {
            format!("return {:?}", route.path)
        } else {
            // Build an f-string with ${param} replaced by {param}.
            let mut tmpl = String::new();
            let mut chars = route.path.chars().peekable();
            while let Some(c) = chars.next() {
                if c == ':' {
                    let mut ident = String::new();
                    while let Some(&nc) = chars.peek() {
                        if nc.is_alphanumeric() || nc == '_' {
                            ident.push(nc);
                            chars.next();
                        } else {
                            break;
                        }
                    }
                    tmpl.push('{');
                    tmpl.push_str(&ident);
                    tmpl.push('}');
                } else {
                    tmpl.push(c);
                }
            }
            format!("return f{:?}", tmpl)
        };
        writeln!(s, "def {fn_name}({sig}) -> str: {body}").unwrap();
    }
    EmittedFile {
        path: PathBuf::from("app/route_helpers.py"),
        content: s,
    }
}
