//! Routes — emits `app/routes.py` (Router registration) and
//! `app/route_helpers.py` (path helper functions).

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use super::shared::controller_class_name;
use crate::App;
use crate::dialect::RouteSpec;

// Routes ---------------------------------------------------------------

pub(super) fn emit_routes(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "from __future__ import annotations").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "from app.http import Router").unwrap();

    // Collect controller module references the routes touch.
    let mut controllers: Vec<String> = Vec::new();
    for entry in &app.routes.entries {
        collect_controller_refs_py(entry, &mut controllers);
    }
    for ctrl in &controllers {
        let stem = crate::naming::snake_case(ctrl);
        writeln!(s, "from app.controllers import {stem} as {ctrl}").unwrap();
    }
    writeln!(s).unwrap();

    // Reset before registering — re-imports during tests (pytest,
    // unittest rerun) shouldn't accumulate duplicate entries.
    writeln!(s, "Router.reset()").unwrap();

    for entry in &app.routes.entries {
        emit_py_route_spec(&mut s, entry);
    }

    EmittedFile { path: PathBuf::from("app/routes.py"), content: s }
}

fn collect_controller_refs_py(spec: &RouteSpec, out: &mut Vec<String>) {
    let push = |name: String, out: &mut Vec<String>| {
        if !out.iter().any(|c| c == &name) {
            out.push(name);
        }
    };
    match spec {
        RouteSpec::Explicit { controller, .. } => {
            push(controller.0.to_string(), out);
        }
        RouteSpec::Root { target } => {
            if let Some((c, _)) = target.split_once('#') {
                push(controller_class_name(c), out);
            }
        }
        RouteSpec::Resources { name, nested, .. } => {
            push(controller_class_name(name.as_str()), out);
            for child in nested {
                collect_controller_refs_py(child, out);
            }
        }
    }
}

fn emit_py_route_spec(out: &mut String, spec: &RouteSpec) {
    match spec {
        RouteSpec::Explicit { method, path, controller, action, .. } => {
            let verb = match method {
                crate::dialect::HttpMethod::Get => "get",
                crate::dialect::HttpMethod::Post => "post",
                crate::dialect::HttpMethod::Put => "put",
                crate::dialect::HttpMethod::Patch => "patch",
                crate::dialect::HttpMethod::Delete => "delete",
                _ => "get",
            };
            writeln!(
                out,
                "Router.{verb}({:?}, {}, {:?})",
                path,
                controller.0,
                action.as_str(),
            )
            .unwrap();
        }
        RouteSpec::Root { target } => {
            let (controller, action) = target
                .split_once('#')
                .map(|(c, a)| (controller_class_name(c), a.to_string()))
                .unwrap_or_else(|| (target.clone(), "index".to_string()));
            writeln!(out, "Router.root({controller}, {action:?})").unwrap();
        }
        RouteSpec::Resources { name, only, except: _, nested } => {
            let controller = controller_class_name(name.as_str());
            let mut opts: Vec<String> = Vec::new();
            if !only.is_empty() {
                let parts: Vec<String> =
                    only.iter().map(|s| format!("{:?}", s.as_str())).collect();
                opts.push(format!("only=[{}]", parts.join(", ")));
            }
            if !nested.is_empty() {
                let mut nested_parts: Vec<String> = Vec::new();
                for child in nested {
                    if let Some(part) = py_nested_spec_entry(child) {
                        nested_parts.push(part);
                    }
                }
                if !nested_parts.is_empty() {
                    opts.push(format!("nested=[{}]", nested_parts.join(", ")));
                }
            }
            if opts.is_empty() {
                writeln!(
                    out,
                    "Router.resources({:?}, {})",
                    name.as_str(),
                    controller
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    "Router.resources({:?}, {}, {})",
                    name.as_str(),
                    controller,
                    opts.join(", ")
                )
                .unwrap();
            }
        }
    }
}

fn py_nested_spec_entry(spec: &RouteSpec) -> Option<String> {
    let RouteSpec::Resources { name, only, except: _, nested: _ } = spec else {
        return None;
    };
    let controller = controller_class_name(name.as_str());
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("\"name\": {:?}", name.as_str()));
    parts.push(format!("\"controller\": {controller}"));
    if !only.is_empty() {
        let items: Vec<String> =
            only.iter().map(|s| format!("{:?}", s.as_str())).collect();
        parts.push(format!("\"only\": [{}]", items.join(", ")));
    }
    Some(format!("{{{}}}", parts.join(", ")))
}

/// Emit `app/route_helpers.py` — one `<as_name>_path(args)`
/// function per unique route `as_name`, derived from the
/// flattened route table. Mirrors the Rust/TS/Crystal twins with
/// Python naming (snake_case, no `Path` suffix).
pub(super) fn emit_py_route_helpers(app: &App) -> EmittedFile {
    let flat = crate::lower::flatten_routes(app);
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "from __future__ import annotations").unwrap();
    writeln!(s).unwrap();
    use std::collections::BTreeSet;
    let mut seen: BTreeSet<String> = BTreeSet::new();
    for route in &flat {
        if !seen.insert(route.as_name.clone()) {
            continue;
        }
        let fn_name = format!("{}_path", route.as_name);
        let sig_params: Vec<String> = route
            .path_params
            .iter()
            .map(|p| format!("{p}: int = 0"))
            .collect();
        let sig = sig_params.join(", ");
        let body = if route.path_params.is_empty() {
            format!("return {:?}", route.path)
        } else {
            // Build an f-string with ${param} replaced by {param}.
            let mut tmpl = String::new();
            let mut chars = route.path.chars().peekable();
            while let Some(c) = chars.next() {
                if c == ':' {
                    let mut ident = String::new();
                    while let Some(&nc) = chars.peek() {
                        if nc.is_alphanumeric() || nc == '_' {
                            ident.push(nc);
                            chars.next();
                        } else {
                            break;
                        }
                    }
                    tmpl.push('{');
                    tmpl.push_str(&ident);
                    tmpl.push('}');
                } else {
                    tmpl.push(c);
                }
            }
            format!("return f{:?}", tmpl)
        };
        writeln!(s, "def {fn_name}({sig}) -> str: {body}").unwrap();
    }
    EmittedFile {
        path: PathBuf::from("app/route_helpers.py"),
        content: s,
    }
}
