//! Schema SQL — emits `app/schema_sql.py` exposing the
//! target-neutral DDL as `CREATE_TABLES`.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use crate::App;

/// `app/schema_sql.py` — Python module exposing the target-neutral
/// DDL as `CREATE_TABLES`. sqlite3's `executescript` handles
/// multi-statement strings directly, so no splitting needed.
pub(super) fn emit_schema_sql(app: &App) -> EmittedFile {
    let ddl = crate::emit::shared::schema_sql::render_schema_sql(&app.schema);
    // Use a Python triple-quoted raw string so the DDL renders with
    // its original line breaks and doesn't need escape-sequence
    // handling. Raw so backslashes in identifiers (none today but
    // defensive) pass through.
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "CREATE_TABLES = r\"\"\"").unwrap();
    s.push_str(&ddl);
    writeln!(s, "\"\"\"").unwrap();
    EmittedFile {
        path: PathBuf::from("app/schema_sql.py"),
        content: s,
    }
}
