//! Test/spec emission — emits `tests/test_*.py` (one per test
//! module) using stdlib `unittest`.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use super::controller_test::{PyTestCtx, emit_py_controller_test_body};
use super::expr::emit_literal;
use super::shared::test_name_snake_py;
use crate::App;
use crate::dialect::{Test, TestModule};
use crate::expr::{Expr, ExprNode, LValue, Literal};
use crate::ident::Symbol;

pub(super) fn emit_py_test(tm: &TestModule, app: &App) -> EmittedFile {
    let fixture_names: Vec<Symbol> =
        app.fixtures.iter().map(|f| f.name.clone()).collect();
    let known_models: Vec<Symbol> =
        app.models.iter().map(|m| m.name.0.clone()).collect();
    let mut attrs_set: std::collections::BTreeSet<Symbol> =
        std::collections::BTreeSet::new();
    for m in &app.models {
        for attr in m.attributes.fields.keys() {
            attrs_set.insert(attr.clone());
        }
    }
    let model_attrs: Vec<Symbol> = attrs_set.into_iter().collect();

    let ctx = PyTestCtx {
        app,
        fixture_names: &fixture_names,
        known_models: &known_models,
        model_attrs: &model_attrs,
    };

    let is_controller_test = tm.name.0.as_str().ends_with("ControllerTest");

    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "from __future__ import annotations").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "import unittest").unwrap();
    writeln!(s).unwrap();
    if is_controller_test {
        // Side-effect import: app.routes registers handlers on the
        // Router at module load. Needed before any dispatch.
        writeln!(s, "import app.routes  # noqa: F401").unwrap();
        writeln!(s, "from app.test_support import TestClient").unwrap();
        writeln!(s, "from app.route_helpers import *  # noqa: F401, F403").unwrap();
    }
    // Import every model so Class.new struct-literals resolve, plus all
    // fixture accessors.
    if !known_models.is_empty() {
        writeln!(
            s,
            "from app.models import {}",
            known_models
                .iter()
                .map(|m| m.as_str().to_string())
                .collect::<Vec<_>>()
                .join(", ")
        )
        .unwrap();
    }
    if !app.fixtures.is_empty() {
        writeln!(s, "from tests import fixtures").unwrap();
    }

    writeln!(s).unwrap();
    writeln!(s, "class {}(unittest.TestCase):", tm.name.0.as_str()).unwrap();

    if !app.fixtures.is_empty() {
        // setUp runs before each test method — opens a fresh :memory:
        // DB and reloads all fixtures, matching Rails' transactional-
        // fixture isolation.
        writeln!(s).unwrap();
        writeln!(s, "    def setUp(self):").unwrap();
        writeln!(s, "        fixtures.setup()").unwrap();
    }

    for test in &tm.tests {
        let fn_name = format!("test_{}", test_name_snake_py(&test.name));
        writeln!(s).unwrap();
        if is_controller_test {
            writeln!(s, "    def {fn_name}(self):").unwrap();
            let body = emit_py_controller_test_body(test, app, &ctx);
            if body.is_empty() {
                writeln!(s, "        pass").unwrap();
            } else {
                for line in body.lines() {
                    writeln!(s, "        {line}").unwrap();
                }
            }
        } else if test_needs_runtime_unsupported_py(test) {
            writeln!(
                s,
                "    @unittest.skip(\"Phase 3: needs persistence runtime\")"
            )
            .unwrap();
            writeln!(s, "    def {fn_name}(self):").unwrap();
            writeln!(s, "        pass").unwrap();
        } else {
            writeln!(s, "    def {fn_name}(self):").unwrap();
            let body = emit_py_test_body(&test.body, ctx);
            if body.is_empty() {
                writeln!(s, "        pass").unwrap();
            } else {
                for line in body.lines() {
                    writeln!(s, "        {line}").unwrap();
                }
            }
        }
    }

    // unittest discover default pattern is `test_*.py`; convert
    // `ArticleTest` → `article_test` → `article` → `test_article`.
    let stem = crate::naming::snake_case(tm.name.0.as_str()).replace("_test", "");
    EmittedFile {
        path: PathBuf::from(format!("tests/test_{stem}.py")),
        content: s,
    }
}

fn emit_py_test_body(body: &Expr, ctx: PyTestCtx) -> String {
    match &*body.node {
        ExprNode::Seq { exprs } if !exprs.is_empty() => exprs
            .iter()
            .map(|e| emit_py_test_stmt(e, ctx))
            .collect::<Vec<_>>()
            .join("\n"),
        _ => emit_py_test_stmt(body, ctx),
    }
}

fn emit_py_test_stmt(e: &Expr, ctx: PyTestCtx) -> String {
    match &*e.node {
        ExprNode::Assign { target: LValue::Var { name, .. }, value } => {
            format!("{} = {}", name, emit_py_test_expr(value, ctx))
        }
        _ => emit_py_test_expr(e, ctx),
    }
}

fn emit_py_test_expr(e: &Expr, ctx: PyTestCtx) -> String {
    match &*e.node {
        ExprNode::Lit { value } => emit_literal(value),
        ExprNode::Var { name, .. } => name.to_string(),
        ExprNode::Const { path } => path
            .iter()
            .map(|s| s.to_string())
            .collect::<Vec<_>>()
            .join("."),
        ExprNode::Send { recv, method, args, block, .. } => {
            emit_py_test_send(recv.as_ref(), method.as_str(), args, block.as_ref(), ctx)
        }
        ExprNode::BoolOp { op, left, right, .. } => {
            use crate::expr::BoolOpKind;
            let op_s = match op {
                BoolOpKind::Or => "or",
                BoolOpKind::And => "and",
            };
            format!(
                "{} {op_s} {}",
                emit_py_test_expr(left, ctx),
                emit_py_test_expr(right, ctx)
            )
        }
        _ => format!("# TODO: Python test emit for {:?}", std::mem::discriminant(&*e.node)),
    }
}

fn emit_py_test_send(
    recv: Option<&Expr>,
    method: &str,
    args: &[Expr],
    block: Option<&Expr>,
    ctx: PyTestCtx,
) -> String {
    let args_s: Vec<String> = args.iter().map(|a| emit_py_test_expr(a, ctx)).collect();

    // Fixture accessor: articles(:one) → fixtures.articles_one()
    if recv.is_none()
        && args.len() == 1
        && ctx.fixture_names.iter().any(|s| s.as_str() == method)
    {
        if let ExprNode::Lit { value: Literal::Sym { value: sym } } = &*args[0].node {
            return format!("fixtures.{}_{}()", method, sym.as_str());
        }
    }

    // assert_difference("Class.count", delta) do ... end → inline
    // before/after capture + self.assertEqual on the delta.
    // Callers see this as a bare expression; we need statement form,
    // so the Stage layer (emit_py_test_stmt) handles newline wrapping.
    if recv.is_none() && method == "assert_difference" {
        if let Some(body) = block {
            if let Some(count_expr) = args
                .first()
                .and_then(|a| match &*a.node {
                    ExprNode::Lit { value: Literal::Str { value } } => {
                        rewrite_ruby_dot_call_py(value)
                    }
                    _ => None,
                })
            {
                let delta = args_s.get(1).cloned().unwrap_or_else(|| "1".into());
                let body_s = emit_block_body_py(body, ctx);
                return format!(
                    "_before = {count_expr}\n{body_s}\n_after = {count_expr}\nself.assertEqual(_after - _before, {delta})"
                );
            }
        }
    }

    // owner.<assoc>.create(hash) / .build(hash) — HasMany rewrite.
    // Python: a lambda-call with a walrus-ish shape won't work
    // cleanly, so we use a helper module-level function wouldn't
    // either. Easiest: expand to a small helper-less form. We can
    // construct Class(article_id=..., commenter=..., body=...) and
    // call save on the result. Since this sits in expression
    // position (assign rhs), wrap in a `(lambda: ...)()` one-shot.
    if (method == "create" || method == "build") && args.len() == 1 {
        if let Some(outer_recv) = recv {
            if let ExprNode::Send {
                recv: Some(assoc_recv),
                method: assoc_method,
                args: inner_args,
                ..
            } = &*outer_recv.node
            {
                if inner_args.is_empty() {
                    if let Some(s) = try_emit_assoc_create_py(
                        assoc_recv,
                        assoc_method.as_str(),
                        args,
                        method,
                        ctx,
                    ) {
                        return s;
                    }
                }
            }
        }
    }

    // Assertion macros → unittest's TestCase methods.
    if recv.is_none() {
        match (method, args_s.len()) {
            ("assert_equal", 2) => {
                return format!(
                    "self.assertEqual({}, {})",
                    args_s[1], args_s[0]
                );
            }
            ("assert_not_equal", 2) => {
                return format!(
                    "self.assertNotEqual({}, {})",
                    args_s[1], args_s[0]
                );
            }
            ("assert_not", 1) => return format!("self.assertFalse({})", args_s[0]),
            ("assert", 1) => return format!("self.assertTrue({})", args_s[0]),
            ("assert_nil", 1) => return format!("self.assertIsNone({})", args_s[0]),
            ("assert_not_nil", 1) => {
                return format!("self.assertIsNotNone({})", args_s[0])
            }
            _ => {}
        }
    }

    // `Class.new(hash)` → `Class(**{...})` or `Class(field=val, ...)`
    if let Some(r) = recv {
        if method == "new" && args.len() == 1 {
            if let ExprNode::Const { path } = &*r.node {
                if let Some(class_name) = path.last() {
                    if ctx.known_models.iter().any(|s| s == class_name) {
                        if let ExprNode::Hash { entries, .. } = &*args[0].node {
                            let pairs: Vec<String> = entries
                                .iter()
                                .filter_map(|(k, v)| {
                                    if let ExprNode::Lit {
                                        value: Literal::Sym { value: f },
                                    } = &*k.node
                                    {
                                        Some(format!(
                                            "{}={}",
                                            f.as_str(),
                                            emit_py_test_expr(v, ctx)
                                        ))
                                    } else {
                                        None
                                    }
                                })
                                .collect();
                            return format!("{class_name}({})", pairs.join(", "));
                        }
                    }
                }
            }
        }
    }

    match recv {
        None => {
            if args_s.is_empty() {
                method.to_string()
            } else {
                format!("{}({})", method, args_s.join(", "))
            }
        }
        Some(r) => {
            let recv_s = emit_py_test_expr(r, ctx);
            // Attribute read (no parens) vs method call.
            let is_attr = args_s.is_empty()
                && ctx.model_attrs.iter().any(|s| s.as_str() == method);
            if is_attr {
                format!("{recv_s}.{method}")
            } else if args_s.is_empty() {
                format!("{recv_s}.{method}()")
            } else {
                format!("{recv_s}.{method}({})", args_s.join(", "))
            }
        }
    }
}

fn test_needs_runtime_unsupported_py(_test: &Test) -> bool {
    // Phase 3 rounded out the Python emitter's real-blog coverage.
    // Keep as a future-guard; nothing in real-blog currently forces
    // a skip.
    false
}

/// Parse a Ruby `"Class.method"` string into Python `Class.method()`.
/// Uppercase LHS → class method call; lowercase LHS → attribute
/// read.
fn rewrite_ruby_dot_call_py(expr: &str) -> Option<String> {
    let trimmed = expr.trim();
    let (lhs, rhs) = trimmed.split_once('.')?;
    let is_ident = |s: &str| {
        !s.is_empty()
            && s.chars().next().is_some_and(|c| c.is_alphabetic() || c == '_')
            && s.chars().all(|c| c.is_alphanumeric() || c == '_')
    };
    if !is_ident(lhs) || !is_ident(rhs) {
        return None;
    }
    let is_class = lhs.chars().next().is_some_and(|c| c.is_uppercase());
    if is_class {
        Some(format!("{lhs}.{rhs}()"))
    } else {
        Some(format!("{lhs}.{rhs}"))
    }
}

/// Render a Ruby block body as Python statements. Ruby `do ... end`
/// lowers to ExprNode::Lambda; peel one layer.
fn emit_block_body_py(e: &Expr, ctx: PyTestCtx) -> String {
    let inner = match &*e.node {
        ExprNode::Lambda { body, .. } => body,
        _ => e,
    };
    match &*inner.node {
        ExprNode::Seq { exprs } if !exprs.is_empty() => exprs
            .iter()
            .map(|s| emit_py_test_stmt(s, ctx))
            .collect::<Vec<_>>()
            .join("\n"),
        _ => emit_py_test_stmt(inner, ctx),
    }
}

fn try_emit_assoc_create_py(
    owner: &Expr,
    assoc_name: &str,
    args: &[Expr],
    outer_method: &str,
    ctx: PyTestCtx,
) -> Option<String> {
    let resolved = crate::lower::resolve_has_many(
        &Symbol::from(assoc_name),
        owner.ty.as_ref(),
        ctx.app,
    )?;
    let target_class = resolved.target_class.0.as_str();
    let foreign_key = resolved.foreign_key.as_str();

    let owner_s = emit_py_test_expr(owner, ctx);
    let hash_entries = match &args.first()?.node.as_ref() {
        ExprNode::Hash { entries, .. } => entries.clone(),
        _ => return None,
    };

    let mut kwargs: Vec<String> = vec![format!("{foreign_key}={owner_s}.id")];
    for (k, v) in &hash_entries {
        if let ExprNode::Lit { value: Literal::Sym { value: field_name } } = &*k.node {
            kwargs.push(format!(
                "{}={}",
                field_name.as_str(),
                emit_py_test_expr(v, ctx),
            ));
        }
    }
    let ctor = format!("{target_class}({})", kwargs.join(", "));
    // Python expression-form sequence: walrus operator in a tuple
    // evaluates both and yields the record. `.create` runs save;
    // `.build` doesn't.
    if outer_method == "create" {
        Some(format!(
            "(lambda _r: (_r.save(), _r)[1])({ctor})"
        ))
    } else {
        Some(ctor)
    }
}
