//! Views — `app/views.py` flat module with all view functions.
//!
//! Python's filenames can't contain dots-inside-stems cleanly
//! (`articles.index.py` works but `articles/index.html.py`
//! doesn't), so every view fn collapses into a single module. The
//! controllers import as `from app import views` and call
//! `views.render_articles_index(records)` etc.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use super::expr::emit_literal;
use super::shared::py_string_literal;
use crate::App;
use crate::expr::{Expr, ExprNode, LValue, Literal};
use crate::ident::Symbol;

pub(super) fn emit_py_views(app: &App) -> Vec<EmittedFile> {
    if app.views.is_empty() && app.controllers.is_empty() {
        return Vec::new();
    }
    let known_models: Vec<Symbol> =
        app.models.iter().map(|m| m.name.0.clone()).collect();
    let attrs_by_class: std::collections::BTreeMap<String, Vec<String>> = app
        .models
        .iter()
        .map(|m| {
            (
                m.name.0.as_str().to_string(),
                m.attributes
                    .fields
                    .keys()
                    .map(|k| k.as_str().to_string())
                    .collect(),
            )
        })
        .collect();
    let has_manys = crate::lower::build_has_many_table(app);
    let stylesheets = app.stylesheets.clone();

    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "from __future__ import annotations").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "from typing import Any").unwrap();
    writeln!(s, "from app import view_helpers as Helpers").unwrap();
    writeln!(s, "from app import importmap").unwrap();
    writeln!(s, "from app.route_helpers import *  # noqa: F401, F403").unwrap();
    if !known_models.is_empty() {
        writeln!(s, "from app.models import *  # noqa: F401, F403").unwrap();
    }
    writeln!(s).unwrap();

    let mut emitted_names: std::collections::BTreeSet<String> =
        std::collections::BTreeSet::new();

    for v in &app.views {
        let fn_name = py_view_function_name(v.name.as_str());
        if !emitted_names.insert(fn_name.clone()) {
            continue;
        }
        emit_view_file_pass2_py(
            &mut s,
            v,
            &known_models,
            &attrs_by_class,
            &has_manys,
            &stylesheets,
        );
        writeln!(s).unwrap();
    }

    // Stub missing standard CRUD views so controllers can always
    // import. Same posture as TS's _stubs.ts.
    for model in &app.models {
        if model.attributes.fields.is_empty() {
            continue;
        }
        let class = model.name.0.as_str();
        let plural = crate::naming::pluralize_snake(class);
        for (_, suffix) in [
            ("Index", "index"),
            ("Show", "show"),
            ("New", "new"),
            ("Edit", "edit"),
        ] {
            let view_name = format!("{plural}/{suffix}");
            let fn_name = py_view_function_name(&view_name);
            if emitted_names.insert(fn_name.clone()) {
                writeln!(s, "def {fn_name}(_record: Any) -> str:").unwrap();
                writeln!(s, "    return \"\"").unwrap();
                writeln!(s).unwrap();
            }
        }
    }

    vec![EmittedFile {
        path: PathBuf::from("app/views.py"),
        content: s,
    }]
}

/// `articles/index` → `render_articles_index`. Slash → underscore;
/// partial-prefix underscores get stripped (`_article` → `article`).
fn py_view_function_name(name: &str) -> String {
    let mut parts: Vec<String> = Vec::new();
    for seg in name.split('/') {
        let trimmed = seg.strip_prefix('_').unwrap_or(seg);
        parts.push(trimmed.to_string());
    }
    format!("render_{}", parts.join("_"))
}

fn emit_view_file_pass2_py(
    out: &mut String,
    view: &crate::dialect::View,
    known_models: &[Symbol],
    attrs_by_class: &std::collections::BTreeMap<String, Vec<String>>,
    has_manys: &[crate::lower::HasManyRow],
    stylesheets: &[String],
) {
    // Python doesn't rewrite ivars → locals in the AST; instead,
    // `emit_py_view_expr_raw` / `emit_py_view_stmt_pass2` treat
    // `Ivar { name }` the same as `Var { name }`. The arg name
    // from `py_view_signature` matches the ivar name in ERB bodies
    // (e.g. signature `articles: list[Article]` with ivar `@articles`).
    let fn_name = py_view_function_name(view.name.as_str());

    let (sig, arg_name, arg_model) =
        py_view_signature(view.name.as_str(), known_models);
    let attrs = arg_model
        .as_ref()
        .and_then(|c| attrs_by_class.get(c).cloned())
        .unwrap_or_default();

    writeln!(out, "def {fn_name}({sig}) -> str:").unwrap();
    writeln!(out, "    _buf = \"\"").unwrap();

    let mut locals: Vec<String> = vec!["_buf".to_string(), arg_name.clone()];
    let ivar_names = py_collect_ivar_names(&view.body);
    for n in &ivar_names {
        if !locals.iter().any(|x| x == n) {
            locals.push(n.clone());
        }
    }
    let resource_dir = view
        .name
        .as_str()
        .rsplit_once('/')
        .map(|(d, _): (&str, &str)| d.to_string())
        .unwrap_or_default();
    let ctx = PyViewCtx {
        locals,
        arg_name: arg_name.clone(),
        arg_attrs: attrs,
        resource_dir,
        known_models: known_models.iter().map(|s| s.as_str().to_string()).collect(),
        has_manys: has_manys.to_vec(),
        stylesheets: stylesheets.to_vec(),
        form_records: Vec::new(),
        attrs_by_class: attrs_by_class.clone(),
    };

    // Apply the shared erubi-trim pass so `<% %>` tags drop their
    // trailing newline + leading indent the same way Rails does.
    let trimmed_body = crate::lower::erb_trim::trim_view(&view.body);
    let body_lines = emit_py_view_body(&trimmed_body, &ctx);
    for line in body_lines {
        writeln!(out, "    {line}").unwrap();
    }
    writeln!(out, "    return _buf").unwrap();
}

#[derive(Clone)]
pub(super) struct PyViewCtx {
    locals: Vec<String>,
    arg_name: String,
    arg_attrs: Vec<String>,
    resource_dir: String,
    #[allow(dead_code)]
    known_models: Vec<String>,
    /// Has-many rows, shared via `crate::lower`. Used by
    /// `article.comments` lowering.
    has_manys: Vec<crate::lower::HasManyRow>,
    stylesheets: Vec<String>,
    /// `(builder_local_name, record_python_expr)` pairs active in
    /// the current scope. Populated on entry to a `form_with`
    /// block; consumed by FormBuilder field emit so `form.text_
    /// field :title` resolves to the bound record's attr.
    form_records: Vec<(String, String)>,
    attrs_by_class: std::collections::BTreeMap<String, Vec<String>>,
}

impl PyViewCtx {
    fn is_local(&self, n: &str) -> bool {
        self.locals.iter().any(|x| x == n)
    }
    fn arg_has_attr(&self, name: &str, attr: &str) -> bool {
        name == self.arg_name && self.arg_attrs.iter().any(|a| a == attr)
    }
    fn local_has_attr(&self, local: &str, attr: &str) -> bool {
        // Primary arg — fast path.
        if self.arg_has_attr(local, attr) {
            return true;
        }
        // Other locals — look up by singularize-camelize convention.
        let class = crate::naming::singularize_camelize(local);
        self.attrs_by_class
            .get(&class)
            .map(|attrs| attrs.iter().any(|a| a == attr))
            .unwrap_or(false)
    }
    fn with_locals(&self, more: impl IntoIterator<Item = String>) -> Self {
        let mut next = self.clone();
        for n in more {
            if !next.locals.iter().any(|x| x == &n) {
                next.locals.push(n);
            }
        }
        next
    }
    fn resolve_has_many_on_local(&self, local: &str, assoc: &str) -> Option<(String, String)> {
        if !self.is_local(local) {
            return None;
        }
        crate::lower::resolve_has_many_on_local(&self.has_manys, local, assoc)
    }
}

fn py_view_signature(
    view_name: &str,
    known_models: &[Symbol],
) -> (String, String, Option<String>) {
    let (dir, base) = view_name.rsplit_once('/').unwrap_or(("", view_name));
    let is_partial = base.starts_with('_');
    let stem = base.trim_start_matches('_');
    let model_class = crate::naming::singularize_camelize(dir);
    let model_exists = known_models.iter().any(|m| m.as_str() == model_class);
    let singular = crate::naming::singularize(dir);

    if is_partial {
        let arg_name = if model_exists { singular.clone() } else { stem.to_string() };
        if model_exists {
            return (format!("{arg_name}: {model_class}"), arg_name, Some(model_class));
        }
        return (format!("{arg_name}: Any"), arg_name, None);
    }
    match stem {
        "index" => {
            let arg_name = dir.to_string();
            if model_exists {
                return (
                    format!("{arg_name}: list[{model_class}]"),
                    arg_name,
                    Some(model_class),
                );
            }
            return (format!("{arg_name}: list[Any]"), arg_name, None);
        }
        _ => {
            let arg_name = singular.clone();
            if model_exists {
                return (format!("{arg_name}: {model_class}"), arg_name, Some(model_class));
            }
            return (format!("{arg_name}: Any"), arg_name, None);
        }
    }
}

fn emit_py_view_body(body: &Expr, ctx: &PyViewCtx) -> Vec<String> {
    let stmts: Vec<&Expr> = match &*body.node {
        ExprNode::Seq { exprs } => exprs.iter().collect(),
        _ => vec![body],
    };
    let mut out = Vec::new();
    for stmt in &stmts {
        out.extend(emit_py_view_stmt_pass2(stmt, ctx));
    }
    if out.is_empty() {
        out.push("pass".to_string());
    }
    out
}

fn emit_py_view_stmt_pass2(stmt: &Expr, ctx: &PyViewCtx) -> Vec<String> {
    match &*stmt.node {
        // Prologue `_buf = ""` — already written by `emit_view_file_pass2_py`.
        ExprNode::Assign { target: LValue::Var { name, .. }, value }
            if name.as_str() == "_buf" =>
        {
            if let ExprNode::Lit { value: Literal::Str { value: s } } = &*value.node {
                if s.is_empty() {
                    return Vec::new();
                }
            }
            // `_buf = _buf + X` — the working shape.
            if let ExprNode::Send { recv: Some(recv), method, args, .. } = &*value.node {
                if method.as_str() == "+" && args.len() == 1 {
                    if let ExprNode::Var { name: rn, .. } = &*recv.node {
                        if rn.as_str() == "_buf" {
                            let chunk = emit_py_view_append_pass2(&args[0], ctx);
                            return chunk
                                .lines()
                                .map(|l| l.to_string())
                                .collect();
                        }
                    }
                }
            }
            vec!["pass  # TODO ERB: _buf shape".to_string()]
        }
        // Epilogue: bare `_buf` — dropped; we emit `return _buf` at the end.
        ExprNode::Var { name, .. } if name.as_str() == "_buf" => Vec::new(),
        // Ivar read at statement level (rare) — drop; the view walker
        // only cares about `_buf` assigns.
        ExprNode::Ivar { .. } => Vec::new(),
        // Statement-form `<% content_for :title, "Articles" %>` —
        // setter. Dispatch via the view-helper classifier.
        ExprNode::Send { recv: None, method, args, block: None, .. } => {
            if let Some(crate::lower::ViewHelperKind::ContentForSetter { slot, body }) =
                crate::lower::classify_view_helper(method.as_str(), args)
            {
                if is_py_simple_expr(body, ctx) {
                    let body_py = emit_py_view_expr_raw(body, ctx);
                    return vec![format!("Helpers.content_for_set({slot:?}, str({body_py}))")];
                }
            }
            vec!["pass  # TODO ERB: unknown stmt".to_string()]
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            let cond_py = if is_py_simple_expr(cond, ctx) {
                emit_py_view_expr_raw(cond, ctx)
            } else {
                "False".to_string()
            };
            let mut out = vec![format!("if {cond_py}:")];
            let then_lines = emit_py_view_body(then_branch, ctx);
            for line in then_lines {
                out.push(format!("    {line}"));
            }
            let has_else = !matches!(
                &*else_branch.node,
                ExprNode::Lit { value: Literal::Nil }
            );
            if has_else {
                out.push("else:".to_string());
                for line in emit_py_view_body(else_branch, ctx) {
                    out.push(format!("    {line}"));
                }
            }
            out
        }
        ExprNode::Send { recv: Some(recv), method, args, block: Some(block), .. }
            if method.as_str() == "each" && args.is_empty() =>
        {
            if !is_py_simple_expr(recv, ctx) {
                return vec!["pass  # TODO ERB: each over complex coll".to_string()];
            }
            let ExprNode::Lambda { params, body, .. } = &*block.node else {
                return vec!["pass  # unexpected each block".to_string()];
            };
            let coll_s = emit_py_view_expr_raw(recv, ctx);
            let var = params
                .first()
                .map(|p| p.as_str().to_string())
                .unwrap_or_else(|| "item".into());
            let inner_ctx = ctx.with_locals([var.clone()]);
            let mut out = vec![format!("for {var} in {coll_s}:")];
            let inner_lines = emit_py_view_body(body, &inner_ctx);
            for line in inner_lines {
                out.push(format!("    {line}"));
            }
            out
        }
        _ => vec!["pass  # TODO ERB: unknown stmt".to_string()],
    }
}

fn emit_py_view_append_pass2(arg: &Expr, ctx: &PyViewCtx) -> String {
    // Text chunk.
    if let ExprNode::Lit { value: Literal::Str { value: s } } = &*arg.node {
        return format!("_buf += {}", py_string_literal(s));
    }
    let inner = unwrap_to_s_py(arg);

    // `<%= yield %>` / `<%= yield :head %>` — emit the stashed
    // inner-view body for bare yield, or the named slot's stash
    // for slot yield.
    if let ExprNode::Yield { args } = &*inner.node {
        if let Some(first) = args.first() {
            if let Some(slot) = py_extract_slot_name(first) {
                return format!("_buf += Helpers.get_slot({slot:?})");
            }
        }
        return "_buf += Helpers.get_yield()".to_string();
    }

    // `<%= content_for(:slot) || "default" %>` — BoolOp fallback.
    if let ExprNode::BoolOp { op, left, right, .. } = &*inner.node {
        if matches!(op, crate::expr::BoolOpKind::Or) {
            if let ExprNode::Send { recv: None, method, args, block: None, .. } = &*left.node {
                if method.as_str() == "content_for" && args.len() == 1 {
                    if let Some(slot) = py_extract_slot_name(&args[0]) {
                        if is_py_simple_expr(right, ctx) {
                            let fb = emit_py_view_expr_raw(right, ctx);
                            return format!(
                                "_buf += Helpers.content_for_get({slot:?}) or str({fb})"
                            );
                        }
                    }
                }
            }
        }
    }

    // `render @coll` or `render "partial", locals` — expand.
    if let ExprNode::Send { recv: None, method, args, block: None, .. } = &*inner.node {
        if method.as_str() == "render" {
            if args.len() == 1 {
                return emit_py_render_call(&args[0], ctx);
            }
            if args.len() == 2 {
                if let (
                    ExprNode::Lit { value: Literal::Str { value: partial } },
                    ExprNode::Hash { entries, .. },
                ) = (&*args[0].node, &*args[1].node)
                {
                    let partial_fn = format!(
                        "render_{}_{}",
                        ctx.resource_dir,
                        partial.trim_start_matches('_'),
                    );
                    if let Some((_, v)) = entries.first() {
                        if is_py_simple_expr(v, ctx) {
                            let arg_expr = emit_py_view_expr_raw(v, ctx);
                            return format!("_buf += {partial_fn}({arg_expr})");
                        }
                    }
                    return format!("_buf += {partial_fn}(None)");
                }
            }
        }
    }

    // form_with / content_for(do block) — capturing helpers.
    if let ExprNode::Send {
        recv: None,
        method,
        args,
        block: Some(block),
        ..
    } = &*inner.node
    {
        if is_py_capturing_helper(method.as_str()) {
            return emit_py_captured_helper(method.as_str(), args, block, ctx);
        }
    }

    // View-helper classifier: link_to, button_to, dom_id, pluralize,
    // truncate, stylesheet_link_tag, content_for (getter),
    // javascript_importmap_tags, csrf_meta_tags, csp_meta_tag,
    // turbo_stream_from.
    if let ExprNode::Send { recv: None, method, args, block: None, .. } = &*inner.node {
        if let Some(kind) = crate::lower::classify_view_helper(method.as_str(), args) {
            if let Some(line) = emit_py_view_helper(&kind, ctx) {
                return line;
            }
        }
    }

    // FormBuilder method calls (`form.label :title`, etc.).
    if let ExprNode::Send { recv: Some(r), method, args, block: None, .. } = &*inner.node {
        if let ExprNode::Var { name, .. } | ExprNode::Ivar { name } = &*r.node {
            if ctx.form_records.iter().any(|(n, _)| n == name.as_str()) {
                if let Some(fb) = crate::lower::classify_form_builder_method(method.as_str()) {
                    if let Some(call) = emit_py_form_builder_call(name.as_str(), fb, args, ctx)
                    {
                        return format!("_buf += {call}");
                    }
                }
            }
        }
    }

    // Simple interpolation.
    if is_py_simple_expr(inner, ctx) {
        return format!(
            "_buf += str({})",
            emit_py_view_expr_raw(inner, ctx),
        );
    }

    "_buf += \"\"  # TODO ERB: complex interpolation".to_string()
}

fn py_extract_slot_name(arg: &Expr) -> Option<&str> {
    match &*arg.node {
        ExprNode::Lit { value: Literal::Sym { value } } => Some(value.as_str()),
        ExprNode::Lit { value: Literal::Str { value } } => Some(value.as_str()),
        _ => None,
    }
}

fn is_py_capturing_helper(method: &str) -> bool {
    matches!(method, "form_with" | "content_for")
}

fn emit_py_captured_helper(
    method: &str,
    args: &[Expr],
    block: &Expr,
    ctx: &PyViewCtx,
) -> String {
    let ExprNode::Lambda { params, body, .. } = &*block.node else {
        return format!("_buf += \"\"  # TODO ERB: {method}");
    };
    let cls_expr = args
        .iter()
        .find_map(|a| py_extract_kwarg(a, "class"))
        .filter(|e| is_py_simple_expr(e, ctx))
        .map(|e| emit_py_view_expr_raw(e, ctx))
        .unwrap_or_else(|| "\"\"".to_string());
    match method {
        "form_with" => {
            // Resolve `model:` kwarg — supports three shapes:
            //  1. `model: @record` — simple; record is the local.
            //  2. `model: [@parent, Child.new]` — nested array;
            //     last element is the form's record, earlier
            //     elements scope the action URL.
            //  3. No `model:` kwarg: fall back to the view's
            //     primary arg (Rails partial convention).
            let model_expr = args.iter().find_map(|a| py_extract_kwarg(a, "model"));
            let model_nested: Option<Vec<Expr>> = model_expr.and_then(|e| match &*e.node {
                ExprNode::Array { elements, .. } if elements.len() >= 2 => {
                    Some(elements.clone())
                }
                _ => None,
            });
            let record_ref: Option<String> = if let Some(elems) = &model_nested {
                Some(emit_py_nested_form_record(&elems[elems.len() - 1]))
            } else {
                model_expr
                    .filter(|e| is_py_simple_expr(e, ctx))
                    .map(|e| emit_py_view_expr_raw(e, ctx))
                    .or_else(|| {
                        if !ctx.arg_name.is_empty() && ctx.is_local(&ctx.arg_name) {
                            Some(ctx.arg_name.clone())
                        } else {
                            None
                        }
                    })
            };
            let prefix = if let Some(elems) = &model_nested {
                py_nested_form_child_prefix(&elems[elems.len() - 1])
                    .unwrap_or_else(|| ctx.arg_name.clone())
            } else if !ctx.resource_dir.is_empty() {
                crate::naming::singularize(&ctx.resource_dir)
            } else {
                ctx.arg_name.clone()
            };

            let pname = params.first().map(|p| p.as_str()).unwrap_or("form");
            let is_persisted_expr = record_ref
                .as_deref()
                .map(|r| format!("({r}.id != 0)"))
                .unwrap_or_else(|| "False".to_string());
            let plural = if !ctx.resource_dir.is_empty() {
                ctx.resource_dir.clone()
            } else {
                crate::naming::pluralize_snake(&prefix)
            };
            let action_expr = match (&record_ref, &model_nested) {
                (Some(record), Some(elems)) => {
                    py_nested_form_path_expr(elems, ctx, record, &prefix)
                }
                (Some(record), None) => format!(
                    "({record}.id != 0) and {prefix}_path({record}.id) or {plural}_path()",
                ),
                (None, _) => format!("{plural}_path()"),
            };

            // Register form builder + bound record in inner ctx.
            let mut inner_ctx = ctx.with_locals([pname.to_string()]);
            if let Some(record) = &record_ref {
                inner_ctx
                    .form_records
                    .push((pname.to_string(), record.clone()));
            }
            let mut lines: Vec<String> = Vec::new();
            lines.push("_form_begin = len(_buf)".to_string());
            lines.push(format!(
                "{pname} = Helpers.FormBuilder({prefix:?}, {cls_expr}, {is_persisted_expr})"
            ));
            if let Some(record) = &record_ref {
                lines.push(format!(
                    "_buf += Helpers.error_messages_for({record}.errors, {prefix:?})"
                ));
            }
            for line in emit_py_view_body(body, &inner_ctx) {
                lines.push(line);
            }
            lines.push(format!(
                "_buf = _buf[:_form_begin] + Helpers.form_wrap({action_expr}, {is_persisted_expr}, {cls_expr}, _buf[_form_begin:])"
            ));
            lines.join("\n")
        }
        "content_for" => {
            // `<%= content_for :slot do %>...<% end %>` — stash the
            // block body into the slot; emit nothing inline. The
            // snapshot-and-slice pattern mirrors form_with.
            let slot = args.first().and_then(|a| match &*a.node {
                ExprNode::Lit { value: Literal::Sym { value } } => Some(value.as_str()),
                ExprNode::Lit { value: Literal::Str { value } } => Some(value.as_str()),
                _ => None,
            });
            let Some(slot) = slot else {
                let _ = cls_expr;
                return "_buf += \"\"".to_string();
            };
            let mut lines: Vec<String> = Vec::new();
            lines.push("_cf_begin = len(_buf)".to_string());
            for line in emit_py_view_body(body, ctx) {
                lines.push(line);
            }
            lines.push(format!(
                "Helpers.content_for_set({slot:?}, _buf[_cf_begin:])"
            ));
            lines.push("_buf = _buf[:_cf_begin]".to_string());
            lines.join("\n")
        }
        _ => {
            let _ = cls_expr;
            "_buf += \"\"".to_string()
        }
    }
}

// ── Nested form/URL element helpers (thin adapters around the
// shared `src/lower/view.rs` classifiers) ──────────────────────

fn emit_py_nested_form_record(el: &Expr) -> String {
    match crate::lower::classify_nested_form_child(el) {
        Some(crate::lower::NestedFormChild::ClassNew { class }) => {
            format!("{class}()")
        }
        Some(crate::lower::NestedFormChild::Local { name }) => name.to_string(),
        None => "None".to_string(),
    }
}

fn py_nested_form_child_prefix(el: &Expr) -> Option<String> {
    crate::lower::classify_nested_form_child(el).map(|k| k.prefix())
}

fn py_nested_element_parts(kind: &crate::lower::NestedUrlElement<'_>) -> (String, String) {
    match kind {
        crate::lower::NestedUrlElement::DirectLocal { name } => {
            ((*name).to_string(), format!("{name}.id"))
        }
        crate::lower::NestedUrlElement::Association { owner, assoc } => {
            ((*assoc).to_string(), format!("{owner}.{assoc}_id"))
        }
    }
}

/// Render a classified `ViewHelperKind` to a python `_buf += …`
/// statement. Returns None when arg shapes aren't renderable (the
/// caller falls through to the TODO placeholder).
fn emit_py_view_helper(
    kind: &crate::lower::ViewHelperKind<'_>,
    ctx: &PyViewCtx,
) -> Option<String> {
    use crate::lower::ViewHelperKind::*;
    match kind {
        CsrfMetaTags => Some("_buf += Helpers.csrf_meta_tags()".to_string()),
        CspMetaTag => Some("_buf += Helpers.csp_meta_tag()".to_string()),
        JavascriptImportmapTags => Some(
            "_buf += Helpers.javascript_importmap_tags(importmap.PINS, \"application\")"
                .to_string(),
        ),
        TurboStreamFrom { channel } => {
            if !is_py_simple_expr(channel, ctx) {
                return None;
            }
            let arg = emit_py_view_expr_raw(channel, ctx);
            Some(format!("_buf += Helpers.turbo_stream_from({arg})"))
        }
        DomId { record, prefix } => {
            let (singular, id_expr) = py_resolve_dom_id_record(record, ctx)?;
            match prefix {
                None => Some(format!(
                    "_buf += Helpers.dom_id({singular:?}, {id_expr})"
                )),
                Some(p) => {
                    let prefix_str = match &*p.node {
                        ExprNode::Lit { value: Literal::Sym { value } } => {
                            format!("{:?}", value.as_str())
                        }
                        ExprNode::Lit { value: Literal::Str { value } } => format!("{value:?}"),
                        _ if is_py_simple_expr(p, ctx) => emit_py_view_expr_raw(p, ctx),
                        _ => return None,
                    };
                    Some(format!(
                        "_buf += Helpers.dom_id({singular:?}, {id_expr}, {prefix_str})"
                    ))
                }
            }
        }
        Pluralize { count, word } => {
            if !is_py_simple_expr(count, ctx) || !is_py_simple_expr(word, ctx) {
                return None;
            }
            let c = emit_py_view_expr_raw(count, ctx);
            let w = emit_py_view_expr_raw(word, ctx);
            Some(format!("_buf += Helpers.pluralize({c}, {w})"))
        }
        Truncate { text, opts } => {
            if !is_py_simple_expr(text, ctx) {
                return None;
            }
            let t = emit_py_view_expr_raw(text, ctx);
            let opts_code = py_opts_from_expr(opts.as_deref(), ctx);
            Some(format!("_buf += Helpers.truncate({t}, {opts_code})"))
        }
        StylesheetLinkTag { name, opts } => {
            let opts_code = py_opts_from_expr(opts.as_deref(), ctx);
            // `stylesheet_link_tag :app` expands per-stylesheet.
            if let ExprNode::Lit { value: Literal::Sym { value } } = &*name.node {
                if value.as_str() == "app" && !ctx.stylesheets.is_empty() {
                    let lines: Vec<String> = ctx
                        .stylesheets
                        .iter()
                        .map(|n| format!(
                            "_buf += Helpers.stylesheet_link_tag({n:?}, **{opts_code})"
                        ))
                        .collect();
                    return Some(lines.join("\n_buf += \"\\n\"\n"));
                }
            }
            let name_expr = match &*name.node {
                ExprNode::Lit { value: Literal::Sym { value } } => format!("{:?}", value.as_str()),
                ExprNode::Lit { value: Literal::Str { value } } => format!("{value:?}"),
                _ => return None,
            };
            Some(format!(
                "_buf += Helpers.stylesheet_link_tag({name_expr}, **{opts_code})"
            ))
        }
        ContentForGetter { slot } => {
            Some(format!("_buf += Helpers.content_for_get({slot:?})"))
        }
        ContentForSetter { .. } => None,
        LinkTo { text, url, opts } => emit_py_link_or_button("link_to", text, url, *opts, ctx)
            .map(|call| format!("_buf += {call}")),
        ButtonTo { text, target, opts } => {
            emit_py_link_or_button("button_to", text, target, *opts, ctx)
                .map(|call| format!("_buf += {call}"))
        }
    }
}

fn py_resolve_dom_id_record(
    record: &Expr,
    ctx: &PyViewCtx,
) -> Option<(String, String)> {
    let name = match &*record.node {
        ExprNode::Var { name, .. } | ExprNode::Ivar { name } if ctx.is_local(name.as_str()) => {
            name.as_str().to_string()
        }
        ExprNode::Send {
            recv: None,
            method,
            args,
            block: None,
            ..
        } if args.is_empty() && ctx.is_local(method.as_str()) => method.as_str().to_string(),
        _ => return None,
    };
    let singular = crate::naming::singularize(&name);
    Some((singular, format!("{name}.id")))
}

fn emit_py_link_or_button(
    helper: &str,
    text: &Expr,
    url: &Expr,
    opts: Option<&Expr>,
    ctx: &PyViewCtx,
) -> Option<String> {
    if !is_py_simple_expr(text, ctx) {
        return None;
    }
    let text_expr = emit_py_view_expr_raw(text, ctx);
    let is_local = |n: &str| ctx.is_local(n);
    let url_kind = crate::lower::classify_view_url_arg(url, &is_local)?;
    let url_expr = match url_kind {
        crate::lower::ViewUrlArg::Literal { value } => format!("{value:?}"),
        crate::lower::ViewUrlArg::PathHelper { name, args } => {
            let args_s: Vec<String> = args.iter().map(|a| py_path_arg(a, ctx)).collect();
            format!("{name}({})", args_s.join(", "))
        }
        crate::lower::ViewUrlArg::RecordRef { name } => {
            format!("{name}_path({name}.id)")
        }
        crate::lower::ViewUrlArg::NestedArray { elements } => {
            py_emit_nested_path(elements, ctx)?
        }
    };
    let opts_code = py_opts_from_expr(opts, ctx);
    Some(format!(
        "Helpers.{helper}({text_expr}, {url_expr}, {opts_code})"
    ))
}

fn py_path_arg(arg: &Expr, ctx: &PyViewCtx) -> String {
    match &*arg.node {
        ExprNode::Var { name, .. } | ExprNode::Ivar { name } if ctx.is_local(name.as_str()) => {
            format!("{}.id", name.as_str())
        }
        ExprNode::Send { recv: None, method, args, block: None, .. }
            if args.is_empty() && ctx.is_local(method.as_str()) =>
        {
            format!("{}.id", method.as_str())
        }
        _ => emit_py_view_expr_raw(arg, ctx),
    }
}

fn py_emit_nested_path(elements: &[Expr], ctx: &PyViewCtx) -> Option<String> {
    let is_local = |n: &str| ctx.is_local(n);
    let mut singulars: Vec<String> = Vec::new();
    let mut args: Vec<String> = Vec::new();
    for el in elements {
        let kind = crate::lower::classify_nested_url_element(el, &is_local)?;
        let (singular, id_expr) = py_nested_element_parts(&kind);
        singulars.push(singular);
        args.push(id_expr);
    }
    let name = format!("{}_path", singulars.join("_"));
    Some(format!("{name}({})", args.join(", ")))
}

fn py_opts_from_expr(opts: Option<&Expr>, ctx: &PyViewCtx) -> String {
    match opts.map(|e| &*e.node) {
        Some(ExprNode::Hash { entries, .. }) => py_hash_to_dict(entries, ctx),
        _ => "{}".to_string(),
    }
}

fn py_hash_to_dict(entries: &[(Expr, Expr)], ctx: &PyViewCtx) -> String {
    let mut items: Vec<(String, String)> = Vec::new();
    for (k, v) in entries {
        let key = match &*k.node {
            ExprNode::Lit { value: Literal::Sym { value } } => value.as_str().to_string(),
            ExprNode::Lit { value: Literal::Str { value } } => value.clone(),
            _ => continue,
        };
        // `data: {turbo_confirm: "..."}` → flatten to `data-turbo-confirm: "..."`.
        if key == "data" {
            if let ExprNode::Hash { entries: data_entries, .. } = &*v.node {
                for (dk, dv) in data_entries {
                    let dk_str = match &*dk.node {
                        ExprNode::Lit { value: Literal::Sym { value } } => {
                            value.as_str().replace('_', "-")
                        }
                        ExprNode::Lit { value: Literal::Str { value } } => {
                            value.replace('_', "-")
                        }
                        _ => continue,
                    };
                    let dv_s = py_opt_value(dv, ctx);
                    items.push((format!("data-{dk_str}"), dv_s));
                }
                continue;
            }
        }
        let val = if key == "class" {
            py_class_value(v, ctx)
        } else {
            py_opt_value(v, ctx)
        };
        items.push((key, val));
    }
    let parts: Vec<String> = items
        .into_iter()
        .map(|(k, v)| format!("{k:?}: {v}"))
        .collect();
    format!("{{{}}}", parts.join(", "))
}

fn py_opt_value(v: &Expr, ctx: &PyViewCtx) -> String {
    match &*v.node {
        ExprNode::Lit { value: Literal::Str { value } } => format!("{value:?}"),
        ExprNode::Lit { value: Literal::Int { value } } => format!("{value}"),
        ExprNode::Lit { value: Literal::Sym { value } } => format!("{:?}", value.as_str()),
        ExprNode::Array { elements, .. } => match elements.first() {
            Some(first) => match &*first.node {
                ExprNode::Lit { value: Literal::Str { value } } => format!("{value:?}"),
                _ => "\"\"".to_string(),
            },
            None => "\"\"".to_string(),
        },
        _ if is_py_simple_expr(v, ctx) => emit_py_view_expr_raw(v, ctx),
        _ => "\"\"".to_string(),
    }
}

fn py_class_value(v: &Expr, ctx: &PyViewCtx) -> String {
    let is_local = |n: &str| ctx.is_local(n);
    let simple_as_py = |e: &Expr| -> Option<String> {
        if is_py_simple_expr(e, ctx) {
            Some(match &*e.node {
                ExprNode::Lit { value: Literal::Str { value } } => format!("{value:?}"),
                _ => emit_py_view_expr_raw(e, ctx),
            })
        } else {
            None
        }
    };
    match crate::lower::classify_class_value(v, &is_local) {
        crate::lower::ClassValueShape::Simple { expr } => {
            simple_as_py(expr).unwrap_or_else(|| "\"\"".to_string())
        }
        crate::lower::ClassValueShape::Conditional { base, clauses } => {
            let Some(base_py) = simple_as_py(base) else {
                return "\"\"".to_string();
            };
            if clauses.is_empty() {
                return base_py;
            }
            let extras: Vec<String> = clauses
                .iter()
                .map(|(cls_text, pred)| {
                    let cond = py_render_errors_field_predicate(pred);
                    format!(" + (\" {cls_text}\" if {cond} else \"\")")
                })
                .collect();
            format!("({base_py}{})", extras.join(""))
        }
        crate::lower::ClassValueShape::Unknown => "\"\"".to_string(),
    }
}

fn py_render_errors_field_predicate(pred: &crate::lower::ErrorsFieldPredicate<'_>) -> String {
    let call = format!(
        "Helpers.field_has_error({}.errors, {:?})",
        pred.record, pred.field,
    );
    if pred.expect_present {
        call
    } else {
        format!("not {call}")
    }
}

fn emit_py_form_builder_call(
    recv: &str,
    kind: crate::lower::FormBuilderMethod,
    args: &[Expr],
    ctx: &PyViewCtx,
) -> Option<String> {
    use crate::lower::FormBuilderMethod::*;
    let (field, opts_entries) = crate::lower::classify_form_builder_args(args);
    let field = field.map(str::to_string);
    let opts = opts_entries
        .map(|entries| py_hash_to_dict(entries, ctx))
        .unwrap_or_else(|| "{}".to_string());
    match kind {
        Label => {
            let field = field?;
            Some(format!("{recv}.label({field:?}, {opts})"))
        }
        TextField | TextArea => {
            let method = if matches!(kind, TextField) { "text_field" } else { "textarea" };
            let field = field?;
            let value_expr = ctx
                .form_records
                .iter()
                .find(|(name, _)| name == recv)
                .and_then(|(_, record)| {
                    if ctx.local_has_attr(record, &field) {
                        Some(format!("{record}.{field}"))
                    } else {
                        None
                    }
                })
                .unwrap_or_else(|| "\"\"".to_string());
            Some(format!(
                "{recv}.{method}({field:?}, {value_expr}, {opts})"
            ))
        }
        Submit => {
            // First positional string arg is the custom label.
            let label_str = args.iter().find_map(|a| match &*a.node {
                ExprNode::Lit { value: Literal::Str { value } } => Some(value.clone()),
                _ => None,
            });
            let opts = if let Some(lbl) = label_str {
                format!("{{**{opts}, \"label\": {lbl:?}}}")
            } else {
                opts
            };
            Some(format!("{recv}.submit({opts})"))
        }
    }
}


fn py_nested_form_path_expr(
    elems: &[Expr],
    ctx: &PyViewCtx,
    record_ref: &str,
    child_prefix: &str,
) -> String {
    let is_local = |n: &str| ctx.is_local(n);
    let mut parent_ids: Vec<String> = Vec::new();
    let mut parent_singulars: Vec<String> = Vec::new();
    for parent in &elems[..elems.len() - 1] {
        let Some(kind) = crate::lower::classify_nested_url_element(parent, &is_local)
        else {
            return "\"\"".to_string();
        };
        let (singular, id_expr) = py_nested_element_parts(&kind);
        parent_singulars.push(singular);
        parent_ids.push(id_expr);
    }
    let member_name = format!(
        "{}_{}_path",
        parent_singulars.join("_"),
        child_prefix,
    );
    let child_plural = crate::naming::pluralize_snake(child_prefix);
    let collection_name = format!(
        "{}_{}_path",
        parent_singulars.join("_"),
        child_plural,
    );
    let parent_args = parent_ids.join(", ");
    let member_args = if parent_args.is_empty() {
        format!("{record_ref}.id")
    } else {
        format!("{parent_args}, {record_ref}.id")
    };
    format!(
        "({record_ref}.id != 0) and {member_name}({member_args}) or {collection_name}({parent_args})",
    )
}

fn emit_py_render_call(arg: &Expr, ctx: &PyViewCtx) -> String {
    match &*arg.node {
        ExprNode::Var { name, .. } | ExprNode::Ivar { name }
            if ctx.is_local(name.as_str()) =>
        {
            let singular = crate::naming::singularize(name.as_str());
            let partial_fn = format!("render_{}_{singular}", name.as_str());
            let coll = name.to_string();
            format!("_buf += \"\".join({partial_fn}(_r) for _r in {coll})")
        }
        ExprNode::Send { recv: Some(r), method, args, .. }
            if args.is_empty()
                && matches!(&*r.node, ExprNode::Var { .. } | ExprNode::Ivar { .. }) =>
        {
            let assoc_plural = method.as_str();
            let singular = crate::naming::singularize(assoc_plural);
            let partial_fn = format!("render_{assoc_plural}_{singular}");
            let parent_name = match &*r.node {
                ExprNode::Var { name, .. } | ExprNode::Ivar { name } => name.to_string(),
                _ => unreachable!(),
            };
            format!(
                "_buf += \"\".join({partial_fn}(_c) for _c in {parent_name}.{assoc_plural})"
            )
        }
        _ => "_buf += \"\"  # TODO ERB: render".to_string(),
    }
}

fn py_extract_kwarg<'a>(arg: &'a Expr, key: &str) -> Option<&'a Expr> {
    if let ExprNode::Hash { entries, .. } = &*arg.node {
        for (k, v) in entries {
            if let ExprNode::Lit { value: Literal::Sym { value } } = &*k.node {
                if value.as_str() == key {
                    return Some(v);
                }
            }
        }
    }
    None
}

fn unwrap_to_s_py(expr: &Expr) -> &Expr {
    if let ExprNode::Send { recv: Some(inner), method, args, .. } = &*expr.node {
        if method.as_str() == "to_s" && args.is_empty() {
            return inner;
        }
    }
    expr
}

fn is_py_simple_expr(expr: &Expr, ctx: &PyViewCtx) -> bool {
    match &*expr.node {
        ExprNode::Lit { .. } => true,
        ExprNode::Var { name, .. } | ExprNode::Ivar { name } => {
            ctx.is_local(name.as_str())
        }
        // Partial-scope local parsed as bare Send — same as rust's
        // is_simple_view_expr: treat as a simple local-read.
        ExprNode::Send { recv: None, method, args, block: None, .. }
            if args.is_empty() && ctx.is_local(method.as_str()) =>
        {
            true
        }
        ExprNode::Send { recv: Some(r), method, args, block, .. } => {
            if !args.is_empty() || block.is_some() {
                return false;
            }
            let clean = method.as_str().trim_end_matches('?').trim_end_matches('!');
            if clean.is_empty() {
                return false;
            }
            let recv_local = match &*r.node {
                ExprNode::Var { name, .. } | ExprNode::Ivar { name } => Some(name.as_str()),
                ExprNode::Send {
                    recv: None,
                    method: m,
                    args: ra,
                    block: None,
                    ..
                } if ra.is_empty() && ctx.is_local(m.as_str()) => Some(m.as_str()),
                _ => None,
            };
            if let Some(local_name) = recv_local {
                if ctx.local_has_attr(local_name, clean) {
                    return true;
                }
                if ctx.is_local(local_name)
                    && matches!(
                        method.as_str(),
                        "any?" | "none?" | "present?" | "empty?"
                    )
                {
                    return true;
                }
                if ctx
                    .resolve_has_many_on_local(local_name, method.as_str())
                    .is_some()
                {
                    return true;
                }
            }
            // Chained simple Sends (`article.comments.size`).
            if is_py_simple_expr(r, ctx) {
                return true;
            }
            false
        }
        ExprNode::StringInterp { parts } => parts.iter().all(|p| match p {
            crate::expr::InterpPart::Text { .. } => true,
            crate::expr::InterpPart::Expr { expr } => is_py_simple_expr(expr, ctx),
        }),
        _ => false,
    }
}

fn emit_py_view_expr_raw(expr: &Expr, ctx: &PyViewCtx) -> String {
    match &*expr.node {
        ExprNode::Lit { value } => emit_literal(value),
        ExprNode::Var { name, .. } | ExprNode::Ivar { name } => name.to_string(),
        ExprNode::Send { recv, method, args, .. } => {
            let method_s = method.as_str();
            // Bare local ref (`article` in partial scope).
            if recv.is_none()
                && args.is_empty()
                && ctx.is_local(method_s)
            {
                return method_s.to_string();
            }
            if let Some(r) = recv {
                if args.is_empty() {
                    // has_many association read: `article.comments`
                    // → inline filter query.
                    let owner_local = match &*r.node {
                        ExprNode::Var { name, .. } | ExprNode::Ivar { name }
                            if ctx.is_local(name.as_str()) =>
                        {
                            Some(name.as_str().to_string())
                        }
                        ExprNode::Send {
                            recv: None,
                            method: m,
                            args: ra,
                            block: None,
                            ..
                        } if ra.is_empty() && ctx.is_local(m.as_str()) => {
                            Some(m.as_str().to_string())
                        }
                        _ => None,
                    };
                    if let Some(owner) = &owner_local {
                        if let Some((target_class, fk)) =
                            ctx.resolve_has_many_on_local(owner, method_s)
                        {
                            return format!(
                                "[__r for __r in {target_class}.all() if __r.{fk} == {owner}.id]",
                            );
                        }
                    }
                    // Collection predicates on any recv.
                    match method_s {
                        "any?" | "present?" => {
                            let recv_s = emit_py_view_expr_raw(r, ctx);
                            return format!("(len({recv_s}) > 0)");
                        }
                        "none?" | "empty?" => {
                            let recv_s = emit_py_view_expr_raw(r, ctx);
                            return format!("(len({recv_s}) == 0)");
                        }
                        "size" | "count" | "length" => {
                            let recv_s = emit_py_view_expr_raw(r, ctx);
                            return format!("len({recv_s})");
                        }
                        "full_message" => {
                            let recv_s = emit_py_view_expr_raw(r, ctx);
                            return format!("{recv_s}.full_message");
                        }
                        _ => {}
                    }
                }
                let recv_s = emit_py_view_expr_raw(r, ctx);
                let clean = method_s.trim_end_matches('?').trim_end_matches('!');
                if args.is_empty() {
                    return format!("{recv_s}.{clean}");
                }
                let args_s: Vec<String> = args
                    .iter()
                    .map(|a| emit_py_view_expr_raw(a, ctx))
                    .collect();
                return format!("{recv_s}.{clean}({})", args_s.join(", "));
            }
            // No recv, no local match — bare fn call.
            let args_s: Vec<String> = args
                .iter()
                .map(|a| emit_py_view_expr_raw(a, ctx))
                .collect();
            if args.is_empty() {
                format!("Helpers.{method_s}()")
            } else {
                format!("Helpers.{method_s}({})", args_s.join(", "))
            }
        }
        ExprNode::StringInterp { parts } => {
            use crate::expr::InterpPart;
            let mut out = String::from("f\"");
            for p in parts {
                match p {
                    InterpPart::Text { value } => {
                        for c in value.chars() {
                            if c == '"' || c == '\\' {
                                out.push('\\');
                            }
                            out.push(c);
                        }
                    }
                    InterpPart::Expr { expr } => {
                        out.push('{');
                        out.push_str(&emit_py_view_expr_raw(expr, ctx));
                        out.push('}');
                    }
                }
            }
            out.push('"');
            out
        }
        _ => "\"\"".to_string(),
    }
}

fn py_collect_ivar_names(expr: &Expr) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    py_collect_ivars_into(expr, &mut out);
    out
}

fn py_collect_ivars_into(expr: &Expr, out: &mut Vec<String>) {
    match &*expr.node {
        ExprNode::Ivar { name } => {
            let n = name.to_string();
            if !out.iter().any(|existing| existing == &n) {
                out.push(n);
            }
        }
        ExprNode::Assign { target, value } => {
            if let LValue::Ivar { name } = target {
                let n = name.to_string();
                if !out.iter().any(|existing| existing == &n) {
                    out.push(n);
                }
            }
            py_collect_ivars_into(value, out);
        }
        ExprNode::Send { recv, args, block, .. } => {
            if let Some(r) = recv {
                py_collect_ivars_into(r, out);
            }
            for a in args {
                py_collect_ivars_into(a, out);
            }
            if let Some(b) = block {
                py_collect_ivars_into(b, out);
            }
        }
        ExprNode::Seq { exprs } | ExprNode::Array { elements: exprs, .. } => {
            for e in exprs {
                py_collect_ivars_into(e, out);
            }
        }
        ExprNode::Hash { entries, .. } => {
            for (k, v) in entries {
                py_collect_ivars_into(k, out);
                py_collect_ivars_into(v, out);
            }
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            py_collect_ivars_into(cond, out);
            py_collect_ivars_into(then_branch, out);
            py_collect_ivars_into(else_branch, out);
        }
        ExprNode::BoolOp { left, right, .. } => {
            py_collect_ivars_into(left, out);
            py_collect_ivars_into(right, out);
        }
        ExprNode::Lambda { body, .. } => py_collect_ivars_into(body, out),
        ExprNode::StringInterp { parts } => {
            for p in parts {
                if let crate::expr::InterpPart::Expr { expr } = p {
                    py_collect_ivars_into(expr, out);
                }
            }
        }
        _ => {}
    }
}
