# The IPAddr port's RULE TABLE, address by address.
#
# A FRAMEWORK test (`tests/runtime_ruby_unit.rs` runs every file under
# `runtime/ruby/test/` on each `cargo test`), not one that ships into an
# emitted tree — the CRuby tree replaces this file with Ruby's own
# stdlib (`ruby_runtime_files`), so a shipped copy would be asserting
# about the stdlib there and about the port under spinel, from one set
# of expectations. Here it is unambiguously the port.
#
# WHY THIS FILE EXISTS. `runtime/ruby/ipaddr.rb` is a PORT — the
# representation is ours (octets, because no strict target has a 128-bit
# integer) but every prefix is Ruby's stdlib ipaddr.rb verbatim. A port
# is exactly the thing that fails quietly: an address wrongly called
# public is a ban that does not take, and nothing raises.
#
# The expectations below are the STDLIB's answers, generated by running
# Ruby 4.0.5's own `IPAddr` over this list:
#
#     ruby -ripaddr -e 'ADDRS.each { |a| i = IPAddr.new(a)
#       puts [a, i.loopback?, i.private?, i.link_local?, i.ipv4?].inspect }'
#
# Regenerate the same way if the table ever needs extending; do not
# hand-write an expectation.
require_relative "test_helper"
require_relative "../ipaddr"

class IPAddrTest < Minitest::Test
  # [address, loopback?, private?, link_local?, ipv4?]
  CASES = [
    ["0.0.0.0", false, false, false, true],
    ["8.8.8.8", false, false, false, true],
    ["127.0.0.1", true, false, false, true],
    ["127.255.255.255", true, false, false, true],
    ["126.255.255.255", false, false, false, true],
    ["128.0.0.1", false, false, false, true],
    ["10.0.0.0", false, true, false, true],
    ["10.255.255.255", false, true, false, true],
    ["9.255.255.255", false, false, false, true],
    ["11.0.0.0", false, false, false, true],
    ["172.15.255.255", false, false, false, true],
    ["172.16.0.0", false, true, false, true],
    ["172.31.255.255", false, true, false, true],
    ["172.32.0.0", false, false, false, true],
    ["192.168.0.0", false, true, false, true],
    ["192.168.255.255", false, true, false, true],
    ["192.167.255.255", false, false, false, true],
    ["192.169.0.0", false, false, false, true],
    ["169.254.0.0", false, false, true, true],
    ["169.254.255.255", false, false, true, true],
    ["169.253.255.255", false, false, false, true],
    ["169.255.0.0", false, false, false, true],
    ["255.255.255.255", false, false, false, true],
    ["::1", true, false, false, false],
    ["::", false, false, false, false],
    ["fe80::1", false, false, true, false],
    ["febf::1", false, false, true, false],
    ["fec0::1", false, false, false, false],
    ["fe7f::1", false, false, false, false],
    ["fc00::", false, true, false, false],
    ["fdff::1", false, true, false, false],
    ["fbff::1", false, false, false, false],
    ["fe00::1", false, false, false, false],
    ["2001:db8::1", false, false, false, false],
    ["::ffff:127.0.0.1", true, false, false, false],
    ["::ffff:10.1.2.3", false, true, false, false],
    ["::ffff:192.168.1.1", false, true, false, false],
    ["::ffff:169.254.1.1", false, false, true, false],
    ["::ffff:8.8.8.8", false, false, false, false],
    ["::ffff:172.16.0.1", false, true, false, false],
    ["::ffff:172.32.0.1", false, false, false, false],
    ["1:2:3:4:5:6:7:8", false, false, false, false],
  ].freeze

  def test_every_predicate_matches_the_stdlib
    CASES.each do |addr, loopback, private_addr, link_local, v4|
      ip = IPAddr.new(addr)
      assert_equal loopback, ip.loopback?, "#{addr}.loopback?"
      assert_equal private_addr, ip.private?, "#{addr}.private?"
      assert_equal link_local, ip.link_local?, "#{addr}.link_local?"
      assert_equal v4, ip.ipv4?, "#{addr}.ipv4?"
    end
  end

  # The boundaries are the whole content of the table — an off-by-one on
  # any of them is a rule that reads right and answers wrong. Every row
  # above sits on one; this asserts the list has not been trimmed to the
  # easy cases.
  def test_the_table_covers_both_sides_of_every_boundary
    assert_operator CASES.length, :>=, 40
  end

  REJECTED = [
    "", "1.2.3", "1.2.3.4.5", "1.2.3.256", "1.2.3.a",
    "::1::2", "fffff::1", "g::1", "1:2:3:4:5:6:7", "1:2:3:4:5:6:7:8:9",
    "hello", "300.1.1.1"
  ].freeze

  def test_a_malformed_address_raises_the_error_the_app_rescues
    REJECTED.each do |addr|
      assert_raises(IPAddr::InvalidAddressError, addr.inspect) { IPAddr.new(addr) }
    end
  end

  # ── prefixes ──────────────────────────────────────────────────────
  #
  # THE CIDR LIST IS CAMPFIRE'S, verbatim from
  # `RestrictedHTTP::PrivateNetworkGuard` — the constant that runs in a
  # CLASS BODY and took the binary down at LOAD before this landed. The
  # probes are one address inside each range plus the neighbours that
  # must fall outside it, and every expectation below was generated by
  # running Ruby 4.0.5's own IPAddr over the same lists:
  #
  #     ruby -ripaddr -e 'NETS.each { |c| n = IPAddr.new(c)
  #       puts [c, n.prefix, n.to_s,
  #             PROBES.select { |p| n.include?(IPAddr.new(p)) }].inspect }'
  #
  # Do not hand-write an expectation here either.

  V4_PROBES = %w[0.1.2.3 1.2.3.4 100.64.0.1 100.127.255.255 100.128.0.0
                 192.0.0.7 192.0.2.99 198.18.5.5 198.20.0.0 203.0.113.9
                 239.1.1.1 240.0.0.1 8.8.8.8].freeze

  V6_PROBES = %w[:: ::1 100::1 2001::9 2001:2::5 2001:db8::1 2002::1
                 fec0::1 ff02::1 2606:4700::1 64:ff9b::1.2.3.4
                 64:ff9b:1::9].freeze

  # network => the probes the stdlib says are INSIDE it. Every probe not
  # listed must be outside, which is what makes a too-permissive mask
  # fail as loudly as a too-strict one.
  V4_MEMBERS = {
    "0.0.0.0/8" => %w[0.1.2.3],
    "100.64.0.0/10" => %w[100.64.0.1 100.127.255.255],
    "192.0.0.0/24" => %w[192.0.0.7],
    "192.0.2.0/24" => %w[192.0.2.99],
    "192.88.99.0/24" => %w[],
    "198.18.0.0/15" => %w[198.18.5.5],
    "198.51.100.0/24" => %w[],
    "203.0.113.0/24" => %w[203.0.113.9],
    "224.0.0.0/4" => %w[239.1.1.1],
    "240.0.0.0/4" => %w[240.0.0.1],
  }.freeze

  V6_MEMBERS = {
    "::/128" => %w[::],
    "100::/64" => %w[100::1],
    "2001::/32" => %w[2001::9],
    "2001:2::/48" => %w[2001:2::5],
    "2001:db8::/32" => %w[2001:db8::1],
    "2002::/16" => %w[2002::1],
    "fec0::/10" => %w[fec0::1],
    "ff00::/8" => %w[ff02::1],
    "64:ff9b::/96" => %w[64:ff9b::1.2.3.4],
    "64:ff9b:1::/48" => %w[64:ff9b:1::9],
  }.freeze

  def test_include_matches_the_stdlib_for_every_campfire_range
    { V4_MEMBERS => V4_PROBES, V6_MEMBERS => V6_PROBES }.each do |members, probes|
      members.each do |cidr, inside|
        net = IPAddr.new(cidr)
        probes.each do |probe|
          assert_equal inside.include?(probe),
                       net.include?(IPAddr.new(probe)),
                       "#{cidr}.include?(#{probe})"
        end
      end
    end
  end

  def test_prefix_is_the_declared_length_and_defaults_to_the_family_width
    assert_equal 8, IPAddr.new("0.0.0.0/8").prefix
    assert_equal 10, IPAddr.new("100.64.0.0/10").prefix
    assert_equal 96, IPAddr.new("64:ff9b::/96").prefix
    assert_equal 128, IPAddr.new("::/128").prefix
    assert_equal 32, IPAddr.new("1.2.3.4").prefix
    assert_equal 128, IPAddr.new("::1").prefix
  end

  # The address is MASKED on the way in, as the stdlib does. campfire's
  # own CIDRs are all already canonical, so they cannot catch a broken
  # mask — these can.
  def test_host_bits_below_the_prefix_are_cleared
    assert_equal "10.0.0.0", IPAddr.new("10.1.2.3/8").to_s
    assert_equal "10.1.0.0", IPAddr.new("10.1.2.3/16").to_s
    assert_equal "10.1.2.0", IPAddr.new("10.1.2.3/24").to_s
    assert_equal "10.1.2.3", IPAddr.new("10.1.2.3/32").to_s
    assert_equal "0.0.0.0", IPAddr.new("255.255.255.255/0").to_s
    # A prefix that lands mid-octet — the arm neither of the two above
    # exercises.
    assert_equal "10.1.2.240", IPAddr.new("10.1.2.255/28").to_s
    assert_equal "192.168.0.0", IPAddr.new("192.168.1.1/23").to_s
  end

  # A network never contains an address of the other family, not even
  # the mapped form of one (measured against the stdlib).
  def test_a_network_does_not_span_families
    refute IPAddr.new("10.0.0.0/8").include?(IPAddr.new("::1"))
    refute IPAddr.new("10.0.0.0/8").include?(IPAddr.new("::ffff:10.1.2.3"))
    refute IPAddr.new("::/0").include?(IPAddr.new("1.2.3.4"))
  end

  # `::a.b.c.d`, the deprecated IPv4-COMPATIBLE form — not the mapped
  # one, whose octets 10 and 11 are 0xff. `::` and `::1` are excluded,
  # matching the stdlib's `@addr < 2` test.
  IPV4_COMPAT = {
    "1.2.3.4" => false,
    "::" => false,
    "::1" => false,
    "::0.0.0.1" => false,
    "::1.2.3.4" => true,
    "::ffff:1.2.3.4" => false,
    "64:ff9b::1.2.3.4" => false,
  }.freeze

  def test_ipv4_compat_matches_the_stdlib
    IPV4_COMPAT.each do |addr, want|
      assert_equal want, IPAddr.new(addr).ipv4_compat?, addr
    end
  end

  # STILL DIVERGENT, asserted so it cannot drift into silence: the
  # stdlib's dotted-quad netmask spelling is declined rather than
  # approximated, and a prefix wider than the family raises the error
  # campfire rescues instead of the stdlib's `InvalidPrefixError`.
  BAD_PREFIXES = [
    "1.2.3.4/255.255.0.0", "1.2.3.4/", "1.2.3.4/abc", "1.2.3.4/33",
    "::1/129", "1.2.3.4/-1"
  ].freeze

  def test_a_prefix_this_port_cannot_answer_raises
    BAD_PREFIXES.each do |addr|
      assert_raises(IPAddr::InvalidAddressError, addr.inspect) { IPAddr.new(addr) }
    end
  end

  def test_ipv4_round_trips_through_to_s
    assert_equal "192.168.1.9", IPAddr.new("192.168.1.9").to_s
  end

  def test_ipv6_renders_uncompressed
    assert_equal "0000:0000:0000:0000:0000:0000:0000:0001", IPAddr.new("::1").to_s
  end
end
