# The IPAddr port's RULE TABLE, address by address.
#
# A FRAMEWORK test (`tests/runtime_ruby_unit.rs` runs every file under
# `runtime/ruby/test/` on each `cargo test`), not one that ships into an
# emitted tree — the CRuby tree replaces this file with Ruby's own
# stdlib (`ruby_runtime_files`), so a shipped copy would be asserting
# about the stdlib there and about the port under spinel, from one set
# of expectations. Here it is unambiguously the port.
#
# WHY THIS FILE EXISTS. `runtime/ruby/ipaddr.rb` is a PORT — the
# representation is ours (octets, because no strict target has a 128-bit
# integer) but every prefix is Ruby's stdlib ipaddr.rb verbatim. A port
# is exactly the thing that fails quietly: an address wrongly called
# public is a ban that does not take, and nothing raises.
#
# The expectations below are the STDLIB's answers, generated by running
# Ruby 4.0.5's own `IPAddr` over this list:
#
#     ruby -ripaddr -e 'ADDRS.each { |a| i = IPAddr.new(a)
#       puts [a, i.loopback?, i.private?, i.link_local?, i.ipv4?].inspect }'
#
# Regenerate the same way if the table ever needs extending; do not
# hand-write an expectation.
require_relative "test_helper"
require_relative "../ipaddr"

class IPAddrTest < Minitest::Test
  # [address, loopback?, private?, link_local?, ipv4?]
  CASES = [
    ["0.0.0.0", false, false, false, true],
    ["8.8.8.8", false, false, false, true],
    ["127.0.0.1", true, false, false, true],
    ["127.255.255.255", true, false, false, true],
    ["126.255.255.255", false, false, false, true],
    ["128.0.0.1", false, false, false, true],
    ["10.0.0.0", false, true, false, true],
    ["10.255.255.255", false, true, false, true],
    ["9.255.255.255", false, false, false, true],
    ["11.0.0.0", false, false, false, true],
    ["172.15.255.255", false, false, false, true],
    ["172.16.0.0", false, true, false, true],
    ["172.31.255.255", false, true, false, true],
    ["172.32.0.0", false, false, false, true],
    ["192.168.0.0", false, true, false, true],
    ["192.168.255.255", false, true, false, true],
    ["192.167.255.255", false, false, false, true],
    ["192.169.0.0", false, false, false, true],
    ["169.254.0.0", false, false, true, true],
    ["169.254.255.255", false, false, true, true],
    ["169.253.255.255", false, false, false, true],
    ["169.255.0.0", false, false, false, true],
    ["255.255.255.255", false, false, false, true],
    ["::1", true, false, false, false],
    ["::", false, false, false, false],
    ["fe80::1", false, false, true, false],
    ["febf::1", false, false, true, false],
    ["fec0::1", false, false, false, false],
    ["fe7f::1", false, false, false, false],
    ["fc00::", false, true, false, false],
    ["fdff::1", false, true, false, false],
    ["fbff::1", false, false, false, false],
    ["fe00::1", false, false, false, false],
    ["2001:db8::1", false, false, false, false],
    ["::ffff:127.0.0.1", true, false, false, false],
    ["::ffff:10.1.2.3", false, true, false, false],
    ["::ffff:192.168.1.1", false, true, false, false],
    ["::ffff:169.254.1.1", false, false, true, false],
    ["::ffff:8.8.8.8", false, false, false, false],
    ["::ffff:172.16.0.1", false, true, false, false],
    ["::ffff:172.32.0.1", false, false, false, false],
    ["1:2:3:4:5:6:7:8", false, false, false, false],
  ].freeze

  def test_every_predicate_matches_the_stdlib
    CASES.each do |addr, loopback, private_addr, link_local, v4|
      ip = IPAddr.new(addr)
      assert_equal loopback, ip.loopback?, "#{addr}.loopback?"
      assert_equal private_addr, ip.private?, "#{addr}.private?"
      assert_equal link_local, ip.link_local?, "#{addr}.link_local?"
      assert_equal v4, ip.ipv4?, "#{addr}.ipv4?"
    end
  end

  # The boundaries are the whole content of the table — an off-by-one on
  # any of them is a rule that reads right and answers wrong. Every row
  # above sits on one; this asserts the list has not been trimmed to the
  # easy cases.
  def test_the_table_covers_both_sides_of_every_boundary
    assert_operator CASES.length, :>=, 40
  end

  REJECTED = [
    "", "1.2.3", "1.2.3.4.5", "1.2.3.256", "1.2.3.a",
    "::1::2", "fffff::1", "g::1", "1:2:3:4:5:6:7", "1:2:3:4:5:6:7:8:9",
    "hello", "300.1.1.1"
  ].freeze

  def test_a_malformed_address_raises_the_error_the_app_rescues
    REJECTED.each do |addr|
      assert_raises(IPAddr::InvalidAddressError, addr.inspect) { IPAddr.new(addr) }
    end
  end

  # The one place this port DIVERGES from the stdlib, asserted so it
  # cannot drift into silence: Ruby accepts a prefix and masks the
  # address; we have no netmask, so we reject rather than answer about
  # `10.0.0.0` when the caller wrote `10.0.0.0/8`.
  def test_a_prefix_is_rejected_rather_than_silently_masked
    assert_raises(IPAddr::InvalidAddressError) { IPAddr.new("1.2.3.4/24") }
  end

  def test_ipv4_round_trips_through_to_s
    assert_equal "192.168.1.9", IPAddr.new("192.168.1.9").to_s
  end

  def test_ipv6_renders_uncompressed
    assert_equal "0000:0000:0000:0000:0000:0000:0000:0001", IPAddr.new("::1").to_s
  end
end
