# The Surfguard port's RULE TABLE, address by address.
#
# A FRAMEWORK test (`tests/runtime_ruby_unit.rs` runs every file under
# `runtime/ruby/test/` on each `cargo test`), not one that ships into an
# emitted tree.
#
# WHY THIS FILE EXISTS. `runtime/ruby/surfguard.rb` is a PORT of
# basecamp/surfguard, and unlike `ipaddr.rb` it has no stdlib twin on
# ANY target to fall back on — the gem is a git dependency, so no lane
# runs the original. A port with no twin is exactly the thing that fails
# quietly: an address wrongly called public is an SSRF fetch that
# should not have happened, and nothing raises.
#
# The expectations below are the GEM's answers, generated by running
# surfguard at the revision campfire's Gemfile.lock pins
# (910be917fd0ab782c5ea939698d44f26694a501d) over this list:
#
#     ruby -Ilib -rsurfguard -e 'ADDRS.each { |a|
#       puts [a, Surfguard.blocked_address?(a)].inspect }'
#
# Regenerate the same way if the table ever needs extending; do not
# hand-write an expectation. (The one time that rule was broken on the
# IPAddr port, the hand-written row was the only red.)
#
# The list covers, in order: public v4; every DISALLOWED_IPV4 range and
# the addresses either side of each boundary; v6 loopback / ULA /
# link-local / site-local / multicast and every DISALLOWED_IPV6 range;
# a public v6; IPv4-mapped and IPv4-compatible (refused whatever they
# wrap); NAT64 well-known (decoded) and RFC 8215 local-use (refused
# whole); SIIT `::ffff:0:0:0/96` (decoded); and a malformed string,
# which errs closed.
require_relative "test_helper"
require_relative "../surfguard"

class SurfguardTest < Minitest::Test
  # [address, blocked?]
  CASES = [
    ["8.8.8.8", false],
    ["1.1.1.1", false],
    ["93.184.216.34", false],
    ["142.250.185.206", false],
    ["0.0.0.0", true],
    ["0.255.255.255", true],
    ["1.0.0.0", false],
    ["10.0.0.0", true],
    ["10.255.255.255", true],
    ["9.255.255.255", false],
    ["11.0.0.0", false],
    ["100.64.0.0", true],
    ["100.127.255.255", true],
    ["100.63.255.255", false],
    ["100.128.0.0", false],
    ["127.0.0.1", true],
    ["127.255.255.255", true],
    ["126.255.255.255", false],
    ["128.0.0.1", false],
    ["169.254.169.254", true],
    ["169.253.255.255", false],
    ["169.255.0.0", false],
    ["172.16.0.0", true],
    ["172.31.255.255", true],
    ["172.15.255.255", false],
    ["172.32.0.0", false],
    ["192.0.0.1", true],
    ["192.0.2.1", true],
    ["192.88.99.1", true],
    ["192.168.0.1", true],
    ["192.168.255.255", true],
    ["192.169.0.0", false],
    ["198.18.0.1", true],
    ["198.19.255.255", true],
    ["198.17.255.255", false],
    ["198.20.0.0", false],
    ["198.51.100.1", true],
    ["203.0.113.1", true],
    ["224.0.0.1", true],
    ["239.255.255.255", true],
    ["240.0.0.1", true],
    ["255.255.255.255", true],
    ["::", true],
    ["::1", true],
    ["fe80::1", true],
    ["fc00::1", true],
    ["fd00:ec2::254", true],
    ["fec0::1", true],
    ["ff00::1", true],
    ["100::1", true],
    ["2001::1", true],
    ["2001:2::1", true],
    ["2001:db8::1", true],
    ["2002:7f00:1::", true],
    ["2606:4700:4700::1111", false],
    ["::ffff:8.8.8.8", true],
    ["::ffff:127.0.0.1", true],
    ["::ffff:169.254.169.254", true],
    ["::0.0.0.8", true],
    ["::127.0.0.1", true],
    ["64:ff9b::8.8.8.8", false],
    ["64:ff9b::a00:5", true],
    ["64:ff9b::7f00:1", true],
    ["64:ff9b:1::a00:1", true],
    ["64:ff9b:1::808:808", true],
    ["64:ff9b:1:ffff::1", true],
    ["::ffff:0:169.254.169.254", true],
    ["::ffff:0:a9fe:a9fe", true],
    ["::ffff:0:127.0.0.1", true],
    ["::ffff:0:192.168.0.1", true],
    ["::ffff:0:8.8.8.8", false],
    ["not-an-address", true],  ].freeze

  def test_blocked_address_matches_the_gem
    mismatches = CASES.reject { |addr, blocked| Surfguard.blocked_address?(addr) == blocked }
    assert_empty mismatches.map(&:first),
      "blocked_address? disagrees with surfguard 910be917 on these addresses"
  end

  # An IP-LITERAL host skips DNS entirely, which is the one path through
  # `resolve_public_ips` a unit test can drive without a resolver.
  def test_resolve_public_ips_passes_a_public_literal_through
    assert_equal [ "8.8.8.8" ], Surfguard.resolve_public_ips("8.8.8.8")
  end

  # A literal that resolves to itself and is refused: the host RESOLVED,
  # so this is an empty list, not Unresolvable. The distinction is the
  # whole reason the gem carries two error classes — see the header of
  # `surfguard.rb`.
  def test_resolve_public_ips_is_empty_for_a_blocked_literal
    assert_equal [], Surfguard.resolve_public_ips("169.254.169.254")
  end

  # The ordering rule `resolve_public_ips` implements — IPv4 ahead of
  # IPv6 — over the two families' predicates. A NAME would exercise it
  # end to end, but nothing here has a resolver to answer one
  # (`runtime/ruby/resolv.rb` raises by design), and campfire's own
  # `Push::SubscriptionTest` already drives that half with
  # `Resolv.getaddresses` stubbed.
  def test_both_families_pass_the_policy_and_are_distinguishable
    v4 = IPAddr.new("8.8.8.8")
    v6 = IPAddr.new("2606:4700:4700::1111")
    refute Surfguard.blocked_ipaddr?(v4)
    refute Surfguard.blocked_ipaddr?(v6)
    assert v4.ipv4?
    refute v6.ipv4?
  end
end
