# The CRC-32 port, against zlib's own answers.
#
# A FRAMEWORK test (`tests/runtime_ruby_unit.rs` runs every file under
# `runtime/ruby/test/` on each `cargo test`), not one that ships into an
# emitted tree — the CRuby/JRuby trees replace `runtime/zlib.rb` with
# Ruby's own `require "zlib"` (`project::ruby_runtime_files`), so a
# shipped copy would be asserting about the stdlib there and about the
# port under spinel, from one set of expectations. Here it is
# unambiguously the port.
#
# WHY THIS FILE EXISTS. A wrong checksum does not raise. It picks a
# different avatar colour, and the only thing that would ever notice is
# a byte diff against Rails — which is a slow and confusing way to
# discover that a shift was in the wrong direction.
#
# The expectations are Ruby's own, generated by running the stdlib over
# this list:
#
#     ruby -rzlib -e 'CASES.each { |s| puts [s, Zlib.crc32(s)].inspect }'
#
# The list covers what the port's two decisions can get wrong: the
# empty string (initial == final mask, so the answer must be 0), pure
# ASCII (the corpus case — a record id), a string long enough for the
# register to wrap many times, and code points in each of UTF-8's four
# encoded lengths, which is the half of this file that is NOT zlib's
# algorithm but our own byte derivation.

require_relative "test_helper"
require_relative "../zlib"

class ZlibTest < Minitest::Test
  CASES = {
    "" => 0,
    "1" => 2212294583,
    "42" => 841265288,
    "123456789" => 3421780262,
    "The quick brown fox jumps over the lazy dog" => 1095738169,
    "a" * 1000 => 2587417091,
    # U+00E9 — two UTF-8 bytes.
    "café" => 2561491637,
    # U+4E2D — three.
    "中" => 3587267211,
    # U+1F600 — four.
    "😀" => 88978756,
    # All four lengths in one string, so a wrong length for any one of
    # them shifts every byte after it.
    "aé中\u{1f600}z" => 1167333859,
  }.freeze

  def test_matches_zlib
    CASES.each do |input, expected|
      assert_equal expected, Zlib.crc32(input),
                   "crc32(#{input.inspect})"
    end
  end

  # The answer is an UNSIGNED 32-bit value: the final XOR is with
  # 0xFFFFFFFF, and a signed reading of the same bits would come back
  # negative for every input whose high bit lands set.
  def test_answers_are_unsigned
    CASES.each_value do |expected|
      assert_operator expected, :>=, 0
      assert_operator expected, :<=, 0xFFFFFFFF
    end
  end

  def test_utf8_bytes_lengths
    assert_equal [ 0x61 ], Zlib.utf8_bytes(0x61)
    assert_equal 2, Zlib.utf8_bytes(0x00E9).length
    assert_equal 3, Zlib.utf8_bytes(0x4E2D).length
    assert_equal 4, Zlib.utf8_bytes(0x1F600).length
  end
end
