//! Controllers + router — Elixir.

use std::fmt::Write;
use std::path::PathBuf;

use crate::App;
use crate::dialect::Controller;
use crate::expr::{Expr, ExprNode, Literal};
use crate::ident::Symbol;
use crate::naming::snake_case;

use super::super::EmittedFile;
use super::expr::emit_expr;
use super::view;
// Trait import — used by ExEmitter's inherent-impl helpers to call
// `self.render_expr(...)` (the trait method) from inside.
use crate::lower::CtrlWalker as _;

// Router ---------------------------------------------------------------

pub(super) fn emit_router_file(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "defmodule Router do").unwrap();
    writeln!(s, "  @routes [").unwrap();
    let flat = crate::lower::flatten_routes(app);
    for (i, route) in flat.iter().enumerate() {
        let sep = if i + 1 == flat.len() { "" } else { "," };
        writeln!(
            s,
            "    %{{method: :{}, path: {:?}, controller: {}, action: :{}}}{sep}",
            ex_http_verb_lower(&route.method),
            route.path,
            route.controller.0,
            route.action,
        )
        .unwrap();
    }
    writeln!(s, "  ]").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "  def routes, do: @routes").unwrap();
    writeln!(s, "end").unwrap();
    EmittedFile { path: PathBuf::from("lib/router.ex"), content: s }
}

fn ex_http_verb_lower(m: &crate::dialect::HttpMethod) -> &'static str {
    use crate::dialect::HttpMethod;
    match m {
        HttpMethod::Get => "get",
        HttpMethod::Post => "post",
        HttpMethod::Put => "put",
        HttpMethod::Patch => "patch",
        HttpMethod::Delete => "delete",
        _ => "get",
    }
}

pub(super) fn controller_class_name(short: &str) -> String {
    let mut s = crate::naming::camelize(short);
    s.push_str("Controller");
    s
}

// Pass-2 controllers ---------------------------------------------------

pub(super) fn emit_controller_file_pass2(
    c: &Controller,
    known_models: &[Symbol],
    app: &App,
) -> EmittedFile {
    let module = c.name.0.as_str();
    let resource = crate::lower::resource_from_controller_name(module);
    let model_class = crate::naming::singularize_camelize(&resource);
    let has_model = known_models.iter().any(|m| m.as_str() == model_class);
    let parent = crate::lower::find_nested_parent(app, module);
    let permitted = crate::lower::permitted_fields_for(c, &resource)
        .unwrap_or_else(|| crate::lower::default_permitted_fields(app, &model_class));

    let (public_actions, _private) = crate::lower::split_public_private(c);

    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "defmodule {module} do").unwrap();
    if !public_actions.is_empty() {
        writeln!(s, "  alias Roundhouse.Http.ActionResponse").unwrap();
        writeln!(s, "  import Roundhouse.RouteHelpers").unwrap();
        writeln!(s).unwrap();
    }

    for action in &public_actions {
        let la = crate::lower::lower_action(
            action.name.as_str(),
            &resource,
            &model_class,
            has_model,
            parent.as_ref(),
            &permitted,
        );
        emit_ex_action(&mut s, &la, &action.body, known_models, c);
        writeln!(s).unwrap();
    }
    writeln!(s, "end").unwrap();

    let fname = format!("lib/{}.ex", snake_case(module));
    EmittedFile {
        path: PathBuf::from(fname),
        content: s,
    }
}

fn ex_view_fn(model_class: &str, suffix: &str) -> String {
    let plural = crate::naming::pluralize_snake(model_class);
    format!("render_{plural}_{}", suffix.to_lowercase())
}

fn emit_ex_action(
    out: &mut String,
    la: &crate::lower::LoweredAction,
    body: &Expr,
    known_models: &[Symbol],
    controller: &Controller,
) {
    let name = la.name.as_str();

    if !la.has_model {
        writeln!(out, "  def {name}(_context) do").unwrap();
        writeln!(out, "    %ActionResponse{{body: \"\"}}").unwrap();
        writeln!(out, "  end").unwrap();
        return;
    }

    use crate::lower::CtrlWalker;
    let normalized = crate::lower::normalize_action_body(controller, la.name.as_str(), body);
    let mut emitter = ExEmitter {
        ctx: crate::lower::WalkCtx {
            known_models,
            model_class: la.model_class.as_str(),
            resource: la.resource.as_str(),
            parent: la.parent.as_ref(),
            permitted: &la.permitted,
            adapter: &crate::adapter::SqliteAdapter,
        },
        state: crate::lower::WalkState::new(),
    };
    let mut body_src = String::new();
    emitter.walk_stmt(&normalized, &mut body_src, 2, true);

    let arg = if emitter.state.uses_context || body_src.contains("context") {
        "context"
    } else {
        "_context"
    };
    writeln!(out, "  def {name}({arg}) do").unwrap();
    out.push_str(&body_src);
    writeln!(out, "  end").unwrap();
}

struct ExEmitter<'a> {
    ctx: crate::lower::WalkCtx<'a>,
    state: crate::lower::WalkState,
}

impl<'a> crate::lower::CtrlWalker<'a> for ExEmitter<'a> {
    fn ctx(&self) -> &crate::lower::WalkCtx<'a> { &self.ctx }
    fn state_mut(&mut self) -> &mut crate::lower::WalkState { &mut self.state }
    fn indent_unit(&self) -> &'static str { "  " }

    fn write_assign(&mut self, name: &str, value: &Expr, indent: &str, out: &mut String) {
        let rhs = self.render_expr(value);
        writeln!(out, "{indent}{name} = {rhs}").unwrap();
    }

    fn write_create_expansion(
        &mut self,
        var_name: &str,
        class: &str,
        indent: &str,
        out: &mut String,
    ) {
        writeln!(out, "{indent}{var_name} = %{class}{{}}").unwrap();
        if let Some(parent) = self.ctx.parent {
            writeln!(
                out,
                "{indent}{var_name} = %{{{var_name} | {0}_id: String.to_integer(to_string(context.params[\"{0}_id\"]))}}",
                parent.singular,
            )
            .unwrap();
            self.state.uses_context = true;
        }
        if !self.ctx.permitted.is_empty() {
            let permitted: Vec<String> = self.ctx.permitted.iter().cloned().collect();
            let resource = self.ctx.resource.to_string();
            let assigns: Vec<String> = permitted.iter()
                .map(|f| format!("{f}: Map.get(context.params, \"{resource}[{f}]\", \"\")"))
                .collect();
            writeln!(
                out,
                "{indent}{var_name} = %{{{var_name} | {}}}",
                assigns.join(", "),
            )
            .unwrap();
            self.state.uses_context = true;
        }
    }

    fn write_if(
        &mut self,
        cond: &Expr,
        then_branch: &Expr,
        else_branch: &Expr,
        indent: &str,
        depth: usize,
        is_tail: bool,
        out: &mut String,
    ) {
        let save_recv = detect_save_cond(cond);
        let cond_s = self.render_expr(cond);
        writeln!(out, "{indent}if {cond_s} do").unwrap();
        if let Some(recv_s) = save_recv {
            if self.state.last_local_is_new && self.ctx.parent.is_none() {
                let inner_indent = "  ".repeat(depth + 1);
                writeln!(
                    out,
                    "{inner_indent}{recv_s} = %{{{recv_s} | id: Roundhouse.Db.last_insert_rowid()}}",
                )
                .unwrap();
            }
        }
        self.walk_stmt(then_branch, out, depth + 1, is_tail);
        if !crate::lower::is_empty_body(else_branch) {
            writeln!(out, "{indent}else").unwrap();
            self.walk_stmt(else_branch, out, depth + 1, is_tail);
        }
        writeln!(out, "{indent}end").unwrap();
    }

    fn write_update_if(
        &mut self,
        recv: &Expr,
        then_branch: &Expr,
        else_branch: &Expr,
        indent: &str,
        depth: usize,
        is_tail: bool,
        out: &mut String,
    ) {
        let recv_s = self.render_expr(recv);
        let permitted: Vec<String> = self.ctx.permitted.iter().cloned().collect();
        let resource = self.ctx.resource.to_string();
        for field in &permitted {
            writeln!(
                out,
                "{indent}{recv_s} = if Map.has_key?(context.params, \"{resource}[{field}]\"), do: %{{{recv_s} | {field}: context.params[\"{resource}[{field}]\"]}}, else: {recv_s}",
            )
            .unwrap();
            self.state.uses_context = true;
        }
        writeln!(out, "{indent}if {}.save({recv_s}) do", self.ctx.model_class).unwrap();
        self.walk_stmt(then_branch, out, depth + 1, is_tail);
        if !crate::lower::is_empty_body(else_branch) {
            writeln!(out, "{indent}else").unwrap();
            self.walk_stmt(else_branch, out, depth + 1, is_tail);
        }
        writeln!(out, "{indent}end").unwrap();
    }

    fn write_response_stmt(&mut self, r: &str, _is_tail: bool, indent: &str, out: &mut String) {
        writeln!(out, "{indent}{r}").unwrap();
    }

    fn write_expr_stmt(&mut self, s: &str, indent: &str, out: &mut String) {
        writeln!(out, "{indent}{s}").unwrap();
    }

    fn render_expr(&mut self, expr: &Expr) -> String {
        if let ExprNode::Send { recv, method, args, block, .. } = &*expr.node {
            if let Some(stmt) = self.render_send_stmt(
                recv.as_ref(), method.as_str(), args, block.as_ref(), "",
            ) {
                return match stmt {
                    crate::lower::Stmt::Response(r) => r,
                    crate::lower::Stmt::Expr(s) => s,
                };
            }
            let args_s: Vec<String> = args.iter().map(|a| self.render_expr(a)).collect();
            return match recv {
                None if args.is_empty() => method.to_string(),
                None => format!("{method}({})", args_s.join(", ")),
                Some(r) => {
                    let recv_s = self.render_expr(r);
                    if is_bare_ex_ident(&recv_s) {
                        let all_args: Vec<String> = std::iter::once(recv_s)
                            .chain(args_s.iter().cloned())
                            .collect();
                        format!("{}.{method}({})", self.ctx.model_class, all_args.join(", "))
                    } else if args.is_empty() {
                        format!("{recv_s}.{method}")
                    } else {
                        format!("{recv_s}.{method}({})", args_s.join(", "))
                    }
                }
            };
        }
        if let ExprNode::Ivar { name } = &*expr.node {
            return name.to_string();
        }
        emit_expr(expr, None)
    }

    fn render_send_stmt(
        &mut self,
        recv: Option<&Expr>,
        method: &str,
        args: &[Expr],
        block: Option<&Expr>,
        _suspending_prefix: &str,
    ) -> Option<crate::lower::Stmt> {
        use crate::lower::{SendKind, Stmt};
        let kind = crate::lower::classify_controller_send(
            recv, method, args, block, self.ctx.known_models,
        )?;
        Some(match kind {
            SendKind::ParamsAccess => {
                self.state.uses_context = true;
                Stmt::Expr("context.params".to_string())
            }
            SendKind::ParamsIndex { key } => {
                self.state.uses_context = true;
                match &*key.node {
                    ExprNode::Lit { value: Literal::Sym { value: k } } => Stmt::Expr(
                        format!("String.to_integer(to_string(context.params[\"{}\"]))", k.as_str()),
                    ),
                    _ => {
                        let ks = self.render_expr(key);
                        Stmt::Expr(format!("context.params[{ks}]"))
                    }
                }
            }
            SendKind::ParamsExpect { args: pe_args } => {
                self.state.uses_context = true;
                match pe_args.first().map(|e| &*e.node) {
                    Some(ExprNode::Lit { value: Literal::Sym { value: k } }) => Stmt::Expr(
                        format!("String.to_integer(to_string(context.params[\"{}\"]))", k.as_str()),
                    ),
                    _ => Stmt::Expr("context.params # TODO: params.expect hash".to_string()),
                }
            }
            SendKind::ModelNew { class } => Stmt::Expr(format!("%{}{{}}", class.as_str())),
            SendKind::ModelFind { class, id } => {
                let id_s = self.render_expr(id);
                Stmt::Expr(format!("{0}.find({id_s}) || %{0}{{}}", class.as_str()))
            }
            SendKind::QueryChain { target: Some(target), method: cm, args: ca, recv: cr } => {
                let mut out = format!("{}.all()", target.as_str());
                let mods = crate::lower::collect_chain_modifiers(cm, ca, cr.as_deref());
                for m in mods {
                    out = view::apply_ex_chain_modifier(out, m);
                }
                Stmt::Expr(out)
            }
            SendKind::QueryChain { target: None, .. } => Stmt::Expr("[]".to_string()),
            SendKind::AssocLookup { target, outer_method } => match outer_method {
                "find" => {
                    let id_s = args.first().map(|a| self.render_expr(a))
                        .unwrap_or_else(|| "0".to_string());
                    Stmt::Expr(format!("{0}.find({id_s}) || %{0}{{}}", target.as_str()))
                }
                _ => Stmt::Expr(format!("%{}{{}}", target.as_str())),
            },
            SendKind::BangStrip { recv, stripped_method, args: bs_args } => {
                let recv_s = self.render_expr(recv);
                let mut call_args = vec![recv_s];
                for a in bs_args {
                    call_args.push(self.render_expr(a));
                }
                Stmt::Expr(format!(
                    "{}.{stripped_method}({})",
                    self.ctx.model_class,
                    call_args.join(", "),
                ))
            }
            SendKind::InstanceUpdate => Stmt::Expr("false".to_string()),
            SendKind::PathOrUrlHelper => {
                let helper = method.strip_suffix("_path").or_else(|| method.strip_suffix("_url"))
                    .unwrap_or(method);
                Stmt::Expr(format!("{helper}_path()"))
            }
            SendKind::Render { args: r_args } => Stmt::Response(self.render_ex_render(r_args)),
            SendKind::RedirectTo { args: r_args } => Stmt::Response(self.render_ex_redirect(r_args)),
            SendKind::Head { args: h_args } => {
                let status = h_args.first().and_then(|a| match &*a.node {
                    ExprNode::Lit { value: Literal::Sym { value: s } } =>
                        Some(crate::lower::status_sym_to_code(s.as_str())),
                    ExprNode::Lit { value: Literal::Int { value: n } } => Some(*n as u16),
                    _ => None,
                }).unwrap_or(200);
                Stmt::Response(format!("%ActionResponse{{status: {status}}}"))
            }
            SendKind::RespondToBlock { .. }
            | SendKind::FormatHtml { .. }
            | SendKind::FormatJson => Stmt::Expr(
                "%ActionResponse{} # unreachable: respond_to not normalized".to_string(),
            ),
        })
    }
}

impl<'a> ExEmitter<'a> {
    fn render_ex_render(&mut self, args: &[Expr]) -> String {
        if let Some(first) = args.first() {
            if let ExprNode::Lit { value: Literal::Sym { value: sym } } = &*first.node {
                let view_fn = ex_view_fn(self.ctx.model_class, sym.as_str());
                let arg = self.state.last_local.clone().unwrap_or_else(|| "nil".to_string());
                let body_part = format!("body: App.Views.{view_fn}({arg})");
                return match crate::lower::extract_status_from_kwargs(&args[1..]) {
                    Some(status) => format!("%ActionResponse{{status: {status}, {body_part}}}"),
                    None => format!("%ActionResponse{{{body_part}}}"),
                };
            }
            let body_s = self.render_expr(first);
            return format!("%ActionResponse{{body: {body_s}}}");
        }
        "%ActionResponse{}".to_string()
    }

    fn render_ex_redirect(&mut self, args: &[Expr]) -> String {
        let Some(first) = args.first() else {
            return "%ActionResponse{status: 303}".to_string();
        };
        let loc = self.render_expr(first);
        let status = crate::lower::extract_status_from_kwargs(&args[1..]).unwrap_or(303);
        if is_bare_ex_ident(&loc) {
            let id_access = format!("{loc}.id");
            return format!(
                "%ActionResponse{{status: {status}, location: {loc}_path({id_access})}}",
            );
        }
        format!("%ActionResponse{{status: {status}, location: {loc}}}")
    }
}

fn detect_save_cond(cond: &Expr) -> Option<String> {
    let ExprNode::Send { recv: Some(r), method, args, .. } = &*cond.node else {
        return None;
    };
    if method.as_str() != "save" || !args.is_empty() {
        return None;
    }
    match &*r.node {
        ExprNode::Var { name, .. } | ExprNode::Ivar { name } => Some(name.to_string()),
        _ => None,
    }
}

fn is_bare_ex_ident(s: &str) -> bool {
    let bytes = s.as_bytes();
    if bytes.is_empty() { return false; }
    let first = bytes[0];
    if !(first.is_ascii_lowercase() || first == b'_') { return false; }
    bytes.iter().all(|&b| b.is_ascii_alphanumeric() || b == b'_')
}
