//! `lib/roundhouse/importmap.ex` emission.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use crate::App;

/// Emit `lib/roundhouse/importmap.ex` — a `Pins` module with a
/// `@pins` attribute that the layout's
/// `javascript_importmap_tags` helper consumes.
pub(super) fn emit_ex_importmap(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "defmodule Roundhouse.Importmap do").unwrap();
    writeln!(s, "  @moduledoc false").unwrap();
    writeln!(s, "  @pins [").unwrap();
    if let Some(importmap) = &app.importmap {
        for pin in &importmap.pins {
            writeln!(s, "    {{{:?}, {:?}}},", pin.name, pin.path).unwrap();
        }
    }
    writeln!(s, "  ]").unwrap();
    writeln!(s, "  def pins, do: @pins").unwrap();
    writeln!(s, "end").unwrap();
    EmittedFile {
        path: PathBuf::from("lib/roundhouse/importmap.ex"),
        content: s,
    }
}
