//! `lib/app_main.ex` emission — runtime entry point.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use crate::App;

/// Emit `lib/app_main.ex` — exposes a `App.Main.run/0` entry that
/// the compare driver invokes via `mix run -e`. Opens the DB via
/// `server.start/2` with the emitted layout when present. Defining
/// this as a module (rather than running top-level via a script)
/// keeps `mix compile` able to inspect it.
pub(super) fn emit_ex_main(app: &App) -> EmittedFile {
    let has_layout = app
        .views
        .iter()
        .any(|v| v.name.as_str() == "layouts/application");
    let layout_opt = if has_layout {
        "layout: fn -> App.Views.render_layouts_application(nil) end, "
    } else {
        ""
    };
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "defmodule App.Main do").unwrap();
    writeln!(s, "  @moduledoc false").unwrap();
    writeln!(s, "  alias Roundhouse.Server").unwrap();
    writeln!(s, "  alias Roundhouse.SchemaSQL").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "  def run do").unwrap();
    writeln!(s, "    App.Routes.register()").unwrap();
    writeln!(s, "    register_partials()").unwrap();
    writeln!(s, "    Server.start(SchemaSQL.create_tables(), {layout_opt}port: resolve_port())").unwrap();
    writeln!(s, "  end").unwrap();
    // Register partial renderers for every model whose plural
    // resource has a `_<singular>.html.erb` partial. Cable's
    // broadcast_*_to resolves the partial by model class name.
    writeln!(s).unwrap();
    writeln!(s, "  defp register_partials do").unwrap();
    writeln!(s, "    Roundhouse.Cable.ensure_started()").unwrap();
    let known_model_names: std::collections::BTreeSet<String> = app
        .models
        .iter()
        .map(|m| m.name.0.as_str().to_string())
        .collect();
    let mut registered: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
    for v in &app.views {
        let name = v.name.as_str();
        if let Some((dir, base)) = name.rsplit_once('/') {
            if let Some(singular) = base.strip_prefix('_') {
                let class = crate::naming::camelize(singular);
                if !known_model_names.contains(&class) {
                    continue;
                }
                if registered.insert(class.clone()) {
                    let fn_name = format!("render_{}_{singular}", dir);
                    writeln!(
                        s,
                        "    Roundhouse.Cable.register_partial({class:?}, fn id ->"
                    )
                    .unwrap();
                    writeln!(s, "      case {class}.find(id) do").unwrap();
                    writeln!(s, "        nil -> \"\"").unwrap();
                    writeln!(s, "        record -> App.Views.{fn_name}(record)").unwrap();
                    writeln!(s, "      end").unwrap();
                    writeln!(s, "    end)").unwrap();
                }
            }
        }
    }
    writeln!(s, "    :ok").unwrap();
    writeln!(s, "  end").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "  defp resolve_port do").unwrap();
    writeln!(s, "    case System.get_env(\"PORT\") do").unwrap();
    writeln!(s, "      nil -> 3000").unwrap();
    writeln!(s, "      s -> String.to_integer(s)").unwrap();
    writeln!(s, "    end").unwrap();
    writeln!(s, "  end").unwrap();
    writeln!(s, "end").unwrap();
    EmittedFile {
        path: PathBuf::from("lib/app_main.ex"),
        content: s,
    }
}
