//! Models — Elixir defstruct + persistence + validations + broadcasters.

use std::fmt::Write;
use std::path::PathBuf;

use crate::App;
use crate::dialect::{MethodDef, Model};
use crate::expr::{Expr, ExprNode, LValue, Literal};
use crate::ident::Symbol;
use crate::naming::snake_case;

use super::super::EmittedFile;
use super::expr::emit_block;

pub(super) fn emit_model_file(model: &Model, app: &App) -> EmittedFile {
    let module = model.name.0.as_str();
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "defmodule {module} do").unwrap();

    let mut fields: Vec<String> = model
        .attributes
        .fields
        .iter()
        .map(|(k, ty)| format!("{}: {}", k.as_str(), ex_default_for(ty)))
        .collect();
    if !model.attributes.fields.is_empty() {
        fields.push("errors: []".to_string());
    }
    if !fields.is_empty() {
        writeln!(s, "  defstruct [{}]", fields.join(", ")).unwrap();
    } else {
        writeln!(s, "  defstruct []").unwrap();
    }

    let attrs: Vec<Symbol> = model.attributes.fields.keys().cloned().collect();
    for method in model.methods() {
        writeln!(s).unwrap();
        emit_model_method_with_attrs(&mut s, module, method, &attrs);
    }

    let lowered = crate::lower::lower_validations(model);
    if !lowered.is_empty() {
        writeln!(s).unwrap();
        emit_validate_method_ex(&mut s, &lowered);
    }
    let has_table = model
        .attributes
        .fields
        .keys()
        .any(|k| k.as_str() != "id");
    if has_table {
        writeln!(s).unwrap();
        let broadcasts = crate::lower::lower_broadcasts(model);
        emit_persistence_methods_ex(
            &mut s,
            module,
            model,
            !lowered.is_empty(),
            app,
            !broadcasts.is_empty(),
        );
        if !broadcasts.is_empty() {
            let lp = crate::lower::lower_persistence(model, app);
            emit_ex_broadcaster_methods(
                &mut s,
                lp.class.0.as_str(),
                lp.table.as_str(),
                &broadcasts,
            );
        }
    }

    writeln!(s, "end").unwrap();
    let fname = format!("lib/{}.ex", snake_case(module));
    EmittedFile { path: PathBuf::from(fname), content: s }
}

// ── Broadcaster emission ────────────────────────────────────────

fn emit_ex_broadcaster_methods(
    out: &mut String,
    class: &str,
    table: &str,
    decls: &crate::lower::LoweredBroadcasts,
) {
    writeln!(out).unwrap();
    writeln!(out, "  def _broadcast_after_save(record) do").unwrap();
    if decls.save.is_empty() {
        writeln!(out, "    _ = record").unwrap();
        writeln!(out, "    :ok").unwrap();
    } else {
        writeln!(out, "    _ = record").unwrap();
        for b in &decls.save {
            emit_ex_one_broadcast_call(out, class, table, b);
        }
        writeln!(out, "    :ok").unwrap();
    }
    writeln!(out, "  end").unwrap();

    writeln!(out).unwrap();
    writeln!(out, "  def _broadcast_after_delete(record) do").unwrap();
    if decls.destroy.is_empty() {
        writeln!(out, "    _ = record").unwrap();
        writeln!(out, "    :ok").unwrap();
    } else {
        writeln!(out, "    _ = record").unwrap();
        for b in &decls.destroy {
            emit_ex_one_broadcast_call(out, class, table, b);
        }
        writeln!(out, "    :ok").unwrap();
    }
    writeln!(out, "  end").unwrap();
}

fn emit_ex_one_broadcast_call(
    out: &mut String,
    class: &str,
    table: &str,
    b: &crate::lower::LoweredBroadcast,
) {
    let channel = ex_render_broadcast_expr(&b.channel, b.self_param.as_ref());
    let target = b
        .target
        .as_ref()
        .map(|t| ex_render_broadcast_expr(t, b.self_param.as_ref()))
        .unwrap_or_else(|| "\"\"".to_string());
    if let Some(assoc) = &b.on_association {
        let var = assoc.name.as_str();
        let target_class = assoc.target_class.as_str();
        let target_table = assoc.target_table.as_str();
        let fk = assoc.foreign_key.as_str();
        writeln!(out, "    {var} = {target_class}.find(record.{fk})").unwrap();
        writeln!(out, "    if {var} != nil do").unwrap();
        if b.action == crate::lower::BroadcastAction::Remove {
            writeln!(
                out,
                "      Roundhouse.Cable.broadcast_remove_to({target_table:?}, {var}.id, {channel}, {target})",
            )
            .unwrap();
        } else {
            let func = ex_action_fn(b.action);
            writeln!(
                out,
                "      Roundhouse.Cable.{func}({target_table:?}, {var}.id, {target_class:?}, {channel}, {target})",
            )
            .unwrap();
        }
        writeln!(out, "    end").unwrap();
        return;
    }
    if b.action == crate::lower::BroadcastAction::Remove {
        writeln!(
            out,
            "    Roundhouse.Cable.broadcast_remove_to({table:?}, record.id, {channel}, {target})",
        )
        .unwrap();
    } else {
        let func = ex_action_fn(b.action);
        writeln!(
            out,
            "    Roundhouse.Cable.{func}({table:?}, record.id, {class:?}, {channel}, {target})",
        )
        .unwrap();
    }
}

fn ex_action_fn(action: crate::lower::BroadcastAction) -> &'static str {
    match action {
        crate::lower::BroadcastAction::Prepend => "broadcast_prepend_to",
        crate::lower::BroadcastAction::Append => "broadcast_append_to",
        crate::lower::BroadcastAction::Replace => "broadcast_replace_to",
        crate::lower::BroadcastAction::Remove => "broadcast_remove_to",
    }
}

fn ex_render_broadcast_expr(expr: &Expr, self_param: Option<&Symbol>) -> String {
    let p = self_param.map(|s| s.as_str());
    match &*expr.node {
        ExprNode::Lit { value: Literal::Str { value } } => format!("{value:?}"),
        ExprNode::Lit { value: Literal::Int { value } } => format!("{value}"),
        ExprNode::Var { name, .. } => {
            if let Some(pname) = p {
                let stripped = pname.strip_prefix('_').unwrap_or(pname);
                if name.as_str() == pname || name.as_str() == stripped {
                    return "record".to_string();
                }
            }
            name.as_str().to_string()
        }
        ExprNode::Send { recv: Some(r), method, .. } => {
            let recv_s = ex_render_broadcast_expr(r, self_param);
            format!("{recv_s}.{}", method.as_str())
        }
        ExprNode::StringInterp { parts } => {
            use crate::expr::InterpPart;
            let mut out = String::from("\"");
            for part in parts {
                match part {
                    InterpPart::Text { value } => {
                        for c in value.chars() {
                            match c {
                                '"' => out.push_str("\\\""),
                                '\\' => out.push_str("\\\\"),
                                '\n' => out.push_str("\\n"),
                                '#' => out.push_str("\\#"),
                                _ => out.push(c),
                            }
                        }
                    }
                    InterpPart::Expr { expr } => {
                        out.push_str("#{");
                        out.push_str(&ex_render_broadcast_expr(expr, self_param));
                        out.push('}');
                    }
                }
            }
            out.push('"');
            out
        }
        _ => "nil".to_string(),
    }
}

fn emit_persistence_methods_ex(
    out: &mut String,
    module: &str,
    model: &Model,
    has_validate: bool,
    app: &App,
    has_broadcasts: bool,
) {
    let lp = crate::lower::lower_persistence(model, app);
    let recv = module_receiver_name(module);

    let insert_sql = positional_placeholders_ex(&lp.insert_sql);
    let update_sql = positional_placeholders_ex(&lp.update_sql);
    let delete_sql = positional_placeholders_ex(&lp.delete_sql);
    let select_by_id_sql = positional_placeholders_ex(&lp.select_by_id_sql);

    let non_id_args: Vec<String> = lp
        .non_id_columns
        .iter()
        .map(|s| format!("{recv}.{}", s.as_str()))
        .collect();

    // ----- save/1 -----
    writeln!(out, "  def save({recv}) do").unwrap();
    if has_validate {
        writeln!(out, "    cond do").unwrap();
        writeln!(out, "      validate({recv}) != [] ->").unwrap();
        writeln!(out, "        false").unwrap();
        for check in &lp.belongs_to_checks {
            let fk = check.foreign_key.as_str();
            let target = check.target_class.0.as_str();
            writeln!(
                out,
                "      {recv}.{fk} == nil or {recv}.{fk} == 0 or {target}.find({recv}.{fk}) == nil ->",
            )
            .unwrap();
            writeln!(out, "        false").unwrap();
        }
        writeln!(out, "      true ->").unwrap();
        writeln!(out, "        do_save({recv})").unwrap();
        writeln!(out, "    end").unwrap();
        writeln!(out, "  end").unwrap();
    } else {
        writeln!(out, "    do_save({recv})").unwrap();
        writeln!(out, "  end").unwrap();
    }

    writeln!(out).unwrap();
    writeln!(out, "  defp do_save({recv}) do").unwrap();
    writeln!(out, "    if {recv}.id == nil or {recv}.id == 0 do").unwrap();
    writeln!(
        out,
        "      _id = Roundhouse.Db.execute({insert_sql:?}, [{}])",
        non_id_args.join(", "),
    )
    .unwrap();
    writeln!(out, "    else").unwrap();
    writeln!(
        out,
        "      _id = Roundhouse.Db.execute({update_sql:?}, [{}, {recv}.id])",
        non_id_args.join(", "),
    )
    .unwrap();
    writeln!(out, "    end").unwrap();
    if has_broadcasts {
        writeln!(out, "    _broadcast_after_save({recv})").unwrap();
    }
    writeln!(out, "    true").unwrap();
    writeln!(out, "  end").unwrap();

    // ----- destroy/1 -----
    writeln!(out).unwrap();
    writeln!(out, "  def destroy({recv}) do").unwrap();
    for dc in &lp.dependent_children {
        let child_class = dc.child_class.0.as_str();
        let child_select = positional_placeholders_ex(&dc.select_by_parent_sql);
        writeln!(
            out,
            "    rows = Roundhouse.Db.query_all({child_select:?}, [{recv}.id])",
        )
        .unwrap();
        writeln!(out, "    Enum.each(rows, fn row ->").unwrap();
        writeln!(out, "      [{}] = row", dc
            .child_columns
            .iter()
            .map(|c| c.as_str().to_string())
            .collect::<Vec<_>>()
            .join(", "))
            .unwrap();
        let fields: Vec<String> = dc
            .child_columns
            .iter()
            .map(|c| format!("{0}: {0}", c.as_str()))
            .collect();
        writeln!(
            out,
            "      child = %{child_class}{{{}}}",
            fields.join(", ")
        )
        .unwrap();
        writeln!(out, "      {child_class}.destroy(child)").unwrap();
        writeln!(out, "    end)").unwrap();
    }
    writeln!(
        out,
        "    _ = Roundhouse.Db.execute({delete_sql:?}, [{recv}.id])",
    )
    .unwrap();
    if has_broadcasts {
        writeln!(out, "    _broadcast_after_delete({recv})").unwrap();
    }
    writeln!(out, "    :ok").unwrap();
    writeln!(out, "  end").unwrap();

    // ----- count/0 -----
    writeln!(out).unwrap();
    writeln!(out, "  def count do").unwrap();
    writeln!(
        out,
        "    Roundhouse.Db.scalar({:?}, [])",
        lp.count_sql,
    )
    .unwrap();
    writeln!(out, "  end").unwrap();

    // ----- find/1 -----
    writeln!(out).unwrap();
    writeln!(out, "  def find(id) do").unwrap();
    writeln!(
        out,
        "    case Roundhouse.Db.query_one({select_by_id_sql:?}, [id]) do",
    )
    .unwrap();
    let field_list: Vec<String> = lp
        .columns
        .iter()
        .map(|c| c.as_str().to_string())
        .collect();
    writeln!(out, "      [{}] ->", field_list.join(", ")).unwrap();
    let struct_fields: Vec<String> = lp
        .columns
        .iter()
        .map(|c| format!("{0}: {0}", c.as_str()))
        .collect();
    writeln!(
        out,
        "        %{module}{{{}}}",
        struct_fields.join(", ")
    )
    .unwrap();
    writeln!(out, "      nil ->").unwrap();
    writeln!(out, "        nil").unwrap();
    writeln!(out, "    end").unwrap();
    writeln!(out, "  end").unwrap();

    // ----- all/0 -----
    let select_all_sql = positional_placeholders_ex(&lp.select_all_sql);
    writeln!(out).unwrap();
    writeln!(out, "  def all do").unwrap();
    writeln!(
        out,
        "    rows = Roundhouse.Db.query_all({select_all_sql:?}, [])"
    )
    .unwrap();
    writeln!(out, "    Enum.map(rows, fn row ->").unwrap();
    writeln!(
        out,
        "      [{}] = row",
        lp.columns
            .iter()
            .map(|c| c.as_str().to_string())
            .collect::<Vec<_>>()
            .join(", ")
    )
    .unwrap();
    writeln!(
        out,
        "      %{module}{{{}}}",
        struct_fields.join(", ")
    )
    .unwrap();
    writeln!(out, "    end)").unwrap();
    writeln!(out, "  end").unwrap();

    // ----- last/0 -----
    let select_last_sql = positional_placeholders_ex(&lp.select_last_sql);
    writeln!(out).unwrap();
    writeln!(out, "  def last do").unwrap();
    writeln!(
        out,
        "    case Roundhouse.Db.query_one({select_last_sql:?}, []) do"
    )
    .unwrap();
    writeln!(out, "      [{}] ->", field_list.join(", ")).unwrap();
    writeln!(
        out,
        "        %{module}{{{}}}",
        struct_fields.join(", ")
    )
    .unwrap();
    writeln!(out, "      nil ->").unwrap();
    writeln!(out, "        nil").unwrap();
    writeln!(out, "    end").unwrap();
    writeln!(out, "  end").unwrap();

    // ----- reload/1 -----
    writeln!(out).unwrap();
    writeln!(out, "  def reload({recv}) do").unwrap();
    writeln!(out, "    case find({recv}.id) do").unwrap();
    writeln!(out, "      nil -> {recv}").unwrap();
    writeln!(out, "      fresh -> fresh").unwrap();
    writeln!(out, "    end").unwrap();
    writeln!(out, "  end").unwrap();

    // ----- has_many association accessors -----
    for dc in &lp.dependent_children {
        let child_class = dc.child_class.0.as_str();
        let assoc = crate::naming::pluralize_snake(child_class);
        let child_select = positional_placeholders_ex(&dc.select_by_parent_sql);
        let child_cols: Vec<String> = dc
            .child_columns
            .iter()
            .map(|c| c.as_str().to_string())
            .collect();
        let child_struct_fields: Vec<String> = dc
            .child_columns
            .iter()
            .map(|c| format!("{0}: {0}", c.as_str()))
            .collect();
        writeln!(out).unwrap();
        writeln!(out, "  def {assoc}({recv}) do").unwrap();
        writeln!(
            out,
            "    rows = Roundhouse.Db.query_all({child_select:?}, [{recv}.id])"
        )
        .unwrap();
        writeln!(out, "    Enum.map(rows, fn row ->").unwrap();
        writeln!(out, "      [{}] = row", child_cols.join(", ")).unwrap();
        writeln!(
            out,
            "      %{child_class}{{{}}}",
            child_struct_fields.join(", ")
        )
        .unwrap();
        writeln!(out, "    end)").unwrap();
        writeln!(out, "  end").unwrap();
    }
}

fn ex_default_for(ty: &crate::ty::Ty) -> &'static str {
    use crate::ty::Ty;
    match ty {
        Ty::Int => "0",
        Ty::Float => "0.0",
        Ty::Bool => "false",
        Ty::Str | Ty::Sym => "\"\"",
        Ty::Class { id, .. } if id.0.as_str() == "Time" => "\"\"",
        _ => "nil",
    }
}

fn positional_placeholders_ex(sql: &str) -> String {
    let mut out = String::new();
    let chars: Vec<char> = sql.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        if chars[i] == '?' {
            out.push('?');
            i += 1;
            while i < chars.len() && chars[i].is_ascii_digit() {
                i += 1;
            }
        } else {
            out.push(chars[i]);
            i += 1;
        }
    }
    out
}

fn emit_validate_method_ex(
    out: &mut String,
    validations: &[crate::lower::LoweredValidation],
) {
    writeln!(out, "  def validate(record) do").unwrap();
    writeln!(out, "    errors = []").unwrap();
    for lv in validations {
        for check in &lv.checks {
            emit_check_inline_ex(out, lv.attribute.as_str(), check);
        }
    }
    writeln!(out, "    errors").unwrap();
    writeln!(out, "  end").unwrap();
}

fn emit_check_inline_ex(out: &mut String, attr: &str, check: &crate::lower::Check) {
    use crate::lower::Check;
    let msg = check.default_message();
    let push = |cond: &str| -> String {
        format!(
            "    errors =\n      if {cond} do\n        [Roundhouse.ValidationError.new({attr:?}, {msg:?}) | errors]\n      else\n        errors\n      end"
        )
    };
    let block = match check {
        Check::Presence => push(&format!("record.{attr} == \"\" or record.{attr} == nil")),
        Check::Absence => push(&format!("record.{attr} != \"\" and record.{attr} != nil")),
        Check::MinLength { n } => {
            push(&format!("record.{attr} == nil or String.length(record.{attr}) < {n}"))
        }
        Check::MaxLength { n } => {
            push(&format!("record.{attr} != nil and String.length(record.{attr}) > {n}"))
        }
        Check::GreaterThan { threshold } => {
            push(&format!("record.{attr} <= {threshold}"))
        }
        Check::LessThan { threshold } => push(&format!("record.{attr} >= {threshold}")),
        Check::OnlyInteger => {
            format!("    # OnlyInteger on {attr:?} — no-op, Elixir has no implicit coercion")
        }
        Check::Inclusion { values } => {
            let parts: Vec<String> = values.iter().map(inclusion_value_to_ex).collect();
            push(&format!("record.{attr} not in [{}]", parts.join(", ")))
        }
        Check::Format { pattern } => {
            format!("    # TODO: Format check on {attr:?} requires Regex ({pattern:?})")
        }
        Check::Uniqueness { .. } => {
            format!("    # TODO: Uniqueness on {attr:?} requires DB access at runtime")
        }
        Check::Custom { method } => {
            format!("    errors = {method}(record, errors)", method = method.as_str())
        }
    };
    writeln!(out, "{block}").unwrap();
}

fn inclusion_value_to_ex(v: &crate::lower::InclusionValue) -> String {
    use crate::lower::InclusionValue;
    match v {
        InclusionValue::Str { value } => format!("{value:?}"),
        InclusionValue::Int { value } => value.to_string(),
        InclusionValue::Float { value } => {
            let s = value.to_string();
            if s.contains('.') { s } else { format!("{s}.0") }
        }
        InclusionValue::Bool { value } => value.to_string(),
    }
}

fn emit_model_method_with_attrs(
    out: &mut String,
    module: &str,
    m: &MethodDef,
    attrs: &[Symbol],
) {
    let name = m.name.as_str();
    let is_instance = matches!(m.receiver, crate::dialect::MethodReceiver::Instance);
    let first_arg = if is_instance { Some(module_receiver_name(module)) } else { None };

    let mut params: Vec<String> = Vec::new();
    if let Some(arg) = &first_arg {
        params.push(arg.clone());
    }
    for p in &m.params {
        params.push(p.to_string());
    }
    let param_list = if params.is_empty() {
        String::new()
    } else {
        format!("({})", params.join(", "))
    };

    writeln!(out, "  def {name}{param_list} do").unwrap();
    let body_expr = if first_arg.is_some() {
        rewrite_bare_attrs_to_ivars_ex(&m.body, attrs)
    } else {
        m.body.clone()
    };
    let body = emit_block(&body_expr, first_arg.as_deref());
    for line in body.lines() {
        writeln!(out, "    {line}").unwrap();
    }
    writeln!(out, "  end").unwrap();
}

fn rewrite_bare_attrs_to_ivars_ex(e: &Expr, attrs: &[Symbol]) -> Expr {
    use crate::expr::{Arm, InterpPart, Pattern};
    let rewrite = |child: &Expr| rewrite_bare_attrs_to_ivars_ex(child, attrs);
    let new_node = match &*e.node {
        ExprNode::Send { recv: None, method, args, block: None, .. }
            if args.is_empty() && attrs.iter().any(|s| s == method) =>
        {
            ExprNode::Ivar { name: method.clone() }
        }
        ExprNode::Send { recv, method, args, block, parenthesized } => ExprNode::Send {
            recv: recv.as_ref().map(&rewrite),
            method: method.clone(),
            args: args.iter().map(&rewrite).collect(),
            block: block.as_ref().map(&rewrite),
            parenthesized: *parenthesized,
        },
        ExprNode::Seq { exprs } => ExprNode::Seq {
            exprs: exprs.iter().map(&rewrite).collect(),
        },
        ExprNode::Array { elements, style } => ExprNode::Array {
            elements: elements.iter().map(&rewrite).collect(),
            style: *style,
        },
        ExprNode::Hash { entries, braced } => ExprNode::Hash {
            entries: entries.iter().map(|(k, v)| (rewrite(k), rewrite(v))).collect(),
            braced: *braced,
        },
        ExprNode::If { cond, then_branch, else_branch } => ExprNode::If {
            cond: rewrite(cond),
            then_branch: rewrite(then_branch),
            else_branch: rewrite(else_branch),
        },
        ExprNode::Case { scrutinee, arms } => ExprNode::Case {
            scrutinee: rewrite(scrutinee),
            arms: arms
                .iter()
                .map(|arm| Arm {
                    pattern: arm.pattern.clone(),
                    guard: arm.guard.as_ref().map(&rewrite),
                    body: rewrite(&arm.body),
                })
                .collect(),
        },
        ExprNode::BoolOp { op, surface, left, right } => ExprNode::BoolOp {
            op: *op,
            surface: *surface,
            left: rewrite(left),
            right: rewrite(right),
        },
        ExprNode::StringInterp { parts } => ExprNode::StringInterp {
            parts: parts
                .iter()
                .map(|p| match p {
                    InterpPart::Text { value } => InterpPart::Text { value: value.clone() },
                    InterpPart::Expr { expr } => InterpPart::Expr { expr: rewrite(expr) },
                })
                .collect(),
        },
        ExprNode::Let { id, name, value, body } => ExprNode::Let {
            id: *id,
            name: name.clone(),
            value: rewrite(value),
            body: rewrite(body),
        },
        ExprNode::Lambda { params, block_param, body, block_style } => ExprNode::Lambda {
            params: params.clone(),
            block_param: block_param.clone(),
            body: rewrite(body),
            block_style: *block_style,
        },
        ExprNode::Apply { fun, args, block } => ExprNode::Apply {
            fun: rewrite(fun),
            args: args.iter().map(&rewrite).collect(),
            block: block.as_ref().map(&rewrite),
        },
        ExprNode::Assign { target, value } => {
            let new_target = match target {
                LValue::Var { id, name } => LValue::Var { id: *id, name: name.clone() },
                LValue::Ivar { name } => LValue::Ivar { name: name.clone() },
                LValue::Attr { recv, name } => LValue::Attr {
                    recv: rewrite(recv),
                    name: name.clone(),
                },
                LValue::Index { recv, index } => LValue::Index {
                    recv: rewrite(recv),
                    index: rewrite(index),
                },
            };
            ExprNode::Assign {
                target: new_target,
                value: rewrite(value),
            }
        }
        ExprNode::Yield { args } => ExprNode::Yield {
            args: args.iter().map(&rewrite).collect(),
        },
        ExprNode::Raise { value } => ExprNode::Raise { value: rewrite(value) },
        ExprNode::RescueModifier { expr, fallback } => ExprNode::RescueModifier {
            expr: rewrite(expr),
            fallback: rewrite(fallback),
        },
        ExprNode::Lit { .. }
        | ExprNode::Var { .. }
        | ExprNode::Ivar { .. }
        | ExprNode::Const { .. }
        | ExprNode::SelfRef => (*e.node).clone(),
        ExprNode::Return { value } => ExprNode::Return { value: rewrite(value) },
        ExprNode::Super { args } => ExprNode::Super {
            args: args.as_ref().map(|v| v.iter().map(&rewrite).collect()),
        },
        ExprNode::BeginRescue { body, rescues, else_branch, ensure, implicit } => {
            ExprNode::BeginRescue {
                body: rewrite(body),
                rescues: rescues
                    .iter()
                    .map(|rc| crate::expr::RescueClause {
                        classes: rc.classes.iter().map(&rewrite).collect(),
                        binding: rc.binding.clone(),
                        body: rewrite(&rc.body),
                    })
                    .collect(),
                else_branch: else_branch.as_ref().map(&rewrite),
                ensure: ensure.as_ref().map(&rewrite),
                implicit: *implicit,
            }
        }
    };
    let _ = Pattern::Wildcard;
    Expr {
        span: e.span,
        node: Box::new(new_node),
        ty: e.ty.clone(),
        effects: e.effects.clone(),
        leading_blank_line: e.leading_blank_line,
        diagnostic: e.diagnostic.clone(),
    }
}

/// Convention: the record arg is the snake_case form of the module name.
fn module_receiver_name(module: &str) -> String {
    snake_case(module)
}
