//! Route emission — `lib/roundhouse/route_helpers.ex` (`<name>_path`
//! functions) and `lib/app/routes.ex` (Router.add registrations).

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use super::controller;
use crate::App;
use crate::dialect::RouteSpec;

pub(super) fn emit_ex_route_helpers(app: &App) -> EmittedFile {
    let flat = crate::lower::flatten_routes(app);
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "defmodule Roundhouse.RouteHelpers do").unwrap();
    writeln!(s, "  @moduledoc false").unwrap();
    writeln!(s).unwrap();
    use std::collections::BTreeSet;
    let mut seen: BTreeSet<String> = BTreeSet::new();
    for route in &flat {
        if !seen.insert(route.as_name.clone()) {
            continue;
        }
        let fn_name = format!("{}_path", route.as_name);
        let params: Vec<String> = route
            .path_params
            .iter()
            .map(|p| format!("{p} \\\\ 0"))
            .collect();
        let sig = if params.is_empty() {
            String::new()
        } else {
            format!("({})", params.join(", "))
        };
        let body = if route.path_params.is_empty() {
            format!("\"{}\"", route.path)
        } else {
            let mut interp = String::new();
            let mut chars = route.path.chars().peekable();
            while let Some(c) = chars.next() {
                if c == ':' {
                    let mut ident = String::new();
                    while let Some(&nc) = chars.peek() {
                        if nc.is_alphanumeric() || nc == '_' {
                            ident.push(nc);
                            chars.next();
                        } else {
                            break;
                        }
                    }
                    interp.push_str("#{");
                    interp.push_str(&ident);
                    interp.push('}');
                } else {
                    interp.push(c);
                }
            }
            format!("\"{}\"", interp)
        };
        writeln!(s, "  def {fn_name}{sig}, do: {body}").unwrap();
    }
    writeln!(s, "end").unwrap();
    EmittedFile {
        path: PathBuf::from("lib/roundhouse/route_helpers.ex"),
        content: s,
    }
}

// Pass-2 route registration --------------------------------------------

pub(super) fn emit_ex_routes_register(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "defmodule App.Routes do").unwrap();
    writeln!(s, "  @moduledoc false").unwrap();
    writeln!(s, "  alias Roundhouse.Http.Router").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "  def register do").unwrap();
    writeln!(s, "    Router.reset()").unwrap();
    for entry in &app.routes.entries {
        emit_ex_route_spec(&mut s, entry);
    }
    writeln!(s, "    :ok").unwrap();
    writeln!(s, "  end").unwrap();
    writeln!(s, "end").unwrap();
    EmittedFile {
        path: PathBuf::from("lib/app/routes.ex"),
        content: s,
    }
}

fn emit_ex_route_spec(out: &mut String, spec: &RouteSpec) {
    match spec {
        RouteSpec::Explicit { method, path, controller, action, .. } => {
            let verb = match method {
                crate::dialect::HttpMethod::Get => "get",
                crate::dialect::HttpMethod::Post => "post",
                crate::dialect::HttpMethod::Put => "put",
                crate::dialect::HttpMethod::Patch => "patch",
                crate::dialect::HttpMethod::Delete => "delete",
                _ => "get",
            };
            writeln!(
                out,
                "    Router.{verb}({:?}, {}, :{})",
                path,
                controller.0,
                action.as_str(),
            )
            .unwrap();
        }
        RouteSpec::Root { target } => {
            let (controller, action) = target
                .split_once('#')
                .map(|(c, a)| (controller::controller_class_name(c), a.to_string()))
                .unwrap_or_else(|| (target.clone(), "index".to_string()));
            writeln!(out, "    Router.root({controller}, :{action})").unwrap();
        }
        RouteSpec::Resources { name, only, except: _, nested } => {
            let controller = controller::controller_class_name(name.as_str());
            let mut opts: Vec<String> = Vec::new();
            if !only.is_empty() {
                let parts: Vec<String> =
                    only.iter().map(|s| format!(":{}", s.as_str())).collect();
                opts.push(format!("only: [{}]", parts.join(", ")));
            }
            if !nested.is_empty() {
                let mut nested_parts: Vec<String> = Vec::new();
                for child in nested {
                    if let Some(part) = ex_nested_spec_entry(child) {
                        nested_parts.push(part);
                    }
                }
                if !nested_parts.is_empty() {
                    opts.push(format!("nested: [{}]", nested_parts.join(", ")));
                }
            }
            if opts.is_empty() {
                writeln!(
                    out,
                    "    Router.resources({:?}, {})",
                    name.as_str(),
                    controller
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    "    Router.resources({:?}, {}, [{}])",
                    name.as_str(),
                    controller,
                    opts.join(", ")
                )
                .unwrap();
            }
        }
    }
}

fn ex_nested_spec_entry(spec: &RouteSpec) -> Option<String> {
    let RouteSpec::Resources { name, only, except: _, nested: _ } = spec else {
        return None;
    };
    let controller = controller::controller_class_name(name.as_str());
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!("name: {:?}", name.as_str()));
    parts.push(format!("controller: {}", controller));
    if !only.is_empty() {
        let items: Vec<String> =
            only.iter().map(|s| format!(":{}", s.as_str())).collect();
        parts.push(format!("only: [{}]", items.join(", ")));
    }
    Some(format!("[{}]", parts.join(", ")))
}
