//! Elixir test/spec emit — `test/<name>_test.exs` per ingested
//! TestModule. Model tests render through the local `ExTestCtx`-driven
//! walker; controller tests use the dedicated controller-test render
//! path further down in this module.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use super::expr::emit_literal;
use crate::App;
use crate::dialect::{Test, TestModule};
use crate::expr::{Expr, ExprNode, LValue, Literal};
use crate::ident::Symbol;
use crate::naming::snake_case;

pub(super) fn emit_ex_test(tm: &TestModule, app: &App) -> EmittedFile {
    let fixture_names: Vec<Symbol> =
        app.fixtures.iter().map(|f| f.name.clone()).collect();
    let known_models: Vec<Symbol> =
        app.models.iter().map(|m| m.name.0.clone()).collect();
    let mut attrs_set: std::collections::BTreeSet<Symbol> =
        std::collections::BTreeSet::new();
    for m in &app.models {
        for attr in m.attributes.fields.keys() {
            attrs_set.insert(attr.clone());
        }
    }
    let model_attrs: Vec<Symbol> = attrs_set.into_iter().collect();

    let ctx = ExTestCtx {
        app,
        fixture_names: &fixture_names,
        known_models: &known_models,
        model_attrs: &model_attrs,
    };

    let is_controller_test = tm.name.0.as_str().ends_with("ControllerTest");

    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "defmodule {} do", tm.name.0).unwrap();
    writeln!(s, "  use ExUnit.Case").unwrap();
    if is_controller_test {
        writeln!(s, "  alias Roundhouse.TestClient").unwrap();
        writeln!(s, "  alias Roundhouse.TestResponse").unwrap();
        writeln!(s, "  import Roundhouse.RouteHelpers").unwrap();
    }
    // Each test starts on a fresh :memory: SQLite DB with all
    // fixtures loaded — Rails' transactional-fixture isolation
    // adapted to Elixir's per-process test semantics.
    if !app.fixtures.is_empty() {
        writeln!(s).unwrap();
        writeln!(s, "  setup do").unwrap();
        if is_controller_test {
            writeln!(s, "    App.Routes.register()").unwrap();
        }
        writeln!(s, "    Fixtures.setup()").unwrap();
        writeln!(s, "    :ok").unwrap();
        writeln!(s, "  end").unwrap();
    }

    for test in &tm.tests {
        writeln!(s).unwrap();
        if is_controller_test {
            writeln!(s, "  test {:?} do", test.name).unwrap();
            let body = emit_ex_controller_test_body(test, app, ctx);
            if body.is_empty() {
                writeln!(s, "    :ok").unwrap();
            } else {
                for line in body.lines() {
                    writeln!(s, "    {line}").unwrap();
                }
            }
            writeln!(s, "  end").unwrap();
        } else if test_needs_runtime_unsupported_ex(test) {
            writeln!(s, "  @tag :skip").unwrap();
            writeln!(s, "  test {:?} do", test.name).unwrap();
            writeln!(s, "    # Phase 3: needs persistence runtime").unwrap();
            writeln!(s, "  end").unwrap();
        } else {
            writeln!(s, "  test {:?} do", test.name).unwrap();
            let body = emit_ex_test_body(&test.body, ctx);
            for line in body.lines() {
                writeln!(s, "    {line}").unwrap();
            }
            writeln!(s, "  end").unwrap();
        }
    }

    writeln!(s, "end").unwrap();

    let filename = snake_case(tm.name.0.as_str());
    EmittedFile {
        path: PathBuf::from(format!("test/{filename}.exs")),
        content: s,
    }
}

#[derive(Clone, Copy)]
struct ExTestCtx<'a> {
    app: &'a App,
    fixture_names: &'a [Symbol],
    known_models: &'a [Symbol],
    model_attrs: &'a [Symbol],
}

fn emit_ex_test_body(body: &Expr, ctx: ExTestCtx) -> String {
    match &*body.node {
        ExprNode::Seq { exprs } if !exprs.is_empty() => exprs
            .iter()
            .map(|e| emit_ex_test_stmt(e, ctx))
            .collect::<Vec<_>>()
            .join("\n"),
        _ => emit_ex_test_stmt(body, ctx),
    }
}

fn emit_ex_test_stmt(e: &Expr, ctx: ExTestCtx) -> String {
    match &*e.node {
        ExprNode::Assign { target: LValue::Var { name, .. }, value } => {
            format!("{} = {}", name, emit_ex_test_expr(value, ctx))
        }
        _ => emit_ex_test_expr(e, ctx),
    }
}

fn emit_ex_test_expr(e: &Expr, ctx: ExTestCtx) -> String {
    match &*e.node {
        ExprNode::Lit { value } => emit_literal(value),
        ExprNode::Var { name, .. } => name.to_string(),
        ExprNode::Const { path } => {
            path.iter().map(|s| s.to_string()).collect::<Vec<_>>().join(".")
        }
        ExprNode::Send { recv, method, args, block, .. } => {
            emit_ex_test_send(recv.as_ref(), method.as_str(), args, block.as_ref(), ctx)
        }
        ExprNode::BoolOp { op, left, right, .. } => {
            use crate::expr::BoolOpKind;
            let op_s = match op {
                BoolOpKind::Or => "or",
                BoolOpKind::And => "and",
            };
            format!(
                "{} {op_s} {}",
                emit_ex_test_expr(left, ctx),
                emit_ex_test_expr(right, ctx)
            )
        }
        ExprNode::Hash { entries, .. } => {
            let parts: Vec<String> = entries
                .iter()
                .map(|(k, v)| {
                    if let ExprNode::Lit { value: Literal::Sym { value } } = &*k.node {
                        format!("{value}: {}", emit_ex_test_expr(v, ctx))
                    } else {
                        format!(
                            "{} => {}",
                            emit_ex_test_expr(k, ctx),
                            emit_ex_test_expr(v, ctx),
                        )
                    }
                })
                .collect();
            format!("%{{{}}}", parts.join(", "))
        }
        _ => format!("# TODO: Elixir test emit for {:?}", std::mem::discriminant(&*e.node)),
    }
}

fn emit_ex_test_send(
    recv: Option<&Expr>,
    method: &str,
    args: &[Expr],
    block: Option<&Expr>,
    ctx: ExTestCtx,
) -> String {
    let args_s: Vec<String> = args.iter().map(|a| emit_ex_test_expr(a, ctx)).collect();

    // Fixture accessor: articles(:one) → Fixtures.Articles.one()
    if recv.is_none()
        && args.len() == 1
        && ctx.fixture_names.iter().any(|s| s.as_str() == method)
    {
        if let ExprNode::Lit { value: Literal::Sym { value: sym } } = &*args[0].node {
            let ns = crate::naming::camelize(method);
            return format!("Fixtures.{ns}.{}()", sym.as_str());
        }
    }

    // assert_difference("Class.count", delta) do ... end →
    // `_before = ...; <body>; _after = ...; assert _after - _before == delta`.
    if recv.is_none() && method == "assert_difference" {
        if let Some(body) = block {
            if let Some(count_expr) = args
                .first()
                .and_then(|a| match &*a.node {
                    ExprNode::Lit { value: Literal::Str { value } } => {
                        rewrite_ruby_dot_call_ex(value)
                    }
                    _ => None,
                })
            {
                let delta = args_s.get(1).cloned().unwrap_or_else(|| "1".into());
                let body_s = emit_block_body_ex(body, ctx);
                return format!(
                    "count_before = {count_expr}\n{body_s}\ncount_after = {count_expr}\nassert count_after - count_before == {delta}"
                );
            }
        }
    }

    // owner.<assoc>.create(hash) / .build(hash) — HasMany rewrite
    // wrapped in an anonymous function so the record (with its
    // assigned id) becomes available as the expression's value.
    if (method == "create" || method == "build") && args.len() == 1 {
        if let Some(outer_recv) = recv {
            if let ExprNode::Send {
                recv: Some(assoc_recv),
                method: assoc_method,
                args: inner_args,
                ..
            } = &*outer_recv.node
            {
                if inner_args.is_empty() {
                    if let Some(s) = try_emit_assoc_create_ex(
                        assoc_recv,
                        assoc_method.as_str(),
                        args,
                        method,
                        ctx,
                    ) {
                        return s;
                    }
                }
            }
        }
    }

    // Assertion macros → ExUnit's assert/refute.
    if recv.is_none() {
        match (method, args_s.len()) {
            ("assert_equal", 2) => {
                return format!(
                    "assert {actual} == {expected}",
                    expected = args_s[0],
                    actual = args_s[1]
                );
            }
            ("assert_not_equal", 2) => {
                return format!(
                    "refute {actual} == {expected}",
                    expected = args_s[0],
                    actual = args_s[1]
                );
            }
            ("assert_not", 1) => return format!("refute {}", args_s[0]),
            ("assert", 1) => return format!("assert {}", args_s[0]),
            ("assert_nil", 1) => return format!("assert is_nil({})", args_s[0]),
            ("assert_not_nil", 1) => return format!("refute is_nil({})", args_s[0]),
            _ => {}
        }
    }

    // `Class.new(hash)` → `%Class{ k: v, ... }` struct literal.
    if let Some(r) = recv {
        if method == "new" && args.len() == 1 {
            if let ExprNode::Const { path } = &*r.node {
                if let Some(class_name) = path.last() {
                    if ctx.known_models.iter().any(|s| s == class_name) {
                        if let ExprNode::Hash { entries, .. } = &*args[0].node {
                            let pairs: Vec<String> = entries
                                .iter()
                                .filter_map(|(k, v)| {
                                    if let ExprNode::Lit {
                                        value: Literal::Sym { value: f },
                                    } = &*k.node
                                    {
                                        Some(format!(
                                            "{}: {}",
                                            f.as_str(),
                                            emit_ex_test_expr(v, ctx)
                                        ))
                                    } else {
                                        None
                                    }
                                })
                                .collect();
                            return format!("%{} {{{}}}", class_name, pairs.join(", "));
                        }
                    }
                }
            }
        }
    }

    match recv {
        None => {
            if args_s.is_empty() {
                method.to_string()
            } else {
                format!("{}({})", method, args_s.join(", "))
            }
        }
        Some(r) => {
            let recv_s = emit_ex_test_expr(r, ctx);
            let is_class_call = matches!(&*r.node, ExprNode::Const { .. });
            if is_class_call {
                // Module.function(args) — Elixir's module-function-call form.
                if args_s.is_empty() {
                    format!("{recv_s}.{method}()")
                } else {
                    format!("{recv_s}.{method}({})", args_s.join(", "))
                }
            } else {
                let is_attr = args_s.is_empty()
                    && ctx.model_attrs.iter().any(|s| s.as_str() == method);
                if is_attr {
                    format!("{recv_s}.{method}")
                } else if matches!(method, "save" | "destroy") && args_s.is_empty() {
                    // Instance-method-like call on a model record:
                    // `article.save` / `article.destroy` in Ruby →
                    // `Module.save(article)` / `Module.destroy(article)`.
                    format!("{}(\n      {recv_s}\n    )", ex_module_fn_for(r, method))
                } else if args_s.is_empty() {
                    format!("{recv_s}.{method}")
                } else {
                    format!("{recv_s}.{method}({})", args_s.join(", "))
                }
            }
        }
    }
}

/// Parse a Ruby-style `"Class.method"` expression into Elixir
/// `Class.method()`. Capitalized LHS → module function call;
/// lowercase LHS → instance field access (same as in the other
/// targets).
fn rewrite_ruby_dot_call_ex(expr: &str) -> Option<String> {
    let trimmed = expr.trim();
    let (lhs, rhs) = trimmed.split_once('.')?;
    let is_ident = |s: &str| {
        !s.is_empty()
            && s.chars().next().is_some_and(|c| c.is_alphabetic() || c == '_')
            && s.chars().all(|c| c.is_alphanumeric() || c == '_')
    };
    if !is_ident(lhs) || !is_ident(rhs) {
        return None;
    }
    let is_class = lhs.chars().next().is_some_and(|c| c.is_uppercase());
    if is_class {
        Some(format!("{lhs}.{rhs}()"))
    } else {
        Some(format!("{lhs}.{rhs}"))
    }
}

/// Render a Ruby block body as Elixir statements, peeling one
/// Lambda layer. Ruby `do ... end` lowers to `ExprNode::Lambda`.
fn emit_block_body_ex(e: &Expr, ctx: ExTestCtx) -> String {
    let inner = match &*e.node {
        ExprNode::Lambda { body, .. } => body,
        _ => e,
    };
    match &*inner.node {
        ExprNode::Seq { exprs } if !exprs.is_empty() => exprs
            .iter()
            .map(|s| emit_ex_test_stmt(s, ctx))
            .collect::<Vec<_>>()
            .join("\n"),
        _ => emit_ex_test_stmt(inner, ctx),
    }
}

fn try_emit_assoc_create_ex(
    owner: &Expr,
    assoc_name: &str,
    args: &[Expr],
    outer_method: &str,
    ctx: ExTestCtx,
) -> Option<String> {
    let resolved = crate::lower::resolve_has_many(
        &Symbol::from(assoc_name),
        owner.ty.as_ref(),
        ctx.app,
    )?;
    let target_class = resolved.target_class.0.as_str();
    let foreign_key = resolved.foreign_key.as_str();

    let owner_s = emit_ex_test_expr(owner, ctx);
    let hash_entries = match &args.first()?.node.as_ref() {
        ExprNode::Hash { entries, .. } => entries.clone(),
        _ => return None,
    };

    let mut pairs: Vec<String> = vec![format!("{foreign_key}: {owner_s}.id")];
    for (k, v) in &hash_entries {
        if let ExprNode::Lit { value: Literal::Sym { value: field_name } } = &*k.node {
            pairs.push(format!(
                "{}: {}",
                field_name.as_str(),
                emit_ex_test_expr(v, ctx),
            ));
        }
    }
    let struct_lit = format!("%{target_class}{{{}}}", pairs.join(", "));
    // Elixir has no direct "block expression" — an anonymous function
    // call is the standard way to evaluate a sequence and yield the
    // last value. `.create` saves and returns the record with its id
    // assigned; `.build` just constructs.
    if outer_method == "create" {
        Some(format!(
            "(fn ->\n      record = {struct_lit}\n      {target_class}.save(record)\n      %{{record | id: Roundhouse.Db.last_insert_rowid()}}\n    end).()"
        ))
    } else {
        Some(struct_lit)
    }
}

/// Guess the module-function path for `recv.method`. If recv is a
/// struct, the struct's module holds the function — so `article.save`
/// emits as `Article.save(article)`. Without type info we scrape the
/// variable name and infer.
fn ex_module_fn_for(recv: &Expr, method: &str) -> String {
    if let ExprNode::Var { name, .. } = &*recv.node {
        let n = name.as_str();
        // Variable names for fixtures follow the snake-cased class name.
        let camelized = crate::naming::camelize(n);
        return format!("{camelized}.{method}");
    }
    format!("??.{method}") // fallback; should be rare
}

fn test_needs_runtime_unsupported_ex(_test: &Test) -> bool {
    // Phase 3 rounded out Elixir's real-blog coverage. Keep as a
    // future-guard; no current pattern forces a skip.
    false
}

// Pass-2 controller-test emit ------------------------------------------
//
// Walks the test AST via the shared classifier + renders each
// statement through an Elixir-specific assertion render table.

fn emit_ex_controller_test_body(test: &Test, app: &App, ctx: ExTestCtx) -> String {
    let mut out = String::new();
    // Prime ivars read without assignment: `@article` → `article = Fixtures.Articles.one()`.
    let walked = crate::lower::walk_controller_ivars(&test.body);
    for ivar in walked.ivars_read_without_assign() {
        let plural = crate::naming::pluralize_snake(ivar.as_str());
        if ctx.fixture_names.iter().any(|s| s.as_str() == plural) {
            let ns = crate::naming::camelize(&plural);
            out.push_str(&format!("{} = Fixtures.{}.one()\n", ivar.as_str(), ns));
        }
    }

    for stmt in crate::lower::test_body_stmts(&test.body) {
        let rendered = emit_ex_ctrl_test_stmt(stmt, app, ctx);
        out.push_str(&rendered);
        out.push('\n');
    }
    out
}

fn emit_ex_ctrl_test_stmt(stmt: &Expr, app: &App, ctx: ExTestCtx) -> String {
    match &*stmt.node {
        ExprNode::Send { recv: None, method, args, block, .. } => {
            emit_ex_ctrl_test_send(method.as_str(), args, block.as_ref(), app, ctx)
        }
        ExprNode::Send { recv: Some(r), method, args, .. } => {
            if method.as_str() == "reload" {
                let recv_s = match &*r.node {
                    ExprNode::Ivar { name } | ExprNode::Var { name, .. } => name.to_string(),
                    _ => emit_ex_ctrl_test_expr(r, app, ctx),
                };
                let module = match &*r.node {
                    ExprNode::Ivar { name } | ExprNode::Var { name, .. } => {
                        crate::naming::camelize(name.as_str())
                    }
                    _ => "Unknown".to_string(),
                };
                return format!("{recv_s} = {module}.reload({recv_s})");
            }
            let recv_s = emit_ex_ctrl_test_expr(r, app, ctx);
            let args_s: Vec<String> = args
                .iter()
                .map(|a| emit_ex_ctrl_test_expr(a, app, ctx))
                .collect();
            if args_s.is_empty() {
                format!("{recv_s}.{}", method.as_str())
            } else {
                format!("{recv_s}.{}({})", method.as_str(), args_s.join(", "))
            }
        }
        ExprNode::Assign { target: LValue::Var { name, .. }, value }
        | ExprNode::Assign { target: LValue::Ivar { name }, value } => {
            format!("{name} = {}", emit_ex_ctrl_test_expr(value, app, ctx))
        }
        _ => emit_ex_ctrl_test_expr(stmt, app, ctx),
    }
}

fn emit_ex_ctrl_test_send(
    method: &str,
    args: &[Expr],
    block: Option<&Expr>,
    app: &App,
    ctx: ExTestCtx,
) -> String {
    use crate::lower::ControllerTestSend;
    match crate::lower::classify_controller_test_send(method, args, block) {
        Some(ControllerTestSend::HttpGet { url }) => {
            let u = emit_ex_url_expr(url, app, ctx);
            format!("resp = TestClient.get({u})")
        }
        Some(ControllerTestSend::HttpWrite { method: m, url, params }) => {
            let u = emit_ex_url_expr(url, app, ctx);
            let body = params
                .map(|h| flatten_ex_params_to_form(h, None, app, ctx))
                .unwrap_or_else(|| "%{}".to_string());
            format!("resp = TestClient.{m}({u}, {body})")
        }
        Some(ControllerTestSend::HttpDelete { url }) => {
            let u = emit_ex_url_expr(url, app, ctx);
            format!("resp = TestClient.delete({u})")
        }
        Some(ControllerTestSend::AssertResponse { sym }) => match sym.as_str() {
            "success" => "TestResponse.assert_ok(resp)".to_string(),
            "unprocessable_entity" => "TestResponse.assert_unprocessable(resp)".to_string(),
            other => format!("TestResponse.assert_status(resp, 200) # TODO: {other:?}"),
        },
        Some(ControllerTestSend::AssertRedirectedTo { url }) => {
            let u = emit_ex_url_expr(url, app, ctx);
            format!("TestResponse.assert_redirected_to(resp, {u})")
        }
        Some(ControllerTestSend::AssertSelect { selector, kind }) => {
            emit_ex_assert_select_classified(selector, kind, app, ctx)
        }
        Some(ControllerTestSend::AssertDifference {
            method: _,
            count_expr,
            delta,
            block,
        }) => emit_ex_assert_difference_classified(count_expr, delta, block, app, ctx),
        Some(ControllerTestSend::AssertEqual { expected, actual }) => {
            let e = emit_ex_ctrl_test_expr(expected, app, ctx);
            let a = emit_ex_ctrl_test_expr(actual, app, ctx);
            format!("assert {a} == {e}")
        }
        None => {
            let args_s: Vec<String> = args
                .iter()
                .map(|a| emit_ex_ctrl_test_expr(a, app, ctx))
                .collect();
            if args_s.is_empty() {
                method.to_string()
            } else {
                format!("{method}({})", args_s.join(", "))
            }
        }
    }
}

fn emit_ex_url_expr(expr: &Expr, app: &App, ctx: ExTestCtx) -> String {
    use crate::lower::UrlArg;
    let Some(helper) = crate::lower::classify_url_expr(expr) else {
        return emit_ex_ctrl_test_expr(expr, app, ctx);
    };
    let helper_name = format!("{}_path", helper.helper_base);
    let args_s: Vec<String> = helper
        .args
        .iter()
        .map(|a| match a {
            UrlArg::IvarOrVarId(name) => format!("{name}.id"),
            UrlArg::ModelLast(class) => format!("{}.last().id", class.as_str()),
            UrlArg::Raw(e) => emit_ex_ctrl_test_expr(e, app, ctx),
        })
        .collect();
    if args_s.is_empty() {
        format!("{helper_name}()")
    } else {
        format!("{helper_name}({})", args_s.join(", "))
    }
}

fn emit_ex_assert_select_classified(
    selector_expr: &Expr,
    kind: crate::lower::AssertSelectKind<'_>,
    app: &App,
    ctx: ExTestCtx,
) -> String {
    use crate::lower::AssertSelectKind;
    let ExprNode::Lit { value: Literal::Str { value: selector } } =
        &*selector_expr.node
    else {
        return format!(
            "TestResponse.assert_select(resp, {}) # TODO: dynamic selector",
            emit_ex_ctrl_test_expr(selector_expr, app, ctx),
        );
    };
    match kind {
        AssertSelectKind::Text(expr) => {
            let text = emit_ex_ctrl_test_expr(expr, app, ctx);
            format!("TestResponse.assert_select_text(resp, {selector:?}, {text})")
        }
        AssertSelectKind::Minimum(expr) => {
            let n = emit_ex_ctrl_test_expr(expr, app, ctx);
            format!("TestResponse.assert_select_min(resp, {selector:?}, {n})")
        }
        AssertSelectKind::SelectorBlock(b) => {
            let mut out = String::new();
            out.push_str(&format!("TestResponse.assert_select(resp, {selector:?})\n"));
            let inner_body = match &*b.node {
                ExprNode::Lambda { body, .. } => body,
                _ => b,
            };
            for stmt in crate::lower::test_body_stmts(inner_body) {
                out.push_str(&emit_ex_ctrl_test_stmt(stmt, app, ctx));
                out.push('\n');
            }
            out.trim_end().to_string()
        }
        AssertSelectKind::SelectorOnly => {
            format!("TestResponse.assert_select(resp, {selector:?})")
        }
    }
}

fn emit_ex_assert_difference_classified(
    count_expr_str: String,
    expected_delta: i64,
    block: Option<&Expr>,
    app: &App,
    ctx: ExTestCtx,
) -> String {
    // `Article.count` → `Article.count()` in Elixir.
    let count_expr = count_expr_str
        .split_once('.')
        .map(|(cls, m)| format!("{cls}.{m}()"))
        .unwrap_or_else(|| count_expr_str.clone());

    let mut out = String::new();
    out.push_str(&format!("count_before = {count_expr}\n"));
    if let Some(b) = block {
        let inner_body = match &*b.node {
            ExprNode::Lambda { body, .. } => body,
            _ => b,
        };
        for stmt in crate::lower::test_body_stmts(inner_body) {
            out.push_str(&emit_ex_ctrl_test_stmt(stmt, app, ctx));
            out.push('\n');
        }
    }
    out.push_str(&format!("count_after = {count_expr}\n"));
    out.push_str(&format!("assert count_after - count_before == {expected_delta}"));
    out
}

fn emit_ex_ctrl_test_expr(expr: &Expr, app: &App, ctx: ExTestCtx) -> String {
    match &*expr.node {
        ExprNode::Lit { value } => emit_literal(value),
        ExprNode::Ivar { name } => name.to_string(),
        ExprNode::Var { name, .. } => name.to_string(),
        ExprNode::Const { path } => {
            path.iter().map(|s| s.to_string()).collect::<Vec<_>>().join(".")
        }
        ExprNode::Send { recv: Some(r), method, args, .. } => {
            let m = method.as_str();
            if m == "last" && args.is_empty() {
                if let ExprNode::Const { path } = &*r.node {
                    let class = path.last().map(|s| s.as_str().to_string()).unwrap_or_default();
                    return format!("{class}.last()");
                }
            }
            if m == "count" && args.is_empty() {
                if let ExprNode::Const { path } = &*r.node {
                    let class = path.last().map(|s| s.as_str().to_string()).unwrap_or_default();
                    return format!("{class}.count()");
                }
            }
            if args.is_empty() {
                let recv_s = match &*r.node {
                    ExprNode::Ivar { name } | ExprNode::Var { name, .. } => name.to_string(),
                    _ => emit_ex_ctrl_test_expr(r, app, ctx),
                };
                return format!("{recv_s}.{m}");
            }
            let recv_s = emit_ex_ctrl_test_expr(r, app, ctx);
            let args_s: Vec<String> = args
                .iter()
                .map(|a| emit_ex_ctrl_test_expr(a, app, ctx))
                .collect();
            format!("{recv_s}.{m}({})", args_s.join(", "))
        }
        ExprNode::Send { recv: None, method, args, .. } => {
            if method.as_str().ends_with("_url") || method.as_str().ends_with("_path") {
                return emit_ex_url_expr(expr, app, ctx);
            }
            let args_s: Vec<String> = args
                .iter()
                .map(|a| emit_ex_ctrl_test_expr(a, app, ctx))
                .collect();
            if args_s.is_empty() {
                method.to_string()
            } else {
                format!("{method}({})", args_s.join(", "))
            }
        }
        ExprNode::Hash { entries, .. } => {
            let parts: Vec<String> = entries
                .iter()
                .map(|(k, v)| {
                    if let ExprNode::Lit {
                        value: Literal::Sym { value },
                    } = &*k.node
                    {
                        format!("{value}: {}", emit_ex_ctrl_test_expr(v, app, ctx))
                    } else {
                        format!(
                            "{} => {}",
                            emit_ex_ctrl_test_expr(k, app, ctx),
                            emit_ex_ctrl_test_expr(v, app, ctx),
                        )
                    }
                })
                .collect();
            format!("%{{{}}}", parts.join(", "))
        }
        _ => "nil # TODO expr".to_string(),
    }
}

fn flatten_ex_params_to_form(
    expr: &Expr,
    scope: Option<&str>,
    app: &App,
    ctx: ExTestCtx,
) -> String {
    let pairs: Vec<String> = crate::lower::flatten_params_pairs(expr, scope)
        .into_iter()
        .map(|(key, value)| {
            let val = emit_ex_ctrl_test_expr(value, app, ctx);
            format!("{key:?} => to_string({val})")
        })
        .collect();
    format!("%{{{}}}", pairs.join(", "))
}

#[allow(dead_code)]

fn test_body_uses_unsupported_ex(e: &Expr) -> bool {
    use crate::expr::InterpPart;
    let self_hit = match &*e.node {
        ExprNode::Send { recv, method, .. } => {
            let m = method.as_str();
            matches!(
                m,
                "assert_difference"
                    | "destroy"
                    | "destroy!"
                    | "build"
                    | "create"
                    | "create!"
            ) || (m == "count"
                && recv.as_ref().is_some_and(|r| matches!(&*r.node, ExprNode::Const { .. })))
        }
        _ => false,
    };
    if self_hit {
        return true;
    }
    match &*e.node {
        ExprNode::Send { recv, args, block, .. } => {
            if let Some(r) = recv {
                if test_body_uses_unsupported_ex(r) {
                    return true;
                }
            }
            for a in args {
                if test_body_uses_unsupported_ex(a) {
                    return true;
                }
            }
            if let Some(b) = block {
                if test_body_uses_unsupported_ex(b) {
                    return true;
                }
            }
        }
        ExprNode::Seq { exprs } | ExprNode::Array { elements: exprs, .. } => {
            for e in exprs {
                if test_body_uses_unsupported_ex(e) {
                    return true;
                }
            }
        }
        ExprNode::Hash { entries, .. } => {
            for (k, v) in entries {
                if test_body_uses_unsupported_ex(k) || test_body_uses_unsupported_ex(v) {
                    return true;
                }
            }
        }
        ExprNode::StringInterp { parts } => {
            for p in parts {
                if let InterpPart::Expr { expr } = p {
                    if test_body_uses_unsupported_ex(expr) {
                        return true;
                    }
                }
            }
        }
        ExprNode::BoolOp { left, right, .. }
        | ExprNode::RescueModifier { expr: left, fallback: right } => {
            if test_body_uses_unsupported_ex(left) || test_body_uses_unsupported_ex(right) {
                return true;
            }
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            if test_body_uses_unsupported_ex(cond)
                || test_body_uses_unsupported_ex(then_branch)
                || test_body_uses_unsupported_ex(else_branch)
            {
                return true;
            }
        }
        ExprNode::Let { value, body, .. } => {
            if test_body_uses_unsupported_ex(value) || test_body_uses_unsupported_ex(body) {
                return true;
            }
        }
        ExprNode::Lambda { body, .. } => {
            if test_body_uses_unsupported_ex(body) {
                return true;
            }
        }
        ExprNode::Assign { value, .. } => {
            if test_body_uses_unsupported_ex(value) {
                return true;
            }
        }
        _ => {}
    }
    false
}
