//! Pass-2 views.
//!
//! Translates the compiled-ERB IR into Elixir functions that
//! concatenate to a `buf` binary, with Roundhouse runtime modules
//! (ViewHelpers, FormBuilder, RouteHelpers, Importmap) called for
//! the structural pieces.

use std::fmt::Write;
use std::path::PathBuf;

use crate::App;
use crate::expr::{Expr, ExprNode, LValue, Literal};
use crate::ident::Symbol;

use super::super::EmittedFile;
use super::expr::emit_literal;

pub(super) fn emit_ex_views(app: &App) -> EmittedFile {
    let known_models: Vec<Symbol> =
        app.models.iter().map(|m| m.name.0.clone()).collect();
    let attrs_by_class: std::collections::BTreeMap<String, Vec<String>> = app
        .models
        .iter()
        .map(|m| {
            (
                m.name.0.as_str().to_string(),
                m.attributes
                    .fields
                    .keys()
                    .map(|k| k.as_str().to_string())
                    .collect(),
            )
        })
        .collect();
    let has_manys = crate::lower::build_has_many_table(app);
    let stylesheets = app.stylesheets.clone();

    let mut body = String::new();

    let mut emitted_names: std::collections::BTreeSet<String> =
        std::collections::BTreeSet::new();

    for v in &app.views {
        let fn_name = ex_view_function_name(v.name.as_str());
        if !emitted_names.insert(fn_name.clone()) {
            continue;
        }
        emit_view_file_pass2_ex(&mut body, v, &known_models, &attrs_by_class, &has_manys, &stylesheets);
        writeln!(body).unwrap();
    }

    // Stub missing standard CRUD views so controllers always link.
    for model in &app.models {
        if model.attributes.fields.is_empty() {
            continue;
        }
        let class = model.name.0.as_str();
        let plural = crate::naming::pluralize_snake(class);
        for (_, suffix) in [
            ("Index", "index"),
            ("Show", "show"),
            ("New", "new"),
            ("Edit", "edit"),
        ] {
            let view_name = format!("{plural}/{suffix}");
            let fn_name = ex_view_function_name(&view_name);
            if emitted_names.insert(fn_name.clone()) {
                writeln!(body, "  def {fn_name}(_record), do: \"\"").unwrap();
                writeln!(body).unwrap();
            }
        }
    }

    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "defmodule App.Views do").unwrap();
    writeln!(s, "  @moduledoc false").unwrap();
    if ex_text_references(&body, "ViewHelpers") {
        writeln!(s, "  alias Roundhouse.ViewHelpers").unwrap();
    }
    if ex_text_references(&body, "FormBuilder") {
        writeln!(s, "  alias Roundhouse.FormBuilder").unwrap();
    }
    if ex_text_references(&body, "RouteHelpers") {
        writeln!(s, "  alias Roundhouse.RouteHelpers").unwrap();
    }
    if ex_text_references(&body, "Importmap") {
        writeln!(s, "  alias Roundhouse.Importmap").unwrap();
    }
    writeln!(s).unwrap();
    s.push_str(&body);
    writeln!(s, "end").unwrap();
    EmittedFile {
        path: PathBuf::from("lib/app/views.ex"),
        content: s,
    }
}

fn ex_view_function_name(name: &str) -> String {
    let mut parts: Vec<String> = Vec::new();
    for seg in name.split('/') {
        let trimmed = seg.strip_prefix('_').unwrap_or(seg);
        parts.push(trimmed.to_string());
    }
    format!("render_{}", parts.join("_"))
}

fn emit_view_file_pass2_ex(
    out: &mut String,
    view: &crate::dialect::View,
    known_models: &[Symbol],
    attrs_by_class: &std::collections::BTreeMap<String, Vec<String>>,
    has_manys: &[crate::lower::HasManyRow],
    stylesheets: &[String],
) {
    let fn_name = ex_view_function_name(view.name.as_str());
    let (arg_name, arg_model) = ex_view_signature(view.name.as_str(), known_models);
    let attrs = arg_model
        .as_ref()
        .and_then(|c| attrs_by_class.get(c).cloned())
        .unwrap_or_default();

    writeln!(out, "  def {fn_name}({arg_name}) do").unwrap();
    writeln!(out, "    _ = {arg_name}").unwrap();
    writeln!(out, "    buf = \"\"").unwrap();

    let mut locals: Vec<String> = vec!["buf".to_string(), arg_name.clone()];
    let ivar_names = ex_collect_ivar_names(&view.body);
    for n in &ivar_names {
        if !locals.iter().any(|x| x == n) {
            locals.push(n.clone());
        }
    }
    let resource_dir = view
        .name
        .as_str()
        .rsplit_once('/')
        .map(|(d, _): (&str, &str)| d.to_string())
        .unwrap_or_default();
    let ctx = ExViewCtx {
        locals,
        arg_name: arg_name.clone(),
        arg_attrs: attrs,
        resource_dir,
        has_manys: has_manys.to_vec(),
        stylesheets: stylesheets.to_vec(),
        form_records: Vec::new(),
        attrs_by_class: attrs_by_class.clone(),
    };

    // Apply the shared erubi-trim pass — same as rust/ts/python/
    // go/crystal. Drops the trailing newline + leading indent of
    // `<% %>` statement tags.
    let trimmed = crate::lower::erb_trim::trim_view(&view.body);
    let body_lines = emit_ex_view_body(&trimmed, &ctx);
    for line in body_lines {
        writeln!(out, "    {line}").unwrap();
    }
    writeln!(out, "    buf").unwrap();
    writeln!(out, "  end").unwrap();
}

#[derive(Clone)]
struct ExViewCtx {
    locals: Vec<String>,
    arg_name: String,
    arg_attrs: Vec<String>,
    resource_dir: String,
    has_manys: Vec<crate::lower::HasManyRow>,
    stylesheets: Vec<String>,
    form_records: Vec<(String, String)>,
    attrs_by_class: std::collections::BTreeMap<String, Vec<String>>,
}

impl ExViewCtx {
    fn is_local(&self, n: &str) -> bool {
        self.locals.iter().any(|x| x == n)
    }
    fn arg_has_attr(&self, name: &str, attr: &str) -> bool {
        name == self.arg_name && self.arg_attrs.iter().any(|a| a == attr)
    }
    fn local_has_attr(&self, local: &str, attr: &str) -> bool {
        if self.arg_has_attr(local, attr) {
            return true;
        }
        let class = crate::naming::singularize_camelize(local);
        self.attrs_by_class
            .get(&class)
            .map(|attrs| attrs.iter().any(|a| a == attr))
            .unwrap_or(false)
    }
    fn with_locals(&self, more: impl IntoIterator<Item = String>) -> Self {
        let mut next = self.clone();
        for n in more {
            if !next.locals.iter().any(|x| x == &n) {
                next.locals.push(n);
            }
        }
        next
    }
    fn resolve_has_many_on_local(&self, local: &str, assoc: &str) -> Option<(String, String)> {
        if !self.is_local(local) {
            return None;
        }
        crate::lower::resolve_has_many_on_local(&self.has_manys, local, assoc)
    }
}

fn ex_view_signature(
    view_name: &str,
    known_models: &[Symbol],
) -> (String, Option<String>) {
    let (dir, base) = view_name.rsplit_once('/').unwrap_or(("", view_name));
    let is_partial = base.starts_with('_');
    let stem = base.trim_start_matches('_');
    let model_class = crate::naming::singularize_camelize(dir);
    let model_exists = known_models.iter().any(|m| m.as_str() == model_class);
    let singular = crate::naming::singularize(dir);

    if is_partial {
        let arg_name = if model_exists { singular } else { stem.to_string() };
        return (arg_name, if model_exists { Some(model_class) } else { None });
    }
    match stem {
        "index" => (dir.to_string(), if model_exists { Some(model_class) } else { None }),
        _ => (singular, if model_exists { Some(model_class) } else { None }),
    }
}

fn emit_ex_view_body(body: &Expr, ctx: &ExViewCtx) -> Vec<String> {
    let stmts: Vec<&Expr> = match &*body.node {
        ExprNode::Seq { exprs } => exprs.iter().collect(),
        _ => vec![body],
    };
    let mut out = Vec::new();
    for stmt in &stmts {
        out.extend(emit_ex_view_stmt_pass2(stmt, ctx));
    }
    out
}

fn emit_ex_view_stmt_pass2(stmt: &Expr, ctx: &ExViewCtx) -> Vec<String> {
    match &*stmt.node {
        ExprNode::Assign { target: LValue::Var { name, .. }, value }
            if name.as_str() == "_buf" =>
        {
            if let ExprNode::Lit { value: Literal::Str { value: s } } = &*value.node {
                if s.is_empty() {
                    return Vec::new();
                }
            }
            if let ExprNode::Send { recv: Some(recv), method, args, .. } = &*value.node {
                if method.as_str() == "+" && args.len() == 1 {
                    if let ExprNode::Var { name: rn, .. } = &*recv.node {
                        if rn.as_str() == "_buf" {
                            let chunk = emit_ex_view_append_pass2(&args[0], ctx);
                            return chunk
                                .lines()
                                .map(|l| l.to_string())
                                .collect();
                        }
                    }
                }
            }
            vec!["# TODO ERB: buf shape".to_string()]
        }
        ExprNode::Var { name, .. } if name.as_str() == "_buf" => Vec::new(),
        ExprNode::Ivar { .. } => Vec::new(),
        ExprNode::If { cond, then_branch, else_branch } => {
            let cond_s = if is_ex_simple_expr(cond, ctx) {
                emit_ex_view_expr_raw(cond, ctx)
            } else {
                "false".to_string()
            };
            let mut out = vec![format!("buf = if {cond_s} do")];
            let then_lines = emit_ex_view_body(then_branch, ctx);
            out.push("  buf = buf".to_string());
            for line in then_lines {
                out.push(format!("  {line}"));
            }
            out.push("  buf".to_string());
            let has_else = !matches!(
                &*else_branch.node,
                ExprNode::Lit { value: Literal::Nil }
            );
            out.push("else".to_string());
            if has_else {
                out.push("  buf = buf".to_string());
                for line in emit_ex_view_body(else_branch, ctx) {
                    out.push(format!("  {line}"));
                }
                out.push("  buf".to_string());
            } else {
                out.push("  buf".to_string());
            }
            out.push("end".to_string());
            out
        }
        ExprNode::Send { recv: Some(recv), method, args, block: Some(block), .. }
            if method.as_str() == "each" && args.is_empty() =>
        {
            if !is_ex_simple_expr(recv, ctx) {
                return vec!["# TODO ERB: each over complex coll".to_string()];
            }
            let ExprNode::Lambda { params, body, .. } = &*block.node else {
                return vec!["# unexpected each block".to_string()];
            };
            let coll_s = emit_ex_view_expr_raw(recv, ctx);
            let var = params
                .first()
                .map(|p| p.as_str().to_string())
                .unwrap_or_else(|| "item".into());
            let inner_ctx = ctx.with_locals([var.clone()]);
            let inner_lines = emit_ex_view_body(body, &inner_ctx);
            let inner_text = inner_lines.join("\n");
            let emitted_var = if ex_text_references(&inner_text, &var) {
                var.clone()
            } else {
                format!("_{var}")
            };
            let mut out = vec![format!(
                "buf = Enum.reduce({coll_s}, buf, fn {emitted_var}, buf ->"
            )];
            for line in inner_lines {
                out.push(format!("  {line}"));
            }
            out.push("  buf".to_string());
            out.push("end)".to_string());
            out
        }
        // Statement-form `<% content_for :title, "Articles" %>`.
        ExprNode::Send { recv: None, method, args, block: None, .. } => {
            if let Some(crate::lower::ViewHelperKind::ContentForSetter { slot, body }) =
                crate::lower::classify_view_helper(method.as_str(), args)
            {
                if is_ex_simple_expr(body, ctx) {
                    let body_ex = emit_ex_view_expr_raw(body, ctx);
                    return vec![format!(
                        "ViewHelpers.content_for_set({slot:?}, to_string({body_ex}))"
                    )];
                }
            }
            vec!["# TODO ERB: unknown stmt".to_string()]
        }
        _ => vec!["# TODO ERB: unknown stmt".to_string()],
    }
}

fn emit_ex_view_append_pass2(arg: &Expr, ctx: &ExViewCtx) -> String {
    if let ExprNode::Lit { value: Literal::Str { value: s } } = &*arg.node {
        return format!("buf = buf <> {}", ex_string_literal(s));
    }
    let inner = unwrap_to_s_ex(arg);

    // `<%= yield %>` / `<%= yield :head %>`.
    if let ExprNode::Yield { args } = &*inner.node {
        if let Some(first) = args.first() {
            if let Some(slot) = ex_extract_slot_name(first) {
                return format!("buf = buf <> ViewHelpers.get_slot({slot:?})");
            }
        }
        return "buf = buf <> ViewHelpers.get_yield()".to_string();
    }

    // `<%= content_for(:slot) || "default" %>` — BoolOp fallback.
    if let ExprNode::BoolOp { op, left, right, .. } = &*inner.node {
        if matches!(op, crate::expr::BoolOpKind::Or) {
            if let ExprNode::Send { recv: None, method, args, block: None, .. } = &*left.node {
                if method.as_str() == "content_for" && args.len() == 1 {
                    if let Some(slot) = ex_extract_slot_name(&args[0]) {
                        if is_ex_simple_expr(right, ctx) {
                            let fb = emit_ex_view_expr_raw(right, ctx);
                            return format!(
                                "buf = buf <> (case ViewHelpers.content_for_get({slot:?}) do\n  \"\" -> to_string({fb})\n  s -> s\nend)"
                            );
                        }
                    }
                }
            }
        }
    }

    if let ExprNode::Send { recv, method, args, block, .. } = &*inner.node {
        if let Some(rp) = crate::lower::classify_render_partial(
            recv.as_ref(),
            method.as_str(),
            args,
            block.as_ref(),
            &|n| ctx.is_local(n),
        ) {
            return emit_ex_render_partial(&rp, ctx);
        }
    }

    if let ExprNode::Send {
        recv: None,
        method,
        args,
        block: Some(block),
        ..
    } = &*inner.node
    {
        if is_ex_capturing_helper(method.as_str()) {
            return emit_ex_captured_helper(method.as_str(), args, block, ctx);
        }
    }

    // View-helper classifier dispatch.
    if let ExprNode::Send { recv: None, method, args, block: None, .. } = &*inner.node {
        if let Some(kind) = crate::lower::classify_view_helper(method.as_str(), args) {
            if let Some(line) = emit_ex_view_helper(&kind, ctx) {
                return line;
            }
        }
    }

    // FormBuilder method calls (`form.label :title`, etc.).
    if let ExprNode::Send { recv: Some(r), method, args, block: None, .. } = &*inner.node {
        if let ExprNode::Var { name, .. } | ExprNode::Ivar { name } = &*r.node {
            if ctx.form_records.iter().any(|(n, _)| n == name.as_str()) {
                if let Some(fb) = crate::lower::classify_form_builder_method(method.as_str()) {
                    if let Some(call) = emit_ex_form_builder_call(name.as_str(), fb, args, ctx)
                    {
                        return format!("buf = buf <> {call}");
                    }
                }
            }
        }
    }

    if is_ex_simple_expr(inner, ctx) {
        return format!(
            "buf = buf <> to_string({})",
            emit_ex_view_expr_raw(inner, ctx),
        );
    }

    "buf = buf <> \"\" # TODO ERB: complex interpolation".to_string()
}

fn ex_extract_slot_name(arg: &Expr) -> Option<&str> {
    match &*arg.node {
        ExprNode::Lit { value: Literal::Sym { value } } => Some(value.as_str()),
        ExprNode::Lit { value: Literal::Str { value } } => Some(value.as_str()),
        _ => None,
    }
}

fn is_ex_capturing_helper(method: &str) -> bool {
    matches!(method, "form_with" | "content_for")
}

fn emit_ex_captured_helper(
    method: &str,
    args: &[Expr],
    block: &Expr,
    ctx: &ExViewCtx,
) -> String {
    let ExprNode::Lambda { params, body, .. } = &*block.node else {
        return format!("buf = buf <> \"\" # TODO ERB: {method}");
    };
    let cls_expr = args
        .iter()
        .find_map(|a| ex_extract_kwarg(a, "class"))
        .filter(|e| is_ex_simple_expr(e, ctx))
        .map(|e| emit_ex_view_expr_raw(e, ctx))
        .unwrap_or_else(|| "\"\"".to_string());
    match method {
        "form_with" => {
            let model_expr = args.iter().find_map(|a| ex_extract_kwarg(a, "model"));
            let model_nested: Option<Vec<Expr>> = model_expr.and_then(|e| match &*e.node {
                ExprNode::Array { elements, .. } if elements.len() >= 2 => {
                    Some(elements.clone())
                }
                _ => None,
            });
            let record_ref: Option<String> = if let Some(elems) = &model_nested {
                Some(emit_ex_nested_form_record(&elems[elems.len() - 1]))
            } else {
                model_expr
                    .filter(|e| is_ex_simple_expr(e, ctx))
                    .map(|e| emit_ex_view_expr_raw(e, ctx))
                    .or_else(|| {
                        if !ctx.arg_name.is_empty() && ctx.is_local(&ctx.arg_name) {
                            Some(ctx.arg_name.clone())
                        } else {
                            None
                        }
                    })
            };
            let prefix = if let Some(elems) = &model_nested {
                ex_nested_form_child_prefix(&elems[elems.len() - 1])
                    .unwrap_or_else(|| ctx.arg_name.clone())
            } else if !ctx.resource_dir.is_empty() {
                crate::naming::singularize(&ctx.resource_dir)
            } else {
                ctx.arg_name.clone()
            };

            let pname = params.first().map(|p| p.as_str()).unwrap_or("form");
            let plural = if !ctx.resource_dir.is_empty() {
                ctx.resource_dir.clone()
            } else {
                crate::naming::pluralize_snake(&prefix)
            };
            let is_persisted_expr = record_ref
                .as_deref()
                .map(|r| format!("({r}.id != 0)"))
                .unwrap_or_else(|| "false".to_string());
            let action_expr = match (&record_ref, &model_nested) {
                (Some(record), Some(elems)) => {
                    ex_nested_form_path_expr(elems, ctx, record, &prefix)
                }
                (Some(record), None) => format!(
                    "(if {record}.id != 0, do: RouteHelpers.{prefix}_path({record}.id), else: RouteHelpers.{plural}_path())",
                ),
                (None, _) => format!("RouteHelpers.{plural}_path()"),
            };
            let mut inner_ctx = ctx.with_locals([pname.to_string(), "form_begin".to_string()]);
            if let Some(record) = &record_ref {
                inner_ctx.form_records.push((pname.to_string(), record.clone()));
            }
            let body_lines = emit_ex_view_body(body, &inner_ctx);
            let mut lines: Vec<String> = Vec::new();
            lines.push("form_begin = byte_size(buf)".to_string());
            lines.push(format!(
                "{pname} = ViewHelpers.form_builder({prefix:?}, {cls_expr}, {is_persisted_expr})"
            ));
            lines.push(format!("_ = {pname}"));
            if let Some(record) = &record_ref {
                lines.push(format!(
                    "buf = buf <> ViewHelpers.error_messages_for({record}.errors, {prefix:?})"
                ));
            }
            for line in body_lines {
                lines.push(line);
            }
            lines.push(format!(
                "buf = binary_part(buf, 0, form_begin) <> ViewHelpers.form_wrap({action_expr}, {is_persisted_expr}, {cls_expr}, binary_part(buf, form_begin, byte_size(buf) - form_begin))"
            ));
            lines.join("\n")
        }
        "content_for" => {
            let slot = args.first().and_then(ex_extract_slot_name);
            let Some(slot) = slot else {
                let _ = cls_expr;
                return "buf = buf <> \"\"".to_string();
            };
            let mut lines: Vec<String> = Vec::new();
            lines.push("cf_begin = byte_size(buf)".to_string());
            for line in emit_ex_view_body(body, ctx) {
                lines.push(line);
            }
            lines.push(format!(
                "ViewHelpers.content_for_set({slot:?}, binary_part(buf, cf_begin, byte_size(buf) - cf_begin))"
            ));
            lines.push("buf = binary_part(buf, 0, cf_begin)".to_string());
            lines.join("\n")
        }
        _ => {
            let _ = cls_expr;
            "buf = buf <> \"\"".to_string()
        }
    }
}

fn emit_ex_nested_form_record(el: &Expr) -> String {
    match crate::lower::classify_nested_form_child(el) {
        Some(crate::lower::NestedFormChild::ClassNew { class }) => {
            format!("%{class}{{}}")
        }
        Some(crate::lower::NestedFormChild::Local { name }) => name.to_string(),
        None => "nil".to_string(),
    }
}

fn ex_nested_form_child_prefix(el: &Expr) -> Option<String> {
    crate::lower::classify_nested_form_child(el).map(|k| k.prefix())
}

fn ex_nested_element_parts(kind: &crate::lower::NestedUrlElement<'_>) -> (String, String) {
    match kind {
        crate::lower::NestedUrlElement::DirectLocal { name } => {
            ((*name).to_string(), format!("{name}.id"))
        }
        crate::lower::NestedUrlElement::Association { owner, assoc } => {
            ((*assoc).to_string(), format!("{owner}.{assoc}_id"))
        }
    }
}

fn ex_nested_form_path_expr(
    elems: &[Expr],
    ctx: &ExViewCtx,
    record_ref: &str,
    child_prefix: &str,
) -> String {
    let is_local = |n: &str| ctx.is_local(n);
    let mut parent_ids: Vec<String> = Vec::new();
    let mut parent_singulars: Vec<String> = Vec::new();
    for parent in &elems[..elems.len() - 1] {
        let Some(kind) = crate::lower::classify_nested_url_element(parent, &is_local) else {
            return "\"\"".to_string();
        };
        let (singular, id_expr) = ex_nested_element_parts(&kind);
        parent_singulars.push(singular);
        parent_ids.push(id_expr);
    }
    let member_name = format!(
        "{}_{}_path",
        parent_singulars.join("_"),
        child_prefix,
    );
    let child_plural = crate::naming::pluralize_snake(child_prefix);
    let collection_name = format!(
        "{}_{}_path",
        parent_singulars.join("_"),
        child_plural,
    );
    let parent_args = parent_ids.join(", ");
    let member_args = if parent_args.is_empty() {
        format!("{record_ref}.id")
    } else {
        format!("{parent_args}, {record_ref}.id")
    };
    let collection_call = if parent_args.is_empty() {
        format!("RouteHelpers.{collection_name}()")
    } else {
        format!("RouteHelpers.{collection_name}({parent_args})")
    };
    format!(
        "(if {record_ref}.id != 0, do: RouteHelpers.{member_name}({member_args}), else: {collection_call})",
    )
}

/// Compose one AR chain modifier onto a running Elixir list
/// expression. Mirrors rust/ts/python/go/crystal — `all`/
/// `includes`/etc. pass through; `order({field: :dir})` uses
/// `Enum.sort_by/2`; `limit(N)` slices via `Enum.take/2`.
pub(super) fn apply_ex_chain_modifier(prev: String, m: crate::lower::ChainModifier<'_>) -> String {
    match m.method {
        "all" | "includes" | "preload" | "joins" | "distinct" | "select" => prev,
        "order" => {
            let Some(hash) = m.args.first() else { return prev };
            let ExprNode::Hash { entries, .. } = &*hash.node else { return prev };
            let Some((k, v)) = entries.first() else { return prev };
            let field = match &*k.node {
                ExprNode::Lit { value: Literal::Sym { value } } => value.as_str().to_string(),
                ExprNode::Lit { value: Literal::Str { value } } => value.clone(),
                _ => return prev,
            };
            let dir = match &*v.node {
                ExprNode::Lit { value: Literal::Sym { value } } => value.as_str().to_string(),
                ExprNode::Lit { value: Literal::Str { value } } => value.clone(),
                _ => "asc".to_string(),
            };
            if dir == "desc" {
                format!("Enum.sort_by({prev}, & &1.{field}, :desc)")
            } else {
                format!("Enum.sort_by({prev}, & &1.{field})")
            }
        }
        "limit" => {
            let Some(n) = m.args.first() else { return prev };
            if let ExprNode::Lit { value: Literal::Int { value, .. } } = &*n.node {
                return format!("Enum.take({prev}, {value})");
            }
            prev
        }
        _ => prev,
    }
}

/// Render a classified `ViewHelperKind` to an Elixir
/// `buf = buf <> ...` line.
fn emit_ex_view_helper(
    kind: &crate::lower::ViewHelperKind<'_>,
    ctx: &ExViewCtx,
) -> Option<String> {
    use crate::lower::ViewHelperKind::*;
    match kind {
        CsrfMetaTags => Some("buf = buf <> ViewHelpers.csrf_meta_tags()".to_string()),
        CspMetaTag => Some("buf = buf <> ViewHelpers.csp_meta_tag()".to_string()),
        JavascriptImportmapTags => Some(
            "buf = buf <> ViewHelpers.javascript_importmap_tags(Importmap.pins(), \"application\")"
                .to_string(),
        ),
        TurboStreamFrom { channel } => {
            if !is_ex_simple_expr(channel, ctx) {
                return None;
            }
            let arg = emit_ex_view_expr_raw(channel, ctx);
            Some(format!("buf = buf <> ViewHelpers.turbo_stream_from({arg})"))
        }
        DomId { record, prefix } => {
            let (singular, id_expr) = ex_resolve_dom_id_record(record, ctx)?;
            match prefix {
                None => Some(format!(
                    "buf = buf <> ViewHelpers.dom_id({singular:?}, {id_expr})"
                )),
                Some(p) => {
                    let prefix_str = match &*p.node {
                        ExprNode::Lit { value: Literal::Sym { value } } => {
                            format!("{:?}", value.as_str())
                        }
                        ExprNode::Lit { value: Literal::Str { value } } => format!("{value:?}"),
                        _ if is_ex_simple_expr(p, ctx) => emit_ex_view_expr_raw(p, ctx),
                        _ => return None,
                    };
                    Some(format!(
                        "buf = buf <> ViewHelpers.dom_id({singular:?}, {id_expr}, {prefix_str})"
                    ))
                }
            }
        }
        Pluralize { count, word } => {
            if !is_ex_simple_expr(count, ctx) || !is_ex_simple_expr(word, ctx) {
                return None;
            }
            let c = emit_ex_view_expr_raw(count, ctx);
            let w = emit_ex_view_expr_raw(word, ctx);
            Some(format!("buf = buf <> ViewHelpers.pluralize({c}, {w})"))
        }
        Truncate { text, opts } => {
            if !is_ex_simple_expr(text, ctx) {
                return None;
            }
            let t = emit_ex_view_expr_raw(text, ctx);
            let opts_code = ex_opts_from_expr(opts.as_deref(), ctx);
            Some(format!("buf = buf <> ViewHelpers.truncate({t}, {opts_code})"))
        }
        StylesheetLinkTag { name, opts } => {
            let opts_code = ex_opts_from_expr(opts.as_deref(), ctx);
            if let ExprNode::Lit { value: Literal::Sym { value } } = &*name.node {
                if value.as_str() == "app" && !ctx.stylesheets.is_empty() {
                    let lines: Vec<String> = ctx
                        .stylesheets
                        .iter()
                        .map(|n| {
                            format!("buf = buf <> ViewHelpers.stylesheet_link_tag({n:?}, {opts_code})")
                        })
                        .collect();
                    return Some(lines.join("\nbuf = buf <> \"\\n\"\n"));
                }
            }
            let name_expr = match &*name.node {
                ExprNode::Lit { value: Literal::Sym { value } } => format!("{:?}", value.as_str()),
                ExprNode::Lit { value: Literal::Str { value } } => format!("{value:?}"),
                _ => return None,
            };
            Some(format!(
                "buf = buf <> ViewHelpers.stylesheet_link_tag({name_expr}, {opts_code})"
            ))
        }
        ContentForGetter { slot } => Some(format!(
            "buf = buf <> ViewHelpers.content_for_get({slot:?})"
        )),
        ContentForSetter { .. } => None,
        LinkTo { text, url, opts } => {
            emit_ex_link_or_button("link_to", text, url, *opts, ctx)
                .map(|call| format!("buf = buf <> {call}"))
        }
        ButtonTo { text, target, opts } => {
            emit_ex_link_or_button("button_to", text, target, *opts, ctx)
                .map(|call| format!("buf = buf <> {call}"))
        }
    }
}

fn ex_resolve_dom_id_record(record: &Expr, ctx: &ExViewCtx) -> Option<(String, String)> {
    let name = match &*record.node {
        ExprNode::Var { name, .. } | ExprNode::Ivar { name } if ctx.is_local(name.as_str()) => {
            name.as_str().to_string()
        }
        ExprNode::Send {
            recv: None,
            method,
            args,
            block: None,
            ..
        } if args.is_empty() && ctx.is_local(method.as_str()) => method.as_str().to_string(),
        _ => return None,
    };
    let singular = crate::naming::singularize(&name);
    Some((singular, format!("{name}.id")))
}

fn emit_ex_link_or_button(
    helper: &str,
    text: &Expr,
    url: &Expr,
    opts: Option<&Expr>,
    ctx: &ExViewCtx,
) -> Option<String> {
    if !is_ex_simple_expr(text, ctx) {
        return None;
    }
    let text_raw = emit_ex_view_expr_raw(text, ctx);
    let text_expr = match &*text.node {
        ExprNode::Lit { value: Literal::Str { .. } } => text_raw,
        _ => format!("to_string({text_raw})"),
    };
    let is_local = |n: &str| ctx.is_local(n);
    let url_kind = crate::lower::classify_view_url_arg(url, &is_local)?;
    let url_expr = match url_kind {
        crate::lower::ViewUrlArg::Literal { value } => format!("{value:?}"),
        crate::lower::ViewUrlArg::PathHelper { name, args } => {
            let args_s: Vec<String> = args.iter().map(|a| ex_path_arg(a, ctx)).collect();
            if args_s.is_empty() {
                format!("RouteHelpers.{name}()")
            } else {
                format!("RouteHelpers.{name}({})", args_s.join(", "))
            }
        }
        crate::lower::ViewUrlArg::RecordRef { name } => {
            format!(
                "RouteHelpers.{}_path({name}.id)",
                crate::naming::singularize(name),
            )
        }
        crate::lower::ViewUrlArg::NestedArray { elements } => ex_emit_nested_path(elements, ctx)?,
    };
    let opts_code = ex_opts_from_expr(opts, ctx);
    Some(format!("ViewHelpers.{helper}({text_expr}, {url_expr}, {opts_code})"))
}

fn ex_path_arg(arg: &Expr, ctx: &ExViewCtx) -> String {
    match &*arg.node {
        ExprNode::Var { name, .. } | ExprNode::Ivar { name } if ctx.is_local(name.as_str()) => {
            format!("{}.id", name.as_str())
        }
        ExprNode::Send { recv: None, method, args, block: None, .. }
            if args.is_empty() && ctx.is_local(method.as_str()) =>
        {
            format!("{}.id", method.as_str())
        }
        _ => emit_ex_view_expr_raw(arg, ctx),
    }
}

fn ex_emit_nested_path(elements: &[Expr], ctx: &ExViewCtx) -> Option<String> {
    let is_local = |n: &str| ctx.is_local(n);
    let mut singulars: Vec<String> = Vec::new();
    let mut args: Vec<String> = Vec::new();
    for el in elements {
        let kind = crate::lower::classify_nested_url_element(el, &is_local)?;
        let (singular, id_expr) = ex_nested_element_parts(&kind);
        singulars.push(singular);
        args.push(id_expr);
    }
    let name = format!("{}_path", singulars.join("_"));
    Some(format!("RouteHelpers.{name}({})", args.join(", ")))
}

fn ex_opts_from_expr(opts: Option<&Expr>, ctx: &ExViewCtx) -> String {
    match opts.map(|e| &*e.node) {
        Some(ExprNode::Hash { entries, .. }) => ex_hash_to_map(entries, ctx),
        _ => "%{}".to_string(),
    }
}

fn ex_hash_to_map(entries: &[(Expr, Expr)], ctx: &ExViewCtx) -> String {
    let mut items: Vec<(String, String)> = Vec::new();
    for (k, v) in entries {
        let key = match &*k.node {
            ExprNode::Lit { value: Literal::Sym { value } } => value.as_str().to_string(),
            ExprNode::Lit { value: Literal::Str { value } } => value.clone(),
            _ => continue,
        };
        if key == "data" {
            if let ExprNode::Hash { entries: de, .. } = &*v.node {
                for (dk, dv) in de {
                    let dk_str = match &*dk.node {
                        ExprNode::Lit { value: Literal::Sym { value } } => {
                            value.as_str().replace('_', "-")
                        }
                        ExprNode::Lit { value: Literal::Str { value } } => {
                            value.replace('_', "-")
                        }
                        _ => continue,
                    };
                    let dv_s = ex_opt_value(dv, ctx);
                    items.push((format!("data-{dk_str}"), dv_s));
                }
                continue;
            }
        }
        let val = if key == "class" {
            ex_class_value(v, ctx)
        } else {
            ex_opt_value(v, ctx)
        };
        items.push((key, val));
    }
    if items.is_empty() {
        return "%{}".to_string();
    }
    let parts: Vec<String> = items
        .into_iter()
        .map(|(k, v)| format!("{k:?} => {v}"))
        .collect();
    format!("%{{{}}}", parts.join(", "))
}

fn ex_opt_value(v: &Expr, ctx: &ExViewCtx) -> String {
    match &*v.node {
        ExprNode::Lit { value: Literal::Str { value } } => format!("{value:?}"),
        ExprNode::Lit { value: Literal::Int { value, .. } } => format!("\"{value}\""),
        ExprNode::Lit { value: Literal::Sym { value } } => format!("{:?}", value.as_str()),
        ExprNode::Array { elements, .. } => match elements.first() {
            Some(first) => match &*first.node {
                ExprNode::Lit { value: Literal::Str { value } } => format!("{value:?}"),
                _ => "\"\"".to_string(),
            },
            None => "\"\"".to_string(),
        },
        _ if is_ex_simple_expr(v, ctx) => {
            let raw = emit_ex_view_expr_raw(v, ctx);
            match &*v.node {
                ExprNode::Lit { .. } => raw,
                _ => format!("to_string({raw})"),
            }
        }
        _ => "\"\"".to_string(),
    }
}

fn ex_class_value(v: &Expr, ctx: &ExViewCtx) -> String {
    let is_local = |n: &str| ctx.is_local(n);
    let simple_as_ex = |e: &Expr| -> Option<String> {
        if is_ex_simple_expr(e, ctx) {
            Some(match &*e.node {
                ExprNode::Lit { value: Literal::Str { value } } => format!("{value:?}"),
                _ => {
                    let raw = emit_ex_view_expr_raw(e, ctx);
                    match &*e.node {
                        ExprNode::Lit { .. } => raw,
                        _ => format!("to_string({raw})"),
                    }
                }
            })
        } else {
            None
        }
    };
    match crate::lower::classify_class_value(v, &is_local) {
        crate::lower::ClassValueShape::Simple { expr } => {
            simple_as_ex(expr).unwrap_or_else(|| "\"\"".to_string())
        }
        crate::lower::ClassValueShape::Conditional { base, clauses } => {
            let Some(base_ex) = simple_as_ex(base) else {
                return "\"\"".to_string();
            };
            if clauses.is_empty() {
                return base_ex;
            }
            let extras: Vec<String> = clauses
                .iter()
                .map(|(cls_text, pred)| {
                    let cond = ex_render_errors_field_predicate(pred);
                    format!(
                        " <> (if {cond}, do: \" {cls_text}\", else: \"\")"
                    )
                })
                .collect();
            format!("({base_ex}{})", extras.join(""))
        }
        crate::lower::ClassValueShape::Unknown => "\"\"".to_string(),
    }
}

fn ex_render_errors_field_predicate(pred: &crate::lower::ErrorsFieldPredicate<'_>) -> String {
    let call = format!(
        "ViewHelpers.field_has_error({}.errors, {:?})",
        pred.record, pred.field,
    );
    if pred.expect_present {
        call
    } else {
        format!("not {call}")
    }
}

fn emit_ex_form_builder_call(
    recv: &str,
    kind: crate::lower::FormBuilderMethod,
    args: &[Expr],
    ctx: &ExViewCtx,
) -> Option<String> {
    use crate::lower::FormBuilderMethod::*;
    let (field, opts_entries) = crate::lower::classify_form_builder_args(args);
    let opts = opts_entries
        .map(|entries| ex_hash_to_map(entries, ctx))
        .unwrap_or_else(|| "%{}".to_string());
    match kind {
        Label => {
            let field = field?;
            Some(format!("ViewHelpers.fb_label({recv}, {field:?}, {opts})"))
        }
        TextField | TextArea => {
            let ex_method = if matches!(kind, TextField) { "fb_text_field" } else { "fb_textarea" };
            let field = field?;
            let field_s = field.to_string();
            let value_expr = ctx
                .form_records
                .iter()
                .find(|(name, _)| name == recv)
                .and_then(|(_, record)| {
                    if ctx.local_has_attr(record, &field_s) {
                        Some(format!("{record}.{field_s}"))
                    } else {
                        None
                    }
                })
                .unwrap_or_else(|| "\"\"".to_string());
            Some(format!(
                "ViewHelpers.{ex_method}({recv}, {field:?}, {value_expr}, {opts})"
            ))
        }
        Submit => {
            let label_str = args.iter().find_map(|a| match &*a.node {
                ExprNode::Lit { value: Literal::Str { value } } => Some(value.clone()),
                _ => None,
            });
            let opts_expr = if let Some(lbl) = label_str {
                format!("Map.put({opts}, \"label\", {lbl:?})")
            } else {
                opts
            };
            Some(format!("ViewHelpers.fb_submit({recv}, {opts_expr})"))
        }
    }
}

fn emit_ex_render_partial(
    rp: &crate::lower::RenderPartial<'_>,
    ctx: &ExViewCtx,
) -> String {
    use crate::lower::RenderPartial;
    match rp {
        RenderPartial::Collection { name, .. } => {
            let singular = crate::naming::singularize(name);
            let partial_fn = format!("render_{name}_{singular}");
            format!(
                "buf = buf <> Enum.map_join({name}, \"\", fn r -> {partial_fn}(r) end)"
            )
        }
        RenderPartial::Association { receiver, method } => {
            let singular = crate::naming::singularize(method);
            let partial_fn = format!("render_{method}_{singular}");
            let parent_name = match &*receiver.node {
                ExprNode::Var { name, .. } | ExprNode::Ivar { name } => name.to_string(),
                _ => return "buf = buf <> \"\" # TODO ERB: render".to_string(),
            };
            let parent_class = crate::naming::singularize_camelize(&parent_name);
            format!(
                "buf = buf <> Enum.map_join({parent_class}.{method}({parent_name}), \"\", fn c -> {partial_fn}(c) end)"
            )
        }
        RenderPartial::Named { partial, arg } => {
            let partial_fn = format!(
                "render_{}_{}",
                ctx.resource_dir,
                partial.trim_start_matches('_'),
            );
            match arg {
                Some(v) if is_ex_simple_expr(v, ctx) => {
                    let arg_expr = emit_ex_view_expr_raw(v, ctx);
                    format!("buf = buf <> {partial_fn}({arg_expr})")
                }
                _ => format!("buf = buf <> {partial_fn}(nil)"),
            }
        }
    }
}

fn ex_extract_kwarg<'a>(arg: &'a Expr, key: &str) -> Option<&'a Expr> {
    if let ExprNode::Hash { entries, .. } = &*arg.node {
        for (k, v) in entries {
            if let ExprNode::Lit { value: Literal::Sym { value } } = &*k.node {
                if value.as_str() == key {
                    return Some(v);
                }
            }
        }
    }
    None
}

fn ex_text_references(text: &str, ident: &str) -> bool {
    let bytes = text.as_bytes();
    let needle = ident.as_bytes();
    let mut i = 0;
    while i + needle.len() <= bytes.len() {
        if &bytes[i..i + needle.len()] == needle {
            let prev_is_word = i > 0
                && (bytes[i - 1].is_ascii_alphanumeric() || bytes[i - 1] == b'_');
            let next_idx = i + needle.len();
            let next_is_word = next_idx < bytes.len()
                && (bytes[next_idx].is_ascii_alphanumeric()
                    || bytes[next_idx] == b'_');
            if !prev_is_word && !next_is_word {
                return true;
            }
        }
        i += 1;
    }
    false
}

fn unwrap_to_s_ex(expr: &Expr) -> &Expr {
    if let ExprNode::Send { recv: Some(inner), method, args, .. } = &*expr.node {
        if method.as_str() == "to_s" && args.is_empty() {
            return inner;
        }
    }
    expr
}

fn ex_string_literal(s: &str) -> String {
    format!("{s:?}")
}

fn is_ex_simple_expr(expr: &Expr, ctx: &ExViewCtx) -> bool {
    match &*expr.node {
        ExprNode::Lit { .. } => true,
        ExprNode::Var { name, .. } | ExprNode::Ivar { name } => {
            ctx.is_local(name.as_str())
        }
        // Partial-scope local parsed as bare Send.
        ExprNode::Send { recv: None, method, args, block: None, .. }
            if args.is_empty() && ctx.is_local(method.as_str()) =>
        {
            true
        }
        ExprNode::Send { recv: Some(r), method, args, block, .. } => {
            if !args.is_empty() || block.is_some() {
                return false;
            }
            let clean = method.as_str().trim_end_matches('?').trim_end_matches('!');
            if clean.is_empty() {
                return false;
            }
            let recv_local = match &*r.node {
                ExprNode::Var { name, .. } | ExprNode::Ivar { name } => Some(name.as_str()),
                ExprNode::Send {
                    recv: None,
                    method: m,
                    args: ra,
                    block: None,
                    ..
                } if ra.is_empty() && ctx.is_local(m.as_str()) => Some(m.as_str()),
                _ => None,
            };
            if let Some(local_name) = recv_local {
                if ctx.local_has_attr(local_name, clean) {
                    return true;
                }
                if ctx.is_local(local_name)
                    && matches!(
                        method.as_str(),
                        "any?" | "none?" | "present?" | "empty?"
                    )
                {
                    return true;
                }
                if ctx
                    .resolve_has_many_on_local(local_name, method.as_str())
                    .is_some()
                {
                    return true;
                }
            }
            if is_ex_simple_expr(r, ctx) {
                return true;
            }
            false
        }
        ExprNode::StringInterp { parts } => parts.iter().all(|p| match p {
            crate::expr::InterpPart::Text { .. } => true,
            crate::expr::InterpPart::Expr { expr } => is_ex_simple_expr(expr, ctx),
        }),
        _ => false,
    }
}

fn emit_ex_view_expr_raw(expr: &Expr, ctx: &ExViewCtx) -> String {
    match &*expr.node {
        ExprNode::Lit { value } => emit_literal(value),
        ExprNode::Var { name, .. } | ExprNode::Ivar { name } => name.to_string(),
        ExprNode::Send { recv, method, args, .. } => {
            let method_s = method.as_str();
            // Bare local ref (partial scope).
            if recv.is_none() && args.is_empty() && ctx.is_local(method_s) {
                return method_s.to_string();
            }
            if let Some(r) = recv {
                if args.is_empty() {
                    // has_many association read → inline filter.
                    // `Enum.filter(Comment.all(), fn c -> c.article_id == article.id end)`.
                    let owner_local = match &*r.node {
                        ExprNode::Var { name, .. } | ExprNode::Ivar { name }
                            if ctx.is_local(name.as_str()) =>
                        {
                            Some(name.as_str().to_string())
                        }
                        ExprNode::Send {
                            recv: None,
                            method: m,
                            args: ra,
                            block: None,
                            ..
                        } if ra.is_empty() && ctx.is_local(m.as_str()) => {
                            Some(m.as_str().to_string())
                        }
                        _ => None,
                    };
                    if let Some(owner) = &owner_local {
                        if let Some((target_class, fk)) =
                            ctx.resolve_has_many_on_local(owner, method_s)
                        {
                            return format!(
                                "Enum.filter({target_class}.all(), fn r -> r.{fk} == {owner}.id end)"
                            );
                        }
                    }
                    // Collection predicates / size on any recv.
                    match method_s {
                        "any?" | "present?" => {
                            let recv_s = emit_ex_view_expr_raw(r, ctx);
                            return format!("(length({recv_s}) > 0)");
                        }
                        "none?" | "empty?" => {
                            let recv_s = emit_ex_view_expr_raw(r, ctx);
                            return format!("(length({recv_s}) == 0)");
                        }
                        "size" | "count" | "length" => {
                            let recv_s = emit_ex_view_expr_raw(r, ctx);
                            return format!("length({recv_s})");
                        }
                        "full_message" => {
                            let recv_s = emit_ex_view_expr_raw(r, ctx);
                            return format!("{recv_s}.full_message");
                        }
                        _ => {}
                    }
                }
                let recv_s = emit_ex_view_expr_raw(r, ctx);
                let clean = method_s.trim_end_matches('?').trim_end_matches('!');
                if args.is_empty() {
                    return format!("{recv_s}.{clean}");
                }
                let args_s: Vec<String> = args
                    .iter()
                    .map(|a| emit_ex_view_expr_raw(a, ctx))
                    .collect();
                return format!("{recv_s}.{clean}({})", args_s.join(", "));
            }
            // Bare fn call (no recv) — assume helper.
            let args_s: Vec<String> =
                args.iter().map(|a| emit_ex_view_expr_raw(a, ctx)).collect();
            if args.is_empty() {
                format!("ViewHelpers.{method_s}()")
            } else {
                format!("ViewHelpers.{method_s}({})", args_s.join(", "))
            }
        }
        ExprNode::StringInterp { parts } => {
            use crate::expr::InterpPart;
            let mut out = String::from("\"");
            for p in parts {
                match p {
                    InterpPart::Text { value } => {
                        for c in value.chars() {
                            match c {
                                '"' => out.push_str("\\\""),
                                '\\' => out.push_str("\\\\"),
                                '\n' => out.push_str("\\n"),
                                other => out.push(other),
                            }
                        }
                    }
                    InterpPart::Expr { expr } => {
                        out.push_str("#{");
                        out.push_str(&emit_ex_view_expr_raw(expr, ctx));
                        out.push('}');
                    }
                }
            }
            out.push('"');
            out
        }
        _ => "\"\"".to_string(),
    }
}

fn ex_collect_ivar_names(expr: &Expr) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    ex_collect_ivars_into(expr, &mut out);
    out
}

fn ex_collect_ivars_into(expr: &Expr, out: &mut Vec<String>) {
    match &*expr.node {
        ExprNode::Ivar { name } => {
            let n = name.to_string();
            if !out.iter().any(|existing| existing == &n) {
                out.push(n);
            }
        }
        ExprNode::Assign { target, value } => {
            if let LValue::Ivar { name } = target {
                let n = name.to_string();
                if !out.iter().any(|existing| existing == &n) {
                    out.push(n);
                }
            }
            ex_collect_ivars_into(value, out);
        }
        ExprNode::Send { recv, args, block, .. } => {
            if let Some(r) = recv {
                ex_collect_ivars_into(r, out);
            }
            for a in args {
                ex_collect_ivars_into(a, out);
            }
            if let Some(b) = block {
                ex_collect_ivars_into(b, out);
            }
        }
        ExprNode::Seq { exprs } | ExprNode::Array { elements: exprs, .. } => {
            for e in exprs {
                ex_collect_ivars_into(e, out);
            }
        }
        ExprNode::Hash { entries, .. } => {
            for (k, v) in entries {
                ex_collect_ivars_into(k, out);
                ex_collect_ivars_into(v, out);
            }
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            ex_collect_ivars_into(cond, out);
            ex_collect_ivars_into(then_branch, out);
            ex_collect_ivars_into(else_branch, out);
        }
        ExprNode::BoolOp { left, right, .. } => {
            ex_collect_ivars_into(left, out);
            ex_collect_ivars_into(right, out);
        }
        ExprNode::Lambda { body, .. } => ex_collect_ivars_into(body, out),
        ExprNode::StringInterp { parts } => {
            for p in parts {
                if let crate::expr::InterpPart::Expr { expr } = p {
                    ex_collect_ivars_into(expr, out);
                }
            }
        }
        _ => {}
    }
}
