//! Elixir test emit (W7).
//!
//! Emits the ExUnit test tree: the hand-written `TestClient` /
//! `TestResponse` runtime, fixtures (`Fixtures` + per-resource loaders),
//! and one module per test file under `test/`.
//!
//! Test bodies are emitted via the shared `crate::lower::classify_*`
//! helpers; the emitted modules reference the app/runtime modules by their
//! bare top-level names (`TestClient`, `Article`, `Fixtures`, …), which
//! resolve directly, and `import RouteHelpers` for bareword `*_path()`
//! calls. `RoutesTable` is static (a function, not a registered table), so
//! no route registration is needed in `setup`.
//!
//! Model tests destructure the model's dual-return `save`
//! (`assert_not record.save` → `{_saved, ok} = ….save(rec); refute ok`),
//! since `save` returns `{record, bool}`; the assoc `.create` helper does
//! the same. Other model calls (`count`/`last`/`destroy`/`find`) aren't
//! dual.

use std::fmt::Write;
use std::path::PathBuf;

use super::super::EmittedFile;
use crate::app::App;
use crate::dialect::{Test, TestModule};
use crate::expr::{Expr, ExprNode, LValue, Literal};
use crate::ident::Symbol;
use crate::naming::{camelize, pluralize_snake, snake_case};

/// The hand-written v2 test-support runtime (`TestClient` /
/// `TestResponse`), shipped as `test/support/test_support.ex`.
const TEST_SUPPORT_SOURCE: &str = include_str!("../../../runtime/elixir/v2/test_support.ex");

/// Emit the full v2 test tree for `app`: the test-support runtime, v2
/// fixtures, and one module per `*ControllerTest`. Returns empty when
/// there are no test modules.
pub(super) fn emit_test_files(app: &App) -> Vec<EmittedFile> {
    let mut out = Vec::new();
    if app.test_modules.is_empty() {
        return out;
    }

    out.push(EmittedFile {
        path: PathBuf::from("test/support/test_support.ex"),
        content: TEST_SUPPORT_SOURCE.to_string(),
    });

    // v2 fixtures (gated on the app actually having fixtures — the
    // controller tests' setup loads them).
    if !app.fixtures.is_empty() {
        let lowered = crate::lower::lower_fixtures(app);
        out.push(emit_fixtures_helper(&lowered, app));
        for f in &lowered.fixtures {
            out.push(emit_fixture(f));
        }
    }

    // One module per test file: controller tests drive TestClient,
    // model tests exercise the V2 model modules directly.
    for tm in &app.test_modules {
        if tm.name.0.as_str().ends_with("ControllerTest") {
            out.push(emit_controller_test(tm, app));
        } else {
            out.push(emit_model_test(tm, app));
        }
    }
    out
}

/// Concrete model names (those with a schema table — abstract bases like
/// `ApplicationRecord` emit no module). Used by the model-test emitter to
/// recognize `Class.new(...)` / `Class.save(...)` receivers.
fn known_models(app: &App) -> Vec<Symbol> {
    app.models
        .iter()
        .filter(|m| app.schema.tables.contains_key(&m.table.0))
        .map(|m| m.name.0.clone())
        .collect()
}

// ---- fixtures ---------------------------------------------------------

/// `test/support/fixtures/<name>.ex` — one `Fixtures.<Ns>` module
/// per fixture set. Mirrors `src/emit/elixir/fixture.rs`, retargeted to
/// `*` and the model's dual-return `save` (`{record, _} = …`); the
/// saved record carries its assigned id, so `register` uses `record.id`
/// rather than `Roundhouse.Db.last_insert_rowid()`.
fn emit_fixture(lowered: &crate::lower::LoweredFixture) -> EmittedFile {
    let fixture_name = lowered.name.as_str();
    let class_name = lowered.class.0.as_str();
    let ns = camelize(fixture_name);

    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse (elixir2).").unwrap();
    writeln!(s, "defmodule Fixtures.{ns} do").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "  def _load_all do").unwrap();
    for record in &lowered.records {
        let label = record.label.as_str();
        let mut field_lines: Vec<String> = Vec::new();
        for field in &record.fields {
            let col = field.column.as_str();
            let val = match &field.value {
                crate::lower::LoweredFixtureValue::Literal { ty, raw } => ex_literal_for(raw, ty),
                crate::lower::LoweredFixtureValue::FkLookup {
                    target_fixture,
                    target_label,
                } => format!(
                    "Fixtures.fixture_id({:?}, {:?})",
                    target_fixture.as_str(),
                    target_label.as_str(),
                ),
            };
            field_lines.push(format!("      {col}: {val}"));
        }
        writeln!(s, "    record = %{class_name}{{").unwrap();
        for (idx, line) in field_lines.iter().enumerate() {
            if idx < field_lines.len() - 1 {
                writeln!(s, "{line},").unwrap();
            } else {
                writeln!(s, "{line}").unwrap();
            }
        }
        writeln!(s, "    }}").unwrap();
        writeln!(s, "    {{record, ok}} = {class_name}.save(record)").unwrap();
        writeln!(
            s,
            "    unless ok, do: raise \"fixture {fixture_name}/{label} failed to save\""
        )
        .unwrap();
        writeln!(s, "    Fixtures.register({fixture_name:?}, {label:?}, record.id)").unwrap();
    }
    writeln!(s, "    :ok").unwrap();
    writeln!(s, "  end").unwrap();

    for record in &lowered.records {
        let label = record.label.as_str();
        writeln!(s).unwrap();
        writeln!(s, "  def {label}() do").unwrap();
        writeln!(s, "    id = Fixtures.fixture_id({fixture_name:?}, {label:?})").unwrap();
        writeln!(s, "    {class_name}.find(id)").unwrap();
        writeln!(s, "  end").unwrap();
    }

    writeln!(s, "end").unwrap();

    EmittedFile {
        path: PathBuf::from(format!("test/support/fixtures/{fixture_name}.ex")),
        content: s,
    }
}

/// `test/support/fixtures.ex` — shared `Fixtures` module (setup,
/// fixture_id lookup, register). Reuses the shared `Roundhouse.Db` /
/// `Roundhouse.SchemaSQL` runtime during the strangler phase.
fn emit_fixtures_helper(lowered: &crate::lower::LoweredFixtureSet, _app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse (elixir2).").unwrap();
    writeln!(s, "defmodule Fixtures do").unwrap();
    writeln!(s, "  @moduledoc false").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "  @doc \"Per-test setup. Called from each test module's ExUnit setup.\"").unwrap();
    writeln!(s, "  def setup do").unwrap();
    writeln!(s, "    Roundhouse.Db.setup_test_db(Roundhouse.SchemaSQL.create_tables())").unwrap();
    writeln!(s, "    Process.put(:roundhouse_fixture_ids, %{{}})").unwrap();
    for f in &lowered.fixtures {
        let ns = camelize(f.name.as_str());
        writeln!(s, "    Fixtures.{ns}._load_all()").unwrap();
    }
    writeln!(s, "    :ok").unwrap();
    writeln!(s, "  end").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "  def register(fixture, label, id) do").unwrap();
    writeln!(s, "    ids = Process.get(:roundhouse_fixture_ids, %{{}})").unwrap();
    writeln!(
        s,
        "    Process.put(:roundhouse_fixture_ids, Map.put(ids, {{fixture, label}}, id))"
    )
    .unwrap();
    writeln!(s, "  end").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "  def fixture_id(fixture, label) do").unwrap();
    writeln!(
        s,
        "    case Map.get(Process.get(:roundhouse_fixture_ids, %{{}}), {{fixture, label}}) do"
    )
    .unwrap();
    writeln!(s, "      nil -> raise \"fixture #{{fixture}}/#{{label}} not loaded\"").unwrap();
    writeln!(s, "      id -> id").unwrap();
    writeln!(s, "    end").unwrap();
    writeln!(s, "  end").unwrap();
    writeln!(s, "end").unwrap();
    EmittedFile {
        path: PathBuf::from("test/support/fixtures.ex"),
        content: s,
    }
}

fn ex_literal_for(value: &str, ty: &crate::ty::Ty) -> String {
    use crate::ty::Ty;
    match ty {
        Ty::Str | Ty::Sym => format!("{value:?}"),
        Ty::Int if value.parse::<i64>().is_ok() => value.to_string(),
        Ty::Float if value.parse::<f64>().is_ok() => value.to_string(),
        Ty::Bool => match value {
            "true" | "1" => "true".into(),
            "false" | "0" => "false".into(),
            _ => format!("false # TODO: coerce {value:?}"),
        },
        _ => format!("{value:?}"),
    }
}

// ---- controller tests -------------------------------------------------

#[derive(Clone, Copy)]
struct ExTestCtx<'a> {
    app: &'a App,
    fixture_names: &'a [Symbol],
    known_models: &'a [Symbol],
}

/// `test/<name>.exs` — one ExUnit module per controller test. Distinct
/// module name (`<Name>ControllerTest`) and path from the v1 tree, so
/// both run under `mix test` during the strangler phase.
fn emit_controller_test(tm: &TestModule, app: &App) -> EmittedFile {
    let fixture_names: Vec<Symbol> = app.fixtures.iter().map(|f| f.name.clone()).collect();
    let known_models = known_models(app);
    let ctx = ExTestCtx {
        app,
        fixture_names: &fixture_names,
        known_models: &known_models,
    };

    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse (elixir2).").unwrap();
    writeln!(s, "defmodule {} do", tm.name.0).unwrap();
    writeln!(s, "  use ExUnit.Case").unwrap();
    // Bare module names (TestClient, TestResponse, Fixtures, the model
    // modules) resolve to the top-level modules directly — no aliases
    // needed. Route helpers are bareword calls (`articles_path()`), so
    // import them.
    writeln!(s, "  import RouteHelpers").unwrap();

    if !app.fixtures.is_empty() {
        writeln!(s).unwrap();
        writeln!(s, "  setup do").unwrap();
        writeln!(s, "    Fixtures.setup()").unwrap();
        writeln!(s, "    :ok").unwrap();
        writeln!(s, "  end").unwrap();
    }

    for test in &tm.tests {
        writeln!(s).unwrap();
        writeln!(s, "  test {:?} do", test.name).unwrap();
        let body = emit_controller_test_body(test, app, ctx);
        if body.trim().is_empty() {
            writeln!(s, "    :ok").unwrap();
        } else {
            for line in body.lines() {
                if line.is_empty() {
                    s.push('\n');
                } else {
                    writeln!(s, "    {line}").unwrap();
                }
            }
        }
        writeln!(s, "  end").unwrap();
    }
    writeln!(s, "end").unwrap();

    let filename = snake_case(tm.name.0.as_str());
    EmittedFile {
        path: PathBuf::from(format!("test/{filename}.exs")),
        content: s,
    }
}

fn emit_controller_test_body(test: &Test, app: &App, ctx: ExTestCtx) -> String {
    let mut out = String::new();
    // Prime ivars read without assignment: `@article` → `article =
    // Fixtures.Articles.one()`.
    let walked = crate::lower::walk_controller_ivars(&test.body);
    for ivar in walked.ivars_read_without_assign() {
        let plural = pluralize_snake(ivar.as_str());
        if ctx.fixture_names.iter().any(|s| s.as_str() == plural) {
            let ns = camelize(&plural);
            out.push_str(&format!("{} = Fixtures.{}.one()\n", ivar.as_str(), ns));
        }
    }

    for stmt in crate::lower::test_body_stmts(&test.body) {
        out.push_str(&emit_ctrl_test_stmt(stmt, app, ctx));
        out.push('\n');
    }
    out
}

fn emit_ctrl_test_stmt(stmt: &Expr, app: &App, ctx: ExTestCtx) -> String {
    match &*stmt.node {
        ExprNode::Send { recv: None, method, args, block, .. } => {
            emit_ctrl_test_send(method.as_str(), args, block.as_ref(), app, ctx)
        }
        ExprNode::Send { recv: Some(r), method, args, .. } => {
            if method.as_str() == "reload" {
                let recv_s = match &*r.node {
                    ExprNode::Ivar { name } | ExprNode::Var { name, .. } => name.to_string(),
                    _ => emit_ctrl_test_expr(r, app, ctx),
                };
                let module = match &*r.node {
                    ExprNode::Ivar { name } | ExprNode::Var { name, .. } => {
                        camelize(name.as_str())
                    }
                    _ => "Unknown".to_string(),
                };
                return format!("{recv_s} = {module}.reload({recv_s})");
            }
            let recv_s = emit_ctrl_test_expr(r, app, ctx);
            let args_s: Vec<String> =
                args.iter().map(|a| emit_ctrl_test_expr(a, app, ctx)).collect();
            if args_s.is_empty() {
                format!("{recv_s}.{}", method.as_str())
            } else {
                format!("{recv_s}.{}({})", method.as_str(), args_s.join(", "))
            }
        }
        ExprNode::Assign { target: LValue::Var { name, .. }, value }
        | ExprNode::Assign { target: LValue::Ivar { name }, value } => {
            format!("{name} = {}", emit_ctrl_test_expr(value, app, ctx))
        }
        _ => emit_ctrl_test_expr(stmt, app, ctx),
    }
}

fn emit_ctrl_test_send(
    method: &str,
    args: &[Expr],
    block: Option<&Expr>,
    app: &App,
    ctx: ExTestCtx,
) -> String {
    use crate::lower::ControllerTestSend;
    match crate::lower::classify_controller_test_send(method, args, block) {
        Some(ControllerTestSend::HttpGet { url }) => {
            format!("resp = TestClient.get({})", emit_url_expr(url, app, ctx))
        }
        Some(ControllerTestSend::HttpWrite { method: m, url, params }) => {
            let u = emit_url_expr(url, app, ctx);
            let body = params
                .map(|h| flatten_params_to_form(h, None, app, ctx))
                .unwrap_or_else(|| "%{}".to_string());
            format!("resp = TestClient.{m}({u}, {body})")
        }
        Some(ControllerTestSend::HttpDelete { url }) => {
            format!("resp = TestClient.delete({})", emit_url_expr(url, app, ctx))
        }
        Some(ControllerTestSend::AssertResponse { sym }) => match sym.as_str() {
            "success" => "TestResponse.assert_ok(resp)".to_string(),
            "unprocessable_entity" | "unprocessable_content" => {
                "TestResponse.assert_unprocessable(resp)".to_string()
            }
            other => format!("TestResponse.assert_status(resp, 200) # TODO: {other:?}"),
        },
        Some(ControllerTestSend::AssertRedirectedTo { url }) => {
            format!("TestResponse.assert_redirected_to(resp, {})", emit_url_expr(url, app, ctx))
        }
        Some(ControllerTestSend::AssertSelect { selector, kind }) => {
            emit_assert_select(selector, kind, app, ctx)
        }
        Some(ControllerTestSend::AssertDifference { method: _, count_expr, delta, block }) => {
            emit_assert_difference(count_expr, delta, block, app, ctx)
        }
        Some(ControllerTestSend::AssertEqual { expected, actual }) => {
            let e = emit_ctrl_test_expr(expected, app, ctx);
            let a = emit_ctrl_test_expr(actual, app, ctx);
            format!("assert {a} == {e}")
        }
        None => {
            let args_s: Vec<String> =
                args.iter().map(|a| emit_ctrl_test_expr(a, app, ctx)).collect();
            if args_s.is_empty() {
                method.to_string()
            } else {
                format!("{method}({})", args_s.join(", "))
            }
        }
    }
}

fn emit_url_expr(expr: &Expr, app: &App, ctx: ExTestCtx) -> String {
    use crate::lower::UrlArg;
    let Some(helper) = crate::lower::classify_url_expr(expr) else {
        return emit_ctrl_test_expr(expr, app, ctx);
    };
    let helper_name = format!("{}_path", helper.helper_base);
    let args_s: Vec<String> = helper
        .args
        .iter()
        .map(|a| match a {
            UrlArg::IvarOrVarId(name) => format!("{name}.id"),
            UrlArg::ModelLast(class) => format!("{}.last().id", class.as_str()),
            UrlArg::Raw(e) => emit_ctrl_test_expr(e, app, ctx),
        })
        .collect();
    if args_s.is_empty() {
        format!("{helper_name}()")
    } else {
        format!("{helper_name}({})", args_s.join(", "))
    }
}

fn emit_assert_select(
    selector_expr: &Expr,
    kind: crate::lower::AssertSelectKind<'_>,
    app: &App,
    ctx: ExTestCtx,
) -> String {
    use crate::lower::AssertSelectKind;
    let ExprNode::Lit { value: Literal::Str { value: selector } } = &*selector_expr.node else {
        return format!(
            "TestResponse.assert_select(resp, {}) # TODO: dynamic selector",
            emit_ctrl_test_expr(selector_expr, app, ctx),
        );
    };
    match kind {
        AssertSelectKind::Text(expr) => {
            let text = emit_ctrl_test_expr(expr, app, ctx);
            format!("TestResponse.assert_select_text(resp, {selector:?}, {text})")
        }
        AssertSelectKind::Minimum(expr) => {
            let n = emit_ctrl_test_expr(expr, app, ctx);
            format!("TestResponse.assert_select_min(resp, {selector:?}, {n})")
        }
        AssertSelectKind::SelectorBlock(b) => {
            let mut out = String::new();
            out.push_str(&format!("TestResponse.assert_select(resp, {selector:?})\n"));
            let inner_body = match &*b.node {
                ExprNode::Lambda { body, .. } => body,
                _ => b,
            };
            for stmt in crate::lower::test_body_stmts(inner_body) {
                out.push_str(&emit_ctrl_test_stmt(stmt, app, ctx));
                out.push('\n');
            }
            out.trim_end().to_string()
        }
        AssertSelectKind::SelectorOnly => {
            format!("TestResponse.assert_select(resp, {selector:?})")
        }
    }
}

fn emit_assert_difference(
    count_expr_str: String,
    expected_delta: i64,
    block: Option<&Expr>,
    app: &App,
    ctx: ExTestCtx,
) -> String {
    let count_expr = count_expr_str
        .split_once('.')
        .map(|(cls, m)| format!("{cls}.{m}()"))
        .unwrap_or_else(|| count_expr_str.clone());

    let mut out = String::new();
    out.push_str(&format!("count_before = {count_expr}\n"));
    if let Some(b) = block {
        let inner_body = match &*b.node {
            ExprNode::Lambda { body, .. } => body,
            _ => b,
        };
        for stmt in crate::lower::test_body_stmts(inner_body) {
            out.push_str(&emit_ctrl_test_stmt(stmt, app, ctx));
            out.push('\n');
        }
    }
    out.push_str(&format!("count_after = {count_expr}\n"));
    out.push_str(&format!("assert count_after - count_before == {expected_delta}"));
    out
}

fn emit_ctrl_test_expr(expr: &Expr, app: &App, ctx: ExTestCtx) -> String {
    match &*expr.node {
        ExprNode::Lit { value } => emit_lit(value),
        ExprNode::Ivar { name } => name.to_string(),
        ExprNode::Var { name, .. } => name.to_string(),
        ExprNode::Const { path } => {
            path.iter().map(|s| s.to_string()).collect::<Vec<_>>().join(".")
        }
        ExprNode::Send { recv: Some(r), method, args, .. } => {
            let m = method.as_str();
            if (m == "last" || m == "count") && args.is_empty() {
                if let ExprNode::Const { path } = &*r.node {
                    let class = path.last().map(|s| s.as_str().to_string()).unwrap_or_default();
                    return format!("{class}.{m}()");
                }
            }
            if args.is_empty() {
                let recv_s = match &*r.node {
                    ExprNode::Ivar { name } | ExprNode::Var { name, .. } => name.to_string(),
                    _ => emit_ctrl_test_expr(r, app, ctx),
                };
                return format!("{recv_s}.{m}");
            }
            let recv_s = emit_ctrl_test_expr(r, app, ctx);
            let args_s: Vec<String> =
                args.iter().map(|a| emit_ctrl_test_expr(a, app, ctx)).collect();
            format!("{recv_s}.{m}({})", args_s.join(", "))
        }
        ExprNode::Send { recv: None, method, args, .. } => {
            if method.as_str().ends_with("_url") || method.as_str().ends_with("_path") {
                return emit_url_expr(expr, app, ctx);
            }
            let args_s: Vec<String> =
                args.iter().map(|a| emit_ctrl_test_expr(a, app, ctx)).collect();
            if args_s.is_empty() {
                method.to_string()
            } else {
                format!("{method}({})", args_s.join(", "))
            }
        }
        ExprNode::Hash { entries, .. } => {
            let parts: Vec<String> = entries
                .iter()
                .map(|(k, v)| {
                    if let ExprNode::Lit { value: Literal::Sym { value } } = &*k.node {
                        format!("{value}: {}", emit_ctrl_test_expr(v, app, ctx))
                    } else {
                        format!(
                            "{} => {}",
                            emit_ctrl_test_expr(k, app, ctx),
                            emit_ctrl_test_expr(v, app, ctx),
                        )
                    }
                })
                .collect();
            format!("%{{{}}}", parts.join(", "))
        }
        _ => "nil # TODO expr".to_string(),
    }
}

fn flatten_params_to_form(expr: &Expr, scope: Option<&str>, app: &App, ctx: ExTestCtx) -> String {
    let pairs: Vec<String> = crate::lower::flatten_params_pairs(expr, scope)
        .into_iter()
        .map(|(key, value)| {
            let val = emit_ctrl_test_expr(value, app, ctx);
            format!("{key:?} => to_string({val})")
        })
        .collect();
    format!("%{{{}}}", pairs.join(", "))
}

// ---- model tests ------------------------------------------------------

/// `test/<name>.exs` — one ExUnit module per model test (`defmodule
/// <Name>Test`). Bodies use bare names (`Article`, `Fixtures`) resolved
/// via the header aliases — identical to v1 except the model's dual-return
/// `save` (`{record, bool}`) is destructured at `assert/assert_not` sites
/// (v1's save returned a bare bool).
fn emit_model_test(tm: &TestModule, app: &App) -> EmittedFile {
    let fixture_names: Vec<Symbol> = app.fixtures.iter().map(|f| f.name.clone()).collect();
    let known_models = known_models(app);
    let ctx = ExTestCtx {
        app,
        fixture_names: &fixture_names,
        known_models: &known_models,
    };

    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse (elixir2).").unwrap();
    writeln!(s, "defmodule {} do", tm.name.0).unwrap();
    writeln!(s, "  use ExUnit.Case").unwrap();
    // Bare module names (the model modules, `Fixtures`) resolve to the
    // top-level modules directly — no aliases needed.

    if !app.fixtures.is_empty() {
        writeln!(s).unwrap();
        writeln!(s, "  setup do").unwrap();
        writeln!(s, "    Fixtures.setup()").unwrap();
        writeln!(s, "    :ok").unwrap();
        writeln!(s, "  end").unwrap();
    }

    for test in &tm.tests {
        writeln!(s).unwrap();
        writeln!(s, "  test {:?} do", test.name).unwrap();
        let body = emit_model_test_body(&test.body, ctx);
        if body.trim().is_empty() {
            writeln!(s, "    :ok").unwrap();
        } else {
            for line in body.lines() {
                if line.is_empty() {
                    s.push('\n');
                } else {
                    writeln!(s, "    {line}").unwrap();
                }
            }
        }
        writeln!(s, "  end").unwrap();
    }
    writeln!(s, "end").unwrap();

    let filename = snake_case(tm.name.0.as_str());
    EmittedFile {
        path: PathBuf::from(format!("test/{filename}.exs")),
        content: s,
    }
}

fn emit_model_test_body(body: &Expr, ctx: ExTestCtx) -> String {
    match &*body.node {
        ExprNode::Seq { exprs } if !exprs.is_empty() => exprs
            .iter()
            .map(|e| emit_model_test_stmt(e, ctx))
            .collect::<Vec<_>>()
            .join("\n"),
        _ => emit_model_test_stmt(body, ctx),
    }
}

fn emit_model_test_stmt(e: &Expr, ctx: ExTestCtx) -> String {
    match &*e.node {
        ExprNode::Assign { target: LValue::Var { name, .. }, value } => {
            format!("{} = {}", name, emit_model_test_expr(value, ctx))
        }
        _ => emit_model_test_expr(e, ctx),
    }
}

fn emit_model_test_expr(e: &Expr, ctx: ExTestCtx) -> String {
    match &*e.node {
        ExprNode::Lit { value } => emit_lit(value),
        ExprNode::Var { name, .. } => name.to_string(),
        ExprNode::Const { path } => {
            path.iter().map(|s| s.to_string()).collect::<Vec<_>>().join(".")
        }
        ExprNode::Send { recv, method, args, block, .. } => {
            emit_model_test_send(recv.as_ref(), method.as_str(), args, block.as_ref(), ctx)
        }
        ExprNode::BoolOp { op, left, right, .. } => {
            use crate::expr::BoolOpKind;
            let op_s = match op {
                BoolOpKind::Or => "or",
                BoolOpKind::And => "and",
            };
            format!(
                "{} {op_s} {}",
                emit_model_test_expr(left, ctx),
                emit_model_test_expr(right, ctx)
            )
        }
        ExprNode::Hash { entries, .. } => {
            let parts: Vec<String> = entries
                .iter()
                .map(|(k, v)| {
                    if let ExprNode::Lit { value: Literal::Sym { value } } = &*k.node {
                        format!("{value}: {}", emit_model_test_expr(v, ctx))
                    } else {
                        format!(
                            "{} => {}",
                            emit_model_test_expr(k, ctx),
                            emit_model_test_expr(v, ctx),
                        )
                    }
                })
                .collect();
            format!("%{{{}}}", parts.join(", "))
        }
        _ => format!("# TODO: model test emit for {:?}", std::mem::discriminant(&*e.node)),
    }
}

/// If `e` is a model `save` call (`record.save` instance form, or
/// `Model.save(record)` class form), return `(module, record_expr)` so the
/// caller can destructure its dual `{record, bool}` return. The module is
/// the bare aliased name (`Article`), resolving to `Article`.
fn dual_save_call(e: &Expr, ctx: ExTestCtx) -> Option<(String, String)> {
    let ExprNode::Send { recv: Some(r), method, args, .. } = &*e.node else { return None };
    if method.as_str() != "save" {
        return None;
    }
    match &*r.node {
        ExprNode::Var { name, .. } if args.is_empty() => {
            Some((camelize(name.as_str()), name.to_string()))
        }
        ExprNode::Const { path } if args.len() == 1 => {
            let class = path.last()?.to_string();
            if ctx.known_models.iter().any(|s| s.as_str() == class) {
                Some((class, emit_model_test_expr(&args[0], ctx)))
            } else {
                None
            }
        }
        _ => None,
    }
}

fn emit_model_test_send(
    recv: Option<&Expr>,
    method: &str,
    args: &[Expr],
    block: Option<&Expr>,
    ctx: ExTestCtx,
) -> String {
    let args_s: Vec<String> = args.iter().map(|a| emit_model_test_expr(a, ctx)).collect();

    // Fixture accessor: articles(:one) → Fixtures.Articles.one().
    if recv.is_none()
        && args.len() == 1
        && ctx.fixture_names.iter().any(|s| s.as_str() == method)
    {
        if let ExprNode::Lit { value: Literal::Sym { value: sym } } = &*args[0].node {
            return format!("Fixtures.{}.{}()", camelize(method), sym.as_str());
        }
    }

    // assert_difference("Class.count", delta) do … end.
    if recv.is_none() && method == "assert_difference" {
        if let Some(body) = block {
            if let Some(count_expr) = args.first().and_then(|a| match &*a.node {
                ExprNode::Lit { value: Literal::Str { value } } => rewrite_ruby_dot_call(value),
                _ => None,
            }) {
                let delta = args_s.get(1).cloned().unwrap_or_else(|| "1".into());
                let body_s = emit_block_body(body, ctx);
                return format!(
                    "count_before = {count_expr}\n{body_s}\ncount_after = {count_expr}\nassert count_after - count_before == {delta}"
                );
            }
        }
    }

    // owner.<assoc>.create(hash) / .build(hash) — HasMany rewrite.
    if (method == "create" || method == "build") && args.len() == 1 {
        if let Some(outer_recv) = recv {
            if let ExprNode::Send { recv: Some(assoc_recv), method: assoc_method, args: inner, .. } =
                &*outer_recv.node
            {
                if inner.is_empty() {
                    if let Some(s) =
                        try_assoc_create(assoc_recv, assoc_method.as_str(), args, method, ctx)
                    {
                        return s;
                    }
                }
            }
        }
    }

    // Assertion macros → ExUnit assert/refute. `assert_not <save>` /
    // `assert <save>` destructure the model's dual-return save.
    if recv.is_none() {
        match (method, args.len()) {
            ("assert_not" | "refute", 1) => {
                if let Some((module, rec)) = dual_save_call(&args[0], ctx) {
                    return format!("{{_saved, ok}} = {module}.save({rec})\nrefute ok");
                }
                return format!("refute {}", args_s[0]);
            }
            ("assert", 1) => {
                if let Some((module, rec)) = dual_save_call(&args[0], ctx) {
                    return format!("{{_saved, ok}} = {module}.save({rec})\nassert ok");
                }
                return format!("assert {}", args_s[0]);
            }
            ("assert_equal", 2) => {
                return format!("assert {} == {}", args_s[1], args_s[0]);
            }
            ("assert_not_equal", 2) => {
                return format!("refute {} == {}", args_s[1], args_s[0]);
            }
            ("assert_nil", 1) => return format!("assert is_nil({})", args_s[0]),
            ("assert_not_nil", 1) => return format!("refute is_nil({})", args_s[0]),
            _ => {}
        }
    }

    // `Class.new(hash)` → `%Class{ k: v, … }` struct literal (bare class
    // name resolves to `%Class{}` via the alias).
    if let Some(r) = recv {
        if method == "new" && args.len() == 1 {
            if let ExprNode::Const { path } = &*r.node {
                if let Some(class) = path.last() {
                    if ctx.known_models.iter().any(|s| s == class) {
                        if let ExprNode::Hash { entries, .. } = &*args[0].node {
                            let pairs: Vec<String> = entries
                                .iter()
                                .filter_map(|(k, v)| match &*k.node {
                                    ExprNode::Lit { value: Literal::Sym { value: f } } => {
                                        Some(format!("{}: {}", f.as_str(), emit_model_test_expr(v, ctx)))
                                    }
                                    _ => None,
                                })
                                .collect();
                            return format!("%{}{{{}}}", class, pairs.join(", "));
                        }
                    }
                }
            }
        }
    }

    match recv {
        None => {
            if args_s.is_empty() {
                method.to_string()
            } else {
                format!("{}({})", method, args_s.join(", "))
            }
        }
        Some(r) => {
            let recv_s = emit_model_test_expr(r, ctx);
            if matches!(&*r.node, ExprNode::Const { .. }) {
                // Module.function(args).
                if args_s.is_empty() {
                    format!("{recv_s}.{method}()")
                } else {
                    format!("{recv_s}.{method}({})", args_s.join(", "))
                }
            } else if method == "destroy" && args_s.is_empty() {
                // Instance call on a record → module function (destroy
                // returns the record, not a dual — fine as a statement).
                format!("{}.destroy({recv_s})", camelize_recv(r))
            } else if args_s.is_empty() {
                // Attribute / field read: `article.title`, `comment.id`.
                format!("{recv_s}.{method}")
            } else {
                format!("{recv_s}.{method}({})", args_s.join(", "))
            }
        }
    }
}

/// `owner.<assoc>.create(hash)` / `.build(hash)` → struct build (+ save for
/// `create`). The dual-return save is destructured; the saved record (with
/// its assigned id) is the expression's value.
fn try_assoc_create(
    owner: &Expr,
    assoc_name: &str,
    args: &[Expr],
    outer_method: &str,
    ctx: ExTestCtx,
) -> Option<String> {
    let resolved =
        crate::lower::resolve_has_many(&Symbol::from(assoc_name), owner.ty.as_ref(), ctx.app)?;
    let target_class = resolved.target_class.0.as_str();
    let foreign_key = resolved.foreign_key.as_str();

    let owner_s = emit_model_test_expr(owner, ctx);
    let ExprNode::Hash { entries, .. } = &*args.first()?.node else { return None };

    let mut pairs: Vec<String> = vec![format!("{foreign_key}: {owner_s}.id")];
    for (k, v) in entries {
        if let ExprNode::Lit { value: Literal::Sym { value: field } } = &*k.node {
            pairs.push(format!("{}: {}", field.as_str(), emit_model_test_expr(v, ctx)));
        }
    }
    let struct_lit = format!("%{target_class}{{{}}}", pairs.join(", "));
    if outer_method == "create" {
        // Anonymous-function call to sequence build → save → yield the
        // saved record (dual save assigns the id onto the returned record).
        Some(format!(
            "(fn ->\n      record = {struct_lit}\n      {{record, _}} = {target_class}.save(record)\n      record\n    end).()"
        ))
    } else {
        Some(struct_lit)
    }
}

fn emit_block_body(e: &Expr, ctx: ExTestCtx) -> String {
    let inner = match &*e.node {
        ExprNode::Lambda { body, .. } => body,
        _ => e,
    };
    match &*inner.node {
        ExprNode::Seq { exprs } if !exprs.is_empty() => exprs
            .iter()
            .map(|s| emit_model_test_stmt(s, ctx))
            .collect::<Vec<_>>()
            .join("\n"),
        _ => emit_model_test_stmt(inner, ctx),
    }
}

/// Module name for an instance call's receiver — fixture var names follow
/// the snake-cased class name (`article` → `Article`, aliased to
/// `Article`).
fn camelize_recv(recv: &Expr) -> String {
    match &*recv.node {
        ExprNode::Var { name, .. } => camelize(name.as_str()),
        _ => "Unknown".to_string(),
    }
}

/// Parse a Ruby `"Class.method"` string into Elixir `Class.method()` (for
/// `assert_difference("Comment.count")`). Capitalized LHS → module call.
fn rewrite_ruby_dot_call(expr: &str) -> Option<String> {
    let (lhs, rhs) = expr.trim().split_once('.')?;
    let is_ident = |s: &str| {
        !s.is_empty()
            && s.chars().next().is_some_and(|c| c.is_alphabetic() || c == '_')
            && s.chars().all(|c| c.is_alphanumeric() || c == '_')
    };
    if !is_ident(lhs) || !is_ident(rhs) {
        return None;
    }
    Some(format!("{lhs}.{rhs}()"))
}

fn emit_lit(v: &Literal) -> String {
    match v {
        Literal::Nil => "nil".to_string(),
        Literal::Bool { value } => value.to_string(),
        Literal::Int { value } => value.to_string(),
        Literal::Float { value } => value.to_string(),
        Literal::Str { value } => format!("{value:?}"),
        Literal::Sym { value } => format!(":{value}"),
        Literal::Regex { pattern, .. } => format!("~r/{pattern}/"),
    }
}
