module ActionController
  class ParameterMissing < StandardError
    @param: String
    def initialize: (String param) -> void
    def param: () -> String
  end

  class UnpermittedParameters < StandardError
  end

  class BadRequest < StandardError
    def initialize: (?String msg) -> void
  end

  class InvalidAuthenticityToken < StandardError
    def initialize: (?String msg) -> void
  end

  class UnknownFormat < StandardError
  end

  class RoutingError < StandardError
    @failures: Array[String]
    def initialize: (String message, ?Array[String] failures) -> void
    def failures: () -> Array[String]
  end
end

module AbstractController
  class ActionNotFound < StandardError
  end
end
