# Top-level entry point for the spinel-blog application.
#
# Reads a CGI request from ENV + $stdin, dispatches through the router
# + controller, writes the CGI response to $stdout. The shape spinel
# can ingest (no sockets, just env-vars + stdin + stdout) and the
# shape any CGI-aware web server can drive.
#
# Library usage (from tests):
#   require_relative "main"
#   Main.run(env_hash, body_io, response_io)
#
# Script usage:
#   REQUEST_METHOD=GET PATH_INFO=/articles ruby main.rb
# Or behind a CGI-aware server:
#   AddHandler cgi-script .rb       (apache)
#   alias /blog /path/to/main.rb    (nginx + fcgiwrap)

# SqliteAdapter is hoisted to top-level so the spinel-AOT compile
# can statically resolve the `SqliteAdapter` constant referenced
# from `Base#save` etc. via the adapter dispatcher. Under CRuby the
# require is harmless (the gem-backed shim only opens a DB on
# `configure`); under spinel the FFI-backed shim only emits when
# `runtime/sqlite_adapter` is in the require graph.
require_relative "runtime/sqlite_adapter"
# Db primitive surface — backs the lowerer-emitted `_adapter_*`
# methods (Level-3 emit + Phase 1 Arel inline-SELECT expansions).
# Required before active_record so Base.rb's default `_adapter_*`
# helpers and per-model overrides find `Db` at constant-resolution
# time. See project_arel_compile_time_first.md.
require_relative "runtime/db"
# Base64 + JSON + Importmap shims. All required before any framework
# Ruby file that references them so spinel-AOT's static resolver
# sees the constants. The per-app config/importmap.rb (when emitted)
# reopens Importmap with the source-derived pins/entry; Base64 and
# JSON have no per-app override. Under CRuby these shims override
# the stdlib equivalents with semantically-identical implementations
# for the surface framework Ruby actually uses.
require_relative "runtime/base64"
require_relative "runtime/json"
# JsonBuilder — the JSON encoding primitives the Jbuilder lowerer
# emits calls to (`Views::Articles.article_json` etc.). Separate from
# `runtime/json.rb`'s `JSON.generate` shim: this module exposes
# `JsonBuilder.encode_value` / `encode_string` for per-value encoding.
require_relative "runtime/json_builder"
require_relative "runtime/importmap"
require_relative "runtime/active_record"
require_relative "config/schema"
require_relative "runtime/action_dispatch"
require_relative "runtime/action_controller"
require_relative "runtime/broadcasts"
require_relative "runtime/cgi_io"
require_relative "config/routes"
# Per-app Importmap override (generated by Roundhouse from the source
# app's config/importmap.rb). Conditional because source apps without
# an importmap don't have this file emitted; the runtime/importmap.rb
# fallback stands in that case. The `begin/rescue` is CRuby-style
# error handling — spinel's static analyzer ignores the rescue path,
# which is fine here because Importmap is already defined by the
# fallback require above.
begin
  require_relative "config/importmap"
rescue LoadError
end
require_relative "app/views"

module Main
  # Dispatch one request. Pure function over (env, stdin, stdout) — no
  # global I/O. Tests construct env hashes + StringIO and call this
  # directly; the script path at the bottom of this file calls it
  # with real ENV + $stdin + $stdout.
  #
  # `ActionView::ViewHelpers` and `ActionDispatch::Router` are
  # written fully-qualified (rather than the prior `include
  # ActionView`/`include ActionDispatch` + bare names) so spinel-AOT's
  # constant resolver sees the references without walking included-
  # module namespaces — a path it doesn't currently follow.
  def self.run(env, stdin, stdout)
    ActionView::ViewHelpers.reset_slots!
    Broadcasts.reset_log!

    request = CgiIo.parse_request(env, stdin)
    # Per-request format inference. Strip a `.json` suffix from the
    # request path before route matching (so `/articles/1.json` and
    # `/articles/1` share one route entry) and remember the format
    # so the controller's `respond_to`-flattened branch can pick the
    # right view + Content-Type. Default html for any unrecognized
    # extension.
    request_format = :html
    request_path = request[:path]
    if request_path.end_with?(".json")
      request_format = :json
      request_path = request_path[0...-5]
    end
    # Prepend ROOT so a GET / request matches before falling through
    # to TABLE. ROOT is kept as a separate constant in routes.rb for
    # legibility (it's the only literal-pattern entry); the dispatch
    # composes them here so Router.match stays a flat-table walk.
    matched = ActionDispatch::Router.match(request[:method], request_path,
                           [Routes.root] + Routes.table)
    if matched.nil?
      CgiIo.write_response(stdout, 404, "<h1>404 Not Found</h1>")
      return
    end

    controller = Main.instantiate_controller(matched[:controller])
    merged = matched[:path_params].dup
    request[:params].each { |k, v| merged[k] = v }
    controller.params  = merged
    controller.session = ActionDispatch::Session.new

    # Decode inbound flash from cookies. Each flash key carries via
    # its own cookie (`flash_notice`, `flash_alert`) so the cookie
    # plumbing stays format-free.
    cookies = request[:cookies] || {}
    inbound_flash = ActionDispatch::Flash.new
    inbound_flash[:notice] = cookies[:flash_notice] if cookies.key?(:flash_notice)
    inbound_flash[:alert]  = cookies[:flash_alert]  if cookies.key?(:flash_alert)
    controller.flash = inbound_flash

    controller.request_method = request[:method]
    controller.request_path   = request[:path]
    controller.request_format = request_format

    begin
      controller.process_action(matched[:action])
    rescue ActiveRecord::RecordNotFound
      CgiIo.write_response(stdout, 404, "<h1>404 Not Found</h1>")
      return
    end

    # Dispatch on status, not on @location nil-ness: redirect_to
    # produces a 3xx status (302/303/etc.) and short-circuits to a
    # "Redirecting…" body; render-with-`location:` (Rails' POST 201
    # idiom) keeps a 2xx status and ships the rendered body alongside
    # the Location header.
    out_cookies = {}
    is_redirect = controller.status >= 300 && controller.status < 400
    if is_redirect
      # Redirect: ship the outbound flash as cookies for the next
      # request to consume.
      out_cookies[:flash_notice] = controller.flash[:notice] unless controller.flash[:notice].nil?
      out_cookies[:flash_alert]  = controller.flash[:alert]  unless controller.flash[:alert].nil?
      CgiIo.write_response(stdout, controller.status,
        %(<a href="#{controller.location}">Redirecting</a>),
        location: controller.location,
        set_cookies: out_cookies)
    else
      # Render: clear inbound flash cookies (the action used them for
      # display; the next request shouldn't see the same notice
      # again). JSON responses skip the html layout wrap and ship the
      # controller body verbatim with the JSON Content-Type. Other
      # formats ride the application layout. `controller.location`
      # (set by `render … location: @article`) flows through as the
      # Location header when present.
      out_cookies[:flash_notice] = nil if cookies.key?(:flash_notice)
      out_cookies[:flash_alert]  = nil if cookies.key?(:flash_alert)
      if controller.request_format == :json
        CgiIo.write_response(stdout, controller.status, controller.body,
          content_type: controller.content_type,
          location: controller.location,
          set_cookies: out_cookies)
      else
        page = Views::Layouts.application(controller.body)
        CgiIo.write_response(stdout, controller.status, page,
          location: controller.location,
          set_cookies: out_cookies)
      end
    end
  end

  # Maps the routes-table controller symbol to a literal `.new`
  # constructor call. Spinel's hash specializations don't accept class
  # references as values, so the route table stores symbols and this
  # case turns the symbol back into an instance via direct
  # constructor calls (statically resolvable; no `.send`).
  def self.instantiate_controller(sym)
    case sym
    when :articles then ArticlesController.new
    when :comments then CommentsController.new
    end
  end

  # First-time setup. Idempotent: skips when already configured (so
  # tests that load main.rb don't conflict with their own test_helper
  # setup).
  #
  # When `BLOG_DB` env var names a path, configure SqliteAdapter
  # against that file — required for the dev server, which forks a
  # fresh CGI process per request and would otherwise lose all data
  # between requests. Without BLOG_DB, fall back to `:memory:` — works
  # for the spinel-compiled binary (FFI sqlite is universal) and the
  # one-shot CGI invocation, and is per-process (no persistence across
  # forks, which is fine for both).
  def self.configure_default_adapter!
    return unless ActiveRecord.adapter.nil?
    db_path = ENV["BLOG_DB"]
    path = (!db_path.nil? && !db_path.empty?) ? db_path : ":memory:"
    # SqliteAdapter.configure delegates to Db.configure (single shared
    # connection); both the legacy AR-adapter dispatch path and the
    # Level-3 lowerer-emitted `_adapter_*` path read through one handle.
    SqliteAdapter.configure(path)
    ActiveRecord.adapter = SqliteAdapter
    Schema.statements.each { |sql| SqliteAdapter.execute_ddl(sql) }
  end
end

# Auto-run only when invoked as a script (`ruby main.rb`). When loaded
# via `require_relative "main"` from tests, the dispatch isn't
# triggered — tests call Main.run themselves with constructed I/O.
#
# The env hash is built explicitly from the CGI variables we read,
# rather than `ENV.to_h` — Spinel supports `ENV[]` indexing reliably
# but `.to_h` is on the verify list.
if __FILE__ == $PROGRAM_NAME
  Main.configure_default_adapter!
  env = {
    "REQUEST_METHOD" => ENV["REQUEST_METHOD"],
    "PATH_INFO"      => ENV["PATH_INFO"],
    "QUERY_STRING"   => ENV["QUERY_STRING"],
    "CONTENT_LENGTH" => ENV["CONTENT_LENGTH"],
    "CONTENT_TYPE"   => ENV["CONTENT_TYPE"],
    "HTTP_COOKIE"    => ENV["HTTP_COOKIE"],
  }
  Main.run(env, $stdin, $stdout)
end
