module ActionDispatch
  module Http
    class Headers
      CGI_VARIABLES: Array[String]
      HTTP_HEADER: Regexp

      @env: Hash[String, untyped]

      def initialize: (Hash[String, untyped] env) -> void
      def []: (String | Symbol key) -> untyped
      def key?: (String | Symbol key) -> bool
      def include?: (String | Symbol key) -> bool
      def fetch: (String | Symbol key, *untyped defaults) -> untyped
      def self.env_name: (String | Symbol key) -> String
    end
  end
end
