# Path router: matches (method, path) against a hand-written route
# table and resolves to (controller_class, action, path_params).
#
# In real-blog this is generated by Rails from `config/routes.rb`'s
# `resources` DSL; in spinel-blog it's a flat data structure (see
# `config/routes.rb`). The eventual transpiler reproduces this shape
# from the DSL declarations.
require_relative "../active_support/hash_with_indifferent_access"

module Router
  module_function

  # Match a request against the route table. Returns a hash with
  # :controller, :action, :path_params on success; nil otherwise.
  #
  # Index-style loop (not `table.each do |...| ... return ... end`)
  # so the cross-target lowering doesn't have to model "return from
  # enclosing method out of an iterator block" — JS `forEach` can't
  # break out of the surrounding function and the body-walker would
  # silently strip the early-return.
  def match(method, path, table)
    method_upcase = method.to_s.upcase
    i = 0
    while i < table.length
      route = table[i]
      if route[:method] == method_upcase
        params = match_pattern(route[:pattern], path)
        unless params.nil?
          return {
            controller: route[:controller],
            action:     route[:action],
            path_params: params,
          }
        end
      end
      i += 1
    end
    nil
  end

  # Match a path against a pattern containing `:name` segments.
  # Returns an HWIA of captured params (String-keyed internally,
  # accepts Symbol-or-String access via `[](:id)` / `["id"]`), or nil
  # if no match. No regex; segment-by-segment compare.
  def match_pattern(pattern, path)
    pattern_parts = pattern.split("/")
    path_parts    = path.split("/")
    return nil if pattern_parts.length != path_parts.length
    params = ActiveSupport::HashWithIndifferentAccess.new
    i = 0
    while i < pattern_parts.length
      pp = pattern_parts[i]
      ap = path_parts[i]
      if pp.start_with?(":")
        params[pp[1..]] = ap
      elsif pp != ap
        return nil
      end
      i += 1
    end
    params
  end
end
