# Path router: matches (method, path) against a typed route table and
# resolves to (controller, action, path_params).
#
# In real-blog this is generated by Rails from `config/routes.rb`'s
# `resources` DSL; in spinel-blog it's a flat data structure (see
# `config/routes.rb`). The eventual transpiler reproduces this shape
# from the DSL declarations.
#
# Route rows are typed `Route` instances (not `Hash[Symbol, untyped]`)
# so strict-typed targets (Rust, Crystal) compile against per-field
# types instead of falling through an `untyped` value channel. Path
# captures land as `Hash[String, String]` — URL segments are always
# strings.

module ActionDispatch
  module Router
    # One entry in the route table. Promoted from
    # `Hash[Symbol, String|Symbol]` to a typed class so each per-field
    # type is statically known. `verb` rather than `method` to avoid
    # shadowing Ruby's `Object#method` reflection method.
    #
    # Positional `initialize` (not kwarg) — the per-target emitters
    # convert def-time kwargs to positional but don't unpack kwarg-style
    # call sites; positional avoids the asymmetry on internal classes
    # like this one.
    class Route
      attr_reader :verb, :pattern, :controller, :action

      def initialize(verb, pattern, controller, action)
        @verb        = verb
        @pattern     = pattern
        @controller  = controller
        @action      = action
      end
    end

    # The result of a successful `Router.match` call: the resolved
    # controller symbol, action symbol, and captured path parameters.
    # Replaces the prior `{ controller:, action:, path_params: }` hash
    # return shape. Positional initialize, same rationale as Route.
    class MatchResult
      attr_reader :controller, :action, :path_params

      def initialize(controller, action, path_params)
        @controller  = controller
        @action      = action
        @path_params = path_params
      end
    end

    # Match a request against the route table. Returns a `MatchResult`
    # on success; nil otherwise.
    #
    # Index-style loop (not `table.each do |...| ... return ... end`)
    # so the cross-target lowering doesn't have to model "return from
    # enclosing method out of an iterator block" — JS `forEach` can't
    # break out of the surrounding function and the body-walker would
    # silently strip the early-return.
    def self.match(method, path, table)
      method_upcase = method.to_s.upcase
      i = 0
      while i < table.length
        route = table[i]
        if route.verb.to_s == method_upcase
          params = match_pattern(route.pattern.to_s, path)
          unless params.nil?
            return MatchResult.new(route.controller, route.action, params)
          end
        end
        i += 1
      end
      nil
    end

    # Match a path against a pattern containing `:name` segments.
    # Returns a `Hash[String, String]` of captured params, or nil
    # if no match. No regex; segment-by-segment compare. Captures
    # are always string-to-string — URL segments are strings, and
    # the typed-hash form survives strict-typed targets (Crystal,
    # Rust). Callers index by string key (`params["id"]`).
    def self.match_pattern(pattern, path)
      pattern_parts = pattern.split("/")
      path_parts    = path.split("/")
      return nil if pattern_parts.length != path_parts.length
      params = {}
      i = 0
      while i < pattern_parts.length
        pp = pattern_parts[i]
        ap = path_parts[i]
        if pp.start_with?(":")
          params[pp[1..]] = ap
        elsif pp != ap
          return nil
        end
        i += 1
      end
      params
    end
  end
end
