//! Crystal emitter.
//!
//! Last Phase 2 scaffold. Crystal is Ruby-flavored with mandatory
//! static types, which makes this the easiest scaffold of the six —
//! the emission shape is almost identical to Ruby's, plus type
//! annotations.
//!
//! Scaffold choices:
//! - Models as `class Name` with typed `property :field : Type`
//!   declarations (Crystal's getter/setter macro).
//! - Controllers as `class Name` with one method per action. No
//!   `< Kemal::Controller` base — Phase 3+ runtime work picks.
//! - Routes as a `ROUTES` constant with a NamedTuple array —
//!   Crystal's idiomatic static table shape.
//!
//! Notably not mirrored from railcar:
//! - Railcar's Crystal output uses a heavy macro DSL
//!   (`model("articles") do column(title, String) end`) to hook
//!   into its runtime. That's a Phase-4-depth choice; our scaffold
//!   stays runtime-agnostic.

use std::fmt::Write;
use std::path::PathBuf;

use super::EmittedFile;
use crate::App;
use crate::dialect::{
    Action, Controller, MethodDef, Model, RouteSpec, Test, TestModule,
};
use crate::expr::{Expr, ExprNode, LValue, Literal};
use crate::ident::Symbol;
use crate::ty::Ty;

const RUNTIME_SOURCE: &str = include_str!("../../runtime/crystal/runtime.cr");
const DB_SOURCE: &str = include_str!("../../runtime/crystal/db.cr");

pub fn emit(app: &App) -> Vec<EmittedFile> {
    let mut files = Vec::new();
    files.push(emit_shard_yml());
    if !app.models.is_empty() {
        files.push(emit_models(app));
        // Runtime tags along whenever any model is emitted — validate()
        // calls ValidationError.new.
        files.push(EmittedFile {
            path: PathBuf::from("src/runtime.cr"),
            content: RUNTIME_SOURCE.to_string(),
        });
        files.push(EmittedFile {
            path: PathBuf::from("src/db.cr"),
            content: DB_SOURCE.to_string(),
        });
        files.push(emit_schema_sql(app));
    }
    if !app.controllers.is_empty() {
        files.push(emit_controllers(app));
    }
    if !app.routes.entries.is_empty() {
        files.push(emit_routes(app));
    }
    // Fixtures as modules under spec/fixtures/. Emitted as individual
    // files plus a top-level spec/fixtures.cr helper.
    if !app.fixtures.is_empty() {
        let lowered = crate::lower::lower_fixtures(app);
        files.push(emit_fixtures_helper(&lowered));
        for f in &lowered.fixtures {
            files.push(emit_crystal_fixture(f));
        }
    }
    if !app.test_modules.is_empty() {
        for tm in &app.test_modules {
            files.push(emit_crystal_spec(tm, app));
        }
        files.push(emit_spec_helper(app));
    }
    files.push(emit_app_cr(app));
    files
}

/// Minimal `shard.yml` — Crystal's equivalent of `Cargo.toml`. Declares
/// one named `targets` entry so `crystal build` knows the entry point;
/// the entry file (`src/app.cr`) requires whatever modules we emitted.
fn emit_shard_yml() -> EmittedFile {
    let content = "\
name: app
version: 0.1.0

targets:
  app:
    main: src/app.cr

dependencies:
  sqlite3:
    github: crystal-lang/crystal-sqlite3
    version: ~> 0.21
";
    EmittedFile {
        path: PathBuf::from("shard.yml"),
        content: content.to_string(),
    }
}

/// `src/schema_sql.cr` — Crystal constant wrapping the target-neutral
/// DDL produced by `lower::lower_schema`. `Roundhouse::Db.setup_test_db`
/// reads it to initialize a fresh :memory: SQLite connection per spec.
fn emit_schema_sql(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "module Roundhouse").unwrap();
    writeln!(s, "  module SchemaSQL").unwrap();
    writeln!(s, "    CREATE_TABLES = <<-SQL").unwrap();
    let ddl = crate::lower::lower_schema(&app.schema);
    for line in ddl.lines() {
        writeln!(s, "      {line}").unwrap();
    }
    writeln!(s, "    SQL").unwrap();
    writeln!(s, "  end").unwrap();
    writeln!(s, "end").unwrap();
    EmittedFile {
        path: PathBuf::from("src/schema_sql.cr"),
        content: s,
    }
}

/// `src/app.cr` — Crystal entry point. Requires the emitted modules we
/// expect to compile. Phase 1 scope: models + runtime only. Controllers
/// + routes are emitted as files but not required, for the same reason
/// the Rust emitter keeps controllers out of `lib.rs`: their bodies
/// reference a Rails runtime that doesn't exist yet.
fn emit_app_cr(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    if !app.models.is_empty() {
        writeln!(s, "require \"./runtime\"").unwrap();
        writeln!(s, "require \"./db\"").unwrap();
        writeln!(s, "require \"./schema_sql\"").unwrap();
        writeln!(s, "require \"./models\"").unwrap();
    }
    EmittedFile {
        path: PathBuf::from("src/app.cr"),
        content: s,
    }
}

// Models ---------------------------------------------------------------

fn emit_models(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    for (i, model) in app.models.iter().enumerate() {
        if i > 0 {
            writeln!(s).unwrap();
        }
        emit_model(&mut s, model, app);
    }
    EmittedFile { path: PathBuf::from("src/models.cr"), content: s }
}

fn emit_model(out: &mut String, model: &Model, app: &App) {
    let name = model.name.0.as_str();
    writeln!(out, "class {name}").unwrap();
    for (field, ty) in &model.attributes.fields {
        writeln!(
            out,
            "  property {} : {} = {}",
            field,
            crystal_ty(ty),
            crystal_default(ty),
        )
        .unwrap();
    }
    for method in model.methods() {
        writeln!(out).unwrap();
        emit_model_method(out, method);
    }
    let lowered = crate::lower::lower_validations(model);
    if !lowered.is_empty() {
        writeln!(out).unwrap();
        emit_validate_method(out, &lowered);
    }
    // Skip persistence for abstract base classes (no columns beyond
    // maybe an `id`) — ApplicationRecord et al. have nothing to save.
    let has_table = model
        .attributes
        .fields
        .keys()
        .any(|k| k.as_str() != "id");
    if has_table {
        writeln!(out).unwrap();
        emit_persistence_methods_cr(out, model, !lowered.is_empty(), app);
    }
    writeln!(out, "end").unwrap();
}

/// Render save/destroy/count/find for a model against the test
/// connection. SQL strings come from `LoweredPersistence`; per-target
/// concerns are placeholder dialect (`?N` → `?`) and the crystal-db
/// API shape (exec/scalar/query_one? with block hydration).
fn emit_persistence_methods_cr(out: &mut String, model: &Model, has_validate: bool, app: &App) {
    let lp = crate::lower::lower_persistence(model, app);
    let class = lp.class.0.as_str();

    let insert_sql = positional_placeholders(&lp.insert_sql);
    let update_sql = positional_placeholders(&lp.update_sql);
    let delete_sql = positional_placeholders(&lp.delete_sql);
    let select_by_id_sql = positional_placeholders(&lp.select_by_id_sql);
    let count_sql = lp.count_sql.clone(); // no placeholders

    let non_id_args: Vec<String> = lp
        .non_id_columns
        .iter()
        .map(|s| s.as_str().to_string())
        .collect();

    // ----- save -----
    writeln!(out, "  def save : Bool").unwrap();
    if has_validate {
        writeln!(out, "    errors = validate").unwrap();
        writeln!(out, "    return false unless errors.empty?").unwrap();
    }
    for check in &lp.belongs_to_checks {
        let fk = check.foreign_key.as_str();
        let target = check.target_class.0.as_str();
        writeln!(
            out,
            "    return false if {fk} == 0_i64 || {target}.find({fk}).nil?",
        )
        .unwrap();
    }
    writeln!(out, "    db = Roundhouse::Db.conn").unwrap();
    writeln!(out, "    if id == 0_i64").unwrap();
    writeln!(
        out,
        "      result = db.exec({insert_sql:?}, {})",
        non_id_args.join(", "),
    )
    .unwrap();
    writeln!(out, "      @id = result.last_insert_id").unwrap();
    writeln!(out, "    else").unwrap();
    writeln!(
        out,
        "      db.exec({update_sql:?}, {}, id)",
        non_id_args.join(", "),
    )
    .unwrap();
    writeln!(out, "    end").unwrap();
    writeln!(out, "    true").unwrap();
    writeln!(out, "  end").unwrap();

    // ----- destroy -----
    writeln!(out).unwrap();
    writeln!(out, "  def destroy").unwrap();
    for dc in &lp.dependent_children {
        let child_class = dc.child_class.0.as_str();
        let child_select = positional_placeholders(&dc.select_by_parent_sql);
        writeln!(out, "    dependents = [] of {child_class}").unwrap();
        writeln!(
            out,
            "    Roundhouse::Db.conn.query_all({child_select:?}, id) do |rs|"
        )
        .unwrap();
        writeln!(out, "      record = {child_class}.new").unwrap();
        for col in &dc.child_columns {
            let col_name = col.as_str();
            let ty = cr_rs_reader_type(col_name);
            writeln!(out, "      record.{col_name} = rs.read({ty})").unwrap();
        }
        writeln!(out, "      dependents << record").unwrap();
        writeln!(out, "    end").unwrap();
        writeln!(out, "    dependents.each(&.destroy)").unwrap();
    }
    writeln!(
        out,
        "    Roundhouse::Db.conn.exec({delete_sql:?}, id)",
    )
    .unwrap();
    writeln!(out, "  end").unwrap();

    // ----- count -----
    writeln!(out).unwrap();
    writeln!(out, "  def self.count : Int64").unwrap();
    writeln!(
        out,
        "    Roundhouse::Db.conn.scalar({count_sql:?}).as(Int64)",
    )
    .unwrap();
    writeln!(out, "  end").unwrap();

    // ----- find -----
    writeln!(out).unwrap();
    writeln!(out, "  def self.find(id : Int64) : {class}?").unwrap();
    writeln!(
        out,
        "    Roundhouse::Db.conn.query_one?({select_by_id_sql:?}, id) do |rs|",
    )
    .unwrap();
    writeln!(out, "      record = {class}.new").unwrap();
    for col in &lp.columns {
        let col_name = col.as_str();
        let ty = cr_rs_reader_type_for(model, col_name);
        writeln!(out, "      record.{col_name} = rs.read({ty})").unwrap();
    }
    writeln!(out, "      record").unwrap();
    writeln!(out, "    end").unwrap();
    writeln!(out, "  end").unwrap();
}

/// SQLite numbered placeholders (`?1`, `?2`) → crystal-db positional
/// (`?`). Same table, same semantics, different wire syntax — a
/// driver-level quirk we absorb at emit time. Keyed on `?` + digit
/// run; non-placeholder `?`s pass through.
fn positional_placeholders(sql: &str) -> String {
    let mut out = String::new();
    let chars: Vec<char> = sql.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        if chars[i] == '?' {
            out.push('?');
            i += 1;
            while i < chars.len() && chars[i].is_ascii_digit() {
                i += 1;
            }
        } else {
            out.push(chars[i]);
            i += 1;
        }
    }
    out
}

/// Crystal reader type for a struct field during cascade hydration.
/// Uses the model's declared type when available; defaults to
/// Int64/String by column-name heuristic otherwise (only happens when
/// a LoweredPersistence DependentChild carries columns whose owning
/// model isn't on hand in this callsite).
fn cr_rs_reader_type(col_name: &str) -> &'static str {
    match col_name {
        "id" => "Int64",
        _ if col_name.ends_with("_id") => "Int64",
        "created_at" | "updated_at" => "Time",
        _ => "String",
    }
}

fn cr_rs_reader_type_for(model: &Model, col_name: &str) -> String {
    if let Some(ty) = model
        .attributes
        .fields
        .iter()
        .find(|(k, _)| k.as_str() == col_name)
        .map(|(_, v)| v)
    {
        match ty {
            Ty::Int => "Int64".to_string(),
            Ty::Float => "Float64".to_string(),
            Ty::Bool => "Bool".to_string(),
            Ty::Str | Ty::Sym => "String".to_string(),
            Ty::Class { id, .. } if id.0.as_str() == "Time" => "Time".to_string(),
            _ => "String".to_string(),
        }
    } else {
        cr_rs_reader_type(col_name).to_string()
    }
}

fn emit_validate_method(
    out: &mut String,
    validations: &[crate::lower::LoweredValidation],
) {
    writeln!(out, "  def validate : Array(Roundhouse::ValidationError)").unwrap();
    writeln!(out, "    errors = [] of Roundhouse::ValidationError").unwrap();
    for lv in validations {
        for check in &lv.checks {
            emit_check_inline_cr(out, lv.attribute.as_str(), check);
        }
    }
    writeln!(out, "    errors").unwrap();
    writeln!(out, "  end").unwrap();
}

fn emit_check_inline_cr(out: &mut String, attr: &str, check: &crate::lower::Check) {
    use crate::lower::Check;
    let msg = check.default_message();
    let push = |cond: &str| -> String {
        format!(
            "    if {cond}\n      errors << Roundhouse::ValidationError.new({attr:?}, {msg:?})\n    end",
        )
    };
    let block = match check {
        Check::Presence => push(&format!("{attr}.empty?")),
        Check::Absence => push(&format!("!{attr}.empty?")),
        Check::MinLength { n } => push(&format!("{attr}.size < {n}")),
        Check::MaxLength { n } => push(&format!("{attr}.size > {n}")),
        Check::GreaterThan { threshold } => push(&format!("{attr} <= {threshold}")),
        Check::LessThan { threshold } => push(&format!("{attr} >= {threshold}")),
        Check::OnlyInteger => {
            format!("    # OnlyInteger on {attr:?} — enforced by Crystal's type system")
        }
        Check::Inclusion { values } => {
            let parts: Vec<String> = values.iter().map(inclusion_value_to_cr).collect();
            push(&format!("![{}].includes?({attr})", parts.join(", ")))
        }
        Check::Format { pattern } => {
            format!(
                "    # TODO: Format check on {attr:?} requires runtime regex ({pattern:?})"
            )
        }
        Check::Uniqueness { .. } => format!(
            "    # TODO: Uniqueness on {attr:?} requires DB access at runtime"
        ),
        Check::Custom { method } => format!("    {method}(errors)"),
    };
    writeln!(out, "{block}").unwrap();
}

fn inclusion_value_to_cr(v: &crate::lower::InclusionValue) -> String {
    use crate::lower::InclusionValue;
    match v {
        InclusionValue::Str { value } => format!("{value:?}"),
        InclusionValue::Int { value } => format!("{value}_i64"),
        InclusionValue::Float { value } => {
            let s = value.to_string();
            if s.contains('.') { format!("{s}_f64") } else { format!("{s}.0_f64") }
        }
        InclusionValue::Bool { value } => value.to_string(),
    }
}

/// A Crystal literal expression for the given type's zero value.
/// Crystal's `property` declarations must be initialized — unlike
/// Rust's `#[derive(Default)]` we have to write the value inline.
/// Keep aligned with `crystal_ty`: whatever a field renders as, its
/// default must be a valid expression of that type.
fn crystal_default(ty: &Ty) -> String {
    match ty {
        Ty::Int => "0_i64".to_string(),
        Ty::Float => "0.0_f64".to_string(),
        Ty::Bool => "false".to_string(),
        Ty::Str | Ty::Sym => "\"\"".to_string(),
        Ty::Nil => "nil".to_string(),
        Ty::Array { .. } => "[] of typeof({})".to_string(),
        Ty::Hash { .. } => "{} of String => String".to_string(),
        // Class types we emit ourselves get a .new; stdlib Time gets
        // Time.utc; anything else falls back to .new and trusts the
        // class defines a zero-arg initializer.
        Ty::Class { id, .. } => match id.0.as_str() {
            "Time" => "Time.utc".to_string(),
            other => format!("{other}.new"),
        },
        _ => "nil".to_string(),
    }
}

fn emit_model_method(out: &mut String, m: &MethodDef) {
    let name = m.name.as_str();
    let ret = m.body.ty.clone().unwrap_or(Ty::Nil);
    let ret_annot = format!(" : {}", crystal_ty(&ret));
    let receiver = match m.receiver {
        crate::dialect::MethodReceiver::Instance => "",
        crate::dialect::MethodReceiver::Class => "self.",
    };
    let params = if m.params.is_empty() {
        String::new()
    } else {
        let ps: Vec<String> = m.params.iter().map(|p| p.to_string()).collect();
        format!("({})", ps.join(", "))
    };
    writeln!(out, "  def {receiver}{name}{params}{ret_annot}").unwrap();
    let body = emit_body(&m.body);
    for line in body.lines() {
        writeln!(out, "    {line}").unwrap();
    }
    writeln!(out, "  end").unwrap();
}

// Controllers ----------------------------------------------------------

fn emit_controllers(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    for (i, controller) in app.controllers.iter().enumerate() {
        if i > 0 {
            writeln!(s).unwrap();
        }
        emit_controller(&mut s, controller);
    }
    EmittedFile { path: PathBuf::from("src/controllers.cr"), content: s }
}

fn emit_controller(out: &mut String, c: &Controller) {
    let name = c.name.0.as_str();
    writeln!(out, "class {name}").unwrap();
    for (i, action) in c.actions().enumerate() {
        if i > 0 {
            writeln!(out).unwrap();
        }
        emit_action(out, action);
    }
    writeln!(out, "end").unwrap();
}

fn emit_action(out: &mut String, a: &Action) {
    let name = a.name.as_str();
    let ret = action_return_type(&a.body);
    let ret_annot = match &ret {
        // Crystal's void return type is `Nil` (capital N — the type,
        // not the literal).
        Ty::Nil => " : Nil".to_string(),
        other => format!(" : {}", crystal_ty(other)),
    };
    writeln!(out, "  def {name}{ret_annot}").unwrap();
    let body = emit_body(&a.body);
    for line in body.lines() {
        writeln!(out, "    {line}").unwrap();
    }
    writeln!(out, "  end").unwrap();
}

fn action_return_type(body: &Expr) -> Ty {
    match &*body.node {
        ExprNode::Assign { value, .. } => value.ty.clone().unwrap_or(Ty::Nil),
        ExprNode::Seq { exprs } => exprs
            .last()
            .and_then(|e| match &*e.node {
                ExprNode::Assign { value, .. } => value.ty.clone(),
                _ => e.ty.clone(),
            })
            .unwrap_or(Ty::Nil),
        _ => body.ty.clone().unwrap_or(Ty::Nil),
    }
}

// Routes ---------------------------------------------------------------

fn emit_routes(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "ROUTES = [").unwrap();
    let mut flat: Vec<(String, String, String, String)> = Vec::new();
    for entry in &app.routes.entries {
        collect_flat_routes(entry, &mut flat, None);
    }
    for (method, path, controller, action) in flat {
        writeln!(
            s,
            "  {{method: :{}, path: {:?}, controller: {:?}, action: :{}}},",
            method.to_lowercase(),
            path,
            controller,
            action,
        )
        .unwrap();
    }
    writeln!(s, "]").unwrap();
    EmittedFile { path: PathBuf::from("src/routes.cr"), content: s }
}

fn collect_flat_routes(
    spec: &RouteSpec,
    out: &mut Vec<(String, String, String, String)>,
    scope_prefix: Option<(&str, &str)>,
) {
    match spec {
        RouteSpec::Explicit { method, path, controller, action, .. } => {
            let verb = match method {
                crate::dialect::HttpMethod::Get => "GET",
                crate::dialect::HttpMethod::Post => "POST",
                crate::dialect::HttpMethod::Put => "PUT",
                crate::dialect::HttpMethod::Patch => "PATCH",
                crate::dialect::HttpMethod::Delete => "DELETE",
                crate::dialect::HttpMethod::Head => "HEAD",
                crate::dialect::HttpMethod::Options => "OPTIONS",
                crate::dialect::HttpMethod::Any => "ANY",
            };
            let full_path = match scope_prefix {
                Some((parent, _)) => format!("/{parent}/:{parent}_id{path}"),
                None => path.clone(),
            };
            out.push((
                verb.to_string(),
                full_path,
                controller.0.to_string(),
                action.to_string(),
            ));
        }
        RouteSpec::Root { target } => {
            if let Some((c, a)) = target.split_once('#') {
                out.push(("GET".into(), "/".into(), controller_class_name(c), a.into()));
            }
        }
        RouteSpec::Resources { name, only, except, nested } => {
            let resource_path = format!("/{name}");
            let controller = controller_class_name(name.as_str());
            for (action, verb, suffix) in standard_resource_actions() {
                let action = *action;
                let verb = *verb;
                let suffix = *suffix;
                if !only.is_empty() && !only.iter().any(|s| s.as_str() == action) {
                    continue;
                }
                if except.iter().any(|s| s.as_str() == action) {
                    continue;
                }
                let path = format!("{resource_path}{suffix}");
                let full_path = match scope_prefix {
                    Some((parent, _)) => format!("/{parent}/:{parent}_id{path}"),
                    None => path,
                };
                out.push((verb.into(), full_path, controller.clone(), action.into()));
            }
            let singular =
                crate::naming::singularize_camelize(name.as_str()).to_lowercase();
            for child in nested {
                collect_flat_routes(child, out, Some((&singular, name.as_str())));
            }
        }
    }
}

fn standard_resource_actions() -> &'static [(&'static str, &'static str, &'static str)] {
    &[
        ("index", "GET", ""),
        ("new", "GET", "/new"),
        ("create", "POST", ""),
        ("show", "GET", "/:id"),
        ("edit", "GET", "/:id/edit"),
        ("update", "PATCH", "/:id"),
        ("destroy", "DELETE", "/:id"),
    ]
}

fn controller_class_name(short: &str) -> String {
    let mut s = crate::naming::camelize(short);
    s.push_str("Controller");
    s
}

// Bodies + expressions -------------------------------------------------

fn emit_body(body: &Expr) -> String {
    match &*body.node {
        ExprNode::Seq { exprs } if !exprs.is_empty() => {
            let mut lines: Vec<String> = Vec::new();
            for (i, e) in exprs.iter().enumerate() {
                if i > 0 && e.leading_blank_line {
                    lines.push(String::new());
                }
                lines.push(emit_stmt(e));
            }
            lines.join("\n")
        }
        _ => emit_stmt(body),
    }
}

fn emit_stmt(e: &Expr) -> String {
    match &*e.node {
        ExprNode::Assign { target: LValue::Var { name, .. }, value } => {
            format!("{} = {}", name, emit_expr(value))
        }
        ExprNode::Assign { target: LValue::Ivar { name }, value } => {
            format!("@{} = {}", name, emit_expr(value))
        }
        _ => emit_expr(e),
    }
}

fn emit_expr(e: &Expr) -> String {
    match &*e.node {
        ExprNode::Lit { value } => emit_literal(value),
        ExprNode::Const { path } => {
            path.iter().map(|s| s.to_string()).collect::<Vec<_>>().join("::")
        }
        ExprNode::Var { name, .. } => name.to_string(),
        ExprNode::Ivar { name } => format!("@{name}"),
        ExprNode::Send { recv, method, args, .. } => {
            emit_send(recv.as_ref(), method.as_str(), args)
        }
        ExprNode::Assign { target: _, value } => emit_expr(value),
        ExprNode::Seq { exprs } => {
            exprs.iter().map(emit_expr).collect::<Vec<_>>().join("; ")
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            // Crystal's if/else/end is identical to Ruby's.
            let cond_s = emit_expr(cond);
            let then_s = emit_body(then_branch);
            let else_s = emit_body(else_branch);
            format!(
                "if {cond_s}\n{}\nelse\n{}\nend",
                indent(&then_s, 1),
                indent(&else_s, 1),
            )
        }
        ExprNode::BoolOp { op, left, right, .. } => {
            use crate::expr::{BoolOpKind, BoolOpSurface};
            // Crystal supports both `&&` / `||` and `and` / `or` — we
            // preserve the surface form from the IR the same way the
            // Ruby emitter does.
            let op_s = match (op, &e.node) {
                (BoolOpKind::Or, _) => {
                    if let ExprNode::BoolOp { surface: BoolOpSurface::Word, .. } = &*e.node {
                        "or"
                    } else {
                        "||"
                    }
                }
                (BoolOpKind::And, _) => {
                    if let ExprNode::BoolOp { surface: BoolOpSurface::Word, .. } = &*e.node {
                        "and"
                    } else {
                        "&&"
                    }
                }
            };
            format!("{} {op_s} {}", emit_expr(left), emit_expr(right))
        }
        ExprNode::Array { elements, .. } => {
            let parts: Vec<String> = elements.iter().map(emit_expr).collect();
            format!("[{}]", parts.join(", "))
        }
        ExprNode::Hash { entries, .. } => {
            let parts: Vec<String> = entries
                .iter()
                .map(|(k, v)| {
                    if let ExprNode::Lit { value: Literal::Sym { value } } = &*k.node {
                        format!("{value}: {}", emit_expr(v))
                    } else {
                        format!("{} => {}", emit_expr(k), emit_expr(v))
                    }
                })
                .collect();
            format!("{{{}}}", parts.join(", "))
        }
        ExprNode::StringInterp { parts } => {
            // Crystal interpolation is identical to Ruby's.
            use crate::expr::InterpPart;
            let mut out = String::from("\"");
            for p in parts {
                match p {
                    InterpPart::Text { value } => {
                        for c in value.chars() {
                            match c {
                                '"' => out.push_str("\\\""),
                                '\\' => out.push_str("\\\\"),
                                '\n' => out.push_str("\\n"),
                                '#' => out.push_str("\\#"),
                                other => out.push(other),
                            }
                        }
                    }
                    InterpPart::Expr { expr } => {
                        out.push_str("#{");
                        out.push_str(&emit_expr(expr));
                        out.push('}');
                    }
                }
            }
            out.push('"');
            out
        }
        ExprNode::Yield { args } => {
            let parts: Vec<String> = args.iter().map(emit_expr).collect();
            if parts.is_empty() {
                "yield".to_string()
            } else {
                format!("yield {}", parts.join(", "))
            }
        }
        other => format!("# TODO: emit {:?}", std::mem::discriminant(other)),
    }
}

fn emit_send(recv: Option<&Expr>, method: &str, args: &[Expr]) -> String {
    let args_s: Vec<String> = args.iter().map(emit_expr).collect();
    if method == "[]" && recv.is_some() {
        return format!("{}[{}]", emit_expr(recv.unwrap()), args_s.join(", "));
    }
    match recv {
        None => {
            if args_s.is_empty() {
                method.to_string()
            } else {
                format!("{}({})", method, args_s.join(", "))
            }
        }
        Some(r) => {
            let recv_s = emit_expr(r);
            if args_s.is_empty() {
                format!("{recv_s}.{method}")
            } else {
                format!("{recv_s}.{method}({})", args_s.join(", "))
            }
        }
    }
}

fn emit_literal(lit: &Literal) -> String {
    match lit {
        Literal::Nil => "nil".to_string(),
        Literal::Bool { value } => value.to_string(),
        Literal::Int { value } => value.to_string(),
        Literal::Float { value } => {
            let s = value.to_string();
            if s.contains('.') { s } else { format!("{s}.0") }
        }
        Literal::Str { value } => format!("{value:?}"),
        // Crystal has first-class symbols just like Ruby.
        Literal::Sym { value } => format!(":{}", value.as_str()),
    }
}

fn indent(text: &str, depth: usize) -> String {
    let pad = "  ".repeat(depth);
    text.lines()
        .map(|l| if l.is_empty() { String::new() } else { format!("{pad}{l}") })
        .collect::<Vec<_>>()
        .join("\n")
}

// Types ----------------------------------------------------------------

pub fn crystal_ty(ty: &Ty) -> String {
    match ty {
        // Crystal's default integer is Int32; Rails schemas typically
        // use BigInt for IDs, so Int64 is the safer default for the
        // scaffold.
        Ty::Int => "Int64".to_string(),
        Ty::Float => "Float64".to_string(),
        Ty::Bool => "Bool".to_string(),
        Ty::Str => "String".to_string(),
        // Crystal has native Symbol.
        Ty::Sym => "Symbol".to_string(),
        Ty::Nil => "Nil".to_string(),
        Ty::Array { elem } => format!("Array({})", crystal_ty(elem)),
        Ty::Hash { key, value } => format!("Hash({}, {})", crystal_ty(key), crystal_ty(value)),
        Ty::Tuple { elems } => {
            let parts: Vec<String> = elems.iter().map(crystal_ty).collect();
            format!("Tuple({})", parts.join(", "))
        }
        Ty::Record { .. } => "Hash(String, String)".to_string(),
        Ty::Union { variants } => {
            // Crystal union: `A | B | C`.
            let parts: Vec<String> = variants.iter().map(crystal_ty).collect();
            parts.join(" | ")
        }
        Ty::Class { id, .. } => id.0.to_string(),
        Ty::Fn { .. } => "Proc(Nil)".to_string(),
        Ty::Var { .. } => "_".to_string(),
    }
}

// Fixtures + specs ----------------------------------------------------

/// Emit one fixture file as `spec/fixtures/<table>.cr` — a `Fixtures::X`
/// module with one `self.<label>` accessor per fixture record. IDs
/// assigned in insertion order (1..N), matching the Rust emitter.
fn emit_crystal_fixture(lowered: &crate::lower::LoweredFixture) -> EmittedFile {
    let fixture_name = lowered.name.as_str();
    let class_name = lowered.class.0.as_str();
    let module_name = crate::naming::camelize(fixture_name);

    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "require \"../../src/app\"").unwrap();
    writeln!(s, "require \"../fixtures\"").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "module Fixtures").unwrap();
    writeln!(s, "  module {module_name}").unwrap();

    // `_load_all` — called from Fixtures.setup. Builds each record
    // through the model's `save` (so validations apply), captures
    // the AUTOINCREMENT id, registers it with the shared lookup map.
    writeln!(s, "    def self._load_all").unwrap();
    for record in &lowered.records {
        let label = record.label.as_str();
        writeln!(s, "      record = {class_name}.new").unwrap();
        for field in &record.fields {
            let col = field.column.as_str();
            let val = match &field.value {
                crate::lower::LoweredFixtureValue::Literal { ty, raw } => {
                    crystal_literal_for(raw, ty)
                }
                crate::lower::LoweredFixtureValue::FkLookup {
                    target_fixture,
                    target_label,
                } => format!(
                    "Fixtures.fixture_id({:?}, {:?})",
                    target_fixture.as_str(),
                    target_label.as_str(),
                ),
            };
            writeln!(s, "      record.{col} = {val}").unwrap();
        }
        writeln!(
            s,
            "      raise \"fixture {fixture_name}/{label} failed to save\" unless record.save",
        )
        .unwrap();
        writeln!(
            s,
            "      Fixtures::FIXTURE_IDS[{{{fixture_name:?}, {label:?}}}] = record.id",
        )
        .unwrap();
    }
    writeln!(s, "    end").unwrap();

    // Named getters — `Fixtures::Articles.one` reads the record this
    // thread's `_load_all` inserted. A nil `find` means the spec's
    // before_each didn't fire.
    for record in &lowered.records {
        let label = record.label.as_str();
        writeln!(s).unwrap();
        writeln!(s, "    def self.{label} : {class_name}").unwrap();
        writeln!(
            s,
            "      id = Fixtures.fixture_id({fixture_name:?}, {label:?})",
        )
        .unwrap();
        writeln!(
            s,
            "      {class_name}.find(id).not_nil!"
        )
        .unwrap();
        writeln!(s, "    end").unwrap();
    }
    writeln!(s, "  end").unwrap();
    writeln!(s, "end").unwrap();

    EmittedFile {
        path: PathBuf::from(format!("spec/fixtures/{fixture_name}.cr")),
        content: s,
    }
}

/// `spec/fixtures.cr` — top-level `Fixtures` module that owns the
/// `(fixture_name, label) → id` lookup and the `setup` entrypoint
/// every spec's `before_each` calls. Per-class submodules reopen
/// `Fixtures` in `spec/fixtures/<table>.cr`.
fn emit_fixtures_helper(lowered: &crate::lower::LoweredFixtureSet) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "require \"../src/app\"").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "module Fixtures").unwrap();
    writeln!(s, "  FIXTURE_IDS = {{}} of {{String, String}} => Int64").unwrap();
    writeln!(s).unwrap();
    writeln!(
        s,
        "  # Per-spec entry point. Opens a fresh :memory: SQLite\n  # connection, runs the schema DDL, and loads every fixture in\n  # declaration order. Idempotent across repeat calls.",
    )
    .unwrap();
    writeln!(s, "  def self.setup").unwrap();
    writeln!(
        s,
        "    Roundhouse::Db.setup_test_db(Roundhouse::SchemaSQL::CREATE_TABLES)"
    )
    .unwrap();
    writeln!(s, "    FIXTURE_IDS.clear").unwrap();
    for f in &lowered.fixtures {
        let mod_name = crate::naming::camelize(f.name.as_str());
        writeln!(s, "    {mod_name}._load_all").unwrap();
    }
    writeln!(s, "  end").unwrap();
    writeln!(s).unwrap();
    writeln!(
        s,
        "  def self.fixture_id(fixture : String, label : String) : Int64",
    )
    .unwrap();
    writeln!(s, "    FIXTURE_IDS[{{fixture, label}}]").unwrap();
    writeln!(s, "  end").unwrap();
    writeln!(s, "end").unwrap();
    EmittedFile {
        path: PathBuf::from("spec/fixtures.cr"),
        content: s,
    }
}

fn crystal_literal_for(value: &str, ty: &Ty) -> String {
    match ty {
        Ty::Str | Ty::Sym => format!("{value:?}"),
        Ty::Int => {
            if value.parse::<i64>().is_ok() {
                format!("{value}_i64")
            } else {
                format!("0_i64 # TODO: coerce {value:?}")
            }
        }
        Ty::Float => {
            if value.parse::<f64>().is_ok() {
                format!("{value}_f64")
            } else {
                format!("0.0_f64 # TODO: coerce {value:?}")
            }
        }
        Ty::Bool => match value {
            "true" | "1" => "true".into(),
            "false" | "0" => "false".into(),
            _ => format!("false # TODO: coerce {value:?}"),
        },
        Ty::Class { id, .. } if id.0.as_str() == "Time" => format!("{value:?}"),
        _ => format!("{value:?}"),
    }
}

fn emit_spec_helper(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "require \"spec\"").unwrap();
    writeln!(s, "require \"../src/app\"").unwrap();
    if !app.fixtures.is_empty() {
        writeln!(s, "require \"./fixtures\"").unwrap();
    }
    for fixture in &app.fixtures {
        writeln!(s, "require \"./fixtures/{}\"", fixture.name).unwrap();
    }
    if !app.fixtures.is_empty() {
        writeln!(s).unwrap();
        // Fresh :memory: DB + reloaded fixtures before every spec,
        // mirroring Rails' transactional-fixture isolation.
        writeln!(s, "Spec.before_each do").unwrap();
        writeln!(s, "  Fixtures.setup").unwrap();
        writeln!(s, "end").unwrap();
    }
    EmittedFile {
        path: PathBuf::from("spec/spec_helper.cr"),
        content: s,
    }
}

fn emit_crystal_spec(tm: &TestModule, app: &App) -> EmittedFile {
    // Target class: Article for ArticleTest. Used as the `describe`
    // subject so the spec output reads naturally.
    let subject = tm
        .target
        .as_ref()
        .map(|c| c.0.as_str().to_string())
        .unwrap_or_else(|| tm.name.0.as_str().to_string());

    let fixture_names: Vec<Symbol> =
        app.fixtures.iter().map(|f| f.name.clone()).collect();
    let known_models: Vec<Symbol> =
        app.models.iter().map(|m| m.name.0.clone()).collect();
    let mut attrs_set: std::collections::BTreeSet<Symbol> =
        std::collections::BTreeSet::new();
    for m in &app.models {
        for attr in m.attributes.fields.keys() {
            attrs_set.insert(attr.clone());
        }
    }
    let model_attrs: Vec<Symbol> = attrs_set.into_iter().collect();

    let ctx = SpecCtx {
        app,
        fixture_names: &fixture_names,
        known_models: &known_models,
        model_attrs: &model_attrs,
    };

    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "require \"../spec_helper\"").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "describe {subject} do").unwrap();

    for test in &tm.tests {
        if test_needs_runtime_unsupported_cr(test) {
            writeln!(
                s,
                "  pending {:?} do",
                test.name
            )
            .unwrap();
            writeln!(s, "    # Phase 3: needs persistence runtime").unwrap();
            writeln!(s, "  end").unwrap();
        } else {
            writeln!(s, "  it {:?} do", test.name).unwrap();
            for line in emit_spec_body(&test.body, ctx).lines() {
                writeln!(s, "    {line}").unwrap();
            }
            writeln!(s, "  end").unwrap();
        }
    }

    writeln!(s, "end").unwrap();

    let filename = crate::naming::snake_case(tm.name.0.as_str());
    // spec/models/article_spec.cr from ArticleTest.
    let filename = filename.replace("_test", "_spec");
    EmittedFile {
        path: PathBuf::from(format!("spec/models/{filename}.cr")),
        content: s,
    }
}

/// Context threaded through spec body emission.
#[derive(Clone, Copy)]
struct SpecCtx<'a> {
    app: &'a App,
    fixture_names: &'a [Symbol],
    known_models: &'a [Symbol],
    model_attrs: &'a [Symbol],
}

/// Top-level emit for a test body — a `Seq` renders line by line; a
/// single expression renders as one line.
fn emit_spec_body(body: &Expr, ctx: SpecCtx) -> String {
    match &*body.node {
        ExprNode::Seq { exprs } if !exprs.is_empty() => exprs
            .iter()
            .map(|e| emit_spec_stmt(e, ctx))
            .collect::<Vec<_>>()
            .join("\n"),
        _ => emit_spec_stmt(body, ctx),
    }
}

fn emit_spec_stmt(e: &Expr, ctx: SpecCtx) -> String {
    match &*e.node {
        ExprNode::Assign { target: LValue::Var { name, .. }, value } => {
            format!("{} = {}", name, emit_spec_expr(value, ctx))
        }
        _ => emit_spec_expr(e, ctx),
    }
}

fn emit_spec_expr(e: &Expr, ctx: SpecCtx) -> String {
    use crate::expr::InterpPart;
    match &*e.node {
        ExprNode::Lit { value } => emit_literal(value),
        ExprNode::Var { name, .. } => name.to_string(),
        ExprNode::Const { path } => {
            path.iter().map(|s| s.to_string()).collect::<Vec<_>>().join("::")
        }
        ExprNode::Hash { entries, .. } => {
            let parts: Vec<String> = entries
                .iter()
                .map(|(k, v)| {
                    format!("{} => {}", emit_spec_expr(k, ctx), emit_spec_expr(v, ctx))
                })
                .collect();
            format!("{{{}}}", parts.join(", "))
        }
        ExprNode::Array { elements, .. } => {
            let parts: Vec<String> = elements.iter().map(|e| emit_spec_expr(e, ctx)).collect();
            format!("[{}]", parts.join(", "))
        }
        ExprNode::StringInterp { parts } => {
            let mut out = String::from("\"");
            for p in parts {
                match p {
                    InterpPart::Text { value } => out.push_str(value),
                    InterpPart::Expr { expr } => {
                        out.push_str("#{");
                        out.push_str(&emit_spec_expr(expr, ctx));
                        out.push('}');
                    }
                }
            }
            out.push('"');
            out
        }
        ExprNode::Send { recv, method, args, block, .. } => {
            emit_spec_send(recv.as_ref(), method.as_str(), args, block.as_ref(), ctx)
        }
        ExprNode::BoolOp { op, left, right, .. } => {
            use crate::expr::BoolOpKind;
            let op_s = match op {
                BoolOpKind::Or => "||",
                BoolOpKind::And => "&&",
            };
            format!(
                "{} {} {}",
                emit_spec_expr(left, ctx),
                op_s,
                emit_spec_expr(right, ctx)
            )
        }
        ExprNode::Assign { target, value } => {
            // Only in rare inline positions; renders as a Crystal
            // assignment expression.
            let v = emit_spec_expr(value, ctx);
            match target {
                LValue::Var { name, .. } => format!("{name} = {v}"),
                LValue::Ivar { name } => format!("@{name} = {v}"),
                _ => v,
            }
        }
        _ => format!("# TODO: spec emit for {:?}", std::mem::discriminant(&*e.node)),
    }
}

fn emit_spec_send(
    recv: Option<&Expr>,
    method: &str,
    args: &[Expr],
    block: Option<&Expr>,
    ctx: SpecCtx,
) -> String {
    let args_s: Vec<String> = args.iter().map(|a| emit_spec_expr(a, ctx)).collect();

    // Fixture accessor: articles(:one) → Fixtures::Articles.one
    if recv.is_none()
        && args.len() == 1
        && ctx.fixture_names.iter().any(|s| s.as_str() == method)
    {
        if let ExprNode::Lit { value: Literal::Sym { value: sym } } = &*args[0].node {
            let module_name = crate::naming::camelize(method);
            return format!("Fixtures::{module_name}.{}", sym.as_str());
        }
    }

    // assert_difference("Class.count", delta) do ... end
    if recv.is_none() && method == "assert_difference" {
        if let Some(body) = block {
            if let Some(count_expr) = args
                .first()
                .and_then(|a| match &*a.node {
                    ExprNode::Lit { value: Literal::Str { value } } => {
                        rewrite_ruby_dot_call_cr(value)
                    }
                    _ => None,
                })
            {
                let delta = args_s.get(1).cloned().unwrap_or_else(|| "1_i64".into());
                let body_s = emit_block_body_cr(body, ctx);
                return format!(
                    "_before = {count_expr}\n    {body_s}\n    ({count_expr} - _before).should eq({delta})"
                );
            }
        }
    }

    // owner.<assoc>.create(hash) / .build(hash) — HasMany rewrite.
    if (method == "create" || method == "build") && args.len() == 1 {
        if let Some(outer_recv) = recv {
            if let ExprNode::Send {
                recv: Some(assoc_recv),
                method: assoc_method,
                args: inner_args,
                ..
            } = &*outer_recv.node
            {
                if inner_args.is_empty() {
                    if let Some(s) = try_emit_assoc_create_cr(
                        assoc_recv,
                        assoc_method.as_str(),
                        args,
                        method,
                        ctx,
                    ) {
                        return s;
                    }
                }
            }
        }
    }

    // Assertion macros → Crystal spec's `should` matchers.
    // Ruby's `assert_equal expected, actual` → `actual.should eq(expected)`.
    if recv.is_none() {
        match (method, args_s.len()) {
            ("assert_equal", 2) => {
                return format!("{}.should eq({})", args_s[1], args_s[0]);
            }
            ("assert_not_equal", 2) => {
                return format!("{}.should_not eq({})", args_s[1], args_s[0]);
            }
            ("assert_not", 1) => {
                return format!("{}.should be_false", args_s[0]);
            }
            ("assert", 1) => {
                return format!("{}.should be_true", args_s[0]);
            }
            ("assert_nil", 1) => {
                return format!("{}.should be_nil", args_s[0]);
            }
            ("assert_not_nil", 1) => {
                return format!("{}.should_not be_nil", args_s[0]);
            }
            _ => {}
        }
    }

    // `Class.new(hash)` → Crystal requires setting properties after .new.
    // Use `.tap do |r| r.k = v end` pattern when the target is a known
    // model.
    if let Some(r) = recv {
        if method == "new" && args.len() == 1 {
            if let ExprNode::Const { path } = &*r.node {
                if let Some(class_name) = path.last() {
                    if ctx.known_models.iter().any(|s| s == class_name) {
                        if let ExprNode::Hash { entries, .. } = &*args[0].node {
                            let mut lines: Vec<String> =
                                vec![format!("{class_name}.new.tap do |record|")];
                            for (k, v) in entries {
                                if let ExprNode::Lit {
                                    value: Literal::Sym { value: f },
                                } = &*k.node
                                {
                                    lines.push(format!(
                                        "      record.{} = {}",
                                        f.as_str(),
                                        emit_spec_expr(v, ctx)
                                    ));
                                }
                            }
                            lines.push("    end".to_string());
                            return lines.join("\n");
                        }
                    }
                }
            }
        }
    }

    match recv {
        None => {
            if args_s.is_empty() {
                method.to_string()
            } else {
                format!("{}({})", method, args_s.join(", "))
            }
        }
        Some(r) => {
            let recv_s = emit_spec_expr(r, ctx);
            let is_class_call = matches!(&*r.node, ExprNode::Const { .. });
            let sep = if is_class_call { "." } else { "." };
            // Crystal doesn't distinguish field vs method call syntactically
            // (property getters ARE method calls), so we can emit both as
            // `recv.method` regardless — but attribute reads should be
            // bare, no parens.
            let is_attr_read = !is_class_call
                && args_s.is_empty()
                && ctx.model_attrs.iter().any(|s| s.as_str() == method);
            if is_attr_read {
                format!("{recv_s}{sep}{method}")
            } else if args_s.is_empty() {
                // Crystal allows omitting parens for zero-arg calls;
                // keep them off for consistency with Ruby idiom.
                format!("{recv_s}{sep}{method}")
            } else {
                format!("{recv_s}{sep}{method}({})", args_s.join(", "))
            }
        }
    }
}

/// Phase 3 rounded out the Crystal emitter's handling of
/// assert_difference, destroy, Class.count, build/create, and
/// belongs_to existence. Keep the predicate as a future-guard; no
/// real-blog shape currently forces a skip.
fn test_needs_runtime_unsupported_cr(_test: &Test) -> bool {
    false
}

/// Parse a Ruby-style `"Class.method"` expression string into Crystal
/// `Class.method` syntax (Crystal uses `.` for both class and instance
/// method calls). Only alphanumeric identifiers on both sides.
fn rewrite_ruby_dot_call_cr(expr: &str) -> Option<String> {
    let trimmed = expr.trim();
    let (lhs, rhs) = trimmed.split_once('.')?;
    let is_ident = |s: &str| {
        !s.is_empty()
            && s.chars().next().is_some_and(|c| c.is_alphabetic() || c == '_')
            && s.chars().all(|c| c.is_alphanumeric() || c == '_')
    };
    if !is_ident(lhs) || !is_ident(rhs) {
        return None;
    }
    Some(format!("{lhs}.{rhs}"))
}

/// Render a Ruby block body (a single expression or a Seq) as Crystal
/// spec statements at spec-body indent. Peels one Lambda layer — Ruby
/// `do ... end` lowers to `ExprNode::Lambda` in the IR but translates
/// to plain statements in Crystal.
fn emit_block_body_cr(e: &Expr, ctx: SpecCtx) -> String {
    let inner = match &*e.node {
        ExprNode::Lambda { body, .. } => body,
        _ => e,
    };
    match &*inner.node {
        ExprNode::Seq { exprs } if !exprs.is_empty() => exprs
            .iter()
            .map(|s| emit_spec_stmt(s, ctx))
            .collect::<Vec<_>>()
            .join("\n    "),
        _ => emit_spec_stmt(inner, ctx),
    }
}

fn try_emit_assoc_create_cr(
    owner: &Expr,
    assoc_name: &str,
    args: &[Expr],
    outer_method: &str,
    ctx: SpecCtx,
) -> Option<String> {
    let resolved = crate::lower::resolve_has_many(
        &Symbol::from(assoc_name),
        owner.ty.as_ref(),
        ctx.app,
    )?;
    let target_class = resolved.target_class.0.as_str();
    let foreign_key = resolved.foreign_key.as_str();

    let owner_s = emit_spec_expr(owner, ctx);
    let hash_entries = match &args.first()?.node.as_ref() {
        ExprNode::Hash { entries, .. } => entries.clone(),
        _ => return None,
    };

    let mut lines: Vec<String> = Vec::new();
    lines.push(format!("{target_class}.new.tap do |record|"));
    lines.push(format!("      record.{foreign_key} = {owner_s}.id"));
    for (k, v) in &hash_entries {
        if let ExprNode::Lit { value: Literal::Sym { value: field_name } } = &*k.node {
            lines.push(format!(
                "      record.{} = {}",
                field_name.as_str(),
                emit_spec_expr(v, ctx),
            ));
        }
    }
    // `.build` returns the unsaved record; `.create` saves it first.
    // Both yield the record so tests can read `.article_id` etc.
    if outer_method == "create" {
        lines.push("      record.save".to_string());
    }
    lines.push("    end".to_string());
    Some(lines.join("\n"))
}

#[allow(dead_code)]
fn test_body_uses_unsupported_cr(e: &Expr) -> bool {
    use crate::expr::InterpPart;
    let self_hit = false;
    if self_hit {
        return true;
    }
    match &*e.node {
        ExprNode::Send { recv, args, block, .. } => {
            if let Some(r) = recv {
                if test_body_uses_unsupported_cr(r) {
                    return true;
                }
            }
            for a in args {
                if test_body_uses_unsupported_cr(a) {
                    return true;
                }
            }
            if let Some(b) = block {
                if test_body_uses_unsupported_cr(b) {
                    return true;
                }
            }
        }
        ExprNode::Seq { exprs } | ExprNode::Array { elements: exprs, .. } => {
            for e in exprs {
                if test_body_uses_unsupported_cr(e) {
                    return true;
                }
            }
        }
        ExprNode::Hash { entries, .. } => {
            for (k, v) in entries {
                if test_body_uses_unsupported_cr(k) || test_body_uses_unsupported_cr(v) {
                    return true;
                }
            }
        }
        ExprNode::StringInterp { parts } => {
            for p in parts {
                if let InterpPart::Expr { expr } = p {
                    if test_body_uses_unsupported_cr(expr) {
                        return true;
                    }
                }
            }
        }
        ExprNode::BoolOp { left, right, .. }
        | ExprNode::RescueModifier { expr: left, fallback: right } => {
            if test_body_uses_unsupported_cr(left) || test_body_uses_unsupported_cr(right) {
                return true;
            }
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            if test_body_uses_unsupported_cr(cond)
                || test_body_uses_unsupported_cr(then_branch)
                || test_body_uses_unsupported_cr(else_branch)
            {
                return true;
            }
        }
        ExprNode::Let { value, body, .. } => {
            if test_body_uses_unsupported_cr(value) || test_body_uses_unsupported_cr(body) {
                return true;
            }
        }
        ExprNode::Lambda { body, .. } => {
            if test_body_uses_unsupported_cr(body) {
                return true;
            }
        }
        ExprNode::Assign { value, .. } => {
            if test_body_uses_unsupported_cr(value) {
                return true;
            }
        }
        _ => {}
    }
    false
}
