//! Crystal emitter.
//!
//! Last Phase 2 scaffold. Crystal is Ruby-flavored with mandatory
//! static types, which makes this the easiest scaffold of the six —
//! the emission shape is almost identical to Ruby's, plus type
//! annotations.
//!
//! Scaffold choices:
//! - Models as `class Name` with typed `property :field : Type`
//!   declarations (Crystal's getter/setter macro).
//! - Controllers as `class Name` with one method per action. No
//!   `< Kemal::Controller` base — Phase 3+ runtime work picks.
//! - Routes as a `ROUTES` constant with a NamedTuple array —
//!   Crystal's idiomatic static table shape.
//!
//! Notably not mirrored from railcar:
//! - Railcar's Crystal output uses a heavy macro DSL
//!   (`model("articles") do column(title, String) end`) to hook
//!   into its runtime. That's a Phase-4-depth choice; our scaffold
//!   stays runtime-agnostic.

use std::fmt::Write;
use std::path::PathBuf;

use super::EmittedFile;
use crate::App;
use crate::dialect::{
    Action, Association, Controller, Fixture, MethodDef, Model, RouteSpec, Test, TestModule,
};
use crate::expr::{Expr, ExprNode, LValue, Literal};
use crate::ident::Symbol;
use crate::ty::Ty;

const RUNTIME_SOURCE: &str = include_str!("../../runtime/crystal/runtime.cr");

pub fn emit(app: &App) -> Vec<EmittedFile> {
    let mut files = Vec::new();
    files.push(emit_shard_yml());
    if !app.models.is_empty() {
        files.push(emit_models(app));
        // Runtime tags along whenever any model is emitted — validate()
        // calls ValidationError.new.
        files.push(EmittedFile {
            path: PathBuf::from("src/runtime.cr"),
            content: RUNTIME_SOURCE.to_string(),
        });
    }
    if !app.controllers.is_empty() {
        files.push(emit_controllers(app));
    }
    if !app.routes.entries.is_empty() {
        files.push(emit_routes(app));
    }
    // Fixtures as modules under spec/fixtures/. Emitted as `pub mod`s
    // from spec_helper.cr when specs are present.
    if !app.fixtures.is_empty() {
        for fixture in &app.fixtures {
            files.push(emit_crystal_fixture(fixture, app));
        }
    }
    if !app.test_modules.is_empty() {
        for tm in &app.test_modules {
            files.push(emit_crystal_spec(tm, app));
        }
        files.push(emit_spec_helper(app));
    }
    files.push(emit_app_cr(app));
    files
}

/// Minimal `shard.yml` — Crystal's equivalent of `Cargo.toml`. Declares
/// one named `targets` entry so `crystal build` knows the entry point;
/// the entry file (`src/app.cr`) requires whatever modules we emitted.
fn emit_shard_yml() -> EmittedFile {
    let content = "\
name: app
version: 0.1.0

targets:
  app:
    main: src/app.cr
";
    EmittedFile {
        path: PathBuf::from("shard.yml"),
        content: content.to_string(),
    }
}

/// `src/app.cr` — Crystal entry point. Requires the emitted modules we
/// expect to compile. Phase 1 scope: models + runtime only. Controllers
/// + routes are emitted as files but not required, for the same reason
/// the Rust emitter keeps controllers out of `lib.rs`: their bodies
/// reference a Rails runtime that doesn't exist yet.
fn emit_app_cr(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    if !app.models.is_empty() {
        writeln!(s, "require \"./runtime\"").unwrap();
        writeln!(s, "require \"./models\"").unwrap();
    }
    EmittedFile {
        path: PathBuf::from("src/app.cr"),
        content: s,
    }
}

// Models ---------------------------------------------------------------

fn emit_models(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    for (i, model) in app.models.iter().enumerate() {
        if i > 0 {
            writeln!(s).unwrap();
        }
        emit_model(&mut s, model);
    }
    EmittedFile { path: PathBuf::from("src/models.cr"), content: s }
}

fn emit_model(out: &mut String, model: &Model) {
    let name = model.name.0.as_str();
    writeln!(out, "class {name}").unwrap();
    for (field, ty) in &model.attributes.fields {
        writeln!(
            out,
            "  property {} : {} = {}",
            field,
            crystal_ty(ty),
            crystal_default(ty),
        )
        .unwrap();
    }
    for method in model.methods() {
        writeln!(out).unwrap();
        emit_model_method(out, method);
    }
    let lowered = crate::lower::lower_validations(model);
    if !lowered.is_empty() {
        writeln!(out).unwrap();
        emit_validate_method(out, &lowered);
        writeln!(out).unwrap();
        // save() runs validation — matches Rails' non-persisting semantics
        // for now. Real save lands when a persistence adapter does.
        writeln!(out, "  def save : Bool").unwrap();
        writeln!(out, "    validate.empty?").unwrap();
        writeln!(out, "  end").unwrap();
    }
    writeln!(out, "end").unwrap();
}

fn emit_validate_method(
    out: &mut String,
    validations: &[crate::lower::LoweredValidation],
) {
    writeln!(out, "  def validate : Array(Roundhouse::ValidationError)").unwrap();
    writeln!(out, "    errors = [] of Roundhouse::ValidationError").unwrap();
    for lv in validations {
        for check in &lv.checks {
            emit_check_inline_cr(out, lv.attribute.as_str(), check);
        }
    }
    writeln!(out, "    errors").unwrap();
    writeln!(out, "  end").unwrap();
}

fn emit_check_inline_cr(out: &mut String, attr: &str, check: &crate::lower::Check) {
    use crate::lower::Check;
    let msg = check.default_message();
    let push = |cond: &str| -> String {
        format!(
            "    if {cond}\n      errors << Roundhouse::ValidationError.new({attr:?}, {msg:?})\n    end",
        )
    };
    let block = match check {
        Check::Presence => push(&format!("{attr}.empty?")),
        Check::Absence => push(&format!("!{attr}.empty?")),
        Check::MinLength { n } => push(&format!("{attr}.size < {n}")),
        Check::MaxLength { n } => push(&format!("{attr}.size > {n}")),
        Check::GreaterThan { threshold } => push(&format!("{attr} <= {threshold}")),
        Check::LessThan { threshold } => push(&format!("{attr} >= {threshold}")),
        Check::OnlyInteger => {
            format!("    # OnlyInteger on {attr:?} — enforced by Crystal's type system")
        }
        Check::Inclusion { values } => {
            let parts: Vec<String> = values.iter().map(inclusion_value_to_cr).collect();
            push(&format!("![{}].includes?({attr})", parts.join(", ")))
        }
        Check::Format { pattern } => {
            format!(
                "    # TODO: Format check on {attr:?} requires runtime regex ({pattern:?})"
            )
        }
        Check::Uniqueness { .. } => format!(
            "    # TODO: Uniqueness on {attr:?} requires DB access at runtime"
        ),
        Check::Custom { method } => format!("    {method}(errors)"),
    };
    writeln!(out, "{block}").unwrap();
}

fn inclusion_value_to_cr(v: &crate::lower::InclusionValue) -> String {
    use crate::lower::InclusionValue;
    match v {
        InclusionValue::Str { value } => format!("{value:?}"),
        InclusionValue::Int { value } => format!("{value}_i64"),
        InclusionValue::Float { value } => {
            let s = value.to_string();
            if s.contains('.') { format!("{s}_f64") } else { format!("{s}.0_f64") }
        }
        InclusionValue::Bool { value } => value.to_string(),
    }
}

/// A Crystal literal expression for the given type's zero value.
/// Crystal's `property` declarations must be initialized — unlike
/// Rust's `#[derive(Default)]` we have to write the value inline.
/// Keep aligned with `crystal_ty`: whatever a field renders as, its
/// default must be a valid expression of that type.
fn crystal_default(ty: &Ty) -> String {
    match ty {
        Ty::Int => "0_i64".to_string(),
        Ty::Float => "0.0_f64".to_string(),
        Ty::Bool => "false".to_string(),
        Ty::Str | Ty::Sym => "\"\"".to_string(),
        Ty::Nil => "nil".to_string(),
        Ty::Array { .. } => "[] of typeof({})".to_string(),
        Ty::Hash { .. } => "{} of String => String".to_string(),
        // Class types we emit ourselves get a .new; stdlib Time gets
        // Time.utc; anything else falls back to .new and trusts the
        // class defines a zero-arg initializer.
        Ty::Class { id, .. } => match id.0.as_str() {
            "Time" => "Time.utc".to_string(),
            other => format!("{other}.new"),
        },
        _ => "nil".to_string(),
    }
}

fn emit_model_method(out: &mut String, m: &MethodDef) {
    let name = m.name.as_str();
    let ret = m.body.ty.clone().unwrap_or(Ty::Nil);
    let ret_annot = format!(" : {}", crystal_ty(&ret));
    let receiver = match m.receiver {
        crate::dialect::MethodReceiver::Instance => "",
        crate::dialect::MethodReceiver::Class => "self.",
    };
    let params = if m.params.is_empty() {
        String::new()
    } else {
        let ps: Vec<String> = m.params.iter().map(|p| p.to_string()).collect();
        format!("({})", ps.join(", "))
    };
    writeln!(out, "  def {receiver}{name}{params}{ret_annot}").unwrap();
    let body = emit_body(&m.body);
    for line in body.lines() {
        writeln!(out, "    {line}").unwrap();
    }
    writeln!(out, "  end").unwrap();
}

// Controllers ----------------------------------------------------------

fn emit_controllers(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    for (i, controller) in app.controllers.iter().enumerate() {
        if i > 0 {
            writeln!(s).unwrap();
        }
        emit_controller(&mut s, controller);
    }
    EmittedFile { path: PathBuf::from("src/controllers.cr"), content: s }
}

fn emit_controller(out: &mut String, c: &Controller) {
    let name = c.name.0.as_str();
    writeln!(out, "class {name}").unwrap();
    for (i, action) in c.actions().enumerate() {
        if i > 0 {
            writeln!(out).unwrap();
        }
        emit_action(out, action);
    }
    writeln!(out, "end").unwrap();
}

fn emit_action(out: &mut String, a: &Action) {
    let name = a.name.as_str();
    let ret = action_return_type(&a.body);
    let ret_annot = match &ret {
        // Crystal's void return type is `Nil` (capital N — the type,
        // not the literal).
        Ty::Nil => " : Nil".to_string(),
        other => format!(" : {}", crystal_ty(other)),
    };
    writeln!(out, "  def {name}{ret_annot}").unwrap();
    let body = emit_body(&a.body);
    for line in body.lines() {
        writeln!(out, "    {line}").unwrap();
    }
    writeln!(out, "  end").unwrap();
}

fn action_return_type(body: &Expr) -> Ty {
    match &*body.node {
        ExprNode::Assign { value, .. } => value.ty.clone().unwrap_or(Ty::Nil),
        ExprNode::Seq { exprs } => exprs
            .last()
            .and_then(|e| match &*e.node {
                ExprNode::Assign { value, .. } => value.ty.clone(),
                _ => e.ty.clone(),
            })
            .unwrap_or(Ty::Nil),
        _ => body.ty.clone().unwrap_or(Ty::Nil),
    }
}

// Routes ---------------------------------------------------------------

fn emit_routes(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "ROUTES = [").unwrap();
    let mut flat: Vec<(String, String, String, String)> = Vec::new();
    for entry in &app.routes.entries {
        collect_flat_routes(entry, &mut flat, None);
    }
    for (method, path, controller, action) in flat {
        writeln!(
            s,
            "  {{method: :{}, path: {:?}, controller: {:?}, action: :{}}},",
            method.to_lowercase(),
            path,
            controller,
            action,
        )
        .unwrap();
    }
    writeln!(s, "]").unwrap();
    EmittedFile { path: PathBuf::from("src/routes.cr"), content: s }
}

fn collect_flat_routes(
    spec: &RouteSpec,
    out: &mut Vec<(String, String, String, String)>,
    scope_prefix: Option<(&str, &str)>,
) {
    match spec {
        RouteSpec::Explicit { method, path, controller, action, .. } => {
            let verb = match method {
                crate::dialect::HttpMethod::Get => "GET",
                crate::dialect::HttpMethod::Post => "POST",
                crate::dialect::HttpMethod::Put => "PUT",
                crate::dialect::HttpMethod::Patch => "PATCH",
                crate::dialect::HttpMethod::Delete => "DELETE",
                crate::dialect::HttpMethod::Head => "HEAD",
                crate::dialect::HttpMethod::Options => "OPTIONS",
                crate::dialect::HttpMethod::Any => "ANY",
            };
            let full_path = match scope_prefix {
                Some((parent, _)) => format!("/{parent}/:{parent}_id{path}"),
                None => path.clone(),
            };
            out.push((
                verb.to_string(),
                full_path,
                controller.0.to_string(),
                action.to_string(),
            ));
        }
        RouteSpec::Root { target } => {
            if let Some((c, a)) = target.split_once('#') {
                out.push(("GET".into(), "/".into(), controller_class_name(c), a.into()));
            }
        }
        RouteSpec::Resources { name, only, except, nested } => {
            let resource_path = format!("/{name}");
            let controller = controller_class_name(name.as_str());
            for (action, verb, suffix) in standard_resource_actions() {
                let action = *action;
                let verb = *verb;
                let suffix = *suffix;
                if !only.is_empty() && !only.iter().any(|s| s.as_str() == action) {
                    continue;
                }
                if except.iter().any(|s| s.as_str() == action) {
                    continue;
                }
                let path = format!("{resource_path}{suffix}");
                let full_path = match scope_prefix {
                    Some((parent, _)) => format!("/{parent}/:{parent}_id{path}"),
                    None => path,
                };
                out.push((verb.into(), full_path, controller.clone(), action.into()));
            }
            let singular =
                crate::naming::singularize_camelize(name.as_str()).to_lowercase();
            for child in nested {
                collect_flat_routes(child, out, Some((&singular, name.as_str())));
            }
        }
    }
}

fn standard_resource_actions() -> &'static [(&'static str, &'static str, &'static str)] {
    &[
        ("index", "GET", ""),
        ("new", "GET", "/new"),
        ("create", "POST", ""),
        ("show", "GET", "/:id"),
        ("edit", "GET", "/:id/edit"),
        ("update", "PATCH", "/:id"),
        ("destroy", "DELETE", "/:id"),
    ]
}

fn controller_class_name(short: &str) -> String {
    let mut s = crate::naming::camelize(short);
    s.push_str("Controller");
    s
}

// Bodies + expressions -------------------------------------------------

fn emit_body(body: &Expr) -> String {
    match &*body.node {
        ExprNode::Seq { exprs } if !exprs.is_empty() => {
            let mut lines: Vec<String> = Vec::new();
            for (i, e) in exprs.iter().enumerate() {
                if i > 0 && e.leading_blank_line {
                    lines.push(String::new());
                }
                lines.push(emit_stmt(e));
            }
            lines.join("\n")
        }
        _ => emit_stmt(body),
    }
}

fn emit_stmt(e: &Expr) -> String {
    match &*e.node {
        ExprNode::Assign { target: LValue::Var { name, .. }, value } => {
            format!("{} = {}", name, emit_expr(value))
        }
        ExprNode::Assign { target: LValue::Ivar { name }, value } => {
            format!("@{} = {}", name, emit_expr(value))
        }
        _ => emit_expr(e),
    }
}

fn emit_expr(e: &Expr) -> String {
    match &*e.node {
        ExprNode::Lit { value } => emit_literal(value),
        ExprNode::Const { path } => {
            path.iter().map(|s| s.to_string()).collect::<Vec<_>>().join("::")
        }
        ExprNode::Var { name, .. } => name.to_string(),
        ExprNode::Ivar { name } => format!("@{name}"),
        ExprNode::Send { recv, method, args, .. } => {
            emit_send(recv.as_ref(), method.as_str(), args)
        }
        ExprNode::Assign { target: _, value } => emit_expr(value),
        ExprNode::Seq { exprs } => {
            exprs.iter().map(emit_expr).collect::<Vec<_>>().join("; ")
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            // Crystal's if/else/end is identical to Ruby's.
            let cond_s = emit_expr(cond);
            let then_s = emit_body(then_branch);
            let else_s = emit_body(else_branch);
            format!(
                "if {cond_s}\n{}\nelse\n{}\nend",
                indent(&then_s, 1),
                indent(&else_s, 1),
            )
        }
        ExprNode::BoolOp { op, left, right, .. } => {
            use crate::expr::{BoolOpKind, BoolOpSurface};
            // Crystal supports both `&&` / `||` and `and` / `or` — we
            // preserve the surface form from the IR the same way the
            // Ruby emitter does.
            let op_s = match (op, &e.node) {
                (BoolOpKind::Or, _) => {
                    if let ExprNode::BoolOp { surface: BoolOpSurface::Word, .. } = &*e.node {
                        "or"
                    } else {
                        "||"
                    }
                }
                (BoolOpKind::And, _) => {
                    if let ExprNode::BoolOp { surface: BoolOpSurface::Word, .. } = &*e.node {
                        "and"
                    } else {
                        "&&"
                    }
                }
            };
            format!("{} {op_s} {}", emit_expr(left), emit_expr(right))
        }
        ExprNode::Array { elements, .. } => {
            let parts: Vec<String> = elements.iter().map(emit_expr).collect();
            format!("[{}]", parts.join(", "))
        }
        ExprNode::Hash { entries, .. } => {
            let parts: Vec<String> = entries
                .iter()
                .map(|(k, v)| {
                    if let ExprNode::Lit { value: Literal::Sym { value } } = &*k.node {
                        format!("{value}: {}", emit_expr(v))
                    } else {
                        format!("{} => {}", emit_expr(k), emit_expr(v))
                    }
                })
                .collect();
            format!("{{{}}}", parts.join(", "))
        }
        ExprNode::StringInterp { parts } => {
            // Crystal interpolation is identical to Ruby's.
            use crate::expr::InterpPart;
            let mut out = String::from("\"");
            for p in parts {
                match p {
                    InterpPart::Text { value } => {
                        for c in value.chars() {
                            match c {
                                '"' => out.push_str("\\\""),
                                '\\' => out.push_str("\\\\"),
                                '\n' => out.push_str("\\n"),
                                '#' => out.push_str("\\#"),
                                other => out.push(other),
                            }
                        }
                    }
                    InterpPart::Expr { expr } => {
                        out.push_str("#{");
                        out.push_str(&emit_expr(expr));
                        out.push('}');
                    }
                }
            }
            out.push('"');
            out
        }
        ExprNode::Yield { args } => {
            let parts: Vec<String> = args.iter().map(emit_expr).collect();
            if parts.is_empty() {
                "yield".to_string()
            } else {
                format!("yield {}", parts.join(", "))
            }
        }
        other => format!("# TODO: emit {:?}", std::mem::discriminant(other)),
    }
}

fn emit_send(recv: Option<&Expr>, method: &str, args: &[Expr]) -> String {
    let args_s: Vec<String> = args.iter().map(emit_expr).collect();
    if method == "[]" && recv.is_some() {
        return format!("{}[{}]", emit_expr(recv.unwrap()), args_s.join(", "));
    }
    match recv {
        None => {
            if args_s.is_empty() {
                method.to_string()
            } else {
                format!("{}({})", method, args_s.join(", "))
            }
        }
        Some(r) => {
            let recv_s = emit_expr(r);
            if args_s.is_empty() {
                format!("{recv_s}.{method}")
            } else {
                format!("{recv_s}.{method}({})", args_s.join(", "))
            }
        }
    }
}

fn emit_literal(lit: &Literal) -> String {
    match lit {
        Literal::Nil => "nil".to_string(),
        Literal::Bool { value } => value.to_string(),
        Literal::Int { value } => value.to_string(),
        Literal::Float { value } => {
            let s = value.to_string();
            if s.contains('.') { s } else { format!("{s}.0") }
        }
        Literal::Str { value } => format!("{value:?}"),
        // Crystal has first-class symbols just like Ruby.
        Literal::Sym { value } => format!(":{}", value.as_str()),
    }
}

fn indent(text: &str, depth: usize) -> String {
    let pad = "  ".repeat(depth);
    text.lines()
        .map(|l| if l.is_empty() { String::new() } else { format!("{pad}{l}") })
        .collect::<Vec<_>>()
        .join("\n")
}

// Types ----------------------------------------------------------------

pub fn crystal_ty(ty: &Ty) -> String {
    match ty {
        // Crystal's default integer is Int32; Rails schemas typically
        // use BigInt for IDs, so Int64 is the safer default for the
        // scaffold.
        Ty::Int => "Int64".to_string(),
        Ty::Float => "Float64".to_string(),
        Ty::Bool => "Bool".to_string(),
        Ty::Str => "String".to_string(),
        // Crystal has native Symbol.
        Ty::Sym => "Symbol".to_string(),
        Ty::Nil => "Nil".to_string(),
        Ty::Array { elem } => format!("Array({})", crystal_ty(elem)),
        Ty::Hash { key, value } => format!("Hash({}, {})", crystal_ty(key), crystal_ty(value)),
        Ty::Tuple { elems } => {
            let parts: Vec<String> = elems.iter().map(crystal_ty).collect();
            format!("Tuple({})", parts.join(", "))
        }
        Ty::Record { .. } => "Hash(String, String)".to_string(),
        Ty::Union { variants } => {
            // Crystal union: `A | B | C`.
            let parts: Vec<String> = variants.iter().map(crystal_ty).collect();
            parts.join(" | ")
        }
        Ty::Class { id, .. } => id.0.to_string(),
        Ty::Fn { .. } => "Proc(Nil)".to_string(),
        Ty::Var { .. } => "_".to_string(),
    }
}

// Fixtures + specs ----------------------------------------------------

/// Emit one fixture file as `spec/fixtures/<table>.cr` — a `Fixtures::X`
/// module with one `self.<label>` accessor per fixture record. IDs
/// assigned in insertion order (1..N), matching the Rust emitter.
fn emit_crystal_fixture(fixture: &Fixture, app: &App) -> EmittedFile {
    let class_name = crate::naming::singularize_camelize(fixture.name.as_str());
    let model = app
        .models
        .iter()
        .find(|m| m.name.0.as_str() == class_name.as_str());

    let module_name = crate::naming::camelize(fixture.name.as_str());

    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "require \"../../src/app\"").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "module Fixtures").unwrap();
    writeln!(s, "  module {module_name}").unwrap();
    for (i, (label, fields)) in fixture.records.iter().enumerate() {
        let id = (i as i64) + 1;
        if i > 0 {
            writeln!(s).unwrap();
        }
        writeln!(s, "    def self.{}() : {}", label.as_str(), class_name).unwrap();
        writeln!(s, "      record = {}.new", class_name).unwrap();
        writeln!(s, "      record.id = {id}_i64").unwrap();
        if let Some(m) = model {
            for (field, value) in fields {
                if let Some((col, rust_val)) = resolve_fixture_field_cr(field, value, m, app) {
                    writeln!(s, "      record.{col} = {rust_val}").unwrap();
                }
            }
        }
        writeln!(s, "      record").unwrap();
        writeln!(s, "    end").unwrap();
    }
    writeln!(s, "  end").unwrap();
    writeln!(s, "end").unwrap();

    EmittedFile {
        path: PathBuf::from(format!("spec/fixtures/{}.cr", fixture.name)),
        content: s,
    }
}

fn resolve_fixture_field_cr(
    field: &Symbol,
    value: &str,
    model: &Model,
    app: &App,
) -> Option<(String, String)> {
    if let Some(ty) = model.attributes.fields.get(field) {
        return Some((field.as_str().to_string(), crystal_literal_for(value, ty)));
    }
    for assoc in model.associations() {
        if let Association::BelongsTo { name, target, foreign_key, .. } = assoc {
            if name == field {
                let target_table = crate::naming::pluralize_snake(target.0.as_str());
                if let Some(target_fixture) = app
                    .fixtures
                    .iter()
                    .find(|f| f.name.as_str() == target_table.as_str())
                {
                    if let Some(idx) = target_fixture
                        .records
                        .keys()
                        .position(|k| k.as_str() == value)
                    {
                        let resolved_id = (idx as i64) + 1;
                        return Some((
                            foreign_key.as_str().to_string(),
                            format!("{}_i64", resolved_id),
                        ));
                    }
                }
            }
        }
    }
    None
}

fn crystal_literal_for(value: &str, ty: &Ty) -> String {
    match ty {
        Ty::Str | Ty::Sym => format!("{value:?}"),
        Ty::Int => {
            if value.parse::<i64>().is_ok() {
                format!("{value}_i64")
            } else {
                format!("0_i64 # TODO: coerce {value:?}")
            }
        }
        Ty::Float => {
            if value.parse::<f64>().is_ok() {
                format!("{value}_f64")
            } else {
                format!("0.0_f64 # TODO: coerce {value:?}")
            }
        }
        Ty::Bool => match value {
            "true" | "1" => "true".into(),
            "false" | "0" => "false".into(),
            _ => format!("false # TODO: coerce {value:?}"),
        },
        Ty::Class { id, .. } if id.0.as_str() == "Time" => format!("{value:?}"),
        _ => format!("{value:?}"),
    }
}

fn emit_spec_helper(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "require \"spec\"").unwrap();
    writeln!(s, "require \"../src/app\"").unwrap();
    for fixture in &app.fixtures {
        writeln!(s, "require \"./fixtures/{}\"", fixture.name).unwrap();
    }
    EmittedFile {
        path: PathBuf::from("spec/spec_helper.cr"),
        content: s,
    }
}

fn emit_crystal_spec(tm: &TestModule, app: &App) -> EmittedFile {
    // Target class: Article for ArticleTest. Used as the `describe`
    // subject so the spec output reads naturally.
    let subject = tm
        .target
        .as_ref()
        .map(|c| c.0.as_str().to_string())
        .unwrap_or_else(|| tm.name.0.as_str().to_string());

    let fixture_names: Vec<Symbol> =
        app.fixtures.iter().map(|f| f.name.clone()).collect();
    let known_models: Vec<Symbol> =
        app.models.iter().map(|m| m.name.0.clone()).collect();
    let mut attrs_set: std::collections::BTreeSet<Symbol> =
        std::collections::BTreeSet::new();
    for m in &app.models {
        for attr in m.attributes.fields.keys() {
            attrs_set.insert(attr.clone());
        }
    }
    let model_attrs: Vec<Symbol> = attrs_set.into_iter().collect();

    let ctx = SpecCtx {
        fixture_names: &fixture_names,
        known_models: &known_models,
        model_attrs: &model_attrs,
    };

    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "require \"../spec_helper\"").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "describe {subject} do").unwrap();

    for test in &tm.tests {
        if test_needs_runtime_unsupported_cr(test) {
            writeln!(
                s,
                "  pending {:?} do",
                test.name
            )
            .unwrap();
            writeln!(s, "    # Phase 3: needs persistence runtime").unwrap();
            writeln!(s, "  end").unwrap();
        } else {
            writeln!(s, "  it {:?} do", test.name).unwrap();
            for line in emit_spec_body(&test.body, ctx).lines() {
                writeln!(s, "    {line}").unwrap();
            }
            writeln!(s, "  end").unwrap();
        }
    }

    writeln!(s, "end").unwrap();

    let filename = crate::naming::snake_case(tm.name.0.as_str());
    // spec/models/article_spec.cr from ArticleTest.
    let filename = filename.replace("_test", "_spec");
    EmittedFile {
        path: PathBuf::from(format!("spec/models/{filename}.cr")),
        content: s,
    }
}

/// Context threaded through spec body emission.
#[derive(Clone, Copy)]
struct SpecCtx<'a> {
    fixture_names: &'a [Symbol],
    known_models: &'a [Symbol],
    model_attrs: &'a [Symbol],
}

/// Top-level emit for a test body — a `Seq` renders line by line; a
/// single expression renders as one line.
fn emit_spec_body(body: &Expr, ctx: SpecCtx) -> String {
    match &*body.node {
        ExprNode::Seq { exprs } if !exprs.is_empty() => exprs
            .iter()
            .map(|e| emit_spec_stmt(e, ctx))
            .collect::<Vec<_>>()
            .join("\n"),
        _ => emit_spec_stmt(body, ctx),
    }
}

fn emit_spec_stmt(e: &Expr, ctx: SpecCtx) -> String {
    match &*e.node {
        ExprNode::Assign { target: LValue::Var { name, .. }, value } => {
            format!("{} = {}", name, emit_spec_expr(value, ctx))
        }
        _ => emit_spec_expr(e, ctx),
    }
}

fn emit_spec_expr(e: &Expr, ctx: SpecCtx) -> String {
    use crate::expr::InterpPart;
    match &*e.node {
        ExprNode::Lit { value } => emit_literal(value),
        ExprNode::Var { name, .. } => name.to_string(),
        ExprNode::Const { path } => {
            path.iter().map(|s| s.to_string()).collect::<Vec<_>>().join("::")
        }
        ExprNode::Hash { entries, .. } => {
            let parts: Vec<String> = entries
                .iter()
                .map(|(k, v)| {
                    format!("{} => {}", emit_spec_expr(k, ctx), emit_spec_expr(v, ctx))
                })
                .collect();
            format!("{{{}}}", parts.join(", "))
        }
        ExprNode::Array { elements, .. } => {
            let parts: Vec<String> = elements.iter().map(|e| emit_spec_expr(e, ctx)).collect();
            format!("[{}]", parts.join(", "))
        }
        ExprNode::StringInterp { parts } => {
            let mut out = String::from("\"");
            for p in parts {
                match p {
                    InterpPart::Text { value } => out.push_str(value),
                    InterpPart::Expr { expr } => {
                        out.push_str("#{");
                        out.push_str(&emit_spec_expr(expr, ctx));
                        out.push('}');
                    }
                }
            }
            out.push('"');
            out
        }
        ExprNode::Send { recv, method, args, .. } => {
            emit_spec_send(recv.as_ref(), method.as_str(), args, ctx)
        }
        ExprNode::BoolOp { op, left, right, .. } => {
            use crate::expr::BoolOpKind;
            let op_s = match op {
                BoolOpKind::Or => "||",
                BoolOpKind::And => "&&",
            };
            format!(
                "{} {} {}",
                emit_spec_expr(left, ctx),
                op_s,
                emit_spec_expr(right, ctx)
            )
        }
        ExprNode::Assign { target, value } => {
            // Only in rare inline positions; renders as a Crystal
            // assignment expression.
            let v = emit_spec_expr(value, ctx);
            match target {
                LValue::Var { name, .. } => format!("{name} = {v}"),
                LValue::Ivar { name } => format!("@{name} = {v}"),
                _ => v,
            }
        }
        _ => format!("# TODO: spec emit for {:?}", std::mem::discriminant(&*e.node)),
    }
}

fn emit_spec_send(
    recv: Option<&Expr>,
    method: &str,
    args: &[Expr],
    ctx: SpecCtx,
) -> String {
    let args_s: Vec<String> = args.iter().map(|a| emit_spec_expr(a, ctx)).collect();

    // Fixture accessor: articles(:one) → Fixtures::Articles.one
    if recv.is_none()
        && args.len() == 1
        && ctx.fixture_names.iter().any(|s| s.as_str() == method)
    {
        if let ExprNode::Lit { value: Literal::Sym { value: sym } } = &*args[0].node {
            let module_name = crate::naming::camelize(method);
            return format!("Fixtures::{module_name}.{}", sym.as_str());
        }
    }

    // Assertion macros → Crystal spec's `should` matchers.
    // Ruby's `assert_equal expected, actual` → `actual.should eq(expected)`.
    if recv.is_none() {
        match (method, args_s.len()) {
            ("assert_equal", 2) => {
                return format!("{}.should eq({})", args_s[1], args_s[0]);
            }
            ("assert_not_equal", 2) => {
                return format!("{}.should_not eq({})", args_s[1], args_s[0]);
            }
            ("assert_not", 1) => {
                return format!("{}.should be_false", args_s[0]);
            }
            ("assert", 1) => {
                return format!("{}.should be_true", args_s[0]);
            }
            ("assert_nil", 1) => {
                return format!("{}.should be_nil", args_s[0]);
            }
            ("assert_not_nil", 1) => {
                return format!("{}.should_not be_nil", args_s[0]);
            }
            _ => {}
        }
    }

    // `Class.new(hash)` → Crystal requires setting properties after .new.
    // Use `.tap do |r| r.k = v end` pattern when the target is a known
    // model.
    if let Some(r) = recv {
        if method == "new" && args.len() == 1 {
            if let ExprNode::Const { path } = &*r.node {
                if let Some(class_name) = path.last() {
                    if ctx.known_models.iter().any(|s| s == class_name) {
                        if let ExprNode::Hash { entries, .. } = &*args[0].node {
                            let mut lines: Vec<String> =
                                vec![format!("{class_name}.new.tap do |record|")];
                            for (k, v) in entries {
                                if let ExprNode::Lit {
                                    value: Literal::Sym { value: f },
                                } = &*k.node
                                {
                                    lines.push(format!(
                                        "      record.{} = {}",
                                        f.as_str(),
                                        emit_spec_expr(v, ctx)
                                    ));
                                }
                            }
                            lines.push("    end".to_string());
                            return lines.join("\n");
                        }
                    }
                }
            }
        }
    }

    match recv {
        None => {
            if args_s.is_empty() {
                method.to_string()
            } else {
                format!("{}({})", method, args_s.join(", "))
            }
        }
        Some(r) => {
            let recv_s = emit_spec_expr(r, ctx);
            let is_class_call = matches!(&*r.node, ExprNode::Const { .. });
            let sep = if is_class_call { "." } else { "." };
            // Crystal doesn't distinguish field vs method call syntactically
            // (property getters ARE method calls), so we can emit both as
            // `recv.method` regardless — but attribute reads should be
            // bare, no parens.
            let is_attr_read = !is_class_call
                && args_s.is_empty()
                && ctx.model_attrs.iter().any(|s| s.as_str() == method);
            if is_attr_read {
                format!("{recv_s}{sep}{method}")
            } else if args_s.is_empty() {
                // Crystal allows omitting parens for zero-arg calls;
                // keep them off for consistency with Ruby idiom.
                format!("{recv_s}{sep}{method}")
            } else {
                format!("{recv_s}{sep}{method}({})", args_s.join(", "))
            }
        }
    }
}

/// Heuristic: does the test body reference runtime support we haven't
/// built yet? Mirrors the Rust equivalent.
fn test_needs_runtime_unsupported_cr(test: &Test) -> bool {
    let known_name_ignored = matches!(test.name.as_str(), "requires valid article");
    if known_name_ignored {
        return true;
    }
    test_body_uses_unsupported_cr(&test.body)
}

fn test_body_uses_unsupported_cr(e: &Expr) -> bool {
    use crate::expr::InterpPart;
    let self_hit = match &*e.node {
        ExprNode::Send { recv, method, .. } => {
            let m = method.as_str();
            matches!(
                m,
                "assert_difference"
                    | "destroy"
                    | "destroy!"
                    | "build"
                    | "create"
                    | "create!"
            ) || (m == "count"
                && recv.as_ref().is_some_and(|r| matches!(&*r.node, ExprNode::Const { .. })))
        }
        _ => false,
    };
    if self_hit {
        return true;
    }
    match &*e.node {
        ExprNode::Send { recv, args, block, .. } => {
            if let Some(r) = recv {
                if test_body_uses_unsupported_cr(r) {
                    return true;
                }
            }
            for a in args {
                if test_body_uses_unsupported_cr(a) {
                    return true;
                }
            }
            if let Some(b) = block {
                if test_body_uses_unsupported_cr(b) {
                    return true;
                }
            }
        }
        ExprNode::Seq { exprs } | ExprNode::Array { elements: exprs, .. } => {
            for e in exprs {
                if test_body_uses_unsupported_cr(e) {
                    return true;
                }
            }
        }
        ExprNode::Hash { entries, .. } => {
            for (k, v) in entries {
                if test_body_uses_unsupported_cr(k) || test_body_uses_unsupported_cr(v) {
                    return true;
                }
            }
        }
        ExprNode::StringInterp { parts } => {
            for p in parts {
                if let InterpPart::Expr { expr } = p {
                    if test_body_uses_unsupported_cr(expr) {
                        return true;
                    }
                }
            }
        }
        ExprNode::BoolOp { left, right, .. }
        | ExprNode::RescueModifier { expr: left, fallback: right } => {
            if test_body_uses_unsupported_cr(left) || test_body_uses_unsupported_cr(right) {
                return true;
            }
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            if test_body_uses_unsupported_cr(cond)
                || test_body_uses_unsupported_cr(then_branch)
                || test_body_uses_unsupported_cr(else_branch)
            {
                return true;
            }
        }
        ExprNode::Let { value, body, .. } => {
            if test_body_uses_unsupported_cr(value) || test_body_uses_unsupported_cr(body) {
                return true;
            }
        }
        ExprNode::Lambda { body, .. } => {
            if test_body_uses_unsupported_cr(body) {
                return true;
            }
        }
        ExprNode::Assign { value, .. } => {
            if test_body_uses_unsupported_cr(value) {
                return true;
            }
        }
        _ => {}
    }
    false
}
