//! Crystal emitter.
//!
//! Last Phase 2 scaffold. Crystal is Ruby-flavored with mandatory
//! static types, which makes this the easiest scaffold of the six —
//! the emission shape is almost identical to Ruby's, plus type
//! annotations.
//!
//! Scaffold choices:
//! - Models as `class Name` with typed `property :field : Type`
//!   declarations (Crystal's getter/setter macro).
//! - Controllers as `class Name` with one method per action. No
//!   `< Kemal::Controller` base — Phase 3+ runtime work picks.
//! - Routes as a `ROUTES` constant with a NamedTuple array —
//!   Crystal's idiomatic static table shape.
//!
//! Notably not mirrored from railcar:
//! - Railcar's Crystal output uses a heavy macro DSL
//!   (`model("articles") do column(title, String) end`) to hook
//!   into its runtime. That's a Phase-4-depth choice; our scaffold
//!   stays runtime-agnostic.

use std::fmt::Write;
use std::path::PathBuf;

use super::EmittedFile;
use crate::App;
use crate::dialect::{Action, Controller, MethodDef, Model, RouteSpec};
use crate::expr::{Expr, ExprNode, LValue, Literal};
use crate::ty::Ty;

pub fn emit(app: &App) -> Vec<EmittedFile> {
    let mut files = Vec::new();
    if !app.models.is_empty() {
        files.push(emit_models(app));
    }
    if !app.controllers.is_empty() {
        files.push(emit_controllers(app));
    }
    if !app.routes.entries.is_empty() {
        files.push(emit_routes(app));
    }
    files
}

// Models ---------------------------------------------------------------

fn emit_models(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    for (i, model) in app.models.iter().enumerate() {
        if i > 0 {
            writeln!(s).unwrap();
        }
        emit_model(&mut s, model);
    }
    EmittedFile { path: PathBuf::from("src/models.cr"), content: s }
}

fn emit_model(out: &mut String, model: &Model) {
    let name = model.name.0.as_str();
    writeln!(out, "class {name}").unwrap();
    for (field, ty) in &model.attributes.fields {
        writeln!(out, "  property {} : {}", field, crystal_ty(ty)).unwrap();
    }
    for method in model.methods() {
        writeln!(out).unwrap();
        emit_model_method(out, method);
    }
    writeln!(out, "end").unwrap();
}

fn emit_model_method(out: &mut String, m: &MethodDef) {
    let name = m.name.as_str();
    let ret = m.body.ty.clone().unwrap_or(Ty::Nil);
    let ret_annot = format!(" : {}", crystal_ty(&ret));
    let receiver = match m.receiver {
        crate::dialect::MethodReceiver::Instance => "",
        crate::dialect::MethodReceiver::Class => "self.",
    };
    let params = if m.params.is_empty() {
        String::new()
    } else {
        let ps: Vec<String> = m.params.iter().map(|p| p.to_string()).collect();
        format!("({})", ps.join(", "))
    };
    writeln!(out, "  def {receiver}{name}{params}{ret_annot}").unwrap();
    let body = emit_body(&m.body);
    for line in body.lines() {
        writeln!(out, "    {line}").unwrap();
    }
    writeln!(out, "  end").unwrap();
}

// Controllers ----------------------------------------------------------

fn emit_controllers(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    for (i, controller) in app.controllers.iter().enumerate() {
        if i > 0 {
            writeln!(s).unwrap();
        }
        emit_controller(&mut s, controller);
    }
    EmittedFile { path: PathBuf::from("src/controllers.cr"), content: s }
}

fn emit_controller(out: &mut String, c: &Controller) {
    let name = c.name.0.as_str();
    writeln!(out, "class {name}").unwrap();
    for (i, action) in c.actions().enumerate() {
        if i > 0 {
            writeln!(out).unwrap();
        }
        emit_action(out, action);
    }
    writeln!(out, "end").unwrap();
}

fn emit_action(out: &mut String, a: &Action) {
    let name = a.name.as_str();
    let ret = action_return_type(&a.body);
    let ret_annot = match &ret {
        // Crystal's void return type is `Nil` (capital N — the type,
        // not the literal).
        Ty::Nil => " : Nil".to_string(),
        other => format!(" : {}", crystal_ty(other)),
    };
    writeln!(out, "  def {name}{ret_annot}").unwrap();
    let body = emit_body(&a.body);
    for line in body.lines() {
        writeln!(out, "    {line}").unwrap();
    }
    writeln!(out, "  end").unwrap();
}

fn action_return_type(body: &Expr) -> Ty {
    match &*body.node {
        ExprNode::Assign { value, .. } => value.ty.clone().unwrap_or(Ty::Nil),
        ExprNode::Seq { exprs } => exprs
            .last()
            .and_then(|e| match &*e.node {
                ExprNode::Assign { value, .. } => value.ty.clone(),
                _ => e.ty.clone(),
            })
            .unwrap_or(Ty::Nil),
        _ => body.ty.clone().unwrap_or(Ty::Nil),
    }
}

// Routes ---------------------------------------------------------------

fn emit_routes(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "ROUTES = [").unwrap();
    let mut flat: Vec<(String, String, String, String)> = Vec::new();
    for entry in &app.routes.entries {
        collect_flat_routes(entry, &mut flat, None);
    }
    for (method, path, controller, action) in flat {
        writeln!(
            s,
            "  {{method: :{}, path: {:?}, controller: {:?}, action: :{}}},",
            method.to_lowercase(),
            path,
            controller,
            action,
        )
        .unwrap();
    }
    writeln!(s, "]").unwrap();
    EmittedFile { path: PathBuf::from("src/routes.cr"), content: s }
}

fn collect_flat_routes(
    spec: &RouteSpec,
    out: &mut Vec<(String, String, String, String)>,
    scope_prefix: Option<(&str, &str)>,
) {
    match spec {
        RouteSpec::Explicit { method, path, controller, action, .. } => {
            let verb = match method {
                crate::dialect::HttpMethod::Get => "GET",
                crate::dialect::HttpMethod::Post => "POST",
                crate::dialect::HttpMethod::Put => "PUT",
                crate::dialect::HttpMethod::Patch => "PATCH",
                crate::dialect::HttpMethod::Delete => "DELETE",
                crate::dialect::HttpMethod::Head => "HEAD",
                crate::dialect::HttpMethod::Options => "OPTIONS",
                crate::dialect::HttpMethod::Any => "ANY",
            };
            let full_path = match scope_prefix {
                Some((parent, _)) => format!("/{parent}/:{parent}_id{path}"),
                None => path.clone(),
            };
            out.push((
                verb.to_string(),
                full_path,
                controller.0.to_string(),
                action.to_string(),
            ));
        }
        RouteSpec::Root { target } => {
            if let Some((c, a)) = target.split_once('#') {
                out.push(("GET".into(), "/".into(), controller_class_name(c), a.into()));
            }
        }
        RouteSpec::Resources { name, only, except, nested } => {
            let resource_path = format!("/{name}");
            let controller = controller_class_name(name.as_str());
            for (action, verb, suffix) in standard_resource_actions() {
                let action = *action;
                let verb = *verb;
                let suffix = *suffix;
                if !only.is_empty() && !only.iter().any(|s| s.as_str() == action) {
                    continue;
                }
                if except.iter().any(|s| s.as_str() == action) {
                    continue;
                }
                let path = format!("{resource_path}{suffix}");
                let full_path = match scope_prefix {
                    Some((parent, _)) => format!("/{parent}/:{parent}_id{path}"),
                    None => path,
                };
                out.push((verb.into(), full_path, controller.clone(), action.into()));
            }
            let singular =
                crate::naming::singularize_camelize(name.as_str()).to_lowercase();
            for child in nested {
                collect_flat_routes(child, out, Some((&singular, name.as_str())));
            }
        }
    }
}

fn standard_resource_actions() -> &'static [(&'static str, &'static str, &'static str)] {
    &[
        ("index", "GET", ""),
        ("new", "GET", "/new"),
        ("create", "POST", ""),
        ("show", "GET", "/:id"),
        ("edit", "GET", "/:id/edit"),
        ("update", "PATCH", "/:id"),
        ("destroy", "DELETE", "/:id"),
    ]
}

fn controller_class_name(short: &str) -> String {
    let mut s = crate::naming::camelize(short);
    s.push_str("Controller");
    s
}

// Bodies + expressions -------------------------------------------------

fn emit_body(body: &Expr) -> String {
    match &*body.node {
        ExprNode::Seq { exprs } if !exprs.is_empty() => {
            let mut lines: Vec<String> = Vec::new();
            for (i, e) in exprs.iter().enumerate() {
                if i > 0 && e.leading_blank_line {
                    lines.push(String::new());
                }
                lines.push(emit_stmt(e));
            }
            lines.join("\n")
        }
        _ => emit_stmt(body),
    }
}

fn emit_stmt(e: &Expr) -> String {
    match &*e.node {
        ExprNode::Assign { target: LValue::Var { name, .. }, value } => {
            format!("{} = {}", name, emit_expr(value))
        }
        ExprNode::Assign { target: LValue::Ivar { name }, value } => {
            format!("@{} = {}", name, emit_expr(value))
        }
        _ => emit_expr(e),
    }
}

fn emit_expr(e: &Expr) -> String {
    match &*e.node {
        ExprNode::Lit { value } => emit_literal(value),
        ExprNode::Const { path } => {
            path.iter().map(|s| s.to_string()).collect::<Vec<_>>().join("::")
        }
        ExprNode::Var { name, .. } => name.to_string(),
        ExprNode::Ivar { name } => format!("@{name}"),
        ExprNode::Send { recv, method, args, .. } => {
            emit_send(recv.as_ref(), method.as_str(), args)
        }
        ExprNode::Assign { target: _, value } => emit_expr(value),
        ExprNode::Seq { exprs } => {
            exprs.iter().map(emit_expr).collect::<Vec<_>>().join("; ")
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            // Crystal's if/else/end is identical to Ruby's.
            let cond_s = emit_expr(cond);
            let then_s = emit_body(then_branch);
            let else_s = emit_body(else_branch);
            format!(
                "if {cond_s}\n{}\nelse\n{}\nend",
                indent(&then_s, 1),
                indent(&else_s, 1),
            )
        }
        ExprNode::BoolOp { op, left, right, .. } => {
            use crate::expr::{BoolOpKind, BoolOpSurface};
            // Crystal supports both `&&` / `||` and `and` / `or` — we
            // preserve the surface form from the IR the same way the
            // Ruby emitter does.
            let op_s = match (op, &e.node) {
                (BoolOpKind::Or, _) => {
                    if let ExprNode::BoolOp { surface: BoolOpSurface::Word, .. } = &*e.node {
                        "or"
                    } else {
                        "||"
                    }
                }
                (BoolOpKind::And, _) => {
                    if let ExprNode::BoolOp { surface: BoolOpSurface::Word, .. } = &*e.node {
                        "and"
                    } else {
                        "&&"
                    }
                }
            };
            format!("{} {op_s} {}", emit_expr(left), emit_expr(right))
        }
        ExprNode::Array { elements, .. } => {
            let parts: Vec<String> = elements.iter().map(emit_expr).collect();
            format!("[{}]", parts.join(", "))
        }
        ExprNode::Hash { entries, .. } => {
            let parts: Vec<String> = entries
                .iter()
                .map(|(k, v)| {
                    if let ExprNode::Lit { value: Literal::Sym { value } } = &*k.node {
                        format!("{value}: {}", emit_expr(v))
                    } else {
                        format!("{} => {}", emit_expr(k), emit_expr(v))
                    }
                })
                .collect();
            format!("{{{}}}", parts.join(", "))
        }
        ExprNode::StringInterp { parts } => {
            // Crystal interpolation is identical to Ruby's.
            use crate::expr::InterpPart;
            let mut out = String::from("\"");
            for p in parts {
                match p {
                    InterpPart::Text { value } => {
                        for c in value.chars() {
                            match c {
                                '"' => out.push_str("\\\""),
                                '\\' => out.push_str("\\\\"),
                                '\n' => out.push_str("\\n"),
                                '#' => out.push_str("\\#"),
                                other => out.push(other),
                            }
                        }
                    }
                    InterpPart::Expr { expr } => {
                        out.push_str("#{");
                        out.push_str(&emit_expr(expr));
                        out.push('}');
                    }
                }
            }
            out.push('"');
            out
        }
        ExprNode::Yield { args } => {
            let parts: Vec<String> = args.iter().map(emit_expr).collect();
            if parts.is_empty() {
                "yield".to_string()
            } else {
                format!("yield {}", parts.join(", "))
            }
        }
        other => format!("# TODO: emit {:?}", std::mem::discriminant(other)),
    }
}

fn emit_send(recv: Option<&Expr>, method: &str, args: &[Expr]) -> String {
    let args_s: Vec<String> = args.iter().map(emit_expr).collect();
    if method == "[]" && recv.is_some() {
        return format!("{}[{}]", emit_expr(recv.unwrap()), args_s.join(", "));
    }
    match recv {
        None => {
            if args_s.is_empty() {
                method.to_string()
            } else {
                format!("{}({})", method, args_s.join(", "))
            }
        }
        Some(r) => {
            let recv_s = emit_expr(r);
            if args_s.is_empty() {
                format!("{recv_s}.{method}")
            } else {
                format!("{recv_s}.{method}({})", args_s.join(", "))
            }
        }
    }
}

fn emit_literal(lit: &Literal) -> String {
    match lit {
        Literal::Nil => "nil".to_string(),
        Literal::Bool { value } => value.to_string(),
        Literal::Int { value } => value.to_string(),
        Literal::Float { value } => {
            let s = value.to_string();
            if s.contains('.') { s } else { format!("{s}.0") }
        }
        Literal::Str { value } => format!("{value:?}"),
        // Crystal has first-class symbols just like Ruby.
        Literal::Sym { value } => format!(":{}", value.as_str()),
    }
}

fn indent(text: &str, depth: usize) -> String {
    let pad = "  ".repeat(depth);
    text.lines()
        .map(|l| if l.is_empty() { String::new() } else { format!("{pad}{l}") })
        .collect::<Vec<_>>()
        .join("\n")
}

// Types ----------------------------------------------------------------

pub fn crystal_ty(ty: &Ty) -> String {
    match ty {
        // Crystal's default integer is Int32; Rails schemas typically
        // use BigInt for IDs, so Int64 is the safer default for the
        // scaffold.
        Ty::Int => "Int64".to_string(),
        Ty::Float => "Float64".to_string(),
        Ty::Bool => "Bool".to_string(),
        Ty::Str => "String".to_string(),
        // Crystal has native Symbol.
        Ty::Sym => "Symbol".to_string(),
        Ty::Nil => "Nil".to_string(),
        Ty::Array { elem } => format!("Array({})", crystal_ty(elem)),
        Ty::Hash { key, value } => format!("Hash({}, {})", crystal_ty(key), crystal_ty(value)),
        Ty::Tuple { elems } => {
            let parts: Vec<String> = elems.iter().map(crystal_ty).collect();
            format!("Tuple({})", parts.join(", "))
        }
        Ty::Record { .. } => "Hash(String, String)".to_string(),
        Ty::Union { variants } => {
            // Crystal union: `A | B | C`.
            let parts: Vec<String> = variants.iter().map(crystal_ty).collect();
            parts.join(" | ")
        }
        Ty::Class { id, .. } => id.0.to_string(),
        Ty::Fn { .. } => "Proc(Nil)".to_string(),
        Ty::Var { .. } => "_".to_string(),
    }
}
