//! Go emitter.
//!
//! Second typed target. Differences from Rust that surface design choices:
//!
//! - Go has no Option / Result — nullable types are pointers (`*T`).
//! - Go has no class methods — `Post.All()` is pseudo-Go; a real mapping
//!   would use a repository pattern or package-level functions.
//! - Go requires explicit `return` for non-void functions and omits the
//!   return type entirely for void functions.
//! - Go convention: `ID`, `URL`, `HTTP` for initialism fields; PascalCase
//!   for exported identifiers, camelCase for unexported.
//! - Go uses tabs for indentation; gofmt would realign struct fields.
//!   We emit single-tab indent without alignment.
//!
//! Output is pseudo-Go — won't compile as-is. The goal is to prove that
//! types flow through to a second typed target without the Rust emitter
//! accidentally hiding ambiguities.

use std::fmt::Write;
use std::path::PathBuf;

use super::EmittedFile;
use crate::App;
use crate::dialect::{
    Action, Association, Controller, MethodDef, Model, Test, TestModule,
};
use crate::expr::{Expr, ExprNode, LValue, Literal};
use crate::ident::Symbol;
use crate::naming::snake_case;
use crate::ty::Ty;

const RUNTIME_SOURCE: &str = include_str!("../../runtime/go/runtime.go");
const DB_SOURCE: &str = include_str!("../../runtime/go/db.go");

pub fn emit(app: &App) -> Vec<EmittedFile> {
    let mut files = Vec::new();
    files.push(emit_go_mod());
    files.push(emit_go_sum());
    if !app.models.is_empty() {
        files.push(emit_models(app));
        files.push(EmittedFile {
            path: PathBuf::from("app/runtime.go"),
            content: RUNTIME_SOURCE.to_string(),
        });
        files.push(EmittedFile {
            path: PathBuf::from("app/db.go"),
            content: DB_SOURCE.to_string(),
        });
        files.push(emit_schema_sql_go(app));
    }
    for controller in &app.controllers {
        files.push(emit_controller(controller));
    }
    if !app.fixtures.is_empty() {
        files.push(emit_go_fixtures(app));
    }
    if !app.test_modules.is_empty() {
        for tm in &app.test_modules {
            files.push(emit_go_tests(tm, app));
        }
    }
    files
}

/// `go.mod` — module name `app`, targeting Go 1.24. Depends on
/// modernc.org/sqlite for the pure-Go SQLite driver that the Phase 3
/// persistence runtime uses. The toolchain test runs `go mod tidy`
/// before building to populate go.sum.
fn emit_go_mod() -> EmittedFile {
    let content = "module app\n\ngo 1.24\n\nrequire modernc.org/sqlite v1.34.1\n";
    EmittedFile {
        path: PathBuf::from("go.mod"),
        content: content.to_string(),
    }
}

/// Empty `go.sum` placeholder — `go mod tidy` populates it on first
/// build. Emitting the file up front avoids a chicken-and-egg where
/// `go vet` refuses to run without it.
fn emit_go_sum() -> EmittedFile {
    EmittedFile {
        path: PathBuf::from("go.sum"),
        content: String::new(),
    }
}

/// `app/schema_sql.go` — Go constant wrapping the target-neutral DDL
/// produced by `lower::lower_schema`. `SetupTestDB` splits it on
/// `;\n` and execs each statement against a fresh :memory: database.
fn emit_schema_sql_go(app: &App) -> EmittedFile {
    let ddl = crate::lower::lower_schema(&app.schema);
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s, "package app").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "const CreateTables = `").unwrap();
    s.push_str(&ddl);
    writeln!(s, "`").unwrap();
    EmittedFile {
        path: PathBuf::from("app/schema_sql.go"),
        content: s,
    }
}

// Models ---------------------------------------------------------------

fn emit_models(app: &App) -> EmittedFile {
    let mut body = String::new();
    for model in &app.models {
        writeln!(body).unwrap();
        emit_struct(&mut body, model);
        for method in model.methods() {
            writeln!(body).unwrap();
            emit_model_method(&mut body, model, method);
        }
        let lowered = crate::lower::lower_validations(model);
        if !lowered.is_empty() {
            writeln!(body).unwrap();
            emit_validate_method_go(&mut body, model, &lowered);
        }
        // Persistence emitted for any model with table columns beyond
        // `id`. Abstract base classes (ApplicationRecord) get skipped.
        let has_table = model
            .attributes
            .fields
            .keys()
            .any(|k| k.as_str() != "id");
        if has_table {
            writeln!(body).unwrap();
            emit_persistence_methods_go(&mut body, model, !lowered.is_empty(), app);
        }
    }
    // Conditional imports: scan the emitted body for package prefixes
    // that indicate which stdlib we need. Go errors on unused imports,
    // so we only emit what's actually referenced.
    let mut imports: Vec<&str> = Vec::new();
    if body.contains("strings.") {
        imports.push("strings");
    }

    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s, "package app").unwrap();
    if !imports.is_empty() {
        writeln!(s).unwrap();
        if imports.len() == 1 {
            writeln!(s, "import \"{}\"", imports[0]).unwrap();
        } else {
            writeln!(s, "import (").unwrap();
            for imp in &imports {
                writeln!(s, "\t\"{imp}\"").unwrap();
            }
            writeln!(s, ")").unwrap();
        }
    }
    s.push_str(&body);
    EmittedFile { path: PathBuf::from("app/models.go"), content: s }
}

fn emit_struct(out: &mut String, model: &Model) {
    writeln!(out, "type {} struct {{", model.name.0).unwrap();
    for (name, ty) in &model.attributes.fields {
        writeln!(out, "\t{} {}", go_field_name(name.as_str()), go_ty(ty)).unwrap();
    }
    writeln!(out, "}}").unwrap();
}

fn emit_model_method(out: &mut String, model: &Model, m: &MethodDef) {
    let ret_ty = m.body.ty.clone().unwrap_or(Ty::Nil);
    let method_name = go_method_name(m.name.as_str());
    let ret_annot = match &ret_ty {
        Ty::Nil => String::new(),
        other => format!(" {}", go_ty(other)),
    };
    let (receiver, receiver_var) = match m.receiver {
        crate::dialect::MethodReceiver::Instance => {
            // Single-letter receiver name — Go idiom (`p *Post`).
            let first = model
                .name
                .0
                .as_str()
                .chars()
                .next()
                .unwrap_or('r')
                .to_ascii_lowercase();
            (format!("({first} *{})", model.name.0), first.to_string())
        }
        crate::dialect::MethodReceiver::Class => {
            // Class method: emit as package-level function (pseudo-Go, since
            // Go has no class methods).
            (String::new(), String::new())
        }
    };
    let space_before_name = if receiver.is_empty() { "" } else { " " };
    writeln!(
        out,
        "func {}{}{}(){} {{",
        receiver, space_before_name, method_name, ret_annot,
    )
    .unwrap();
    // Pre-emit rewrite: bare `title` inside a method body → `p.Title`
    // (receiver-var + PascalCased field). Same pattern as the other
    // typed emitters; Go makes it the receiver variable rather than
    // `self`/`this`.
    let attrs: Vec<Symbol> = model.attributes.fields.keys().cloned().collect();
    let rewritten = if !receiver_var.is_empty() {
        rewrite_bare_attrs_to_receiver(&m.body, &attrs, &receiver_var)
    } else {
        m.body.clone()
    };
    let body_s = if matches!(ret_ty, Ty::Nil) {
        emit_expr(&rewritten)
    } else {
        format!("return {}", emit_expr(&rewritten))
    };
    for line in body_s.lines() {
        writeln!(out, "\t{}", line).unwrap();
    }
    writeln!(out, "}}").unwrap();
}

// Controllers ----------------------------------------------------------

fn emit_controller(c: &Controller) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s, "package app").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "type {} struct{{}}", c.name.0).unwrap();
    for action in c.actions() {
        writeln!(s).unwrap();
        emit_action(&mut s, c, action);
    }
    let fname = format!("app/controllers/{}.go", snake_case(c.name.0.as_str()));
    EmittedFile { path: PathBuf::from(fname), content: s }
}

fn emit_action(out: &mut String, c: &Controller, a: &Action) {
    let ret_ty = action_return_type(&a.body);
    let method_name = go_method_name(a.name.as_str());
    let ret_annot = match &ret_ty {
        Ty::Nil => String::new(),
        other => format!(" {}", go_ty(other)),
    };
    writeln!(out, "func (c *{}) {}(){} {{", c.name.0, method_name, ret_annot).unwrap();
    let body = emit_body(&a.body, &ret_ty);
    for line in body.lines() {
        writeln!(out, "\t{}", line).unwrap();
    }
    writeln!(out, "}}").unwrap();
}

fn action_return_type(body: &Expr) -> Ty {
    match &*body.node {
        ExprNode::Assign { value, .. } => value.ty.clone().unwrap_or(Ty::Nil),
        ExprNode::Seq { exprs } => exprs
            .last()
            .and_then(|e| match &*e.node {
                ExprNode::Assign { value, .. } => value.ty.clone(),
                _ => e.ty.clone(),
            })
            .unwrap_or(Ty::Nil),
        _ => body.ty.clone().unwrap_or(Ty::Nil),
    }
}

// Body and expressions -------------------------------------------------

fn emit_body(body: &Expr, return_ty: &Ty) -> String {
    let is_void = matches!(return_ty, Ty::Nil);
    match &*body.node {
        ExprNode::Assign { target: LValue::Ivar { .. }, value } => {
            if is_void {
                emit_expr(value)
            } else {
                format!("return {}", emit_expr(value))
            }
        }
        ExprNode::Seq { exprs } if !exprs.is_empty() => {
            let mut lines: Vec<String> = Vec::new();
            for (i, e) in exprs.iter().enumerate() {
                lines.push(emit_stmt(e, i == exprs.len() - 1, is_void));
            }
            lines.join("\n")
        }
        _ => {
            if is_void {
                emit_expr(body)
            } else {
                format!("return {}", emit_expr(body))
            }
        }
    }
}

fn emit_stmt(e: &Expr, is_last: bool, void_return: bool) -> String {
    match &*e.node {
        // Local `foo = expr` and ivar `@foo = expr` both become `foo := expr`.
        ExprNode::Assign { target: LValue::Var { name, .. }, value } => {
            format!("{} := {}", name, emit_expr(value))
        }
        ExprNode::Assign { target: LValue::Ivar { name }, value } => {
            format!("{} := {}", name, emit_expr(value))
        }
        _ => {
            if is_last && !void_return {
                format!("return {}", emit_expr(e))
            } else {
                emit_expr(e)
            }
        }
    }
}

fn emit_expr(e: &Expr) -> String {
    match &*e.node {
        ExprNode::Lit { value } => emit_literal(value),
        ExprNode::Const { path } => {
            path.iter().map(|s| s.to_string()).collect::<Vec<_>>().join(".")
        }
        ExprNode::Var { name, .. } => name.to_string(),
        ExprNode::Ivar { name } => name.to_string(),
        ExprNode::Send { recv, method, args, .. } => emit_send(recv.as_ref(), method.as_str(), args),
        ExprNode::Assign { target: _, value } => emit_expr(value),
        ExprNode::Seq { exprs } => {
            exprs.iter().map(emit_expr).collect::<Vec<_>>().join("; ")
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            let cond_s = emit_expr(cond);
            let then_s = emit_block_body(then_branch);
            let else_s = emit_block_body(else_branch);
            format!("if {cond_s} {{\n{then_s}\n}} else {{\n{else_s}\n}}")
        }
        ExprNode::Hash { entries, .. } => {
            let parts: Vec<String> = entries
                .iter()
                .map(|(k, v)| format!("{}: {}", emit_expr(k), emit_expr(v)))
                .collect();
            format!("map[string]interface{{}}{{{}}}", parts.join(", "))
        }
        ExprNode::Array { elements, .. } => {
            let parts: Vec<String> = elements.iter().map(emit_expr).collect();
            format!("[]interface{{}}{{{}}}", parts.join(", "))
        }
        ExprNode::BoolOp { op, left, right, .. } => {
            use crate::expr::BoolOpKind;
            let op_s = match op {
                BoolOpKind::Or => "||",
                BoolOpKind::And => "&&",
            };
            format!("{} {} {}", emit_expr(left), op_s, emit_expr(right))
        }
        ExprNode::StringInterp { parts } => {
            use crate::expr::InterpPart;
            let mut fmt = String::new();
            let mut args: Vec<String> = Vec::new();
            for p in parts {
                match p {
                    InterpPart::Text { value } => {
                        for c in value.chars() {
                            if c == '%' {
                                fmt.push_str("%%");
                            } else {
                                fmt.push(c);
                            }
                        }
                    }
                    InterpPart::Expr { expr } => {
                        fmt.push_str("%v");
                        args.push(emit_expr(expr));
                    }
                }
            }
            if args.is_empty() {
                format!("{fmt:?}")
            } else {
                format!("fmt.Sprintf({fmt:?}, {})", args.join(", "))
            }
        }
        other => format!("/* TODO: emit {:?} */", std::mem::discriminant(other)),
    }
}

fn emit_send(recv: Option<&Expr>, method: &str, args: &[Expr]) -> String {
    let args_s: Vec<String> = args.iter().map(emit_expr).collect();

    if method == "[]" && recv.is_some() {
        return format!("{}[{}]", emit_expr(recv.unwrap()), args_s.join(", "));
    }

    // Ruby→Go method-name mapping for string operations that have no
    // 1:1 in Go's stdlib (`strip` is `strings.TrimSpace(…)`, not
    // `.Strip()`). Only kicks in for instance dispatch on Str-typed
    // receivers; class calls and unknown types pass through.
    if let Some(r) = recv {
        if args.is_empty() && matches!(r.ty, Some(Ty::Str)) {
            if let Some(wrapped) = map_go_str_method(method, &emit_expr(r)) {
                return wrapped;
            }
        }
    }

    let go_m = go_method_name(method);
    match recv {
        None => {
            if args_s.is_empty() {
                go_m
            } else {
                format!("{}({})", go_m, args_s.join(", "))
            }
        }
        Some(r) => {
            let recv_s = emit_expr(r);
            // Struct field access vs method call: 0-arg Sends on a
            // non-Class receiver whose method isn't a known AR/stdlib
            // call render without parens (`p.Title`, not `p.Title()`).
            let is_class_call = matches!(&*r.node, ExprNode::Const { .. });
            if !is_class_call && args_s.is_empty() && !is_known_go_method(method) {
                return format!("{recv_s}.{go_m}");
            }
            format!("{}.{}({})", recv_s, go_m, args_s.join(", "))
        }
    }
}

/// AR/stdlib method names that should emit with parens on a model
/// struct receiver. Everything else on a non-Class receiver with no
/// args is treated as a field read. Grows alongside the runtime.
fn is_known_go_method(name: &str) -> bool {
    matches!(
        name,
        "save" | "save!" | "destroy" | "destroy!" | "update" | "update!"
            | "delete" | "touch" | "reload"
            | "validate" | "attributes" | "errors"
    )
}

/// Map Ruby String methods onto Go expressions that compile. `strip`
/// in Ruby is `strings.TrimSpace(s)` in Go — no method form exists.
/// Returns `Some(emit_text)` for a handled method. Unhandled methods
/// fall through to the default `.Method()` emit which may or may not
/// compile depending on the target receiver's actual methods.
fn map_go_str_method(method: &str, recv_text: &str) -> Option<String> {
    match method {
        "strip" => Some(format!("strings.TrimSpace({recv_text})")),
        "upcase" => Some(format!("strings.ToUpper({recv_text})")),
        "downcase" => Some(format!("strings.ToLower({recv_text})")),
        _ => None,
    }
}

fn emit_block_body(e: &Expr) -> String {
    let raw = match &*e.node {
        ExprNode::Seq { exprs } => exprs
            .iter()
            .map(emit_expr)
            .collect::<Vec<_>>()
            .join("\n"),
        _ => emit_expr(e),
    };
    raw.lines().map(|l| format!("\t{l}")).collect::<Vec<_>>().join("\n")
}

fn emit_literal(lit: &Literal) -> String {
    match lit {
        Literal::Nil => "nil".to_string(),
        Literal::Bool { value } => value.to_string(),
        Literal::Int { value } => value.to_string(),
        Literal::Float { value } => {
            let s = value.to_string();
            if s.contains('.') { s } else { format!("{s}.0") }
        }
        Literal::Str { value } => format!("{value:?}"),
        Literal::Sym { value } => format!("{:?}", value.as_str()),
    }
}

// Types ----------------------------------------------------------------

pub fn go_ty(ty: &Ty) -> String {
    match ty {
        Ty::Int => "int64".to_string(),
        Ty::Float => "float64".to_string(),
        Ty::Bool => "bool".to_string(),
        Ty::Str | Ty::Sym => "string".to_string(),
        Ty::Nil => "struct{}".to_string(),
        Ty::Array { elem } => format!("[]{}", go_ty(elem)),
        Ty::Hash { key, value } => format!("map[{}]{}", go_ty(key), go_ty(value)),
        Ty::Tuple { elems } => {
            // Go has no tuple; collapse to interface{} for now.
            let _ = elems;
            "interface{}".to_string()
        }
        Ty::Record { .. } => "map[string]interface{}".to_string(),
        Ty::Union { variants } => option_shape(variants).unwrap_or_else(|| {
            // Arbitrary union -> empty interface; would be a sum type emit later.
            "interface{}".to_string()
        }),
        Ty::Class { id, .. } => match id.0.as_str() {
            // Schema DateTime/Date/Time columns carry Ty::Class(Time); Go
            // has a time package (`time.Time`) but wiring that import
            // into emit adds complexity. String is the same pragmatic
            // stand-in Rust uses; real timestamps arrive when a DB
            // adapter does.
            "Time" => "string".to_string(),
            other => other.to_string(),
        },
        Ty::Fn { .. } => "func()".to_string(),
        Ty::Var { .. } => "interface{}".to_string(),
    }
}

fn option_shape(variants: &[Ty]) -> Option<String> {
    if variants.len() != 2 {
        return None;
    }
    match (&variants[0], &variants[1]) {
        (Ty::Nil, other) | (other, Ty::Nil) => Some(format!("*{}", go_ty(other))),
        _ => None,
    }
}

// Naming ---------------------------------------------------------------

fn go_field_name(ruby_name: &str) -> String {
    // Convert snake_case to PascalCase, special-casing common initialisms.
    ruby_name
        .split('_')
        .map(|part| match part {
            "id" => "ID".to_string(),
            "url" => "URL".to_string(),
            "http" => "HTTP".to_string(),
            "json" => "JSON".to_string(),
            "html" => "HTML".to_string(),
            "api" => "API".to_string(),
            other => pascalize_word(other),
        })
        .collect::<String>()
}

fn go_method_name(ruby_name: &str) -> String {
    ruby_name
        .split('_')
        .map(|part| match part {
            "id" => "ID".to_string(),
            other => pascalize_word(other),
        })
        .collect::<String>()
}

fn pascalize_word(word: &str) -> String {
    let mut chars = word.chars();
    match chars.next() {
        Some(c) => c.to_ascii_uppercase().to_string() + chars.as_str(),
        None => String::new(),
    }
}

/// Pre-emit rewrite for model method bodies: turn any bare-name Send
/// whose method matches a model attribute into a receiver-prefixed
/// Send. Ruby's implicit self becomes Go's explicit receiver variable
/// (`p` on `Post`, `c` on `Comment`, etc.). Emit then renders the
/// outer Send as `p.Title` — modulo go_method_name PascalCasing the
/// field, matching the struct definition.
fn rewrite_bare_attrs_to_receiver(
    e: &Expr,
    attrs: &[Symbol],
    receiver_var: &str,
) -> Expr {
    use crate::expr::{Arm, InterpPart, Pattern};
    use crate::ident::VarId;
    let rewrite = |child: &Expr| rewrite_bare_attrs_to_receiver(child, attrs, receiver_var);
    let receiver_ref = |span: crate::span::Span| Expr {
        span,
        node: Box::new(ExprNode::Var {
            id: VarId(0),
            name: Symbol::from(receiver_var),
        }),
        ty: None,
        leading_blank_line: false,
    };
    let new_node = match &*e.node {
        ExprNode::Send { recv: None, method, args, block: None, parenthesized }
            if args.is_empty() && attrs.iter().any(|s| s == method) =>
        {
            ExprNode::Send {
                recv: Some(receiver_ref(e.span)),
                method: method.clone(),
                args: vec![],
                block: None,
                parenthesized: *parenthesized,
            }
        }
        ExprNode::Send { recv, method, args, block, parenthesized } => ExprNode::Send {
            recv: recv.as_ref().map(&rewrite),
            method: method.clone(),
            args: args.iter().map(&rewrite).collect(),
            block: block.as_ref().map(&rewrite),
            parenthesized: *parenthesized,
        },
        ExprNode::Seq { exprs } => ExprNode::Seq {
            exprs: exprs.iter().map(&rewrite).collect(),
        },
        ExprNode::Array { elements, style } => ExprNode::Array {
            elements: elements.iter().map(&rewrite).collect(),
            style: *style,
        },
        ExprNode::Hash { entries, braced } => ExprNode::Hash {
            entries: entries.iter().map(|(k, v)| (rewrite(k), rewrite(v))).collect(),
            braced: *braced,
        },
        ExprNode::If { cond, then_branch, else_branch } => ExprNode::If {
            cond: rewrite(cond),
            then_branch: rewrite(then_branch),
            else_branch: rewrite(else_branch),
        },
        ExprNode::Case { scrutinee, arms } => ExprNode::Case {
            scrutinee: rewrite(scrutinee),
            arms: arms
                .iter()
                .map(|arm| Arm {
                    pattern: arm.pattern.clone(),
                    guard: arm.guard.as_ref().map(&rewrite),
                    body: rewrite(&arm.body),
                })
                .collect(),
        },
        ExprNode::BoolOp { op, surface, left, right } => ExprNode::BoolOp {
            op: *op,
            surface: *surface,
            left: rewrite(left),
            right: rewrite(right),
        },
        ExprNode::StringInterp { parts } => ExprNode::StringInterp {
            parts: parts
                .iter()
                .map(|p| match p {
                    InterpPart::Text { value } => InterpPart::Text { value: value.clone() },
                    InterpPart::Expr { expr } => InterpPart::Expr { expr: rewrite(expr) },
                })
                .collect(),
        },
        ExprNode::Let { id, name, value, body } => ExprNode::Let {
            id: *id,
            name: name.clone(),
            value: rewrite(value),
            body: rewrite(body),
        },
        ExprNode::Lambda { params, block_param, body, block_style } => ExprNode::Lambda {
            params: params.clone(),
            block_param: block_param.clone(),
            body: rewrite(body),
            block_style: *block_style,
        },
        ExprNode::Apply { fun, args, block } => ExprNode::Apply {
            fun: rewrite(fun),
            args: args.iter().map(&rewrite).collect(),
            block: block.as_ref().map(&rewrite),
        },
        ExprNode::Assign { target, value } => {
            let new_target = match target {
                LValue::Var { id, name } => LValue::Var { id: *id, name: name.clone() },
                LValue::Ivar { name } => LValue::Ivar { name: name.clone() },
                LValue::Attr { recv, name } => LValue::Attr {
                    recv: rewrite(recv),
                    name: name.clone(),
                },
                LValue::Index { recv, index } => LValue::Index {
                    recv: rewrite(recv),
                    index: rewrite(index),
                },
            };
            ExprNode::Assign {
                target: new_target,
                value: rewrite(value),
            }
        }
        ExprNode::Yield { args } => ExprNode::Yield {
            args: args.iter().map(&rewrite).collect(),
        },
        ExprNode::Raise { value } => ExprNode::Raise { value: rewrite(value) },
        ExprNode::RescueModifier { expr, fallback } => ExprNode::RescueModifier {
            expr: rewrite(expr),
            fallback: rewrite(fallback),
        },
        // Leaves.
        ExprNode::Lit { .. }
        | ExprNode::Var { .. }
        | ExprNode::Ivar { .. }
        | ExprNode::Const { .. } => (*e.node).clone(),
    };
    let _ = Pattern::Wildcard;
    Expr {
        span: e.span,
        node: Box::new(new_node),
        ty: e.ty.clone(),
        leading_blank_line: e.leading_blank_line,
    }
}

// Validations, fixtures, tests ---------------------------------------

fn emit_validate_method_go(
    out: &mut String,
    model: &Model,
    validations: &[crate::lower::LoweredValidation],
) {
    let recv_var = receiver_letter(model);
    writeln!(
        out,
        "func ({recv_var} *{}) Validate() []ValidationError {{",
        model.name.0
    )
    .unwrap();
    writeln!(out, "\tvar errors []ValidationError").unwrap();
    for lv in validations {
        for check in &lv.checks {
            emit_check_inline_go(out, &recv_var, lv.attribute.as_str(), check);
        }
    }
    writeln!(out, "\treturn errors").unwrap();
    writeln!(out, "}}").unwrap();
}

/// Render Save/Destroy/Count/Find for a model against the test DB.
/// SQL strings come from LoweredPersistence; the per-target surface
/// is database/sql API shape, the `?N → ?` placeholder rewrite, and
/// class-method-as-package-function naming (`Article.count` →
/// `ArticleCount()`).
fn emit_persistence_methods_go(
    out: &mut String,
    model: &Model,
    has_validate: bool,
    app: &App,
) {
    let lp = crate::lower::lower_persistence(model, app);
    let class = lp.class.0.as_str();
    let recv = receiver_letter(model);

    let insert_sql = positional_placeholders_go(&lp.insert_sql);
    let update_sql = positional_placeholders_go(&lp.update_sql);
    let delete_sql = positional_placeholders_go(&lp.delete_sql);
    let select_by_id_sql = positional_placeholders_go(&lp.select_by_id_sql);

    let non_id_args: Vec<String> = lp
        .non_id_columns
        .iter()
        .map(|s| format!("{recv}.{}", go_field_name(s.as_str())))
        .collect();

    // ----- Save -----
    writeln!(out, "func ({recv} *{class}) Save() bool {{").unwrap();
    if has_validate {
        writeln!(out, "\tif len({recv}.Validate()) > 0 {{ return false }}").unwrap();
    }
    // belongs_to existence: FK must be non-zero and refer to an
    // existing row in the target table.
    for check in &lp.belongs_to_checks {
        let fk_field = go_field_name(check.foreign_key.as_str());
        let target = check.target_class.0.as_str();
        writeln!(
            out,
            "\tif {recv}.{fk_field} == 0 || {target}Find({recv}.{fk_field}) == nil {{ return false }}",
        )
        .unwrap();
    }
    writeln!(out, "\tdb := Conn()").unwrap();
    writeln!(out, "\tif {recv}.ID == 0 {{").unwrap();
    writeln!(
        out,
        "\t\tres, err := db.Exec({insert_sql:?}, {})",
        non_id_args.join(", "),
    )
    .unwrap();
    writeln!(out, "\t\tif err != nil {{ panic(err) }}").unwrap();
    writeln!(out, "\t\tid, _ := res.LastInsertId()").unwrap();
    writeln!(out, "\t\t{recv}.ID = id").unwrap();
    writeln!(out, "\t}} else {{").unwrap();
    writeln!(
        out,
        "\t\t_, err := db.Exec({update_sql:?}, {}, {recv}.ID)",
        non_id_args.join(", "),
    )
    .unwrap();
    writeln!(out, "\t\tif err != nil {{ panic(err) }}").unwrap();
    writeln!(out, "\t}}").unwrap();
    writeln!(out, "\treturn true").unwrap();
    writeln!(out, "}}").unwrap();

    // ----- Destroy -----
    writeln!(out).unwrap();
    writeln!(out, "func ({recv} *{class}) Destroy() {{").unwrap();
    for dc in &lp.dependent_children {
        let child_class = dc.child_class.0.as_str();
        let child_select = positional_placeholders_go(&dc.select_by_parent_sql);
        writeln!(out, "\t{{").unwrap();
        writeln!(
            out,
            "\t\trows, err := Conn().Query({child_select:?}, {recv}.ID)",
        )
        .unwrap();
        writeln!(out, "\t\tif err != nil {{ panic(err) }}").unwrap();
        writeln!(out, "\t\tvar children []{child_class}").unwrap();
        writeln!(out, "\t\tfor rows.Next() {{").unwrap();
        writeln!(out, "\t\t\tvar c {child_class}").unwrap();
        let scans: Vec<String> = dc
            .child_columns
            .iter()
            .map(|s| format!("&c.{}", go_field_name(s.as_str())))
            .collect();
        writeln!(out, "\t\t\tif err := rows.Scan({}); err != nil {{ panic(err) }}", scans.join(", ")).unwrap();
        writeln!(out, "\t\t\tchildren = append(children, c)").unwrap();
        writeln!(out, "\t\t}}").unwrap();
        writeln!(out, "\t\trows.Close()").unwrap();
        writeln!(out, "\t\tfor i := range children {{").unwrap();
        writeln!(out, "\t\t\tchildren[i].Destroy()").unwrap();
        writeln!(out, "\t\t}}").unwrap();
        writeln!(out, "\t}}").unwrap();
    }
    writeln!(
        out,
        "\tif _, err := Conn().Exec({delete_sql:?}, {recv}.ID); err != nil {{ panic(err) }}",
    )
    .unwrap();
    writeln!(out, "}}").unwrap();

    // ----- Count (package-level function, since Go has no class methods) -----
    writeln!(out).unwrap();
    writeln!(out, "func {class}Count() int64 {{").unwrap();
    writeln!(out, "\tvar n int64").unwrap();
    writeln!(
        out,
        "\tif err := Conn().QueryRow({:?}).Scan(&n); err != nil {{ panic(err) }}",
        lp.count_sql,
    )
    .unwrap();
    writeln!(out, "\treturn n").unwrap();
    writeln!(out, "}}").unwrap();

    // ----- Find (package-level function) -----
    writeln!(out).unwrap();
    writeln!(out, "func {class}Find(id int64) *{class} {{").unwrap();
    writeln!(
        out,
        "\trow := Conn().QueryRow({select_by_id_sql:?}, id)",
    )
    .unwrap();
    writeln!(out, "\tvar r {class}").unwrap();
    let scans: Vec<String> = lp
        .columns
        .iter()
        .map(|s| format!("&r.{}", go_field_name(s.as_str())))
        .collect();
    writeln!(
        out,
        "\tif err := row.Scan({}); err != nil {{ return nil }}",
        scans.join(", ")
    )
    .unwrap();
    writeln!(out, "\treturn &r").unwrap();
    writeln!(out, "}}").unwrap();
}

/// SQLite `?N` → database/sql `?`. `database/sql` doesn't support
/// numbered placeholders in the same positional style; drop the
/// trailing digits.
fn positional_placeholders_go(sql: &str) -> String {
    let mut out = String::new();
    let chars: Vec<char> = sql.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        if chars[i] == '?' {
            out.push('?');
            i += 1;
            while i < chars.len() && chars[i].is_ascii_digit() {
                i += 1;
            }
        } else {
            out.push(chars[i]);
            i += 1;
        }
    }
    out
}

fn receiver_letter(model: &Model) -> String {
    model
        .name
        .0
        .as_str()
        .chars()
        .next()
        .unwrap_or('r')
        .to_ascii_lowercase()
        .to_string()
}

fn emit_check_inline_go(
    out: &mut String,
    recv: &str,
    attr: &str,
    check: &crate::lower::Check,
) {
    use crate::lower::Check;
    let field = go_field_name(attr);
    let msg = check.default_message();
    let push = |cond: &str| -> String {
        format!(
            "\tif {cond} {{\n\t\terrors = append(errors, NewValidationError({attr:?}, {msg:?}))\n\t}}"
        )
    };
    let block = match check {
        Check::Presence => push(&format!("{recv}.{field} == \"\"")),
        Check::Absence => push(&format!("{recv}.{field} != \"\"")),
        Check::MinLength { n } => push(&format!("len({recv}.{field}) < {n}")),
        Check::MaxLength { n } => push(&format!("len({recv}.{field}) > {n}")),
        Check::GreaterThan { threshold } => push(&format!("{recv}.{field} <= {threshold}")),
        Check::LessThan { threshold } => push(&format!("{recv}.{field} >= {threshold}")),
        Check::OnlyInteger => {
            format!("\t// OnlyInteger on {attr:?} — enforced by Go's type system")
        }
        Check::Inclusion { values } => {
            let parts: Vec<String> =
                values.iter().map(inclusion_value_to_go).collect();
            // Emit an inline membership check via a switch-style OR.
            let cond = parts
                .iter()
                .map(|p| format!("{recv}.{field} != {p}"))
                .collect::<Vec<_>>()
                .join(" && ");
            push(&cond)
        }
        Check::Format { pattern } => {
            format!("\t// TODO: Format check on {attr:?} requires runtime regex ({pattern:?})")
        }
        Check::Uniqueness { .. } => {
            format!("\t// TODO: Uniqueness on {attr:?} requires DB access at runtime")
        }
        Check::Custom { method } => {
            format!("\t{recv}.{}(errors)", go_field_name(method.as_str()))
        }
    };
    writeln!(out, "{block}").unwrap();
}

fn inclusion_value_to_go(v: &crate::lower::InclusionValue) -> String {
    use crate::lower::InclusionValue;
    match v {
        InclusionValue::Str { value } => format!("{value:?}"),
        InclusionValue::Int { value } => value.to_string(),
        InclusionValue::Float { value } => {
            let s = value.to_string();
            if s.contains('.') { s } else { format!("{s}.0") }
        }
        InclusionValue::Bool { value } => value.to_string(),
    }
}

fn emit_go_fixtures(app: &App) -> EmittedFile {
    // Single file `app/fixtures_test.go` keeps fixtures inside the
    // package's test build (not shipped in production). Go's `_test.go`
    // suffix excludes files from `go build`; `go test` picks them up.
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s, "package app").unwrap();

    for fixture in &app.fixtures {
        let class_name = crate::naming::singularize_camelize(fixture.name.as_str());
        let model = app
            .models
            .iter()
            .find(|m| m.name.0.as_str() == class_name.as_str());
        let ns = go_field_name(fixture.name.as_str());
        for (i, (label, fields)) in fixture.records.iter().enumerate() {
            let id = (i as i64) + 1;
            let label_pascal = go_field_name(label.as_str());
            writeln!(s).unwrap();
            writeln!(
                s,
                "func {ns}{label_pascal}() *{class_name} {{",
            )
            .unwrap();
            writeln!(s, "\tr := &{class_name}{{}}").unwrap();
            writeln!(s, "\tr.ID = {id}").unwrap();
            if let Some(m) = model {
                for (field, value) in fields {
                    if let Some((col, go_val)) = resolve_fixture_field_go(field, value, m, app)
                    {
                        writeln!(s, "\tr.{} = {go_val}", go_field_name(&col)).unwrap();
                    }
                }
            }
            writeln!(s, "\treturn r").unwrap();
            writeln!(s, "}}").unwrap();
        }
    }

    EmittedFile {
        path: PathBuf::from("app/fixtures_test.go"),
        content: s,
    }
}

fn resolve_fixture_field_go(
    field: &crate::ident::Symbol,
    value: &str,
    model: &Model,
    app: &App,
) -> Option<(String, String)> {
    if let Some(ty) = model.attributes.fields.get(field) {
        return Some((field.as_str().to_string(), go_literal_for(value, ty)));
    }
    for assoc in model.associations() {
        if let Association::BelongsTo { name, target, foreign_key, .. } = assoc {
            if name == field {
                let target_table = crate::naming::pluralize_snake(target.0.as_str());
                if let Some(target_fixture) = app
                    .fixtures
                    .iter()
                    .find(|f| f.name.as_str() == target_table.as_str())
                {
                    if let Some(idx) = target_fixture
                        .records
                        .keys()
                        .position(|k| k.as_str() == value)
                    {
                        let resolved_id = (idx as i64) + 1;
                        return Some((
                            foreign_key.as_str().to_string(),
                            resolved_id.to_string(),
                        ));
                    }
                }
            }
        }
    }
    None
}

fn go_literal_for(value: &str, ty: &Ty) -> String {
    match ty {
        Ty::Str | Ty::Sym => format!("{value:?}"),
        Ty::Int => {
            if value.parse::<i64>().is_ok() {
                value.to_string()
            } else {
                format!("0 /* TODO: coerce {value:?} */")
            }
        }
        Ty::Float => {
            if value.parse::<f64>().is_ok() {
                value.to_string()
            } else {
                format!("0.0 /* TODO: coerce {value:?} */")
            }
        }
        Ty::Bool => match value {
            "true" | "1" => "true".into(),
            "false" | "0" => "false".into(),
            _ => format!("false /* TODO: coerce {value:?} */"),
        },
        Ty::Class { id, .. } if id.0.as_str() == "Time" => format!("{value:?}"),
        _ => format!("{value:?}"),
    }
}

fn emit_go_tests(tm: &TestModule, app: &App) -> EmittedFile {
    let fixture_names: Vec<crate::ident::Symbol> =
        app.fixtures.iter().map(|f| f.name.clone()).collect();
    let known_models: Vec<crate::ident::Symbol> =
        app.models.iter().map(|m| m.name.0.clone()).collect();
    let mut attrs_set: std::collections::BTreeSet<crate::ident::Symbol> =
        std::collections::BTreeSet::new();
    for m in &app.models {
        for attr in m.attributes.fields.keys() {
            attrs_set.insert(attr.clone());
        }
    }
    let model_attrs: Vec<crate::ident::Symbol> = attrs_set.into_iter().collect();

    let ctx = GoTestCtx {
        fixture_names: &fixture_names,
        known_models: &known_models,
        model_attrs: &model_attrs,
    };

    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s, "package app").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "import \"testing\"").unwrap();

    for test in &tm.tests {
        let fn_name = format!("Test{}", go_field_name(&test_name_snake(&test.name)));
        writeln!(s).unwrap();
        writeln!(s, "func {fn_name}(t *testing.T) {{").unwrap();
        if test_needs_runtime_unsupported_go(test) {
            writeln!(
                s,
                "\tt.Skip(\"Phase 3: needs persistence runtime\")"
            )
            .unwrap();
        } else {
            let body = emit_test_body_go(&test.body, ctx);
            for line in body.lines() {
                writeln!(s, "\t{line}").unwrap();
            }
        }
        writeln!(s, "}}").unwrap();
    }

    let filename = snake_case(tm.name.0.as_str());
    let filename = filename.replace("_test", "");
    EmittedFile {
        path: PathBuf::from(format!("app/{filename}_test.go")),
        content: s,
    }
}

fn test_name_snake(desc: &str) -> String {
    let mut s: String = desc
        .chars()
        .map(|c| if c.is_alphanumeric() { c.to_ascii_lowercase() } else { '_' })
        .collect();
    while s.contains("__") {
        s = s.replace("__", "_");
    }
    s.trim_matches('_').to_string()
}

#[derive(Clone, Copy)]
struct GoTestCtx<'a> {
    fixture_names: &'a [crate::ident::Symbol],
    known_models: &'a [crate::ident::Symbol],
    model_attrs: &'a [crate::ident::Symbol],
}

fn emit_test_body_go(body: &Expr, ctx: GoTestCtx) -> String {
    match &*body.node {
        ExprNode::Seq { exprs } if !exprs.is_empty() => exprs
            .iter()
            .map(|e| emit_test_stmt_go(e, ctx))
            .collect::<Vec<_>>()
            .join("\n"),
        _ => emit_test_stmt_go(body, ctx),
    }
}

fn emit_test_stmt_go(e: &Expr, ctx: GoTestCtx) -> String {
    match &*e.node {
        ExprNode::Assign { target: LValue::Var { name, .. }, value } => {
            format!("{} := {}", name, emit_test_expr_go(value, ctx))
        }
        _ => emit_test_expr_go(e, ctx),
    }
}

fn emit_test_expr_go(e: &Expr, ctx: GoTestCtx) -> String {
    match &*e.node {
        ExprNode::Lit { value } => emit_literal(value),
        ExprNode::Var { name, .. } => name.to_string(),
        ExprNode::Const { path } => path
            .iter()
            .map(|s| s.to_string())
            .collect::<Vec<_>>()
            .join("."),
        ExprNode::Send { recv, method, args, .. } => {
            emit_test_send_go(recv.as_ref(), method.as_str(), args, ctx)
        }
        ExprNode::Hash { entries, .. } => {
            // Rough: only used inside Class.new(hash) — handled above.
            let parts: Vec<String> = entries
                .iter()
                .map(|(k, v)| format!("{}: {}", emit_test_expr_go(k, ctx), emit_test_expr_go(v, ctx)))
                .collect();
            format!("map[string]interface{{}}{{{}}}", parts.join(", "))
        }
        ExprNode::BoolOp { op, left, right, .. } => {
            use crate::expr::BoolOpKind;
            let op_s = match op {
                BoolOpKind::Or => "||",
                BoolOpKind::And => "&&",
            };
            format!(
                "{} {} {}",
                emit_test_expr_go(left, ctx),
                op_s,
                emit_test_expr_go(right, ctx)
            )
        }
        _ => format!("/* TODO: Go test emit for {:?} */", std::mem::discriminant(&*e.node)),
    }
}

fn emit_test_send_go(
    recv: Option<&Expr>,
    method: &str,
    args: &[Expr],
    ctx: GoTestCtx,
) -> String {
    let args_s: Vec<String> = args.iter().map(|a| emit_test_expr_go(a, ctx)).collect();

    // Fixture accessor: articles(:one) → ArticlesOne()
    if recv.is_none()
        && args.len() == 1
        && ctx.fixture_names.iter().any(|s| s.as_str() == method)
    {
        if let ExprNode::Lit { value: Literal::Sym { value: sym } } = &*args[0].node {
            return format!(
                "{}{}()",
                go_field_name(method),
                go_field_name(sym.as_str())
            );
        }
    }

    // Assertion macros → Go's inline `if ... { t.Errorf(...) }` pattern.
    if recv.is_none() {
        match (method, args_s.len()) {
            ("assert_equal", 2) => {
                return format!(
                    "if {actual} != {expected} {{ t.Errorf(\"expected %v, got %v\", {expected}, {actual}) }}",
                    expected = args_s[0],
                    actual = args_s[1],
                );
            }
            ("assert_not_equal", 2) => {
                return format!(
                    "if {actual} == {expected} {{ t.Errorf(\"expected not equal to %v\", {expected}) }}",
                    expected = args_s[0],
                    actual = args_s[1],
                );
            }
            ("assert_not", 1) => {
                return format!(
                    "if {cond} {{ t.Errorf(\"expected false\") }}",
                    cond = args_s[0]
                );
            }
            ("assert", 1) => {
                return format!(
                    "if !({cond}) {{ t.Errorf(\"expected true\") }}",
                    cond = args_s[0]
                );
            }
            ("assert_nil", 1) => {
                // Go's "nil-ness" varies. Ints test against zero; pointers
                // against nil. We pick based on whether the arg expression
                // looks like a method chain (assume it's a primitive value).
                return format!(
                    "if {expr} != 0 {{ t.Errorf(\"expected zero/nil, got %v\", {expr}) }}",
                    expr = args_s[0]
                );
            }
            ("assert_not_nil", 1) => {
                return format!(
                    "if {expr} == 0 {{ t.Errorf(\"expected non-zero\") }}",
                    expr = args_s[0]
                );
            }
            _ => {}
        }
    }

    // `Class.new(hash)` → `&Class{ Field: val, ... }` struct literal.
    if let Some(r) = recv {
        if method == "new" && args.len() == 1 {
            if let ExprNode::Const { path } = &*r.node {
                if let Some(class_name) = path.last() {
                    if ctx.known_models.iter().any(|s| s == class_name) {
                        if let ExprNode::Hash { entries, .. } = &*args[0].node {
                            let pairs: Vec<String> = entries
                                .iter()
                                .filter_map(|(k, v)| {
                                    if let ExprNode::Lit {
                                        value: Literal::Sym { value: f },
                                    } = &*k.node
                                    {
                                        Some(format!(
                                            "{}: {}",
                                            go_field_name(f.as_str()),
                                            emit_test_expr_go(v, ctx)
                                        ))
                                    } else {
                                        None
                                    }
                                })
                                .collect();
                            return format!(
                                "&{}{{{}}}",
                                class_name,
                                pairs.join(", ")
                            );
                        }
                    }
                }
            }
        }
    }

    match recv {
        None => {
            if args_s.is_empty() {
                method.to_string()
            } else {
                format!("{}({})", method, args_s.join(", "))
            }
        }
        Some(r) => {
            let recv_s = emit_test_expr_go(r, ctx);
            let is_class_call = matches!(&*r.node, ExprNode::Const { .. });
            let is_attr = !is_class_call
                && args_s.is_empty()
                && ctx.model_attrs.iter().any(|s| s.as_str() == method);
            if is_attr {
                format!("{recv_s}.{}", go_field_name(method))
            } else if args_s.is_empty() {
                format!("{recv_s}.{}()", go_field_name(method))
            } else {
                format!(
                    "{recv_s}.{}({})",
                    go_field_name(method),
                    args_s.join(", ")
                )
            }
        }
    }
}

fn test_needs_runtime_unsupported_go(test: &Test) -> bool {
    let known_name = matches!(test.name.as_str(), "requires valid article");
    if known_name {
        return true;
    }
    test_body_uses_unsupported_go(&test.body)
}

fn test_body_uses_unsupported_go(e: &Expr) -> bool {
    use crate::expr::InterpPart;
    let self_hit = match &*e.node {
        ExprNode::Send { recv, method, .. } => {
            let m = method.as_str();
            matches!(
                m,
                "assert_difference"
                    | "destroy"
                    | "destroy!"
                    | "build"
                    | "create"
                    | "create!"
            ) || (m == "count"
                && recv.as_ref().is_some_and(|r| matches!(&*r.node, ExprNode::Const { .. })))
        }
        _ => false,
    };
    if self_hit {
        return true;
    }
    match &*e.node {
        ExprNode::Send { recv, args, block, .. } => {
            if let Some(r) = recv {
                if test_body_uses_unsupported_go(r) {
                    return true;
                }
            }
            for a in args {
                if test_body_uses_unsupported_go(a) {
                    return true;
                }
            }
            if let Some(b) = block {
                if test_body_uses_unsupported_go(b) {
                    return true;
                }
            }
        }
        ExprNode::Seq { exprs } | ExprNode::Array { elements: exprs, .. } => {
            for e in exprs {
                if test_body_uses_unsupported_go(e) {
                    return true;
                }
            }
        }
        ExprNode::Hash { entries, .. } => {
            for (k, v) in entries {
                if test_body_uses_unsupported_go(k) || test_body_uses_unsupported_go(v) {
                    return true;
                }
            }
        }
        ExprNode::StringInterp { parts } => {
            for p in parts {
                if let InterpPart::Expr { expr } = p {
                    if test_body_uses_unsupported_go(expr) {
                        return true;
                    }
                }
            }
        }
        ExprNode::BoolOp { left, right, .. }
        | ExprNode::RescueModifier { expr: left, fallback: right } => {
            if test_body_uses_unsupported_go(left) || test_body_uses_unsupported_go(right) {
                return true;
            }
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            if test_body_uses_unsupported_go(cond)
                || test_body_uses_unsupported_go(then_branch)
                || test_body_uses_unsupported_go(else_branch)
            {
                return true;
            }
        }
        ExprNode::Let { value, body, .. } => {
            if test_body_uses_unsupported_go(value) || test_body_uses_unsupported_go(body) {
                return true;
            }
        }
        ExprNode::Lambda { body, .. } => {
            if test_body_uses_unsupported_go(body) {
                return true;
            }
        }
        ExprNode::Assign { value, .. } => {
            if test_body_uses_unsupported_go(value) {
                return true;
            }
        }
        _ => {}
    }
    false
}
