//! Go emitter.
//!
//! Second typed target. Differences from Rust that surface design choices:
//!
//! - Go has no Option / Result — nullable types are pointers (`*T`).
//! - Go has no class methods — `Post.All()` is pseudo-Go; a real mapping
//!   would use a repository pattern or package-level functions.
//! - Go requires explicit `return` for non-void functions and omits the
//!   return type entirely for void functions.
//! - Go convention: `ID`, `URL`, `HTTP` for initialism fields; PascalCase
//!   for exported identifiers, camelCase for unexported.
//! - Go uses tabs for indentation; gofmt would realign struct fields.
//!   We emit single-tab indent without alignment.
//!
//! Output is pseudo-Go — won't compile as-is. The goal is to prove that
//! types flow through to a second typed target without the Rust emitter
//! accidentally hiding ambiguities.

use std::fmt::Write;
use std::path::PathBuf;

use super::EmittedFile;
use crate::App;
use crate::dialect::{Action, Controller, MethodDef, Model, Test, TestModule};
use crate::expr::{Expr, ExprNode, LValue, Literal};
use crate::ident::Symbol;
use crate::naming::snake_case;
use crate::ty::Ty;

const RUNTIME_SOURCE: &str = include_str!("../../runtime/go/runtime.go");
const DB_SOURCE: &str = include_str!("../../runtime/go/db.go");
/// Go HTTP runtime — Phase 4c compile-only stubs. Copied verbatim into
/// generated projects as `app/http.go` whenever any controller emits.
/// Mirrors the Rust + Crystal twins; real HTTP behavior lands in a
/// later Phase 4 stage.
const HTTP_SOURCE: &str = include_str!("../../runtime/go/http.go");

pub fn emit(app: &App) -> Vec<EmittedFile> {
    let mut files = Vec::new();
    files.push(emit_go_mod());
    files.push(emit_go_sum());
    if !app.models.is_empty() {
        files.push(emit_models(app));
        files.push(EmittedFile {
            path: PathBuf::from("app/runtime.go"),
            content: RUNTIME_SOURCE.to_string(),
        });
        files.push(EmittedFile {
            path: PathBuf::from("app/db.go"),
            content: DB_SOURCE.to_string(),
        });
        files.push(emit_schema_sql_go(app));
    }
    if !app.controllers.is_empty() {
        // HTTP runtime, copied verbatim. Same posture as runtime.go /
        // db.go. Provides Response, ParamSet, RespondTo, Render,
        // RedirectTo, Head, FormatRouter.
        files.push(EmittedFile {
            path: PathBuf::from("app/http.go"),
            content: HTTP_SOURCE.to_string(),
        });
        let known_models: Vec<Symbol> =
            app.models.iter().map(|m| m.name.0.clone()).collect();
        for controller in &app.controllers {
            files.push(emit_controller(controller, &known_models));
        }
    }
    if !app.fixtures.is_empty() {
        files.push(emit_go_fixtures(app));
    }
    if !app.test_modules.is_empty() {
        for tm in &app.test_modules {
            files.push(emit_go_tests(tm, app));
        }
    }
    files
}

/// `go.mod` — module name `app`, targeting Go 1.24. Depends on
/// modernc.org/sqlite for the pure-Go SQLite driver that the Phase 3
/// persistence runtime uses. The toolchain test runs `go mod tidy`
/// before building to populate go.sum.
fn emit_go_mod() -> EmittedFile {
    let content = "module app\n\ngo 1.24\n\nrequire modernc.org/sqlite v1.34.1\n";
    EmittedFile {
        path: PathBuf::from("go.mod"),
        content: content.to_string(),
    }
}

/// Empty `go.sum` placeholder — `go mod tidy` populates it on first
/// build. Emitting the file up front avoids a chicken-and-egg where
/// `go vet` refuses to run without it.
fn emit_go_sum() -> EmittedFile {
    EmittedFile {
        path: PathBuf::from("go.sum"),
        content: String::new(),
    }
}

/// `app/schema_sql.go` — Go constant wrapping the target-neutral DDL
/// produced by `lower::lower_schema`. `SetupTestDB` splits it on
/// `;\n` and execs each statement against a fresh :memory: database.
fn emit_schema_sql_go(app: &App) -> EmittedFile {
    let ddl = crate::lower::lower_schema(&app.schema);
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s, "package app").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "const CreateTables = `").unwrap();
    s.push_str(&ddl);
    writeln!(s, "`").unwrap();
    EmittedFile {
        path: PathBuf::from("app/schema_sql.go"),
        content: s,
    }
}

// Models ---------------------------------------------------------------

fn emit_models(app: &App) -> EmittedFile {
    let mut body = String::new();
    for model in &app.models {
        writeln!(body).unwrap();
        emit_struct(&mut body, model);
        for method in model.methods() {
            writeln!(body).unwrap();
            emit_model_method(&mut body, model, method);
        }
        let lowered = crate::lower::lower_validations(model);
        if !lowered.is_empty() {
            writeln!(body).unwrap();
            emit_validate_method_go(&mut body, model, &lowered);
        }
        // Persistence emitted for any model with table columns beyond
        // `id`. Abstract base classes (ApplicationRecord) get skipped.
        let has_table = model
            .attributes
            .fields
            .keys()
            .any(|k| k.as_str() != "id");
        if has_table {
            writeln!(body).unwrap();
            emit_persistence_methods_go(&mut body, model, !lowered.is_empty(), app);
        }
    }
    // Conditional imports: scan the emitted body for package prefixes
    // that indicate which stdlib we need. Go errors on unused imports,
    // so we only emit what's actually referenced.
    let mut imports: Vec<&str> = Vec::new();
    if body.contains("strings.") {
        imports.push("strings");
    }

    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s, "package app").unwrap();
    if !imports.is_empty() {
        writeln!(s).unwrap();
        if imports.len() == 1 {
            writeln!(s, "import \"{}\"", imports[0]).unwrap();
        } else {
            writeln!(s, "import (").unwrap();
            for imp in &imports {
                writeln!(s, "\t\"{imp}\"").unwrap();
            }
            writeln!(s, ")").unwrap();
        }
    }
    s.push_str(&body);
    EmittedFile { path: PathBuf::from("app/models.go"), content: s }
}

fn emit_struct(out: &mut String, model: &Model) {
    writeln!(out, "type {} struct {{", model.name.0).unwrap();
    for (name, ty) in &model.attributes.fields {
        writeln!(out, "\t{} {}", go_field_name(name.as_str()), go_ty(ty)).unwrap();
    }
    writeln!(out, "}}").unwrap();
}

fn emit_model_method(out: &mut String, model: &Model, m: &MethodDef) {
    let ret_ty = m.body.ty.clone().unwrap_or(Ty::Nil);
    let method_name = go_method_name(m.name.as_str());
    let ret_annot = match &ret_ty {
        Ty::Nil => String::new(),
        other => format!(" {}", go_ty(other)),
    };
    let (receiver, receiver_var) = match m.receiver {
        crate::dialect::MethodReceiver::Instance => {
            // Single-letter receiver name — Go idiom (`p *Post`).
            let first = model
                .name
                .0
                .as_str()
                .chars()
                .next()
                .unwrap_or('r')
                .to_ascii_lowercase();
            (format!("({first} *{})", model.name.0), first.to_string())
        }
        crate::dialect::MethodReceiver::Class => {
            // Class method: emit as package-level function (pseudo-Go, since
            // Go has no class methods).
            (String::new(), String::new())
        }
    };
    let space_before_name = if receiver.is_empty() { "" } else { " " };
    writeln!(
        out,
        "func {}{}{}(){} {{",
        receiver, space_before_name, method_name, ret_annot,
    )
    .unwrap();
    // Pre-emit rewrite: bare `title` inside a method body → `p.Title`
    // (receiver-var + PascalCased field). Same pattern as the other
    // typed emitters; Go makes it the receiver variable rather than
    // `self`/`this`.
    let attrs: Vec<Symbol> = model.attributes.fields.keys().cloned().collect();
    let rewritten = if !receiver_var.is_empty() {
        rewrite_bare_attrs_to_receiver(&m.body, &attrs, &receiver_var)
    } else {
        m.body.clone()
    };
    let body_s = if matches!(ret_ty, Ty::Nil) {
        emit_expr(&rewritten)
    } else {
        format!("return {}", emit_expr(&rewritten))
    };
    for line in body_s.lines() {
        writeln!(out, "\t{}", line).unwrap();
    }
    writeln!(out, "}}").unwrap();
}

// Controllers ----------------------------------------------------------
//
// Phase 4c: controllers live flat under `app/` (same package as models
// and runtime) so the generated code can reference `Article`,
// `ArticleFind(id)`, etc. directly without cross-package imports. Each
// controller struct exposes every referenced ivar as a typed field
// (`c.article *Article`, `c.articles []*Article`) — Rails'
// before_action filters would set these; Phase 4c's tests stay
// `t.Skip`-ped so the fields never get populated at runtime.
//
// Rewrites for controller-body Sends:
//   * bare `params`          → `Params()`
//   * `params.expect(...)`   → `Params().Expect(...)`
//   * `params[k]`            → `Params().At(k)`
//   * `respond_to { |fmt| ... }` → `RespondTo(func(fr *FormatRouter)
//                              *Response { ... })`
//   * `format.html { body }` → `fr.Html(func() *Response { body })`
//   * `format.json { body }` → replaced by a `// TODO: JSON branch`
//   * bare `redirect_to` / `render` / `head` → package-level funcs
//   * `Model.new` / `Model.new(anything)` → `&Model{}`
//   * `Model.find(x)`        → existing `ModelFind(x)` (returns
//                              `*Model` — nullable via nil pointer;
//                              no `not_nil!` needed, the declared
//                              field type is already a pointer)
//   * `<assoc>.find/build/create(hash)` → `&Target{}` via
//                              singularization
//   * `x.destroy!` / `save!` / `update!` → `x.Destroy() / Save() /
//                              Update()` (Go forbids `!` in idents)
//   * bare `*_path` / `*_url` → `""`
//   * unsupported query chains → `[]*Target{}`

fn emit_controller(c: &Controller, known_models: &[Symbol]) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s, "package app").unwrap();
    writeln!(s).unwrap();

    let (public_actions, private_actions) =
        crate::lower::split_public_private(c);
    let self_methods: Vec<Symbol> = public_actions
        .iter()
        .chain(private_actions.iter())
        .map(|a| a.name.clone())
        .collect();

    // Collect every ivar referenced across actions so they become
    // struct fields — Go has no implicit `@name` scope. Type comes
    // from singularizing the name against `known_models` (pointer
    // for singular, slice of pointers for plural).
    let ivars = collect_controller_ivars_go(c, known_models);

    writeln!(s, "type {} struct {{", c.name.0).unwrap();
    for (name, ty) in &ivars {
        writeln!(s, "\t{name} {ty}").unwrap();
    }
    writeln!(s, "}}").unwrap();

    let ctx = GoCtx {
        self_methods: &self_methods,
        known_models,
        ivars: &ivars,
        in_controller: true,
    };

    for action in &public_actions {
        writeln!(s).unwrap();
        emit_action(&mut s, c, action, ctx);
    }
    for action in &private_actions {
        writeln!(s).unwrap();
        emit_private_helper(&mut s, c, action, ctx);
    }

    let fname = format!("app/{}.go", snake_case(c.name.0.as_str()));
    EmittedFile { path: PathBuf::from(fname), content: s }
}

fn emit_action(out: &mut String, c: &Controller, a: &Action, ctx: GoCtx) {
    let method_name = go_method_name(a.name.as_str());
    writeln!(
        out,
        "func (c *{}) {}() *Response {{",
        c.name.0, method_name,
    )
    .unwrap();
    let body = emit_action_body_go(&a.body, ctx);
    for line in body.lines() {
        writeln!(out, "\t{}", line).unwrap();
    }
    writeln!(out, "\treturn &Response{{}}").unwrap();
    writeln!(out, "}}").unwrap();
}

fn emit_private_helper(out: &mut String, c: &Controller, a: &Action, ctx: GoCtx) {
    // Private helpers collapse to a zero-value body — same posture as
    // Rust's `Default::default()` and Crystal's `crystal_default`.
    let method_name = go_method_name(a.name.as_str());
    let ret = a.body.ty.clone().unwrap_or(Ty::Nil);
    // Model-typed returns render as `*Model` so the body's `&Model{}`
    // default matches. `go_ty` emits bare `Model`, which works for
    // struct-valued fields but not for the pointer convention we use
    // in controller helpers.
    let ret_annot = match &ret {
        Ty::Nil => String::new(),
        Ty::Class { id, .. }
            if ctx.known_models.iter().any(|m| m.as_str() == id.0.as_str()) =>
        {
            format!(" *{}", id.0.as_str())
        }
        other => format!(" {}", go_ty(other)),
    };
    writeln!(
        out,
        "func (c *{}) {}(){} {{",
        c.name.0, method_name, ret_annot,
    )
    .unwrap();
    match &ret {
        Ty::Nil => {}
        other => {
            writeln!(out, "\treturn {}", go_default(other)).unwrap();
        }
    }
    writeln!(out, "}}").unwrap();
}

/// Render a zero-value expression for a given Ty (used as the body of
/// private helpers that Phase 4c doesn't wire semantically).
fn go_default(ty: &Ty) -> String {
    match ty {
        Ty::Int => "0".to_string(),
        Ty::Float => "0.0".to_string(),
        Ty::Bool => "false".to_string(),
        Ty::Str | Ty::Sym => "\"\"".to_string(),
        Ty::Nil => "nil".to_string(),
        Ty::Array { elem } => format!("[]{}{{}}", go_ty(elem)),
        Ty::Hash { .. } => "map[string]interface{}{}".to_string(),
        Ty::Class { id, .. } => match id.0.as_str() {
            "Time" => "time.Time{}".to_string(),
            other => format!("&{other}{{}}"),
        },
        _ => "nil".to_string(),
    }
}

/// Gather every ivar any action/helper references, paired with its
/// Go field type. `@article` → `*Article`; `@articles` → `[]*Article`;
/// fall back to `interface{}` when the name doesn't resolve to a
/// known model (no concrete type to guess). IR walk is shared with
/// Rust + Crystal via `lower::controller`.
fn collect_controller_ivars_go(
    c: &Controller,
    known_models: &[Symbol],
) -> Vec<(String, String)> {
    let mut seen = std::collections::BTreeSet::<String>::new();
    let mut out: Vec<(String, String)> = Vec::new();
    for action in c.actions() {
        let walked = crate::lower::walk_controller_ivars(&action.body);
        for name in walked.referenced {
            let name_s = name.as_str().to_string();
            if seen.insert(name_s.clone()) {
                let ty = guess_ivar_type_go(&name_s, known_models);
                out.push((name_s, ty));
            }
        }
    }
    out
}

fn guess_ivar_type_go(name: &str, known_models: &[Symbol]) -> String {
    let singular_class = crate::naming::singularize_camelize(name);
    let is_plural = singular_class.to_lowercase() != name.to_lowercase();
    if known_models.iter().any(|m| m.as_str() == singular_class) {
        return if is_plural {
            format!("[]*{singular_class}")
        } else {
            format!("*{singular_class}")
        };
    }
    // Non-model ivars fall back to an interface that accepts anything
    // — Phase 4c's fixtures don't hit this path, but the annotation
    // keeps Go's type-checker happy if they did.
    "interface{}".to_string()
}

/// Controller-scope emit context. Threaded through the Go Send
/// rewrites to pick up `in_controller`, the known model list, and the
/// controller's ivar → struct-field map.
#[derive(Clone, Copy, Default)]
struct GoCtx<'a> {
    self_methods: &'a [Symbol],
    known_models: &'a [Symbol],
    ivars: &'a [(String, String)],
    in_controller: bool,
}

impl<'a> GoCtx<'a> {
    fn has_ivar(&self, name: &str) -> bool {
        self.ivars.iter().any(|(n, _)| n == name)
    }
}

fn emit_action_body_go(body: &Expr, ctx: GoCtx) -> String {
    match &*body.node {
        ExprNode::Seq { exprs } if exprs.is_empty() => String::new(),
        ExprNode::Seq { exprs } => exprs
            .iter()
            .map(|e| emit_stmt_go_ctx(e, ctx))
            .collect::<Vec<_>>()
            .join("\n"),
        _ => emit_stmt_go_ctx(body, ctx),
    }
}

fn emit_stmt_go_ctx(e: &Expr, ctx: GoCtx) -> String {
    match &*e.node {
        ExprNode::Assign { target: LValue::Var { name, .. }, value } => {
            // Introduce locals with `:=`; Go will error on unused so
            // the emitter might prefer `_ = value` for purely-typed-
            // discard patterns. In practice the controller bodies
            // pair the binding with a later read, so `:=` is fine.
            format!("{} := {}", name, emit_expr_go_ctx(value, ctx))
        }
        ExprNode::Assign { target: LValue::Ivar { name }, value } => {
            // Ivars live on the controller struct — emit as
            // `c.name = ...`.
            format!("c.{} = {}", name, emit_expr_go_ctx(value, ctx))
        }
        _ => emit_expr_go_ctx(e, ctx),
    }
}

fn emit_expr_go_ctx(e: &Expr, ctx: GoCtx) -> String {
    match &*e.node {
        ExprNode::Ivar { name } => {
            // Ivars read via the receiver. Non-declared ivars
            // (shouldn't happen in practice) fall back to the bare
            // name — Go will error, signalling an ivar the walker
            // missed.
            if ctx.has_ivar(name.as_str()) {
                format!("c.{}", name)
            } else {
                name.to_string()
            }
        }
        ExprNode::Send { recv, method, args, block, .. } => {
            emit_send_go_ctx(recv.as_ref(), method.as_str(), args, block.as_ref(), ctx)
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            let cond_s = emit_expr_go_ctx(cond, ctx);
            let then_s = emit_block_body_go_ctx(then_branch, ctx);
            let else_s = emit_block_body_go_ctx(else_branch, ctx);
            format!("if {cond_s} {{\n{}\n}} else {{\n{}\n}}", then_s, else_s)
        }
        _ => emit_expr(e),
    }
}

fn emit_block_body_go_ctx(e: &Expr, ctx: GoCtx) -> String {
    let body = match &*e.node {
        ExprNode::Lambda { body, .. } => body,
        _ => e,
    };
    match &*body.node {
        ExprNode::Seq { exprs } if !exprs.is_empty() => exprs
            .iter()
            .map(|stmt| format!("\t{}", emit_stmt_go_ctx(stmt, ctx)))
            .collect::<Vec<_>>()
            .join("\n"),
        _ => format!("\t{}", emit_stmt_go_ctx(body, ctx)),
    }
}

fn emit_send_go_ctx(
    recv: Option<&Expr>,
    method: &str,
    args: &[Expr],
    block: Option<&Expr>,
    ctx: GoCtx,
) -> String {
    if ctx.in_controller {
        if let Some(s) = emit_controller_send_go(recv, method, args, block, ctx) {
            return s;
        }
    }
    // Fall back to a ctx-aware dispatch rather than the plain
    // `emit_send` — otherwise an Ivar recv (`@article.save`) emits as
    // bare `article` instead of `c.article`. Blocks drop off here;
    // the only controller block we care about (respond_to) is handled
    // in `emit_controller_send_go` above.
    let _ = block;
    let args_s: Vec<String> =
        args.iter().map(|a| emit_expr_go_ctx(a, ctx)).collect();
    if method == "[]" && recv.is_some() {
        return format!(
            "{}[{}]",
            emit_expr_go_ctx(recv.unwrap(), ctx),
            args_s.join(", "),
        );
    }
    let go_m = go_method_name(method);
    match recv {
        None => {
            if args_s.is_empty() {
                go_m
            } else {
                format!("{}({})", go_m, args_s.join(", "))
            }
        }
        Some(r) => {
            let recv_s = emit_expr_go_ctx(r, ctx);
            let is_class_call = matches!(&*r.node, ExprNode::Const { .. });
            if !is_class_call && args_s.is_empty() && !is_known_go_method(method) {
                return format!("{recv_s}.{go_m}");
            }
            format!("{}.{}({})", recv_s, go_m, args_s.join(", "))
        }
    }
}

fn emit_controller_send_go(
    recv: Option<&Expr>,
    method: &str,
    args: &[Expr],
    block: Option<&Expr>,
    ctx: GoCtx,
) -> Option<String> {
    use crate::lower::SendKind;
    // Render args with controller ctx so nested rewrites apply.
    let args_s: Vec<String> =
        args.iter().map(|a| emit_expr_go_ctx(a, ctx)).collect();

    // Self-method bare call doesn't go through the shared classifier
    // — it's specific to Go's struct-method dispatch (`c.Foo()`
    // syntax). Handled here before the classifier runs.
    if recv.is_none() && block.is_none() {
        if ctx.self_methods.iter().any(|s| s.as_str() == method) {
            let go_m = go_method_name(method);
            if args_s.is_empty() {
                return Some(format!("c.{go_m}()"));
            }
            return Some(format!("c.{go_m}({})", args_s.join(", ")));
        }
    }

    let kind =
        crate::lower::classify_controller_send(recv, method, args, block, ctx.known_models)?;
    Some(match kind {
        SendKind::ParamsAccess => "Params()".to_string(),
        SendKind::ParamsExpect { .. } => {
            format!("Params().Expect({})", args_s.join(", "))
        }
        SendKind::ParamsIndex { .. } => {
            let arg = args_s.first().cloned().unwrap_or_default();
            format!("Params().At({arg})")
        }

        SendKind::ModelNew { class } => format!("&{}{{}}", class.as_str()),

        SendKind::ModelFind { class, .. } => {
            // Go's ModelFind already returns *Model (nullable via
            // nil) — no unwrap wrapper needed.
            let arg = args_s.first().cloned().unwrap_or_default();
            format!("{}Find({arg})", class.as_str())
        }

        SendKind::AssocLookup { target, .. } => format!("&{}{{}}", target.as_str()),

        SendKind::QueryChain { target: Some(target) } => {
            format!("[]*{}{{}}", target.as_str())
        }
        SendKind::QueryChain { target: None } => "nil".to_string(),

        SendKind::PathOrUrlHelper => "\"\"".to_string(),

        SendKind::BangStrip { recv, stripped_method, .. } => {
            let recv_s = emit_expr_go_ctx(recv, ctx);
            let go_m = go_method_name(stripped_method);
            format!("{recv_s}.{go_m}()")
        }

        SendKind::InstanceUpdate => "false".to_string(),

        SendKind::Render { .. } => format!("Render({})", args_s.join(", ")),
        SendKind::RedirectTo { .. } => {
            format!("RedirectTo({})", args_s.join(", "))
        }
        SendKind::Head { .. } => format!("Head({})", args_s.join(", ")),

        SendKind::RespondToBlock { body } => {
            let body_s = emit_respond_to_body_go(body, ctx);
            format!(
                "RespondTo(func(fr *FormatRouter) *Response {{\n{}\n\treturn &Response{{}}\n}})",
                indent_go(&body_s, 1),
            )
        }

        SendKind::FormatHtml { body } => {
            let body_s = emit_respond_to_branch_body(body, ctx);
            format!(
                "fr.Html(func() *Response {{\n{}\n\treturn &Response{{}}\n}})",
                indent_go(&body_s, 1),
            )
        }

        SendKind::FormatJson => "// TODO: JSON branch (Phase 4e)".to_string(),
    })
}

fn emit_respond_to_body_go(body: &Expr, ctx: GoCtx) -> String {
    match &*body.node {
        ExprNode::Seq { exprs } => exprs
            .iter()
            .map(|e| emit_stmt_go_ctx(e, ctx))
            .collect::<Vec<_>>()
            .join("\n"),
        ExprNode::If { cond, then_branch, else_branch } => {
            let cond_s = emit_expr_go_ctx(cond, ctx);
            let then_s = emit_respond_to_body_go(then_branch, ctx);
            let else_s = emit_respond_to_body_go(else_branch, ctx);
            format!(
                "if {cond_s} {{\n{}\n}} else {{\n{}\n}}",
                indent_go(&then_s, 1),
                indent_go(&else_s, 1),
            )
        }
        _ => emit_stmt_go_ctx(body, ctx),
    }
}

fn emit_respond_to_branch_body(e: &Expr, ctx: GoCtx) -> String {
    let body = match &*e.node {
        ExprNode::Lambda { body, .. } => body,
        _ => e,
    };
    match &*body.node {
        ExprNode::Seq { exprs } => exprs
            .iter()
            .map(|stmt| emit_stmt_go_ctx(stmt, ctx))
            .collect::<Vec<_>>()
            .join("\n"),
        _ => emit_stmt_go_ctx(body, ctx),
    }
}

/// Indent every line with `n` tabs. Tabs match the rest of the Go
/// emitter's style.
fn indent_go(s: &str, n: usize) -> String {
    let prefix = "\t".repeat(n);
    s.lines()
        .map(|l| format!("{prefix}{l}"))
        .collect::<Vec<_>>()
        .join("\n")
}

// Body and expressions -------------------------------------------------

fn emit_body(body: &Expr, return_ty: &Ty) -> String {
    let is_void = matches!(return_ty, Ty::Nil);
    match &*body.node {
        ExprNode::Assign { target: LValue::Ivar { .. }, value } => {
            if is_void {
                emit_expr(value)
            } else {
                format!("return {}", emit_expr(value))
            }
        }
        ExprNode::Seq { exprs } if !exprs.is_empty() => {
            let mut lines: Vec<String> = Vec::new();
            for (i, e) in exprs.iter().enumerate() {
                lines.push(emit_stmt(e, i == exprs.len() - 1, is_void));
            }
            lines.join("\n")
        }
        _ => {
            if is_void {
                emit_expr(body)
            } else {
                format!("return {}", emit_expr(body))
            }
        }
    }
}

fn emit_stmt(e: &Expr, is_last: bool, void_return: bool) -> String {
    match &*e.node {
        // Local `foo = expr` and ivar `@foo = expr` both become `foo := expr`.
        ExprNode::Assign { target: LValue::Var { name, .. }, value } => {
            format!("{} := {}", name, emit_expr(value))
        }
        ExprNode::Assign { target: LValue::Ivar { name }, value } => {
            format!("{} := {}", name, emit_expr(value))
        }
        _ => {
            if is_last && !void_return {
                format!("return {}", emit_expr(e))
            } else {
                emit_expr(e)
            }
        }
    }
}

fn emit_expr(e: &Expr) -> String {
    match &*e.node {
        ExprNode::Lit { value } => emit_literal(value),
        ExprNode::Const { path } => {
            path.iter().map(|s| s.to_string()).collect::<Vec<_>>().join(".")
        }
        ExprNode::Var { name, .. } => name.to_string(),
        ExprNode::Ivar { name } => name.to_string(),
        ExprNode::Send { recv, method, args, .. } => emit_send(recv.as_ref(), method.as_str(), args),
        ExprNode::Assign { target: _, value } => emit_expr(value),
        ExprNode::Seq { exprs } => {
            exprs.iter().map(emit_expr).collect::<Vec<_>>().join("; ")
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            let cond_s = emit_expr(cond);
            let then_s = emit_block_body(then_branch);
            let else_s = emit_block_body(else_branch);
            format!("if {cond_s} {{\n{then_s}\n}} else {{\n{else_s}\n}}")
        }
        ExprNode::Hash { entries, .. } => {
            let parts: Vec<String> = entries
                .iter()
                .map(|(k, v)| format!("{}: {}", emit_expr(k), emit_expr(v)))
                .collect();
            format!("map[string]interface{{}}{{{}}}", parts.join(", "))
        }
        ExprNode::Array { elements, .. } => {
            let parts: Vec<String> = elements.iter().map(emit_expr).collect();
            format!("[]interface{{}}{{{}}}", parts.join(", "))
        }
        ExprNode::BoolOp { op, left, right, .. } => {
            use crate::expr::BoolOpKind;
            let op_s = match op {
                BoolOpKind::Or => "||",
                BoolOpKind::And => "&&",
            };
            format!("{} {} {}", emit_expr(left), op_s, emit_expr(right))
        }
        ExprNode::StringInterp { parts } => {
            use crate::expr::InterpPart;
            let mut fmt = String::new();
            let mut args: Vec<String> = Vec::new();
            for p in parts {
                match p {
                    InterpPart::Text { value } => {
                        for c in value.chars() {
                            if c == '%' {
                                fmt.push_str("%%");
                            } else {
                                fmt.push(c);
                            }
                        }
                    }
                    InterpPart::Expr { expr } => {
                        fmt.push_str("%v");
                        args.push(emit_expr(expr));
                    }
                }
            }
            if args.is_empty() {
                format!("{fmt:?}")
            } else {
                format!("fmt.Sprintf({fmt:?}, {})", args.join(", "))
            }
        }
        other => format!("/* TODO: emit {:?} */", std::mem::discriminant(other)),
    }
}

fn emit_send(recv: Option<&Expr>, method: &str, args: &[Expr]) -> String {
    let args_s: Vec<String> = args.iter().map(emit_expr).collect();

    if method == "[]" && recv.is_some() {
        return format!("{}[{}]", emit_expr(recv.unwrap()), args_s.join(", "));
    }

    // Ruby→Go method-name mapping for string operations that have no
    // 1:1 in Go's stdlib (`strip` is `strings.TrimSpace(…)`, not
    // `.Strip()`). Only kicks in for instance dispatch on Str-typed
    // receivers; class calls and unknown types pass through.
    if let Some(r) = recv {
        if args.is_empty() && matches!(r.ty, Some(Ty::Str)) {
            if let Some(wrapped) = map_go_str_method(method, &emit_expr(r)) {
                return wrapped;
            }
        }
    }

    let go_m = go_method_name(method);
    match recv {
        None => {
            if args_s.is_empty() {
                go_m
            } else {
                format!("{}({})", go_m, args_s.join(", "))
            }
        }
        Some(r) => {
            let recv_s = emit_expr(r);
            // Struct field access vs method call: 0-arg Sends on a
            // non-Class receiver whose method isn't a known AR/stdlib
            // call render without parens (`p.Title`, not `p.Title()`).
            let is_class_call = matches!(&*r.node, ExprNode::Const { .. });
            if !is_class_call && args_s.is_empty() && !is_known_go_method(method) {
                return format!("{recv_s}.{go_m}");
            }
            format!("{}.{}({})", recv_s, go_m, args_s.join(", "))
        }
    }
}

/// AR/stdlib method names that should emit with parens on a model
/// struct receiver. Everything else on a non-Class receiver with no
/// args is treated as a field read. Grows alongside the runtime.
fn is_known_go_method(name: &str) -> bool {
    matches!(
        name,
        "save" | "save!" | "destroy" | "destroy!" | "update" | "update!"
            | "delete" | "touch" | "reload"
            | "validate" | "attributes" | "errors"
    )
}

/// Map Ruby String methods onto Go expressions that compile. `strip`
/// in Ruby is `strings.TrimSpace(s)` in Go — no method form exists.
/// Returns `Some(emit_text)` for a handled method. Unhandled methods
/// fall through to the default `.Method()` emit which may or may not
/// compile depending on the target receiver's actual methods.
fn map_go_str_method(method: &str, recv_text: &str) -> Option<String> {
    match method {
        "strip" => Some(format!("strings.TrimSpace({recv_text})")),
        "upcase" => Some(format!("strings.ToUpper({recv_text})")),
        "downcase" => Some(format!("strings.ToLower({recv_text})")),
        _ => None,
    }
}

fn emit_block_body(e: &Expr) -> String {
    let raw = match &*e.node {
        ExprNode::Seq { exprs } => exprs
            .iter()
            .map(emit_expr)
            .collect::<Vec<_>>()
            .join("\n"),
        _ => emit_expr(e),
    };
    raw.lines().map(|l| format!("\t{l}")).collect::<Vec<_>>().join("\n")
}

fn emit_literal(lit: &Literal) -> String {
    match lit {
        Literal::Nil => "nil".to_string(),
        Literal::Bool { value } => value.to_string(),
        Literal::Int { value } => value.to_string(),
        Literal::Float { value } => {
            let s = value.to_string();
            if s.contains('.') { s } else { format!("{s}.0") }
        }
        Literal::Str { value } => format!("{value:?}"),
        Literal::Sym { value } => format!("{:?}", value.as_str()),
    }
}

// Types ----------------------------------------------------------------

pub fn go_ty(ty: &Ty) -> String {
    match ty {
        Ty::Int => "int64".to_string(),
        Ty::Float => "float64".to_string(),
        Ty::Bool => "bool".to_string(),
        Ty::Str | Ty::Sym => "string".to_string(),
        Ty::Nil => "struct{}".to_string(),
        Ty::Array { elem } => format!("[]{}", go_ty(elem)),
        Ty::Hash { key, value } => format!("map[{}]{}", go_ty(key), go_ty(value)),
        Ty::Tuple { elems } => {
            // Go has no tuple; collapse to interface{} for now.
            let _ = elems;
            "interface{}".to_string()
        }
        Ty::Record { .. } => "map[string]interface{}".to_string(),
        Ty::Union { variants } => option_shape(variants).unwrap_or_else(|| {
            // Arbitrary union -> empty interface; would be a sum type emit later.
            "interface{}".to_string()
        }),
        Ty::Class { id, .. } => match id.0.as_str() {
            // Schema DateTime/Date/Time columns carry Ty::Class(Time); Go
            // has a time package (`time.Time`) but wiring that import
            // into emit adds complexity. String is the same pragmatic
            // stand-in Rust uses; real timestamps arrive when a DB
            // adapter does.
            "Time" => "string".to_string(),
            other => other.to_string(),
        },
        Ty::Fn { .. } => "func()".to_string(),
        Ty::Var { .. } => "interface{}".to_string(),
    }
}

fn option_shape(variants: &[Ty]) -> Option<String> {
    if variants.len() != 2 {
        return None;
    }
    match (&variants[0], &variants[1]) {
        (Ty::Nil, other) | (other, Ty::Nil) => Some(format!("*{}", go_ty(other))),
        _ => None,
    }
}

// Naming ---------------------------------------------------------------

fn go_field_name(ruby_name: &str) -> String {
    // Convert snake_case to PascalCase, special-casing common initialisms.
    ruby_name
        .split('_')
        .map(|part| match part {
            "id" => "ID".to_string(),
            "url" => "URL".to_string(),
            "http" => "HTTP".to_string(),
            "json" => "JSON".to_string(),
            "html" => "HTML".to_string(),
            "api" => "API".to_string(),
            other => pascalize_word(other),
        })
        .collect::<String>()
}

fn go_method_name(ruby_name: &str) -> String {
    ruby_name
        .split('_')
        .map(|part| match part {
            "id" => "ID".to_string(),
            other => pascalize_word(other),
        })
        .collect::<String>()
}

fn pascalize_word(word: &str) -> String {
    let mut chars = word.chars();
    match chars.next() {
        Some(c) => c.to_ascii_uppercase().to_string() + chars.as_str(),
        None => String::new(),
    }
}

/// Pre-emit rewrite for model method bodies: turn any bare-name Send
/// whose method matches a model attribute into a receiver-prefixed
/// Send. Ruby's implicit self becomes Go's explicit receiver variable
/// (`p` on `Post`, `c` on `Comment`, etc.). Emit then renders the
/// outer Send as `p.Title` — modulo go_method_name PascalCasing the
/// field, matching the struct definition.
fn rewrite_bare_attrs_to_receiver(
    e: &Expr,
    attrs: &[Symbol],
    receiver_var: &str,
) -> Expr {
    use crate::expr::{Arm, InterpPart, Pattern};
    use crate::ident::VarId;
    let rewrite = |child: &Expr| rewrite_bare_attrs_to_receiver(child, attrs, receiver_var);
    let receiver_ref = |span: crate::span::Span| Expr {
        span,
        node: Box::new(ExprNode::Var {
            id: VarId(0),
            name: Symbol::from(receiver_var),
        }),
        ty: None,
        leading_blank_line: false,
    };
    let new_node = match &*e.node {
        ExprNode::Send { recv: None, method, args, block: None, parenthesized }
            if args.is_empty() && attrs.iter().any(|s| s == method) =>
        {
            ExprNode::Send {
                recv: Some(receiver_ref(e.span)),
                method: method.clone(),
                args: vec![],
                block: None,
                parenthesized: *parenthesized,
            }
        }
        ExprNode::Send { recv, method, args, block, parenthesized } => ExprNode::Send {
            recv: recv.as_ref().map(&rewrite),
            method: method.clone(),
            args: args.iter().map(&rewrite).collect(),
            block: block.as_ref().map(&rewrite),
            parenthesized: *parenthesized,
        },
        ExprNode::Seq { exprs } => ExprNode::Seq {
            exprs: exprs.iter().map(&rewrite).collect(),
        },
        ExprNode::Array { elements, style } => ExprNode::Array {
            elements: elements.iter().map(&rewrite).collect(),
            style: *style,
        },
        ExprNode::Hash { entries, braced } => ExprNode::Hash {
            entries: entries.iter().map(|(k, v)| (rewrite(k), rewrite(v))).collect(),
            braced: *braced,
        },
        ExprNode::If { cond, then_branch, else_branch } => ExprNode::If {
            cond: rewrite(cond),
            then_branch: rewrite(then_branch),
            else_branch: rewrite(else_branch),
        },
        ExprNode::Case { scrutinee, arms } => ExprNode::Case {
            scrutinee: rewrite(scrutinee),
            arms: arms
                .iter()
                .map(|arm| Arm {
                    pattern: arm.pattern.clone(),
                    guard: arm.guard.as_ref().map(&rewrite),
                    body: rewrite(&arm.body),
                })
                .collect(),
        },
        ExprNode::BoolOp { op, surface, left, right } => ExprNode::BoolOp {
            op: *op,
            surface: *surface,
            left: rewrite(left),
            right: rewrite(right),
        },
        ExprNode::StringInterp { parts } => ExprNode::StringInterp {
            parts: parts
                .iter()
                .map(|p| match p {
                    InterpPart::Text { value } => InterpPart::Text { value: value.clone() },
                    InterpPart::Expr { expr } => InterpPart::Expr { expr: rewrite(expr) },
                })
                .collect(),
        },
        ExprNode::Let { id, name, value, body } => ExprNode::Let {
            id: *id,
            name: name.clone(),
            value: rewrite(value),
            body: rewrite(body),
        },
        ExprNode::Lambda { params, block_param, body, block_style } => ExprNode::Lambda {
            params: params.clone(),
            block_param: block_param.clone(),
            body: rewrite(body),
            block_style: *block_style,
        },
        ExprNode::Apply { fun, args, block } => ExprNode::Apply {
            fun: rewrite(fun),
            args: args.iter().map(&rewrite).collect(),
            block: block.as_ref().map(&rewrite),
        },
        ExprNode::Assign { target, value } => {
            let new_target = match target {
                LValue::Var { id, name } => LValue::Var { id: *id, name: name.clone() },
                LValue::Ivar { name } => LValue::Ivar { name: name.clone() },
                LValue::Attr { recv, name } => LValue::Attr {
                    recv: rewrite(recv),
                    name: name.clone(),
                },
                LValue::Index { recv, index } => LValue::Index {
                    recv: rewrite(recv),
                    index: rewrite(index),
                },
            };
            ExprNode::Assign {
                target: new_target,
                value: rewrite(value),
            }
        }
        ExprNode::Yield { args } => ExprNode::Yield {
            args: args.iter().map(&rewrite).collect(),
        },
        ExprNode::Raise { value } => ExprNode::Raise { value: rewrite(value) },
        ExprNode::RescueModifier { expr, fallback } => ExprNode::RescueModifier {
            expr: rewrite(expr),
            fallback: rewrite(fallback),
        },
        // Leaves.
        ExprNode::Lit { .. }
        | ExprNode::Var { .. }
        | ExprNode::Ivar { .. }
        | ExprNode::Const { .. } => (*e.node).clone(),
    };
    let _ = Pattern::Wildcard;
    Expr {
        span: e.span,
        node: Box::new(new_node),
        ty: e.ty.clone(),
        leading_blank_line: e.leading_blank_line,
    }
}

// Validations, fixtures, tests ---------------------------------------

fn emit_validate_method_go(
    out: &mut String,
    model: &Model,
    validations: &[crate::lower::LoweredValidation],
) {
    let recv_var = receiver_letter(model);
    writeln!(
        out,
        "func ({recv_var} *{}) Validate() []ValidationError {{",
        model.name.0
    )
    .unwrap();
    writeln!(out, "\tvar errors []ValidationError").unwrap();
    for lv in validations {
        for check in &lv.checks {
            emit_check_inline_go(out, &recv_var, lv.attribute.as_str(), check);
        }
    }
    writeln!(out, "\treturn errors").unwrap();
    writeln!(out, "}}").unwrap();
}

/// Render Save/Destroy/Count/Find for a model against the test DB.
/// SQL strings come from LoweredPersistence; the per-target surface
/// is database/sql API shape, the `?N → ?` placeholder rewrite, and
/// class-method-as-package-function naming (`Article.count` →
/// `ArticleCount()`).
fn emit_persistence_methods_go(
    out: &mut String,
    model: &Model,
    has_validate: bool,
    app: &App,
) {
    let lp = crate::lower::lower_persistence(model, app);
    let class = lp.class.0.as_str();
    let recv = receiver_letter(model);

    let insert_sql = positional_placeholders_go(&lp.insert_sql);
    let update_sql = positional_placeholders_go(&lp.update_sql);
    let delete_sql = positional_placeholders_go(&lp.delete_sql);
    let select_by_id_sql = positional_placeholders_go(&lp.select_by_id_sql);

    let non_id_args: Vec<String> = lp
        .non_id_columns
        .iter()
        .map(|s| format!("{recv}.{}", go_field_name(s.as_str())))
        .collect();

    // ----- Save -----
    writeln!(out, "func ({recv} *{class}) Save() bool {{").unwrap();
    if has_validate {
        writeln!(out, "\tif len({recv}.Validate()) > 0 {{ return false }}").unwrap();
    }
    // belongs_to existence: FK must be non-zero and refer to an
    // existing row in the target table.
    for check in &lp.belongs_to_checks {
        let fk_field = go_field_name(check.foreign_key.as_str());
        let target = check.target_class.0.as_str();
        writeln!(
            out,
            "\tif {recv}.{fk_field} == 0 || {target}Find({recv}.{fk_field}) == nil {{ return false }}",
        )
        .unwrap();
    }
    writeln!(out, "\tdb := Conn()").unwrap();
    writeln!(out, "\tif {recv}.ID == 0 {{").unwrap();
    writeln!(
        out,
        "\t\tres, err := db.Exec({insert_sql:?}, {})",
        non_id_args.join(", "),
    )
    .unwrap();
    writeln!(out, "\t\tif err != nil {{ panic(err) }}").unwrap();
    writeln!(out, "\t\tid, _ := res.LastInsertId()").unwrap();
    writeln!(out, "\t\t{recv}.ID = id").unwrap();
    writeln!(out, "\t}} else {{").unwrap();
    writeln!(
        out,
        "\t\t_, err := db.Exec({update_sql:?}, {}, {recv}.ID)",
        non_id_args.join(", "),
    )
    .unwrap();
    writeln!(out, "\t\tif err != nil {{ panic(err) }}").unwrap();
    writeln!(out, "\t}}").unwrap();
    writeln!(out, "\treturn true").unwrap();
    writeln!(out, "}}").unwrap();

    // ----- Destroy -----
    writeln!(out).unwrap();
    writeln!(out, "func ({recv} *{class}) Destroy() {{").unwrap();
    for dc in &lp.dependent_children {
        let child_class = dc.child_class.0.as_str();
        let child_select = positional_placeholders_go(&dc.select_by_parent_sql);
        writeln!(out, "\t{{").unwrap();
        writeln!(
            out,
            "\t\trows, err := Conn().Query({child_select:?}, {recv}.ID)",
        )
        .unwrap();
        writeln!(out, "\t\tif err != nil {{ panic(err) }}").unwrap();
        writeln!(out, "\t\tvar children []{child_class}").unwrap();
        writeln!(out, "\t\tfor rows.Next() {{").unwrap();
        writeln!(out, "\t\t\tvar c {child_class}").unwrap();
        let scans: Vec<String> = dc
            .child_columns
            .iter()
            .map(|s| format!("&c.{}", go_field_name(s.as_str())))
            .collect();
        writeln!(out, "\t\t\tif err := rows.Scan({}); err != nil {{ panic(err) }}", scans.join(", ")).unwrap();
        writeln!(out, "\t\t\tchildren = append(children, c)").unwrap();
        writeln!(out, "\t\t}}").unwrap();
        writeln!(out, "\t\trows.Close()").unwrap();
        writeln!(out, "\t\tfor i := range children {{").unwrap();
        writeln!(out, "\t\t\tchildren[i].Destroy()").unwrap();
        writeln!(out, "\t\t}}").unwrap();
        writeln!(out, "\t}}").unwrap();
    }
    writeln!(
        out,
        "\tif _, err := Conn().Exec({delete_sql:?}, {recv}.ID); err != nil {{ panic(err) }}",
    )
    .unwrap();
    writeln!(out, "}}").unwrap();

    // ----- Count (package-level function, since Go has no class methods) -----
    writeln!(out).unwrap();
    writeln!(out, "func {class}Count() int64 {{").unwrap();
    writeln!(out, "\tvar n int64").unwrap();
    writeln!(
        out,
        "\tif err := Conn().QueryRow({:?}).Scan(&n); err != nil {{ panic(err) }}",
        lp.count_sql,
    )
    .unwrap();
    writeln!(out, "\treturn n").unwrap();
    writeln!(out, "}}").unwrap();

    // ----- Find (package-level function) -----
    writeln!(out).unwrap();
    writeln!(out, "func {class}Find(id int64) *{class} {{").unwrap();
    writeln!(
        out,
        "\trow := Conn().QueryRow({select_by_id_sql:?}, id)",
    )
    .unwrap();
    writeln!(out, "\tvar r {class}").unwrap();
    let scans: Vec<String> = lp
        .columns
        .iter()
        .map(|s| format!("&r.{}", go_field_name(s.as_str())))
        .collect();
    writeln!(
        out,
        "\tif err := row.Scan({}); err != nil {{ return nil }}",
        scans.join(", ")
    )
    .unwrap();
    writeln!(out, "\treturn &r").unwrap();
    writeln!(out, "}}").unwrap();
}

/// SQLite `?N` → database/sql `?`. `database/sql` doesn't support
/// numbered placeholders in the same positional style; drop the
/// trailing digits.
fn positional_placeholders_go(sql: &str) -> String {
    let mut out = String::new();
    let chars: Vec<char> = sql.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        if chars[i] == '?' {
            out.push('?');
            i += 1;
            while i < chars.len() && chars[i].is_ascii_digit() {
                i += 1;
            }
        } else {
            out.push(chars[i]);
            i += 1;
        }
    }
    out
}

fn receiver_letter(model: &Model) -> String {
    model
        .name
        .0
        .as_str()
        .chars()
        .next()
        .unwrap_or('r')
        .to_ascii_lowercase()
        .to_string()
}

fn emit_check_inline_go(
    out: &mut String,
    recv: &str,
    attr: &str,
    check: &crate::lower::Check,
) {
    use crate::lower::Check;
    let field = go_field_name(attr);
    let msg = check.default_message();
    let push = |cond: &str| -> String {
        format!(
            "\tif {cond} {{\n\t\terrors = append(errors, NewValidationError({attr:?}, {msg:?}))\n\t}}"
        )
    };
    let block = match check {
        Check::Presence => push(&format!("{recv}.{field} == \"\"")),
        Check::Absence => push(&format!("{recv}.{field} != \"\"")),
        Check::MinLength { n } => push(&format!("len({recv}.{field}) < {n}")),
        Check::MaxLength { n } => push(&format!("len({recv}.{field}) > {n}")),
        Check::GreaterThan { threshold } => push(&format!("{recv}.{field} <= {threshold}")),
        Check::LessThan { threshold } => push(&format!("{recv}.{field} >= {threshold}")),
        Check::OnlyInteger => {
            format!("\t// OnlyInteger on {attr:?} — enforced by Go's type system")
        }
        Check::Inclusion { values } => {
            let parts: Vec<String> =
                values.iter().map(inclusion_value_to_go).collect();
            // Emit an inline membership check via a switch-style OR.
            let cond = parts
                .iter()
                .map(|p| format!("{recv}.{field} != {p}"))
                .collect::<Vec<_>>()
                .join(" && ");
            push(&cond)
        }
        Check::Format { pattern } => {
            format!("\t// TODO: Format check on {attr:?} requires runtime regex ({pattern:?})")
        }
        Check::Uniqueness { .. } => {
            format!("\t// TODO: Uniqueness on {attr:?} requires DB access at runtime")
        }
        Check::Custom { method } => {
            format!("\t{recv}.{}(errors)", go_field_name(method.as_str()))
        }
    };
    writeln!(out, "{block}").unwrap();
}

fn inclusion_value_to_go(v: &crate::lower::InclusionValue) -> String {
    use crate::lower::InclusionValue;
    match v {
        InclusionValue::Str { value } => format!("{value:?}"),
        InclusionValue::Int { value } => value.to_string(),
        InclusionValue::Float { value } => {
            let s = value.to_string();
            if s.contains('.') { s } else { format!("{s}.0") }
        }
        InclusionValue::Bool { value } => value.to_string(),
    }
}

fn emit_go_fixtures(app: &App) -> EmittedFile {
    // Single file `app/fixtures_test.go` keeps fixtures inside the
    // package's test build (not shipped in production). Go's
    // `_test.go` suffix excludes files from `go build`; `go test`
    // picks them up.
    let lowered = crate::lower::lower_fixtures(app);
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s, "package app").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "// FixtureIDs maps (fixture_name, label) → AUTOINCREMENT id").unwrap();
    writeln!(s, "// assigned when the fixture loaded. Reset by setupTest.").unwrap();
    writeln!(s, "var FixtureIDs = map[[2]string]int64{{}}").unwrap();
    writeln!(s).unwrap();
    writeln!(
        s,
        "// setupTest opens a fresh :memory: SQLite DB, runs the schema DDL,"
    )
    .unwrap();
    writeln!(s, "// and reloads every fixture in declaration order. Each generated").unwrap();
    writeln!(s, "// test calls this at the top of its body.").unwrap();
    writeln!(s, "func setupTest() {{").unwrap();
    writeln!(s, "\tSetupTestDB(CreateTables)").unwrap();
    writeln!(s, "\tFixtureIDs = map[[2]string]int64{{}}").unwrap();
    for f in &lowered.fixtures {
        let mod_ns = crate::naming::camelize(f.name.as_str());
        writeln!(s, "\t{mod_ns}LoadAll()").unwrap();
    }
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "func FixtureID(fixture, label string) int64 {{").unwrap();
    writeln!(s, "\tid, ok := FixtureIDs[[2]string{{fixture, label}}]").unwrap();
    writeln!(s, "\tif !ok {{").unwrap();
    writeln!(
        s,
        "\t\tpanic(\"fixture \" + fixture + \"/\" + label + \" not loaded\")"
    )
    .unwrap();
    writeln!(s, "\t}}").unwrap();
    writeln!(s, "\treturn id").unwrap();
    writeln!(s, "}}").unwrap();

    for fixture in &lowered.fixtures {
        let class_name = fixture.class.0.as_str();
        let ns = crate::naming::camelize(fixture.name.as_str());

        // LoadAll — insert each record via Save (validations +
        // INSERT via the juntos-style runtime) and record the
        // AUTOINCREMENT id in FixtureIDs.
        writeln!(s).unwrap();
        writeln!(s, "func {ns}LoadAll() {{").unwrap();
        for record in &fixture.records {
            let label = record.label.as_str();
            writeln!(s, "\t{{").unwrap();
            writeln!(s, "\t\tr := &{class_name}{{}}").unwrap();
            for field in &record.fields {
                let col = go_field_name(field.column.as_str());
                let val = match &field.value {
                    crate::lower::LoweredFixtureValue::Literal { ty, raw } => {
                        go_literal_for(raw, ty)
                    }
                    crate::lower::LoweredFixtureValue::FkLookup {
                        target_fixture,
                        target_label,
                    } => format!(
                        "FixtureID({:?}, {:?})",
                        target_fixture.as_str(),
                        target_label.as_str(),
                    ),
                };
                writeln!(s, "\t\tr.{col} = {val}").unwrap();
            }
            writeln!(
                s,
                "\t\tif !r.Save() {{ panic(\"fixture {}/{label} failed to save\") }}",
                fixture.name.as_str(),
            )
            .unwrap();
            writeln!(
                s,
                "\t\tFixtureIDs[[2]string{{{:?}, {:?}}}] = r.ID",
                fixture.name.as_str(),
                label,
            )
            .unwrap();
            writeln!(s, "\t}}").unwrap();
        }
        writeln!(s, "}}").unwrap();

        // Named-record getters: look up id + Find.
        for record in &fixture.records {
            let label = record.label.as_str();
            let label_pascal = go_field_name(label);
            writeln!(s).unwrap();
            writeln!(s, "func {ns}{label_pascal}() *{class_name} {{").unwrap();
            writeln!(
                s,
                "\tid := FixtureID({:?}, {:?})",
                fixture.name.as_str(),
                label,
            )
            .unwrap();
            writeln!(s, "\tr := {class_name}Find(id)").unwrap();
            writeln!(
                s,
                "\tif r == nil {{ panic(\"fixture {}/{label} not loaded\") }}",
                fixture.name.as_str(),
            )
            .unwrap();
            writeln!(s, "\treturn r").unwrap();
            writeln!(s, "}}").unwrap();
        }
    }

    EmittedFile {
        path: PathBuf::from("app/fixtures_test.go"),
        content: s,
    }
}

fn go_literal_for(value: &str, ty: &Ty) -> String {
    match ty {
        Ty::Str | Ty::Sym => format!("{value:?}"),
        Ty::Int => {
            if value.parse::<i64>().is_ok() {
                value.to_string()
            } else {
                format!("0 /* TODO: coerce {value:?} */")
            }
        }
        Ty::Float => {
            if value.parse::<f64>().is_ok() {
                value.to_string()
            } else {
                format!("0.0 /* TODO: coerce {value:?} */")
            }
        }
        Ty::Bool => match value {
            "true" | "1" => "true".into(),
            "false" | "0" => "false".into(),
            _ => format!("false /* TODO: coerce {value:?} */"),
        },
        Ty::Class { id, .. } if id.0.as_str() == "Time" => format!("{value:?}"),
        _ => format!("{value:?}"),
    }
}

fn emit_go_tests(tm: &TestModule, app: &App) -> EmittedFile {
    let fixture_names: Vec<crate::ident::Symbol> =
        app.fixtures.iter().map(|f| f.name.clone()).collect();
    let known_models: Vec<crate::ident::Symbol> =
        app.models.iter().map(|m| m.name.0.clone()).collect();
    let mut attrs_set: std::collections::BTreeSet<crate::ident::Symbol> =
        std::collections::BTreeSet::new();
    for m in &app.models {
        for attr in m.attributes.fields.keys() {
            attrs_set.insert(attr.clone());
        }
    }
    let model_attrs: Vec<crate::ident::Symbol> = attrs_set.into_iter().collect();

    let ctx = GoTestCtx {
        app,
        fixture_names: &fixture_names,
        known_models: &known_models,
        model_attrs: &model_attrs,
    };

    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s, "package app").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "import \"testing\"").unwrap();

    // Controller tests t.Skip wholesale — Phase 4 HTTP runtime
    // (get/post, render, redirect_to, etc.) isn't wired.
    let is_controller_test = tm.name.0.as_str().ends_with("ControllerTest");
    for test in &tm.tests {
        let fn_name = format!("Test{}", go_field_name(&test_name_snake(&test.name)));
        writeln!(s).unwrap();
        writeln!(s, "func {fn_name}(t *testing.T) {{").unwrap();
        if is_controller_test {
            writeln!(s, "\tt.Skip(\"Phase 4: needs HTTP runtime\")").unwrap();
        } else if test_needs_runtime_unsupported_go(test) {
            writeln!(
                s,
                "\tt.Skip(\"Phase 3: needs persistence runtime\")"
            )
            .unwrap();
        } else {
            if !app.fixtures.is_empty() {
                // Every test starts on a fresh :memory: DB with all
                // fixtures loaded — Rails' transactional-fixture shape.
                writeln!(s, "\tsetupTest()").unwrap();
            }
            let body = emit_test_body_go(&test.body, ctx);
            for line in body.lines() {
                writeln!(s, "\t{line}").unwrap();
            }
        }
        writeln!(s, "}}").unwrap();
    }

    let filename = snake_case(tm.name.0.as_str());
    let filename = filename.replace("_test", "");
    EmittedFile {
        path: PathBuf::from(format!("app/{filename}_test.go")),
        content: s,
    }
}

fn test_name_snake(desc: &str) -> String {
    let mut s: String = desc
        .chars()
        .map(|c| if c.is_alphanumeric() { c.to_ascii_lowercase() } else { '_' })
        .collect();
    while s.contains("__") {
        s = s.replace("__", "_");
    }
    s.trim_matches('_').to_string()
}

#[derive(Clone, Copy)]
struct GoTestCtx<'a> {
    app: &'a App,
    fixture_names: &'a [crate::ident::Symbol],
    known_models: &'a [crate::ident::Symbol],
    model_attrs: &'a [crate::ident::Symbol],
}

fn emit_test_body_go(body: &Expr, ctx: GoTestCtx) -> String {
    match &*body.node {
        ExprNode::Seq { exprs } if !exprs.is_empty() => exprs
            .iter()
            .map(|e| emit_test_stmt_go(e, ctx))
            .collect::<Vec<_>>()
            .join("\n"),
        _ => emit_test_stmt_go(body, ctx),
    }
}

fn emit_test_stmt_go(e: &Expr, ctx: GoTestCtx) -> String {
    match &*e.node {
        ExprNode::Assign { target: LValue::Var { name, .. }, value } => {
            format!("{} := {}", name, emit_test_expr_go(value, ctx))
        }
        _ => emit_test_expr_go(e, ctx),
    }
}

fn emit_test_expr_go(e: &Expr, ctx: GoTestCtx) -> String {
    match &*e.node {
        ExprNode::Lit { value } => emit_literal(value),
        ExprNode::Var { name, .. } => name.to_string(),
        ExprNode::Const { path } => path
            .iter()
            .map(|s| s.to_string())
            .collect::<Vec<_>>()
            .join("."),
        ExprNode::Send { recv, method, args, block, .. } => {
            emit_test_send_go(recv.as_ref(), method.as_str(), args, block.as_ref(), ctx)
        }
        ExprNode::Hash { entries, .. } => {
            // Rough: only used inside Class.new(hash) — handled above.
            let parts: Vec<String> = entries
                .iter()
                .map(|(k, v)| format!("{}: {}", emit_test_expr_go(k, ctx), emit_test_expr_go(v, ctx)))
                .collect();
            format!("map[string]interface{{}}{{{}}}", parts.join(", "))
        }
        ExprNode::BoolOp { op, left, right, .. } => {
            use crate::expr::BoolOpKind;
            let op_s = match op {
                BoolOpKind::Or => "||",
                BoolOpKind::And => "&&",
            };
            format!(
                "{} {} {}",
                emit_test_expr_go(left, ctx),
                op_s,
                emit_test_expr_go(right, ctx)
            )
        }
        _ => format!("/* TODO: Go test emit for {:?} */", std::mem::discriminant(&*e.node)),
    }
}

fn emit_test_send_go(
    recv: Option<&Expr>,
    method: &str,
    args: &[Expr],
    block: Option<&Expr>,
    ctx: GoTestCtx,
) -> String {
    let args_s: Vec<String> = args.iter().map(|a| emit_test_expr_go(a, ctx)).collect();

    // Fixture accessor: articles(:one) → ArticlesOne()
    if recv.is_none()
        && args.len() == 1
        && ctx.fixture_names.iter().any(|s| s.as_str() == method)
    {
        if let ExprNode::Lit { value: Literal::Sym { value: sym } } = &*args[0].node {
            return format!(
                "{}{}()",
                go_field_name(method),
                go_field_name(sym.as_str())
            );
        }
    }

    // assert_difference("Class.count", delta) do ... end →
    // before/after capture + inline Go comparison. Parses the Ruby
    // string into a Go expression (`Comment.count` → `CommentCount()`).
    if recv.is_none() && method == "assert_difference" {
        if let Some(body) = block {
            if let Some(count_expr) = args
                .first()
                .and_then(|a| match &*a.node {
                    ExprNode::Lit { value: Literal::Str { value } } => {
                        rewrite_ruby_dot_call_go(value)
                    }
                    _ => None,
                })
            {
                let delta = args_s.get(1).cloned().unwrap_or_else(|| "1".into());
                let body_s = emit_block_body_go(body, ctx);
                return format!(
                    "_before := {count_expr}\n{body_s}\n_after := {count_expr}\nif _after - _before != int64({delta}) {{ t.Errorf(\"expected delta {delta}, got %d\", _after - _before) }}",
                );
            }
        }
    }

    // owner.<assoc>.create(hash) / .build(hash) — HasMany rewrite.
    // Renders as a Go IIFE so the surrounding assignment/expression
    // context still gets a value.
    if (method == "create" || method == "build") && args.len() == 1 {
        if let Some(outer_recv) = recv {
            if let ExprNode::Send {
                recv: Some(assoc_recv),
                method: assoc_method,
                args: inner_args,
                ..
            } = &*outer_recv.node
            {
                if inner_args.is_empty() {
                    if let Some(s) = try_emit_assoc_create_go(
                        assoc_recv,
                        assoc_method.as_str(),
                        args,
                        method,
                        ctx,
                    ) {
                        return s;
                    }
                }
            }
        }
    }

    // Assertion macros → Go's inline `if ... { t.Errorf(...) }` pattern.
    if recv.is_none() {
        match (method, args_s.len()) {
            ("assert_equal", 2) => {
                return format!(
                    "if {actual} != {expected} {{ t.Errorf(\"expected %v, got %v\", {expected}, {actual}) }}",
                    expected = args_s[0],
                    actual = args_s[1],
                );
            }
            ("assert_not_equal", 2) => {
                return format!(
                    "if {actual} == {expected} {{ t.Errorf(\"expected not equal to %v\", {expected}) }}",
                    expected = args_s[0],
                    actual = args_s[1],
                );
            }
            ("assert_not", 1) => {
                return format!(
                    "if {cond} {{ t.Errorf(\"expected false\") }}",
                    cond = args_s[0]
                );
            }
            ("assert", 1) => {
                return format!(
                    "if !({cond}) {{ t.Errorf(\"expected true\") }}",
                    cond = args_s[0]
                );
            }
            ("assert_nil", 1) => {
                // Go's "nil-ness" varies. Ints test against zero; pointers
                // against nil. We pick based on whether the arg expression
                // looks like a method chain (assume it's a primitive value).
                return format!(
                    "if {expr} != 0 {{ t.Errorf(\"expected zero/nil, got %v\", {expr}) }}",
                    expr = args_s[0]
                );
            }
            ("assert_not_nil", 1) => {
                return format!(
                    "if {expr} == 0 {{ t.Errorf(\"expected non-zero\") }}",
                    expr = args_s[0]
                );
            }
            _ => {}
        }
    }

    // `Class.new(hash)` → `&Class{ Field: val, ... }` struct literal.
    if let Some(r) = recv {
        if method == "new" && args.len() == 1 {
            if let ExprNode::Const { path } = &*r.node {
                if let Some(class_name) = path.last() {
                    if ctx.known_models.iter().any(|s| s == class_name) {
                        if let ExprNode::Hash { entries, .. } = &*args[0].node {
                            let pairs: Vec<String> = entries
                                .iter()
                                .filter_map(|(k, v)| {
                                    if let ExprNode::Lit {
                                        value: Literal::Sym { value: f },
                                    } = &*k.node
                                    {
                                        Some(format!(
                                            "{}: {}",
                                            go_field_name(f.as_str()),
                                            emit_test_expr_go(v, ctx)
                                        ))
                                    } else {
                                        None
                                    }
                                })
                                .collect();
                            return format!(
                                "&{}{{{}}}",
                                class_name,
                                pairs.join(", ")
                            );
                        }
                    }
                }
            }
        }
    }

    match recv {
        None => {
            if args_s.is_empty() {
                method.to_string()
            } else {
                format!("{}({})", method, args_s.join(", "))
            }
        }
        Some(r) => {
            let recv_s = emit_test_expr_go(r, ctx);
            let is_class_call = matches!(&*r.node, ExprNode::Const { .. });
            // Class-level calls flatten to `ClassMethod(args)` — Go
            // has no class methods, and our persistence emitter laid
            // down package-level `ArticleFind` / `CommentCount` /
            // etc. to stand in.
            if is_class_call {
                if args_s.is_empty() {
                    return format!("{recv_s}{}()", go_field_name(method));
                } else {
                    return format!(
                        "{recv_s}{}({})",
                        go_field_name(method),
                        args_s.join(", ")
                    );
                }
            }
            let is_attr = args_s.is_empty()
                && ctx.model_attrs.iter().any(|s| s.as_str() == method);
            if is_attr {
                format!("{recv_s}.{}", go_field_name(method))
            } else if args_s.is_empty() {
                format!("{recv_s}.{}()", go_field_name(method))
            } else {
                format!(
                    "{recv_s}.{}({})",
                    go_field_name(method),
                    args_s.join(", ")
                )
            }
        }
    }
}

/// Parse a Ruby-style `"Class.method"` expression into Go syntax.
/// Capitalized LHS → package-level function (`Comment.count` →
/// `CommentCount()`); lowercase LHS → instance field read.
fn rewrite_ruby_dot_call_go(expr: &str) -> Option<String> {
    let trimmed = expr.trim();
    let (lhs, rhs) = trimmed.split_once('.')?;
    let is_ident = |s: &str| {
        !s.is_empty()
            && s.chars().next().is_some_and(|c| c.is_alphabetic() || c == '_')
            && s.chars().all(|c| c.is_alphanumeric() || c == '_')
    };
    if !is_ident(lhs) || !is_ident(rhs) {
        return None;
    }
    let is_class = lhs.chars().next().is_some_and(|c| c.is_uppercase());
    if is_class {
        Some(format!("{lhs}{}()", go_field_name(rhs)))
    } else {
        Some(format!("{lhs}.{}", go_field_name(rhs)))
    }
}

/// Render a Ruby block body as Go statements, peeling one Lambda
/// layer (Ruby `do ... end` lowers to `ExprNode::Lambda` in the IR).
fn emit_block_body_go(e: &Expr, ctx: GoTestCtx) -> String {
    let inner = match &*e.node {
        ExprNode::Lambda { body, .. } => body,
        _ => e,
    };
    match &*inner.node {
        ExprNode::Seq { exprs } if !exprs.is_empty() => exprs
            .iter()
            .map(|s| emit_test_stmt_go(s, ctx))
            .collect::<Vec<_>>()
            .join("\n"),
        _ => emit_test_stmt_go(inner, ctx),
    }
}

fn try_emit_assoc_create_go(
    owner: &Expr,
    assoc_name: &str,
    args: &[Expr],
    outer_method: &str,
    ctx: GoTestCtx,
) -> Option<String> {
    let resolved = crate::lower::resolve_has_many(
        &crate::ident::Symbol::from(assoc_name),
        owner.ty.as_ref(),
        ctx.app,
    )?;
    let target_class = resolved.target_class.0.as_str();
    let foreign_key = go_field_name(resolved.foreign_key.as_str());

    let owner_s = emit_test_expr_go(owner, ctx);
    let hash_entries = match &args.first()?.node.as_ref() {
        ExprNode::Hash { entries, .. } => entries.clone(),
        _ => return None,
    };

    let mut pairs: Vec<String> =
        vec![format!("{foreign_key}: {owner_s}.ID")];
    for (k, v) in &hash_entries {
        if let ExprNode::Lit { value: Literal::Sym { value: field_name } } = &*k.node {
            pairs.push(format!(
                "{}: {}",
                go_field_name(field_name.as_str()),
                emit_test_expr_go(v, ctx),
            ));
        }
    }
    let struct_lit = format!("&{target_class}{{{}}}", pairs.join(", "));
    // Go IIFE — wraps the multi-statement build+save+return so the
    // caller can use it in an expression position (e.g. RHS of :=).
    if outer_method == "create" {
        Some(format!(
            "func() *{target_class} {{ r := {struct_lit}; r.Save(); return r }}()"
        ))
    } else {
        Some(format!(
            "func() *{target_class} {{ r := {struct_lit}; return r }}()"
        ))
    }
}

fn test_needs_runtime_unsupported_go(_test: &Test) -> bool {
    // Phase 3 rounded out the Go emitter's coverage. Keep the
    // predicate as a future-guard; no real-blog shape forces a
    // skip today.
    false
}

#[allow(dead_code)]

fn test_body_uses_unsupported_go(e: &Expr) -> bool {
    use crate::expr::InterpPart;
    let self_hit = match &*e.node {
        ExprNode::Send { recv, method, .. } => {
            let m = method.as_str();
            matches!(
                m,
                "assert_difference"
                    | "destroy"
                    | "destroy!"
                    | "build"
                    | "create"
                    | "create!"
            ) || (m == "count"
                && recv.as_ref().is_some_and(|r| matches!(&*r.node, ExprNode::Const { .. })))
        }
        _ => false,
    };
    if self_hit {
        return true;
    }
    match &*e.node {
        ExprNode::Send { recv, args, block, .. } => {
            if let Some(r) = recv {
                if test_body_uses_unsupported_go(r) {
                    return true;
                }
            }
            for a in args {
                if test_body_uses_unsupported_go(a) {
                    return true;
                }
            }
            if let Some(b) = block {
                if test_body_uses_unsupported_go(b) {
                    return true;
                }
            }
        }
        ExprNode::Seq { exprs } | ExprNode::Array { elements: exprs, .. } => {
            for e in exprs {
                if test_body_uses_unsupported_go(e) {
                    return true;
                }
            }
        }
        ExprNode::Hash { entries, .. } => {
            for (k, v) in entries {
                if test_body_uses_unsupported_go(k) || test_body_uses_unsupported_go(v) {
                    return true;
                }
            }
        }
        ExprNode::StringInterp { parts } => {
            for p in parts {
                if let InterpPart::Expr { expr } = p {
                    if test_body_uses_unsupported_go(expr) {
                        return true;
                    }
                }
            }
        }
        ExprNode::BoolOp { left, right, .. }
        | ExprNode::RescueModifier { expr: left, fallback: right } => {
            if test_body_uses_unsupported_go(left) || test_body_uses_unsupported_go(right) {
                return true;
            }
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            if test_body_uses_unsupported_go(cond)
                || test_body_uses_unsupported_go(then_branch)
                || test_body_uses_unsupported_go(else_branch)
            {
                return true;
            }
        }
        ExprNode::Let { value, body, .. } => {
            if test_body_uses_unsupported_go(value) || test_body_uses_unsupported_go(body) {
                return true;
            }
        }
        ExprNode::Lambda { body, .. } => {
            if test_body_uses_unsupported_go(body) {
                return true;
            }
        }
        ExprNode::Assign { value, .. } => {
            if test_body_uses_unsupported_go(value) {
                return true;
            }
        }
        _ => {}
    }
    false
}
