//! Go emitter.
//!
//! Second typed target. Differences from Rust that surface design choices:
//!
//! - Go has no Option / Result — nullable types are pointers (`*T`).
//! - Go has no class methods — `Post.All()` is pseudo-Go; a real mapping
//!   would use a repository pattern or package-level functions.
//! - Go requires explicit `return` for non-void functions and omits the
//!   return type entirely for void functions.
//! - Go convention: `ID`, `URL`, `HTTP` for initialism fields; PascalCase
//!   for exported identifiers, camelCase for unexported.
//! - Go uses tabs for indentation; gofmt would realign struct fields.
//!   We emit single-tab indent without alignment.
//!
//! Output is pseudo-Go — won't compile as-is. The goal is to prove that
//! types flow through to a second typed target without the Rust emitter
//! accidentally hiding ambiguities.

use std::fmt::Write;
use std::path::PathBuf;

use super::EmittedFile;
use crate::App;
use crate::dialect::{Action, Controller, MethodDef, Model};
use crate::expr::{Expr, ExprNode, LValue, Literal};
use crate::naming::snake_case;
use crate::ty::Ty;

pub fn emit(app: &App) -> Vec<EmittedFile> {
    let mut files = Vec::new();
    if !app.models.is_empty() {
        files.push(emit_models(app));
    }
    for controller in &app.controllers {
        files.push(emit_controller(controller));
    }
    files
}

// Models ---------------------------------------------------------------

fn emit_models(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s, "package app").unwrap();
    for model in &app.models {
        writeln!(s).unwrap();
        emit_struct(&mut s, model);
        for method in &model.methods {
            writeln!(s).unwrap();
            emit_model_method(&mut s, model, method);
        }
    }
    EmittedFile { path: PathBuf::from("app/models.go"), content: s }
}

fn emit_struct(out: &mut String, model: &Model) {
    writeln!(out, "type {} struct {{", model.name.0).unwrap();
    for (name, ty) in &model.attributes.fields {
        writeln!(out, "\t{} {}", go_field_name(name.as_str()), go_ty(ty)).unwrap();
    }
    writeln!(out, "}}").unwrap();
}

fn emit_model_method(out: &mut String, model: &Model, m: &MethodDef) {
    let ret_ty = m.body.ty.clone().unwrap_or(Ty::Nil);
    let method_name = go_method_name(m.name.as_str());
    let ret_annot = match &ret_ty {
        Ty::Nil => String::new(),
        other => format!(" {}", go_ty(other)),
    };
    let receiver = match m.receiver {
        crate::dialect::MethodReceiver::Instance => {
            // Single-letter receiver name — Go idiom (`p *Post`).
            let first = model
                .name
                .0
                .as_str()
                .chars()
                .next()
                .unwrap_or('r')
                .to_ascii_lowercase();
            format!("({first} *{})", model.name.0)
        }
        crate::dialect::MethodReceiver::Class => {
            // Class method: emit as package-level function (pseudo-Go, since
            // Go has no class methods).
            String::new()
        }
    };
    let space_before_name = if receiver.is_empty() { "" } else { " " };
    writeln!(
        out,
        "func {}{}{}(){} {{",
        receiver, space_before_name, method_name, ret_annot,
    )
    .unwrap();
    let body_s = if matches!(ret_ty, Ty::Nil) {
        emit_expr(&m.body)
    } else {
        format!("return {}", emit_expr(&m.body))
    };
    for line in body_s.lines() {
        writeln!(out, "\t{}", line).unwrap();
    }
    writeln!(out, "}}").unwrap();
}

// Controllers ----------------------------------------------------------

fn emit_controller(c: &Controller) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s, "package app").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "type {} struct{{}}", c.name.0).unwrap();
    for action in &c.actions {
        writeln!(s).unwrap();
        emit_action(&mut s, c, action);
    }
    let fname = format!("app/controllers/{}.go", snake_case(c.name.0.as_str()));
    EmittedFile { path: PathBuf::from(fname), content: s }
}

fn emit_action(out: &mut String, c: &Controller, a: &Action) {
    let ret_ty = action_return_type(&a.body);
    let method_name = go_method_name(a.name.as_str());
    let ret_annot = match &ret_ty {
        Ty::Nil => String::new(),
        other => format!(" {}", go_ty(other)),
    };
    writeln!(out, "func (c *{}) {}(){} {{", c.name.0, method_name, ret_annot).unwrap();
    let body = emit_body(&a.body, &ret_ty);
    for line in body.lines() {
        writeln!(out, "\t{}", line).unwrap();
    }
    writeln!(out, "}}").unwrap();
}

fn action_return_type(body: &Expr) -> Ty {
    match &*body.node {
        ExprNode::Assign { value, .. } => value.ty.clone().unwrap_or(Ty::Nil),
        ExprNode::Seq { exprs } => exprs
            .last()
            .and_then(|e| match &*e.node {
                ExprNode::Assign { value, .. } => value.ty.clone(),
                _ => e.ty.clone(),
            })
            .unwrap_or(Ty::Nil),
        _ => body.ty.clone().unwrap_or(Ty::Nil),
    }
}

// Body and expressions -------------------------------------------------

fn emit_body(body: &Expr, return_ty: &Ty) -> String {
    let is_void = matches!(return_ty, Ty::Nil);
    match &*body.node {
        ExprNode::Assign { target: LValue::Ivar { .. }, value } => {
            if is_void {
                emit_expr(value)
            } else {
                format!("return {}", emit_expr(value))
            }
        }
        ExprNode::Seq { exprs } if !exprs.is_empty() => {
            let mut lines: Vec<String> = Vec::new();
            for (i, e) in exprs.iter().enumerate() {
                lines.push(emit_stmt(e, i == exprs.len() - 1, is_void));
            }
            lines.join("\n")
        }
        _ => {
            if is_void {
                emit_expr(body)
            } else {
                format!("return {}", emit_expr(body))
            }
        }
    }
}

fn emit_stmt(e: &Expr, is_last: bool, void_return: bool) -> String {
    match &*e.node {
        // Local `foo = expr` and ivar `@foo = expr` both become `foo := expr`.
        ExprNode::Assign { target: LValue::Var { name, .. }, value } => {
            format!("{} := {}", name, emit_expr(value))
        }
        ExprNode::Assign { target: LValue::Ivar { name }, value } => {
            format!("{} := {}", name, emit_expr(value))
        }
        _ => {
            if is_last && !void_return {
                format!("return {}", emit_expr(e))
            } else {
                emit_expr(e)
            }
        }
    }
}

fn emit_expr(e: &Expr) -> String {
    match &*e.node {
        ExprNode::Lit { value } => emit_literal(value),
        ExprNode::Const { path } => {
            path.iter().map(|s| s.to_string()).collect::<Vec<_>>().join(".")
        }
        ExprNode::Var { name, .. } => name.to_string(),
        ExprNode::Ivar { name } => name.to_string(),
        ExprNode::Send { recv, method, args, .. } => emit_send(recv.as_ref(), method.as_str(), args),
        ExprNode::Assign { target: _, value } => emit_expr(value),
        ExprNode::Seq { exprs } => {
            exprs.iter().map(emit_expr).collect::<Vec<_>>().join("; ")
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            let cond_s = emit_expr(cond);
            let then_s = emit_block_body(then_branch);
            let else_s = emit_block_body(else_branch);
            format!("if {cond_s} {{\n{then_s}\n}} else {{\n{else_s}\n}}")
        }
        ExprNode::Hash { entries, .. } => {
            let parts: Vec<String> = entries
                .iter()
                .map(|(k, v)| format!("{}: {}", emit_expr(k), emit_expr(v)))
                .collect();
            format!("map[string]interface{{}}{{{}}}", parts.join(", "))
        }
        other => format!("/* TODO: emit {:?} */", std::mem::discriminant(other)),
    }
}

fn emit_send(recv: Option<&Expr>, method: &str, args: &[Expr]) -> String {
    let args_s: Vec<String> = args.iter().map(emit_expr).collect();

    if method == "[]" && recv.is_some() {
        return format!("{}[{}]", emit_expr(recv.unwrap()), args_s.join(", "));
    }

    let go_m = go_method_name(method);
    match recv {
        None => {
            if args_s.is_empty() {
                go_m
            } else {
                format!("{}({})", go_m, args_s.join(", "))
            }
        }
        Some(r) => {
            let recv_s = emit_expr(r);
            format!("{}.{}({})", recv_s, go_m, args_s.join(", "))
        }
    }
}

fn emit_block_body(e: &Expr) -> String {
    let raw = match &*e.node {
        ExprNode::Seq { exprs } => exprs
            .iter()
            .map(emit_expr)
            .collect::<Vec<_>>()
            .join("\n"),
        _ => emit_expr(e),
    };
    raw.lines().map(|l| format!("\t{l}")).collect::<Vec<_>>().join("\n")
}

fn emit_literal(lit: &Literal) -> String {
    match lit {
        Literal::Nil => "nil".to_string(),
        Literal::Bool { value } => value.to_string(),
        Literal::Int { value } => value.to_string(),
        Literal::Float { value } => {
            let s = value.to_string();
            if s.contains('.') { s } else { format!("{s}.0") }
        }
        Literal::Str { value } => format!("{value:?}"),
        Literal::Sym { value } => format!("{:?}", value.as_str()),
    }
}

// Types ----------------------------------------------------------------

pub fn go_ty(ty: &Ty) -> String {
    match ty {
        Ty::Int => "int64".to_string(),
        Ty::Float => "float64".to_string(),
        Ty::Bool => "bool".to_string(),
        Ty::Str | Ty::Sym => "string".to_string(),
        Ty::Nil => "struct{}".to_string(),
        Ty::Array { elem } => format!("[]{}", go_ty(elem)),
        Ty::Hash { key, value } => format!("map[{}]{}", go_ty(key), go_ty(value)),
        Ty::Tuple { elems } => {
            // Go has no tuple; collapse to interface{} for now.
            let _ = elems;
            "interface{}".to_string()
        }
        Ty::Record { .. } => "map[string]interface{}".to_string(),
        Ty::Union { variants } => option_shape(variants).unwrap_or_else(|| {
            // Arbitrary union -> empty interface; would be a sum type emit later.
            "interface{}".to_string()
        }),
        Ty::Class { id, .. } => id.0.to_string(),
        Ty::Fn { .. } => "func()".to_string(),
        Ty::Var { .. } => "interface{}".to_string(),
    }
}

fn option_shape(variants: &[Ty]) -> Option<String> {
    if variants.len() != 2 {
        return None;
    }
    match (&variants[0], &variants[1]) {
        (Ty::Nil, other) | (other, Ty::Nil) => Some(format!("*{}", go_ty(other))),
        _ => None,
    }
}

// Naming ---------------------------------------------------------------

fn go_field_name(ruby_name: &str) -> String {
    // Convert snake_case to PascalCase, special-casing common initialisms.
    ruby_name
        .split('_')
        .map(|part| match part {
            "id" => "ID".to_string(),
            "url" => "URL".to_string(),
            "http" => "HTTP".to_string(),
            "json" => "JSON".to_string(),
            "html" => "HTML".to_string(),
            "api" => "API".to_string(),
            other => pascalize_word(other),
        })
        .collect::<String>()
}

fn go_method_name(ruby_name: &str) -> String {
    ruby_name
        .split('_')
        .map(|part| match part {
            "id" => "ID".to_string(),
            other => pascalize_word(other),
        })
        .collect::<String>()
}

fn pascalize_word(word: &str) -> String {
    let mut chars = word.chars();
    match chars.next() {
        Some(c) => c.to_ascii_uppercase().to_string() + chars.as_str(),
        None => String::new(),
    }
}
