//! Python emitter.
//!
//! Third Phase 2 scaffold. Python and Ruby share a lot of surface
//! grammar (snake_case identifiers, `class`, dynamic typing), which
//! lets the emitter be thin. The interesting parts are the shape
//! choices:
//!
//! - Models as classes with type-hinted fields (`id: int`). No
//!   `@dataclass` yet — constructors and defaults are a Phase 3
//!   runtime concern.
//! - Controllers as classes with `async def` per action. Railcar's
//!   Python output uses module-level `async def` functions (aiohttp
//!   handler convention). The class shape is a deliberate choice for
//!   scaffold consistency with TS; Phase 3 can pivot to module-level
//!   if the Juntos-equivalent Python runtime prefers it.
//! - Routes as a `list[dict]` dispatch table.
//!
//! Python-specific idioms:
//! - `from __future__ import annotations` so forward references in
//!   type hints work without runtime import order concerns.
//! - `int | None` syntax for optional types (PEP 604, Python 3.10+).
//! - `list[T]` / `dict[K, V]` (PEP 585, Python 3.9+). No `typing.List`.
//! - Ruby symbols → string literals (same as TS).

use std::fmt::Write;
use std::path::PathBuf;

use super::EmittedFile;
use crate::App;
use crate::dialect::{
    Action, Association, Controller, MethodDef, Model, RouteSpec, Test, TestModule,
};
use crate::ident::Symbol;
use crate::expr::{Expr, ExprNode, LValue, Literal};
use crate::ty::Ty;

const RUNTIME_SOURCE: &str = include_str!("../../runtime/python/runtime.py");
const DB_SOURCE: &str = include_str!("../../runtime/python/db.py");

pub fn emit(app: &App) -> Vec<EmittedFile> {
    let mut files = Vec::new();
    if !app.models.is_empty() {
        files.push(emit_models(app));
        files.push(EmittedFile {
            path: PathBuf::from("app/runtime.py"),
            content: RUNTIME_SOURCE.to_string(),
        });
        files.push(EmittedFile {
            path: PathBuf::from("app/db.py"),
            content: DB_SOURCE.to_string(),
        });
        files.push(emit_schema_sql_py(app));
        files.push(EmittedFile {
            path: PathBuf::from("app/__init__.py"),
            content: String::new(),
        });
    }
    if !app.controllers.is_empty() {
        files.push(emit_controllers(app));
    }
    if !app.routes.entries.is_empty() {
        files.push(emit_routes(app));
    }
    if !app.fixtures.is_empty() {
        files.push(emit_py_fixtures(app));
        // tests/ needs __init__.py so unittest can discover
        files.push(EmittedFile {
            path: PathBuf::from("tests/__init__.py"),
            content: String::new(),
        });
    }
    if !app.test_modules.is_empty() {
        for tm in &app.test_modules {
            files.push(emit_py_test(tm, app));
        }
        if app.fixtures.is_empty() {
            files.push(EmittedFile {
                path: PathBuf::from("tests/__init__.py"),
                content: String::new(),
            });
        }
    }
    files
}

// Models ---------------------------------------------------------------

fn emit_models(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "from __future__ import annotations").unwrap();
    let any_validations = app
        .models
        .iter()
        .any(|m| !crate::lower::lower_validations(m).is_empty());
    if any_validations {
        writeln!(s).unwrap();
        writeln!(s, "from app.runtime import ValidationError").unwrap();
    }
    for model in &app.models {
        writeln!(s).unwrap();
        emit_model(&mut s, model, app);
    }
    EmittedFile { path: PathBuf::from("app/models.py"), content: s }
}

fn emit_model(out: &mut String, model: &Model, app: &App) {
    let name = model.name.0.as_str();
    writeln!(out, "class {name}:").unwrap();
    let has_fields = !model.attributes.fields.is_empty();
    let has_methods = model.methods().next().is_some();
    let lowered = crate::lower::lower_validations(model);
    if !has_fields && !has_methods && lowered.is_empty() {
        writeln!(out, "    pass").unwrap();
        return;
    }
    // Class-level type hints (documentation; not assigned).
    for (field, ty) in &model.attributes.fields {
        writeln!(out, "    {}: {}", field, python_ty(ty)).unwrap();
    }
    if has_fields {
        // Instance constructor: `Article(title="X", body="Y")` assigns
        // each kwarg to self, defaulting missing fields to type-
        // appropriate zero values so bare `Article()` also works.
        writeln!(out).unwrap();
        writeln!(out, "    def __init__(self, **kwargs):").unwrap();
        for (field, ty) in &model.attributes.fields {
            let fname = field.as_str();
            writeln!(
                out,
                "        self.{fname} = kwargs.get({fname:?}, {})",
                python_default(ty)
            )
            .unwrap();
        }
    }
    let model_attrs: Vec<Symbol> = model.attributes.fields.keys().cloned().collect();
    for method in model.methods() {
        writeln!(out).unwrap();
        emit_model_method_with_attrs(out, method, &model_attrs);
    }
    if !lowered.is_empty() {
        writeln!(out).unwrap();
        emit_validate_method_py(out, &lowered);
    }
    // Skip persistence for abstract models (no columns beyond id).
    let has_table = model
        .attributes
        .fields
        .keys()
        .any(|k| k.as_str() != "id");
    if has_table {
        emit_persistence_methods_py(out, model, !lowered.is_empty(), app);
    }
}

/// Render save/destroy/count/find for a model against the stdlib
/// `sqlite3`-backed test connection. Save/destroy are instance
/// methods; count/find are classmethods.
fn emit_persistence_methods_py(
    out: &mut String,
    model: &Model,
    has_validate: bool,
    app: &App,
) {
    let lp = crate::lower::lower_persistence(model, app);
    let class = lp.class.0.as_str();

    let insert_sql = positional_placeholders_py(&lp.insert_sql);
    let update_sql = positional_placeholders_py(&lp.update_sql);
    let delete_sql = positional_placeholders_py(&lp.delete_sql);
    let select_by_id_sql = positional_placeholders_py(&lp.select_by_id_sql);

    let non_id_args: Vec<String> = lp
        .non_id_columns
        .iter()
        .map(|s| format!("self.{}", s.as_str()))
        .collect();

    // ----- save -----
    writeln!(out).unwrap();
    writeln!(out, "    def save(self) -> bool:").unwrap();
    if has_validate {
        writeln!(out, "        if self.validate():").unwrap();
        writeln!(out, "            return False").unwrap();
    }
    for check in &lp.belongs_to_checks {
        let fk = check.foreign_key.as_str();
        let target = check.target_class.0.as_str();
        writeln!(
            out,
            "        if not self.{fk} or {target}.find(self.{fk}) is None:",
        )
        .unwrap();
        writeln!(out, "            return False").unwrap();
    }
    writeln!(out, "        from app import db").unwrap();
    writeln!(out, "        if not self.id:").unwrap();
    writeln!(
        out,
        "            self.id = db.execute(\n                {insert_sql:?},\n                [{}],\n            )",
        non_id_args.join(", "),
    )
    .unwrap();
    writeln!(out, "        else:").unwrap();
    writeln!(
        out,
        "            db.execute(\n                {update_sql:?},\n                [{}, self.id],\n            )",
        non_id_args.join(", "),
    )
    .unwrap();
    writeln!(out, "        return True").unwrap();

    // ----- destroy -----
    writeln!(out).unwrap();
    writeln!(out, "    def destroy(self) -> None:").unwrap();
    writeln!(out, "        from app import db").unwrap();
    for dc in &lp.dependent_children {
        let child_class = dc.child_class.0.as_str();
        let child_select = positional_placeholders_py(&dc.select_by_parent_sql);
        writeln!(
            out,
            "        children = db.query_all({child_select:?}, [self.id])",
        )
        .unwrap();
        writeln!(out, "        for row in children:").unwrap();
        writeln!(out, "            child = {child_class}(").unwrap();
        let kw: Vec<String> = dc
            .child_columns
            .iter()
            .map(|c| format!("                {0}=row[{0:?}]", c.as_str()))
            .collect();
        writeln!(out, "{}", kw.join(",\n")).unwrap();
        writeln!(out, "            )").unwrap();
        writeln!(out, "            child.destroy()").unwrap();
    }
    writeln!(
        out,
        "        db.execute({delete_sql:?}, [self.id])",
    )
    .unwrap();

    // ----- count -----
    writeln!(out).unwrap();
    writeln!(out, "    @classmethod").unwrap();
    writeln!(out, "    def count(cls) -> int:").unwrap();
    writeln!(out, "        from app import db").unwrap();
    writeln!(
        out,
        "        return db.scalar({:?}) or 0",
        lp.count_sql,
    )
    .unwrap();

    // ----- find -----
    writeln!(out).unwrap();
    writeln!(out, "    @classmethod").unwrap();
    writeln!(out, "    def find(cls, id: int) -> {class} | None:").unwrap();
    writeln!(out, "        from app import db").unwrap();
    writeln!(
        out,
        "        row = db.query_one({select_by_id_sql:?}, [id])",
    )
    .unwrap();
    writeln!(out, "        if row is None:").unwrap();
    writeln!(out, "            return None").unwrap();
    writeln!(out, "        return cls(").unwrap();
    let kw: Vec<String> = lp
        .columns
        .iter()
        .map(|c| format!("            {0}=row[{0:?}]", c.as_str()))
        .collect();
    writeln!(out, "{}", kw.join(",\n")).unwrap();
    writeln!(out, "        )").unwrap();
}

/// SQLite `?N` → Python's stdlib sqlite3 positional `?`. Same
/// workaround as Crystal / Go / TS / Elixir.
fn positional_placeholders_py(sql: &str) -> String {
    let mut out = String::new();
    let chars: Vec<char> = sql.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        if chars[i] == '?' {
            out.push('?');
            i += 1;
            while i < chars.len() && chars[i].is_ascii_digit() {
                i += 1;
            }
        } else {
            out.push(chars[i]);
            i += 1;
        }
    }
    out
}

/// `app/schema_sql.py` — Python module exposing the target-neutral
/// DDL as `CREATE_TABLES`. sqlite3's `executescript` handles
/// multi-statement strings directly, so no splitting needed.
fn emit_schema_sql_py(app: &App) -> EmittedFile {
    let ddl = crate::lower::lower_schema(&app.schema);
    // Use a Python triple-quoted raw string so the DDL renders with
    // its original line breaks and doesn't need escape-sequence
    // handling. Raw so backslashes in identifiers (none today but
    // defensive) pass through.
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "CREATE_TABLES = r\"\"\"").unwrap();
    s.push_str(&ddl);
    writeln!(s, "\"\"\"").unwrap();
    EmittedFile {
        path: PathBuf::from("app/schema_sql.py"),
        content: s,
    }
}

fn python_default(ty: &Ty) -> String {
    match ty {
        Ty::Int => "0".to_string(),
        Ty::Float => "0.0".to_string(),
        Ty::Bool => "False".to_string(),
        Ty::Str | Ty::Sym => "\"\"".to_string(),
        Ty::Nil => "None".to_string(),
        Ty::Array { .. } => "[]".to_string(),
        Ty::Hash { .. } => "{}".to_string(),
        Ty::Class { id, .. } if id.0.as_str() == "Time" => "\"\"".to_string(),
        _ => "None".to_string(),
    }
}

fn emit_validate_method_py(
    out: &mut String,
    validations: &[crate::lower::LoweredValidation],
) {
    writeln!(out, "    def validate(self) -> list[ValidationError]:").unwrap();
    writeln!(out, "        errors: list[ValidationError] = []").unwrap();
    for lv in validations {
        for check in &lv.checks {
            emit_check_inline_py(out, lv.attribute.as_str(), check);
        }
    }
    writeln!(out, "        return errors").unwrap();
}

fn emit_check_inline_py(out: &mut String, attr: &str, check: &crate::lower::Check) {
    use crate::lower::Check;
    let msg = check.default_message();
    let push = |cond: &str| -> String {
        format!(
            "        if {cond}:\n            errors.append(ValidationError({attr:?}, {msg:?}))"
        )
    };
    let block = match check {
        Check::Presence => push(&format!("not self.{attr}")),
        Check::Absence => push(&format!("self.{attr}")),
        Check::MinLength { n } => push(&format!("len(self.{attr}) < {n}")),
        Check::MaxLength { n } => push(&format!("len(self.{attr}) > {n}")),
        Check::GreaterThan { threshold } => push(&format!("self.{attr} <= {threshold}")),
        Check::LessThan { threshold } => push(&format!("self.{attr} >= {threshold}")),
        Check::OnlyInteger => {
            format!("        # OnlyInteger on {attr:?} — type hint documents, Python doesn't enforce")
        }
        Check::Inclusion { values } => {
            let parts: Vec<String> = values.iter().map(inclusion_value_to_py).collect();
            push(&format!("self.{attr} not in [{}]", parts.join(", ")))
        }
        Check::Format { pattern } => {
            format!("        # TODO: Format check on {attr:?} requires re module ({pattern:?})")
        }
        Check::Uniqueness { .. } => {
            format!("        # TODO: Uniqueness on {attr:?} requires DB access at runtime")
        }
        Check::Custom { method } => {
            format!("        self.{method}(errors)", method = method.as_str())
        }
    };
    writeln!(out, "{block}").unwrap();
}

fn inclusion_value_to_py(v: &crate::lower::InclusionValue) -> String {
    use crate::lower::InclusionValue;
    match v {
        InclusionValue::Str { value } => format!("{value:?}"),
        InclusionValue::Int { value } => value.to_string(),
        InclusionValue::Float { value } => {
            let s = value.to_string();
            if s.contains('.') { s } else { format!("{s}.0") }
        }
        InclusionValue::Bool { value } => {
            if *value { "True".into() } else { "False".into() }
        }
    }
}

fn emit_model_method_with_attrs(out: &mut String, m: &MethodDef, attrs: &[Symbol]) {
    let name = m.name.as_str();
    let ret = m.body.ty.clone().unwrap_or(Ty::Nil);
    let ret_annot = format!(" -> {}", python_ty(&ret));
    let (def_kind, params, is_instance) = match m.receiver {
        crate::dialect::MethodReceiver::Instance => {
            ("def", first_param("self", &m.params), true)
        }
        crate::dialect::MethodReceiver::Class => {
            // Class methods get a `@classmethod` decorator on the
            // previous line (written by the caller) and `cls` as the
            // first positional arg — Python's class-method shape.
            writeln!(out, "    @classmethod").unwrap();
            ("def", first_param("cls", &m.params), false)
        }
    };
    writeln!(out, "    {def_kind} {name}({params}){ret_annot}:").unwrap();
    // Pre-emit rewrite: inside an instance method, bare `title` →
    // `self.title` via Ivar substitution (emit already renders Ivars
    // as `self.<name>` in Python).
    let rewritten = if is_instance {
        rewrite_bare_attrs_to_ivars_py(&m.body, attrs)
    } else {
        m.body.clone()
    };
    let body = emit_body(&rewritten, &ret);
    if body.is_empty() {
        writeln!(out, "        pass").unwrap();
    } else {
        for line in body.lines() {
            writeln!(out, "        {line}").unwrap();
        }
    }
}

fn rewrite_bare_attrs_to_ivars_py(e: &Expr, attrs: &[Symbol]) -> Expr {
    use crate::expr::{Arm, InterpPart, Pattern};
    let rewrite = |child: &Expr| rewrite_bare_attrs_to_ivars_py(child, attrs);
    let new_node = match &*e.node {
        ExprNode::Send { recv: None, method, args, block: None, .. }
            if args.is_empty() && attrs.iter().any(|s| s == method) =>
        {
            ExprNode::Ivar { name: method.clone() }
        }
        ExprNode::Send { recv, method, args, block, parenthesized } => ExprNode::Send {
            recv: recv.as_ref().map(&rewrite),
            method: method.clone(),
            args: args.iter().map(&rewrite).collect(),
            block: block.as_ref().map(&rewrite),
            parenthesized: *parenthesized,
        },
        ExprNode::Seq { exprs } => ExprNode::Seq {
            exprs: exprs.iter().map(&rewrite).collect(),
        },
        ExprNode::Array { elements, style } => ExprNode::Array {
            elements: elements.iter().map(&rewrite).collect(),
            style: *style,
        },
        ExprNode::Hash { entries, braced } => ExprNode::Hash {
            entries: entries.iter().map(|(k, v)| (rewrite(k), rewrite(v))).collect(),
            braced: *braced,
        },
        ExprNode::If { cond, then_branch, else_branch } => ExprNode::If {
            cond: rewrite(cond),
            then_branch: rewrite(then_branch),
            else_branch: rewrite(else_branch),
        },
        ExprNode::Case { scrutinee, arms } => ExprNode::Case {
            scrutinee: rewrite(scrutinee),
            arms: arms
                .iter()
                .map(|arm| Arm {
                    pattern: arm.pattern.clone(),
                    guard: arm.guard.as_ref().map(&rewrite),
                    body: rewrite(&arm.body),
                })
                .collect(),
        },
        ExprNode::BoolOp { op, surface, left, right } => ExprNode::BoolOp {
            op: *op,
            surface: *surface,
            left: rewrite(left),
            right: rewrite(right),
        },
        ExprNode::StringInterp { parts } => ExprNode::StringInterp {
            parts: parts
                .iter()
                .map(|p| match p {
                    InterpPart::Text { value } => InterpPart::Text { value: value.clone() },
                    InterpPart::Expr { expr } => InterpPart::Expr { expr: rewrite(expr) },
                })
                .collect(),
        },
        ExprNode::Let { id, name, value, body } => ExprNode::Let {
            id: *id,
            name: name.clone(),
            value: rewrite(value),
            body: rewrite(body),
        },
        ExprNode::Lambda { params, block_param, body, block_style } => ExprNode::Lambda {
            params: params.clone(),
            block_param: block_param.clone(),
            body: rewrite(body),
            block_style: *block_style,
        },
        ExprNode::Apply { fun, args, block } => ExprNode::Apply {
            fun: rewrite(fun),
            args: args.iter().map(&rewrite).collect(),
            block: block.as_ref().map(&rewrite),
        },
        ExprNode::Assign { target, value } => {
            let new_target = match target {
                LValue::Var { id, name } => LValue::Var { id: *id, name: name.clone() },
                LValue::Ivar { name } => LValue::Ivar { name: name.clone() },
                LValue::Attr { recv, name } => LValue::Attr {
                    recv: rewrite(recv),
                    name: name.clone(),
                },
                LValue::Index { recv, index } => LValue::Index {
                    recv: rewrite(recv),
                    index: rewrite(index),
                },
            };
            ExprNode::Assign {
                target: new_target,
                value: rewrite(value),
            }
        }
        ExprNode::Yield { args } => ExprNode::Yield {
            args: args.iter().map(&rewrite).collect(),
        },
        ExprNode::Raise { value } => ExprNode::Raise { value: rewrite(value) },
        ExprNode::RescueModifier { expr, fallback } => ExprNode::RescueModifier {
            expr: rewrite(expr),
            fallback: rewrite(fallback),
        },
        ExprNode::Lit { .. }
        | ExprNode::Var { .. }
        | ExprNode::Ivar { .. }
        | ExprNode::Const { .. } => (*e.node).clone(),
    };
    let _ = Pattern::Wildcard;
    Expr {
        span: e.span,
        node: Box::new(new_node),
        ty: e.ty.clone(),
        leading_blank_line: e.leading_blank_line,
    }
}

/// Build a comma-separated Python parameter list, prepending the
/// receiver (`self` or `cls`) when present. Empty trailing args collapse.
fn first_param(receiver: &str, params: &[crate::ident::Symbol]) -> String {
    let mut out = String::from(receiver);
    for p in params {
        out.push_str(", ");
        out.push_str(p.as_str());
    }
    out
}

// Controllers ----------------------------------------------------------

fn emit_controllers(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "from __future__ import annotations").unwrap();
    for controller in &app.controllers {
        writeln!(s).unwrap();
        emit_controller(&mut s, controller);
    }
    EmittedFile { path: PathBuf::from("app/controllers.py"), content: s }
}

fn emit_controller(out: &mut String, c: &Controller) {
    let name = c.name.0.as_str();
    writeln!(out, "class {name}:").unwrap();
    let actions: Vec<_> = c.actions().collect();
    if actions.is_empty() {
        writeln!(out, "    pass").unwrap();
        return;
    }
    for (i, action) in actions.iter().enumerate() {
        if i > 0 {
            writeln!(out).unwrap();
        }
        emit_action(out, action);
    }
}

fn emit_action(out: &mut String, a: &Action) {
    let name = a.name.as_str();
    let ret = action_return_type(&a.body);
    let ret_annot = format!(" -> {}", python_ty(&ret));
    writeln!(out, "    async def {name}(self){ret_annot}:").unwrap();
    let body = emit_body(&a.body, &ret);
    if body.is_empty() {
        writeln!(out, "        pass").unwrap();
    } else {
        for line in body.lines() {
            writeln!(out, "        {line}").unwrap();
        }
    }
}

fn action_return_type(body: &Expr) -> Ty {
    match &*body.node {
        ExprNode::Assign { value, .. } => value.ty.clone().unwrap_or(Ty::Nil),
        ExprNode::Seq { exprs } => exprs
            .last()
            .and_then(|e| match &*e.node {
                ExprNode::Assign { value, .. } => value.ty.clone(),
                _ => e.ty.clone(),
            })
            .unwrap_or(Ty::Nil),
        _ => body.ty.clone().unwrap_or(Ty::Nil),
    }
}

// Routes ---------------------------------------------------------------

fn emit_routes(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "from __future__ import annotations").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "routes: list[dict] = [").unwrap();
    let mut flat: Vec<(String, String, String, String)> = Vec::new();
    for entry in &app.routes.entries {
        collect_flat_routes(entry, &mut flat, None);
    }
    for (method, path, controller, action) in flat {
        writeln!(
            s,
            "    {{\"method\": {:?}, \"path\": {:?}, \"controller\": {:?}, \"action\": {:?}}},",
            method, path, controller, action,
        )
        .unwrap();
    }
    writeln!(s, "]").unwrap();
    EmittedFile { path: PathBuf::from("app/routes.py"), content: s }
}

fn collect_flat_routes(
    spec: &RouteSpec,
    out: &mut Vec<(String, String, String, String)>,
    scope_prefix: Option<(&str, &str)>,
) {
    match spec {
        RouteSpec::Explicit { method, path, controller, action, .. } => {
            let verb = match method {
                crate::dialect::HttpMethod::Get => "GET",
                crate::dialect::HttpMethod::Post => "POST",
                crate::dialect::HttpMethod::Put => "PUT",
                crate::dialect::HttpMethod::Patch => "PATCH",
                crate::dialect::HttpMethod::Delete => "DELETE",
                crate::dialect::HttpMethod::Head => "HEAD",
                crate::dialect::HttpMethod::Options => "OPTIONS",
                crate::dialect::HttpMethod::Any => "ANY",
            };
            let full_path = match scope_prefix {
                Some((parent, _)) => format!("/{parent}/:{parent}_id{path}"),
                None => path.clone(),
            };
            out.push((
                verb.to_string(),
                full_path,
                controller.0.to_string(),
                action.to_string(),
            ));
        }
        RouteSpec::Root { target } => {
            if let Some((c, a)) = target.split_once('#') {
                out.push(("GET".into(), "/".into(), controller_class_name(c), a.into()));
            }
        }
        RouteSpec::Resources { name, only, except, nested } => {
            let resource_path = format!("/{name}");
            let controller = controller_class_name(name.as_str());
            for (action, verb, suffix) in standard_resource_actions() {
                let action = *action;
                let verb = *verb;
                let suffix = *suffix;
                if !only.is_empty() && !only.iter().any(|s| s.as_str() == action) {
                    continue;
                }
                if except.iter().any(|s| s.as_str() == action) {
                    continue;
                }
                let path = format!("{resource_path}{suffix}");
                let full_path = match scope_prefix {
                    Some((parent, _)) => format!("/{parent}/:{parent}_id{path}"),
                    None => path,
                };
                out.push((verb.into(), full_path, controller.clone(), action.into()));
            }
            let singular =
                crate::naming::singularize_camelize(name.as_str()).to_lowercase();
            for child in nested {
                collect_flat_routes(child, out, Some((&singular, name.as_str())));
            }
        }
    }
}

fn standard_resource_actions() -> &'static [(&'static str, &'static str, &'static str)] {
    &[
        ("index", "GET", ""),
        ("new", "GET", "/new"),
        ("create", "POST", ""),
        ("show", "GET", "/:id"),
        ("edit", "GET", "/:id/edit"),
        ("update", "PATCH", "/:id"),
        ("destroy", "DELETE", "/:id"),
    ]
}

fn controller_class_name(short: &str) -> String {
    let mut s = crate::naming::camelize(short);
    s.push_str("Controller");
    s
}

// Bodies + expressions -------------------------------------------------

fn emit_body(body: &Expr, return_ty: &Ty) -> String {
    let is_void = matches!(return_ty, Ty::Nil);
    match &*body.node {
        ExprNode::Assign { target: LValue::Ivar { .. }, value } => {
            if is_void {
                emit_expr(value)
            } else {
                format!("return {}", emit_expr(value))
            }
        }
        ExprNode::Seq { exprs } if !exprs.is_empty() => {
            let mut lines: Vec<String> = Vec::new();
            for (i, e) in exprs.iter().enumerate() {
                if i > 0 && e.leading_blank_line {
                    lines.push(String::new());
                }
                lines.push(emit_stmt(e, i == exprs.len() - 1, is_void));
            }
            lines.join("\n")
        }
        _ => {
            if is_void {
                emit_expr(body)
            } else {
                format!("return {}", emit_expr(body))
            }
        }
    }
}

fn emit_stmt(e: &Expr, is_last: bool, void_return: bool) -> String {
    match &*e.node {
        ExprNode::Assign { target: LValue::Var { name, .. }, value } => {
            format!("{} = {}", name, emit_expr(value))
        }
        ExprNode::Assign { target: LValue::Ivar { name }, value } => {
            format!("self.{} = {}", name, emit_expr(value))
        }
        _ => {
            if is_last && !void_return {
                format!("return {}", emit_expr(e))
            } else {
                emit_expr(e)
            }
        }
    }
}

fn emit_expr(e: &Expr) -> String {
    match &*e.node {
        ExprNode::Lit { value } => emit_literal(value),
        ExprNode::Const { path } => {
            path.iter().map(|s| s.to_string()).collect::<Vec<_>>().join(".")
        }
        ExprNode::Var { name, .. } => name.to_string(),
        ExprNode::Ivar { name } => format!("self.{name}"),
        ExprNode::Send { recv, method, args, .. } => {
            emit_send(recv.as_ref(), method.as_str(), args)
        }
        ExprNode::Assign { target: _, value } => emit_expr(value),
        ExprNode::Seq { exprs } => {
            exprs.iter().map(emit_expr).collect::<Vec<_>>().join("; ")
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            // Python `if … : \n body \n else: \n body`. No braces,
            // no trailing `end`. The inner emitter produces the
            // branch expression as a single line — the scaffold
            // doesn't try to reformat multi-line if bodies.
            let cond_s = emit_expr(cond);
            let then_s = emit_expr(then_branch);
            let else_s = emit_expr(else_branch);
            format!("if {cond_s}:\n    {then_s}\nelse:\n    {else_s}")
        }
        ExprNode::BoolOp { op, left, right, .. } => {
            use crate::expr::BoolOpKind;
            let op_s = match op {
                BoolOpKind::Or => "or",
                BoolOpKind::And => "and",
            };
            format!("{} {op_s} {}", emit_expr(left), emit_expr(right))
        }
        ExprNode::Array { elements, .. } => {
            let parts: Vec<String> = elements.iter().map(emit_expr).collect();
            format!("[{}]", parts.join(", "))
        }
        ExprNode::Hash { entries, .. } => {
            let parts: Vec<String> = entries
                .iter()
                .map(|(k, v)| {
                    // Symbol keys become string keys in Python dicts
                    // (since Python has no atom type). Rails-style
                    // `{foo: 1}` → `{"foo": 1}`.
                    if let ExprNode::Lit { value: Literal::Sym { value } } = &*k.node {
                        format!("{:?}: {}", value.as_str(), emit_expr(v))
                    } else {
                        format!("{}: {}", emit_expr(k), emit_expr(v))
                    }
                })
                .collect();
            format!("{{{}}}", parts.join(", "))
        }
        ExprNode::StringInterp { parts } => {
            // Python f-string — `f"text {expr} more"`. Reserved chars
            // inside the `{}` are rare for the Ruby expressions we
            // ingest, so no escape bookkeeping yet; if a fixture
            // triggers one we add it then.
            use crate::expr::InterpPart;
            let mut out = String::from("f\"");
            for p in parts {
                match p {
                    InterpPart::Text { value } => {
                        for c in value.chars() {
                            match c {
                                '"' => out.push_str("\\\""),
                                '\\' => out.push_str("\\\\"),
                                '{' => out.push_str("{{"),
                                '}' => out.push_str("}}"),
                                '\n' => out.push_str("\\n"),
                                other => out.push(other),
                            }
                        }
                    }
                    InterpPart::Expr { expr } => {
                        out.push('{');
                        out.push_str(&emit_expr(expr));
                        out.push('}');
                    }
                }
            }
            out.push('"');
            out
        }
        other => format!("# TODO: emit {:?}", std::mem::discriminant(other)),
    }
}

fn emit_send(recv: Option<&Expr>, method: &str, args: &[Expr]) -> String {
    let args_s: Vec<String> = args.iter().map(emit_expr).collect();
    if method == "[]" && recv.is_some() {
        return format!("{}[{}]", emit_expr(recv.unwrap()), args_s.join(", "));
    }
    match recv {
        None => {
            if args_s.is_empty() {
                method.to_string()
            } else {
                format!("{}({})", method, args_s.join(", "))
            }
        }
        Some(r) => {
            let recv_s = emit_expr(r);
            if args_s.is_empty() {
                // Bare `recv.method` (no parens) is how Python accesses
                // attributes. For method calls with no args we emit
                // `recv.method()` — matches Python idiom and avoids
                // confusing a 0-arity call with an attribute read.
                format!("{recv_s}.{method}()")
            } else {
                format!("{recv_s}.{method}({})", args_s.join(", "))
            }
        }
    }
}

fn emit_literal(lit: &Literal) -> String {
    match lit {
        Literal::Nil => "None".to_string(),
        Literal::Bool { value } => {
            if *value { "True".to_string() } else { "False".to_string() }
        }
        Literal::Int { value } => value.to_string(),
        Literal::Float { value } => {
            let s = value.to_string();
            if s.contains('.') { s } else { format!("{s}.0") }
        }
        Literal::Str { value } => format!("{value:?}"),
        // Symbols have no direct Python equivalent; emit as string
        // literals. Enum detection would refine this into a typed
        // Enum subclass later.
        Literal::Sym { value } => format!("{:?}", value.as_str()),
    }
}

// Types ----------------------------------------------------------------

pub fn python_ty(ty: &Ty) -> String {
    match ty {
        Ty::Int => "int".to_string(),
        Ty::Float => "float".to_string(),
        Ty::Bool => "bool".to_string(),
        Ty::Str | Ty::Sym => "str".to_string(),
        Ty::Nil => "None".to_string(),
        Ty::Array { elem } => format!("list[{}]", python_ty(elem)),
        Ty::Hash { key, value } => format!("dict[{}, {}]", python_ty(key), python_ty(value)),
        Ty::Tuple { elems } => {
            let parts: Vec<String> = elems.iter().map(python_ty).collect();
            format!("tuple[{}]", parts.join(", "))
        }
        Ty::Record { .. } => "dict[str, object]".to_string(),
        Ty::Union { variants } => {
            // PEP 604 union syntax: `A | B | C`. Python 3.10+.
            let parts: Vec<String> = variants.iter().map(python_ty).collect();
            parts.join(" | ")
        }
        Ty::Class { id, .. } => match id.0.as_str() {
            "Time" => "str".to_string(),
            other => other.to_string(),
        },
        Ty::Fn { .. } => "object".to_string(),
        Ty::Var { .. } => "object".to_string(),
    }
}

// Fixtures + tests ---------------------------------------------------

fn emit_py_fixtures(app: &App) -> EmittedFile {
    let lowered = crate::lower::lower_fixtures(app);
    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "from __future__ import annotations").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "from app import db").unwrap();
    writeln!(s, "from app.schema_sql import CREATE_TABLES").unwrap();
    writeln!(s, "from app.models import {}", app
        .models
        .iter()
        .map(|m| m.name.0.as_str().to_string())
        .collect::<Vec<_>>()
        .join(", ")).unwrap();

    writeln!(s).unwrap();
    writeln!(s, "FIXTURE_IDS: dict[tuple[str, str], int] = {{}}").unwrap();

    // Fixtures.setup — called from each TestCase's setUp. Opens a
    // fresh :memory: DB, runs schema DDL, clears the fixture id
    // map, and reloads all fixtures in declaration order.
    writeln!(s).unwrap();
    writeln!(s, "def setup() -> None:").unwrap();
    writeln!(s, "    db.setup_test_db(CREATE_TABLES)").unwrap();
    writeln!(s, "    FIXTURE_IDS.clear()").unwrap();
    for f in &lowered.fixtures {
        let ns = f.name.as_str();
        writeln!(s, "    {ns}_load_all()").unwrap();
    }

    writeln!(s).unwrap();
    writeln!(s, "def fixture_id(fixture: str, label: str) -> int:").unwrap();
    writeln!(s, "    key = (fixture, label)").unwrap();
    writeln!(s, "    if key not in FIXTURE_IDS:").unwrap();
    writeln!(s, "        raise RuntimeError(f\"fixture {{fixture}}/{{label}} not loaded\")").unwrap();
    writeln!(s, "    return FIXTURE_IDS[key]").unwrap();

    for fixture in &lowered.fixtures {
        let class_name = fixture.class.0.as_str();
        let ns = fixture.name.as_str();

        // <ns>_load_all — insert each record via Class.save (which
        // runs validate + INSERT) then capture the assigned id via
        // the mutated self.id attribute.
        writeln!(s).unwrap();
        writeln!(s, "def {ns}_load_all() -> None:").unwrap();
        for record in &fixture.records {
            let label = record.label.as_str();
            let kwargs: Vec<String> = record
                .fields
                .iter()
                .map(|f| {
                    let col = f.column.as_str();
                    let val = match &f.value {
                        crate::lower::LoweredFixtureValue::Literal { ty, raw } => {
                            py_literal_for(raw, ty)
                        }
                        crate::lower::LoweredFixtureValue::FkLookup {
                            target_fixture,
                            target_label,
                        } => format!(
                            "fixture_id({:?}, {:?})",
                            target_fixture.as_str(),
                            target_label.as_str(),
                        ),
                    };
                    format!("        {col}={val}")
                })
                .collect();
            writeln!(s, "    r = {class_name}(").unwrap();
            writeln!(s, "{}", kwargs.join(",\n")).unwrap();
            writeln!(s, "    )").unwrap();
            writeln!(
                s,
                "    if not r.save():\n        raise RuntimeError(\"fixture {ns}/{label} failed to save\")"
            )
            .unwrap();
            writeln!(
                s,
                "    FIXTURE_IDS[({ns:?}, {label:?})] = r.id",
            )
            .unwrap();
        }

        // Named-record getters — lookup id + Class.find.
        for record in &fixture.records {
            let label = record.label.as_str();
            writeln!(s).unwrap();
            writeln!(s, "def {ns}_{label}() -> {class_name}:").unwrap();
            writeln!(s, "    id = fixture_id({ns:?}, {label:?})").unwrap();
            writeln!(s, "    record = {class_name}.find(id)").unwrap();
            writeln!(
                s,
                "    if record is None:\n        raise RuntimeError(\"fixture {ns}/{label} not loaded\")"
            )
            .unwrap();
            writeln!(s, "    return record").unwrap();
        }
    }

    EmittedFile {
        path: PathBuf::from("tests/fixtures.py"),
        content: s,
    }
}

fn py_literal_for(value: &str, ty: &Ty) -> String {
    match ty {
        Ty::Str | Ty::Sym => format!("{value:?}"),
        Ty::Int => {
            if value.parse::<i64>().is_ok() {
                value.to_string()
            } else {
                format!("0  # TODO: coerce {value:?}")
            }
        }
        Ty::Float => {
            if value.parse::<f64>().is_ok() {
                value.to_string()
            } else {
                format!("0.0  # TODO: coerce {value:?}")
            }
        }
        Ty::Bool => match value {
            "true" | "1" => "True".into(),
            "false" | "0" => "False".into(),
            _ => format!("False  # TODO: coerce {value:?}"),
        },
        Ty::Class { id, .. } if id.0.as_str() == "Time" => format!("{value:?}"),
        _ => format!("{value:?}"),
    }
}

fn emit_py_test(tm: &TestModule, app: &App) -> EmittedFile {
    let fixture_names: Vec<Symbol> =
        app.fixtures.iter().map(|f| f.name.clone()).collect();
    let known_models: Vec<Symbol> =
        app.models.iter().map(|m| m.name.0.clone()).collect();
    let mut attrs_set: std::collections::BTreeSet<Symbol> =
        std::collections::BTreeSet::new();
    for m in &app.models {
        for attr in m.attributes.fields.keys() {
            attrs_set.insert(attr.clone());
        }
    }
    let model_attrs: Vec<Symbol> = attrs_set.into_iter().collect();

    let ctx = PyTestCtx {
        app,
        fixture_names: &fixture_names,
        known_models: &known_models,
        model_attrs: &model_attrs,
    };

    let mut s = String::new();
    writeln!(s, "# Generated by Roundhouse.").unwrap();
    writeln!(s, "from __future__ import annotations").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "import unittest").unwrap();
    writeln!(s).unwrap();
    // Import every model so Class.new struct-literals resolve, plus all
    // fixture accessors.
    writeln!(
        s,
        "from app.models import {}",
        known_models
            .iter()
            .map(|m| m.as_str().to_string())
            .collect::<Vec<_>>()
            .join(", ")
    )
    .unwrap();
    if !app.fixtures.is_empty() {
        writeln!(s, "from tests import fixtures").unwrap();
    }

    writeln!(s).unwrap();
    writeln!(s, "class {}(unittest.TestCase):", tm.name.0.as_str()).unwrap();

    if !app.fixtures.is_empty() {
        // setUp runs before each test method — opens a fresh :memory:
        // DB and reloads all fixtures, matching Rails' transactional-
        // fixture isolation.
        writeln!(s).unwrap();
        writeln!(s, "    def setUp(self):").unwrap();
        writeln!(s, "        fixtures.setup()").unwrap();
    }

    for test in &tm.tests {
        let fn_name = format!("test_{}", test_name_snake_py(&test.name));
        writeln!(s).unwrap();
        if test_needs_runtime_unsupported_py(test) {
            writeln!(
                s,
                "    @unittest.skip(\"Phase 3: needs persistence runtime\")"
            )
            .unwrap();
            writeln!(s, "    def {fn_name}(self):").unwrap();
            writeln!(s, "        pass").unwrap();
        } else {
            writeln!(s, "    def {fn_name}(self):").unwrap();
            let body = emit_py_test_body(&test.body, ctx);
            if body.is_empty() {
                writeln!(s, "        pass").unwrap();
            } else {
                for line in body.lines() {
                    writeln!(s, "        {line}").unwrap();
                }
            }
        }
    }

    // unittest discover default pattern is `test_*.py`; convert
    // `ArticleTest` → `article_test` → `article` → `test_article`.
    let stem = crate::naming::snake_case(tm.name.0.as_str()).replace("_test", "");
    EmittedFile {
        path: PathBuf::from(format!("tests/test_{stem}.py")),
        content: s,
    }
}

fn test_name_snake_py(desc: &str) -> String {
    let mut s: String = desc
        .chars()
        .map(|c| if c.is_alphanumeric() { c.to_ascii_lowercase() } else { '_' })
        .collect();
    while s.contains("__") {
        s = s.replace("__", "_");
    }
    s.trim_matches('_').to_string()
}

#[derive(Clone, Copy)]
struct PyTestCtx<'a> {
    app: &'a App,
    fixture_names: &'a [Symbol],
    known_models: &'a [Symbol],
    model_attrs: &'a [Symbol],
}

fn emit_py_test_body(body: &Expr, ctx: PyTestCtx) -> String {
    match &*body.node {
        ExprNode::Seq { exprs } if !exprs.is_empty() => exprs
            .iter()
            .map(|e| emit_py_test_stmt(e, ctx))
            .collect::<Vec<_>>()
            .join("\n"),
        _ => emit_py_test_stmt(body, ctx),
    }
}

fn emit_py_test_stmt(e: &Expr, ctx: PyTestCtx) -> String {
    match &*e.node {
        ExprNode::Assign { target: LValue::Var { name, .. }, value } => {
            format!("{} = {}", name, emit_py_test_expr(value, ctx))
        }
        _ => emit_py_test_expr(e, ctx),
    }
}

fn emit_py_test_expr(e: &Expr, ctx: PyTestCtx) -> String {
    match &*e.node {
        ExprNode::Lit { value } => emit_literal(value),
        ExprNode::Var { name, .. } => name.to_string(),
        ExprNode::Const { path } => path
            .iter()
            .map(|s| s.to_string())
            .collect::<Vec<_>>()
            .join("."),
        ExprNode::Send { recv, method, args, block, .. } => {
            emit_py_test_send(recv.as_ref(), method.as_str(), args, block.as_ref(), ctx)
        }
        ExprNode::BoolOp { op, left, right, .. } => {
            use crate::expr::BoolOpKind;
            let op_s = match op {
                BoolOpKind::Or => "or",
                BoolOpKind::And => "and",
            };
            format!(
                "{} {op_s} {}",
                emit_py_test_expr(left, ctx),
                emit_py_test_expr(right, ctx)
            )
        }
        _ => format!("# TODO: Python test emit for {:?}", std::mem::discriminant(&*e.node)),
    }
}

fn emit_py_test_send(
    recv: Option<&Expr>,
    method: &str,
    args: &[Expr],
    block: Option<&Expr>,
    ctx: PyTestCtx,
) -> String {
    let args_s: Vec<String> = args.iter().map(|a| emit_py_test_expr(a, ctx)).collect();

    // Fixture accessor: articles(:one) → fixtures.articles_one()
    if recv.is_none()
        && args.len() == 1
        && ctx.fixture_names.iter().any(|s| s.as_str() == method)
    {
        if let ExprNode::Lit { value: Literal::Sym { value: sym } } = &*args[0].node {
            return format!("fixtures.{}_{}()", method, sym.as_str());
        }
    }

    // assert_difference("Class.count", delta) do ... end → inline
    // before/after capture + self.assertEqual on the delta.
    // Callers see this as a bare expression; we need statement form,
    // so the Stage layer (emit_py_test_stmt) handles newline wrapping.
    if recv.is_none() && method == "assert_difference" {
        if let Some(body) = block {
            if let Some(count_expr) = args
                .first()
                .and_then(|a| match &*a.node {
                    ExprNode::Lit { value: Literal::Str { value } } => {
                        rewrite_ruby_dot_call_py(value)
                    }
                    _ => None,
                })
            {
                let delta = args_s.get(1).cloned().unwrap_or_else(|| "1".into());
                let body_s = emit_block_body_py(body, ctx);
                return format!(
                    "_before = {count_expr}\n{body_s}\n_after = {count_expr}\nself.assertEqual(_after - _before, {delta})"
                );
            }
        }
    }

    // owner.<assoc>.create(hash) / .build(hash) — HasMany rewrite.
    // Python: a lambda-call with a walrus-ish shape won't work
    // cleanly, so we use a helper module-level function wouldn't
    // either. Easiest: expand to a small helper-less form. We can
    // construct Class(article_id=..., commenter=..., body=...) and
    // call save on the result. Since this sits in expression
    // position (assign rhs), wrap in a `(lambda: ...)()` one-shot.
    if (method == "create" || method == "build") && args.len() == 1 {
        if let Some(outer_recv) = recv {
            if let ExprNode::Send {
                recv: Some(assoc_recv),
                method: assoc_method,
                args: inner_args,
                ..
            } = &*outer_recv.node
            {
                if inner_args.is_empty() {
                    if let Some(s) = try_emit_assoc_create_py(
                        assoc_recv,
                        assoc_method.as_str(),
                        args,
                        method,
                        ctx,
                    ) {
                        return s;
                    }
                }
            }
        }
    }

    // Assertion macros → unittest's TestCase methods.
    if recv.is_none() {
        match (method, args_s.len()) {
            ("assert_equal", 2) => {
                return format!(
                    "self.assertEqual({}, {})",
                    args_s[1], args_s[0]
                );
            }
            ("assert_not_equal", 2) => {
                return format!(
                    "self.assertNotEqual({}, {})",
                    args_s[1], args_s[0]
                );
            }
            ("assert_not", 1) => return format!("self.assertFalse({})", args_s[0]),
            ("assert", 1) => return format!("self.assertTrue({})", args_s[0]),
            ("assert_nil", 1) => return format!("self.assertIsNone({})", args_s[0]),
            ("assert_not_nil", 1) => {
                return format!("self.assertIsNotNone({})", args_s[0])
            }
            _ => {}
        }
    }

    // `Class.new(hash)` → `Class(**{...})` or `Class(field=val, ...)`
    if let Some(r) = recv {
        if method == "new" && args.len() == 1 {
            if let ExprNode::Const { path } = &*r.node {
                if let Some(class_name) = path.last() {
                    if ctx.known_models.iter().any(|s| s == class_name) {
                        if let ExprNode::Hash { entries, .. } = &*args[0].node {
                            let pairs: Vec<String> = entries
                                .iter()
                                .filter_map(|(k, v)| {
                                    if let ExprNode::Lit {
                                        value: Literal::Sym { value: f },
                                    } = &*k.node
                                    {
                                        Some(format!(
                                            "{}={}",
                                            f.as_str(),
                                            emit_py_test_expr(v, ctx)
                                        ))
                                    } else {
                                        None
                                    }
                                })
                                .collect();
                            return format!("{class_name}({})", pairs.join(", "));
                        }
                    }
                }
            }
        }
    }

    match recv {
        None => {
            if args_s.is_empty() {
                method.to_string()
            } else {
                format!("{}({})", method, args_s.join(", "))
            }
        }
        Some(r) => {
            let recv_s = emit_py_test_expr(r, ctx);
            // Attribute read (no parens) vs method call.
            let is_attr = args_s.is_empty()
                && ctx.model_attrs.iter().any(|s| s.as_str() == method);
            if is_attr {
                format!("{recv_s}.{method}")
            } else if args_s.is_empty() {
                format!("{recv_s}.{method}()")
            } else {
                format!("{recv_s}.{method}({})", args_s.join(", "))
            }
        }
    }
}

fn test_needs_runtime_unsupported_py(_test: &Test) -> bool {
    // Phase 3 rounded out the Python emitter's real-blog coverage.
    // Keep as a future-guard; nothing in real-blog currently forces
    // a skip.
    false
}

/// Parse a Ruby `"Class.method"` string into Python `Class.method()`.
/// Uppercase LHS → class method call; lowercase LHS → attribute
/// read.
fn rewrite_ruby_dot_call_py(expr: &str) -> Option<String> {
    let trimmed = expr.trim();
    let (lhs, rhs) = trimmed.split_once('.')?;
    let is_ident = |s: &str| {
        !s.is_empty()
            && s.chars().next().is_some_and(|c| c.is_alphabetic() || c == '_')
            && s.chars().all(|c| c.is_alphanumeric() || c == '_')
    };
    if !is_ident(lhs) || !is_ident(rhs) {
        return None;
    }
    let is_class = lhs.chars().next().is_some_and(|c| c.is_uppercase());
    if is_class {
        Some(format!("{lhs}.{rhs}()"))
    } else {
        Some(format!("{lhs}.{rhs}"))
    }
}

/// Render a Ruby block body as Python statements. Ruby `do ... end`
/// lowers to ExprNode::Lambda; peel one layer.
fn emit_block_body_py(e: &Expr, ctx: PyTestCtx) -> String {
    let inner = match &*e.node {
        ExprNode::Lambda { body, .. } => body,
        _ => e,
    };
    match &*inner.node {
        ExprNode::Seq { exprs } if !exprs.is_empty() => exprs
            .iter()
            .map(|s| emit_py_test_stmt(s, ctx))
            .collect::<Vec<_>>()
            .join("\n"),
        _ => emit_py_test_stmt(inner, ctx),
    }
}

fn try_emit_assoc_create_py(
    owner: &Expr,
    assoc_name: &str,
    args: &[Expr],
    outer_method: &str,
    ctx: PyTestCtx,
) -> Option<String> {
    let resolved = crate::lower::resolve_has_many(
        &Symbol::from(assoc_name),
        owner.ty.as_ref(),
        ctx.app,
    )?;
    let target_class = resolved.target_class.0.as_str();
    let foreign_key = resolved.foreign_key.as_str();

    let owner_s = emit_py_test_expr(owner, ctx);
    let hash_entries = match &args.first()?.node.as_ref() {
        ExprNode::Hash { entries, .. } => entries.clone(),
        _ => return None,
    };

    let mut kwargs: Vec<String> = vec![format!("{foreign_key}={owner_s}.id")];
    for (k, v) in &hash_entries {
        if let ExprNode::Lit { value: Literal::Sym { value: field_name } } = &*k.node {
            kwargs.push(format!(
                "{}={}",
                field_name.as_str(),
                emit_py_test_expr(v, ctx),
            ));
        }
    }
    let ctor = format!("{target_class}({})", kwargs.join(", "));
    // Python expression-form sequence: walrus operator in a tuple
    // evaluates both and yields the record. `.create` runs save;
    // `.build` doesn't.
    if outer_method == "create" {
        Some(format!(
            "(lambda _r: (_r.save(), _r)[1])({ctor})"
        ))
    } else {
        Some(ctor)
    }
}

fn test_body_uses_unsupported_py(e: &Expr) -> bool {
    use crate::expr::InterpPart;
    let self_hit = match &*e.node {
        ExprNode::Send { recv, method, .. } => {
            let m = method.as_str();
            matches!(
                m,
                "assert_difference"
                    | "destroy"
                    | "destroy!"
                    | "build"
                    | "create"
                    | "create!"
            ) || (m == "count"
                && recv.as_ref().is_some_and(|r| matches!(&*r.node, ExprNode::Const { .. })))
        }
        _ => false,
    };
    if self_hit {
        return true;
    }
    match &*e.node {
        ExprNode::Send { recv, args, block, .. } => {
            if let Some(r) = recv {
                if test_body_uses_unsupported_py(r) {
                    return true;
                }
            }
            for a in args {
                if test_body_uses_unsupported_py(a) {
                    return true;
                }
            }
            if let Some(b) = block {
                if test_body_uses_unsupported_py(b) {
                    return true;
                }
            }
        }
        ExprNode::Seq { exprs } | ExprNode::Array { elements: exprs, .. } => {
            for e in exprs {
                if test_body_uses_unsupported_py(e) {
                    return true;
                }
            }
        }
        ExprNode::Hash { entries, .. } => {
            for (k, v) in entries {
                if test_body_uses_unsupported_py(k) || test_body_uses_unsupported_py(v) {
                    return true;
                }
            }
        }
        ExprNode::StringInterp { parts } => {
            for p in parts {
                if let InterpPart::Expr { expr } = p {
                    if test_body_uses_unsupported_py(expr) {
                        return true;
                    }
                }
            }
        }
        ExprNode::BoolOp { left, right, .. }
        | ExprNode::RescueModifier { expr: left, fallback: right } => {
            if test_body_uses_unsupported_py(left) || test_body_uses_unsupported_py(right) {
                return true;
            }
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            if test_body_uses_unsupported_py(cond)
                || test_body_uses_unsupported_py(then_branch)
                || test_body_uses_unsupported_py(else_branch)
            {
                return true;
            }
        }
        ExprNode::Let { value, body, .. } => {
            if test_body_uses_unsupported_py(value) || test_body_uses_unsupported_py(body) {
                return true;
            }
        }
        ExprNode::Lambda { body, .. } => {
            if test_body_uses_unsupported_py(body) {
                return true;
            }
        }
        ExprNode::Assign { value, .. } => {
            if test_body_uses_unsupported_py(value) {
                return true;
            }
        }
        _ => {}
    }
    false
}
