//! Rust emitter.
//!
//! First-pass scope: emit each model as a plain struct with its attributes
//! as fields. No derives, no associations-as-references, no behavior — just
//! data shape. Extend incrementally; pressure from this emitter is what will
//! tell us where the IR and the analyzer need to grow.
//!
//! This is the first *typed* target. Unlike the Ruby emitter, output here
//! depends on `Ty` — `Str` → `String`, `Int` → `i64`, `Option<Ty::Nil, T>`
//! → `Option<T>`. The `ruby_emit_is_type_invariant` test deliberately
//! does NOT generalize to this emitter.

use std::fmt::Write;
use std::path::PathBuf;

use super::EmittedFile;
use crate::App;
use crate::dialect::{Action, Controller, MethodDef, Model};
use crate::expr::{Expr, ExprNode, LValue, Literal};
use crate::ident::Symbol;
use crate::naming::snake_case;
use crate::ty::Ty;

/// Source of the hand-written Roundhouse Rust runtime. Pulled in at
/// compile time from `runtime/rust/runtime.rs` so the file stays
/// editable as normal Rust (with its own tests, rust-analyzer support,
/// etc.) rather than living as a string constant here. When the
/// emitter runs, this string is copied verbatim into the generated
/// project's `src/runtime.rs`.
const RUNTIME_SOURCE: &str = include_str!("../../runtime/rust/runtime.rs");

pub fn emit(app: &App) -> Vec<EmittedFile> {
    let mut files = Vec::new();

    // Project skeleton: Cargo.toml + src/lib.rs. These tag along
    // unconditionally so the output is a self-contained Cargo project
    // the target toolchain will accept.
    files.push(emit_cargo_toml());

    if !app.models.is_empty() {
        files.push(emit_models(app));
        // The runtime tags along whenever any model is emitted —
        // every non-trivial app references at least
        // `crate::runtime::ValidationError` through the lowered
        // validation evaluator.
        files.push(EmittedFile {
            path: PathBuf::from("src/runtime.rs"),
            content: RUNTIME_SOURCE.to_string(),
        });
    }
    for controller in &app.controllers {
        files.push(emit_controller(controller));
    }

    // lib.rs declares the modules we emitted. Phase 1 scope: models +
    // runtime only. Controllers are emitted as files but not yet wired
    // into lib.rs — their bodies reference runtime that doesn't exist
    // yet (params, redirect_to, AR dispatch), so including them blocks
    // cargo check until Phase 3 wires the runtime.
    files.push(emit_lib_rs(app));

    files
}

/// A minimal Cargo.toml for a library crate. Phase 1 scope uses std
/// only; when the controller-runtime work lands, add `rusqlite`,
/// `axum`, etc. via feature flags or a richer template.
fn emit_cargo_toml() -> EmittedFile {
    let content = "\
[package]
name = \"app\"
version = \"0.1.0\"
edition = \"2024\"

[lib]
path = \"src/lib.rs\"

[dependencies]
";
    EmittedFile {
        path: PathBuf::from("Cargo.toml"),
        content: content.to_string(),
    }
}

/// `src/lib.rs` — declares the crate modules Phase 1 expects to compile.
/// Controllers deliberately excluded until their runtime lands.
fn emit_lib_rs(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s).unwrap();
    if !app.models.is_empty() {
        writeln!(s, "pub mod runtime;").unwrap();
        writeln!(s, "pub mod models;").unwrap();
    }
    EmittedFile {
        path: PathBuf::from("src/lib.rs"),
        content: s,
    }
}

fn emit_models(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();

    // Import ValidationError from the (as-yet-unwritten) Roundhouse
    // Rust runtime if any model in this file has validations.
    // Phase 4's Rust runtime will define it; for now the `use` line
    // references an intended module that the generated code expects.
    let any_validations = app
        .models
        .iter()
        .any(|m| !crate::lower::lower_validations(m).is_empty());
    if any_validations {
        writeln!(s).unwrap();
        writeln!(s, "use crate::runtime;").unwrap();
    }

    for model in &app.models {
        writeln!(s).unwrap();
        emit_struct(&mut s, model);
        let lowered = crate::lower::lower_validations(model);
        let has_methods = model.methods().next().is_some();
        if has_methods || !lowered.is_empty() {
            writeln!(s).unwrap();
            emit_model_impl(&mut s, model, &lowered);
        }
    }
    EmittedFile { path: PathBuf::from("src/models.rs"), content: s }
}

fn emit_struct(out: &mut String, model: &Model) {
    writeln!(out, "pub struct {} {{", model.name.0).unwrap();
    for (name, ty) in &model.attributes.fields {
        writeln!(out, "    pub {}: {},", name, rust_ty(ty)).unwrap();
    }
    writeln!(out, "}}").unwrap();
}

fn emit_model_impl(
    out: &mut String,
    model: &Model,
    validations: &[crate::lower::LoweredValidation],
) {
    writeln!(out, "impl {} {{", model.name.0).unwrap();
    // Collect the names of attributes + methods on this class. Used by
    // emit_model_method to rewrite bare-name Sends (implicit-self calls)
    // into `self.method` when the name matches one of our members.
    let self_methods: Vec<Symbol> = model
        .attributes
        .fields
        .keys()
        .cloned()
        .chain(model.methods().map(|m| m.name.clone()))
        .collect();

    let mut first = true;
    for method in model.methods() {
        if !first {
            writeln!(out).unwrap();
        }
        first = false;
        emit_model_method(out, method, &self_methods);
    }
    if !validations.is_empty() {
        if !first {
            writeln!(out).unwrap();
        }
        emit_validate_method(out, validations);
    }
    writeln!(out, "}}").unwrap();
}

/// Render `fn validate(&self) -> Vec<runtime::ValidationError>` with
/// each lowered `Check` as an inline conditional. No runtime
/// validation primitives — the IR is the shared vocabulary, the
/// render is target-specific code. This is the Phase 4 showpiece:
/// the same `LoweredValidation` input feeds the TS emitter (which
/// calls Juntos's `this.validates_<kind>_of(...)` primitives) and
/// this emitter (which inlines the checks as plain Rust).
fn emit_validate_method(out: &mut String, validations: &[crate::lower::LoweredValidation]) {
    writeln!(
        out,
        "    pub fn validate(&self) -> Vec<runtime::ValidationError> {{"
    )
    .unwrap();
    writeln!(out, "        let mut errors = Vec::new();").unwrap();
    for lv in validations {
        for check in &lv.checks {
            emit_check_inline(out, lv.attribute.as_str(), check);
        }
    }
    writeln!(out, "        errors").unwrap();
    writeln!(out, "    }}").unwrap();
}

/// Render one atomic `Check` as a Rust `if` block that pushes a
/// `ValidationError` when the failure condition holds. Field access
/// uses `self.<attr>` directly — Rust's type system gives us concrete
/// access without the runtime-reflection gymnastics a generic
/// evaluator would need. Each `Check` variant maps 1:1 to a small
/// inline condition; default error message comes from the check.
fn emit_check_inline(out: &mut String, attr: &str, check: &crate::lower::Check) {
    use crate::lower::{Check, InclusionValue};
    let msg = check.default_message();
    let push = |cond: &str| -> String {
        format!(
            "        if {cond} {{\n            errors.push(runtime::ValidationError::new({attr:?}, {msg:?}));\n        }}",
        )
    };
    let block = match check {
        // Field must not be empty. The scaffold assumes a `String`
        // field; future fixtures with `Option<String>` would need
        // `self.<attr>.as_deref().unwrap_or("").is_empty()` or similar
        // — drive from a real case when one appears.
        Check::Presence => push(&format!("self.{attr}.is_empty()")),
        Check::Absence => push(&format!("!self.{attr}.is_empty()")),
        Check::MinLength { n } => push(&format!("self.{attr}.len() < {n}")),
        Check::MaxLength { n } => push(&format!("self.{attr}.len() > {n}")),
        Check::GreaterThan { threshold } => {
            push(&format!("self.{attr} <= {threshold}"))
        }
        Check::LessThan { threshold } => push(&format!("self.{attr} >= {threshold}")),
        Check::OnlyInteger => {
            // Rust's type system already distinguishes integer vs
            // float fields, so `only_integer` is semantically a
            // no-op here — the field is either i64 or f64 by Ty.
            // Emit a comment so it's clear the check was recognized
            // and handled at compile time rather than silently dropped.
            format!("        // OnlyInteger check on {attr:?} — enforced by Rust type system")
        }
        Check::Inclusion { values } => {
            let parts: Vec<String> = values.iter().map(inclusion_value_to_rust).collect();
            push(&format!(
                "![{}].contains(&self.{attr})",
                parts.join(", ")
            ))
        }
        Check::Format { pattern } => {
            // Regex dependency is a Phase-4-runtime choice; for the
            // scaffold emit a commented-out check so the generated
            // code compiles (once the runtime exists, swap in the
            // real regex call).
            format!(
                "        // TODO: Format check on {attr:?} requires runtime regex ({pattern:?})",
            )
        }
        Check::Uniqueness { .. } => {
            // Uniqueness hits the DB — it's a runtime concern, not an
            // inline check. The real runtime will provide
            // `runtime::check_uniqueness(record, attr, ...)`; until
            // then, leave a marker.
            format!(
                "        // TODO: Uniqueness check on {attr:?} requires DB access at runtime",
            )
        }
        Check::Custom { method } => {
            // User-defined method populates `errors` itself. Emit a
            // call through to it; the user is responsible for the
            // signature.
            let _ = InclusionValue::Str { value: String::new() };
            format!("        self.{method}(&mut errors);")
        }
    };
    writeln!(out, "{block}").unwrap();
}

/// Render an `InclusionValue` as a Rust literal.
fn inclusion_value_to_rust(v: &crate::lower::InclusionValue) -> String {
    use crate::lower::InclusionValue;
    match v {
        InclusionValue::Str { value } => format!("{value:?}.to_string()"),
        InclusionValue::Int { value } => format!("{value}i64"),
        InclusionValue::Float { value } => {
            let s = value.to_string();
            if s.contains('.') { format!("{s}f64") } else { format!("{s}.0f64") }
        }
        InclusionValue::Bool { value } => value.to_string(),
    }
}

fn emit_model_method(out: &mut String, m: &MethodDef, self_methods: &[Symbol]) {
    let ret_ty = m.body.ty.clone().unwrap_or(Ty::Nil);
    let receiver = match m.receiver {
        crate::dialect::MethodReceiver::Instance => "&self",
        crate::dialect::MethodReceiver::Class => "",
    };
    writeln!(
        out,
        "    pub fn {}({}) -> {} {{",
        m.name,
        receiver,
        rust_ty(&ret_ty),
    )
    .unwrap();
    let ctx = EmitCtx { self_methods };
    for line in emit_expr(&m.body, ctx).lines() {
        writeln!(out, "        {}", line).unwrap();
    }
    writeln!(out, "    }}").unwrap();
}

// Controllers ----------------------------------------------------------

fn emit_controller(controller: &Controller) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "pub struct {};", controller.name.0).unwrap();
    writeln!(s).unwrap();
    writeln!(s, "impl {} {{", controller.name.0).unwrap();
    for (i, action) in controller.actions().enumerate() {
        if i > 0 {
            writeln!(s).unwrap();
        }
        emit_action(&mut s, action);
    }
    writeln!(s, "}}").unwrap();

    let filename = format!("src/controllers/{}.rs", snake_case(controller.name.0.as_str()));
    EmittedFile { path: PathBuf::from(filename), content: s }
}

fn emit_action(out: &mut String, action: &Action) {
    let ret_ty = action_return_type(&action.body);
    writeln!(
        out,
        "    pub fn {}() -> {} {{",
        action.name,
        rust_ty(&ret_ty),
    )
    .unwrap();
    let body = emit_body(&action.body, EmitCtx::default());
    for line in body.lines() {
        writeln!(out, "        {}", line).unwrap();
    }
    writeln!(out, "    }}").unwrap();
}

/// The "return value" of a Ruby action body is usually the RHS of the last
/// assignment (ivar-to-view convention). Squint at the body and pick.
fn action_return_type(body: &Expr) -> Ty {
    match &*body.node {
        ExprNode::Assign { value, .. } => value.ty.clone().unwrap_or(Ty::Nil),
        ExprNode::Seq { exprs } => exprs
            .last()
            .and_then(|e| match &*e.node {
                ExprNode::Assign { value, .. } => value.ty.clone(),
                _ => e.ty.clone(),
            })
            .unwrap_or(Ty::Nil),
        _ => body.ty.clone().unwrap_or(Ty::Nil),
    }
}

/// Context threaded through expression emission. Only field today is the
/// enclosing class's method/attribute names: when a bare-name `Send` (Ruby's
/// implicit-self call) matches one of these, it emits as `self.method`
/// rather than the bare identifier. Outside a model method (controllers,
/// free-form expressions), `self_methods` is empty and emit keeps its
/// current behavior.
#[derive(Default, Clone, Copy)]
struct EmitCtx<'a> {
    self_methods: &'a [Symbol],
}

fn emit_body(body: &Expr, ctx: EmitCtx) -> String {
    // An action body like `@posts = Post.all` drops the ivar assignment and
    // just returns the RHS (Rails convention: ivars pass data to the view).
    // Local-variable assignments become `let` bindings. Multi-statement
    // bodies join with newlines, tail-expression is the function's return.
    match &*body.node {
        ExprNode::Assign { target: LValue::Ivar { .. }, value } => emit_expr(value, ctx),
        ExprNode::Seq { exprs } if !exprs.is_empty() => {
            let mut lines: Vec<String> = Vec::new();
            for (i, e) in exprs.iter().enumerate() {
                lines.push(emit_stmt(e, i == exprs.len() - 1, ctx));
            }
            lines.join("\n")
        }
        _ => emit_expr(body, ctx),
    }
}

fn emit_stmt(e: &Expr, is_last: bool, ctx: EmitCtx) -> String {
    match &*e.node {
        // Local `foo = expr` -> `let foo = expr;`.
        ExprNode::Assign { target: LValue::Var { name, .. }, value } => {
            format!("let {} = {};", name, emit_expr(value, ctx))
        }
        // Ivars in a multi-statement body: treat as locals. Later stmts can
        // read them via `ExprNode::Ivar` which also emits as the bare name.
        ExprNode::Assign { target: LValue::Ivar { name }, value } => {
            format!("let {} = {};", name, emit_expr(value, ctx))
        }
        _ => {
            if is_last {
                emit_expr(e, ctx)
            } else {
                format!("{};", emit_expr(e, ctx))
            }
        }
    }
}

fn emit_expr(e: &Expr, ctx: EmitCtx) -> String {
    match &*e.node {
        ExprNode::Lit { value } => emit_literal(value),
        ExprNode::Const { path } => {
            path.iter().map(|s| s.to_string()).collect::<Vec<_>>().join("::")
        }
        ExprNode::Var { name, .. } => name.to_string(),
        // Rails ivars become plain locals in the action body's Rust scope.
        // Cross-action ivar handoff (via filters, views) is a separate concern.
        ExprNode::Ivar { name } => name.to_string(),
        ExprNode::Hash { entries, .. } => {
            // Rough approximation — real target code would probably want a
            // strongly-typed struct. HashMap::from is the dumbest-that-works.
            let parts: Vec<String> = entries
                .iter()
                .map(|(k, v)| format!("({}, {})", emit_expr(k, ctx), emit_expr(v, ctx)))
                .collect();
            format!("HashMap::from([{}])", parts.join(", "))
        }
        ExprNode::Array { elements, .. } => {
            let parts: Vec<String> = elements.iter().map(|e| emit_expr(e, ctx)).collect();
            format!("vec![{}]", parts.join(", "))
        }
        ExprNode::BoolOp { op, left, right, .. } => {
            use crate::expr::BoolOpKind;
            let op_s = match op {
                BoolOpKind::Or => "||",
                BoolOpKind::And => "&&",
            };
            format!("{} {} {}", emit_expr(left, ctx), op_s, emit_expr(right, ctx))
        }
        ExprNode::StringInterp { parts } => {
            use crate::expr::InterpPart;
            let mut fmt = String::new();
            let mut args: Vec<String> = Vec::new();
            for p in parts {
                match p {
                    InterpPart::Text { value } => {
                        for c in value.chars() {
                            if c == '{' || c == '}' {
                                fmt.push(c);
                                fmt.push(c);
                            } else {
                                fmt.push(c);
                            }
                        }
                    }
                    InterpPart::Expr { expr } => {
                        fmt.push_str("{}");
                        args.push(emit_expr(expr, ctx));
                    }
                }
            }
            if args.is_empty() {
                format!("{fmt:?}.to_string()")
            } else {
                format!("format!({fmt:?}, {})", args.join(", "))
            }
        }
        ExprNode::Send { recv, method, args, .. } => emit_send(recv.as_ref(), method.as_str(), args, ctx),
        ExprNode::Assign { target: _, value } => emit_expr(value, ctx),
        ExprNode::Seq { exprs } => {
            exprs.iter().map(|e| emit_expr(e, ctx)).collect::<Vec<_>>().join("; ")
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            let cond_s = emit_expr(cond, ctx);
            let then_s = emit_block_body(then_branch, ctx);
            let else_s = emit_block_body(else_branch, ctx);
            format!("if {cond_s} {{\n{then_s}\n}} else {{\n{else_s}\n}}")
        }
        other => format!("/* TODO: emit {:?} */", std::mem::discriminant(other)),
    }
}

/// Emit an expression as the body of a `{ ... }` block, indented one level.
/// For a Seq, each non-tail statement gets a trailing `;`; the tail stays
/// as the block's value expression. For a single expression, emit it alone.
fn emit_block_body(e: &Expr, ctx: EmitCtx) -> String {
    let raw = match &*e.node {
        ExprNode::Seq { exprs } => {
            let mut lines: Vec<String> = Vec::new();
            for (i, inner) in exprs.iter().enumerate() {
                if i == exprs.len() - 1 {
                    lines.push(emit_expr(inner, ctx));
                } else {
                    lines.push(format!("{};", emit_expr(inner, ctx)));
                }
            }
            lines.join("\n")
        }
        _ => emit_expr(e, ctx),
    };
    raw.lines().map(|l| format!("    {l}")).collect::<Vec<_>>().join("\n")
}

fn emit_send(recv: Option<&Expr>, method: &str, args: &[Expr], ctx: EmitCtx) -> String {
    let args_s: Vec<String> = args.iter().map(|a| emit_expr(a, ctx)).collect();

    // `recv[args]` sugar for the `[]` method.
    if method == "[]" && recv.is_some() {
        return format!("{}[{}]", emit_expr(recv.unwrap(), ctx), args_s.join(", "));
    }

    match recv {
        None => {
            // Bare-name Send on implicit self: if the enclosing class has
            // this method/attribute, emit as `self.method` — Ruby's
            // self-dispatch doesn't translate to Rust's bare-name scope.
            if ctx.self_methods.iter().any(|s| s.as_str() == method) {
                if args_s.is_empty() {
                    return format!("self.{method}");
                } else {
                    return format!("self.{method}({})", args_s.join(", "));
                }
            }
            if args_s.is_empty() {
                method.to_string()
            } else {
                format!("{}({})", method, args_s.join(", "))
            }
        }
        Some(r) => {
            let recv_s = emit_expr(r, ctx);
            // Class method dispatch (`Post.all`) uses `::`; instance method
            // dispatch (`post.title`) uses `.`. Heuristic: constants look
            // class-ish.
            let is_class_call = matches!(&*r.node, ExprNode::Const { .. });
            let sep = if is_class_call { "::" } else { "." };
            // Ruby→Rust instance-method name mapping (e.g., `String#strip`
            // → `str::trim` + `.to_string()` so the return type stays
            // `String`). Only applies to instance dispatch — class calls
            // keep the Ruby name untouched.
            let (rust_method, suffix) = if is_class_call {
                (method.to_string(), String::new())
            } else {
                map_instance_method(method, r.ty.as_ref())
            };
            if args_s.is_empty() {
                format!("{recv_s}{sep}{rust_method}(){suffix}")
            } else {
                format!("{recv_s}{sep}{rust_method}({}){suffix}", args_s.join(", "))
            }
        }
    }
}

/// Map a Ruby instance-method call to its Rust equivalent, returning the
/// Rust method name and an optional call-site suffix (commonly `.to_string()`
/// when a `&str`-returning Rust method replaces a `String`-returning Ruby
/// one). Grows as new fixtures surface new cases; unmapped methods pass
/// through with their Ruby name.
fn map_instance_method(method: &str, recv_ty: Option<&Ty>) -> (String, String) {
    match recv_ty {
        Some(Ty::Str) => match method {
            // Ruby's `strip` returns a new String; Rust's `trim` returns
            // `&str`. Wrap in `.to_string()` so the type matches.
            "strip" => ("trim".into(), ".to_string()".into()),
            _ => (method.into(), String::new()),
        },
        _ => (method.into(), String::new()),
    }
}

fn emit_literal(lit: &Literal) -> String {
    match lit {
        Literal::Nil => "None".to_string(),
        Literal::Bool { value } => value.to_string(),
        Literal::Int { value } => format!("{value}_i64"),
        Literal::Float { value } => format!("{value}_f64"),
        Literal::Str { value } => format!("{value:?}.to_string()"),
        Literal::Sym { value } => format!("{:?}", value.as_str()),
    }
}

pub fn rust_ty(ty: &Ty) -> String {
    match ty {
        Ty::Int => "i64".to_string(),
        Ty::Float => "f64".to_string(),
        Ty::Bool => "bool".to_string(),
        Ty::Str => "String".to_string(),
        Ty::Sym => "String".to_string(),
        Ty::Nil => "()".to_string(),
        Ty::Array { elem } => format!("Vec<{}>", rust_ty(elem)),
        Ty::Hash { key, value } => {
            format!("std::collections::HashMap<{}, {}>", rust_ty(key), rust_ty(value))
        }
        Ty::Tuple { elems } => {
            let parts: Vec<String> = elems.iter().map(rust_ty).collect();
            format!("({})", parts.join(", "))
        }
        Ty::Record { .. } => "serde_json::Value".to_string(),
        Ty::Union { variants } => option_shape(variants).unwrap_or_else(|| {
            // Non-nullable unions: fall back to a boxed trait object for now.
            // Real answer: emit an enum. Landing when a fixture demands it.
            "Box<dyn std::any::Any>".to_string()
        }),
        Ty::Class { id, .. } => id.0.to_string(),
        Ty::Fn { .. } => "Box<dyn Fn()>".to_string(),
        Ty::Var { .. } => "()".to_string(),
    }
}

fn option_shape(variants: &[Ty]) -> Option<String> {
    if variants.len() != 2 {
        return None;
    }
    match (&variants[0], &variants[1]) {
        (Ty::Nil, other) | (other, Ty::Nil) => Some(format!("Option<{}>", rust_ty(other))),
        _ => None,
    }
}
