//! Rust emitter.
//!
//! First-pass scope: emit each model as a plain struct with its attributes
//! as fields. No derives, no associations-as-references, no behavior — just
//! data shape. Extend incrementally; pressure from this emitter is what will
//! tell us where the IR and the analyzer need to grow.
//!
//! This is the first *typed* target. Unlike the Ruby emitter, output here
//! depends on `Ty` — `Str` → `String`, `Int` → `i64`, `Option<Ty::Nil, T>`
//! → `Option<T>`. The `ruby_emit_is_type_invariant` test deliberately
//! does NOT generalize to this emitter.

use std::fmt::Write;
use std::path::PathBuf;

use super::EmittedFile;
use crate::App;
use crate::dialect::{Action, Controller, MethodDef, Model};
use crate::expr::{Expr, ExprNode, LValue, Literal};
use crate::naming::snake_case;
use crate::ty::Ty;

pub fn emit(app: &App) -> Vec<EmittedFile> {
    let mut files = Vec::new();
    if !app.models.is_empty() {
        files.push(emit_models(app));
    }
    for controller in &app.controllers {
        files.push(emit_controller(controller));
    }
    files
}

fn emit_models(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    for model in &app.models {
        writeln!(s).unwrap();
        emit_struct(&mut s, model);
        if !model.methods.is_empty() {
            writeln!(s).unwrap();
            emit_model_impl(&mut s, model);
        }
    }
    EmittedFile { path: PathBuf::from("src/models.rs"), content: s }
}

fn emit_struct(out: &mut String, model: &Model) {
    writeln!(out, "pub struct {} {{", model.name.0).unwrap();
    for (name, ty) in &model.attributes.fields {
        writeln!(out, "    pub {}: {},", name, rust_ty(ty)).unwrap();
    }
    writeln!(out, "}}").unwrap();
}

fn emit_model_impl(out: &mut String, model: &Model) {
    writeln!(out, "impl {} {{", model.name.0).unwrap();
    for (i, method) in model.methods.iter().enumerate() {
        if i > 0 {
            writeln!(out).unwrap();
        }
        emit_model_method(out, method);
    }
    writeln!(out, "}}").unwrap();
}

fn emit_model_method(out: &mut String, m: &MethodDef) {
    let ret_ty = m.body.ty.clone().unwrap_or(Ty::Nil);
    let receiver = match m.receiver {
        crate::dialect::MethodReceiver::Instance => "&self",
        crate::dialect::MethodReceiver::Class => "",
    };
    writeln!(
        out,
        "    pub fn {}({}) -> {} {{",
        m.name,
        receiver,
        rust_ty(&ret_ty),
    )
    .unwrap();
    for line in emit_expr(&m.body).lines() {
        writeln!(out, "        {}", line).unwrap();
    }
    writeln!(out, "    }}").unwrap();
}

// Controllers ----------------------------------------------------------

fn emit_controller(controller: &Controller) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "pub struct {};", controller.name.0).unwrap();
    writeln!(s).unwrap();
    writeln!(s, "impl {} {{", controller.name.0).unwrap();
    for (i, action) in controller.actions.iter().enumerate() {
        if i > 0 {
            writeln!(s).unwrap();
        }
        emit_action(&mut s, action);
    }
    writeln!(s, "}}").unwrap();

    let filename = format!("src/controllers/{}.rs", snake_case(controller.name.0.as_str()));
    EmittedFile { path: PathBuf::from(filename), content: s }
}

fn emit_action(out: &mut String, action: &Action) {
    let ret_ty = action_return_type(&action.body);
    writeln!(
        out,
        "    pub fn {}() -> {} {{",
        action.name,
        rust_ty(&ret_ty),
    )
    .unwrap();
    let body = emit_body(&action.body);
    for line in body.lines() {
        writeln!(out, "        {}", line).unwrap();
    }
    writeln!(out, "    }}").unwrap();
}

/// The "return value" of a Ruby action body is usually the RHS of the last
/// assignment (ivar-to-view convention). Squint at the body and pick.
fn action_return_type(body: &Expr) -> Ty {
    match &*body.node {
        ExprNode::Assign { value, .. } => value.ty.clone().unwrap_or(Ty::Nil),
        ExprNode::Seq { exprs } => exprs
            .last()
            .and_then(|e| match &*e.node {
                ExprNode::Assign { value, .. } => value.ty.clone(),
                _ => e.ty.clone(),
            })
            .unwrap_or(Ty::Nil),
        _ => body.ty.clone().unwrap_or(Ty::Nil),
    }
}

fn emit_body(body: &Expr) -> String {
    // An action body like `@posts = Post.all` drops the ivar assignment and
    // just returns the RHS (Rails convention: ivars pass data to the view).
    // Local-variable assignments become `let` bindings. Multi-statement
    // bodies join with newlines, tail-expression is the function's return.
    match &*body.node {
        ExprNode::Assign { target: LValue::Ivar { .. }, value } => emit_expr(value),
        ExprNode::Seq { exprs } if !exprs.is_empty() => {
            let mut lines: Vec<String> = Vec::new();
            for (i, e) in exprs.iter().enumerate() {
                lines.push(emit_stmt(e, i == exprs.len() - 1));
            }
            lines.join("\n")
        }
        _ => emit_expr(body),
    }
}

fn emit_stmt(e: &Expr, is_last: bool) -> String {
    match &*e.node {
        // Local `foo = expr` -> `let foo = expr;`.
        ExprNode::Assign { target: LValue::Var { name, .. }, value } => {
            format!("let {} = {};", name, emit_expr(value))
        }
        // Ivars in a multi-statement body: treat as locals. Later stmts can
        // read them via `ExprNode::Ivar` which also emits as the bare name.
        ExprNode::Assign { target: LValue::Ivar { name }, value } => {
            format!("let {} = {};", name, emit_expr(value))
        }
        _ => {
            if is_last {
                emit_expr(e)
            } else {
                format!("{};", emit_expr(e))
            }
        }
    }
}

fn emit_expr(e: &Expr) -> String {
    match &*e.node {
        ExprNode::Lit { value } => emit_literal(value),
        ExprNode::Const { path } => {
            path.iter().map(|s| s.to_string()).collect::<Vec<_>>().join("::")
        }
        ExprNode::Var { name, .. } => name.to_string(),
        // Rails ivars become plain locals in the action body's Rust scope.
        // Cross-action ivar handoff (via filters, views) is a separate concern.
        ExprNode::Ivar { name } => name.to_string(),
        ExprNode::Hash { entries, .. } => {
            // Rough approximation — real target code would probably want a
            // strongly-typed struct. HashMap::from is the dumbest-that-works.
            let parts: Vec<String> = entries
                .iter()
                .map(|(k, v)| format!("({}, {})", emit_expr(k), emit_expr(v)))
                .collect();
            format!("HashMap::from([{}])", parts.join(", "))
        }
        ExprNode::Array { elements, .. } => {
            let parts: Vec<String> = elements.iter().map(emit_expr).collect();
            format!("vec![{}]", parts.join(", "))
        }
        ExprNode::BoolOp { op, left, right, .. } => {
            use crate::expr::BoolOpKind;
            let op_s = match op {
                BoolOpKind::Or => "||",
                BoolOpKind::And => "&&",
            };
            format!("{} {} {}", emit_expr(left), op_s, emit_expr(right))
        }
        ExprNode::StringInterp { parts } => {
            use crate::expr::InterpPart;
            let mut fmt = String::new();
            let mut args: Vec<String> = Vec::new();
            for p in parts {
                match p {
                    InterpPart::Text { value } => {
                        for c in value.chars() {
                            if c == '{' || c == '}' {
                                fmt.push(c);
                                fmt.push(c);
                            } else {
                                fmt.push(c);
                            }
                        }
                    }
                    InterpPart::Expr { expr } => {
                        fmt.push_str("{}");
                        args.push(emit_expr(expr));
                    }
                }
            }
            if args.is_empty() {
                format!("{fmt:?}.to_string()")
            } else {
                format!("format!({fmt:?}, {})", args.join(", "))
            }
        }
        ExprNode::Send { recv, method, args, .. } => emit_send(recv.as_ref(), method.as_str(), args),
        ExprNode::Assign { target: _, value } => emit_expr(value),
        ExprNode::Seq { exprs } => {
            exprs.iter().map(emit_expr).collect::<Vec<_>>().join("; ")
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            let cond_s = emit_expr(cond);
            let then_s = emit_block_body(then_branch);
            let else_s = emit_block_body(else_branch);
            format!("if {cond_s} {{\n{then_s}\n}} else {{\n{else_s}\n}}")
        }
        other => format!("/* TODO: emit {:?} */", std::mem::discriminant(other)),
    }
}

/// Emit an expression as the body of a `{ ... }` block, indented one level.
/// For a Seq, each non-tail statement gets a trailing `;`; the tail stays
/// as the block's value expression. For a single expression, emit it alone.
fn emit_block_body(e: &Expr) -> String {
    let raw = match &*e.node {
        ExprNode::Seq { exprs } => {
            let mut lines: Vec<String> = Vec::new();
            for (i, inner) in exprs.iter().enumerate() {
                if i == exprs.len() - 1 {
                    lines.push(emit_expr(inner));
                } else {
                    lines.push(format!("{};", emit_expr(inner)));
                }
            }
            lines.join("\n")
        }
        _ => emit_expr(e),
    };
    raw.lines().map(|l| format!("    {l}")).collect::<Vec<_>>().join("\n")
}

fn emit_send(recv: Option<&Expr>, method: &str, args: &[Expr]) -> String {
    let args_s: Vec<String> = args.iter().map(emit_expr).collect();

    // `recv[args]` sugar for the `[]` method.
    if method == "[]" && recv.is_some() {
        return format!("{}[{}]", emit_expr(recv.unwrap()), args_s.join(", "));
    }

    match recv {
        None => {
            if args_s.is_empty() {
                method.to_string()
            } else {
                format!("{}({})", method, args_s.join(", "))
            }
        }
        Some(r) => {
            let recv_s = emit_expr(r);
            // Class method dispatch (`Post.all`) uses `::`; instance method
            // dispatch (`post.title`) uses `.`. Heuristic: constants look
            // class-ish.
            let is_class_call = matches!(&*r.node, ExprNode::Const { .. });
            let sep = if is_class_call { "::" } else { "." };
            if args_s.is_empty() {
                format!("{recv_s}{sep}{method}()")
            } else {
                format!("{recv_s}{sep}{method}({})", args_s.join(", "))
            }
        }
    }
}

fn emit_literal(lit: &Literal) -> String {
    match lit {
        Literal::Nil => "None".to_string(),
        Literal::Bool { value } => value.to_string(),
        Literal::Int { value } => format!("{value}_i64"),
        Literal::Float { value } => format!("{value}_f64"),
        Literal::Str { value } => format!("{value:?}.to_string()"),
        Literal::Sym { value } => format!("{:?}", value.as_str()),
    }
}

pub fn rust_ty(ty: &Ty) -> String {
    match ty {
        Ty::Int => "i64".to_string(),
        Ty::Float => "f64".to_string(),
        Ty::Bool => "bool".to_string(),
        Ty::Str => "String".to_string(),
        Ty::Sym => "String".to_string(),
        Ty::Nil => "()".to_string(),
        Ty::Array { elem } => format!("Vec<{}>", rust_ty(elem)),
        Ty::Hash { key, value } => {
            format!("std::collections::HashMap<{}, {}>", rust_ty(key), rust_ty(value))
        }
        Ty::Tuple { elems } => {
            let parts: Vec<String> = elems.iter().map(rust_ty).collect();
            format!("({})", parts.join(", "))
        }
        Ty::Record { .. } => "serde_json::Value".to_string(),
        Ty::Union { variants } => option_shape(variants).unwrap_or_else(|| {
            // Non-nullable unions: fall back to a boxed trait object for now.
            // Real answer: emit an enum. Landing when a fixture demands it.
            "Box<dyn std::any::Any>".to_string()
        }),
        Ty::Class { id, .. } => id.0.to_string(),
        Ty::Fn { .. } => "Box<dyn Fn()>".to_string(),
        Ty::Var { .. } => "()".to_string(),
    }
}

fn option_shape(variants: &[Ty]) -> Option<String> {
    if variants.len() != 2 {
        return None;
    }
    match (&variants[0], &variants[1]) {
        (Ty::Nil, other) | (other, Ty::Nil) => Some(format!("Option<{}>", rust_ty(other))),
        _ => None,
    }
}
