//! Rust target — `rust2` parallel emit (Phase 1+ of the rust migration).
//!
//! Strangler-fig orchestrator running alongside the legacy
//! `src/emit/rust.rs` while the migration to Group 1 (lowered IR +
//! transpiled `runtime/ruby/`) lands phase-by-phase. The legacy
//! emitter keeps shipping real-blog; this one grows in parallel until
//! it passes the same gates, then takes over in one switchover commit
//! (Phase 7 of the migration plan — see `docs/rust-migration-plan.md`).
//!
//! Selected at runtime via `ROUNDHOUSE_RUST_V2=1` env var checked in
//! `src/emit/rust.rs::emit`. Without the env var, the legacy emitter
//! runs unchanged.
//!
//! Phase 1 scope (this file): emit a minimal compilable Cargo.toml +
//! `src/lib.rs` + `src/main.rs` + `src/db.rs` stub. Empty App must
//! produce a "hello world" crate that builds cleanly. No framework
//! runtime transpile, no app code emit yet — those land in Phases
//! 2-6.

use std::path::PathBuf;

use super::EmittedFile;
use crate::App;

mod expr;
pub(crate) mod library;
mod method;
mod shared;
mod ty;

/// Minimal Cargo.toml for the migration-target crate. Mirrors what
/// the migration plan's "Cargo.toml shape" section described: rust
/// 2024 edition, axum + tokio + rusqlite for primitive runtime,
/// serde + chrono + regex + base64 for the transpiled framework
/// runtime to reach.
///
/// Phase 1: ship the full template even though most deps are
/// unused — keeps subsequent phases additive on the runtime side
/// (no Cargo.toml churn between phases).
const CARGO_TOML_TEMPLATE: &str = r#"[package]
name = "app"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
name = "app"
path = "src/main.rs"

[dependencies]
axum = { version = "0.8", features = ["ws"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "sync", "time"] }
futures-util = "0.3"
rusqlite = { version = "0.33", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"
regex = "1"
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
axum-test = "18"
"#;

/// Phase 1 stub `src/main.rs`. Compiles to a no-op binary; later
/// phases replace with the real `#[tokio::main]` server entry.
const MAIN_RS_STUB: &str = "// Generated by Roundhouse (rust2 stub).\n\
fn main() {}\n";

// Phase 3 hand-written primitive runtime — `runtime/rust/*.rs` files
// the transpile pipeline can't produce yet (HWIA-shape shim methods,
// trait-dispatched adapter slot, error-token mapping). Compiled into
// the binary via include_str! and emitted alongside the transpiled
// framework runtime files.
const RT_PARAM_VALUE_SOURCE: &str = include_str!("../../runtime/rust/param_value.rs");
const RT_FLASH_SOURCE: &str = include_str!("../../runtime/rust/flash.rs");
const RT_SESSION_SOURCE: &str = include_str!("../../runtime/rust/session.rs");
const RT_ERRORS_EXT_SOURCE: &str = include_str!("../../runtime/rust/errors_ext.rs");
const RT_ACTIVE_RECORD_ADAPTER_SOURCE: &str =
    include_str!("../../runtime/rust/active_record_adapter.rs");
const RT_ADAPTER_INTERFACE_SOURCE: &str =
    include_str!("../../runtime/rust/adapter_interface.rs");
const RT_FRAMEWORK_TEST_ADAPTER_SOURCE: &str =
    include_str!("../../runtime/rust/framework_test_adapter.rs");
const RT_HASH_EXT_SOURCE: &str = include_str!("../../runtime/rust/hash_ext.rs");
const RT_DB_SOURCE: &str = include_str!("../../runtime/rust/db.rs");
const RT_BROADCASTS_SOURCE: &str = include_str!("../../runtime/rust/broadcasts.rs");

/// `use crate::*;` imports prepended to every emitted app-model
/// file. The lowerer (`src/lower/model_to_library/adapter_emit.rs`)
/// emits bare references to `Db.prepare(...)`, `Self.column_int(...)`,
/// etc.; without these imports those references E0433 even though
/// the modules are declared in `src/lib.rs`. `#[allow(unused_imports)]`
/// suppresses the warning when a given model doesn't reach every
/// item (most models don't broadcast, e.g.).
/// Prelude for emitted view files. View bodies call into ViewHelpers
/// (link_to, pluralize, dom_id, ...), RouteHelpers (article_path,
/// ...), Inflector (humanize, ...), and any model class reached by
/// `render @article` partials. Over-imports are harmless under
/// `#[allow(unused_imports)]`; under-imports surface as E0433 on
/// bare references the lowerer leaves unqualified.
const VIEW_IMPORTS: &str = "\
#[allow(unused_imports)]
use crate::view_helpers::{self, ViewHelpers, FormBuilder};
#[allow(unused_imports)]
use crate::route_helpers::{self, RouteHelpers};
#[allow(unused_imports)]
use crate::inflector::{self, Inflector};
#[allow(unused_imports)]
use crate::importmap::{self, Importmap};
#[allow(unused_imports)]
use crate::json_builder::{self, JsonBuilder};
#[allow(unused_imports)]
use crate::models::*;
#[allow(unused_imports)]
use crate::views::*;
";

/// Prelude for emitted controller files. Controllers call into the
/// view layer (`Articles::index(...)`), models, ActionDispatch
/// (Flash/Session), and the broadcasts shim. Same `#[allow(unused_
/// imports)]` discipline as MODEL_IMPORTS / VIEW_IMPORTS.
const CONTROLLER_IMPORTS: &str = "\
#[allow(unused_imports)]
use crate::action_controller_base::{self, Base};
#[allow(unused_imports)]
use crate::flash::Flash;
#[allow(unused_imports)]
use crate::session::Session;
#[allow(unused_imports)]
use crate::param_value::ParamValue;
#[allow(unused_imports)]
use crate::db::Db;
#[allow(unused_imports)]
use crate::route_helpers::{self, RouteHelpers};
#[allow(unused_imports)]
use crate::view_helpers::{self, ViewHelpers};
#[allow(unused_imports)]
use crate::broadcasts::Broadcasts;
#[allow(unused_imports)]
use crate::models::*;
#[allow(unused_imports)]
use crate::views::*;
#[allow(unused_imports)]
use crate::errors_ext::{raise, NotImplementedError, RecordNotFound, RecordInvalid};
";

const MODEL_IMPORTS: &str = "\
#[allow(unused_imports)]
use crate::param_value::ParamValue;
#[allow(unused_imports)]
use crate::db::Db;
#[allow(unused_imports)]
use crate::broadcasts::Broadcasts;
// Sibling-model glob so cross-file refs (Article ↔ Comment, the
// `<Model>Row` typed-row pair) resolve through the `pub use` chain
// that `emit_models_mod_rs` lays into `src/models/mod.rs`. Rust
// doesn't auto-import siblings — the lowerer leaves bare `Article`
// / `Comment` / `ArticleRow` / `CommentRow` references at every
// `Comment.belongs_to :article`, `has_many :comments`, and
// `instantiate(row)` call site; without this line each of those
// E0433s independently.
#[allow(unused_imports)]
use crate::models::*;
// View modules (Phase 5b stubs). The model lowerer's broadcasts_to
// expansion emits `Articles::article(self)` / `Comments::comment
// (self)` partial renders inside `after_*_commit` callback bodies;
// the actual view emit isn't yet wired through rust2, so each
// LibraryClass produced by `lower_views_to_library_classes` lands
// here as a fully-generic `String::new()` stub. Replace with real
// view emit when Phase 5b lands.
#[allow(unused_imports)]
use crate::views::*;
";

/// Emit a `rust2`-shaped project for `app`. Phase 2.1+: minimal
/// scaffold + transpiled framework runtime files. Phase 5 (in
/// progress): adds per-file application code emit through the
/// `lower_*_to_library_classes` lowerers + the shared
/// `library::emit_library_class` consumer.
pub fn emit(app: &App) -> Vec<EmittedFile> {
    let mut files = vec![
        EmittedFile {
            path: PathBuf::from("Cargo.toml"),
            content: CARGO_TOML_TEMPLATE.to_string(),
        },
        EmittedFile {
            path: PathBuf::from("src/main.rs"),
            content: MAIN_RS_STUB.to_string(),
        },
    ];

    // Phase 3 hand-written primitive runtime. Emit first so that the
    // transpiled framework runtime files (which carry `use crate::*`
    // imports referring to these modules) resolve at compile time.
    for (path, content) in [
        ("src/param_value.rs", RT_PARAM_VALUE_SOURCE),
        ("src/flash.rs", RT_FLASH_SOURCE),
        ("src/session.rs", RT_SESSION_SOURCE),
        ("src/errors_ext.rs", RT_ERRORS_EXT_SOURCE),
        ("src/active_record_adapter.rs", RT_ACTIVE_RECORD_ADAPTER_SOURCE),
        ("src/adapter_interface.rs", RT_ADAPTER_INTERFACE_SOURCE),
        ("src/framework_test_adapter.rs", RT_FRAMEWORK_TEST_ADAPTER_SOURCE),
        ("src/hash_ext.rs", RT_HASH_EXT_SOURCE),
        ("src/db.rs", RT_DB_SOURCE),
        ("src/broadcasts.rs", RT_BROADCASTS_SOURCE),
    ] {
        files.push(EmittedFile {
            path: PathBuf::from(path),
            content: content.to_string(),
        });
    }

    // Transpiled framework runtime — `runtime/ruby/*.rb` files
    // converted to Rust at app emit time. Tree-shake comes in a
    // later pass; today's transform runs the str_color pass to
    // annotate `Expr.str_coercion` per Ty::Str expression. Phase 2
    // wires `emit/rust2/expr.rs` to consume those annotations and
    // retire the IVAR_TYPES/PARAM_TYPES peepholes.
    //
    // Per-unit registry (no cross-unit knowledge): most string-typed
    // calls in a runtime file resolve to other methods in the same
    // file. Cross-unit miscompiles, if they surface, get added to
    // `register_hand_written_runtime` against the concrete site.
    let runtime_units = crate::runtime_loader::rust_units(|_path, mut classes| {
        let registry = crate::analyze::str_color::build_registry(&classes, &[]);
        crate::analyze::str_color::color_classes(&mut classes, &registry);
        // Annotate every instance method's `mutates_self` flag. Used by
        // `emit/rust2/library.rs` to pick `&self` vs `&mut self` at the
        // method-emit boundary. Lifted out of emit per the
        // self-describing-IR pattern — Crystal/Go/Kotlin/Swift can
        // consume the same flag without recomputing.
        crate::analyze::mutates_self::propagate(&mut classes);
        classes
    })
    .expect("rust runtime transpile failed (Ruby source error)");
    for unit in runtime_units {
        files.push(EmittedFile {
            path: unit.out_path,
            content: unit.content,
        });
    }

    // Phase 5: app models → `src/models/<stem>.rs`. The model lowerer
    // produces LibraryClass instances ready for the same generic
    // emit path used by the framework runtime. Each gets its own
    // file under `src/models/`; the aggregator `src/models/mod.rs`
    // (emitted by `emit_models_mod_rs`) lists them, and
    // `emit_lib_rs` declares `pub mod models;` when the directory
    // exists.

    // Phase 5 — lower all app code (models, route_helpers, views) up
    // front. Build a cross-LC class-method registry so model emit's
    // `Articles::article(self)` calls into a view module find the
    // callee's full param-Ty list and pad missing trailing optionals
    // with `synth_default_for_ty` defaults. The per-file emits below
    // run inside `with_global_class_methods` so the Const-recv
    // dispatch in `emit_send` consults the registry as its third
    // fallback.
    // Use `lower_models_with_registry` (not the simpler
    // `lower_models_to_library_classes`) so the per-class ClassInfo
    // is available downstream. View lowering needs it as extras so
    // the view body-typer can resolve `article.comments()` to
    // `Vec<Comment>` (and thus dispatch `.size()` / `.each` through
    // `try_recv_typed_method`'s Ty::Array arm). Without the model
    // registry feeding the view lowerer, those method chains land
    // with `recv.ty == None` and the Vec bridges don't fire.
    let (mut model_lcs, model_registry): (
        Vec<crate::dialect::LibraryClass>,
        std::collections::HashMap<crate::ident::ClassId, crate::analyze::ClassInfo>,
    ) = if !app.models.is_empty() {
        let (mut lcs, registry) = crate::lower::lower_models_with_registry(
            &app.models,
            &app.schema,
            vec![],
        );
        let str_color_registry = crate::analyze::str_color::build_registry(&lcs, &[]);
        crate::analyze::str_color::color_classes(&mut lcs, &str_color_registry);
        crate::analyze::mutates_self::propagate(&mut lcs);
        (lcs, registry)
    } else {
        (Vec::new(), std::collections::HashMap::new())
    };

    let route_helper_funcs = crate::lower::lower_routes_to_library_functions(app);
    let route_helpers_lc: Option<crate::dialect::LibraryClass> = if !route_helper_funcs.is_empty() {
        let mut lcs = vec![module_funcs_to_library_class("RouteHelpers", &route_helper_funcs)];
        let registry = crate::analyze::str_color::build_registry(&lcs, &[]);
        crate::analyze::str_color::color_classes(&mut lcs, &registry);
        crate::analyze::mutates_self::propagate(&mut lcs);
        Some(lcs.into_iter().next().unwrap())
    } else {
        None
    };

    let importmap_funcs = crate::lower::lower_importmap_to_library_functions(app);
    let importmap_lc: Option<crate::dialect::LibraryClass> = if !importmap_funcs.is_empty() {
        let mut lcs = vec![module_funcs_to_library_class("Importmap", &importmap_funcs)];
        let registry = crate::analyze::str_color::build_registry(&lcs, &[]);
        crate::analyze::str_color::color_classes(&mut lcs, &registry);
        crate::analyze::mutates_self::propagate(&mut lcs);
        Some(lcs.into_iter().next().unwrap())
    } else {
        None
    };

    let mut view_lcs: Vec<crate::dialect::LibraryClass> = if !app.views.is_empty() {
        // Seed the view lowerer's body-typer with the model registry
        // + route_helpers function signatures so cross-class method
        // dispatch (`article.comments()` → Vec<Comment>) types
        // through. Without this, the view body-typer flatters every
        // model-method recv as Untyped and downstream recv-typed
        // method bridges (Vec.size/each, Hash.size, etc.) miss.
        let mut view_extras: Vec<(crate::ident::ClassId, crate::analyze::ClassInfo)> =
            model_registry.clone().into_iter().collect();
        view_extras.extend(crate::lower::library_extras::extras_from_funcs(&route_helper_funcs));
        // HTML views + JSON jbuilder views fold into the same per-
        // directory module (`Views::Articles`). The html lowerer
        // produces `index` / `show` / `_article`; the jbuilder lowerer
        // produces `index_json` / `show_json` / `_article_json` under
        // the same struct name. Controller render branches dispatch
        // by `request_format`-driven name selection — both variants
        // need to land on the same `impl Articles { ... }`.
        let mut raw_lcs = crate::lower::lower_views_to_library_classes(
            &app.views,
            app,
            view_extras.clone(),
        );
        raw_lcs.extend(crate::lower::lower_jbuilder_to_library_classes(
            &app.views,
            app,
            view_extras,
        ));
        let mut merged: std::collections::BTreeMap<String, crate::dialect::LibraryClass> =
            std::collections::BTreeMap::new();
        for lc in raw_lcs {
            let raw = lc.name.0.as_str();
            let struct_name = raw.rsplit("::").next().unwrap_or(raw).to_string();
            merged
                .entry(struct_name)
                .and_modify(|acc: &mut crate::dialect::LibraryClass| {
                    let seen: std::collections::BTreeSet<String> =
                        acc.methods.iter().map(|m| m.name.as_str().to_string()).collect();
                    for m in lc.methods.clone() {
                        if !seen.contains(m.name.as_str()) {
                            acc.methods.push(m);
                        }
                    }
                })
                .or_insert(lc);
        }
        let mut lcs: Vec<crate::dialect::LibraryClass> = merged.into_values().collect();
        let registry = crate::analyze::str_color::build_registry(&lcs, &[]);
        crate::analyze::str_color::color_classes(&mut lcs, &registry);
        crate::analyze::mutates_self::propagate(&mut lcs);
        lcs
    } else {
        Vec::new()
    };

    // Fixtures — synthesize `<Resource>Fixtures` LibraryClasses from
    // `test/fixtures/*.yml`. Each fixture file becomes a
    // `<Resource>Fixtures` module with class methods returning the
    // hydrated records by name. Used by tests; production builds w/o
    // tests skip emission via the `app.test_modules` gate parallel
    // to Crystal's pattern.
    let mut fixture_lcs: Vec<crate::dialect::LibraryClass> =
        if !app.fixtures.is_empty() {
            let mut lcs = crate::lower::lower_fixtures_to_library_classes(app);
            let registry = crate::analyze::str_color::build_registry(&lcs, &[]);
            crate::analyze::str_color::color_classes(&mut lcs, &registry);
            crate::analyze::mutates_self::propagate(&mut lcs);
            lcs
        } else {
            Vec::new()
        };

    // Controllers — extras include model_registry + view_lcs +
    // route_helper extras (mirror Crystal's `controller_extras` setup).
    // The lowerer also synthesizes `<Resource>Params` classes (origin
    // is Some) which belong under `src/models/` not `src/controllers/`,
    // following the Crystal pattern.
    let mut controller_lcs: Vec<crate::dialect::LibraryClass> = if !app.controllers.is_empty() {
        let mut controller_extras: Vec<(crate::ident::ClassId, crate::analyze::ClassInfo)> =
            model_registry.clone().into_iter().collect();
        controller_extras.extend(crate::lower::library_extras::extras_from_lcs(&view_lcs));
        controller_extras.extend(crate::lower::library_extras::extras_from_funcs(&route_helper_funcs));
        let mut lcs = crate::lower::lower_controllers_with_arel_and_views(
            &app.controllers,
            controller_extras,
            Some(&app.schema),
            &app.views,
        );
        let registry = crate::analyze::str_color::build_registry(&lcs, &[]);
        crate::analyze::str_color::color_classes(&mut lcs, &registry);
        crate::analyze::mutates_self::propagate(&mut lcs);
        lcs
    } else {
        Vec::new()
    };

    let global_methods = collect_global_class_methods(
        &model_lcs,
        route_helpers_lc.as_ref(),
        importmap_lc.as_ref(),
        &view_lcs,
        &controller_lcs,
        &fixture_lcs,
    );
    // Avoid unused-mut warnings on the lowered LC accumulators when
    // any one of them is empty for the current fixture.
    let _ = (&mut model_lcs, &mut view_lcs, &mut controller_lcs, &mut fixture_lcs);

    crate::emit::rust2::expr::with_global_class_methods(global_methods, || {
    if !model_lcs.is_empty() {
        for lc in &model_lcs {
            let stem = crate::naming::snake_case(lc.name.0.as_str());
            let body = match library::emit_library_class(lc) {
                Ok(s) => s,
                Err(e) => {
                    panic!("rust2 model emit failed for {}: {e}", lc.name.0.as_str());
                }
            };
            // App-model emit calls into the rust2 primitive runtime
            // (`Db::prepare`, etc.) and the transpiled framework
            // runtime (`Base`, `Broadcasts`, …). Prepend `use crate::*`
            // imports for the known surface. Over-imports are
            // harmless under Rust's `#[allow(unused_imports)]`
            // permissive default; under-imports trip E0433. Add new
            // entries here when a follow-up phase surfaces another
            // bare reference.
            //
            // AR::Base inheritance shim — Rust lacks class inheritance,
            // so methods carried by `runtime/ruby/active_record/base.rb`
            // (`mark_persisted!`, `errors`, `save`, `update`) aren't
            // automatically available on the lowered per-model struct.
            // Append a minimal impl block for the three methods that
            // call sites synthesized by the model lowerer reach:
            // `mark_persisted_bang` (no-op), `errors` (returns empty
            // `Vec<String>`), `save` (drives validate + returns true).
            // Behavioral simplifications — lifecycle callbacks not
            // fired, errors not accumulated across validate→save — are
            // acceptable for Phase 5 compile-cleanup; later sessions
            // route through the lowerer's specialization-always-on
            // path (project_specialization_strategy.md) for the per-
            // model body restoration.
            //
            // Gate on `_adapter_insert` to skip ApplicationRecord
            // (abstract, no table) and synthesized Row classes (no
            // adapter methods).
            let needs_ar_shim = lc
                .methods
                .iter()
                .any(|m| m.name.as_str() == "_adapter_insert");
            let ar_shim = if needs_ar_shim {
                // `destroy` and `exists` are paired in:
                //   - Article#dependent_destroy: `c.destroy()` over the
                //     has_many comments collection (Comment side)
                //   - Comment#validate's belongs_to inline check:
                //     `Article::exists(self.article_id)` (Article side)
                // Both are AR::Base methods in Crystal/Spinel/Ruby
                // (inherited); Rust needs them on the concrete struct.
                // Minimal stubs: `destroy` flips persisted+destroyed
                // flags (no-op without state — current shim is
                // intentionally stateless); `exists` routes through
                // the lowerer-emitted `_adapter_exists_by_id`.
                format!(
                    "\nimpl {name} {{\n\
                        pub fn mark_persisted_bang(&mut self) {{ }}\n\
                        pub fn errors(&self) -> Vec<String> {{ Vec::new() }}\n\
                        pub fn save(&mut self) -> bool {{ self.validate(); true }}\n\
                        pub fn destroy(&mut self) {{ self._adapter_delete(); }}\n\
                        pub fn exists(id: i64) -> bool {{ Self::_adapter_exists_by_id(id) }}\n\
                        pub fn persisted(&self) -> bool {{ self.id != 0 }}\n\
                        pub fn find(id: i64) -> Self {{ Self::_adapter_find_by_id(id).expect(\"record not found\") }}\n\
                    }}\n",
                    name = lc.name.0.as_str()
                )
            } else {
                String::new()
            };
            let content = format!("{MODEL_IMPORTS}{body}{ar_shim}");
            files.push(EmittedFile {
                path: PathBuf::from(format!("src/models/{stem}.rs")),
                content,
            });
        }
        files.push(emit_models_mod_rs(&model_lcs));
    }

    if let Some(lc) = &route_helpers_lc {
        let body = match library::emit_library_class(lc) {
            Ok(s) => s,
            Err(e) => panic!("rust2 route_helpers emit failed: {e}"),
        };
        files.push(EmittedFile {
            path: PathBuf::from("src/route_helpers.rs"),
            content: body,
        });
    }

    if let Some(lc) = &importmap_lc {
        let body = match library::emit_library_class(lc) {
            Ok(s) => s,
            Err(e) => panic!("rust2 importmap emit failed: {e}"),
        };
        files.push(EmittedFile {
            path: PathBuf::from("src/importmap.rs"),
            content: body,
        });
    }

    if !view_lcs.is_empty() {
        let mut view_entries: Vec<(String, String)> = Vec::new();
        for lc in &view_lcs {
            let raw = lc.name.0.as_str();
            let struct_name = raw.rsplit("::").next().unwrap_or(raw).to_string();
            let stem = crate::naming::snake_case(&struct_name);
            let body = match library::emit_library_class(lc) {
                Ok(s) => s,
                Err(e) => {
                    panic!("rust2 view emit failed for {}: {e}", lc.name.0.as_str());
                }
            };
            let content = format!("{VIEW_IMPORTS}{body}");
            files.push(EmittedFile {
                path: PathBuf::from(format!("src/views/{stem}.rs")),
                content,
            });
            view_entries.push((stem, struct_name));
        }
        files.push(emit_views_mod_rs(&view_entries));
    }

    // Controllers — controller LCs with `origin: None` go to
    // `src/controllers/<stem>.rs`; synthesized `<Resource>Params`
    // classes (origin: Some) go to `src/models/<stem>.rs` since they
    // belong to the model layer conceptually. Mirrors Crystal's
    // routing.
    if !controller_lcs.is_empty() {
        let mut controller_entries: Vec<(String, String)> = Vec::new();
        let mut model_param_entries: Vec<(String, String)> = Vec::new();
        for lc in &controller_lcs {
            let raw = lc.name.0.as_str();
            let struct_name = raw.rsplit("::").next().unwrap_or(raw).to_string();
            let stem = crate::naming::snake_case(&struct_name);
            let body = match library::emit_library_class(lc) {
                Ok(s) => s,
                Err(e) => {
                    panic!("rust2 controller emit failed for {}: {e}", lc.name.0.as_str());
                }
            };
            if lc.origin.is_some() {
                // Synthesized `<Resource>Params` — emit under
                // `src/models/`. Re-use MODEL_IMPORTS so adapter/db/
                // sibling-model references resolve.
                let content = format!("{MODEL_IMPORTS}{body}");
                files.push(EmittedFile {
                    path: PathBuf::from(format!("src/models/{stem}.rs")),
                    content,
                });
                model_param_entries.push((stem, struct_name));
            } else {
                // AC::Base inheritance shim — appended `impl <Name>`
                // block providing the request-lifecycle helpers that
                // controller bodies invoke as `Send`s on self. The
                // field-shape ivars (`flash`, `session`, `params`,
                // ...) come from `walk_collect_ivars`'s read-only
                // ivar surface and land on the struct naturally. The
                // methods below stub the AC::Base contract for now —
                // `render` echoes its arg, `request_format` returns
                // "html", `redirect_to` / `head` are no-ops. Real
                // plumbing (HTTP response state, content negotiation)
                // is later runtime work; the goal here is compile-
                // clean so the aggregate error count moves.
                let ac_shim = format!(
                    "\nimpl {name} {{\n\
                    \x20   pub fn render(&self, content: String) -> String {{ content }}\n\
                    \x20   pub fn render_with(&self, content: String, _opts: std::collections::HashMap<String, crate::param_value::ParamValue>) -> String {{ content }}\n\
                    \x20   pub fn request_format(&self) -> String {{ \"html\".to_string() }}\n\
                    \x20   pub fn redirect_to(&self, _url: String, _opts: std::collections::HashMap<String, crate::param_value::ParamValue>) {{ }}\n\
                    \x20   pub fn head(&self, _status: &str) {{ }}\n\
                    }}\n",
                    name = lc.name.0.as_str()
                );
                let content = format!("{CONTROLLER_IMPORTS}{body}{ac_shim}");
                files.push(EmittedFile {
                    path: PathBuf::from(format!("src/controllers/{stem}.rs")),
                    content,
                });
                controller_entries.push((stem, struct_name));
            }
        }
        if !controller_entries.is_empty() {
            files.push(emit_controllers_mod_rs(&controller_entries));
        }
        // Augment src/models/mod.rs entries with the synthesized
        // params classes. emit_models_mod_rs already emitted earlier
        // — re-emit if there are params classes. (Idempotent: we
        // simply replace the previous models/mod.rs in `files` by
        // appending; the EmittedFile path is unique-keyed by emitters
        // downstream — last write wins for files w/ same path.)
        if !model_param_entries.is_empty() {
            let mut all_models = model_lcs.clone();
            // Wrap synthesized entries as fake LibraryClasses with
            // just the name so the existing aggregator helper works.
            // Already emitted as files; just need them indexed in
            // mod.rs.
            for (stem, struct_name) in &model_param_entries {
                use crate::dialect::LibraryClass;
                use crate::ident::ClassId;
                all_models.push(LibraryClass {
                    name: ClassId(crate::ident::Symbol::from(struct_name.as_str())),
                    is_module: false,
                    parent: None,
                    includes: Vec::new(),
                    methods: Vec::new(),
                    origin: None,
                });
                let _ = stem;
            }
            files.push(emit_models_mod_rs(&all_models));
        }
    }

    // Fixtures — each `<Resource>Fixtures` LibraryClass becomes one
    // file under `src/fixtures/`. The aggregator `src/fixtures/mod.rs`
    // declares them so the test harness can reach `ArticleFixtures::
    // load(...)` style methods.
    if !fixture_lcs.is_empty() {
        let mut fixture_entries: Vec<(String, String)> = Vec::new();
        for lc in &fixture_lcs {
            let raw = lc.name.0.as_str();
            let struct_name = raw.rsplit("::").next().unwrap_or(raw).to_string();
            let stem = crate::naming::snake_case(
                struct_name.strip_suffix("Fixtures").unwrap_or(&struct_name),
            );
            let body = match library::emit_library_class(lc) {
                Ok(s) => s,
                Err(e) => {
                    panic!("rust2 fixture emit failed for {}: {e}", lc.name.0.as_str());
                }
            };
            // Fixtures reference models; reuse MODEL_IMPORTS.
            let content = format!("{MODEL_IMPORTS}{body}");
            files.push(EmittedFile {
                path: PathBuf::from(format!("src/fixtures/{stem}.rs")),
                content,
            });
            fixture_entries.push((stem, struct_name));
        }
        files.push(emit_fixtures_mod_rs(&fixture_entries));
    }
    }); // end with_global_class_methods

    // src/lib.rs — declares the modules emitted above (hand-written +
    // transpiled). emit_lib_rs scans the emitted file list for stems
    // under `src/`, so adding a new file is enough — no list to update.
    files.push(emit_lib_rs(&files));

    files
}

/// Build `src/lib.rs` from the set of files emitted so far, declaring
/// each `src/<name>.rs` as a `pub mod` and each `src/<subdir>/`
/// containing a `mod.rs` as a `pub mod <subdir>`. Later phases will
/// need dependency-aware ordering when modules `use` each other;
/// alphabetical is fine for now.
fn emit_lib_rs(emitted: &[EmittedFile]) -> EmittedFile {
    let mut lines = vec!["// Generated by Roundhouse (rust2).".to_string(), String::new()];
    let mut mods: Vec<String> = emitted
        .iter()
        .filter_map(|f| {
            let p = f.path.to_string_lossy();
            let rest = p.strip_prefix("src/")?;
            // Subdirectory module: `src/models/mod.rs` → `pub mod models;`.
            if let Some(subdir_stem) = rest.strip_suffix("/mod.rs") {
                return Some(subdir_stem.to_string());
            }
            let stem = rest.strip_suffix(".rs")?;
            // Skip main + lib themselves.
            if stem == "main" || stem == "lib" {
                return None;
            }
            // Skip per-model files (their parent `mod.rs` declares them).
            if stem.contains('/') {
                return None;
            }
            Some(stem.to_string())
        })
        .collect();
    mods.sort();
    mods.dedup();
    for m in &mods {
        lines.push(format!("pub mod {m};"));
    }
    EmittedFile {
        path: PathBuf::from("src/lib.rs"),
        content: lines.join("\n") + "\n",
    }
}

/// `src/models/mod.rs` aggregator — declares each emitted model
/// file as `pub mod <stem>;` so `app::models::Article` etc. resolve
/// from outside the directory.
fn emit_models_mod_rs(lcs: &[crate::dialect::LibraryClass]) -> EmittedFile {
    let mut lines = vec!["// Generated by Roundhouse (rust2).".to_string(), String::new()];
    let mut entries: Vec<(String, String)> = lcs
        .iter()
        .map(|lc| {
            (
                crate::naming::snake_case(lc.name.0.as_str()),
                lc.name.0.as_str().to_string(),
            )
        })
        .collect();
    entries.sort();
    entries.dedup();
    // Two-pass emit: `pub mod <stem>;` then `pub use <stem>::<Name>;`.
    // The re-export is what `MODEL_IMPORTS`' `use crate::models::*;`
    // hits, so sibling files (article.rs) can name `Comment` without
    // a `crate::models::comment::` path. Each per-file struct picks
    // up the same glob, so cross-association code (`Comment::exists`
    // in Comment's own belongs_to validate, `Vec<Comment>` in
    // Article#comments) compiles without per-target use plumbing.
    for (stem, _) in &entries {
        lines.push(format!("pub mod {stem};"));
    }
    for (stem, name) in &entries {
        lines.push(format!("pub use {stem}::{name};"));
    }
    EmittedFile {
        path: PathBuf::from("src/models/mod.rs"),
        content: lines.join("\n") + "\n",
    }
}

/// `src/views/mod.rs` aggregator — same shape as `emit_models_mod_rs`:
/// declares each view module as `pub mod <stem>;` and re-exports the
/// struct as `pub use <stem>::<Name>;` so `use crate::views::*;` in
/// MODEL_IMPORTS pulls `Articles` / `Comments` / etc. into scope.
fn emit_views_mod_rs(entries: &[(String, String)]) -> EmittedFile {
    let mut lines = vec!["// Generated by Roundhouse (rust2).".to_string(), String::new()];
    let mut entries = entries.to_vec();
    entries.sort();
    entries.dedup();
    for (stem, _) in &entries {
        lines.push(format!("pub mod {stem};"));
    }
    for (stem, name) in &entries {
        lines.push(format!("pub use {stem}::{name};"));
    }
    EmittedFile {
        path: PathBuf::from("src/views/mod.rs"),
        content: lines.join("\n") + "\n",
    }
}

/// `src/fixtures/mod.rs` aggregator — same shape as the other
/// per-directory aggregators.
fn emit_fixtures_mod_rs(entries: &[(String, String)]) -> EmittedFile {
    let mut lines = vec!["// Generated by Roundhouse (rust2).".to_string(), String::new()];
    let mut entries = entries.to_vec();
    entries.sort();
    entries.dedup();
    for (stem, _) in &entries {
        lines.push(format!("pub mod {stem};"));
    }
    for (stem, name) in &entries {
        lines.push(format!("pub use {stem}::{name};"));
    }
    EmittedFile {
        path: PathBuf::from("src/fixtures/mod.rs"),
        content: lines.join("\n") + "\n",
    }
}

/// `src/controllers/mod.rs` aggregator — same shape as
/// `emit_models_mod_rs` / `emit_views_mod_rs`.
fn emit_controllers_mod_rs(entries: &[(String, String)]) -> EmittedFile {
    let mut lines = vec!["// Generated by Roundhouse (rust2).".to_string(), String::new()];
    let mut entries = entries.to_vec();
    entries.sort();
    entries.dedup();
    for (stem, _) in &entries {
        lines.push(format!("pub mod {stem};"));
    }
    for (stem, name) in &entries {
        lines.push(format!("pub use {stem}::{name};"));
    }
    EmittedFile {
        path: PathBuf::from("src/controllers/mod.rs"),
        content: lines.join("\n") + "\n",
    }
}

/// Build the cross-LC class-method registry consumed by emit_send's
/// Const-recv dispatch. Each LC's class methods get folded into a
/// per-class table keyed by method name; cross-class callers (a
/// model's `Articles::article(self)`, a view's `Inflector::pluralize
/// (...)`, etc.) consult this map via `global_class_method_param_tys`
/// when neither `external_class_method_param_tys` nor
/// `current_class_method_param_tys` resolves. Pulls signature data
/// from `MethodDef.signature` when present; methods without a typed
/// signature get an empty Tys vec and the Const-recv arity-pad path
/// no-ops (same behavior as no entry).
fn collect_global_class_methods(
    model_lcs: &[crate::dialect::LibraryClass],
    route_helpers_lc: Option<&crate::dialect::LibraryClass>,
    importmap_lc: Option<&crate::dialect::LibraryClass>,
    view_lcs: &[crate::dialect::LibraryClass],
    controller_lcs: &[crate::dialect::LibraryClass],
    fixture_lcs: &[crate::dialect::LibraryClass],
) -> std::collections::HashMap<String, std::collections::HashMap<String, Vec<crate::ty::Ty>>> {
    use crate::dialect::{LibraryClass, MethodReceiver};
    use crate::ty::{ParamKind, Ty};

    fn collect_one(
        lc: &LibraryClass,
        out: &mut std::collections::HashMap<String, std::collections::HashMap<String, Vec<Ty>>>,
    ) {
        let raw = lc.name.0.as_str();
        let class_name = raw.rsplit("::").next().unwrap_or(raw).to_string();
        let entry = out.entry(class_name).or_default();
        // Collect ALL methods (Class + Instance), since constructor
        // candidates (`initialize`) live in instance methods but are
        // reached at call sites as `Article::new(...)`. The instance
        // entry doubles as the class-method registry for any same-
        // name call across the recv kinds. The downstream caller
        // (emit_send Const-recv arm) picks the entry by method name;
        // it doesn't care about receiver kind.
        for m in &lc.methods {
            let tys: Vec<Ty> = match m.signature.as_ref() {
                Some(Ty::Fn { params, .. }) => params
                    .iter()
                    .filter(|p| !matches!(p.kind, ParamKind::Block | ParamKind::KeywordRest))
                    .map(|p| p.ty.clone())
                    .collect(),
                _ => m.params.iter().map(|_| Ty::Untyped).collect(),
            };
            // Alias `initialize` → `new` so `Article::new(args)`
            // dispatches against the constructor's param list (Ruby
            // syntactic difference; Rust always names the constructor
            // `new`). Mirrors the same alias in `collect_class_method
            // _param_tys` (library.rs) used for self-class lookups.
            if m.name.as_str() == "initialize" {
                entry.insert("new".to_string(), tys.clone());
            }
            entry.insert(m.name.as_str().to_string(), tys);
        }
    }

    let mut out: std::collections::HashMap<
        String,
        std::collections::HashMap<String, Vec<Ty>>,
    > = std::collections::HashMap::new();
    for lc in model_lcs {
        collect_one(lc, &mut out);
    }
    if let Some(lc) = route_helpers_lc {
        collect_one(lc, &mut out);
    }
    if let Some(lc) = importmap_lc {
        collect_one(lc, &mut out);
    }
    for lc in view_lcs {
        collect_one(lc, &mut out);
    }
    for lc in controller_lcs {
        collect_one(lc, &mut out);
    }
    for lc in fixture_lcs {
        collect_one(lc, &mut out);
    }
    out
}

/// Build a synthetic `LibraryClass` from a flat list of
/// `LibraryFunction`s sharing a module path. Each function becomes a
/// class-receiver method on the synthetic class; the library emit
/// path handles it via `emit_module_singleton`. Used for
/// `RouteHelpers` / `Importmap` and analogous module-only outputs
/// from the per-module lowerers.
fn module_funcs_to_library_class(
    name: &str,
    funcs: &[crate::dialect::LibraryFunction],
) -> crate::dialect::LibraryClass {
    use crate::dialect::{AccessorKind, LibraryClass, MethodDef, MethodReceiver};
    use crate::ident::ClassId;
    let methods: Vec<MethodDef> = funcs
        .iter()
        .map(|f| MethodDef {
            name: f.name.clone(),
            receiver: MethodReceiver::Class,
            params: f.params.clone(),
            body: f.body.clone(),
            signature: f.signature.clone(),
            effects: f.effects.clone(),
            enclosing_class: Some(crate::ident::Symbol::from(name)),
            kind: AccessorKind::Method,
            is_async: f.is_async,
            mutates_self: false,
        })
        .collect();
    LibraryClass {
        name: ClassId(crate::ident::Symbol::from(name)),
        is_module: true,
        parent: None,
        includes: Vec::new(),
        methods,
        origin: None,
    }
}
