//! Rust target — `rust2` parallel emit (Phase 1+ of the rust migration).
//!
//! Strangler-fig orchestrator running alongside the legacy
//! `src/emit/rust.rs` while the migration to Group 1 (lowered IR +
//! transpiled `runtime/ruby/`) lands phase-by-phase. The legacy
//! emitter keeps shipping real-blog; this one grows in parallel until
//! it passes the same gates, then takes over in one switchover commit
//! (Phase 7 of the migration plan — see `docs/rust-migration-plan.md`).
//!
//! Selected at runtime via `ROUNDHOUSE_RUST_V2=1` env var checked in
//! `src/emit/rust.rs::emit`. Without the env var, the legacy emitter
//! runs unchanged.
//!
//! Phase 1 scope (this file): emit a minimal compilable Cargo.toml +
//! `src/lib.rs` + `src/main.rs` + `src/db.rs` stub. Empty App must
//! produce a "hello world" crate that builds cleanly. No framework
//! runtime transpile, no app code emit yet — those land in Phases
//! 2-6.

use std::path::PathBuf;

use super::EmittedFile;
use crate::App;

mod expr;
pub(crate) mod library;
mod method;
mod shared;
mod ty;

/// Minimal Cargo.toml for the migration-target crate. Mirrors what
/// the migration plan's "Cargo.toml shape" section described: rust
/// 2024 edition, axum + tokio + rusqlite for primitive runtime,
/// serde + chrono + regex + base64 for the transpiled framework
/// runtime to reach.
///
/// Phase 1: ship the full template even though most deps are
/// unused — keeps subsequent phases additive on the runtime side
/// (no Cargo.toml churn between phases).
const CARGO_TOML_TEMPLATE: &str = r#"[package]
name = "app"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
name = "app"
path = "src/main.rs"

[dependencies]
axum = { version = "0.8", features = ["ws"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "sync", "time"] }
futures-util = "0.3"
rusqlite = { version = "0.33", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"
regex = "1"
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
axum-test = "18"
"#;

/// Phase 1 stub `src/main.rs`. Compiles to a no-op binary; later
/// phases replace with the real `#[tokio::main]` server entry.
const MAIN_RS_STUB: &str = "// Generated by Roundhouse (rust2 stub).\n\
fn main() {}\n";

// Phase 3 hand-written primitive runtime — `runtime/rust/*.rs` files
// the transpile pipeline can't produce yet (HWIA-shape shim methods,
// trait-dispatched adapter slot, error-token mapping). Compiled into
// the binary via include_str! and emitted alongside the transpiled
// framework runtime files.
const RT_PARAM_VALUE_SOURCE: &str = include_str!("../../runtime/rust/param_value.rs");
const RT_FLASH_SOURCE: &str = include_str!("../../runtime/rust/flash.rs");
const RT_SESSION_SOURCE: &str = include_str!("../../runtime/rust/session.rs");
const RT_ERRORS_EXT_SOURCE: &str = include_str!("../../runtime/rust/errors_ext.rs");
const RT_ACTIVE_RECORD_ADAPTER_SOURCE: &str =
    include_str!("../../runtime/rust/active_record_adapter.rs");
const RT_ADAPTER_INTERFACE_SOURCE: &str =
    include_str!("../../runtime/rust/adapter_interface.rs");
const RT_FRAMEWORK_TEST_ADAPTER_SOURCE: &str =
    include_str!("../../runtime/rust/framework_test_adapter.rs");
const RT_HASH_EXT_SOURCE: &str = include_str!("../../runtime/rust/hash_ext.rs");

/// Emit a `rust2`-shaped project for `app`. Phase 2.1+: minimal
/// scaffold + transpiled framework runtime files (currently just
/// `inflector.rs`). Future phases extend further: primitive runtime
/// (Phase 3), application code (Phase 5).
pub fn emit(app: &App) -> Vec<EmittedFile> {
    // App is unused in Phase 2.1 — once application emit lands it
    // becomes the source of truth for what to ship.
    let _ = app;

    let mut files = vec![
        EmittedFile {
            path: PathBuf::from("Cargo.toml"),
            content: CARGO_TOML_TEMPLATE.to_string(),
        },
        EmittedFile {
            path: PathBuf::from("src/main.rs"),
            content: MAIN_RS_STUB.to_string(),
        },
    ];

    // Phase 3 hand-written primitive runtime. Emit first so that the
    // transpiled framework runtime files (which carry `use crate::*`
    // imports referring to these modules) resolve at compile time.
    for (path, content) in [
        ("src/param_value.rs", RT_PARAM_VALUE_SOURCE),
        ("src/flash.rs", RT_FLASH_SOURCE),
        ("src/session.rs", RT_SESSION_SOURCE),
        ("src/errors_ext.rs", RT_ERRORS_EXT_SOURCE),
        ("src/active_record_adapter.rs", RT_ACTIVE_RECORD_ADAPTER_SOURCE),
        ("src/adapter_interface.rs", RT_ADAPTER_INTERFACE_SOURCE),
        ("src/framework_test_adapter.rs", RT_FRAMEWORK_TEST_ADAPTER_SOURCE),
        ("src/hash_ext.rs", RT_HASH_EXT_SOURCE),
    ] {
        files.push(EmittedFile {
            path: PathBuf::from(path),
            content: content.to_string(),
        });
    }

    // Transpiled framework runtime — `runtime/ruby/*.rb` files
    // converted to Rust at app emit time. Tree-shake comes in a
    // later pass; today's transform runs the str_color pass to
    // annotate `Expr.str_coercion` per Ty::Str expression. Phase 2
    // wires `emit/rust2/expr.rs` to consume those annotations and
    // retire the IVAR_TYPES/PARAM_TYPES peepholes.
    //
    // Per-unit registry (no cross-unit knowledge): most string-typed
    // calls in a runtime file resolve to other methods in the same
    // file. Cross-unit miscompiles, if they surface, get added to
    // `register_hand_written_runtime` against the concrete site.
    let runtime_units = crate::runtime_loader::rust_units(|_path, mut classes| {
        let registry = crate::analyze::str_color::build_registry(&classes, &[]);
        crate::analyze::str_color::color_classes(&mut classes, &registry);
        classes
    })
    .expect("rust runtime transpile failed (Ruby source error)");
    for unit in runtime_units {
        files.push(EmittedFile {
            path: unit.out_path,
            content: unit.content,
        });
    }

    // src/lib.rs — declares the modules emitted above (hand-written +
    // transpiled). emit_lib_rs scans the emitted file list for stems
    // under `src/`, so adding a new file is enough — no list to update.
    files.push(emit_lib_rs(&files));

    files
}

/// Build `src/lib.rs` from the set of files emitted so far, declaring
/// each `src/<name>.rs` as a `pub mod`. Later phases will need
/// dependency-aware ordering (Crystal's `RUNTIME_ORDER` analog) when
/// modules `use` each other; Phase 2.1 has only inflector with no
/// deps, so alphabetical is fine.
fn emit_lib_rs(emitted: &[EmittedFile]) -> EmittedFile {
    let mut lines = vec!["// Generated by Roundhouse (rust2).".to_string(), String::new()];
    let mut mods: Vec<String> = emitted
        .iter()
        .filter_map(|f| {
            let p = f.path.to_string_lossy();
            let stem = p.strip_prefix("src/")?.strip_suffix(".rs")?;
            // Skip main + lib themselves.
            if stem == "main" || stem == "lib" {
                return None;
            }
            Some(stem.to_string())
        })
        .collect();
    mods.sort();
    mods.dedup();
    for m in &mods {
        lines.push(format!("pub mod {m};"));
    }
    EmittedFile {
        path: PathBuf::from("src/lib.rs"),
        content: lines.join("\n") + "\n",
    }
}
