//! Rust target — `rust2` parallel emit (Phase 1+ of the rust migration).
//!
//! Strangler-fig orchestrator running alongside the legacy
//! `src/emit/rust.rs` while the migration to Group 1 (lowered IR +
//! transpiled `runtime/ruby/`) lands phase-by-phase. The legacy
//! emitter keeps shipping real-blog; this one grows in parallel until
//! it passes the same gates, then takes over in one switchover commit
//! (Phase 7 of the migration plan — see `docs/rust-migration-plan.md`).
//!
//! Selected at runtime via `ROUNDHOUSE_RUST_V2=1` env var checked in
//! `src/emit/rust.rs::emit`. Without the env var, the legacy emitter
//! runs unchanged.
//!
//! Phase 1 scope (this file): emit a minimal compilable Cargo.toml +
//! `src/lib.rs` + `src/main.rs` + `src/db.rs` stub. Empty App must
//! produce a "hello world" crate that builds cleanly. No framework
//! runtime transpile, no app code emit yet — those land in Phases
//! 2-6.

use std::path::PathBuf;

use super::EmittedFile;
use crate::App;

mod expr;
mod library;
mod method;
mod shared;
mod ty;

/// Minimal Cargo.toml for the migration-target crate. Mirrors what
/// the migration plan's "Cargo.toml shape" section described: rust
/// 2024 edition, axum + tokio + rusqlite for primitive runtime,
/// serde + chrono + regex + base64 for the transpiled framework
/// runtime to reach.
///
/// Phase 1: ship the full template even though most deps are
/// unused — keeps subsequent phases additive on the runtime side
/// (no Cargo.toml churn between phases).
const CARGO_TOML_TEMPLATE: &str = r#"[package]
name = "app"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
name = "app"
path = "src/main.rs"

[dependencies]
axum = { version = "0.8", features = ["ws"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "sync", "time"] }
futures-util = "0.3"
rusqlite = { version = "0.33", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"
regex = "1"
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
axum-test = "18"
"#;

/// Phase 1 stub `src/main.rs`. Compiles to a no-op binary; later
/// phases replace with the real `#[tokio::main]` server entry.
const MAIN_RS_STUB: &str = "// Generated by Roundhouse (rust2 stub).\n\
fn main() {}\n";

/// Phase 1 stub `src/lib.rs`. Empty crate root — later phases add
/// `pub mod` declarations as runtime + app code lands.
const LIB_RS_STUB: &str = "// Generated by Roundhouse (rust2 stub).\n";

/// Emit a `rust2`-shaped project for `app`. Phase 1: minimal
/// scaffold only. Future phases extend by ingesting transpiled
/// runtime (Phase 2), shipping primitive runtime (Phase 3),
/// emitting application code (Phase 5).
pub fn emit(app: &App) -> Vec<EmittedFile> {
    // App is unused in Phase 1 — once runtime/app emit lands it
    // becomes the source of truth for what to ship.
    let _ = app;

    vec![
        EmittedFile {
            path: PathBuf::from("Cargo.toml"),
            content: CARGO_TOML_TEMPLATE.to_string(),
        },
        EmittedFile {
            path: PathBuf::from("src/main.rs"),
            content: MAIN_RS_STUB.to_string(),
        },
        EmittedFile {
            path: PathBuf::from("src/lib.rs"),
            content: LIB_RS_STUB.to_string(),
        },
    ]
}
