//! TypeScript emitter.
//!
//! Second typed target after Rust/Go and the first of the Phase 2
//! scaffolds. Shape goals for this scaffold:
//!
//! - One `class` per `Model` with typed instance fields from the schema.
//! - One `class` per `Controller` with one async method per action.
//! - A single `routes` dispatch table listing every route.
//!
//! TypeScript accommodates a lot of Ruby shapes cleanly — classes,
//! nullable via `T | null`, typed arrays, `Record<K,V>` for hashes.
//! That's why it's the first Phase-2 scaffold: if a feature doesn't
//! fit here cleanly, the typed IR probably needs to change, and
//! we find out before committing to deeper target work.
//!
//! Non-goals (deferred to Phase 3+):
//! - Juntos runtime integration (`import { ActiveRecord } from …`).
//! - View / template emission.
//! - `tsc --strict` cleanliness — the output is structurally valid
//!   TypeScript but the runtime symbols won't resolve.

use std::fmt::Write;
use std::path::PathBuf;

use super::EmittedFile;
use crate::App;
use crate::dialect::{Action, Controller, MethodDef, Model, RouteSpec};
use crate::expr::{Expr, ExprNode, LValue, Literal};
use crate::ty::Ty;

pub fn emit(app: &App) -> Vec<EmittedFile> {
    let mut files = Vec::new();
    if !app.models.is_empty() {
        files.push(emit_models(app));
    }
    if !app.controllers.is_empty() {
        files.push(emit_controllers(app));
    }
    if !app.routes.entries.is_empty() {
        files.push(emit_routes(app));
    }
    files
}

// Models ---------------------------------------------------------------

fn emit_models(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    for (i, model) in app.models.iter().enumerate() {
        if i > 0 {
            writeln!(s).unwrap();
        }
        emit_model(&mut s, model);
    }
    EmittedFile { path: PathBuf::from("src/models.ts"), content: s }
}

fn emit_model(out: &mut String, model: &Model) {
    let name = model.name.0.as_str();
    writeln!(out, "export class {name} {{").unwrap();
    for (field, ty) in &model.attributes.fields {
        writeln!(out, "  {}: {};", ts_field_name(field.as_str()), ts_ty(ty)).unwrap();
    }
    for method in model.methods() {
        writeln!(out).unwrap();
        emit_model_method(out, method);
    }
    writeln!(out, "}}").unwrap();
}

fn emit_model_method(out: &mut String, m: &MethodDef) {
    let name = ts_method_name(m.name.as_str());
    let ret = m.body.ty.clone().unwrap_or(Ty::Nil);
    let ret_annot = if matches!(ret, Ty::Nil) {
        ": void".to_string()
    } else {
        format!(": {}", ts_ty(&ret))
    };
    let is_static = matches!(m.receiver, crate::dialect::MethodReceiver::Class);
    let static_prefix = if is_static { "static " } else { "" };
    writeln!(out, "  {static_prefix}{name}(){ret_annot} {{").unwrap();
    let body_text = emit_body(&m.body, &ret);
    for line in body_text.lines() {
        writeln!(out, "    {line}").unwrap();
    }
    writeln!(out, "  }}").unwrap();
}

// Controllers ----------------------------------------------------------

fn emit_controllers(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    for (i, controller) in app.controllers.iter().enumerate() {
        if i > 0 {
            writeln!(s).unwrap();
        }
        emit_controller(&mut s, controller);
    }
    EmittedFile { path: PathBuf::from("src/controllers.ts"), content: s }
}

fn emit_controller(out: &mut String, c: &Controller) {
    let name = c.name.0.as_str();
    writeln!(out, "export class {name} {{").unwrap();
    for (i, action) in c.actions().enumerate() {
        if i > 0 {
            writeln!(out).unwrap();
        }
        emit_action(out, action);
    }
    writeln!(out, "}}").unwrap();
}

fn emit_action(out: &mut String, a: &Action) {
    let name = ts_method_name(a.name.as_str());
    let ret = action_return_type(&a.body);
    // Async methods must return `Promise<T>` (or `Promise<void>`).
    // TypeScript's type system enforces this; keeping the wrap even
    // at scaffold depth avoids surprising later readers.
    let ret_annot = match &ret {
        Ty::Nil => ": Promise<void>".to_string(),
        other => format!(": Promise<{}>", ts_ty(other)),
    };
    writeln!(out, "  async {name}(){ret_annot} {{").unwrap();
    let body_text = emit_body(&a.body, &ret);
    for line in body_text.lines() {
        writeln!(out, "    {line}").unwrap();
    }
    writeln!(out, "  }}").unwrap();
}

fn action_return_type(body: &Expr) -> Ty {
    match &*body.node {
        ExprNode::Assign { value, .. } => value.ty.clone().unwrap_or(Ty::Nil),
        ExprNode::Seq { exprs } => exprs
            .last()
            .and_then(|e| match &*e.node {
                ExprNode::Assign { value, .. } => value.ty.clone(),
                _ => e.ty.clone(),
            })
            .unwrap_or(Ty::Nil),
        _ => body.ty.clone().unwrap_or(Ty::Nil),
    }
}

// Routes ---------------------------------------------------------------

fn emit_routes(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "export interface Route {{").unwrap();
    writeln!(s, "  method: string;").unwrap();
    writeln!(s, "  path: string;").unwrap();
    writeln!(s, "  controller: string;").unwrap();
    writeln!(s, "  action: string;").unwrap();
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "export const routes: Route[] = [").unwrap();
    let mut flat: Vec<(String, String, String, String)> = Vec::new();
    for entry in &app.routes.entries {
        collect_flat_routes(entry, &mut flat, None);
    }
    for (method, path, controller, action) in flat {
        writeln!(
            s,
            "  {{ method: {:?}, path: {:?}, controller: {:?}, action: {:?} }},",
            method, path, controller, action,
        )
        .unwrap();
    }
    writeln!(s, "];").unwrap();
    EmittedFile { path: PathBuf::from("src/routes.ts"), content: s }
}

/// Flatten `RouteSpec` entries into concrete route records for the
/// dispatch table. `resources :name` expands into the 7 standard
/// actions (or the subset permitted by `only` / `except`). Nested
/// resources inherit a scope prefix.
fn collect_flat_routes(
    spec: &RouteSpec,
    out: &mut Vec<(String, String, String, String)>,
    scope_prefix: Option<(&str, &str)>,
) {
    match spec {
        RouteSpec::Explicit { method, path, controller, action, .. } => {
            let verb = match method {
                crate::dialect::HttpMethod::Get => "GET",
                crate::dialect::HttpMethod::Post => "POST",
                crate::dialect::HttpMethod::Put => "PUT",
                crate::dialect::HttpMethod::Patch => "PATCH",
                crate::dialect::HttpMethod::Delete => "DELETE",
                crate::dialect::HttpMethod::Head => "HEAD",
                crate::dialect::HttpMethod::Options => "OPTIONS",
                crate::dialect::HttpMethod::Any => "ANY",
            };
            let full_path = match scope_prefix {
                Some((parent, _)) => format!("/{parent}/:{parent}_id{path}"),
                None => path.clone(),
            };
            out.push((
                verb.to_string(),
                full_path,
                controller.0.to_string(),
                action.to_string(),
            ));
        }
        RouteSpec::Root { target } => {
            if let Some((c, a)) = target.split_once('#') {
                out.push((
                    "GET".into(),
                    "/".into(),
                    controller_class_name(c),
                    a.to_string(),
                ));
            }
        }
        RouteSpec::Resources { name, only, except, nested } => {
            let resource_path = format!("/{name}");
            let controller = controller_class_name(name.as_str());
            for (action, verb, suffix) in standard_resource_actions() {
                let action = *action;
                let verb = *verb;
                let suffix = *suffix;
                if !only.is_empty() && !only.iter().any(|s| s.as_str() == action) {
                    continue;
                }
                if except.iter().any(|s| s.as_str() == action) {
                    continue;
                }
                let path = format!("{resource_path}{suffix}");
                let full_path = match scope_prefix {
                    Some((parent, _)) => {
                        format!("/{parent}/:{parent}_id{path}")
                    }
                    None => path,
                };
                out.push((verb.into(), full_path, controller.clone(), action.into()));
            }
            // Nested resources scope under this resource's singular name.
            let singular =
                crate::naming::singularize_camelize(name.as_str()).to_lowercase();
            for child in nested {
                collect_flat_routes(child, out, Some((&singular, name.as_str())));
            }
        }
    }
}

/// The seven standard resource actions, in the order Rails conventionally
/// documents them: `(action_name, http_verb, path_suffix_after_resource)`.
fn standard_resource_actions() -> &'static [(&'static str, &'static str, &'static str)] {
    &[
        ("index", "GET", ""),
        ("new", "GET", "/new"),
        ("create", "POST", ""),
        ("show", "GET", "/:id"),
        ("edit", "GET", "/:id/edit"),
        ("update", "PATCH", "/:id"),
        ("destroy", "DELETE", "/:id"),
    ]
}

fn controller_class_name(short: &str) -> String {
    let mut s = crate::naming::camelize(short);
    s.push_str("Controller");
    s
}

// Body + expressions ---------------------------------------------------

fn emit_body(body: &Expr, return_ty: &Ty) -> String {
    let is_void = matches!(return_ty, Ty::Nil);
    match &*body.node {
        ExprNode::Assign { target: LValue::Ivar { .. }, value } => {
            if is_void {
                format!("{};", emit_expr(value))
            } else {
                format!("return {};", emit_expr(value))
            }
        }
        ExprNode::Seq { exprs } if !exprs.is_empty() => {
            let mut lines: Vec<String> = Vec::new();
            for (i, e) in exprs.iter().enumerate() {
                lines.push(emit_stmt(e, i == exprs.len() - 1, is_void));
            }
            lines.join("\n")
        }
        _ => {
            if is_void {
                format!("{};", emit_expr(body))
            } else {
                format!("return {};", emit_expr(body))
            }
        }
    }
}

fn emit_stmt(e: &Expr, is_last: bool, void_return: bool) -> String {
    match &*e.node {
        ExprNode::Assign { target: LValue::Var { name, .. }, value } => {
            format!("const {} = {};", name, emit_expr(value))
        }
        ExprNode::Assign { target: LValue::Ivar { name }, value } => {
            format!("this.{} = {};", ts_field_name(name.as_str()), emit_expr(value))
        }
        _ => {
            if is_last && !void_return {
                format!("return {};", emit_expr(e))
            } else {
                format!("{};", emit_expr(e))
            }
        }
    }
}

fn emit_expr(e: &Expr) -> String {
    match &*e.node {
        ExprNode::Lit { value } => emit_literal(value),
        ExprNode::Const { path } => {
            path.iter().map(|s| s.to_string()).collect::<Vec<_>>().join(".")
        }
        ExprNode::Var { name, .. } => name.to_string(),
        ExprNode::Ivar { name } => format!("this.{}", ts_field_name(name.as_str())),
        ExprNode::Send { recv, method, args, .. } => {
            emit_send(recv.as_ref(), method.as_str(), args)
        }
        ExprNode::Assign { target: _, value } => emit_expr(value),
        ExprNode::Seq { exprs } => {
            exprs.iter().map(emit_expr).collect::<Vec<_>>().join("; ")
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            let cond_s = emit_expr(cond);
            let then_s = indent_lines(&emit_expr(then_branch), 1);
            let else_s = indent_lines(&emit_expr(else_branch), 1);
            format!("if ({cond_s}) {{\n{then_s}\n}} else {{\n{else_s}\n}}")
        }
        ExprNode::BoolOp { op, left, right, .. } => {
            use crate::expr::BoolOpKind;
            let op_s = match op {
                BoolOpKind::Or => "||",
                BoolOpKind::And => "&&",
            };
            format!("{} {} {}", emit_expr(left), op_s, emit_expr(right))
        }
        ExprNode::Array { elements, .. } => {
            let parts: Vec<String> = elements.iter().map(emit_expr).collect();
            format!("[{}]", parts.join(", "))
        }
        ExprNode::Hash { entries, .. } => {
            let parts: Vec<String> = entries
                .iter()
                .map(|(k, v)| format!("{}: {}", emit_expr(k), emit_expr(v)))
                .collect();
            format!("{{ {} }}", parts.join(", "))
        }
        ExprNode::StringInterp { parts } => {
            use crate::expr::InterpPart;
            let mut out = String::from("`");
            for p in parts {
                match p {
                    InterpPart::Text { value } => {
                        for c in value.chars() {
                            if c == '`' || c == '\\' {
                                out.push('\\');
                                out.push(c);
                            } else if c == '$' {
                                out.push_str("\\$");
                            } else {
                                out.push(c);
                            }
                        }
                    }
                    InterpPart::Expr { expr } => {
                        out.push_str("${");
                        out.push_str(&emit_expr(expr));
                        out.push('}');
                    }
                }
            }
            out.push('`');
            out
        }
        other => format!("/* TODO: emit {:?} */", std::mem::discriminant(other)),
    }
}

fn emit_send(recv: Option<&Expr>, method: &str, args: &[Expr]) -> String {
    let args_s: Vec<String> = args.iter().map(emit_expr).collect();
    if method == "[]" && recv.is_some() {
        return format!("{}[{}]", emit_expr(recv.unwrap()), args_s.join(", "));
    }
    let ts_m = ts_method_name(method);
    match recv {
        None => {
            if args_s.is_empty() {
                ts_m
            } else {
                format!("{}({})", ts_m, args_s.join(", "))
            }
        }
        Some(r) => {
            let recv_s = emit_expr(r);
            format!("{}.{}({})", recv_s, ts_m, args_s.join(", "))
        }
    }
}

fn emit_literal(lit: &Literal) -> String {
    match lit {
        Literal::Nil => "null".to_string(),
        Literal::Bool { value } => value.to_string(),
        Literal::Int { value } => value.to_string(),
        Literal::Float { value } => {
            let s = value.to_string();
            if s.contains('.') { s } else { format!("{s}.0") }
        }
        Literal::Str { value } => format!("{value:?}"),
        // Ruby symbols map to string literals — the typed analyzer may
        // refine this into a discriminated-union enum later, but for
        // the scaffold a string is unambiguous and round-trips through
        // comparison as expected.
        Literal::Sym { value } => format!("{:?}", value.as_str()),
    }
}

fn indent_lines(text: &str, depth: usize) -> String {
    let pad = "  ".repeat(depth);
    text.lines()
        .map(|l| format!("{pad}{l}"))
        .collect::<Vec<_>>()
        .join("\n")
}

// Types ----------------------------------------------------------------

pub fn ts_ty(ty: &Ty) -> String {
    match ty {
        Ty::Int | Ty::Float => "number".to_string(),
        Ty::Bool => "boolean".to_string(),
        // Symbols model as string for now. When a pass identifies a
        // closed set of symbols at a given position (enum detection),
        // emit it as a union-of-string-literals instead.
        Ty::Str | Ty::Sym => "string".to_string(),
        Ty::Nil => "null".to_string(),
        Ty::Array { elem } => format!("{}[]", ts_ty(elem)),
        Ty::Hash { key, value } => {
            format!("Record<{}, {}>", ts_ty(key), ts_ty(value))
        }
        Ty::Tuple { elems } => {
            let parts: Vec<String> = elems.iter().map(ts_ty).collect();
            format!("[{}]", parts.join(", "))
        }
        Ty::Record { .. } => "Record<string, unknown>".to_string(),
        Ty::Union { variants } => {
            let parts: Vec<String> = variants.iter().map(ts_ty).collect();
            parts.join(" | ")
        }
        Ty::Class { id, .. } => id.0.to_string(),
        Ty::Fn { .. } => "(...args: unknown[]) => unknown".to_string(),
        Ty::Var { .. } => "unknown".to_string(),
    }
}

// Naming ---------------------------------------------------------------

/// Instance-field name: TypeScript / JS idiom is camelCase. Ruby's
/// `post_id` becomes `postId`; `title` stays `title`.
fn ts_field_name(ruby_name: &str) -> String {
    to_camel_case(ruby_name)
}

/// Method name: same camelCase rule as fields. Ruby's `redirect_to`
/// becomes `redirectTo`, `respond_to` → `respondTo`, etc. Single-word
/// names pass through unchanged.
fn ts_method_name(ruby_name: &str) -> String {
    to_camel_case(ruby_name)
}

fn to_camel_case(snake: &str) -> String {
    let mut parts = snake.split('_');
    let first = parts.next().unwrap_or("").to_string();
    let rest: String = parts
        .map(|p| {
            let mut chars = p.chars();
            match chars.next() {
                Some(c) => c.to_ascii_uppercase().to_string() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect();
    first + &rest
}
