//! TypeScript emitter — targets Juntos.
//!
//! Started as the Phase 2 scaffold; Phase 3 upgrades the output to
//! Juntos's runtime shape (the committed TS target per the strategy
//! memory). Changes land incrementally so each commit stays small:
//!
//! - **Models** (this commit): `extends ApplicationRecord`, `static
//!   table_name`, `static columns`. One file per model under
//!   `app/models/<snake>.ts`. Schema-derived instance fields drop
//!   from the class body — Juntos materializes them at runtime from
//!   the `columns` list, and declaring them statically would
//!   collide with the runtime accessors.
//! - Validations, associations, broadcasts: separate Phase 3 commits
//!   once this first shape is in place.
//! - Controllers + router + views: later Phase 3 commits.
//!
//! Ruby → Juntos translation rules come from ruby2js's
//! `lib/ruby2js/filter/rails/model.rb` and `lib/ruby2js/filter/rails/
//! active_record.rb`. Those are the reference; our job is to produce
//! equivalent output driven by the typed IR.
//!
//! Non-goals still (later Phase 3 commits):
//! - Controller shape (extends Controller, ivar-style state).
//! - Router emit (Router.resources calls, not a flat table).
//! - View / template emission.
//! - `tsc --strict` cleanliness.

use std::fmt::Write;
use std::path::PathBuf;

use super::EmittedFile;
use crate::App;
use crate::dialect::{
    Action, Association, Controller, MethodDef, Model, RouteSpec, Validation, ValidationRule,
};
use crate::expr::{Expr, ExprNode, LValue, Literal};
use crate::ty::Ty;

pub fn emit(app: &App) -> Vec<EmittedFile> {
    let mut files = Vec::new();
    files.extend(emit_models(app));
    if !app.controllers.is_empty() {
        files.push(emit_controllers(app));
    }
    if !app.routes.entries.is_empty() {
        files.push(emit_routes(app));
    }
    files
}

// Models ---------------------------------------------------------------

/// Emit one `app/models/<snake>.ts` per model. Juntos imports each
/// model as its own module; a flat `models.ts` bundle would make
/// circular-import resolution harder and doesn't match the Rails-
/// per-file convention.
fn emit_models(app: &App) -> Vec<EmittedFile> {
    app.models.iter().map(emit_model_file).collect()
}

fn emit_model_file(model: &Model) -> EmittedFile {
    let name = model.name.0.as_str();
    let file_stem = crate::naming::snake_case(name);
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    // The import list grows with what the model actually uses:
    // - ApplicationRecord is always imported (every model extends it).
    // - CollectionProxy + modelRegistry ride along when has_many is present.
    // - Reference joins for belongs_to.
    // - HasOneReference for has_one.
    let mut imports: Vec<&str> = vec!["ApplicationRecord"];
    let has_many = model.associations().any(|a| matches!(a, Association::HasMany { .. }));
    let has_one = model.associations().any(|a| matches!(a, Association::HasOne { .. }));
    let has_belongs_to = model
        .associations()
        .any(|a| matches!(a, Association::BelongsTo { .. }));
    let uses_registry = has_many || has_one || has_belongs_to;
    if has_many {
        imports.push("CollectionProxy");
    }
    if has_belongs_to {
        imports.push("Reference");
    }
    if has_one {
        imports.push("HasOneReference");
    }
    if uses_registry {
        imports.push("modelRegistry");
    }
    writeln!(
        s,
        "import {{ {} }} from \"juntos\";",
        imports.join(", ")
    )
    .unwrap();
    writeln!(s).unwrap();

    let parent = model
        .parent
        .as_ref()
        .map(|p| p.0.to_string())
        .unwrap_or_else(|| "ApplicationRecord".to_string());
    writeln!(s, "export class {name} extends {parent} {{").unwrap();

    let table = model.table.0.as_str();
    writeln!(s, "  static table_name = {table:?};").unwrap();

    // Juntos discovers columns from this static — omitting the `id`
    // primary key since it's universal (matches the ruby2js filter's
    // behavior: columns listed are the non-id schema columns).
    let columns: Vec<String> = model
        .attributes
        .fields
        .keys()
        .filter(|k| k.as_str() != "id")
        .map(|k| format!("{:?}", k.as_str()))
        .collect();
    if columns.is_empty() {
        writeln!(s, "  static columns: string[] = [];").unwrap();
    } else {
        writeln!(s, "  static columns = [{}];", columns.join(", ")).unwrap();
    }

    // Associations: one getter per association. Returns a
    // CollectionProxy (has_many), Reference (belongs_to), or
    // HasOneReference (has_one). Juntos's proxies lazily resolve
    // the target model through modelRegistry, which sidesteps
    // circular-import issues across model files.
    for assoc in model.associations() {
        writeln!(s).unwrap();
        emit_association(&mut s, assoc);
    }

    // Validations collapse into a single `validate()` method — one line
    // per (attribute, rule) pair. Juntos calls this method during
    // `isValid()` / `save()`; each `validates_<kind>_of` sets errors
    // on `this.errors`.
    let validations: Vec<&Validation> = model.validations().collect();
    if !validations.is_empty() {
        writeln!(s).unwrap();
        writeln!(s, "  validate() {{").unwrap();
        for v in &validations {
            for rule in &v.rules {
                if let Some(call) = emit_validate_call(v.attribute.as_str(), rule) {
                    writeln!(s, "    {call};").unwrap();
                }
            }
        }
        writeln!(s, "  }}").unwrap();
    }

    for method in model.methods() {
        writeln!(s).unwrap();
        emit_model_method(&mut s, method);
    }
    writeln!(s, "}}").unwrap();

    EmittedFile {
        path: PathBuf::from(format!("app/models/{file_stem}.ts")),
        content: s,
    }
}

/// Emit a Juntos-shaped association getter. Each kind produces a
/// `get <name>()` that constructs the appropriate proxy object; the
/// target class is looked up lazily through `modelRegistry` so model
/// files don't need to import each other.
fn emit_association(out: &mut String, assoc: &Association) {
    match assoc {
        Association::HasMany { name, target, foreign_key, .. } => {
            writeln!(out, "  get {name}() {{").unwrap();
            writeln!(out, "    return new CollectionProxy(this, {{").unwrap();
            writeln!(out, "      name: {:?},", name.as_str()).unwrap();
            writeln!(out, "      type: \"has_many\",").unwrap();
            writeln!(out, "      foreignKey: {:?}", foreign_key.as_str()).unwrap();
            writeln!(out, "    }}, modelRegistry.{});", target.0).unwrap();
            writeln!(out, "  }}").unwrap();
        }
        Association::HasOne { name, target, foreign_key, .. } => {
            writeln!(out, "  get {name}() {{").unwrap();
            writeln!(out, "    return new HasOneReference(this, {{").unwrap();
            writeln!(out, "      name: {:?},", name.as_str()).unwrap();
            writeln!(out, "      type: \"has_one\",").unwrap();
            writeln!(out, "      foreignKey: {:?}", foreign_key.as_str()).unwrap();
            writeln!(out, "    }}, modelRegistry.{});", target.0).unwrap();
            writeln!(out, "  }}").unwrap();
        }
        Association::BelongsTo { name, target, foreign_key, optional } => {
            writeln!(out, "  get {name}() {{").unwrap();
            let fk_access = format!("this.attributes.{}", foreign_key.as_str());
            if *optional {
                // Optional belongs_to returns null when the FK is
                // unset. Matches Rails' `belongs_to :x, optional: true`.
                writeln!(
                    out,
                    "    return {fk_access} ? new Reference(modelRegistry.{}, {fk_access}) : null;",
                    target.0
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    "    return new Reference(modelRegistry.{}, {fk_access});",
                    target.0
                )
                .unwrap();
            }
            writeln!(out, "  }}").unwrap();
        }
        Association::HasAndBelongsToMany { name, target, join_table } => {
            // Juntos doesn't have a dedicated HABTM proxy class in the
            // reference material we've seen; emit a CollectionProxy
            // with a HABTM type tag plus the join-table name. Worst
            // case the Juntos runtime errors loudly — no fixture
            // exercises this yet.
            writeln!(out, "  get {name}() {{").unwrap();
            writeln!(out, "    return new CollectionProxy(this, {{").unwrap();
            writeln!(out, "      name: {:?},", name.as_str()).unwrap();
            writeln!(out, "      type: \"has_and_belongs_to_many\",").unwrap();
            writeln!(out, "      joinTable: {:?}", join_table.as_str()).unwrap();
            writeln!(out, "    }}, modelRegistry.{});", target.0).unwrap();
            writeln!(out, "  }}").unwrap();
        }
    }
}

/// Build the single-line `this.validates_<kind>_of(...)` call for one
/// attribute + one rule. Returns `None` for rules we can't yet emit
/// (so emit silently skips rather than producing broken JS); that's
/// temporary — a fixture forcing the gap will drive the follow-up.
fn emit_validate_call(attr: &str, rule: &ValidationRule) -> Option<String> {
    let attr_lit = format!("{attr:?}");
    match rule {
        ValidationRule::Presence => {
            Some(format!("this.validates_presence_of({attr_lit})"))
        }
        ValidationRule::Absence => {
            Some(format!("this.validates_absence_of({attr_lit})"))
        }
        ValidationRule::Length { min, max } => {
            let mut opts = Vec::new();
            if let Some(n) = min { opts.push(format!("minimum: {n}")); }
            if let Some(n) = max { opts.push(format!("maximum: {n}")); }
            Some(format!(
                "this.validates_length_of({attr_lit}, {{{}}})",
                opts.join(", ")
            ))
        }
        ValidationRule::Uniqueness { scope, case_sensitive } => {
            let mut opts = Vec::new();
            if !scope.is_empty() {
                let parts: Vec<String> =
                    scope.iter().map(|s| format!("{:?}", s.as_str())).collect();
                opts.push(format!("scope: [{}]", parts.join(", ")));
            }
            if !*case_sensitive {
                opts.push("case_sensitive: false".to_string());
            }
            Some(if opts.is_empty() {
                format!("this.validates_uniqueness_of({attr_lit})")
            } else {
                format!(
                    "this.validates_uniqueness_of({attr_lit}, {{{}}})",
                    opts.join(", ")
                )
            })
        }
        ValidationRule::Format { pattern } => Some(format!(
            "this.validates_format_of({attr_lit}, {{with: /{pattern}/}})"
        )),
        ValidationRule::Numericality { only_integer, gt, lt } => {
            let mut opts = Vec::new();
            if *only_integer { opts.push("only_integer: true".to_string()); }
            if let Some(n) = gt { opts.push(format!("greater_than: {n}")); }
            if let Some(n) = lt { opts.push(format!("less_than: {n}")); }
            Some(if opts.is_empty() {
                format!("this.validates_numericality_of({attr_lit})")
            } else {
                format!(
                    "this.validates_numericality_of({attr_lit}, {{{}}})",
                    opts.join(", ")
                )
            })
        }
        ValidationRule::Inclusion { values } => {
            let parts: Vec<String> = values.iter().map(emit_literal).collect();
            Some(format!(
                "this.validates_inclusion_of({attr_lit}, {{in: [{}]}})",
                parts.join(", ")
            ))
        }
        ValidationRule::Custom { method } => {
            // `validate :method_name` (no `s` — different DSL). Juntos
            // convention is still a method reference; emit as a direct
            // call so the method runs during `validate()`.
            Some(format!("this.{method}()"))
        }
    }
}

fn emit_model_method(out: &mut String, m: &MethodDef) {
    let name = ts_method_name(m.name.as_str());
    let ret = m.body.ty.clone().unwrap_or(Ty::Nil);
    let ret_annot = if matches!(ret, Ty::Nil) {
        ": void".to_string()
    } else {
        format!(": {}", ts_ty(&ret))
    };
    let is_static = matches!(m.receiver, crate::dialect::MethodReceiver::Class);
    let static_prefix = if is_static { "static " } else { "" };
    writeln!(out, "  {static_prefix}{name}(){ret_annot} {{").unwrap();
    let body_text = emit_body(&m.body, &ret);
    for line in body_text.lines() {
        writeln!(out, "    {line}").unwrap();
    }
    writeln!(out, "  }}").unwrap();
}

// Controllers ----------------------------------------------------------

fn emit_controllers(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    for (i, controller) in app.controllers.iter().enumerate() {
        if i > 0 {
            writeln!(s).unwrap();
        }
        emit_controller(&mut s, controller);
    }
    EmittedFile { path: PathBuf::from("src/controllers.ts"), content: s }
}

fn emit_controller(out: &mut String, c: &Controller) {
    let name = c.name.0.as_str();
    writeln!(out, "export class {name} {{").unwrap();
    for (i, action) in c.actions().enumerate() {
        if i > 0 {
            writeln!(out).unwrap();
        }
        emit_action(out, action);
    }
    writeln!(out, "}}").unwrap();
}

fn emit_action(out: &mut String, a: &Action) {
    let name = ts_method_name(a.name.as_str());
    let ret = action_return_type(&a.body);
    // Async methods must return `Promise<T>` (or `Promise<void>`).
    // TypeScript's type system enforces this; keeping the wrap even
    // at scaffold depth avoids surprising later readers.
    let ret_annot = match &ret {
        Ty::Nil => ": Promise<void>".to_string(),
        other => format!(": Promise<{}>", ts_ty(other)),
    };
    writeln!(out, "  async {name}(){ret_annot} {{").unwrap();
    let body_text = emit_body(&a.body, &ret);
    for line in body_text.lines() {
        writeln!(out, "    {line}").unwrap();
    }
    writeln!(out, "  }}").unwrap();
}

fn action_return_type(body: &Expr) -> Ty {
    match &*body.node {
        ExprNode::Assign { value, .. } => value.ty.clone().unwrap_or(Ty::Nil),
        ExprNode::Seq { exprs } => exprs
            .last()
            .and_then(|e| match &*e.node {
                ExprNode::Assign { value, .. } => value.ty.clone(),
                _ => e.ty.clone(),
            })
            .unwrap_or(Ty::Nil),
        _ => body.ty.clone().unwrap_or(Ty::Nil),
    }
}

// Routes ---------------------------------------------------------------

fn emit_routes(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "export interface Route {{").unwrap();
    writeln!(s, "  method: string;").unwrap();
    writeln!(s, "  path: string;").unwrap();
    writeln!(s, "  controller: string;").unwrap();
    writeln!(s, "  action: string;").unwrap();
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "export const routes: Route[] = [").unwrap();
    let mut flat: Vec<(String, String, String, String)> = Vec::new();
    for entry in &app.routes.entries {
        collect_flat_routes(entry, &mut flat, None);
    }
    for (method, path, controller, action) in flat {
        writeln!(
            s,
            "  {{ method: {:?}, path: {:?}, controller: {:?}, action: {:?} }},",
            method, path, controller, action,
        )
        .unwrap();
    }
    writeln!(s, "];").unwrap();
    EmittedFile { path: PathBuf::from("src/routes.ts"), content: s }
}

/// Flatten `RouteSpec` entries into concrete route records for the
/// dispatch table. `resources :name` expands into the 7 standard
/// actions (or the subset permitted by `only` / `except`). Nested
/// resources inherit a scope prefix.
fn collect_flat_routes(
    spec: &RouteSpec,
    out: &mut Vec<(String, String, String, String)>,
    scope_prefix: Option<(&str, &str)>,
) {
    match spec {
        RouteSpec::Explicit { method, path, controller, action, .. } => {
            let verb = match method {
                crate::dialect::HttpMethod::Get => "GET",
                crate::dialect::HttpMethod::Post => "POST",
                crate::dialect::HttpMethod::Put => "PUT",
                crate::dialect::HttpMethod::Patch => "PATCH",
                crate::dialect::HttpMethod::Delete => "DELETE",
                crate::dialect::HttpMethod::Head => "HEAD",
                crate::dialect::HttpMethod::Options => "OPTIONS",
                crate::dialect::HttpMethod::Any => "ANY",
            };
            let full_path = match scope_prefix {
                Some((parent, _)) => format!("/{parent}/:{parent}_id{path}"),
                None => path.clone(),
            };
            out.push((
                verb.to_string(),
                full_path,
                controller.0.to_string(),
                action.to_string(),
            ));
        }
        RouteSpec::Root { target } => {
            if let Some((c, a)) = target.split_once('#') {
                out.push((
                    "GET".into(),
                    "/".into(),
                    controller_class_name(c),
                    a.to_string(),
                ));
            }
        }
        RouteSpec::Resources { name, only, except, nested } => {
            let resource_path = format!("/{name}");
            let controller = controller_class_name(name.as_str());
            for (action, verb, suffix) in standard_resource_actions() {
                let action = *action;
                let verb = *verb;
                let suffix = *suffix;
                if !only.is_empty() && !only.iter().any(|s| s.as_str() == action) {
                    continue;
                }
                if except.iter().any(|s| s.as_str() == action) {
                    continue;
                }
                let path = format!("{resource_path}{suffix}");
                let full_path = match scope_prefix {
                    Some((parent, _)) => {
                        format!("/{parent}/:{parent}_id{path}")
                    }
                    None => path,
                };
                out.push((verb.into(), full_path, controller.clone(), action.into()));
            }
            // Nested resources scope under this resource's singular name.
            let singular =
                crate::naming::singularize_camelize(name.as_str()).to_lowercase();
            for child in nested {
                collect_flat_routes(child, out, Some((&singular, name.as_str())));
            }
        }
    }
}

/// The seven standard resource actions, in the order Rails conventionally
/// documents them: `(action_name, http_verb, path_suffix_after_resource)`.
fn standard_resource_actions() -> &'static [(&'static str, &'static str, &'static str)] {
    &[
        ("index", "GET", ""),
        ("new", "GET", "/new"),
        ("create", "POST", ""),
        ("show", "GET", "/:id"),
        ("edit", "GET", "/:id/edit"),
        ("update", "PATCH", "/:id"),
        ("destroy", "DELETE", "/:id"),
    ]
}

fn controller_class_name(short: &str) -> String {
    let mut s = crate::naming::camelize(short);
    s.push_str("Controller");
    s
}

// Body + expressions ---------------------------------------------------

fn emit_body(body: &Expr, return_ty: &Ty) -> String {
    let is_void = matches!(return_ty, Ty::Nil);
    match &*body.node {
        ExprNode::Assign { target: LValue::Ivar { .. }, value } => {
            if is_void {
                format!("{};", emit_expr(value))
            } else {
                format!("return {};", emit_expr(value))
            }
        }
        ExprNode::Seq { exprs } if !exprs.is_empty() => {
            let mut lines: Vec<String> = Vec::new();
            for (i, e) in exprs.iter().enumerate() {
                lines.push(emit_stmt(e, i == exprs.len() - 1, is_void));
            }
            lines.join("\n")
        }
        _ => {
            if is_void {
                format!("{};", emit_expr(body))
            } else {
                format!("return {};", emit_expr(body))
            }
        }
    }
}

fn emit_stmt(e: &Expr, is_last: bool, void_return: bool) -> String {
    match &*e.node {
        ExprNode::Assign { target: LValue::Var { name, .. }, value } => {
            format!("const {} = {};", name, emit_expr(value))
        }
        ExprNode::Assign { target: LValue::Ivar { name }, value } => {
            format!("this.{} = {};", ts_field_name(name.as_str()), emit_expr(value))
        }
        _ => {
            if is_last && !void_return {
                format!("return {};", emit_expr(e))
            } else {
                format!("{};", emit_expr(e))
            }
        }
    }
}

fn emit_expr(e: &Expr) -> String {
    match &*e.node {
        ExprNode::Lit { value } => emit_literal(value),
        ExprNode::Const { path } => {
            path.iter().map(|s| s.to_string()).collect::<Vec<_>>().join(".")
        }
        ExprNode::Var { name, .. } => name.to_string(),
        ExprNode::Ivar { name } => format!("this.{}", ts_field_name(name.as_str())),
        ExprNode::Send { recv, method, args, .. } => {
            emit_send(recv.as_ref(), method.as_str(), args)
        }
        ExprNode::Assign { target: _, value } => emit_expr(value),
        ExprNode::Seq { exprs } => {
            exprs.iter().map(emit_expr).collect::<Vec<_>>().join("; ")
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            let cond_s = emit_expr(cond);
            let then_s = indent_lines(&emit_expr(then_branch), 1);
            let else_s = indent_lines(&emit_expr(else_branch), 1);
            format!("if ({cond_s}) {{\n{then_s}\n}} else {{\n{else_s}\n}}")
        }
        ExprNode::BoolOp { op, left, right, .. } => {
            use crate::expr::BoolOpKind;
            let op_s = match op {
                BoolOpKind::Or => "||",
                BoolOpKind::And => "&&",
            };
            format!("{} {} {}", emit_expr(left), op_s, emit_expr(right))
        }
        ExprNode::Array { elements, .. } => {
            let parts: Vec<String> = elements.iter().map(emit_expr).collect();
            format!("[{}]", parts.join(", "))
        }
        ExprNode::Hash { entries, .. } => {
            let parts: Vec<String> = entries
                .iter()
                .map(|(k, v)| format!("{}: {}", emit_expr(k), emit_expr(v)))
                .collect();
            format!("{{ {} }}", parts.join(", "))
        }
        ExprNode::StringInterp { parts } => {
            use crate::expr::InterpPart;
            let mut out = String::from("`");
            for p in parts {
                match p {
                    InterpPart::Text { value } => {
                        for c in value.chars() {
                            if c == '`' || c == '\\' {
                                out.push('\\');
                                out.push(c);
                            } else if c == '$' {
                                out.push_str("\\$");
                            } else {
                                out.push(c);
                            }
                        }
                    }
                    InterpPart::Expr { expr } => {
                        out.push_str("${");
                        out.push_str(&emit_expr(expr));
                        out.push('}');
                    }
                }
            }
            out.push('`');
            out
        }
        other => format!("/* TODO: emit {:?} */", std::mem::discriminant(other)),
    }
}

fn emit_send(recv: Option<&Expr>, method: &str, args: &[Expr]) -> String {
    let args_s: Vec<String> = args.iter().map(emit_expr).collect();
    if method == "[]" && recv.is_some() {
        return format!("{}[{}]", emit_expr(recv.unwrap()), args_s.join(", "));
    }
    let ts_m = ts_method_name(method);
    match recv {
        None => {
            if args_s.is_empty() {
                ts_m
            } else {
                format!("{}({})", ts_m, args_s.join(", "))
            }
        }
        Some(r) => {
            let recv_s = emit_expr(r);
            format!("{}.{}({})", recv_s, ts_m, args_s.join(", "))
        }
    }
}

fn emit_literal(lit: &Literal) -> String {
    match lit {
        Literal::Nil => "null".to_string(),
        Literal::Bool { value } => value.to_string(),
        Literal::Int { value } => value.to_string(),
        Literal::Float { value } => {
            let s = value.to_string();
            if s.contains('.') { s } else { format!("{s}.0") }
        }
        Literal::Str { value } => format!("{value:?}"),
        // Ruby symbols map to string literals — the typed analyzer may
        // refine this into a discriminated-union enum later, but for
        // the scaffold a string is unambiguous and round-trips through
        // comparison as expected.
        Literal::Sym { value } => format!("{:?}", value.as_str()),
    }
}

fn indent_lines(text: &str, depth: usize) -> String {
    let pad = "  ".repeat(depth);
    text.lines()
        .map(|l| format!("{pad}{l}"))
        .collect::<Vec<_>>()
        .join("\n")
}

// Types ----------------------------------------------------------------

pub fn ts_ty(ty: &Ty) -> String {
    match ty {
        Ty::Int | Ty::Float => "number".to_string(),
        Ty::Bool => "boolean".to_string(),
        // Symbols model as string for now. When a pass identifies a
        // closed set of symbols at a given position (enum detection),
        // emit it as a union-of-string-literals instead.
        Ty::Str | Ty::Sym => "string".to_string(),
        Ty::Nil => "null".to_string(),
        Ty::Array { elem } => format!("{}[]", ts_ty(elem)),
        Ty::Hash { key, value } => {
            format!("Record<{}, {}>", ts_ty(key), ts_ty(value))
        }
        Ty::Tuple { elems } => {
            let parts: Vec<String> = elems.iter().map(ts_ty).collect();
            format!("[{}]", parts.join(", "))
        }
        Ty::Record { .. } => "Record<string, unknown>".to_string(),
        Ty::Union { variants } => {
            let parts: Vec<String> = variants.iter().map(ts_ty).collect();
            parts.join(" | ")
        }
        Ty::Class { id, .. } => id.0.to_string(),
        Ty::Fn { .. } => "(...args: unknown[]) => unknown".to_string(),
        Ty::Var { .. } => "unknown".to_string(),
    }
}

// Naming ---------------------------------------------------------------

/// Instance-field name: TypeScript / JS idiom is camelCase. Ruby's
/// `post_id` becomes `postId`; `title` stays `title`.
fn ts_field_name(ruby_name: &str) -> String {
    to_camel_case(ruby_name)
}

/// Method name: same camelCase rule as fields. Ruby's `redirect_to`
/// becomes `redirectTo`, `respond_to` → `respondTo`, etc. Single-word
/// names pass through unchanged.
fn ts_method_name(ruby_name: &str) -> String {
    to_camel_case(ruby_name)
}

fn to_camel_case(snake: &str) -> String {
    let mut parts = snake.split('_');
    let first = parts.next().unwrap_or("").to_string();
    let rest: String = parts
        .map(|p| {
            let mut chars = p.chars();
            match chars.next() {
                Some(c) => c.to_ascii_uppercase().to_string() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect();
    first + &rest
}
