//! TypeScript emitter — targets Juntos.
//!
//! Started as the Phase 2 scaffold; Phase 3 upgrades the output to
//! Juntos's runtime shape (the committed TS target per the strategy
//! memory). Changes land incrementally so each commit stays small:
//!
//! - **Models** (this commit): `extends ApplicationRecord`, `static
//!   table_name`, `static columns`. One file per model under
//!   `app/models/<snake>.ts`. Schema-derived instance fields drop
//!   from the class body — Juntos materializes them at runtime from
//!   the `columns` list, and declaring them statically would
//!   collide with the runtime accessors.
//! - Validations, associations, broadcasts: separate Phase 3 commits
//!   once this first shape is in place.
//! - Controllers + router + views: later Phase 3 commits.
//!
//! Ruby → Juntos translation rules come from ruby2js's
//! `lib/ruby2js/filter/rails/model.rb` and `lib/ruby2js/filter/rails/
//! active_record.rb`. Those are the reference; our job is to produce
//! equivalent output driven by the typed IR.
//!
//! Non-goals still (later Phase 3 commits):
//! - Controller shape (extends Controller, ivar-style state).
//! - Router emit (Router.resources calls, not a flat table).
//! - View / template emission.
//! - `tsc --strict` cleanliness.

use std::fmt::Write;
use std::path::PathBuf;

use super::EmittedFile;
use crate::App;
use crate::dialect::{
    Action, Association, Controller, MethodDef, Model, ModelBodyItem, RouteSpec, Validation,
    ValidationRule,
};
use crate::expr::{Expr, ExprNode, LValue, Literal};
use crate::ty::Ty;

pub fn emit(app: &App) -> Vec<EmittedFile> {
    let mut files = Vec::new();
    files.extend(emit_models(app));
    files.extend(emit_controllers(app));
    if !app.routes.entries.is_empty() {
        files.push(emit_routes(app));
    }
    files
}

// Models ---------------------------------------------------------------

/// Emit one `app/models/<snake>.ts` per model. Juntos imports each
/// model as its own module; a flat `models.ts` bundle would make
/// circular-import resolution harder and doesn't match the Rails-
/// per-file convention.
fn emit_models(app: &App) -> Vec<EmittedFile> {
    app.models.iter().map(emit_model_file).collect()
}

fn emit_model_file(model: &Model) -> EmittedFile {
    let name = model.name.0.as_str();
    let file_stem = crate::naming::snake_case(name);
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    // Normalize parent references for TS emission:
    // `ActiveRecord::Base` (Rails' root) → `ActiveRecord` (the Juntos
    // import), since `::` is a Ruby path separator, not valid JS.
    // Anything else keeps its IR spelling.
    let parent = model
        .parent
        .as_ref()
        .map(|p| {
            let name = p.0.as_str();
            if name == "ActiveRecord::Base" {
                "ActiveRecord".to_string()
            } else {
                name.to_string()
            }
        })
        .unwrap_or_else(|| "ApplicationRecord".to_string());

    // Import list: the parent itself (so `extends` resolves) plus the
    // proxy / registry symbols any associations on this model need.
    // Using the actual parent rather than hard-coding ApplicationRecord
    // avoids a self-import collision on `application_record.ts` (which
    // defines its own `export class ApplicationRecord extends
    // ActiveRecord`).
    let mut imports: Vec<&str> = vec![parent.as_str()];
    let has_many = model.associations().any(|a| matches!(a, Association::HasMany { .. }));
    let has_one = model.associations().any(|a| matches!(a, Association::HasOne { .. }));
    let has_belongs_to = model
        .associations()
        .any(|a| matches!(a, Association::BelongsTo { .. }));
    let uses_registry = has_many || has_one || has_belongs_to;
    if has_many {
        imports.push("CollectionProxy");
    }
    if has_belongs_to {
        imports.push("Reference");
    }
    if has_one {
        imports.push("HasOneReference");
    }
    if uses_registry {
        imports.push("modelRegistry");
    }
    writeln!(
        s,
        "import {{ {} }} from \"juntos\";",
        imports.join(", ")
    )
    .unwrap();
    writeln!(s).unwrap();

    writeln!(s, "export class {name} extends {parent} {{").unwrap();

    let table = model.table.0.as_str();
    writeln!(s, "  static table_name = {table:?};").unwrap();

    // Juntos discovers columns from this static — omitting the `id`
    // primary key since it's universal (matches the ruby2js filter's
    // behavior: columns listed are the non-id schema columns).
    let columns: Vec<String> = model
        .attributes
        .fields
        .keys()
        .filter(|k| k.as_str() != "id")
        .map(|k| format!("{:?}", k.as_str()))
        .collect();
    if columns.is_empty() {
        writeln!(s, "  static columns: string[] = [];").unwrap();
    } else {
        writeln!(s, "  static columns = [{}];", columns.join(", ")).unwrap();
    }

    // Associations: one getter per association. Returns a
    // CollectionProxy (has_many), Reference (belongs_to), or
    // HasOneReference (has_one). Juntos's proxies lazily resolve
    // the target model through modelRegistry, which sidesteps
    // circular-import issues across model files.
    for assoc in model.associations() {
        writeln!(s).unwrap();
        emit_association(&mut s, assoc);
    }

    // Validations collapse into a single `validate()` method — one line
    // per (attribute, rule) pair. Juntos calls this method during
    // `isValid()` / `save()`; each `validates_<kind>_of` sets errors
    // on `this.errors`.
    let validations: Vec<&Validation> = model.validations().collect();
    if !validations.is_empty() {
        writeln!(s).unwrap();
        writeln!(s, "  validate() {{").unwrap();
        for v in &validations {
            for rule in &v.rules {
                if let Some(call) = emit_validate_call(v.attribute.as_str(), rule) {
                    writeln!(s, "    {call};").unwrap();
                }
            }
        }
        writeln!(s, "  }}").unwrap();
    }

    for method in model.methods() {
        writeln!(s).unwrap();
        emit_model_method(&mut s, method);
    }
    writeln!(s, "}}").unwrap();

    // Broadcast callbacks land after the class body. Juntos's
    // Turbo-Streams integration registers them as `Model.afterSave`
    // / `Model.afterDestroy` hooks so they fire on every persist.
    // Pattern-matched out of `Unknown` body items — `broadcasts_to`
    // isn't a typed dialect node yet, so we look for the raw Send
    // and translate it here.
    let broadcast_lines = collect_broadcast_registrations(model);
    if !broadcast_lines.is_empty() {
        writeln!(s).unwrap();
        for line in broadcast_lines {
            writeln!(s, "{line}").unwrap();
        }
    }

    EmittedFile {
        path: PathBuf::from(format!("app/models/{file_stem}.ts")),
        content: s,
    }
}

/// Walk the model body for `broadcasts_to ...` calls (stored as
/// `Unknown` since they're not a typed dialect node yet) and return
/// one-line callback registrations per broadcast. Emits an afterSave
/// and an afterDestroy for each `broadcasts_to`.
fn collect_broadcast_registrations(model: &Model) -> Vec<String> {
    let mut lines: Vec<String> = Vec::new();
    let model_name = model.name.0.as_str();
    for item in &model.body {
        let ModelBodyItem::Unknown { expr, .. } = item else { continue };
        let ExprNode::Send { recv: None, method, args, .. } = &*expr.node else { continue };
        if method.as_str() != "broadcasts_to" {
            continue;
        }
        let Some(registration) = translate_broadcasts_to(model_name, args) else {
            continue;
        };
        lines.extend(registration);
    }
    lines
}

/// Translate one `broadcasts_to ..., opts` call into the two callback
/// registrations Juntos expects. Returns `None` when the shape is too
/// far from what we can map today (e.g., a stream-name expression that
/// isn't a lambda-with-string body).
fn translate_broadcasts_to(model_name: &str, args: &[Expr]) -> Option<Vec<String>> {
    // Arg 0: stream identifier. Usually `-> { "stream" }` or
    // `->(record) { "stream_#{record.foo}" }`. Fall back to emitting
    // the raw expression when it's a bare string / symbol / other.
    let stream_arg = args.first()?;
    let stream_js = broadcast_stream_expr(stream_arg)?;

    // Options hash (second arg, optional). We only care about
    // `inserts_by:` (append vs prepend) and `target:` today.
    let mut inserts_by: Option<&str> = None;
    let mut target_js: Option<String> = None;
    if let Some(opts) = args.get(1) {
        if let ExprNode::Hash { entries, .. } = &*opts.node {
            for (k, v) in entries {
                let Some(key) = hash_sym_key(k) else { continue };
                match key.as_str() {
                    "inserts_by" => {
                        if let ExprNode::Lit { value: Literal::Sym { value } } = &*v.node {
                            inserts_by = match value.as_str() {
                                "prepend" => Some("Prepend"),
                                "append" => Some("Append"),
                                _ => None,
                            };
                        }
                    }
                    "target" => {
                        // Target override: emit the raw expression as
                        // the first positional argument; Juntos's
                        // `broadcastXTo(stream, { target: ... })` is
                        // the richer form but both shapes appear.
                        target_js = Some(emit_expr(v));
                    }
                    _ => {}
                }
            }
        }
    }
    let insert_method = match inserts_by {
        Some("Prepend") => "broadcastPrependTo",
        _ => "broadcastAppendTo",
    };
    let mut save_args = vec![stream_js.clone()];
    if let Some(t) = &target_js {
        save_args.push(format!("{{ target: {t} }}"));
    }
    let destroy_args = vec![stream_js];
    Some(vec![
        format!(
            "{model_name}.afterSave((record) => record.{insert_method}({}));",
            save_args.join(", ")
        ),
        format!(
            "{model_name}.afterDestroy((record) => record.broadcastRemoveTo({}));",
            destroy_args.join(", ")
        ),
    ])
}

/// Pull the JS expression for a broadcasts_to stream argument. Handles
/// the common shapes: `-> { "name" }` (literal), `-> { "x_#{...}" }`
/// (interpolated — `#{expr}` becomes `${expr}` in the emit), or a
/// bare string / ident (pass-through).
fn broadcast_stream_expr(arg: &Expr) -> Option<String> {
    match &*arg.node {
        ExprNode::Lambda { body, params, .. } => {
            // Lambda param (if present) is conceptually `record` inside
            // the template body. Replace bare references to that param
            // with `record` in the emitted JS. For simple bodies we
            // handle literals and interpolation; complex bodies fall
            // through to the generic emit.
            let param_name = params.first().map(|s| s.to_string());
            Some(rewrite_record_refs(&emit_expr(body), param_name.as_deref()))
        }
        ExprNode::Lit { value: Literal::Str { value } } => Some(format!("{value:?}")),
        _ => Some(emit_expr(arg)),
    }
}

/// If the lambda param is `_article` or similar, the Juntos callback's
/// parameter is conventionally named `record`. Rewrite bare references
/// in the emitted text. `_`-prefixed idents (Ruby's "unused param"
/// convention) get included — we strip the underscore too so
/// `_article.foo` and `article.foo` both map to `record.foo`.
fn rewrite_record_refs(js: &str, param_name: Option<&str>) -> String {
    let Some(orig) = param_name else { return js.to_string() };
    // Consider both the raw param name and its underscore-stripped
    // form, since Ruby's `->(_article) { … }` can reference either
    // spelling in the body (the stripped one is unusual but valid).
    let stripped = orig.strip_prefix('_').unwrap_or(orig).to_string();
    let mut out = replace_word(js, orig, "record");
    if stripped != orig {
        out = replace_word(&out, &stripped, "record");
    }
    out
}

/// Replace every occurrence of `needle` in `haystack` where the match
/// is surrounded by non-identifier characters. Avoids mangling
/// `articles` when replacing `article`. No regex dependency.
fn replace_word(haystack: &str, needle: &str, replacement: &str) -> String {
    if needle.is_empty() {
        return haystack.to_string();
    }
    let bytes = haystack.as_bytes();
    let n = needle.len();
    let mut out = String::with_capacity(haystack.len());
    let mut i = 0;
    while i + n <= bytes.len() {
        if &bytes[i..i + n] == needle.as_bytes() {
            let prev_ok = i == 0 || !is_ident_byte(bytes[i - 1]);
            let next_ok = i + n == bytes.len() || !is_ident_byte(bytes[i + n]);
            if prev_ok && next_ok {
                out.push_str(replacement);
                i += n;
                continue;
            }
        }
        out.push(bytes[i] as char);
        i += 1;
    }
    if i < bytes.len() {
        out.push_str(&haystack[i..]);
    }
    out
}

fn is_ident_byte(b: u8) -> bool {
    b.is_ascii_alphanumeric() || b == b'_' || b == b'$'
}

fn hash_sym_key(k: &Expr) -> Option<crate::ident::Symbol> {
    match &*k.node {
        ExprNode::Lit { value: Literal::Sym { value } } => Some(value.clone()),
        _ => None,
    }
}

/// Emit a Juntos-shaped association getter. Each kind produces a
/// `get <name>()` that constructs the appropriate proxy object; the
/// target class is looked up lazily through `modelRegistry` so model
/// files don't need to import each other.
fn emit_association(out: &mut String, assoc: &Association) {
    match assoc {
        Association::HasMany { name, target, foreign_key, .. } => {
            writeln!(out, "  get {name}() {{").unwrap();
            writeln!(out, "    return new CollectionProxy(this, {{").unwrap();
            writeln!(out, "      name: {:?},", name.as_str()).unwrap();
            writeln!(out, "      type: \"has_many\",").unwrap();
            writeln!(out, "      foreignKey: {:?}", foreign_key.as_str()).unwrap();
            writeln!(out, "    }}, modelRegistry.{});", target.0).unwrap();
            writeln!(out, "  }}").unwrap();
        }
        Association::HasOne { name, target, foreign_key, .. } => {
            writeln!(out, "  get {name}() {{").unwrap();
            writeln!(out, "    return new HasOneReference(this, {{").unwrap();
            writeln!(out, "      name: {:?},", name.as_str()).unwrap();
            writeln!(out, "      type: \"has_one\",").unwrap();
            writeln!(out, "      foreignKey: {:?}", foreign_key.as_str()).unwrap();
            writeln!(out, "    }}, modelRegistry.{});", target.0).unwrap();
            writeln!(out, "  }}").unwrap();
        }
        Association::BelongsTo { name, target, foreign_key, optional } => {
            writeln!(out, "  get {name}() {{").unwrap();
            let fk_access = format!("this.attributes.{}", foreign_key.as_str());
            if *optional {
                // Optional belongs_to returns null when the FK is
                // unset. Matches Rails' `belongs_to :x, optional: true`.
                writeln!(
                    out,
                    "    return {fk_access} ? new Reference(modelRegistry.{}, {fk_access}) : null;",
                    target.0
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    "    return new Reference(modelRegistry.{}, {fk_access});",
                    target.0
                )
                .unwrap();
            }
            writeln!(out, "  }}").unwrap();
        }
        Association::HasAndBelongsToMany { name, target, join_table } => {
            // Juntos doesn't have a dedicated HABTM proxy class in the
            // reference material we've seen; emit a CollectionProxy
            // with a HABTM type tag plus the join-table name. Worst
            // case the Juntos runtime errors loudly — no fixture
            // exercises this yet.
            writeln!(out, "  get {name}() {{").unwrap();
            writeln!(out, "    return new CollectionProxy(this, {{").unwrap();
            writeln!(out, "      name: {:?},", name.as_str()).unwrap();
            writeln!(out, "      type: \"has_and_belongs_to_many\",").unwrap();
            writeln!(out, "      joinTable: {:?}", join_table.as_str()).unwrap();
            writeln!(out, "    }}, modelRegistry.{});", target.0).unwrap();
            writeln!(out, "  }}").unwrap();
        }
    }
}

/// Build the single-line `this.validates_<kind>_of(...)` call for one
/// attribute + one rule. Returns `None` for rules we can't yet emit
/// (so emit silently skips rather than producing broken JS); that's
/// temporary — a fixture forcing the gap will drive the follow-up.
fn emit_validate_call(attr: &str, rule: &ValidationRule) -> Option<String> {
    let attr_lit = format!("{attr:?}");
    match rule {
        ValidationRule::Presence => {
            Some(format!("this.validates_presence_of({attr_lit})"))
        }
        ValidationRule::Absence => {
            Some(format!("this.validates_absence_of({attr_lit})"))
        }
        ValidationRule::Length { min, max } => {
            let mut opts = Vec::new();
            if let Some(n) = min { opts.push(format!("minimum: {n}")); }
            if let Some(n) = max { opts.push(format!("maximum: {n}")); }
            Some(format!(
                "this.validates_length_of({attr_lit}, {{{}}})",
                opts.join(", ")
            ))
        }
        ValidationRule::Uniqueness { scope, case_sensitive } => {
            let mut opts = Vec::new();
            if !scope.is_empty() {
                let parts: Vec<String> =
                    scope.iter().map(|s| format!("{:?}", s.as_str())).collect();
                opts.push(format!("scope: [{}]", parts.join(", ")));
            }
            if !*case_sensitive {
                opts.push("case_sensitive: false".to_string());
            }
            Some(if opts.is_empty() {
                format!("this.validates_uniqueness_of({attr_lit})")
            } else {
                format!(
                    "this.validates_uniqueness_of({attr_lit}, {{{}}})",
                    opts.join(", ")
                )
            })
        }
        ValidationRule::Format { pattern } => Some(format!(
            "this.validates_format_of({attr_lit}, {{with: /{pattern}/}})"
        )),
        ValidationRule::Numericality { only_integer, gt, lt } => {
            let mut opts = Vec::new();
            if *only_integer { opts.push("only_integer: true".to_string()); }
            if let Some(n) = gt { opts.push(format!("greater_than: {n}")); }
            if let Some(n) = lt { opts.push(format!("less_than: {n}")); }
            Some(if opts.is_empty() {
                format!("this.validates_numericality_of({attr_lit})")
            } else {
                format!(
                    "this.validates_numericality_of({attr_lit}, {{{}}})",
                    opts.join(", ")
                )
            })
        }
        ValidationRule::Inclusion { values } => {
            let parts: Vec<String> = values.iter().map(emit_literal).collect();
            Some(format!(
                "this.validates_inclusion_of({attr_lit}, {{in: [{}]}})",
                parts.join(", ")
            ))
        }
        ValidationRule::Custom { method } => {
            // `validate :method_name` (no `s` — different DSL). Juntos
            // convention is still a method reference; emit as a direct
            // call so the method runs during `validate()`.
            Some(format!("this.{method}()"))
        }
    }
}

fn emit_model_method(out: &mut String, m: &MethodDef) {
    let name = ts_method_name(m.name.as_str());
    let ret = m.body.ty.clone().unwrap_or(Ty::Nil);
    let ret_annot = if matches!(ret, Ty::Nil) {
        ": void".to_string()
    } else {
        format!(": {}", ts_ty(&ret))
    };
    let is_static = matches!(m.receiver, crate::dialect::MethodReceiver::Class);
    let static_prefix = if is_static { "static " } else { "" };
    writeln!(out, "  {static_prefix}{name}(){ret_annot} {{").unwrap();
    let body_text = emit_body(&m.body, &ret);
    for line in body_text.lines() {
        writeln!(out, "    {line}").unwrap();
    }
    writeln!(out, "  }}").unwrap();
}

// Controllers ----------------------------------------------------------

/// Juntos controllers are *modules of exported async functions*, not
/// classes. Each action becomes `export async function name(context)`.
/// Rails instance variables (`@foo = ...`) rebind to local `let`s;
/// `params[:key]` rewrites to `context.params.key`. Matches ruby2js's
/// `lib/ruby2js/filter/rails/controller.rb` shape.
fn emit_controllers(app: &App) -> Vec<EmittedFile> {
    app.controllers.iter().map(emit_controller_file).collect()
}

fn emit_controller_file(c: &Controller) -> EmittedFile {
    let name = c.name.0.as_str();
    // The file stem keeps the `_controller` suffix — Rails convention
    // is `articles_controller.rb` for `ArticlesController`.
    let file_stem = crate::naming::snake_case(name);
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    // `emit_action` opens with a blank line, giving the header-to-
    // first-action and action-to-action spacing in one place.
    for action in c.actions() {
        emit_action(&mut s, action);
    }
    EmittedFile {
        path: PathBuf::from(format!("app/controllers/{file_stem}.ts")),
        content: s,
    }
}

fn emit_action(out: &mut String, a: &Action) {
    // `new` is a reserved word in JS; Rails uses it as an action name,
    // so ruby2js escapes to `$new`. Apply the same rule.
    let raw = a.name.as_str();
    let name = if raw == "new" { "$new" } else { raw };

    // Write actions (create, update, destroy) accept a second `params`
    // arg. Read actions get just `context`. Matches ruby2js's shape.
    let write_actions = matches!(raw, "create" | "update");
    let params_list = if write_actions {
        "context, params"
    } else {
        "context"
    };
    writeln!(out).unwrap();
    writeln!(out, "export async function {name}({params_list}) {{").unwrap();
    let body_text = emit_controller_body(&a.body);
    for line in body_text.lines() {
        if line.is_empty() {
            writeln!(out).unwrap();
        } else {
            writeln!(out, "  {line}").unwrap();
        }
    }
    writeln!(out, "}}").unwrap();
}

/// Emit a controller action body. Ivar assignments become `let`
/// rebinds; ivar reads and `params[:key]` access rewrite at the IR
/// level before falling through to the generic `emit_expr`.
fn emit_controller_body(body: &Expr) -> String {
    let rewritten = rewrite_for_controller(body);
    match &*rewritten.node {
        ExprNode::Seq { exprs } if !exprs.is_empty() => {
            let mut lines: Vec<String> = Vec::new();
            for (i, e) in exprs.iter().enumerate() {
                if i > 0 && e.leading_blank_line {
                    lines.push(String::new());
                }
                lines.push(emit_controller_stmt(e));
            }
            lines.join("\n")
        }
        _ => emit_controller_stmt(&rewritten),
    }
}

fn emit_controller_stmt(e: &Expr) -> String {
    match &*e.node {
        ExprNode::Assign { target: LValue::Var { name, .. }, value } => {
            // `let` rebind — ivar assignments were rewritten to Var
            // assignments by `rewrite_for_controller`, so both local
            // and "formerly ivar" writes land here identically.
            format!("let {} = {};", name, emit_expr(value))
        }
        _ => format!("{};", emit_expr(e)),
    }
}

/// IR-level rewrite pass that reshapes a controller action body to
/// Juntos conventions *before* the generic expression emitter runs:
///
/// - `@foo = x` → `foo = x`        (ivar writes become locals)
/// - `@foo`      → `foo`           (ivar reads become locals)
/// - `params[:k]` → `context.params.k` via a chained Send
///
/// Doing it at the IR level lets the existing `emit_expr` recurse
/// through nested expressions naturally — there's no need to thread
/// a "controller mode" flag through every call site.
fn rewrite_for_controller(expr: &Expr) -> Expr {
    use crate::ident::VarId;
    // Intercept the `params[:key]` pattern as a whole node first.
    if let Some(rewritten) = try_rewrite_params_access(expr) {
        return rewritten;
    }
    let new_node: ExprNode = match &*expr.node {
        ExprNode::Ivar { name } => ExprNode::Var { id: VarId(0), name: name.clone() },
        ExprNode::Assign { target: LValue::Ivar { name }, value } => ExprNode::Assign {
            target: LValue::Var { id: VarId(0), name: name.clone() },
            value: rewrite_for_controller(value),
        },
        ExprNode::Assign { target: LValue::Var { id, name }, value } => ExprNode::Assign {
            target: LValue::Var { id: *id, name: name.clone() },
            value: rewrite_for_controller(value),
        },
        ExprNode::Assign { target: LValue::Attr { recv, name }, value } => ExprNode::Assign {
            target: LValue::Attr {
                recv: rewrite_for_controller(recv),
                name: name.clone(),
            },
            value: rewrite_for_controller(value),
        },
        ExprNode::Assign { target: LValue::Index { recv, index }, value } => ExprNode::Assign {
            target: LValue::Index {
                recv: rewrite_for_controller(recv),
                index: rewrite_for_controller(index),
            },
            value: rewrite_for_controller(value),
        },
        ExprNode::Send { recv, method, args, block, parenthesized } => ExprNode::Send {
            recv: recv.as_ref().map(rewrite_for_controller),
            method: method.clone(),
            args: args.iter().map(rewrite_for_controller).collect(),
            block: block.as_ref().map(rewrite_for_controller),
            parenthesized: *parenthesized,
        },
        ExprNode::Seq { exprs } => ExprNode::Seq {
            exprs: exprs.iter().map(rewrite_for_controller).collect(),
        },
        ExprNode::If { cond, then_branch, else_branch } => ExprNode::If {
            cond: rewrite_for_controller(cond),
            then_branch: rewrite_for_controller(then_branch),
            else_branch: rewrite_for_controller(else_branch),
        },
        ExprNode::BoolOp { op, surface, left, right } => ExprNode::BoolOp {
            op: *op,
            surface: *surface,
            left: rewrite_for_controller(left),
            right: rewrite_for_controller(right),
        },
        ExprNode::Array { elements, style } => ExprNode::Array {
            elements: elements.iter().map(rewrite_for_controller).collect(),
            style: *style,
        },
        ExprNode::Hash { entries, braced } => ExprNode::Hash {
            entries: entries
                .iter()
                .map(|(k, v)| (rewrite_for_controller(k), rewrite_for_controller(v)))
                .collect(),
            braced: *braced,
        },
        // Other variants don't contain rewritable subtrees we care
        // about at controller-scope today (Literal, Const, Var,
        // Lambda, Apply, Case, Yield, Raise, RescueModifier,
        // StringInterp, Let). Clone verbatim.
        other => other.clone(),
    };
    Expr {
        span: expr.span,
        node: Box::new(new_node),
        ty: expr.ty.clone(),
        leading_blank_line: expr.leading_blank_line,
    }
}

/// Match the `params[:key]` call shape and rewrite it to the Juntos
/// `context.params.<key>` three-level Send chain. Returns None if the
/// expression isn't the params-access shape — the outer rewriter
/// continues with its generic recursion.
fn try_rewrite_params_access(expr: &Expr) -> Option<Expr> {
    let ExprNode::Send { recv: Some(recv), method, args, .. } = &*expr.node else {
        return None;
    };
    if method.as_str() != "[]" {
        return None;
    }
    let ExprNode::Send {
        recv: None,
        method: recv_method,
        args: recv_args,
        ..
    } = &*recv.node
    else {
        return None;
    };
    if recv_method.as_str() != "params" || !recv_args.is_empty() {
        return None;
    }
    let idx = args.first()?;
    let ExprNode::Lit { value: Literal::Sym { value: key } } = &*idx.node else {
        return None;
    };
    // Build `context.params.<key>` as three chained Sends — emit_expr
    // renders this as `context.params.<key>` via the Ruby-reader path.
    let span = expr.span;
    let context = Expr::new(
        span,
        ExprNode::Send {
            recv: None,
            method: crate::ident::Symbol::from("context"),
            args: vec![],
            block: None,
            parenthesized: false,
        },
    );
    let params = Expr::new(
        span,
        ExprNode::Send {
            recv: Some(context),
            method: crate::ident::Symbol::from("params"),
            args: vec![],
            block: None,
            parenthesized: false,
        },
    );
    Some(Expr::new(
        span,
        ExprNode::Send {
            recv: Some(params),
            method: key.clone(),
            args: vec![],
            block: None,
            parenthesized: false,
        },
    ))
}

// Routes ---------------------------------------------------------------

fn emit_routes(app: &App) -> EmittedFile {
    let mut s = String::new();
    writeln!(s, "// Generated by Roundhouse.").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "export interface Route {{").unwrap();
    writeln!(s, "  method: string;").unwrap();
    writeln!(s, "  path: string;").unwrap();
    writeln!(s, "  controller: string;").unwrap();
    writeln!(s, "  action: string;").unwrap();
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "export const routes: Route[] = [").unwrap();
    let mut flat: Vec<(String, String, String, String)> = Vec::new();
    for entry in &app.routes.entries {
        collect_flat_routes(entry, &mut flat, None);
    }
    for (method, path, controller, action) in flat {
        writeln!(
            s,
            "  {{ method: {:?}, path: {:?}, controller: {:?}, action: {:?} }},",
            method, path, controller, action,
        )
        .unwrap();
    }
    writeln!(s, "];").unwrap();
    EmittedFile { path: PathBuf::from("src/routes.ts"), content: s }
}

/// Flatten `RouteSpec` entries into concrete route records for the
/// dispatch table. `resources :name` expands into the 7 standard
/// actions (or the subset permitted by `only` / `except`). Nested
/// resources inherit a scope prefix.
fn collect_flat_routes(
    spec: &RouteSpec,
    out: &mut Vec<(String, String, String, String)>,
    scope_prefix: Option<(&str, &str)>,
) {
    match spec {
        RouteSpec::Explicit { method, path, controller, action, .. } => {
            let verb = match method {
                crate::dialect::HttpMethod::Get => "GET",
                crate::dialect::HttpMethod::Post => "POST",
                crate::dialect::HttpMethod::Put => "PUT",
                crate::dialect::HttpMethod::Patch => "PATCH",
                crate::dialect::HttpMethod::Delete => "DELETE",
                crate::dialect::HttpMethod::Head => "HEAD",
                crate::dialect::HttpMethod::Options => "OPTIONS",
                crate::dialect::HttpMethod::Any => "ANY",
            };
            let full_path = match scope_prefix {
                Some((parent, _)) => format!("/{parent}/:{parent}_id{path}"),
                None => path.clone(),
            };
            out.push((
                verb.to_string(),
                full_path,
                controller.0.to_string(),
                action.to_string(),
            ));
        }
        RouteSpec::Root { target } => {
            if let Some((c, a)) = target.split_once('#') {
                out.push((
                    "GET".into(),
                    "/".into(),
                    controller_class_name(c),
                    a.to_string(),
                ));
            }
        }
        RouteSpec::Resources { name, only, except, nested } => {
            let resource_path = format!("/{name}");
            let controller = controller_class_name(name.as_str());
            for (action, verb, suffix) in standard_resource_actions() {
                let action = *action;
                let verb = *verb;
                let suffix = *suffix;
                if !only.is_empty() && !only.iter().any(|s| s.as_str() == action) {
                    continue;
                }
                if except.iter().any(|s| s.as_str() == action) {
                    continue;
                }
                let path = format!("{resource_path}{suffix}");
                let full_path = match scope_prefix {
                    Some((parent, _)) => {
                        format!("/{parent}/:{parent}_id{path}")
                    }
                    None => path,
                };
                out.push((verb.into(), full_path, controller.clone(), action.into()));
            }
            // Nested resources scope under this resource's singular name.
            let singular =
                crate::naming::singularize_camelize(name.as_str()).to_lowercase();
            for child in nested {
                collect_flat_routes(child, out, Some((&singular, name.as_str())));
            }
        }
    }
}

/// The seven standard resource actions, in the order Rails conventionally
/// documents them: `(action_name, http_verb, path_suffix_after_resource)`.
fn standard_resource_actions() -> &'static [(&'static str, &'static str, &'static str)] {
    &[
        ("index", "GET", ""),
        ("new", "GET", "/new"),
        ("create", "POST", ""),
        ("show", "GET", "/:id"),
        ("edit", "GET", "/:id/edit"),
        ("update", "PATCH", "/:id"),
        ("destroy", "DELETE", "/:id"),
    ]
}

fn controller_class_name(short: &str) -> String {
    let mut s = crate::naming::camelize(short);
    s.push_str("Controller");
    s
}

// Body + expressions ---------------------------------------------------

fn emit_body(body: &Expr, return_ty: &Ty) -> String {
    let is_void = matches!(return_ty, Ty::Nil);
    match &*body.node {
        ExprNode::Assign { target: LValue::Ivar { .. }, value } => {
            if is_void {
                format!("{};", emit_expr(value))
            } else {
                format!("return {};", emit_expr(value))
            }
        }
        ExprNode::Seq { exprs } if !exprs.is_empty() => {
            let mut lines: Vec<String> = Vec::new();
            for (i, e) in exprs.iter().enumerate() {
                lines.push(emit_stmt(e, i == exprs.len() - 1, is_void));
            }
            lines.join("\n")
        }
        _ => {
            if is_void {
                format!("{};", emit_expr(body))
            } else {
                format!("return {};", emit_expr(body))
            }
        }
    }
}

fn emit_stmt(e: &Expr, is_last: bool, void_return: bool) -> String {
    match &*e.node {
        ExprNode::Assign { target: LValue::Var { name, .. }, value } => {
            format!("const {} = {};", name, emit_expr(value))
        }
        ExprNode::Assign { target: LValue::Ivar { name }, value } => {
            format!("this.{} = {};", ts_field_name(name.as_str()), emit_expr(value))
        }
        _ => {
            if is_last && !void_return {
                format!("return {};", emit_expr(e))
            } else {
                format!("{};", emit_expr(e))
            }
        }
    }
}

fn emit_expr(e: &Expr) -> String {
    match &*e.node {
        ExprNode::Lit { value } => emit_literal(value),
        ExprNode::Const { path } => {
            path.iter().map(|s| s.to_string()).collect::<Vec<_>>().join(".")
        }
        ExprNode::Var { name, .. } => name.to_string(),
        ExprNode::Ivar { name } => format!("this.{}", ts_field_name(name.as_str())),
        ExprNode::Send { recv, method, args, parenthesized, .. } => {
            emit_send_with_parens(recv.as_ref(), method.as_str(), args, *parenthesized)
        }
        ExprNode::Assign { target: _, value } => emit_expr(value),
        ExprNode::Seq { exprs } => {
            exprs.iter().map(emit_expr).collect::<Vec<_>>().join("; ")
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            let cond_s = emit_expr(cond);
            let then_s = indent_lines(&emit_expr(then_branch), 1);
            let else_s = indent_lines(&emit_expr(else_branch), 1);
            format!("if ({cond_s}) {{\n{then_s}\n}} else {{\n{else_s}\n}}")
        }
        ExprNode::BoolOp { op, left, right, .. } => {
            use crate::expr::BoolOpKind;
            let op_s = match op {
                BoolOpKind::Or => "||",
                BoolOpKind::And => "&&",
            };
            format!("{} {} {}", emit_expr(left), op_s, emit_expr(right))
        }
        ExprNode::Array { elements, .. } => {
            let parts: Vec<String> = elements.iter().map(emit_expr).collect();
            format!("[{}]", parts.join(", "))
        }
        ExprNode::Hash { entries, .. } => {
            let parts: Vec<String> = entries
                .iter()
                .map(|(k, v)| format!("{}: {}", emit_expr(k), emit_expr(v)))
                .collect();
            format!("{{ {} }}", parts.join(", "))
        }
        ExprNode::StringInterp { parts } => {
            use crate::expr::InterpPart;
            let mut out = String::from("`");
            for p in parts {
                match p {
                    InterpPart::Text { value } => {
                        for c in value.chars() {
                            if c == '`' || c == '\\' {
                                out.push('\\');
                                out.push(c);
                            } else if c == '$' {
                                out.push_str("\\$");
                            } else {
                                out.push(c);
                            }
                        }
                    }
                    InterpPart::Expr { expr } => {
                        out.push_str("${");
                        out.push_str(&emit_expr(expr));
                        out.push('}');
                    }
                }
            }
            out.push('`');
            out
        }
        other => format!("/* TODO: emit {:?} */", std::mem::discriminant(other)),
    }
}

/// Core send emission. `parenthesized` reflects whether the Ruby
/// source wrapped args in explicit parens — for 0-arg explicit-
/// receiver calls we use it to decide between `recv.name` (Ruby
/// reader convention, JS property access) and `recv.name()` (method
/// call). Always emits parens when args are present.
fn emit_send_with_parens(
    recv: Option<&Expr>,
    method: &str,
    args: &[Expr],
    parenthesized: bool,
) -> String {
    let args_s: Vec<String> = args.iter().map(emit_expr).collect();
    if method == "[]" && recv.is_some() {
        return format!("{}[{}]", emit_expr(recv.unwrap()), args_s.join(", "));
    }
    let ts_m = ts_method_name(method);
    match recv {
        None => {
            if args_s.is_empty() {
                ts_m
            } else {
                format!("{}({})", ts_m, args_s.join(", "))
            }
        }
        Some(r) => {
            let recv_s = emit_expr(r);
            if args_s.is_empty() && !parenthesized {
                // Ruby's `obj.name` without parens is typically a
                // reader; Juntos mirrors that with a property
                // accessor / getter, so emit without parens.
                format!("{recv_s}.{ts_m}")
            } else {
                format!("{recv_s}.{ts_m}({})", args_s.join(", "))
            }
        }
    }
}

fn emit_literal(lit: &Literal) -> String {
    match lit {
        Literal::Nil => "null".to_string(),
        Literal::Bool { value } => value.to_string(),
        Literal::Int { value } => value.to_string(),
        Literal::Float { value } => {
            let s = value.to_string();
            if s.contains('.') { s } else { format!("{s}.0") }
        }
        Literal::Str { value } => format!("{value:?}"),
        // Ruby symbols map to string literals — the typed analyzer may
        // refine this into a discriminated-union enum later, but for
        // the scaffold a string is unambiguous and round-trips through
        // comparison as expected.
        Literal::Sym { value } => format!("{:?}", value.as_str()),
    }
}

fn indent_lines(text: &str, depth: usize) -> String {
    let pad = "  ".repeat(depth);
    text.lines()
        .map(|l| format!("{pad}{l}"))
        .collect::<Vec<_>>()
        .join("\n")
}

// Types ----------------------------------------------------------------

pub fn ts_ty(ty: &Ty) -> String {
    match ty {
        Ty::Int | Ty::Float => "number".to_string(),
        Ty::Bool => "boolean".to_string(),
        // Symbols model as string for now. When a pass identifies a
        // closed set of symbols at a given position (enum detection),
        // emit it as a union-of-string-literals instead.
        Ty::Str | Ty::Sym => "string".to_string(),
        Ty::Nil => "null".to_string(),
        Ty::Array { elem } => format!("{}[]", ts_ty(elem)),
        Ty::Hash { key, value } => {
            format!("Record<{}, {}>", ts_ty(key), ts_ty(value))
        }
        Ty::Tuple { elems } => {
            let parts: Vec<String> = elems.iter().map(ts_ty).collect();
            format!("[{}]", parts.join(", "))
        }
        Ty::Record { .. } => "Record<string, unknown>".to_string(),
        Ty::Union { variants } => {
            let parts: Vec<String> = variants.iter().map(ts_ty).collect();
            parts.join(" | ")
        }
        Ty::Class { id, .. } => id.0.to_string(),
        Ty::Fn { .. } => "(...args: unknown[]) => unknown".to_string(),
        Ty::Var { .. } => "unknown".to_string(),
    }
}

// Naming ---------------------------------------------------------------

/// Instance-field name: preserves snake_case. Juntos's ActiveRecord
/// accessors match the Rails column names exactly (`article_id`, not
/// `articleId`), and ruby2js's rails model filter does the same.
/// Single-word idiomatic JS (`title`) is the same either way; the
/// difference is only visible on multi-word names.
fn ts_field_name(ruby_name: &str) -> String {
    ruby_name.to_string()
}

/// Method name: same snake_case preservation as fields. Method calls
/// that should resolve to JS-native APIs (e.g. `findBy` vs Ruby's
/// `find_by`) will need a per-method translation table later; until
/// then, the Rails-side name survives and Juntos maps at runtime.
fn ts_method_name(ruby_name: &str) -> String {
    ruby_name.to_string()
}
