//! `rust2` library/module emit — `LibraryClass` consumer +
//! Module-mode entry points.
//!
//! Phase 2.1 scope: Module-mode `emit_module` for free-function
//! runtime files (inflector). Library-mode `emit_library_class`
//! comes in Phase 2.2 (HWIA) when struct + impl emit lands.

use std::fmt::Write;

use super::method::emit_module_method;
use crate::dialect::{LibraryClass, MethodDef};
use crate::expr::Expr;

/// Module mode — flat list of `def self.*` helpers (e.g.
/// `inflector.rb`'s `Inflector.pluralize`). Each method emits as a
/// top-level `pub fn`. The output file IS the namespace at the
/// Rust module level (`src/inflector.rs` → `crate::inflector`); no
/// extra `mod NAME { ... }` wrapper needed.
///
/// Mirrors `crystal::emit_module` in role; differs in that crystal
/// requires explicit `module X ... end` wrapping while rust uses
/// the file-as-module convention.
pub fn emit_module(methods: &[MethodDef]) -> Result<String, String> {
    if methods.is_empty() {
        return Ok(String::new());
    }
    let mut out = String::new();
    writeln!(out, "// Generated by Roundhouse (rust2).").unwrap();
    writeln!(out).unwrap();
    let mut first = true;
    for m in methods {
        if !first {
            writeln!(out).unwrap();
        }
        first = false;
        out.push_str(&emit_module_method(m)?);
    }
    Ok(out)
}

/// Library mode — class declarations. Phase 2.2 stub; populated when
/// HWIA lands.
pub fn emit_library_class(_class: &LibraryClass) -> Result<String, String> {
    Err("rust2::emit_library_class: not yet implemented (Phase 2.2)".to_string())
}

/// Top-level constant declaration. Crystal: `NAME = VALUE`. TS:
/// `const NAME = VALUE;`. Rust: `pub const NAME: T = VALUE;` — but
/// the type and value rendering depends on the expression. Phase
/// 2.1 stub returns a TODO; runtime files that use module-level
/// constants land in Phase 2.9 (view_helpers).
pub fn format_constant(name: &str, value: &str) -> String {
    format!("// TODO rust2 const: pub const {name}: _ = {value};")
}

/// Expression emit for runtime-side constant value rendering.
/// Phase 2.1 stub; constants land in Phase 2.9 (view_helpers
/// HTML_ESCAPES).
pub fn emit_expr_for_runtime(_e: &Expr) -> String {
    "/* TODO rust2: emit_expr_for_runtime */".to_string()
}
