//! `rust2` library/module emit — `LibraryClass` consumer +
//! Module-mode entry points.
//!
//! Phase 2.1 scope: Module-mode `emit_module` for free-function
//! runtime files (inflector). Library-mode `emit_library_class`
//! comes in Phase 2.2 (HWIA) when struct + impl emit lands.

use std::fmt::Write;

use super::method::{emit_instance_method, emit_module_method};
use super::ty::rust_ty;
use crate::dialect::{LibraryClass, MethodDef, MethodReceiver};
use crate::expr::{Expr, ExprNode, LValue};
use crate::ty::Ty;

/// Module mode — flat list of `def self.*` helpers (e.g.
/// `inflector.rb`'s `Inflector.pluralize`). Each method emits as a
/// top-level `pub fn`. The output file IS the namespace at the
/// Rust module level (`src/inflector.rs` → `crate::inflector`); no
/// extra `mod NAME { ... }` wrapper needed.
///
/// Mirrors `crystal::emit_module` in role; differs in that crystal
/// requires explicit `module X ... end` wrapping while rust uses
/// the file-as-module convention.
pub fn emit_module(methods: &[MethodDef]) -> Result<String, String> {
    if methods.is_empty() {
        return Ok(String::new());
    }
    let mut out = String::new();
    writeln!(out, "// Generated by Roundhouse (rust2).").unwrap();
    writeln!(out).unwrap();
    let mut first = true;
    for m in methods {
        if !first {
            writeln!(out).unwrap();
        }
        first = false;
        out.push_str(&emit_module_method(m)?);
    }
    Ok(out)
}

/// Library mode — `class Foo ... end` → `pub struct Foo { ... }` +
/// `impl Foo { ... }`. Phase 2.2 lands the scaffold:
///
/// * Ivars are collected from method bodies and emitted as private
///   struct fields. Type comes from each ivar's first observed
///   assignment in the analyzed IR (the body-typer fills `e.ty`);
///   untyped ivars fall back to `serde_json::Value` via `rust_ty`.
/// * Each instance method emits as `pub fn name(&self, ...)` or
///   `pub fn name(&mut self, ...)`. The mutability heuristic walks
///   the body for `@ivar = ...` (LValue::Ivar) or `self[k] = v`
///   (LValue::Index recv=SelfRef) and picks `&mut self` if it sees
///   either.
/// * `def initialize` becomes `pub fn new(...) -> Self`; the
///   construction body is the user's `initialize` body with a final
///   `Self { fields }` return expression.
///
/// Subsequent commits drive the per-ExprNode body emit until the
/// produced Rust is `cargo check`-clean.
pub fn emit_library_class(class: &LibraryClass) -> Result<String, String> {
    // Strip the namespace prefix (`ActiveSupport::HashWithIndifferentAccess`
    // → `HashWithIndifferentAccess`). Rust uses file-as-module, so the
    // namespace is carried by the file path, not the struct name.
    let name = class
        .name
        .0
        .as_str()
        .rsplit("::")
        .next()
        .unwrap_or(class.name.0.as_str())
        .to_string();

    let ivars = collect_ivar_types(&class.methods);

    // Pre-pass: identify methods whose body never reads `self` or
    // any `@ivar`. Those are static-safe — emit as `pub fn name(...)`
    // (no `self` receiver) so they're callable from `new` before an
    // instance exists. HWIA's `normalize_value` is the canonical
    // case: pure value-transformation, no instance state. The
    // companion call-site rewrite in `expr.rs::emit_send` routes
    // `self.method(args)` for these methods to `Self::method(args)`.
    let static_method_names: std::collections::HashSet<String> = class
        .methods
        .iter()
        .filter(|m| {
            matches!(m.receiver, MethodReceiver::Instance)
                && m.name.as_str() != "initialize"
                && !method_reads_self(&m.body)
        })
        .map(|m| m.name.as_str().to_string())
        .collect();

    let mut out = String::new();

    // Struct declaration.
    writeln!(out, "pub struct {name} {{").unwrap();
    for (fname, ty) in &ivars {
        writeln!(out, "    {fname}: {},", rust_ty(ty)).unwrap();
    }
    out.push_str("}\n\n");

    // Impl block. Each method renders independently; `initialize`
    // routes through the constructor variant of `emit_instance_method`.
    // `def self.X` class methods emit as `pub fn name(...)` (no
    // receiver) — Rust's free-function-in-impl form. Callers reach
    // them via `Type::name(...)`, same dispatch path static-safe
    // instance methods use.
    writeln!(out, "impl {name} {{").unwrap();
    let mut first = true;
    // Make this class's ivar → field-type table available to
    // `emit_assign` (via thread-local) so RHS values can be coerced
    // when their Ty doesn't match the declared field type — most
    // commonly `self.body = ""` where field is `String` and `""` is
    // `&str`. Empty outside class-body scope; scoped per-class to
    // prevent bleeding between siblings.
    let ivar_type_map: std::collections::HashMap<String, Ty> =
        ivars.iter().cloned().collect();
    let body_result = super::expr::with_ivar_types(ivar_type_map, || super::expr::with_static_methods(static_method_names.clone(), || {
        for m in &class.methods {
            if matches!(m.name.as_str(), "[]" | "[]=") {
                continue;
            }
            if !first {
                writeln!(out).unwrap();
            }
            first = false;
            let body = match m.receiver {
                MethodReceiver::Class => {
                    // `def self.X` → `pub fn X(...)` with no receiver.
                    // Module-style call from within the impl block.
                    super::method::emit_module_method(m)?
                }
                MethodReceiver::Instance => {
                    let is_static = static_method_names.contains(m.name.as_str());
                    let mutates = method_mutates_self(&m.body);
                    emit_instance_method(m, mutates, is_static, &name, &ivars)?
                }
            };
            for line in body.lines() {
                if line.is_empty() {
                    writeln!(out).unwrap();
                } else {
                    writeln!(out, "    {line}").unwrap();
                }
            }
        }
        Ok::<(), String>(())
    }));
    body_result?;
    out.push_str("}\n");
    Ok(out)
}

/// Static-method probe: returns `true` when the method body
/// references `self` (any `Ivar` read/write or `SelfRef` use). The
/// pre-pass in `emit_library_class` filters this down to methods
/// that can be lifted to `pub fn name(...)` (no `&self`).
fn method_reads_self(body: &Expr) -> bool {
    fn walk(e: &Expr) -> bool {
        match &*e.node {
            ExprNode::SelfRef | ExprNode::Ivar { .. } => true,
            ExprNode::Assign { target, value } => {
                if matches!(target, LValue::Ivar { .. }) {
                    return true;
                }
                if let LValue::Attr { recv, .. } | LValue::Index { recv, .. } = target {
                    if walk(recv) { return true; }
                }
                walk(value)
            }
            ExprNode::Seq { exprs } => exprs.iter().any(walk),
            ExprNode::If { cond, then_branch, else_branch } => {
                walk(cond) || walk(then_branch) || walk(else_branch)
            }
            ExprNode::While { cond, body, .. } => walk(cond) || walk(body),
            ExprNode::Send { recv, args, block, .. } => {
                recv.as_ref().map(|r| walk(r)).unwrap_or(false)
                    || args.iter().any(walk)
                    || block.as_ref().map(|b| walk(b)).unwrap_or(false)
            }
            ExprNode::Return { value } => walk(value),
            ExprNode::StringInterp { parts } => parts.iter().any(|p| {
                if let crate::expr::InterpPart::Expr { expr } = p { walk(expr) } else { false }
            }),
            ExprNode::Hash { entries, .. } => entries.iter().any(|(k, v)| walk(k) || walk(v)),
            ExprNode::Array { elements, .. } => elements.iter().any(walk),
            _ => false,
        }
    }
    walk(body)
}

/// Walk all methods collecting `@ivar = …` assignments. Returns the
/// observed ivar set with each entry's inferred type (the analyzer
/// fills `Expr.ty` during typing; an unset `ty` falls back to
/// `Ty::Untyped` and renders as `serde_json::Value`).
fn collect_ivar_types(methods: &[MethodDef]) -> Vec<(String, Ty)> {
    // Phase 1: walk every method body and record every Ty observed
    // assigning to each ivar — both direct `@x =` (Ivar lvalue) and
    // `self.x = ...` (Attr lvalue with SelfRef recv, which writes the
    // same backing field on the emitted struct). Preserve first-seen
    // order so the struct's field declaration order matches the
    // source's `def initialize` order.
    let mut order: Vec<String> = Vec::new();
    let mut observed: std::collections::HashMap<String, Vec<Ty>> =
        std::collections::HashMap::new();
    for m in methods {
        walk_collect_ivars(&m.body, &mut order, &mut observed);
    }
    // Phase 2: unify each ivar's observed-type list into one Ty.
    // Rules:
    //   - {Nil, T, ...}            → Option<T> (T = first non-Nil)
    //   - {Nil}                    → Option<Untyped> (nil-only ivar,
    //                                widen to Option for setter shape)
    //   - {Hash<_,_>, Hash<K, V>}  → keep the widest (matches the
    //                                previous one-shot widening for
    //                                empty-literal seeded hashes)
    //   - {T}                      → T (single-type ivar)
    //   - {T1, T2, ...} mixed      → first observed (fallback)
    order
        .into_iter()
        .map(|name| {
            let tys = observed.remove(&name).unwrap_or_default();
            let unified = unify_ivar_tys(&tys);
            (name, unified)
        })
        .collect()
}

fn unify_ivar_tys(tys: &[Ty]) -> Ty {
    let has_nil = tys.iter().any(|t| matches!(t, Ty::Nil));
    let first_non_nil = tys.iter().find(|t| !matches!(t, Ty::Nil)).cloned();
    if has_nil {
        match first_non_nil {
            Some(t) => Ty::Union {
                variants: vec![Ty::Nil, t],
            },
            // Nil-only ivar (e.g. `@location = nil` with no other
            // assignments visible in the class body) — widen to
            // Option<Untyped> so the setter side can assign any
            // value-typed payload without an E0308. Without widening
            // the field types as `()` and every other path fails.
            None => Ty::Union {
                variants: vec![Ty::Nil, Ty::Untyped],
            },
        }
    } else {
        // No Nil observed — pick the most informative concrete type.
        // For Hash, prefer the most-specified variant (Hash{K, V} with
        // concrete K/V over Hash{Untyped, Untyped}) — matches the
        // previous single-shot widening.
        tys.iter()
            .max_by_key(|t| match t {
                Ty::Hash { key, value } => {
                    let k = !matches!(**key, Ty::Untyped);
                    let v = !matches!(**value, Ty::Untyped);
                    (k as u8) + (v as u8)
                }
                _ => 0,
            })
            .cloned()
            .unwrap_or(Ty::Untyped)
    }
}

fn walk_collect_ivars(
    e: &Expr,
    order: &mut Vec<String>,
    observed: &mut std::collections::HashMap<String, Vec<Ty>>,
) {
    fn record(
        name: &str,
        ty: Ty,
        order: &mut Vec<String>,
        observed: &mut std::collections::HashMap<String, Vec<Ty>>,
    ) {
        let k = name.to_string();
        if !order.iter().any(|n| n == &k) {
            order.push(k.clone());
        }
        observed.entry(k).or_default().push(ty);
    }
    match &*e.node {
        ExprNode::Assign { target: LValue::Ivar { name }, value } => {
            let ty = value.ty.clone().unwrap_or(Ty::Untyped);
            record(name.as_str(), ty, order, observed);
            walk_collect_ivars(value, order, observed);
        }
        // `self.x = value` — Attr lvalue with SelfRef recv. Writes
        // the same backing field as `@x = value`. Without this, an
        // ivar assigned only as `@x = nil` in `initialize` and then
        // `self.x = path` in `redirect_to` would type as `()`,
        // mismatching every `self.x = path` site.
        ExprNode::Assign {
            target: LValue::Attr { recv, name },
            value,
        } if matches!(&*recv.node, ExprNode::SelfRef) => {
            let ty = value.ty.clone().unwrap_or(Ty::Untyped);
            record(name.as_str(), ty, order, observed);
            walk_collect_ivars(value, order, observed);
        }
        // `@ivar[k] = v` — Ruby parses as Send `[]=` on Ivar recv.
        // The empty-literal `@data = {}` types as `Hash<Untyped,
        // Untyped>` from analyzer inference; subsequent index-assigns
        // tell us the real key/value types. Only record a Hash
        // observation when the ivar's prior observations already
        // contain a Hash — otherwise `@flash[:notice] = "..."` (where
        // `@flash` is the typed `Flash` struct, not a HashMap) would
        // be misread as a Hash assignment and widen the ivar type
        // away from the concrete struct.
        ExprNode::Send { recv: Some(recv), method, args, .. }
            if method.as_str() == "[]=" && args.len() == 2 =>
        {
            if let ExprNode::Ivar { name } = &*recv.node {
                let key = name.as_str();
                let already_hash = observed
                    .get(key)
                    .map(|tys| tys.iter().any(|t| matches!(t, Ty::Hash { .. })))
                    .unwrap_or(false);
                if already_hash {
                    let k_ty = args[0].ty.clone().unwrap_or(Ty::Untyped);
                    let v_ty = args[1].ty.clone().unwrap_or(Ty::Untyped);
                    record(
                        key,
                        Ty::Hash {
                            key: Box::new(k_ty),
                            value: Box::new(v_ty),
                        },
                        order,
                        observed,
                    );
                }
            }
            walk_collect_ivars(recv, order, observed);
            args.iter().for_each(|a| walk_collect_ivars(a, order, observed));
        }
        ExprNode::Seq { exprs } => {
            exprs.iter().for_each(|e| walk_collect_ivars(e, order, observed))
        }
        ExprNode::If { cond, then_branch, else_branch } => {
            walk_collect_ivars(cond, order, observed);
            walk_collect_ivars(then_branch, order, observed);
            walk_collect_ivars(else_branch, order, observed);
        }
        ExprNode::Send { recv, args, block, .. } => {
            if let Some(r) = recv { walk_collect_ivars(r, order, observed); }
            args.iter().for_each(|a| walk_collect_ivars(a, order, observed));
            if let Some(b) = block { walk_collect_ivars(b, order, observed); }
        }
        ExprNode::While { cond, body, .. } => {
            walk_collect_ivars(cond, order, observed);
            walk_collect_ivars(body, order, observed);
        }
        ExprNode::Return { value } => walk_collect_ivars(value, order, observed),
        _ => {}
    }
}

/// Receiver-kind heuristic: returns `true` when the method body
/// contains any write to instance state (`@ivar = …`, `self[k] = v`,
/// `self.attr = v`). Lands as Phase 2.2's first design choice; if the
/// heuristic misclassifies in practice the lifting path is the
/// [self-describing IR](feedback_self_describing_ir) pattern — add a
/// `mutates_self` flag to `MethodDef` and let lowerers fill it.
fn method_mutates_self(body: &Expr) -> bool {
    fn walk(e: &Expr) -> bool {
        match &*e.node {
            ExprNode::Assign { target, .. } => match target {
                LValue::Ivar { .. } => true,
                LValue::Attr { recv, .. } | LValue::Index { recv, .. } => {
                    matches!(&*recv.node, ExprNode::SelfRef | ExprNode::Ivar { .. })
                        || walk(recv)
                }
                LValue::Var { .. } => false,
            },
            // `self[k] = v` and `self.foo = v` lower as `Send`s to
            // `[]=` / setter-suffixed methods, not Assign. Same for
            // `@data[k] = v` — direct ivar mutation via index assign
            // (HWIA `set` / `delete`). Treat all of these as mutation.
            ExprNode::Send { recv: Some(recv), method, .. }
                if matches!(&*recv.node, ExprNode::SelfRef | ExprNode::Ivar { .. })
                    && (method.as_str() == "[]=" || method.as_str().ends_with('='))
                    && !is_comparison_method(method.as_str()) =>
            {
                true
            }
            ExprNode::Seq { exprs } => exprs.iter().any(walk),
            ExprNode::If { cond, then_branch, else_branch } => {
                walk(cond) || walk(then_branch) || walk(else_branch)
            }
            ExprNode::While { cond, body, .. } => walk(cond) || walk(body),
            ExprNode::Send { recv, args, block, .. } => {
                recv.as_ref().map(|r| walk(r)).unwrap_or(false)
                    || args.iter().any(walk)
                    || block.as_ref().map(|b| walk(b)).unwrap_or(false)
            }
            ExprNode::Return { value } => walk(value),
            _ => false,
        }
    }
    walk(body)
}

/// Trailing-`=` filter: `==`, `!=`, `<=`, `>=` end with `=` but are
/// comparison sends, not setters. The setter heuristic above needs
/// to exclude them.
fn is_comparison_method(m: &str) -> bool {
    matches!(m, "==" | "!=" | "<=" | ">=" | "<=>" | "===" | "=~")
}

/// Top-level constant declaration. Crystal: `NAME = VALUE`. TS:
/// `const NAME = VALUE;`. Rust: `pub const NAME: T = VALUE;` — but
/// the type and value rendering depends on the expression. Phase
/// 2.1 stub returns a TODO; runtime files that use module-level
/// constants land in Phase 2.9 (view_helpers).
pub fn format_constant(name: &str, value: &str) -> String {
    format!("// TODO rust2 const: pub const {name}: _ = {value};")
}

/// Expression emit for runtime-side constant value rendering.
/// Phase 2.1 stub; constants land in Phase 2.9 (view_helpers
/// HTML_ESCAPES).
pub fn emit_expr_for_runtime(_e: &Expr) -> String {
    "/* TODO rust2: emit_expr_for_runtime */".to_string()
}
